# Data Collection

This notebook goes through the steps taken to web scrape financial documents and data from JSE and BSE's websites. It also goes through the steps taken for direct text extraction and Cloud OCR.

**Note that you will need to apply for your own Cloud OCR key, it is free and can be accessed from https://ocr.space/ocrapi/freekey.

## JSE (Jamaica Stock Exchange) Data Scraper

In [1]:
# Import the required packages
import io
import json
import logging
import time
from datetime import date, timedelta
from pathlib import Path
from typing import Optional
import pandas as pd
import pdfplumber
import requests
from bs4 import BeautifulSoup

# Set the configurations for JSE scraping
BASE_URL = "https://www.jamstockex.com"
WP_API_POSTS = f"{BASE_URL}/wp-json/wp/v2/posts"
NEWSROOM_URL = f"{BASE_URL}/newsroom/"
DAILY_QUOTE_PDF_URL = f"{BASE_URL}/trading/trade-quotes/daily-quote-pdf/"
REQUEST_DELAY_SECONDS = 1.5
TIMEOUT = 20

logging.basicConfig(
    level = logging.INFO,
    format = "%(asctime)s [%(levelname)s] %(message)s",)

log = logging.getLogger("jse_scraper")

# Create the JSE session header
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.jamstockex.com/",})

In [2]:
# Define a function to clean the scraped text
def clean_html_to_text(html: str) -> str:
    """Strip HTML tags/scripts and collapse whitespace into plain text."""
    soup = BeautifulSoup(html or "", "html.parser")
    for tag in soup(["script", "style"]):
        tag.decompose()
    text = soup.get_text(separator=" ")
    return " ".join(text.split())

In [3]:
# Define function to retrieve data from the WordPress API
def try_wp_api(max_pages: int, after_date: str = None) -> list:
    
    records = []
    page = 1
    per_page = 20
    base_params = {"per_page": per_page, "_embed": "true"}
    if after_date:
        base_params["after"] = f"{after_date}T00:00:00"

    # Lightweight probe request to check the API even responds.
    try:
        probe = session.get(WP_API_POSTS, params = {**base_params, "per_page": 1, "page": 1}, timeout = TIMEOUT)
    except requests.RequestException as e:
        log.warning("WP API probe failed (network error): %s", e)
        return []

    if probe.status_code != 200:
        log.warning("WP API probe returned status %s -- will use HTML fallback.", probe.status_code)
        return []

    try:
        probe.json()
    except ValueError:
        log.warning("WP API probe did not return JSON -- will use HTML fallback.")
        return []

    total_posts = probe.headers.get("X-WP-Total")
    log.info("WP API is reachable. Total posts matching filter: %s", total_posts)

    while page <= max_pages:
        params = {**base_params, "page": page}
        try:
            resp = session.get(WP_API_POSTS, params=params, timeout=TIMEOUT)
        except requests.RequestException as e:
            log.warning("Request error on API page %s: %s", page, e)
            break

        if resp.status_code == 400:
            log.info("Reached end of available pages at page %s.", page)
            break
        if resp.status_code != 200:
            log.warning("API page %s returned status %s -- stopping API pull.", page, resp.status_code)
            break

        posts = resp.json()
        if not posts:
            break

        for post in posts:
            title = clean_html_to_text(post.get("title", {}).get("rendered", ""))
            body = clean_html_to_text(post.get("content", {}).get("rendered", ""))
            categories = []
            embedded = post.get("_embedded", {})
            for term_group in embedded.get("wp:term", []):
                for term in term_group:
                    if term.get("taxonomy") in ("category", "post_tag"):
                        categories.append(term.get("name"))

            records.append({
                "id": f"wp-{post.get('id')}",
                "source": "jse",
                "title": title,
                "date": post.get("date"),
                "url": post.get("link"),
                "categories": categories,
                "text": body,
                "retrieved_via": "wp_api",
            })

        log.info("API page %s: collected %s posts (running total: %s)", page, len(posts), len(records))
        page += 1
        time.sleep(REQUEST_DELAY_SECONDS)

    return records

In [4]:
# Define a function to scrape the HTML if the API scraping fails
def scrape_article(url: str) -> Optional[dict]:
  
    try:
        resp = session.get(url, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to fetch article %s: %s", url, e)
        return None

    if resp.status_code != 200:
        log.warning("Article %s returned status %s.", url, resp.status_code)
        return None

    soup = BeautifulSoup(resp.text, "html.parser")

    title_tag = soup.find(["h1", "h2"], class_=lambda c: c and "title" in c.lower()) or soup.find("h1")
    title = title_tag.get_text(strip=True) if title_tag else url

    body_tag = (
        soup.find("div", class_=lambda c: c and "entry-content" in c.lower())
        or soup.find("article")
        or soup.find("main"))
    
    body_text = clean_html_to_text(str(body_tag)) if body_tag else clean_html_to_text(resp.text)

    date_tag = soup.find("time")
    date_val = date_tag.get("datetime") if date_tag and date_tag.get("datetime") else (
        date_tag.get_text(strip=True) if date_tag else None)

    return {
        "id": f"html-{abs(hash(url))}",
        "source": "jse",
        "title": title,
        "date": date_val,
        "url": url,
        "categories": [],
        "text": body_text,
        "retrieved_via": "html_fallback",}

# Define a function to failover to the HTML scraper if the API fails
def html_fallback_scrape(max_pages: int) -> list:
    
    records = []
    seen_urls = set()

    for page in range(1, max_pages + 1):
        listing_url = NEWSROOM_URL if page == 1 else f"{NEWSROOM_URL}page/{page}/"
        try:
            resp = session.get(listing_url, timeout = TIMEOUT)
        except requests.RequestException as e:
            log.warning("Failed to fetch listing page %s: %s", listing_url, e)
            break

        if resp.status_code == 404:
            log.info("No more listing pages (404 at page %s).", page)
            break
        if resp.status_code != 200:
            log.warning("Listing page %s returned status %s.", listing_url, resp.status_code)
            break

        soup = BeautifulSoup(resp.text, "html.parser")

        article_links = set()
        for a in soup.select("article a[href]"):
            href = a.get("href", "")
            if href.startswith(BASE_URL) and href not in seen_urls:
                article_links.add(href)

        if not article_links:
            for a in soup.select("a[href]"):
                href = a.get("href", "")
                if href.startswith(BASE_URL) and href.rstrip("/").count("/") >= 3:
                    article_links.add(href)

        if not article_links:
            log.info("No article links found on page %s -- stopping.", page)
            break

        log.info("Listing page %s: found %s candidate article links.", page, len(article_links))

        for url in article_links:
            if url in seen_urls:
                continue
            seen_urls.add(url)
            record = scrape_article(url)
            if record:
                records.append(record)
            time.sleep(REQUEST_DELAY_SECONDS)

        time.sleep(REQUEST_DELAY_SECONDS)

    return records

## JSE Financial Data Collection

In [6]:
# Set the cut off date (2 years) and max number of web pages to scrape
cutoff_date = (date.today() - timedelta(days = 365*2)).isoformat()
MAX_PAGES = 280 

# Scrape the website and save the number of records
records = try_wp_api(max_pages = MAX_PAGES, after_date = cutoff_date)

# If there are no records, return a message and try the HTML scraper
if not records:
    print("WP API returned nothing -- using HTML fallback.")
    records = html_fallback_scrape(max_pages = MAX_PAGES)

# Print the number of records collected
print(f"Total records collected: {len(records)}")

2026-08-16 21:28:55,488 [INFO] WP API is reachable. Total posts matching filter: 5531
2026-08-16 21:28:58,110 [INFO] API page 1: collected 20 posts (running total: 20)
2026-08-16 21:29:02,252 [INFO] API page 2: collected 20 posts (running total: 40)
2026-08-16 21:29:07,540 [INFO] API page 3: collected 20 posts (running total: 60)
2026-08-16 21:29:12,718 [INFO] API page 4: collected 20 posts (running total: 80)
2026-08-16 21:29:17,882 [INFO] API page 5: collected 20 posts (running total: 100)
2026-08-16 21:29:23,584 [INFO] API page 6: collected 20 posts (running total: 120)
2026-08-16 21:29:28,575 [INFO] API page 7: collected 20 posts (running total: 140)
2026-08-16 21:29:33,790 [INFO] API page 8: collected 20 posts (running total: 160)
2026-08-16 21:29:38,917 [INFO] API page 9: collected 20 posts (running total: 180)
2026-08-16 21:29:44,186 [INFO] API page 10: collected 20 posts (running total: 200)
2026-08-16 21:29:49,263 [INFO] API page 11: collected 20 posts (running total: 220)
2026-08-16 21:29:54,373 [INFO] API page 12: collected 20 posts (running total: 240)
2026-08-16 21:29:59,512 [INFO] API page 13: collected 20 posts (running total: 260)
2026-08-16 21:30:04,813 [INFO] API page 14: collected 20 posts (running total: 280)
2026-08-16 21:30:10,128 [INFO] API page 15: collected 20 posts (running total: 300)
2026-08-16 21:30:15,201 [INFO] API page 16: collected 20 posts (running total: 320)
2026-08-16 21:30:20,293 [INFO] API page 17: collected 20 posts (running total: 340)
2026-08-16 21:30:25,967 [INFO] API page 18: collected 20 posts (running total: 360)
2026-08-16 21:30:31,160 [INFO] API page 19: collected 20 posts (running total: 380)
2026-08-16 21:30:36,130 [INFO] API page 20: collected 20 posts (running total: 400)
2026-08-16 21:30:41,245 [INFO] API page 21: collected 20 posts (running total: 420)
2026-08-16 21:30:46,300 [INFO] API page 22: collected 20 posts (running total: 440)
2026-08-16 21:30:51,282 [INFO] API page 23: collected 20 posts (running total: 460)
2026-08-16 21:30:56,490 [INFO] API page 24: collected 20 posts (running total: 480)
2026-08-16 21:31:01,579 [INFO] API page 25: collected 20 posts (running total: 500)
2026-08-16 21:31:06,772 [INFO] API page 26: collected 20 posts (running total: 520)
2026-08-16 21:31:11,850 [INFO] API page 27: collected 20 posts (running total: 540)
2026-08-16 21:31:16,808 [INFO] API page 28: collected 20 posts (running total: 560)
2026-08-16 21:31:22,015 [INFO] API page 29: collected 20 posts (running total: 580)
2026-08-16 21:31:27,783 [INFO] API page 30: collected 20 posts (running total: 600)
2026-08-16 21:31:32,802 [INFO] API page 31: collected 20 posts (running total: 620)
2026-08-16 21:31:38,011 [INFO] API page 32: collected 20 posts (running total: 640)
2026-08-16 21:31:42,991 [INFO] API page 33: collected 20 posts (running total: 660)
2026-08-16 21:31:48,354 [INFO] API page 34: collected 20 posts (running total: 680)
2026-08-16 21:31:53,401 [INFO] API page 35: collected 20 posts (running total: 700)
2026-08-16 21:31:58,724 [INFO] API page 36: collected 20 posts (running total: 720)
2026-08-16 21:32:03,956 [INFO] API page 37: collected 20 posts (running total: 740)
2026-08-16 21:32:09,136 [INFO] API page 38: collected 20 posts (running total: 760)
2026-08-16 21:32:14,482 [INFO] API page 39: collected 20 posts (running total: 780)
2026-08-16 21:32:19,715 [INFO] API page 40: collected 20 posts (running total: 800)
2026-08-16 21:32:24,771 [INFO] API page 41: collected 20 posts (running total: 820)
2026-08-16 21:32:30,259 [INFO] API page 42: collected 20 posts (running total: 840)
2026-08-16 21:32:35,614 [INFO] API page 43: collected 20 posts (running total: 860)
2026-08-16 21:32:40,856 [INFO] API page 44: collected 20 posts (running total: 880)
2026-08-16 21:32:45,725 [INFO] API page 45: collected 20 posts (running total: 900)
2026-08-16 21:32:50,929 [INFO] API page 46: collected 20 posts (running total: 920)
2026-08-16 21:32:56,137 [INFO] API page 47: collected 20 posts (running total: 940)
2026-08-16 21:33:01,474 [INFO] API page 48: collected 20 posts (running total: 960)
2026-08-16 21:33:06,501 [INFO] API page 49: collected 20 posts (running total: 980)
2026-08-16 21:33:11,811 [INFO] API page 50: collected 20 posts (running total: 1000)
2026-08-16 21:33:16,836 [INFO] API page 51: collected 20 posts (running total: 1020)
2026-08-16 21:33:21,851 [INFO] API page 52: collected 20 posts (running total: 1040)
2026-08-16 21:33:27,301 [INFO] API page 53: collected 20 posts (running total: 1060)
2026-08-16 21:33:32,388 [INFO] API page 54: collected 20 posts (running total: 1080)
2026-08-16 21:33:37,473 [INFO] API page 55: collected 20 posts (running total: 1100)
2026-08-16 21:33:42,662 [INFO] API page 56: collected 20 posts (running total: 1120)
2026-08-16 21:33:48,056 [INFO] API page 57: collected 20 posts (running total: 1140)
2026-08-16 21:33:53,181 [INFO] API page 58: collected 20 posts (running total: 1160)
2026-08-16 21:33:58,419 [INFO] API page 59: collected 20 posts (running total: 1180)
2026-08-16 21:34:03,389 [INFO] API page 60: collected 20 posts (running total: 1200)
2026-08-16 21:34:08,559 [INFO] API page 61: collected 20 posts (running total: 1220)
2026-08-16 21:34:13,689 [INFO] API page 62: collected 20 posts (running total: 1240)
2026-08-16 21:34:18,823 [INFO] API page 63: collected 20 posts (running total: 1260)
2026-08-16 21:34:23,720 [INFO] API page 64: collected 20 posts (running total: 1280)
2026-08-16 21:34:29,096 [INFO] API page 65: collected 20 posts (running total: 1300)
2026-08-16 21:34:34,458 [INFO] API page 66: collected 20 posts (running total: 1320)
2026-08-16 21:34:39,510 [INFO] API page 67: collected 20 posts (running total: 1340)
2026-08-16 21:34:44,686 [INFO] API page 68: collected 20 posts (running total: 1360)
2026-08-16 21:34:49,633 [INFO] API page 69: collected 20 posts (running total: 1380)
2026-08-16 21:34:54,748 [INFO] API page 70: collected 20 posts (running total: 1400)
2026-08-16 21:34:59,817 [INFO] API page 71: collected 20 posts (running total: 1420)
2026-08-16 21:35:05,186 [INFO] API page 72: collected 20 posts (running total: 1440)
2026-08-16 21:35:10,268 [INFO] API page 73: collected 20 posts (running total: 1460)
2026-08-16 21:35:15,446 [INFO] API page 74: collected 20 posts (running total: 1480)
2026-08-16 21:35:20,708 [INFO] API page 75: collected 20 posts (running total: 1500)
2026-08-16 21:35:25,777 [INFO] API page 76: collected 20 posts (running total: 1520)
2026-08-16 21:35:31,103 [INFO] API page 77: collected 20 posts (running total: 1540)
2026-08-16 21:35:36,233 [INFO] API page 78: collected 20 posts (running total: 1560)
2026-08-16 21:35:41,252 [INFO] API page 79: collected 20 posts (running total: 1580)
2026-08-16 21:35:46,314 [INFO] API page 80: collected 20 posts (running total: 1600)
2026-08-16 21:35:51,674 [INFO] API page 81: collected 20 posts (running total: 1620)
2026-08-16 21:35:56,971 [INFO] API page 82: collected 20 posts (running total: 1640)
2026-08-16 21:36:02,064 [INFO] API page 83: collected 20 posts (running total: 1660)
2026-08-16 21:36:07,247 [INFO] API page 84: collected 20 posts (running total: 1680)
2026-08-16 21:36:12,414 [INFO] API page 85: collected 20 posts (running total: 1700)
2026-08-16 21:36:17,480 [INFO] API page 86: collected 20 posts (running total: 1720)
2026-08-16 21:36:22,448 [INFO] API page 87: collected 20 posts (running total: 1740)
2026-08-16 21:36:27,440 [INFO] API page 88: collected 20 posts (running total: 1760)
2026-08-16 21:36:32,549 [INFO] API page 89: collected 20 posts (running total: 1780)
2026-08-16 21:36:37,643 [INFO] API page 90: collected 20 posts (running total: 1800)
2026-08-16 21:36:42,755 [INFO] API page 91: collected 20 posts (running total: 1820)
2026-08-16 21:36:47,605 [INFO] API page 92: collected 20 posts (running total: 1840)
2026-08-16 21:36:52,769 [INFO] API page 93: collected 20 posts (running total: 1860)
2026-08-16 21:36:57,913 [INFO] API page 94: collected 20 posts (running total: 1880)
2026-08-16 21:37:03,074 [INFO] API page 95: collected 20 posts (running total: 1900)
2026-08-16 21:37:07,977 [INFO] API page 96: collected 20 posts (running total: 1920)
2026-08-16 21:37:13,062 [INFO] API page 97: collected 20 posts (running total: 1940)

2026-08-16 21:37:18,115 [INFO] API page 98: collected 20 posts (running total: 1960)
2026-08-16 21:37:23,290 [INFO] API page 99: collected 20 posts (running total: 1980)
2026-08-16 21:37:28,765 [INFO] API page 100: collected 20 posts (running total: 2000)
2026-08-16 21:37:33,690 [INFO] API page 101: collected 20 posts (running total: 2020)
2026-08-16 21:37:38,650 [INFO] API page 102: collected 20 posts (running total: 2040)
2026-08-16 21:37:43,618 [INFO] API page 103: collected 20 posts (running total: 2060)
2026-08-16 21:37:48,663 [INFO] API page 104: collected 20 posts (running total: 2080)
2026-08-16 21:37:53,852 [INFO] API page 105: collected 20 posts (running total: 2100)
2026-08-16 21:37:59,222 [INFO] API page 106: collected 20 posts (running total: 2120)
2026-08-16 21:38:04,309 [INFO] API page 107: collected 20 posts (running total: 2140)
2026-08-16 21:38:09,402 [INFO] API page 108: collected 20 posts (running total: 2160)
2026-08-16 21:38:14,446 [INFO] API page 109: collected 20 posts (running total: 2180)
2026-08-16 21:38:19,776 [INFO] API page 110: collected 20 posts (running total: 2200)
2026-08-16 21:38:25,060 [INFO] API page 111: collected 20 posts (running total: 2220)
2026-08-16 21:38:30,556 [INFO] API page 112: collected 20 posts (running total: 2240)
2026-08-16 21:38:35,613 [INFO] API page 113: collected 20 posts (running total: 2260)
2026-08-16 21:38:40,429 [INFO] API page 114: collected 20 posts (running total: 2280)
2026-08-16 21:38:45,405 [INFO] API page 115: collected 20 posts (running total: 2300)
2026-08-16 21:38:50,513 [INFO] API page 116: collected 20 posts (running total: 2320)
2026-08-16 21:38:55,599 [INFO] API page 117: collected 20 posts (running total: 2340)
2026-08-16 21:39:00,803 [INFO] API page 118: collected 20 posts (running total: 2360)
2026-08-16 21:39:05,872 [INFO] API page 119: collected 20 posts (running total: 2380)
2026-08-16 21:39:11,111 [INFO] API page 120: collected 20 posts (running total: 2400)
2026-08-16 21:39:16,289 [INFO] API page 121: collected 20 posts (running total: 2420)
2026-08-16 21:39:21,260 [INFO] API page 122: collected 20 posts (running total: 2440)
2026-08-16 21:39:26,437 [INFO] API page 123: collected 20 posts (running total: 2460)
2026-08-16 21:39:31,461 [INFO] API page 124: collected 20 posts (running total: 2480)
2026-08-16 21:39:36,516 [INFO] API page 125: collected 20 posts (running total: 2500)
2026-08-16 21:39:41,823 [INFO] API page 126: collected 20 posts (running total: 2520)
2026-08-16 21:39:46,925 [INFO] API page 127: collected 20 posts (running total: 2540)
2026-08-16 21:39:52,042 [INFO] API page 128: collected 20 posts (running total: 2560)
2026-08-16 21:39:57,100 [INFO] API page 129: collected 20 posts (running total: 2580)
2026-08-16 21:40:02,130 [INFO] API page 130: collected 20 posts (running total: 2600)
2026-08-16 21:40:07,392 [INFO] API page 131: collected 20 posts (running total: 2620)
2026-08-16 21:40:12,673 [INFO] API page 132: collected 20 posts (running total: 2640)
2026-08-16 21:40:18,500 [INFO] API page 133: collected 20 posts (running total: 2660)
2026-08-16 21:40:23,669 [INFO] API page 134: collected 20 posts (running total: 2680)
2026-08-16 21:40:28,702 [INFO] API page 135: collected 20 posts (running total: 2700)
2026-08-16 21:40:33,745 [INFO] API page 136: collected 20 posts (running total: 2720)
2026-08-16 21:40:39,067 [INFO] API page 137: collected 20 posts (running total: 2740)
2026-08-16 21:40:44,296 [INFO] API page 138: collected 20 posts (running total: 2760)
2026-08-16 21:40:49,522 [INFO] API page 139: collected 20 posts (running total: 2780)
2026-08-16 21:40:54,660 [INFO] API page 140: collected 20 posts (running total: 2800)
2026-08-16 21:40:59,848 [INFO] API page 141: collected 20 posts (running total: 2820)
2026-08-16 21:41:04,969 [INFO] API page 142: collected 20 posts (running total: 2840)
2026-08-16 21:41:10,199 [INFO] API page 143: collected 20 posts (running total: 2860)
2026-08-16 21:41:15,361 [INFO] API page 144: collected 20 posts (running total: 2880)
2026-08-16 21:41:20,466 [INFO] API page 145: collected 20 posts (running total: 2900)
2026-08-16 21:41:25,566 [INFO] API page 146: collected 20 posts (running total: 2920)
2026-08-16 21:41:30,985 [INFO] API page 147: collected 20 posts (running total: 2940)
2026-08-16 21:41:35,954 [INFO] API page 148: collected 20 posts (running total: 2960)
2026-08-16 21:41:41,075 [INFO] API page 149: collected 20 posts (running total: 2980)
2026-08-16 21:41:46,156 [INFO] API page 150: collected 20 posts (running total: 3000)
2026-08-16 21:41:51,476 [INFO] API page 151: collected 20 posts (running total: 3020)
2026-08-16 21:41:56,599 [INFO] API page 152: collected 20 posts (running total: 3040)
2026-08-16 21:42:01,627 [INFO] API page 153: collected 20 posts (running total: 3060)
2026-08-16 21:42:06,840 [INFO] API page 154: collected 20 posts (running total: 3080)
2026-08-16 21:42:12,124 [INFO] API page 155: collected 20 posts (running total: 3100)
2026-08-16 21:42:17,195 [INFO] API page 156: collected 20 posts (running total: 3120)
2026-08-16 21:42:22,929 [INFO] API page 157: collected 20 posts (running total: 3140)
2026-08-16 21:42:28,365 [INFO] API page 158: collected 20 posts (running total: 3160)
2026-08-16 21:42:33,474 [INFO] API page 159: collected 20 posts (running total: 3180)
2026-08-16 21:42:38,465 [INFO] API page 160: collected 20 posts (running total: 3200)
2026-08-16 21:42:43,627 [INFO] API page 161: collected 20 posts (running total: 3220)
2026-08-16 21:42:48,485 [INFO] API page 162: collected 20 posts (running total: 3240)
2026-08-16 21:42:53,485 [INFO] API page 163: collected 20 posts (running total: 3260)
2026-08-16 21:42:58,693 [INFO] API page 164: collected 20 posts (running total: 3280)
2026-08-16 21:43:03,710 [INFO] API page 165: collected 20 posts (running total: 3300)
2026-08-16 21:43:08,771 [INFO] API page 166: collected 20 posts (running total: 3320)
2026-08-16 21:43:13,968 [INFO] API page 167: collected 20 posts (running total: 3340)
2026-08-16 21:43:19,138 [INFO] API page 168: collected 20 posts (running total: 3360)
2026-08-16 21:43:24,253 [INFO] API page 169: collected 20 posts (running total: 3380)
2026-08-16 21:43:29,271 [INFO] API page 170: collected 20 posts (running total: 3400)
2026-08-16 21:43:34,381 [INFO] API page 171: collected 20 posts (running total: 3420)
2026-08-16 21:43:39,329 [INFO] API page 172: collected 20 posts (running total: 3440)
2026-08-16 21:43:44,460 [INFO] API page 173: collected 20 posts (running total: 3460)
2026-08-16 21:43:49,843 [INFO] API page 174: collected 20 posts (running total: 3480)
2026-08-16 21:43:54,964 [INFO] API page 175: collected 20 posts (running total: 3500)
2026-08-16 21:44:00,070 [INFO] API page 176: collected 20 posts (running total: 3520)
2026-08-16 21:44:05,320 [INFO] API page 177: collected 20 posts (running total: 3540)
2026-08-16 21:44:10,511 [INFO] API page 178: collected 20 posts (running total: 3560)
2026-08-16 21:44:15,515 [INFO] API page 179: collected 20 posts (running total: 3580)
2026-08-16 21:44:20,485 [INFO] API page 180: collected 20 posts (running total: 3600)
2026-08-16 21:44:25,655 [INFO] API page 181: collected 20 posts (running total: 3620)
2026-08-16 21:44:30,812 [INFO] API page 182: collected 20 posts (running total: 3640)
2026-08-16 21:44:35,982 [INFO] API page 183: collected 20 posts (running total: 3660)
2026-08-16 21:44:41,026 [INFO] API page 184: collected 20 posts (running total: 3680)
2026-08-16 21:44:46,103 [INFO] API page 185: collected 20 posts (running total: 3700)
2026-08-16 21:44:51,254 [INFO] API page 186: collected 20 posts (running total: 3720)
2026-08-16 21:44:56,254 [INFO] API page 187: collected 20 posts (running total: 3740)
2026-08-16 21:45:01,773 [INFO] API page 188: collected 20 posts (running total: 3760)
2026-08-16 21:45:06,939 [INFO] API page 189: collected 20 posts (running total: 3780)
2026-08-16 21:45:12,365 [INFO] API page 190: collected 20 posts (running total: 3800)
2026-08-16 21:45:17,512 [INFO] API page 191: collected 20 posts (running total: 3820)
2026-08-16 21:45:25,814 [INFO] API page 192: collected 20 posts (running total: 3840)
2026-08-16 21:45:32,178 [INFO] API page 193: collected 20 posts (running total: 3860)

2026-08-16 21:45:37,503 [INFO] API page 194: collected 20 posts (running total: 3880)
2026-08-16 21:45:42,716 [INFO] API page 195: collected 20 posts (running total: 3900)
2026-08-16 21:45:47,955 [INFO] API page 196: collected 20 posts (running total: 3920)
2026-08-16 21:45:52,921 [INFO] API page 197: collected 20 posts (running total: 3940)
2026-08-16 21:45:58,244 [INFO] API page 198: collected 20 posts (running total: 3960)
2026-08-16 21:46:03,202 [INFO] API page 199: collected 20 posts (running total: 3980)
2026-08-16 21:46:08,481 [INFO] API page 200: collected 20 posts (running total: 4000)
2026-08-16 21:46:13,650 [INFO] API page 201: collected 20 posts (running total: 4020)
2026-08-16 21:46:18,837 [INFO] API page 202: collected 20 posts (running total: 4040)
2026-08-16 21:46:24,179 [INFO] API page 203: collected 20 posts (running total: 4060)
2026-08-16 21:46:29,641 [INFO] API page 204: collected 20 posts (running total: 4080)
2026-08-16 21:46:34,750 [INFO] API page 205: collected 20 posts (running total: 4100)
2026-08-16 21:46:39,731 [INFO] API page 206: collected 20 posts (running total: 4120)
2026-08-16 21:46:44,696 [INFO] API page 207: collected 20 posts (running total: 4140)
2026-08-16 21:46:49,714 [INFO] API page 208: collected 20 posts (running total: 4160)
2026-08-16 21:46:54,760 [INFO] API page 209: collected 20 posts (running total: 4180)
2026-08-16 21:47:00,230 [INFO] API page 210: collected 20 posts (running total: 4200)
2026-08-16 21:47:05,427 [INFO] API page 211: collected 20 posts (running total: 4220)
2026-08-16 21:47:10,700 [INFO] API page 212: collected 20 posts (running total: 4240)
2026-08-16 21:47:15,751 [INFO] API page 213: collected 20 posts (running total: 4260)
2026-08-16 21:47:20,766 [INFO] API page 214: collected 20 posts (running total: 4280)
2026-08-16 21:47:26,403 [INFO] API page 215: collected 20 posts (running total: 4300)
2026-08-16 21:47:31,465 [INFO] API page 216: collected 20 posts (running total: 4320)
2026-08-16 21:47:36,507 [INFO] API page 217: collected 20 posts (running total: 4340)
2026-08-16 21:47:41,538 [INFO] API page 218: collected 20 posts (running total: 4360)
2026-08-16 21:47:46,801 [INFO] API page 219: collected 20 posts (running total: 4380)
2026-08-16 21:47:51,788 [INFO] API page 220: collected 20 posts (running total: 4400)
2026-08-16 21:47:56,985 [INFO] API page 221: collected 20 posts (running total: 4420)
2026-08-16 21:48:01,957 [INFO] API page 222: collected 20 posts (running total: 4440)
2026-08-16 21:48:07,204 [INFO] API page 223: collected 20 posts (running total: 4460)
2026-08-16 21:48:12,435 [INFO] API page 224: collected 20 posts (running total: 4480)
2026-08-16 21:48:17,513 [INFO] API page 225: collected 20 posts (running total: 4500)
2026-08-16 21:48:22,465 [INFO] API page 226: collected 20 posts (running total: 4520)
2026-08-16 21:48:27,539 [INFO] API page 227: collected 20 posts (running total: 4540)
2026-08-16 21:48:32,779 [INFO] API page 228: collected 20 posts (running total: 4560)
2026-08-16 21:48:37,885 [INFO] API page 229: collected 20 posts (running total: 4580)
2026-08-16 21:48:43,075 [INFO] API page 230: collected 20 posts (running total: 4600)
2026-08-16 21:48:48,033 [INFO] API page 231: collected 20 posts (running total: 4620)
2026-08-16 21:48:53,112 [INFO] API page 232: collected 20 posts (running total: 4640)
2026-08-16 21:48:58,083 [INFO] API page 233: collected 20 posts (running total: 4660)
2026-08-16 21:49:04,082 [INFO] API page 234: collected 20 posts (running total: 4680)
2026-08-16 21:49:09,330 [INFO] API page 235: collected 20 posts (running total: 4700)
2026-08-16 21:49:14,316 [INFO] API page 236: collected 20 posts (running total: 4720)
2026-08-16 21:49:19,500 [INFO] API page 237: collected 20 posts (running total: 4740)
2026-08-16 21:49:24,500 [INFO] API page 238: collected 20 posts (running total: 4760)
2026-08-16 21:49:29,346 [INFO] API page 239: collected 20 posts (running total: 4780)
2026-08-16 21:49:34,333 [INFO] API page 240: collected 20 posts (running total: 4800)
2026-08-16 21:49:39,671 [INFO] API page 241: collected 20 posts (running total: 4820)
2026-08-16 21:49:44,913 [INFO] API page 242: collected 20 posts (running total: 4840)
2026-08-16 21:49:50,390 [INFO] API page 243: collected 20 posts (running total: 4860)
2026-08-16 21:49:55,590 [INFO] API page 244: collected 20 posts (running total: 4880)
2026-08-16 21:50:00,766 [INFO] API page 245: collected 20 posts (running total: 4900)
2026-08-16 21:50:06,108 [INFO] API page 246: collected 20 posts (running total: 4920)
2026-08-16 21:50:11,151 [INFO] API page 247: collected 20 posts (running total: 4940)
2026-08-16 21:50:16,387 [INFO] API page 248: collected 20 posts (running total: 4960)
2026-08-16 21:50:21,526 [INFO] API page 249: collected 20 posts (running total: 4980)
2026-08-16 21:50:26,493 [INFO] API page 250: collected 20 posts (running total: 5000)
2026-08-16 21:50:31,761 [INFO] API page 251: collected 20 posts (running total: 5020)
2026-08-16 21:50:36,943 [INFO] API page 252: collected 20 posts (running total: 5040)
2026-08-16 21:50:42,469 [INFO] API page 253: collected 20 posts (running total: 5060)
2026-08-16 21:50:48,186 [INFO] API page 254: collected 20 posts (running total: 5080)
2026-08-16 21:50:53,820 [INFO] API page 255: collected 20 posts (running total: 5100)
2026-08-16 21:51:00,062 [INFO] API page 256: collected 20 posts (running total: 5120)
2026-08-16 21:51:05,675 [INFO] API page 257: collected 20 posts (running total: 5140)
2026-08-16 21:51:10,612 [INFO] API page 258: collected 20 posts (running total: 5160)
2026-08-16 21:51:15,595 [INFO] API page 259: collected 20 posts (running total: 5180)
2026-08-16 21:51:20,654 [INFO] API page 260: collected 20 posts (running total: 5200)
2026-08-16 21:51:26,068 [INFO] API page 261: collected 20 posts (running total: 5220)
2026-08-16 21:51:31,455 [INFO] API page 262: collected 20 posts (running total: 5240)
2026-08-16 21:51:36,461 [INFO] API page 263: collected 20 posts (running total: 5260)
2026-08-16 21:51:41,402 [INFO] API page 264: collected 20 posts (running total: 5280)
2026-08-16 21:51:46,528 [INFO] API page 265: collected 20 posts (running total: 5300)
2026-08-16 21:51:51,638 [INFO] API page 266: collected 20 posts (running total: 5320)
2026-08-16 21:51:56,900 [INFO] API page 267: collected 20 posts (running total: 5340)
2026-08-16 21:52:02,051 [INFO] API page 268: collected 20 posts (running total: 5360)
2026-08-16 21:52:07,100 [INFO] API page 269: collected 20 posts (running total: 5380)
2026-08-16 21:52:12,376 [INFO] API page 270: collected 20 posts (running total: 5400)
2026-08-16 21:52:17,409 [INFO] API page 271: collected 20 posts (running total: 5420)
2026-08-16 21:52:22,557 [INFO] API page 272: collected 20 posts (running total: 5440)
2026-08-16 21:52:27,960 [INFO] API page 273: collected 20 posts (running total: 5460)
2026-08-16 21:52:32,962 [INFO] API page 274: collected 20 posts (running total: 5480)
2026-08-16 21:52:37,928 [INFO] API page 275: collected 20 posts (running total: 5500)
2026-08-16 21:52:42,888 [INFO] API page 276: collected 20 posts (running total: 5520)
2026-08-16 21:52:46,624 [INFO] API page 277: collected 11 posts (running total: 5531)
2026-08-16 21:52:48,929 [INFO] Reached end of available pages at page 278.

Total records collected: 5531

In [7]:
# Set the output path
out_path = Path("jse_corpus.json")

# Save the extracted records
out_path.write_text(json.dumps(records, indent = 2, ensure_ascii = False), encoding = "utf-8")

# Print number of records saved
print(f"Saved {len(records)} records to {out_path.resolve()}")

Saved 5531 records to /home/areas001/Final Project/Final Notebooks/jse_corpus.json

In [8]:
# Save the scraped data in a DataFrame
df = pd.DataFrame(records)
print(df.shape)

# Preview the first 10 rows for a sanity check
df[["title", "date", "url", "retrieved_via"]].head(10)

(5531, 8)

,title,date,url,retrieved_via
0,Tropical Battery Company Limited (TROPICAL) – ...,2026-08-14T19:43:27,https://www.jamstockex.com/tropical-battery-co...,wp_api
1,PROVEN GROUP LIMITED UNAUDITED FIRST QUARTER R...,2026-08-14T19:43:05,https://www.jamstockex.com/proven-group-limite...,wp_api
2,Dolphin Cove Limited (DCOVE) – Unaudited Finan...,2026-08-14T19:36:32,https://www.jamstockex.com/dolphin-cove-limite...,wp_api
3,Kingston Properties Limited (KPREIT) Unaudited...,2026-08-14T19:31:17,https://www.jamstockex.com/kingston-properties...,wp_api
4,Eppley Caribbean Property Fund Limited SCC (CP...,2026-08-14T19:29:50,https://www.jamstockex.com/eppley-caribbean-pr...,wp_api
5,Eppley Caribbean Property Fund Limited SCC (CP...,2026-08-14T19:29:13,https://www.jamstockex.com/eppley-caribbean-pr...,wp_api
6,Eppley Caribbean Property Fund Limited SCC – V...,2026-08-14T19:28:39,https://www.jamstockex.com/eppley-caribbean-pr...,wp_api
7,FosRich Company Limited (FOSRICH) Unaudited Fi...,2026-08-14T19:26:55,https://www.jamstockex.com/fosrich-company-lim...,wp_api
8,Consolidated Bakeries Jamaica Limited (PURITY)...,2026-08-14T19:25:29,https://www.jamstockex.com/consolidated-bakeri...,wp_api
9,Carreras Limited (CAR) Unaudited Financial Sta...,2026-08-14T19:18:10,https://www.jamstockex.com/carreras-limited-ca...,wp_api

## JSE Price Data Collection

## 10. Price-scraper configuration

In [3]:
# list all JSE's market codes
MARKET_CODES = {
    "main": 31,
    "junior": 22,
    "combined": 50,
    "usd": 49,
    "bond": 51,
    "usd_bond": 52,
    "jmd_government_bond": 71,}

# Specify the trade data columns
QUOTE_COLUMNS = [
    "symbol", "last_traded_price", "closing_price", "price_change",
    "closing_bid", "closing_ask", "volume", "today_high", "today_low",
    "52wk_high", "52wk_low", "total_prev_yr_div", "total_current_yr_div",]

In [10]:
# Define a function to extract the company symbols
def _looks_like_symbol(cell: str) -> bool:
    
    if not cell:
        return False
    cell = cell.strip()
    if not cell or len(cell) > 15:
        return False
    if cell.lower() in ("symbol", "ordinary shares", "preference shares"):
        return False
    return any(c.isalpha() for c in cell) and cell.upper() == cell

# Define the function to fetch the daily trade reports
def fetch_daily_quotes(quote_date: date, market_code: int) -> list:
    
    params = {"date": quote_date.isoformat(), "market": market_code}
    try:
        resp = session.get(DAILY_QUOTE_PDF_URL, params=params, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Request failed for %s market=%s: %s", quote_date, market_code, e)
        return []

    if resp.status_code != 200:
        log.info("No PDF for %s market=%s (status %s) -- likely non-trading day.",
                  quote_date, market_code, resp.status_code)
        return []

    content_type = resp.headers.get("Content-Type", "")
    if "pdf" not in content_type.lower():
        log.info("Response for %s market=%s wasn't a PDF (Content-Type: %s) -- skipping.",
                  quote_date, market_code, content_type)
        return []

    rows = []
    try:
        with pdfplumber.open(io.BytesIO(resp.content)) as pdf:
            for page in pdf.pages:
                tables = page.extract_tables()
                for table in tables:
                    for raw_row in table:
                        if not raw_row:
                            continue
                        cleaned = [c.strip() if c else "" for c in raw_row]
                        if not cleaned or not _looks_like_symbol(cleaned[0]):
                            continue
                        cleaned = (cleaned + [""] * len(QUOTE_COLUMNS))[:len(QUOTE_COLUMNS)]
                        row_dict = dict(zip(QUOTE_COLUMNS, cleaned))
                        row_dict["date"] = quote_date.isoformat()
                        row_dict["market"] = market_code
                        rows.append(row_dict)
    except Exception as e:
        log.warning("Failed to parse PDF for %s market=%s: %s", quote_date, market_code, e)
        return []

    return rows

In [11]:
# Perform a sanity check to ensure the columns match
test_date = date(2026, 4, 14)
test_rows = fetch_daily_quotes(test_date, MARKET_CODES["main"])

# Print the sample of rows
print(f"Extracted {len(test_rows)} rows for {test_date}")
test_rows[:5]

Extracted 34 rows for 2026-04-14

[{'symbol': 'ASBH',
  'last_traded_price': '26.00',
  'closing_price': '26.18',
  'price_change': '-0.68',
  'closing_bid': '26.75',
  'closing_ask': '29.46',
  'volume': '2,860',
  'today_high': '27.01',
  'today_low': '26.00',
  '52wk_high': '40.00',
  '52wk_low': '20.00',
  'total_prev_yr_div': '0.0397',
  'total_current_yr_div': '0.0132',
  'date': '2026-04-14',
  'market': 31},
 {'symbol': 'BRG',
  'last_traded_price': '5.15',
  'closing_price': '5.15',
  'price_change': '-0.23',
  'closing_bid': '5.15',
  'closing_ask': '5.70',
  'volume': '979',
  'today_high': '5.15',
  'today_low': '5.15',
  '52wk_high': '7.89',
  '52wk_low': '5.00',
  'total_prev_yr_div': '',
  'total_current_yr_div': '',
  'date': '2026-04-14',
  'market': 31},
 {'symbol': 'CPJ',
  'last_traded_price': '5.68',
  'closing_price': '5.67',
  'price_change': '-0.06',
  'closing_bid': '5.55',
  'closing_ask': '5.70',
  'volume': '1,161',
  'today_high': '5.68',
  'today_low': '5.55',
  '52wk_high': '9.05',
  '52wk_low': '5.50',
  'total_prev_yr_div': '',
  'total_current_yr_div': '',
  'date': '2026-04-14',
  'market': 31},
 {'symbol': 'CPFV',
  'last_traded_price': '44.49',
  'closing_price': '44.33',
  'price_change': '1.22',
  'closing_bid': '40.00',
  'closing_ask': '44.50',
  'volume': '10,036',
  'today_high': '44.49',
  'today_low': '40.00',
  '52wk_high': '50.02',
  '52wk_low': '34.50',
  'total_prev_yr_div': '0.0424',
  'total_current_yr_div': '0.0095',
  'date': '2026-04-14',
  'market': 31},
 {'symbol': 'FIRSTROCKJMD',
  'last_traded_price': '9.13',
  'closing_price': '9.54',
  'price_change': '1.54',
  'closing_bid': '8.30',
  'closing_ask': '9.00',
  'volume': '2,715',
  'today_high': '9.54',
  'today_low': '9.13',
  '52wk_high': '12.50',
  '52wk_low': '6.85',
  'total_prev_yr_div': '',
  'total_current_yr_div': '',
  'date': '2026-04-14',
  'market': 31}]

In [12]:
# Set the start and end dates
START_DATE = date.today() - timedelta(days = 365 * 2)
END_DATE = date.today()

# Create the variable to save the price rows and set the number days
all_price_rows = []
current = START_DATE
total_days = (END_DATE - START_DATE).days + 1
processed = 0

# For the date period, scrape the price rows for each market
while current <= END_DATE:
    for market_name, market_code in MARKET_CODES.items():
        rows = fetch_daily_quotes(current, market_code)
        for r in rows:
            r["market_name"] = market_name
        all_price_rows.extend(rows)
        time.sleep(REQUEST_DELAY_SECONDS)

    processed += 1
    if processed % 25 == 0:
        log.info("Processed %s/%s days -- %s rows collected so far.",
                  processed, total_days, len(all_price_rows))

    current += timedelta(days=1)

# Print once completed
print(f"Done. Total rows collected: {len(all_price_rows)}")

2026-08-16 22:01:44,933 [INFO] Processed 25/731 days -- 2339 rows collected so far.
2026-08-16 22:10:36,064 [INFO] Processed 50/731 days -- 4961 rows collected so far.
2026-08-16 22:19:07,477 [INFO] Processed 75/731 days -- 7154 rows collected so far.
2026-08-16 22:27:50,964 [INFO] Processed 100/731 days -- 9620 rows collected so far.
2026-08-16 22:36:31,544 [INFO] Processed 125/731 days -- 12086 rows collected so far.
2026-08-16 22:44:48,892 [INFO] Processed 150/731 days -- 14004 rows collected so far.
2026-08-16 22:53:32,236 [INFO] Processed 175/731 days -- 16589 rows collected so far.
2026-08-16 23:02:24,478 [INFO] Processed 200/731 days -- 18881 rows collected so far.
2026-08-16 23:11:22,144 [INFO] Processed 225/731 days -- 21289 rows collected so far.
2026-08-16 23:19:48,427 [INFO] Processed 250/731 days -- 23327 rows collected so far.
2026-08-16 23:28:29,881 [INFO] Processed 275/731 days -- 25793 rows collected so far.
2026-08-16 23:37:09,586 [INFO] Processed 300/731 days -- 28122 rows collected so far.
2026-08-16 23:45:55,254 [INFO] Processed 325/731 days -- 30461 rows collected so far.
2026-08-16 23:54:46,777 [INFO] Processed 350/731 days -- 33134 rows collected so far.
2026-08-17 00:03:32,849 [INFO] Processed 375/731 days -- 35231 rows collected so far.
2026-08-17 00:12:23,415 [INFO] Processed 400/731 days -- 37885 rows collected so far.
2026-08-17 00:21:04,803 [INFO] Processed 425/731 days -- 40265 rows collected so far.
2026-08-17 00:29:25,569 [INFO] Processed 450/731 days -- 42225 rows collected so far.
2026-08-17 00:38:13,111 [INFO] Processed 475/731 days -- 44735 rows collected so far.
2026-08-17 00:46:41,274 [INFO] Processed 500/731 days -- 46828 rows collected so far.
2026-08-17 00:55:26,660 [INFO] Processed 525/731 days -- 49365 rows collected so far.
2026-08-17 01:04:23,582 [INFO] Processed 550/731 days -- 51762 rows collected so far.
2026-08-17 01:13:05,509 [INFO] Processed 575/731 days -- 54281 rows collected so far.
2026-08-17 01:21:33,584 [INFO] Processed 600/731 days -- 56387 rows collected so far.
2026-08-17 01:30:22,216 [INFO] Processed 625/731 days -- 58942 rows collected so far.
2026-08-17 01:39:39,898 [INFO] Processed 650/731 days -- 61494 rows collected so far.
2026-08-17 01:48:30,462 [INFO] Processed 675/731 days -- 63902 rows collected so far.
2026-08-17 01:57:26,343 [INFO] Processed 700/731 days -- 66626 rows collected so far.
2026-08-17 02:06:21,332 [INFO] Processed 725/731 days -- 68930 rows collected so far.

Done. Total rows collected: 69506

In [13]:
# Save the price data to a DataFrame
price_df = pd.DataFrame(all_price_rows)

# Save the price data to csv
price_df.to_csv("jse_price_data.csv", index = False)

# Preview the first 10 rows as a sanity check
print(f"Saved {len(price_df)} rows to jse_price_data.csv")
price_df.head(10)

Saved 69506 rows to jse_price_data.csv

,symbol,last_traded_price,closing_price,price_change,closing_bid,closing_ask,volume,today_high,today_low,52wk_high,52wk_low,total_prev_yr_div,total_current_yr_div,date,market,market_name
0,ASBH,37.50,33.95,-5.03,35.00,37.49,474,37.50,33.50,45.00,28.01,,,2024-08-16,31,main
1,BRG,6.36,6.85,0.05,6.50,6.85,"4,157",6.85,6.36,11.98,3.90,,,2024-08-16,31,main
2,CPJ,9.03,9.02,0.00,9.03,9.24,"33,885",9.03,9.01,13.89,8.00,,,2024-08-16,31,main
3,CPFV,40.75,40.75,3.21,35.01,40.75,84,40.75,40.75,42.10,30.00,0.0288,0.0302,2024-08-16,31,main
4,FIRSTROCKJMD,10.30,10.36,0.06,10.30,10.92,"44,202",10.93,10.30,11.00,6.00,,,2024-08-16,31,main
5,GK,73.40,74.02,-0.10,73.01,74.22,"23,166",74.22,73.01,82.90,60.00,2.1700,1.6200,2024-08-16,31,main
6,ENERGY,0.82,0.82,-0.06,0.82,0.87,"4,853",0.88,0.82,1.70,0.65,,,2024-08-16,31,main
7,JP,22.95,22.86,0.00,21.50,22.95,0,0.00,0.00,27.45,18.00,0.3000,0.3000,2024-08-16,31,main
8,JMMBGL,21.90,22.16,-0.41,22.78,22.79,"51,609",23.03,21.90,30.00,21.90,0.2500,0.2500,2024-08-16,31,main
9,KPREIT,9.00,9.00,0.00,9.00,9.18,"10,000",9.00,9.00,9.65,6.20,0.0015,0.0006,2024-08-16,31,main

## BSE Data Scraper

In [4]:
# Set the BSE configuration for web scrapping
BASE_URL = "https://bse.com.bb"
WP_API_POSTS = f"{BASE_URL}/wp-json/wp/v2/posts"
NEWS_URL = f"{BASE_URL}/news/"

log = logging.getLogger("bse_scraper")

# Set the BSE session header
session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://bse.com.bb/",})

In [18]:
# Test on 2 pages to ensure that the scraper is successful
test_records = try_wp_api(max_pages = 2, after_date = cutoff_date)

# If the test fails, try the HTML scraper
if not test_records:
    print("WP API returned nothing -- trying HTML fallback...")
    test_records = html_fallback_scrape(max_pages = 2)

# Print the number of rows collected
print(f"Collected {len(test_records)} records in test run.")
if test_records:
    {k: v for k, v in test_records[0].items() if k != "content_html"}

Cutoff date (2 years back): 2024-08-17

2026-08-17 02:08:27,379 [INFO] WP API is reachable. Total posts matching filter: 604
2026-08-17 02:08:28,347 [INFO] API page 1: collected 20 posts (running total: 20)
2026-08-17 02:08:30,913 [INFO] API page 2: collected 20 posts (running total: 40)

Collected 40 records in test run.

In [19]:
# Run the scrapper on the full number of pages
MAX_PAGES = 620 

# Save the scrapped data
records = try_wp_api(max_pages = MAX_PAGES, after_date = cutoff_date)

# If there were no records, try the HTML scraper
if not records:
    print("WP API returned nothing -- using HTML fallback.")
    records = html_fallback_scrape(max_pages = MAX_PAGES)

# Print the total number of records collected
print(f"Total records collected: {len(records)}")

2026-08-17 02:08:32,642 [INFO] WP API is reachable. Total posts matching filter: 604
2026-08-17 02:08:33,596 [INFO] API page 1: collected 20 posts (running total: 20)
2026-08-17 02:08:36,230 [INFO] API page 2: collected 20 posts (running total: 40)
2026-08-17 02:08:39,054 [INFO] API page 3: collected 20 posts (running total: 60)
2026-08-17 02:08:41,712 [INFO] API page 4: collected 20 posts (running total: 80)
2026-08-17 02:08:44,248 [INFO] API page 5: collected 20 posts (running total: 100)
2026-08-17 02:08:46,560 [INFO] API page 6: collected 20 posts (running total: 120)
2026-08-17 02:08:49,139 [INFO] API page 7: collected 20 posts (running total: 140)
2026-08-17 02:08:51,755 [INFO] API page 8: collected 20 posts (running total: 160)
2026-08-17 02:08:54,369 [INFO] API page 9: collected 20 posts (running total: 180)
2026-08-17 02:08:56,759 [INFO] API page 10: collected 20 posts (running total: 200)
2026-08-17 02:08:59,294 [INFO] API page 11: collected 20 posts (running total: 220)
2026-08-17 02:09:02,728 [INFO] API page 12: collected 20 posts (running total: 240)
2026-08-17 02:09:04,957 [INFO] API page 13: collected 20 posts (running total: 260)
2026-08-17 02:09:07,474 [INFO] API page 14: collected 20 posts (running total: 280)
2026-08-17 02:09:13,137 [INFO] API page 15: collected 20 posts (running total: 300)
2026-08-17 02:09:15,698 [INFO] API page 16: collected 20 posts (running total: 320)
2026-08-17 02:09:18,359 [INFO] API page 17: collected 20 posts (running total: 340)
2026-08-17 02:09:20,890 [INFO] API page 18: collected 20 posts (running total: 360)
2026-08-17 02:09:23,178 [INFO] API page 19: collected 20 posts (running total: 380)
2026-08-17 02:09:25,404 [INFO] API page 20: collected 20 posts (running total: 400)
2026-08-17 02:09:27,978 [INFO] API page 21: collected 20 posts (running total: 420)
2026-08-17 02:09:30,532 [INFO] API page 22: collected 20 posts (running total: 440)
2026-08-17 02:09:33,267 [INFO] API page 23: collected 20 posts (running total: 460)
2026-08-17 02:09:35,840 [INFO] API page 24: collected 20 posts (running total: 480)
2026-08-17 02:09:38,387 [INFO] API page 25: collected 20 posts (running total: 500)
2026-08-17 02:09:40,721 [INFO] API page 26: collected 20 posts (running total: 520)
2026-08-17 02:09:43,075 [INFO] API page 27: collected 20 posts (running total: 540)
2026-08-17 02:09:45,633 [INFO] API page 28: collected 20 posts (running total: 560)
2026-08-17 02:09:48,222 [INFO] API page 29: collected 20 posts (running total: 580)
2026-08-17 02:09:51,646 [INFO] API page 30: collected 20 posts (running total: 600)
2026-08-17 02:09:53,548 [INFO] API page 31: collected 4 posts (running total: 604)
2026-08-17 02:09:55,250 [INFO] Reached end of available pages at page 32.

Total records collected: 604

In [20]:
# Drop the raw content_html from the saved corpus 
disclosures_out = [{k: v for k, v in r.items() if k != "content_html"} for r in records]

# Save the BSE scrapped data
out_path = Path("bse_corpus.json")
out_path.write_text(json.dumps(disclosures_out, indent = 2, ensure_ascii = False), encoding = "utf-8")

# Print the number of records collected
print(f"Saved {len(disclosures_out)} records to {out_path.resolve()}")

Saved 604 records to /home/areas001/Final Project/Final Notebooks/bse_corpus.json

In [21]:
# Save the data in a DataFrame
df = pd.DataFrame(disclosures_out)

# Print the DataFrame shape
print(df.shape)

# Preview the first 10 rows of the BSE data
df[["title", "date", "url", "retrieved_via"]].head(10)

(604, 8)

,title,date,url,retrieved_via
0,"BSE Trading Report Package August 14, 2026",2026-08-14T15:21:35,https://bse.com.bb/news/30043,wp_api
1,"BSE Trading Report Package August 13, 2026",2026-08-13T14:29:03,https://bse.com.bb/news/30038,wp_api
2,"BSE Trading Report Package August 12, 2026",2026-08-12T14:13:30,https://bse.com.bb/news/30011,wp_api
3,"BSE Trading Report Package August 11, 2026",2026-08-11T14:12:13,https://bse.com.bb/news/30002,wp_api
4,"BSE Trading Report Package August 10, 2026",2026-08-10T14:35:58,https://bse.com.bb/news/29997,wp_api
5,"BSE Trading Report Package August 7, 2026",2026-08-07T14:49:24,https://bse.com.bb/news/29988,wp_api
6,"BSE Trading Report Package August 6, 2026",2026-08-06T14:20:42,https://bse.com.bb/news/29982,wp_api
7,"BSE Trading Report Package August 5, 2026",2026-08-05T14:22:08,https://bse.com.bb/news/29975,wp_api
8,"BSE Trading Report Package August 4, 2026",2026-08-04T14:09:19,https://bse.com.bb/news/29969,wp_api
9,"BSE Trading Report Package July 31, 2026",2026-07-31T14:42:58,https://bse.com.bb/news/29964,wp_api

## BSE Price Data Collection

In [22]:
# Import the required package
import re

# Define a function to clean the BSE post links
def clean_url(href: str) -> str:
    href = href.strip()
    href = re.sub(r'^https?:/+\s*(https?://)', r'\1', href)
    return href

# Define a function to download the trade PDFs from the BSE links
def extract_report_links(content_html: str) -> dict:

    soup = BeautifulSoup(content_html or "", "html.parser")
    links = {"trading_report_pdf": None, "share_summary_xls": None, "market_cap_pdf": None}
    for a in soup.find_all("a", href=True):
        href = clean_url(a["href"])
        text = a.get_text(strip=True).lower()
        combined = f"{text} {href.lower()}"

        if "market cap" in combined or "market-cap" in combined:
            links["market_cap_pdf"] = href
        elif "share summary" in combined or "share-summary" in combined:
            links["share_summary_xls"] = href
        elif "trading report" in combined or href.lower().endswith(".pdf"):
            links["trading_report_pdf"] = href

    return links


# Save the extracted price rows
report_posts = []
for r in records:
    if "trading report package" in r["title"].lower():
        links = extract_report_links(r["content_html"])
        report_posts.append({
            "date": r["date"][:10] if r["date"] else None,
            "title": r["title"],
            "url": r["url"],
            **links,})

# Print the number of trade posts found
print(f"Found {len(report_posts)} Trading Report Package posts.")

# Preview the first 3 as a sanity check
report_posts[:3]

Found 495 Trading Report Package posts.

[{'date': '2026-08-14',
  'title': 'BSE Trading Report Package August 14, 2026',
  'url': 'https://bse.com.bb/news/30043',
  'trading_report_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/20260814.pdf',
  'share_summary_xls': 'http://bse.com.bb/wp-content/uploads/2026/08/Share-Summary-August-14-2026.xls',
  'market_cap_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/Market-Cap-August-14-2026.pdf'},
 {'date': '2026-08-13',
  'title': 'BSE Trading Report Package August 13, 2026',
  'url': 'https://bse.com.bb/news/30038',
  'trading_report_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/20260813.pdf',
  'share_summary_xls': 'http://bse.com.bb/wp-content/uploads/2026/08/Share-Summary-August-13-2026.xls',
  'market_cap_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/Market-Cap-August-13-2026.pdf'},
 {'date': '2026-08-12',
  'title': 'BSE Trading Report Package August 12, 2026',
  'url': 'https://bse.com.bb/news/30011',
  'trading_report_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/20260812.pdf',
  'share_summary_xls': 'http://bse.com.bb/wp-content/uploads/2026/08/Share-Summary-August-12-2026.xls',
  'market_cap_pdf': 'http://bse.com.bb/wp-content/uploads/2026/08/Market-Cap-August-12-2026.pdf'}]

In [23]:
# Map the column names to the extracted column names
KNOWN_HEADER_MAP = {
    "last trade date": "last_trade_date",
    "volume": "volume",
    "high": "day_high",
    "low": "day_low",
    "last": "last_traded_price",
    "last  close": "last_traded_price",
    "close": "closing_price",
    "current close": "current_close",
    "price change": "price_change",
    "bid price": "bid_price",
    "ask price": "ask_price",
    "bid          size": "bid_size",
    "ask          size": "ask_size",
    "bid size": "bid_size",
    "ask size": "ask_size",}

# Define the function to extract the header row
def find_header_row(raw_df, max_scan_rows = 10):

    for i in range(min(max_scan_rows, len(raw_df))):
        row_values = [str(c).strip().lower() if pd.notna(c) else "" for c in raw_df.iloc[i]]
        if "volume" in row_values or "last trade date" in row_values:
            return i
    return None

# Extract the trade data from the downloaded xls files
def parse_share_summary_xls(xls_url: str, report_date: str) -> list:
 
    try:
        resp = session.get(xls_url, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to fetch %s: %s", xls_url, e)
        return []

    if resp.status_code != 200:
        log.warning("%s returned status %s.", xls_url, resp.status_code)
        return []

    try:
        raw_df = pd.read_excel(io.BytesIO(resp.content), header=None)
    except Exception as e:
        log.warning("Failed to parse %s: %s", xls_url, e)
        return []

    header_idx = find_header_row(raw_df)
    if header_idx is None:
        log.warning("Could not find a recognizable header row in %s (date=%s) -- skipping. "
                    "This file may use a different report layout.", xls_url, report_date)
        return []

    header_row = raw_df.iloc[header_idx]
    data_df = raw_df.iloc[header_idx + 1:].reset_index(drop=True)

    new_columns = []
    for i, c in enumerate(header_row):
        if i == 0:
            new_columns.append("company_name")
            continue
        label = str(c).strip().lower() if pd.notna(c) else ""
        new_columns.append(KNOWN_HEADER_MAP.get(label, f"unrecognized_{label or f'col_{i}'}"))
    data_df.columns = new_columns

    data_df = data_df.dropna(subset=["company_name"])

    unrecognized = [c for c in data_df.columns if c.startswith("unrecognized_")]
    if unrecognized:
        log.warning("File %s (date=%s) has unrecognized columns: %s", xls_url, report_date, unrecognized)

    data_df["date"] = report_date
    return data_df.to_dict(orient="records")


# Run a test on the most recent report as a sanity check
test_report = next((r for r in report_posts if r["share_summary_xls"]), None)
if test_report:
    test_price_rows = parse_share_summary_xls(test_report["share_summary_xls"], test_report["date"])
    report_date = test_report["date"]
    print(f"Extracted {len(test_price_rows)} rows for {report_date}")
    test_price_rows[:5]
else:
    print("No Share Summary .xls link found.")

Extracted 29 rows for 2026-08-14

In [24]:
# Create a variable to save all the BSE price rows
all_price_rows = []
skipped_no_link = 0

# For each post, extract the price rows
for i, rp in enumerate(report_posts):
    if not rp["share_summary_xls"]:
        skipped_no_link += 1
        continue
    rows = parse_share_summary_xls(rp["share_summary_xls"], rp["date"])
    all_price_rows.extend(rows)
    if (i + 1) % 25 == 0:
        log.info("Processed %s/%s report posts -- %s rows collected so far.",
                  i + 1, len(report_posts), len(all_price_rows))
    time.sleep(REQUEST_DELAY_SECONDS)

# Once completed, print the number of rows extracted
print(f"Done. Total price rows collected: {len(all_price_rows)}")
print(f"Report posts with no Share Summary link at all: {skipped_no_link} / {len(report_posts)}")

# If any files failed, report the failed files
if all_price_rows:
    all_columns = set()
    for r in all_price_rows:
        all_columns.update(r.keys())
    unrecognized_cols = [c for c in all_columns if c.startswith("unrecognized_")]
    if unrecognized_cols:
        print(f"\nWARNING: found unrecognized columns across the collected rows: {unrecognized_cols}")
        print("Some Share Summary files may use a different layout than expected -- worth checking a sample.")
    else:
        print("\nNo unrecognized columns found -- all parsed files matched the expected layout.")

2026-08-17 02:10:44,264 [INFO] Processed 25/495 report posts -- 725 rows collected so far.
2026-08-17 02:11:33,936 [INFO] Processed 50/495 report posts -- 1450 rows collected so far.
2026-08-17 02:12:23,569 [INFO] Processed 75/495 report posts -- 2154 rows collected so far.
2026-08-17 02:13:13,197 [INFO] Processed 100/495 report posts -- 2854 rows collected so far.
2026-08-17 02:14:02,894 [INFO] Processed 125/495 report posts -- 3554 rows collected so far.
2026-08-17 02:14:52,521 [INFO] Processed 150/495 report posts -- 4254 rows collected so far.
2026-08-17 02:15:42,143 [INFO] Processed 175/495 report posts -- 4954 rows collected so far.
2026-08-17 02:16:31,828 [INFO] Processed 200/495 report posts -- 5654 rows collected so far.
2026-08-17 02:17:21,468 [INFO] Processed 225/495 report posts -- 6354 rows collected so far.
2026-08-17 02:18:11,153 [INFO] Processed 250/495 report posts -- 7406 rows collected so far.
2026-08-17 02:19:00,841 [INFO] Processed 275/495 report posts -- 9206 rows collected so far.
2026-08-17 02:19:50,519 [INFO] Processed 300/495 report posts -- 11006 rows collected so far.
2026-08-17 02:20:40,208 [INFO] Processed 325/495 report posts -- 12806 rows collected so far.
2026-08-17 02:21:29,895 [INFO] Processed 350/495 report posts -- 14606 rows collected so far.
2026-08-17 02:22:19,582 [INFO] Processed 375/495 report posts -- 16406 rows collected so far.
2026-08-17 02:23:09,267 [INFO] Processed 400/495 report posts -- 18206 rows collected so far.
2026-08-17 02:23:58,951 [INFO] Processed 425/495 report posts -- 20006 rows collected so far.
2026-08-17 02:24:48,622 [INFO] Processed 450/495 report posts -- 21806 rows collected so far.
2026-08-17 02:25:38,295 [INFO] Processed 475/495 report posts -- 23606 rows collected so far.

Done. Total price rows collected: 25046
Report posts with no Share Summary link at all: 0 / 495

No unrecognized columns found -- all parsed files matched the expected layout.

In [25]:
# Save the price data into a DataFrame
price_df = pd.DataFrame(all_price_rows)

# Save the price data into a csv file
price_df.to_csv("bse_price_data.csv", index = False)
print(f"Saved {len(price_df)} rows to bse_price_data.csv")

# Preview the first 10 rows as a sanity check
price_df.head(10)

Saved 25046 rows to bse_price_data.csv

,company_name,last_trade_date,volume,day_high,day_low,last_traded_price,current_close,price_change,bid_price,ask_price,bid_size,ask_size,date
0,Banks Holdings Limited,2026-07-07,0,NaN,NaN,4.5,4.50,0,0.00,4.49,0.0,2750.0,2026-08-14
1,Barbados Dairy Industries Limited,2026-08-06,0,NaN,NaN,2.44,2.44,0,0.00,2.44,0.0,514.0,2026-08-14
2,Barbados Farms Limited,2026-02-18,0,NaN,NaN,0.4,0.40,0,0.00,0.00,0.0,0.0,2026-08-14
3,BICO Limited,2026-05-26,0,NaN,NaN,2,2.00,0,0.00,0.00,0.0,0.0,2026-08-14
4,Cave Shepherd and Company Limited -*,2026-08-06,0,NaN,NaN,9.7,9.70,0,8.50,9.70,30.0,5236.0,2026-08-14
5,CIBC Caribbean Bank Limited,2026-08-13,0,NaN,NaN,2.2,2.20,0,2.15,2.20,23390.0,27238.0,2026-08-14
6,Emera Deposit Receipt -*,2026-08-14,3,25.31,25.31,25.16,25.31,0.15,25.16,25.31,40.0,1183.0,2026-08-14
7,Eppley Caribbean Property Fund SCC - Developme...,2026-06-10,0,NaN,NaN,0.12,0.12,0,0.00,0.12,0.0,24052.0,2026-08-14
8,Eppley Caribbean Property Fund SCC - Value Fund,2026-08-13,0,NaN,NaN,0.51,0.51,0,0.51,0.53,76083.0,27367.0,2026-08-14
9,Goddard Enterprises Limited -*,2026-08-11,0,NaN,NaN,2.65,2.65,0,2.65,2.74,84211.0,10000.0,2026-08-14

## Download PDFs- JSE & BSE

In [1]:
log = logging.getLogger("pdf_downloader")

# Set the browser headers
BROWSER_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",}

# Define the function to download PDFs from the JSE & BSE websites
def download_pdf(session: requests.Session, url: str, dest_folder: Path, filename: str) -> bool:
 
    dest_folder.mkdir(parents=True, exist_ok=True)
    dest_path = dest_folder / filename

    if dest_path.exists():
        log.info("Already downloaded, skipping: %s", filename)
        return True

    try:
        resp = session.get(url, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to download %s: %s", url, e)
        return False

    if resp.status_code != 200:
        log.warning("%s returned status %s", url, resp.status_code)
        return False

    content_type = resp.headers.get("Content-Type", "")
    if "pdf" not in content_type.lower():
        log.warning("%s wasn't a PDF (Content-Type: %s) -- skipping", url, content_type)
        return False

    dest_path.write_bytes(resp.content)
    return True

### JSE PDF Extraction

In [31]:
# Set the JSE config for PDF download
JSE_BASE_URL = "https://www.jamstockex.com"
JSE_WP_API_POSTS = f"{JSE_BASE_URL}/wp-json/wp/v2/posts"

# Set the JSE session
jse_session = requests.Session()
jse_session.headers.update({**BROWSER_HEADERS, "Referer": f"{JSE_BASE_URL}/"})

# Set the download path
jse_corpus_path = Path("jse_corpus.json")

# Download the PDF for each collected URL
with open(jse_corpus_path, "r", encoding = "utf-8") as f:
    jse_records = json.load(f)
print(f"Loaded {len(jse_records)} records from {jse_corpus_path}")

# Print the number of candidate posts 
jse_candidate_posts = [r for r in jse_records if r["id"].startswith("wp-")]

print(f"{len(jse_candidate_posts)} records have a refetchable WP post ID "
      f"({len(jse_records) - len(jse_candidate_posts)} skipped -- no post ID available).")

Loaded 5531 records from jse_corpus.json
5531 records have a refetchable WP post ID (0 skipped -- no post ID available).

In [32]:
# Define a function to fetch a single post by its numeric ID via the WordPress REST AP
def get_post_content_html(base_url: str, session: requests.Session, post_id: int) -> str:
    url = f"{base_url}/wp-json/wp/v2/posts/{post_id}"
    try:
        resp = session.get(url, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to refetch post %s: %s", post_id, e)
        return ""
    if resp.status_code != 200:
        log.warning("Failed to refetch post %s: status %s", post_id, resp.status_code)
        return ""
    return resp.json().get("content", {}).get("rendered", "")

# Define a function to retrieve every link in the post body whose URL ends in .pdf
def extract_pdf_links(html: str) -> list:
    soup = BeautifulSoup(html or "", "html.parser")
    return [a["href"] for a in soup.find_all("a", href=True) if a["href"].lower().endswith(".pdf")]

# Set the folder to save the downloaded PDFs
jse_pdf_folder = Path("./JSE Data")
downloaded_count = 0
posts_with_pdf = 0
posts_without_pdf = 0

# Save the download progress
progress_path = Path("jse_pdf_link_check_progress.json")
if progress_path.exists():
    with open(progress_path, "r", encoding="utf-8") as f:
        checked_post_ids = set(json.load(f))
    print(f"Resuming -- {len(checked_post_ids)} posts already checked in a previous run.")
else:
    checked_post_ids = set()

# Check every JSE disclosure post for a linked PDF
for i, post in enumerate(jse_candidate_posts):
    post_id_str = post["id"]
    if post_id_str in checked_post_ids:
        continue
    post_id = int(post_id_str.split("-")[1])

    html = get_post_content_html(JSE_BASE_URL, jse_session, post_id)
    pdf_links = extract_pdf_links(html)

    if pdf_links:
        posts_with_pdf += 1
        for pdf_url in pdf_links:
            filename = pdf_url.split("/")[-1]
            if download_pdf(jse_session, pdf_url, jse_pdf_folder, filename):
                downloaded_count += 1
    else:
        posts_without_pdf += 1

    checked_post_ids.add(post_id_str)

    if (i + 1) % 20 == 0:
        with open(progress_path, "w", encoding="utf-8") as f:
            json.dump(list(checked_post_ids), f)
        log.info("Checked %s/%s posts -- %s have a PDF, %s downloaded so far.",
                  i + 1, len(jse_candidate_posts), posts_with_pdf, downloaded_count)
    time.sleep(REQUEST_DELAY_SECONDS)
    
# Final save once every post has been checked,
with open(progress_path, "w", encoding="utf-8") as f:
    json.dump(list(checked_post_ids), f)

# Once completed, print the number of extracted posts
print(f"\nDone. Checked {len(checked_post_ids)} posts.")
print(f"Posts with at least one PDF link: {posts_with_pdf}")
print(f"Posts with no PDF link at all: {posts_without_pdf}")
print(f"Total PDFs downloaded to {jse_pdf_folder.resolve()}: {downloaded_count}")

2026-08-17 02:27:54,122 [INFO] Already downloaded, skipping: Regency-Petroleum-Company-Limited-2nd-Quarter-Report-2026.pdf
2026-08-17 02:28:03,365 [INFO] Checked 20/5531 posts -- 17 have a PDF, 23 downloaded so far.
2026-08-17 02:29:07,125 [INFO] Checked 40/5531 posts -- 35 have a PDF, 49 downloaded so far.
2026-08-17 02:30:04,462 [INFO] Checked 60/5531 posts -- 48 have a PDF, 63 downloaded so far.
2026-08-17 02:31:00,775 [INFO] Checked 80/5531 posts -- 58 have a PDF, 77 downloaded so far.
2026-08-17 02:31:57,329 [INFO] Checked 100/5531 posts -- 70 have a PDF, 96 downloaded so far.
2026-08-17 02:32:51,023 [INFO] Checked 120/5531 posts -- 82 have a PDF, 109 downloaded so far.
2026-08-17 02:33:43,356 [INFO] Checked 140/5531 posts -- 93 have a PDF, 123 downloaded so far.
2026-08-17 02:34:35,253 [INFO] Checked 160/5531 posts -- 101 have a PDF, 134 downloaded so far.
2026-08-17 02:35:25,741 [INFO] Checked 180/5531 posts -- 111 have a PDF, 144 downloaded so far.
2026-08-17 02:36:17,129 [INFO] Checked 200/5531 posts -- 122 have a PDF, 158 downloaded so far.
2026-08-17 02:37:07,799 [INFO] Checked 220/5531 posts -- 129 have a PDF, 169 downloaded so far.
2026-08-17 02:37:57,400 [INFO] Checked 240/5531 posts -- 135 have a PDF, 175 downloaded so far.
2026-08-17 02:38:47,260 [INFO] Checked 260/5531 posts -- 142 have a PDF, 182 downloaded so far.
2026-08-17 02:39:36,851 [INFO] Checked 280/5531 posts -- 149 have a PDF, 189 downloaded so far.
2026-08-17 02:40:32,368 [INFO] Checked 300/5531 posts -- 160 have a PDF, 206 downloaded so far.
2026-08-17 02:41:22,968 [INFO] Checked 320/5531 posts -- 167 have a PDF, 213 downloaded so far.
2026-08-17 02:42:16,349 [INFO] Checked 340/5531 posts -- 179 have a PDF, 232 downloaded so far.
2026-08-17 02:43:09,106 [INFO] Checked 360/5531 posts -- 191 have a PDF, 245 downloaded so far.
2026-08-17 02:43:59,225 [INFO] Checked 380/5531 posts -- 200 have a PDF, 254 downloaded so far.
2026-08-17 02:44:47,774 [INFO] Checked 400/5531 posts -- 206 have a PDF, 262 downloaded so far.
2026-08-17 02:45:39,210 [INFO] Checked 420/5531 posts -- 218 have a PDF, 275 downloaded so far.
2026-08-17 02:46:30,620 [INFO] Checked 440/5531 posts -- 223 have a PDF, 282 downloaded so far.
2026-08-17 02:47:20,999 [INFO] Checked 460/5531 posts -- 229 have a PDF, 288 downloaded so far.
2026-08-17 02:48:10,853 [INFO] Checked 480/5531 posts -- 236 have a PDF, 295 downloaded so far.
2026-08-17 02:49:01,508 [INFO] Checked 500/5531 posts -- 245 have a PDF, 306 downloaded so far.
2026-08-17 02:49:51,793 [INFO] Checked 520/5531 posts -- 254 have a PDF, 322 downloaded so far.
2026-08-17 02:50:44,934 [INFO] Checked 540/5531 posts -- 262 have a PDF, 341 downloaded so far.
2026-08-17 02:51:36,892 [INFO] Checked 560/5531 posts -- 272 have a PDF, 351 downloaded so far.
2026-08-17 02:52:25,191 [INFO] Checked 580/5531 posts -- 279 have a PDF, 358 downloaded so far.
2026-08-17 02:53:16,945 [INFO] Checked 600/5531 posts -- 288 have a PDF, 367 downloaded so far.
2026-08-17 02:54:10,690 [INFO] Checked 620/5531 posts -- 302 have a PDF, 385 downloaded so far.
2026-08-17 02:55:01,311 [INFO] Checked 640/5531 posts -- 313 have a PDF, 405 downloaded so far.
2026-08-17 02:55:52,071 [INFO] Checked 660/5531 posts -- 322 have a PDF, 414 downloaded so far.
2026-08-17 02:56:45,396 [INFO] Checked 680/5531 posts -- 332 have a PDF, 434 downloaded so far.
2026-08-17 02:57:38,546 [INFO] Checked 700/5531 posts -- 343 have a PDF, 446 downloaded so far.
2026-08-17 02:58:30,558 [INFO] Checked 720/5531 posts -- 356 have a PDF, 461 downloaded so far.
2026-08-17 02:59:19,516 [INFO] Checked 740/5531 posts -- 361 have a PDF, 467 downloaded so far.
2026-08-17 03:00:28,270 [INFO] Checked 760/5531 posts -- 376 have a PDF, 486 downloaded so far.
2026-08-17 03:00:57,514 [INFO] Already downloaded, skipping: RPL-Q1-2026-Report.pdf
2026-08-17 03:01:21,978 [INFO] Checked 780/5531 posts -- 393 have a PDF, 508 downloaded so far.
2026-08-17 03:02:15,310 [INFO] Checked 800/5531 posts -- 406 have a PDF, 522 downloaded so far.
2026-08-17 03:03:04,162 [INFO] Checked 820/5531 posts -- 413 have a PDF, 529 downloaded so far.
2026-08-17 03:03:30,216 [INFO] Already downloaded, skipping: MASSY-Notice-of-Interim-Dividend-Declaration.pdf
2026-08-17 03:03:57,336 [INFO] Checked 840/5531 posts -- 423 have a PDF, 543 downloaded so far.
2026-08-17 03:04:48,784 [INFO] Checked 860/5531 posts -- 431 have a PDF, 554 downloaded so far.
2026-08-17 03:05:40,525 [INFO] Checked 880/5531 posts -- 442 have a PDF, 567 downloaded so far.
2026-08-17 03:06:34,209 [INFO] Checked 900/5531 posts -- 456 have a PDF, 584 downloaded so far.
2026-08-17 03:07:02,485 [INFO] Already downloaded, skipping: RPL-Annual-Report-FY2025_compressed.pdf
2026-08-17 03:07:25,949 [INFO] Checked 920/5531 posts -- 471 have a PDF, 606 downloaded so far.
2026-08-17 03:08:15,918 [INFO] Checked 940/5531 posts -- 484 have a PDF, 621 downloaded so far.
2026-08-17 03:09:09,472 [INFO] Checked 960/5531 posts -- 493 have a PDF, 635 downloaded so far.
2026-08-17 03:10:00,648 [INFO] Checked 980/5531 posts -- 503 have a PDF, 646 downloaded so far.
2026-08-17 03:10:52,221 [INFO] Checked 1000/5531 posts -- 510 have a PDF, 653 downloaded so far.
2026-08-17 03:11:43,501 [INFO] Checked 1020/5531 posts -- 517 have a PDF, 664 downloaded so far.
2026-08-17 03:12:34,180 [INFO] Checked 1040/5531 posts -- 523 have a PDF, 671 downloaded so far.
2026-08-17 03:13:26,889 [INFO] Checked 1060/5531 posts -- 534 have a PDF, 685 downloaded so far.
2026-08-17 03:16:36,880 [INFO] Checked 1080/5531 posts -- 544 have a PDF, 696 downloaded so far.
2026-08-17 03:17:28,258 [INFO] Checked 1100/5531 posts -- 552 have a PDF, 704 downloaded so far.
2026-08-17 03:17:38,624 [INFO] Already downloaded, skipping: Directors-Holding-as-at-December-31-2025.pdf
2026-08-17 03:18:21,071 [INFO] Checked 1120/5531 posts -- 562 have a PDF, 717 downloaded so far.
2026-08-17 03:19:15,612 [INFO] Checked 1140/5531 posts -- 575 have a PDF, 739 downloaded so far.
2026-08-17 03:20:05,203 [INFO] Checked 1160/5531 posts -- 584 have a PDF, 748 downloaded so far.
2026-08-17 03:20:54,278 [INFO] Checked 1180/5531 posts -- 588 have a PDF, 752 downloaded so far.
2026-08-17 03:21:29,526 [INFO] Already downloaded, skipping: Full-Speech-Financing-Utility-Resilience-in-an-Era-of-Extreme-Events-Livingstone-Morrison-Group-CEO-JSE.pdf
2026-08-17 03:21:29,528 [INFO] Already downloaded, skipping: Full-Speech-Financing-Utility-Resilience-in-an-Era-of-Extreme-Events-Livingstone-Morrison-Group-CEO-JSE.pdf
2026-08-17 03:21:44,766 [INFO] Checked 1200/5531 posts -- 597 have a PDF, 763 downloaded so far.
2026-08-17 03:22:37,555 [INFO] Checked 1220/5531 posts -- 605 have a PDF, 772 downloaded so far.
2026-08-17 03:23:29,326 [INFO] Checked 1240/5531 posts -- 616 have a PDF, 789 downloaded so far.
2026-08-17 03:24:19,152 [INFO] Checked 1260/5531 posts -- 623 have a PDF, 796 downloaded so far.
2026-08-17 03:25:08,578 [INFO] Checked 1280/5531 posts -- 630 have a PDF, 804 downloaded so far.
2026-08-17 03:25:58,279 [INFO] Checked 1300/5531 posts -- 636 have a PDF, 810 downloaded so far.
2026-08-17 03:26:53,148 [INFO] Checked 1320/5531 posts -- 648 have a PDF, 829 downloaded so far.
2026-08-17 03:27:45,959 [INFO] Checked 1340/5531 posts -- 664 have a PDF, 850 downloaded so far.
2026-08-17 03:28:03,452 [INFO] Already downloaded, skipping: Directors-Holding-as-at-December-31-2025-1.pdf
2026-08-17 03:28:21,400 [INFO] Already downloaded, skipping: Directors-Holding-as-at-December-31-2025.pdf
2026-08-17 03:28:38,798 [INFO] Checked 1360/5531 posts -- 677 have a PDF, 874 downloaded so far.
2026-08-17 03:29:30,502 [INFO] Checked 1380/5531 posts -- 685 have a PDF, 882 downloaded so far.
2026-08-17 03:30:20,826 [INFO] Checked 1400/5531 posts -- 692 have a PDF, 889 downloaded so far.
2026-08-17 03:31:09,192 [INFO] Checked 1420/5531 posts -- 697 have a PDF, 894 downloaded so far.
2026-08-17 03:32:01,518 [INFO] Checked 1440/5531 posts -- 707 have a PDF, 915 downloaded so far.
2026-08-17 03:32:53,324 [INFO] Checked 1460/5531 posts -- 718 have a PDF, 926 downloaded so far.
2026-08-17 03:33:43,996 [INFO] Checked 1480/5531 posts -- 732 have a PDF, 940 downloaded so far.
2026-08-17 03:34:23,305 [INFO] Already downloaded, skipping: Senior-Managers-Holding-as-at-December-31-2025-1.pdf

2026-08-17 03:34:39,239 [INFO] Checked 1500/5531 posts -- 747 have a PDF, 958 downloaded so far.
2026-08-17 03:35:31,492 [INFO] Checked 1520/5531 posts -- 759 have a PDF, 973 downloaded so far.
2026-08-17 03:36:20,492 [INFO] Checked 1540/5531 posts -- 766 have a PDF, 986 downloaded so far.
2026-08-17 03:37:10,420 [INFO] Already downloaded, skipping: MASSY-Notice-of-Interim-Dividend-Declaration.pdf
2026-08-17 03:37:12,723 [INFO] Checked 1560/5531 posts -- 773 have a PDF, 1001 downloaded so far.
2026-08-17 03:38:02,337 [INFO] Checked 1580/5531 posts -- 780 have a PDF, 1008 downloaded so far.
2026-08-17 03:38:53,862 [INFO] Checked 1600/5531 posts -- 791 have a PDF, 1022 downloaded so far.
2026-08-17 03:39:44,068 [INFO] Checked 1620/5531 posts -- 800 have a PDF, 1031 downloaded so far.
2026-08-17 03:40:38,185 [INFO] Checked 1640/5531 posts -- 809 have a PDF, 1042 downloaded so far.
2026-08-17 03:41:30,224 [INFO] Checked 1660/5531 posts -- 819 have a PDF, 1055 downloaded so far.
2026-08-17 03:41:58,763 [INFO] Already downloaded, skipping: SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-October-31-2025.pdf
2026-08-17 03:42:21,694 [INFO] Checked 1680/5531 posts -- 827 have a PDF, 1065 downloaded so far.
2026-08-17 03:43:16,497 [INFO] Checked 1700/5531 posts -- 840 have a PDF, 1082 downloaded so far.
2026-08-17 03:44:06,567 [INFO] Checked 1720/5531 posts -- 845 have a PDF, 1087 downloaded so far.
2026-08-17 03:44:55,216 [INFO] Checked 1740/5531 posts -- 849 have a PDF, 1091 downloaded so far.
2026-08-17 03:45:44,202 [INFO] Checked 1760/5531 posts -- 854 have a PDF, 1096 downloaded so far.
2026-08-17 03:46:37,967 [INFO] Checked 1780/5531 posts -- 864 have a PDF, 1107 downloaded so far.
2026-08-17 03:47:26,326 [INFO] Checked 1800/5531 posts -- 871 have a PDF, 1114 downloaded so far.
2026-08-17 03:48:15,753 [INFO] Checked 1820/5531 posts -- 876 have a PDF, 1119 downloaded so far.
2026-08-17 03:49:05,465 [INFO] Checked 1840/5531 posts -- 884 have a PDF, 1130 downloaded so far.
2026-08-17 03:49:46,166 [WARNING] https://cdn.jamstockex.com/pd/2025/12/Kintyre-and-Miracle-BOLD-Move-2.pdf returned status 403
2026-08-17 03:50:01,606 [INFO] Checked 1860/5531 posts -- 894 have a PDF, 1147 downloaded so far.
2026-08-17 03:50:14,001 [INFO] Already downloaded, skipping: Senior-Mangement-Shareholdings-as-at-November-1-2025.pdf
2026-08-17 03:50:52,291 [INFO] Checked 1880/5531 posts -- 903 have a PDF, 1160 downloaded so far.
2026-08-17 03:51:41,789 [INFO] Already downloaded, skipping: SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-October-31-2025.pdf
2026-08-17 03:51:45,296 [INFO] Checked 1900/5531 posts -- 914 have a PDF, 1173 downloaded so far.
2026-08-17 03:52:19,691 [INFO] Already downloaded, skipping: Venture-Capital-Pitch-Room-Application-Form-2026.pdf
2026-08-17 03:52:33,830 [INFO] Checked 1920/5531 posts -- 918 have a PDF, 1178 downloaded so far.
2026-08-17 03:52:57,432 [INFO] Already downloaded, skipping: Best-Practices-Awards-Winners-2025-for-2024-Assessments.pdf
2026-08-17 03:53:24,167 [INFO] Checked 1940/5531 posts -- 928 have a PDF, 1191 downloaded so far.
2026-08-17 03:54:15,707 [INFO] Checked 1960/5531 posts -- 936 have a PDF, 1200 downloaded so far.
2026-08-17 03:55:06,371 [INFO] Checked 1980/5531 posts -- 944 have a PDF, 1208 downloaded so far.
2026-08-17 03:55:57,725 [INFO] Checked 2000/5531 posts -- 954 have a PDF, 1220 downloaded so far.
2026-08-17 03:56:46,834 [INFO] Checked 2020/5531 posts -- 958 have a PDF, 1224 downloaded so far.
2026-08-17 03:57:36,968 [INFO] Checked 2040/5531 posts -- 966 have a PDF, 1232 downloaded so far.
2026-08-17 03:58:28,811 [INFO] Checked 2060/5531 posts -- 977 have a PDF, 1253 downloaded so far.
2026-08-17 03:59:24,577 [INFO] Checked 2080/5531 posts -- 993 have a PDF, 1272 downloaded so far.
2026-08-17 03:59:49,803 [INFO] Already downloaded, skipping: RPL-Q3-2025-Report-Stitch-2.pdf
2026-08-17 04:00:37,578 [INFO] Checked 2100/5531 posts -- 1007 have a PDF, 1290 downloaded so far.
2026-08-17 04:01:30,939 [INFO] Checked 2120/5531 posts -- 1021 have a PDF, 1313 downloaded so far.
2026-08-17 04:02:23,623 [INFO] Checked 2140/5531 posts -- 1036 have a PDF, 1333 downloaded so far.
2026-08-17 04:03:15,042 [INFO] Checked 2160/5531 posts -- 1046 have a PDF, 1350 downloaded so far.
2026-08-17 04:04:04,775 [INFO] Checked 2180/5531 posts -- 1055 have a PDF, 1372 downloaded so far.
2026-08-17 04:04:58,732 [INFO] Checked 2200/5531 posts -- 1067 have a PDF, 1392 downloaded so far.
2026-08-17 04:05:49,851 [INFO] Checked 2220/5531 posts -- 1078 have a PDF, 1404 downloaded so far.
2026-08-17 04:06:40,472 [INFO] Checked 2240/5531 posts -- 1083 have a PDF, 1411 downloaded so far.
2026-08-17 04:07:31,419 [INFO] Checked 2260/5531 posts -- 1090 have a PDF, 1419 downloaded so far.
2026-08-17 04:08:21,434 [INFO] Checked 2280/5531 posts -- 1097 have a PDF, 1427 downloaded so far.
2026-08-17 04:09:16,418 [INFO] Checked 2300/5531 posts -- 1108 have a PDF, 1442 downloaded so far.
2026-08-17 04:09:58,969 [INFO] Already downloaded, skipping: MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf
2026-08-17 04:09:59,026 [INFO] Already downloaded, skipping: AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-AUGUST-2025.pdf
2026-08-17 04:10:06,663 [INFO] Checked 2320/5531 posts -- 1118 have a PDF, 1456 downloaded so far.
2026-08-17 04:10:58,295 [INFO] Checked 2340/5531 posts -- 1126 have a PDF, 1464 downloaded so far.
2026-08-17 04:11:48,619 [INFO] Checked 2360/5531 posts -- 1134 have a PDF, 1472 downloaded so far.
2026-08-17 04:12:38,683 [INFO] Checked 2380/5531 posts -- 1141 have a PDF, 1479 downloaded so far.
2026-08-17 04:13:28,510 [INFO] Checked 2400/5531 posts -- 1148 have a PDF, 1486 downloaded so far.
2026-08-17 04:14:18,184 [INFO] Checked 2420/5531 posts -- 1152 have a PDF, 1492 downloaded so far.
2026-08-17 04:15:07,060 [INFO] Checked 2440/5531 posts -- 1160 have a PDF, 1500 downloaded so far.
2026-08-17 04:15:56,952 [INFO] Checked 2460/5531 posts -- 1166 have a PDF, 1506 downloaded so far.
2026-08-17 04:16:01,072 [WARNING] https://www.jamstockex.com/wp-content/uploads/2025/09/Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Don-Gittens-as-Director-and-Compensation-Committee.pdf returned status 404
2026-08-17 04:16:47,826 [INFO] Checked 2480/5531 posts -- 1174 have a PDF, 1515 downloaded so far.
2026-08-17 04:17:37,242 [INFO] Checked 2500/5531 posts -- 1178 have a PDF, 1519 downloaded so far.
2026-08-17 04:18:03,153 [INFO] Already downloaded, skipping: MEEG-Directors-Holding-as-at-July-31-2025.pdf
2026-08-17 04:18:27,633 [INFO] Checked 2520/5531 posts -- 1188 have a PDF, 1532 downloaded so far.
2026-08-17 04:19:20,197 [INFO] Checked 2540/5531 posts -- 1199 have a PDF, 1544 downloaded so far.
2026-08-17 04:20:15,031 [INFO] Checked 2560/5531 posts -- 1206 have a PDF, 1556 downloaded so far.
2026-08-17 04:21:06,447 [INFO] Checked 2580/5531 posts -- 1213 have a PDF, 1563 downloaded so far.
2026-08-17 04:21:56,331 [INFO] Checked 2600/5531 posts -- 1221 have a PDF, 1571 downloaded so far.
2026-08-17 04:22:49,180 [INFO] Checked 2620/5531 posts -- 1230 have a PDF, 1584 downloaded so far.
2026-08-17 04:23:37,719 [INFO] Checked 2640/5531 posts -- 1238 have a PDF, 1593 downloaded so far.
2026-08-17 04:24:27,388 [INFO] Checked 2660/5531 posts -- 1247 have a PDF, 1606 downloaded so far.
2026-08-17 04:25:18,442 [INFO] Checked 2680/5531 posts -- 1256 have a PDF, 1617 downloaded so far.
2026-08-17 04:26:10,636 [INFO] Checked 2700/5531 posts -- 1266 have a PDF, 1627 downloaded so far.
2026-08-17 04:27:02,109 [INFO] Checked 2720/5531 posts -- 1278 have a PDF, 1642 downloaded so far.
2026-08-17 04:27:53,045 [INFO] Checked 2740/5531 posts -- 1295 have a PDF, 1668 downloaded so far.
2026-08-17 04:28:43,395 [INFO] Checked 2760/5531 posts -- 1309 have a PDF, 1683 downloaded so far.
2026-08-17 04:29:38,313 [INFO] Checked 2780/5531 posts -- 1325 have a PDF, 1702 downloaded so far.
2026-08-17 04:30:27,821 [INFO] Already downloaded, skipping: RPL-Q2-2025-Unaudited-Financials.pdf
2026-08-17 04:30:32,488 [INFO] Checked 2800/5531 posts -- 1342 have a PDF, 1731 downloaded so far.
2026-08-17 04:31:23,325 [INFO] Checked 2820/5531 posts -- 1351 have a PDF, 1744 downloaded so far.

2026-08-17 04:32:15,865 [INFO] Checked 2840/5531 posts -- 1362 have a PDF, 1757 downloaded so far.
2026-08-17 04:33:05,825 [INFO] Checked 2860/5531 posts -- 1373 have a PDF, 1773 downloaded so far.
2026-08-17 04:34:01,866 [INFO] Checked 2880/5531 posts -- 1384 have a PDF, 1793 downloaded so far.
2026-08-17 04:34:56,847 [INFO] Checked 2900/5531 posts -- 1394 have a PDF, 1812 downloaded so far.
2026-08-17 04:35:50,687 [INFO] Checked 2920/5531 posts -- 1405 have a PDF, 1827 downloaded so far.
2026-08-17 04:36:42,656 [INFO] Checked 2940/5531 posts -- 1414 have a PDF, 1839 downloaded so far.
2026-08-17 04:37:33,724 [INFO] Checked 2960/5531 posts -- 1419 have a PDF, 1844 downloaded so far.
2026-08-17 04:38:23,645 [INFO] Checked 2980/5531 posts -- 1425 have a PDF, 1854 downloaded so far.
2026-08-17 04:39:15,490 [INFO] Checked 3000/5531 posts -- 1435 have a PDF, 1865 downloaded so far.
2026-08-17 04:39:30,048 [INFO] Already downloaded, skipping: MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf
2026-08-17 04:39:56,197 [INFO] Already downloaded, skipping: Proxy-Form.pdf
2026-08-17 04:40:08,427 [INFO] Checked 3020/5531 posts -- 1447 have a PDF, 1883 downloaded so far.
2026-08-17 04:40:58,684 [INFO] Checked 3040/5531 posts -- 1455 have a PDF, 1891 downloaded so far.
2026-08-17 04:41:48,636 [INFO] Checked 3060/5531 posts -- 1459 have a PDF, 1895 downloaded so far.
2026-08-17 04:42:40,458 [INFO] Checked 3080/5531 posts -- 1469 have a PDF, 1906 downloaded so far.
2026-08-17 04:43:30,396 [INFO] Checked 3100/5531 posts -- 1475 have a PDF, 1912 downloaded so far.
2026-08-17 04:44:20,067 [INFO] Checked 3120/5531 posts -- 1485 have a PDF, 1922 downloaded so far.
2026-08-17 04:44:36,667 [INFO] Already downloaded, skipping: LUMBER-Delayed-Filing-of-Audited-Financial-Statements.pdf
2026-08-17 04:45:08,560 [INFO] Checked 3140/5531 posts -- 1492 have a PDF, 1929 downloaded so far.
2026-08-17 04:46:02,783 [INFO] Checked 3160/5531 posts -- 1503 have a PDF, 1940 downloaded so far.
2026-08-17 04:46:52,201 [INFO] Checked 3180/5531 posts -- 1508 have a PDF, 1945 downloaded so far.
2026-08-17 04:47:42,552 [INFO] Checked 3200/5531 posts -- 1515 have a PDF, 1952 downloaded so far.
2026-08-17 04:48:33,357 [INFO] Checked 3220/5531 posts -- 1523 have a PDF, 1962 downloaded so far.
2026-08-17 04:49:24,152 [INFO] Checked 3240/5531 posts -- 1529 have a PDF, 1969 downloaded so far.
2026-08-17 04:49:42,981 [INFO] Already downloaded, skipping: Notice-of-AGM.pdf
2026-08-17 04:50:13,216 [INFO] Checked 3260/5531 posts -- 1535 have a PDF, 1977 downloaded so far.
2026-08-17 04:51:06,244 [INFO] Checked 3280/5531 posts -- 1544 have a PDF, 1988 downloaded so far.
2026-08-17 04:51:58,157 [INFO] Checked 3300/5531 posts -- 1553 have a PDF, 1997 downloaded so far.
2026-08-17 04:52:51,398 [INFO] Checked 3320/5531 posts -- 1563 have a PDF, 2009 downloaded so far.
2026-08-17 04:53:42,565 [INFO] Checked 3340/5531 posts -- 1574 have a PDF, 2021 downloaded so far.
2026-08-17 04:54:31,575 [INFO] Checked 3360/5531 posts -- 1584 have a PDF, 2041 downloaded so far.
2026-08-17 04:55:21,205 [INFO] Checked 3380/5531 posts -- 1590 have a PDF, 2047 downloaded so far.
2026-08-17 04:56:11,978 [INFO] Checked 3400/5531 posts -- 1597 have a PDF, 2055 downloaded so far.
2026-08-17 04:57:03,740 [INFO] Checked 3420/5531 posts -- 1606 have a PDF, 2066 downloaded so far.
2026-08-17 04:57:53,141 [INFO] Checked 3440/5531 posts -- 1613 have a PDF, 2073 downloaded so far.
2026-08-17 04:58:45,029 [INFO] Checked 3460/5531 posts -- 1631 have a PDF, 2098 downloaded so far.
2026-08-17 04:59:23,432 [INFO] Already downloaded, skipping: AGM-Notice-2025.pdf
2026-08-17 04:59:23,434 [INFO] Already downloaded, skipping: Proxy-Form.pdf
2026-08-17 04:59:39,295 [INFO] Checked 3480/5531 posts -- 1645 have a PDF, 2116 downloaded so far.
2026-08-17 05:00:31,843 [INFO] Already downloaded, skipping: RPL-Q1-2025-Report_compressed.pdf
2026-08-17 05:00:49,736 [INFO] Checked 3500/5531 posts -- 1661 have a PDF, 2145 downloaded so far.
2026-08-17 05:01:41,196 [INFO] Checked 3520/5531 posts -- 1672 have a PDF, 2158 downloaded so far.
2026-08-17 05:02:36,410 [INFO] Checked 3540/5531 posts -- 1686 have a PDF, 2174 downloaded so far.
2026-08-17 05:02:49,434 [INFO] Already downloaded, skipping: Unaudited-Financials-Q1-2025.pdf
2026-08-17 05:02:49,436 [INFO] Already downloaded, skipping: Unaudited-Financials-Q1-2025.pdf
2026-08-17 05:03:28,782 [INFO] Checked 3560/5531 posts -- 1696 have a PDF, 2187 downloaded so far.
2026-08-17 05:04:07,780 [INFO] Already downloaded, skipping: Agenda-NEW-YORK-May-8-2025.pdf
2026-08-17 05:04:10,085 [INFO] Already downloaded, skipping: Agenda-NEW-YORK-May-8-2025.pdf
2026-08-17 05:04:12,418 [INFO] Already downloaded, skipping: Agenda-NEW-YORK-May-8-2025.pdf
2026-08-17 05:04:23,230 [INFO] Checked 3580/5531 posts -- 1709 have a PDF, 2205 downloaded so far.
2026-08-17 05:04:57,070 [INFO] Already downloaded, skipping: Agenda-NEW-YORK-May-8-2025.pdf
2026-08-17 05:04:58,820 [INFO] Already downloaded, skipping: Agenda-NEW-YORK-May-8-2025.pdf
2026-08-17 05:05:15,045 [INFO] Checked 3600/5531 posts -- 1716 have a PDF, 2217 downloaded so far.
2026-08-17 05:06:06,100 [INFO] Checked 3620/5531 posts -- 1723 have a PDF, 2226 downloaded so far.
2026-08-17 05:06:59,783 [INFO] Checked 3640/5531 posts -- 1737 have a PDF, 2249 downloaded so far.
2026-08-17 05:07:22,302 [INFO] Already downloaded, skipping: 1GS-Annual-Report-2024.pdf
2026-08-17 05:07:49,209 [INFO] Checked 3660/5531 posts -- 1750 have a PDF, 2267 downloaded so far.
2026-08-17 05:08:43,177 [INFO] Checked 3680/5531 posts -- 1766 have a PDF, 2289 downloaded so far.
2026-08-17 05:09:36,181 [INFO] Checked 3700/5531 posts -- 1777 have a PDF, 2301 downloaded so far.
2026-08-17 05:10:27,436 [INFO] Checked 3720/5531 posts -- 1789 have a PDF, 2314 downloaded so far.
2026-08-17 05:11:06,819 [INFO] Already downloaded, skipping: NOTICE-OF-ANNUAL-GENERAL-MEETING.pdf
2026-08-17 05:11:17,827 [INFO] Checked 3740/5531 posts -- 1797 have a PDF, 2323 downloaded so far.
2026-08-17 05:14:15,167 [INFO] Checked 3760/5531 posts -- 1809 have a PDF, 2335 downloaded so far.
2026-08-17 05:14:17,498 [INFO] Already downloaded, skipping: MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf
2026-08-17 05:15:08,749 [INFO] Checked 3780/5531 posts -- 1818 have a PDF, 2350 downloaded so far.
2026-08-17 05:16:02,528 [INFO] Checked 3800/5531 posts -- 1829 have a PDF, 2365 downloaded so far.
2026-08-17 05:16:54,203 [INFO] Checked 3820/5531 posts -- 1837 have a PDF, 2375 downloaded so far.
2026-08-17 05:17:30,007 [INFO] Already downloaded, skipping: Notice_SE_PP_Material_Change.pdf
2026-08-17 05:17:44,570 [INFO] Checked 3840/5531 posts -- 1846 have a PDF, 2385 downloaded so far.
2026-08-17 05:18:33,488 [INFO] Checked 3860/5531 posts -- 1850 have a PDF, 2390 downloaded so far.
2026-08-17 05:19:27,739 [INFO] Checked 3880/5531 posts -- 1858 have a PDF, 2407 downloaded so far.
2026-08-17 05:20:17,446 [INFO] Checked 3900/5531 posts -- 1870 have a PDF, 2423 downloaded so far.
2026-08-17 05:21:05,449 [INFO] Checked 3920/5531 posts -- 1875 have a PDF, 2432 downloaded so far.
2026-08-17 05:21:14,573 [INFO] Already downloaded, skipping: CEO-FORUM-Speakers.pdf
2026-08-17 05:21:14,575 [INFO] Already downloaded, skipping: Registration-Form-CEO-BUSINESS-FORUM._.pdf
2026-08-17 05:21:14,576 [INFO] Already downloaded, skipping: Methods-of-Payment.pdf
2026-08-17 05:21:57,943 [INFO] Checked 3940/5531 posts -- 1883 have a PDF, 2445 downloaded so far.
2026-08-17 05:22:48,034 [INFO] Checked 3960/5531 posts -- 1889 have a PDF, 2451 downloaded so far.
2026-08-17 05:23:21,673 [INFO] Already downloaded, skipping: Press-Release-_JSE-Website-March-2025.pdf
2026-08-17 05:23:39,858 [INFO] Checked 3980/5531 posts -- 1898 have a PDF, 2461 downloaded so far.
2026-08-17 05:24:29,016 [INFO] Checked 4000/5531 posts -- 1906 have a PDF, 2471 downloaded so far.
2026-08-17 05:25:20,577 [INFO] Checked 4020/5531 posts -- 1912 have a PDF, 2478 downloaded so far.
2026-08-17 05:26:14,192 [INFO] Checked 4040/5531 posts -- 1922 have a PDF, 2491 downloaded so far.
2026-08-17 05:27:07,954 [WARNING] https://www.jamstockex.com/wp-content/uploads/_pda/2025/03/Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-for-the-Fourth-Quarter-Ended-December-31-2024.pdf returned status 404

2026-08-17 05:27:07,961 [INFO] Checked 4060/5531 posts -- 1935 have a PDF, 2505 downloaded so far.
2026-08-17 05:27:15,638 [INFO] Already downloaded, skipping: Chairmans-Update-to-Stockholders-of-Supreme-Ventures-Limited.pdf
2026-08-17 05:27:59,133 [INFO] Checked 4080/5531 posts -- 1949 have a PDF, 2528 downloaded so far.
2026-08-17 05:28:51,822 [INFO] Already downloaded, skipping: 2024-December-Top-Ten-10-Stockholders.pdf
2026-08-17 05:28:51,836 [INFO] Checked 4100/5531 posts -- 1963 have a PDF, 2562 downloaded so far.
2026-08-17 05:29:42,578 [INFO] Checked 4120/5531 posts -- 1967 have a PDF, 2569 downloaded so far.
2026-08-17 05:30:31,151 [INFO] Checked 4140/5531 posts -- 1971 have a PDF, 2576 downloaded so far.
2026-08-17 05:31:23,585 [INFO] Checked 4160/5531 posts -- 1978 have a PDF, 2583 downloaded so far.
2026-08-17 05:32:17,913 [INFO] Checked 4180/5531 posts -- 1986 have a PDF, 2594 downloaded so far.
2026-08-17 05:33:09,276 [INFO] Checked 4200/5531 posts -- 1996 have a PDF, 2604 downloaded so far.
2026-08-17 05:33:29,360 [INFO] Already downloaded, skipping: Directors-Holding-as-at-December-31-2024.pdf
2026-08-17 05:34:01,100 [INFO] Checked 4220/5531 posts -- 2012 have a PDF, 2630 downloaded so far.
2026-08-17 05:34:54,194 [INFO] Checked 4240/5531 posts -- 2028 have a PDF, 2649 downloaded so far.
2026-08-17 05:35:45,422 [INFO] Checked 4260/5531 posts -- 2038 have a PDF, 2660 downloaded so far.
2026-08-17 05:36:38,687 [INFO] Checked 4280/5531 posts -- 2053 have a PDF, 2687 downloaded so far.
2026-08-17 05:37:00,014 [INFO] Already downloaded, skipping: MASSY-Notice-of-Interim-Dividend-Declaration.pdf
2026-08-17 05:37:29,814 [INFO] Checked 4300/5531 posts -- 2061 have a PDF, 2696 downloaded so far.
2026-08-17 05:38:24,736 [INFO] Checked 4320/5531 posts -- 2070 have a PDF, 2710 downloaded so far.
2026-08-17 05:39:20,667 [INFO] Checked 4340/5531 posts -- 2081 have a PDF, 2725 downloaded so far.
2026-08-17 05:40:01,836 [INFO] Already downloaded, skipping: HONBUN-Annual-Report-2024.pdf
2026-08-17 05:40:11,720 [INFO] Checked 4360/5531 posts -- 2087 have a PDF, 2732 downloaded so far.
2026-08-17 05:40:34,649 [INFO] Already downloaded, skipping: SALF-Shareholders-Update-for-60th-AGM-amended.pdf
2026-08-17 05:41:06,001 [INFO] Checked 4380/5531 posts -- 2095 have a PDF, 2742 downloaded so far.
2026-08-17 05:41:57,429 [INFO] Checked 4400/5531 posts -- 2103 have a PDF, 2754 downloaded so far.
2026-08-17 05:42:49,458 [INFO] Checked 4420/5531 posts -- 2112 have a PDF, 2763 downloaded so far.
2026-08-17 05:43:38,917 [INFO] Checked 4440/5531 posts -- 2121 have a PDF, 2772 downloaded so far.
2026-08-17 05:44:29,653 [INFO] Already downloaded, skipping: MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf
2026-08-17 05:44:36,884 [INFO] Checked 4460/5531 posts -- 2136 have a PDF, 2793 downloaded so far.
2026-08-17 05:45:28,960 [INFO] Checked 4480/5531 posts -- 2145 have a PDF, 2802 downloaded so far.
2026-08-17 05:46:18,963 [INFO] Checked 4500/5531 posts -- 2151 have a PDF, 2810 downloaded so far.
2026-08-17 05:47:08,781 [INFO] Checked 4520/5531 posts -- 2157 have a PDF, 2817 downloaded so far.
2026-08-17 05:47:57,439 [INFO] Checked 4540/5531 posts -- 2162 have a PDF, 2825 downloaded so far.
2026-08-17 05:48:46,191 [INFO] Checked 4560/5531 posts -- 2166 have a PDF, 2832 downloaded so far.
2026-08-17 05:49:37,338 [INFO] Checked 4580/5531 posts -- 2173 have a PDF, 2839 downloaded so far.
2026-08-17 05:50:26,254 [INFO] Checked 4600/5531 posts -- 2179 have a PDF, 2845 downloaded so far.
2026-08-17 05:51:15,763 [INFO] Checked 4620/5531 posts -- 2186 have a PDF, 2853 downloaded so far.
2026-08-17 05:51:44,786 [INFO] Already downloaded, skipping: SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-Oct.-31-2024.pdf
2026-08-17 05:52:07,484 [INFO] Checked 4640/5531 posts -- 2195 have a PDF, 2865 downloaded so far.
2026-08-17 05:52:58,418 [INFO] Checked 4660/5531 posts -- 2201 have a PDF, 2872 downloaded so far.
2026-08-17 05:53:51,048 [INFO] Checked 4680/5531 posts -- 2211 have a PDF, 2887 downloaded so far.
2026-08-17 05:54:42,850 [INFO] Checked 4700/5531 posts -- 2220 have a PDF, 2897 downloaded so far.
2026-08-17 05:55:32,746 [INFO] Checked 4720/5531 posts -- 2227 have a PDF, 2904 downloaded so far.
2026-08-17 05:56:23,120 [INFO] Checked 4740/5531 posts -- 2237 have a PDF, 2916 downloaded so far.
2026-08-17 05:56:51,685 [INFO] Already downloaded, skipping: MASSY-Notice-of-Annual-Meeting.pdf
2026-08-17 05:56:51,687 [INFO] Already downloaded, skipping: MASSY-Notice-of-Annual-Report.pdf
2026-08-17 05:57:16,903 [INFO] Checked 4760/5531 posts -- 2244 have a PDF, 2931 downloaded so far.
2026-08-17 05:58:07,337 [INFO] Checked 4780/5531 posts -- 2252 have a PDF, 2939 downloaded so far.
2026-08-17 05:58:56,082 [INFO] Checked 4800/5531 posts -- 2256 have a PDF, 2943 downloaded so far.
2026-08-17 05:59:47,909 [INFO] Checked 4820/5531 posts -- 2265 have a PDF, 2952 downloaded so far.
2026-08-17 06:00:53,502 [INFO] Checked 4840/5531 posts -- 2273 have a PDF, 2961 downloaded so far.
2026-08-17 06:01:50,485 [INFO] Checked 4860/5531 posts -- 2291 have a PDF, 2984 downloaded so far.
2026-08-17 06:02:44,257 [INFO] Checked 4880/5531 posts -- 2307 have a PDF, 3014 downloaded so far.
2026-08-17 06:03:37,513 [INFO] Checked 4900/5531 posts -- 2323 have a PDF, 3034 downloaded so far.
2026-08-17 06:03:41,333 [INFO] Already downloaded, skipping: Regency-Petroleum-Company-Limited-RPL-Q3-2024-Report.pdf
2026-08-17 06:04:28,525 [INFO] Checked 4920/5531 posts -- 2334 have a PDF, 3049 downloaded so far.
2026-08-17 06:05:20,890 [INFO] Checked 4940/5531 posts -- 2346 have a PDF, 3064 downloaded so far.
2026-08-17 06:06:16,446 [INFO] Checked 4960/5531 posts -- 2353 have a PDF, 3077 downloaded so far.
2026-08-17 06:07:10,659 [INFO] Checked 4980/5531 posts -- 2363 have a PDF, 3094 downloaded so far.
2026-08-17 06:08:00,535 [INFO] Checked 5000/5531 posts -- 2370 have a PDF, 3101 downloaded so far.
2026-08-17 06:08:49,189 [INFO] Checked 5020/5531 posts -- 2374 have a PDF, 3106 downloaded so far.
2026-08-17 06:09:39,541 [INFO] Checked 5040/5531 posts -- 2382 have a PDF, 3120 downloaded so far.
2026-08-17 06:10:30,496 [INFO] Checked 5060/5531 posts -- 2389 have a PDF, 3129 downloaded so far.
2026-08-17 06:11:21,486 [INFO] Checked 5080/5531 posts -- 2396 have a PDF, 3140 downloaded so far.
2026-08-17 06:12:09,825 [INFO] Checked 5100/5531 posts -- 2400 have a PDF, 3144 downloaded so far.
2026-08-17 06:12:23,289 [INFO] Already downloaded, skipping: JSEs-Monthly-Regulatory-Report-June-2024-3.pdf
2026-08-17 06:13:02,825 [INFO] Checked 5120/5531 posts -- 2412 have a PDF, 3158 downloaded so far.
2026-08-17 06:13:32,589 [INFO] Already downloaded, skipping: MANAGEMENT-DISCUSSION-AND-ANALYSIS-1.pdf
2026-08-17 06:13:32,646 [INFO] Already downloaded, skipping: AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-AUGUST-2024.pdf
2026-08-17 06:13:52,558 [INFO] Checked 5140/5531 posts -- 2420 have a PDF, 3169 downloaded so far.
2026-08-17 06:14:44,343 [INFO] Checked 5160/5531 posts -- 2427 have a PDF, 3176 downloaded so far.
2026-08-17 06:15:33,728 [INFO] Checked 5180/5531 posts -- 2433 have a PDF, 3182 downloaded so far.
2026-08-17 06:16:23,864 [INFO] Checked 5200/5531 posts -- 2439 have a PDF, 3192 downloaded so far.
2026-08-17 06:17:14,906 [INFO] Checked 5220/5531 posts -- 2448 have a PDF, 3201 downloaded so far.
2026-08-17 06:17:25,738 [INFO] Already downloaded, skipping: Caribbean-Producers-Jamaica-Limited-Audited-Financials-for-Year-Ended-June-30-2024-a.pdf
2026-08-17 06:17:39,886 [INFO] Already downloaded, skipping: Paramount-Trading-Jamaica-Limited-Annual-Report-2023-2024.pdf
2026-08-17 06:18:03,326 [INFO] Checked 5240/5531 posts -- 2455 have a PDF, 3211 downloaded so far.
2026-08-17 06:18:54,185 [INFO] Checked 5260/5531 posts -- 2462 have a PDF, 3218 downloaded so far.
2026-08-17 06:18:57,143 [INFO] Already downloaded, skipping: Press-Release-24-09-2024-1.pdf
2026-08-17 06:19:14,321 [INFO] Already downloaded, skipping: ANNUALREPORT2024.DIGITALVERSION-1-1.pdf
2026-08-17 06:19:19,738 [INFO] Already downloaded, skipping: RMOD-Newsletter-May-2024-2-2.pdf
2026-08-17 06:19:44,129 [INFO] Checked 5280/5531 posts -- 2468 have a PDF, 3227 downloaded so far.

2026-08-17 06:19:48,858 [INFO] Already downloaded, skipping: FESCO_Future-Energy-Source-Co-Ltd_Annual-Report-2024_Final.pdf
2026-08-17 06:19:48,865 [INFO] Already downloaded, skipping: FESCO_Notice-of-2024-Annual-General-Meeting.pdf
2026-08-17 06:19:48,871 [INFO] Already downloaded, skipping: FESCO_2024-Form-of-Proxy.pdf
2026-08-17 06:20:02,505 [INFO] Already downloaded, skipping: JSEs-Monthly-Regulatory-Report-May-2024.pdf
2026-08-17 06:20:05,946 [INFO] Already downloaded, skipping: ANNUALREPORT2024.DIGITALVERSION.pdf
2026-08-17 06:20:06,679 [INFO] Already downloaded, skipping: NOTICE-OF-MEETING-2024-4.pdf
2026-08-17 06:20:07,315 [INFO] Already downloaded, skipping: RADIO-JAMAICA-LIMITED-Form-of-Proxy-3.pdf
2026-08-17 06:20:07,957 [INFO] Already downloaded, skipping: ANNOUNCEMENT.CHANGE.AUDITOR.FINAL_-3.pdf
2026-08-17 06:20:23,516 [INFO] Already downloaded, skipping: ISP-2nd-Quarter-Filing-Report-Revised.pdf
2026-08-17 06:20:33,096 [INFO] Already downloaded, skipping: ISP-Annual-Report_2023-Final-Report.pdf
2026-08-17 06:20:37,766 [INFO] Checked 5300/5531 posts -- 2477 have a PDF, 3251 downloaded so far.
2026-08-17 06:20:47,698 [INFO] Already downloaded, skipping: Wigton-Amended-2024-Annual-Report.pdf
2026-08-17 06:20:47,707 [INFO] Already downloaded, skipping: Amended-and-Restated-Notice-of-the-2024-Annual-General-Meeting-and-Explanatory-Circular.pdf
2026-08-17 06:20:47,714 [INFO] Already downloaded, skipping: Form-of-Proxy-2024-AGM.pdf
2026-08-17 06:21:10,448 [INFO] Already downloaded, skipping: General-Accident-Proxy-Form-2024.pdf
2026-08-17 06:21:11,004 [INFO] Already downloaded, skipping: General_Accident-Notice_Of_AGM.pdf
2026-08-17 06:21:28,058 [INFO] Checked 5320/5531 posts -- 2484 have a PDF, 3268 downloaded so far.
2026-08-17 06:21:38,048 [INFO] Already downloaded, skipping: CEO-Business-Report-unaudited-Q3-2024.docx.pdf
2026-08-17 06:21:38,839 [INFO] Already downloaded, skipping: FINAL-JSE-Quarterly-Report-with-Notes-3rd-Quarter-July-2024-Signed.pdf
2026-08-17 06:21:55,866 [INFO] Already downloaded, skipping: The-LAB_Financial-Performance_July-31_.pdf
2026-08-17 06:22:18,802 [INFO] Checked 5340/5531 posts -- 2490 have a PDF, 3278 downloaded so far.
2026-08-17 06:22:29,452 [INFO] Already downloaded, skipping: Nine-Months-Q3-INDIES-PHARMA-Inhouse-Financials_31-July-2024.pdf
2026-08-17 06:22:32,372 [INFO] Already downloaded, skipping: Board-Appointment-for-Rochelle-Burnett-2.pdf
2026-08-17 06:23:08,752 [INFO] Checked 5360/5531 posts -- 2496 have a PDF, 3286 downloaded so far.
2026-08-17 06:23:16,207 [INFO] Already downloaded, skipping: Annual-Report-2023-Notice-to-Shareholders-September-10-2024.pdf
2026-08-17 06:23:31,606 [INFO] Already downloaded, skipping: Notice-of-Annual-General-Meeting-Final.docx-11.pdf
2026-08-17 06:23:43,800 [INFO] Already downloaded, skipping: Board-Appointment-for-Nick-Rowles-Davies-4.pdf
2026-08-17 06:23:56,969 [INFO] Already downloaded, skipping: LUMBER-RESULTS-AS-AT-JULY-312024.pdf
2026-08-17 06:23:59,327 [INFO] Checked 5380/5531 posts -- 2505 have a PDF, 3301 downloaded so far.
2026-08-17 06:24:09,251 [INFO] Already downloaded, skipping: Notice-of-USFDA-Approval-for-Indies-Pharmas-Drug_JSE-Sept-2024.pdf
2026-08-17 06:24:20,302 [INFO] Already downloaded, skipping: NOTICE-2024-ANNUAL-GENERAL-MEETING-1.pdf
2026-08-17 06:24:49,750 [INFO] Already downloaded, skipping: BPOW-RESULTS-AS-AT-JULY-31-2024.pdf
2026-08-17 06:24:49,758 [INFO] Checked 5400/5531 posts -- 2514 have a PDF, 3318 downloaded so far.
2026-08-17 06:25:00,232 [INFO] Already downloaded, skipping: Notice-to-Shareholders.pdf
2026-08-17 06:25:39,262 [INFO] Checked 5420/5531 posts -- 2518 have a PDF, 3323 downloaded so far.
2026-08-17 06:26:28,793 [INFO] Checked 5440/5531 posts -- 2522 have a PDF, 3327 downloaded so far.
2026-08-17 06:26:38,260 [INFO] Already downloaded, skipping: Wisynco-Group-Limited-Audited-Financial-Statements-FY-2024-1.pdf
2026-08-17 06:26:38,358 [INFO] Already downloaded, skipping: Wisynco-Group-Limited-Report-to-Stockholders-for-year-ended-June-30-2024-revised.pdf
2026-08-17 06:27:12,582 [INFO] Already downloaded, skipping: FINAL-JSE-Quarterly-Report-with-Notes-3rd-Quarter-July-2023-JSE-Revision-v2-signed.pdf
2026-08-17 06:27:15,725 [INFO] Already downloaded, skipping: FINAL-JSE-Quarterly-Report-with-Notes-2nd-Quarter-April-2023-JSE-Revision-v2-signed.pdf
2026-08-17 06:27:20,382 [INFO] Checked 5460/5531 posts -- 2531 have a PDF, 3341 downloaded so far.
2026-08-17 06:27:34,127 [INFO] Already downloaded, skipping: Course-Description-The-Secret-to-Master-Salesmanship-Workshop.pdf
2026-08-17 06:27:34,130 [INFO] Already downloaded, skipping: Course-Description-The-Secret-to-Master-Salesmanship-Workshop.pdf
2026-08-17 06:27:34,131 [INFO] Already downloaded, skipping: Profile-of-Mac-Kroupensky-.pdf
2026-08-17 06:27:34,132 [INFO] Already downloaded, skipping: Profile-of-Mac-Kroupensky-.pdf
2026-08-17 06:27:34,133 [INFO] Already downloaded, skipping: Salesmanship-Workshop.pdf
2026-08-17 06:27:34,134 [INFO] Already downloaded, skipping: Salesmanship-Workshop.pdf
2026-08-17 06:27:41,797 [INFO] Already downloaded, skipping: Blue-Power-Group-LimitedBPOW-2024-Annual-Report-Proxy-Form.pdf
2026-08-17 06:27:41,823 [INFO] Already downloaded, skipping: Blue-Power-Group-LimitedBPOW-2024-Annual-Report.pdf
2026-08-17 06:27:44,207 [INFO] Already downloaded, skipping: LUMBER-DEPOT-LIMITED-LUMBER-2024-ANNUAL-REPORT.pdf
2026-08-17 06:27:44,215 [INFO] Already downloaded, skipping: LUMBER-DEPOT-LIMITED-LUMBER-2024-ANNUAL-REPORT-PROXY-FORM.pdf
2026-08-17 06:28:01,072 [INFO] Already downloaded, skipping: Top-10-Shareholders-as-at-April-27-2024.pdf
2026-08-17 06:28:11,252 [INFO] Checked 5480/5531 posts -- 2540 have a PDF, 3368 downloaded so far.
2026-08-17 06:28:14,115 [INFO] Already downloaded, skipping: PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-q3-2024.pdf
2026-08-17 06:28:16,466 [INFO] Already downloaded, skipping: Productive-Business-Solutions-Limited-PBS-letter-to-JSE-Annual-Report.pdf
2026-08-17 06:28:33,993 [INFO] Already downloaded, skipping: SOS-2nd-Qtr-2024-Unaudited-Financials-Signed-Full.pdf
2026-08-17 06:29:01,578 [INFO] Checked 5500/5531 posts -- 2549 have a PDF, 3382 downloaded so far.
2026-08-17 06:29:20,307 [INFO] Already downloaded, skipping: Jetcon-AR2023-Reupload.pdf
2026-08-17 06:29:32,265 [INFO] Already downloaded, skipping: JAMAICA-MONEY-MARKET-BROKERS-LIMITED-Annual-Report-2024-.pdf
2026-08-17 06:29:40,497 [INFO] Already downloaded, skipping: Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager.pdf
2026-08-17 06:29:51,902 [INFO] Already downloaded, skipping: 2024-2nd-Qtr-Statement-June-2024-Final-JSE.pdf
2026-08-17 06:29:51,910 [INFO] Checked 5520/5531 posts -- 2555 have a PDF, 3393 downloaded so far.
2026-08-17 06:30:10,118 [INFO] Already downloaded, skipping: press-release-BAIC-2024.pdf
2026-08-17 06:30:21,781 [INFO] Already downloaded, skipping: iCreate-Group-Unaudited-Q2-Financial-Statements.pdf

Done. Checked 5531 posts.
Posts with at least one PDF link: 2561
Posts with no PDF link at all: 2970
Total PDFs downloaded to /home/areas001/Final Project/Final Notebooks/JSE Data: 3401

### BSE PDF Extraction

In [33]:
# Set the BSE configurations
BSE_BASE_URL = "https://bse.com.bb"
BSE_LISTED_COMPANIES_URL = f"{BSE_BASE_URL}/markets/listed-companies"
BSE_SHARE_SUMMARY_URL = f"{BSE_BASE_URL}/reports/share-summary"

# Set the BSE session
bse_session = requests.Session()
bse_session.headers.update({**BROWSER_HEADERS, "Referer": f"{BSE_BASE_URL}/"})

# Retrieve the list of active BSE companies
def get_active_companies() -> list:
    try:
        resp = bse_session.get(BSE_LISTED_COMPANIES_URL, params={"filter": "all", "mode": "filter"}, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to fetch listed companies page: %s", e)
        return []
    if resp.status_code != 200:
        log.warning("Listed companies page returned status %s", resp.status_code)
        return []

    soup = BeautifulSoup(resp.text, "html.parser")
    companies = []
    in_active_section = False

    for el in soup.find_all(["h1", "h2", "h3", "h4", "table"]):
        if el.name in ("h1", "h2", "h3", "h4"):
            heading_text = el.get_text(strip=True).lower()
            if "active" in heading_text:
                in_active_section = True
                continue
            elif "delisted" in heading_text:
                in_active_section = False
                continue
        elif el.name == "table" and in_active_section:
            for row in el.find_all("tr"):
                cols = row.find_all(["td", "th"])
                if len(cols) < 2:
                    continue
                name_link = cols[0].find("a", href=True)
                if not name_link:
                    continue
                href = name_link["href"]
                match = re.search(r"instrumentCode=([^&]+)", href)
                if not match:
                    continue
                companies.append({
                    "name": name_link.get_text(strip=True),
                    "instrument_code": match.group(1),
                })

    return companies

# Save the BSE active companies
bse_active_companies = get_active_companies()

# Print the number of companies found
print(f"Found {len(bse_active_companies)} active BSE companies.")

Found 26 active BSE companies.

In [34]:
# Define a function to extract the link to each company's financial documents
def get_company_financial_links(instrument_code: str) -> list:
    try:
        resp = bse_session.get(BSE_SHARE_SUMMARY_URL, params={"instrumentCode": instrument_code}, timeout=TIMEOUT)
    except requests.RequestException as e:
        log.warning("Failed to fetch share summary for %s: %s", instrument_code, e)
        return []
    if resp.status_code != 200:
        log.warning("Share summary for %s returned status %s", instrument_code, resp.status_code)
        return []

    soup = BeautifulSoup(resp.text, "html.parser")
    heading = None
    for tag in soup.find_all(["h2", "h3", "h4"]):
        if "financial statements" in tag.get_text(strip=True).lower():
            heading = tag
            break
    if heading is None:
        return []

    table = heading.find_next("table")
    if table is None:
        return []

    links = []
    current_year = None
    for row in table.find_all("tr"):
        cells_ = row.find_all(["td", "th"])
        if not cells_:
            continue
        first_text = cells_[0].get_text(strip=True)
        if re.match(r"^\d{4}$", first_text):
            current_year = first_text
        for cell in cells_:
            a = cell.find("a", href=True)
            if a and a["href"].lower().endswith(".pdf"):
                links.append({
                    "instrument_code": instrument_code,
                    "year": current_year,
                    "doc_type": a.get_text(strip=True),
                    "url": a["href"],
                })
    return links

# Create a variable to save all the BSE links
bse_all_links = []

# For each company find the financial documents URL
for i, company in enumerate(bse_active_companies):
    links = get_company_financial_links(company["instrument_code"])
    bse_all_links.extend(links)
    if (i + 1) % 10 == 0:
        log.info("Processed %s/%s companies -- %s document links found so far.",
                  i + 1, len(bse_active_companies), len(bse_all_links))
    time.sleep(REQUEST_DELAY_SECONDS)

# Print the total number of links found
print(f"Total BSE financial document links found: {len(bse_all_links)}")

2026-08-17 06:30:53,081 [INFO] Processed 10/26 companies -- 98 document links found so far.
2026-08-17 06:31:45,562 [INFO] Processed 20/26 companies -- 148 document links found so far.

Total BSE financial document links found: 148

In [35]:
# Set the BSE PDF download path
bse_pdf_folder = Path("./BSE Data")
bse_downloaded_count = 0

# For each BSE link, download the corresponding PDF
for i, link in enumerate(bse_all_links):
    filename = f"{link['instrument_code']}_{link['year']}_{link['doc_type']}.pdf".replace(" ", "_").replace("/", "-")
    if download_pdf(bse_session, link["url"], bse_pdf_folder, filename):
        bse_downloaded_count += 1

    if (i + 1) % 20 == 0:
        log.info("Processed %s/%s links -- %s PDFs downloaded so far.",
                  i + 1, len(bse_all_links), bse_downloaded_count)
    time.sleep(REQUEST_DELAY_SECONDS)

# Once completed, print the number of files downloaded
print(f"\nDone. Downloaded {bse_downloaded_count} BSE PDFs to {bse_pdf_folder.resolve()}")

2026-08-17 06:33:08,563 [INFO] Processed 20/148 links -- 20 PDFs downloaded so far.
2026-08-17 06:34:04,876 [INFO] Processed 40/148 links -- 40 PDFs downloaded so far.
2026-08-17 06:34:58,402 [INFO] Processed 60/148 links -- 60 PDFs downloaded so far.
2026-08-17 06:35:59,269 [INFO] Processed 80/148 links -- 80 PDFs downloaded so far.
2026-08-17 06:36:55,854 [INFO] Processed 100/148 links -- 100 PDFs downloaded so far.
2026-08-17 06:37:56,094 [INFO] Processed 120/148 links -- 120 PDFs downloaded so far.
2026-08-17 06:38:43,677 [INFO] Processed 140/148 links -- 140 PDFs downloaded so far.

Done. Downloaded 148 BSE PDFs to /home/areas001/Final Project/Final Notebooks/BSE Data

## PDF Text Extraction and Cloud OCR

In [1]:
# Set the PDF paths for each exchange
SOURCES = {
    "jse": Path("./JSE Data"),
    "bse": Path("./BSE Data"),
    "ttse": Path("./TTSE Data/TTSE Annual Reports"),}

TTSE_TRADE_REPORTS_FOLDER = Path("./TTSE Data/TTSE Trade Reports")

pdf_files_by_source = {}

# Create a list of PDF files for each configured source
for source_name, folder in SOURCES.items():
    if not folder.exists():
        print(f"{source_name}: folder {folder} not found -- skipping.")
        pdf_files_by_source[source_name] = []
        continue
    files = sorted(folder.glob("*.pdf"))
    pdf_files_by_source[source_name] = files
    print(f"{source_name}: found {len(files)} PDF(s) in {folder.resolve()}")

if TTSE_TRADE_REPORTS_FOLDER.exists():
    ttse_trade_files = sorted(TTSE_TRADE_REPORTS_FOLDER.glob("*.pdf"))
    print(f"ttse_trade_reports: found {len(ttse_trade_files)} PDF(s) in {TTSE_TRADE_REPORTS_FOLDER.resolve()}")
else:
    ttse_trade_files = []
    print(f"ttse_trade_reports: folder {TTSE_TRADE_REPORTS_FOLDER} not found -- skipping.")

jse: found 3287 PDF(s) in /home/areas001/Final Project/Final Notebooks/JSE Data
bse: found 148 PDF(s) in /home/areas001/Final Project/Final Notebooks/BSE Data
ttse: found 1305 PDF(s) in /home/areas001/Final Project/Final Notebooks/TTSE Data/TTSE Annual Reports
ttse_trade_reports: found 2472 PDF(s) in /home/areas001/Final Project/Final Notebooks/TTSE Data/TTSE Trade Reports

In [3]:
# Import the required packages
import pdfplumber
import fitz

# Define a function to attempt a text direct extraction of the PDFs
def try_direct_extraction(pdf_path: Path) -> str:

    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = "\n".join((page.extract_text() or "") for page in pdf.pages).strip()
        if text:
            return text
    except Exception as e:
        print(f"  pdfplumber failed on {pdf_path.name}: {e}")

    try:
        doc = fitz.open(pdf_path)
        text = "\n".join(page.get_text() for page in doc).strip()
        if text:
            return text
    except Exception as e:
        print(f"  PyMuPDF failed on {pdf_path.name}: {e}")

    return ""

In [4]:
# List month names
MONTH_NAMES = "January|February|March|April|May|June|July|August|September|October|November|December"

# Define a function to extract the date from the financial documents
def extract_date_from_text(text: str):
   
    patterns = [
        rf"(?:as at|as of|year ended|period ended|for the (?:year|nine months|six months|three months) ended)\s+(\d{{1,2}})\s+({MONTH_NAMES}),?\s+(\d{{4}})",
        rf"(?:as at|as of|year ended|period ended|for the (?:year|nine months|six months|three months) ended)\s+({MONTH_NAMES})\s+(\d{{1,2}}),?\s+(\d{{4}})",
    ]
    text_sample = text[:3000]
    for pattern in patterns:
        match = re.search(pattern, text_sample, re.IGNORECASE)
        if match:
            groups = match.groups()
            try:
                if groups[0].isdigit():
                    day, month_str, year = groups
                else:
                    month_str, day, year = groups
                return datetime.strptime(f"{day} {month_str} {year}", "%d %B %Y")
            except (ValueError, AttributeError):
                continue
    return None


# Define a function to extract the date from the file name
def extract_date_from_filename(filename: str):
    """Fallback: parse a date out of the filename/title itself."""
    filename = filename.replace("_", "-")

    match = re.search(rf"({MONTH_NAMES}|[A-Za-z]{{3}})[-\s](\d{{1,2}})[-,\s]+(\d{{4}})", filename, re.IGNORECASE)
    if match:
        month_str, day, year = match.groups()
        for fmt in ("%B-%d-%Y", "%b-%d-%Y"):
            try:
                return datetime.strptime(f"{month_str}-{day}-{year}", fmt)
            except ValueError:
                continue

    match = re.search(rf"({MONTH_NAMES})[-\s](\d{{4}})", filename, re.IGNORECASE)
    if match:
        month_str, year = match.groups()
        try:
            return datetime.strptime(f"1-{month_str}-{year}", "%d-%B-%Y")
        except ValueError:
            pass

    match = re.search(r"\b(20\d{2})\b", filename)
    if match:
        return datetime(int(match.group(1)), 1, 1)

    return None

# Define a function to try text-based extraction first, then filename.
def resolve_chunk_date(chunk_text: str, title: str) -> str:
    date_obj = extract_date_from_text(chunk_text) or extract_date_from_filename(title or "")
    return date_obj.date().isoformat() if date_obj else ""

In [5]:
# Sets the PDF corpus names for each exchange
CORPUS_FILES_TO_BACKFILL = [
    "jse_local_pdf_corpus.json",
    "bse_local_pdf_corpus.json",
    "ttse_local_pdf_corpus.json",]

# If there are missing date fields patch them in the existing corpus
for filename in CORPUS_FILES_TO_BACKFILL:
    path = Path(filename)
    if not path.exists():
        print(f"{filename} not found -- skipping.")
        continue

    with open(path, "r", encoding="utf-8") as f:
        records = json.load(f)

    backfilled = 0
    for r in records:
        if not r.get("date") and r.get("text"):
            r["date"] = resolve_chunk_date(r["text"], r.get("filename", ""))
            if r["date"]:
                backfilled += 1

    with open(path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)

    print(f"{filename}: backfilled dates for {backfilled} of {len(records)} records")

jse_local_pdf_corpus.json: backfilled dates for 2836 of 3287 records
bse_local_pdf_corpus.json: backfilled dates for 146 of 148 records
ttse_local_pdf_corpus.json: backfilled dates for 1180 of 1305 records

In [38]:
# Import the required package
import time as time_module

# Create variables for the records and already completed
records = []
already_done_by_source = {}

# Check if the record was previously extracted
for source_name in pdf_files_by_source:
    out_path = Path(f"{source_name}_local_pdf_corpus.json")
    if out_path.exists():
        with open(out_path, "r", encoding="utf-8") as f:
            existing = json.load(f)
        records.extend(existing)
        already_done_by_source[source_name] = {r["filename"] for r in existing}
        print(f"{source_name}: resuming -- {len(existing)} already processed, will skip these.")
    else:
        already_done_by_source[source_name] = set()
        
# For each unprocessed file, perform direct text extraction
for source_name, files in pdf_files_by_source.items():
    if not files:
        continue
    already_done = already_done_by_source[source_name]
    remaining_files = [f for f in files if f.name not in already_done]
    if not remaining_files:
        print(f"\n=== {source_name.upper()}: all {len(files)} files already processed, skipping ===")
        continue

    print(f"\n=== Processing {source_name.upper()} ({len(remaining_files)} remaining of {len(files)} total) ===")

    for i, pdf_path in enumerate(remaining_files):
        file_start = time_module.time()
        print(f"[{i+1}/{len(remaining_files)}] {pdf_path.name}...", end=" ")

        text = try_direct_extraction(pdf_path)
       
        method = "direct" if text else "needs_ocr_elsewhere"

        elapsed = time_module.time() - file_start
        print(f"{method} ({elapsed:.1f}s)")
        if elapsed > 30:
            print(f"    ^ SLOW FILE -- {pdf_path.name} took {elapsed:.1f}s")

        records.append({
            "id": f"{source_name}-localpdf-{i}",
            "source": source_name,
            "filename": pdf_path.name,
            "filepath": str(pdf_path.resolve()),
            "text": text,
            "date": resolve_chunk_date(text, pdf_path.name),   # <-- add this line
            "retrieved_via": method,
        })

        if (i + 1) % 10 == 0:
            source_records_so_far = [r for r in records if r["source"] == source_name]
            out_path = Path(f"{source_name}_local_pdf_corpus.json")
            out_path.write_text(json.dumps(source_records_so_far, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"  -- checkpoint saved ({len(source_records_so_far)} {source_name} records so far)")

# Print the total number of records completed
print(f"\nDone. Total records (including resumed): {len(records)}")
for source_name in pdf_files_by_source:
    source_records = [r for r in records if r["source"] == source_name]
    if not source_records:
        continue
    print(f"\n{source_name.upper()}:")
    print(f"  Direct: {sum(1 for r in source_records if r['retrieved_via'] == 'direct')}")
    print(f"  Needs Cloud OCR: {sum(1 for r in source_records if r['retrieved_via'] == 'needs_ocr_elsewhere')}")

=== Processing JSE (3287 remaining of 3287 total) ===
[1/3287] 0725-Public-Notice-AR-AGM-1.pdf... direct (0.0s)
[2/3287] 1-Class-C-Shareholder-Advisory.pdf... direct (0.2s)
[3/3287] 1-SYGNUS-Class-C-Notice-of-Adjourned-Meeting.pdf... direct (0.2s)
[4/3287] 138-Quarterly-Report-December-2025.pdf... direct (1.2s)
[5/3287] 138-Quarterly-Report-June-2025.pdf... direct (1.4s)
[6/3287] 138-Quarterly-Report-June-2026-Final.pdf... direct (1.5s)
[7/3287] 138-Quarterly-Report-March-2025.pdf... direct (1.4s)
[8/3287] 138-Quarterly-Report-March-2026.pdf... direct (1.2s)
[9/3287] 138-Quarterly-Report-September-2025-JSE.pdf... direct (2.2s)
[10/3287] 138-SL-Corporate-Governance-Policy-Manual-February-11-2025-Revised.pdf... direct (4.0s)
  -- checkpoint saved (10 jse records so far)
[11/3287] 138-Student-Living-Annual-Report-September-2025.pdf... direct (10.2s)
[12/3287] 138-Student-Living-Jamaica-2024-Final.pdf... direct (6.5s)
[13/3287] 138-Student-Living-Jamaica-2025-Final.pdf... direct (8.5s)
[14/3287] 138-Student-Living-Jamaica-Limited-Annual-Report-2024.pdf... direct (9.2s)
[15/3287] 138-Student-Living-Jamaica-Limited-Quarterly-Report-%E2%80%93-December-31-2024.pdf... direct (1.1s)
[16/3287] 138-Student-Living-Jamaica-Limited-Quarterly-Report-September-30-2024.pdf... direct (1.2s)
[17/3287] 1GS-2024-Audited-Financial-Statements.pdf... direct (7.8s)
[18/3287] 1GS-2024-Equity-Report-Summary.pdf... direct (0.1s)
[19/3287] 1GS-Annual-Report-2024.pdf... direct (10.7s)
[20/3287] 1GS-Annual-Report-2025.pdf... direct (10.7s)
  -- checkpoint saved (20 jse records so far)
[21/3287] 1GS-FY-2025-Audited-Financials-Amended.pdf... direct (8.3s)
[22/3287] 1GS-Interim-Shareholders-Report-FY-2025-Amended.pdf... direct (0.9s)
[23/3287] 1GS-Interim-Shareholders-Report-Q1-2026.pdf... direct (1.5s)
[24/3287] 1GS-Interim-Shareholders-Report-Q1_2025.pdf... direct (1.5s)
[25/3287] 1GS-Interim-Shareholders-Report-Q2-2025.pdf... direct (1.4s)
[26/3287] 1GS-Interim-Shareholders-Report-Q2-2026.pdf... direct (1.7s)
[27/3287] 1GS-Interim-Shareholders-Report-Q3-2024.pdf... direct (1.7s)
[28/3287] 1GS-Interim-Shareholders-Report-Q3-2025.pdf... direct (1.4s)
[29/3287] 1GS-Q1-2026-Quarterly-Equity-Report-Summary.pdf... direct (0.1s)
[30/3287] 1GS-Q1_2025-Quarterly-Equity-Report-Summary.pdf... direct (0.3s)
  -- checkpoint saved (30 jse records so far)
[31/3287] 1GS-Q2-2025-Quarterly-Equity-Report-Summary.pdf... direct (0.1s)
[32/3287] 1GS-Q2-2026-Quarterly-Equity-Report-Summary.pdf... direct (0.2s)
[33/3287] 1GS-Q3-2024-Quarterly-Equity-Report-Summary.pdf... direct (0.1s)
[34/3287] 1GS-Q3-2025-Quarterly-Equity-Report-Summary.pdf... direct (0.1s)
[35/3287] 1GS-Shareholders-Report-FY-2024.pdf... direct (0.7s)
[36/3287] 1st-Qrt-Fin-Statement-ending-March-2025-Signed-1.pdf... direct (0.7s)
[37/3287] 2-Class-D-Shareholder-Advisory.pdf... direct (0.2s)
[38/3287] 2-SYGNUS-Class-D-Notice-of-Adjourned-Meeting.pdf... direct (0.3s)
[39/3287] 2024-10-16-Fosrich-Notice-Dividend-Meeting.pdf... direct (0.0s)
[40/3287] 2024-2nd-Qtr-Statement-June-2024-Final-JSE.pdf... direct (0.8s)
  -- checkpoint saved (40 jse records so far)
[41/3287] 2024-2nd-Qtr-Statement-June-2024-Signed.pdf... direct (0.8s)
[42/3287] 2024-3rd-Qrt-Fin-Statement-ending-Sep-2024-Signed.pdf... direct (0.8s)
[43/3287] 2024-CHL-December-Q1-1.pdf... needs_ocr_elsewhere (0.0s)
[44/3287] 2024-CHL-Sept-Q4.pdf... needs_ocr_elsewhere (0.0s)
[45/3287] 2024-Cargo-Handlers-Limited.pdf... direct (6.1s)
[46/3287] 2024-Cargo-Handlers-Ltd.pdf... needs_ocr_elsewhere (0.1s)
[47/3287] 2024-Consolidated-Financial-Statements-FINAL-Derrimon-Trading-Company.pdf... direct (10.0s)
[48/3287] 2024-DECEMBER-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[49/3287] 2024-December-31-DCOVE-Audited-Financial-Statements.pdf... direct (5.5s)
[50/3287] 2024-December-31-DCOVE-Directors-Holdings.pdf... direct (0.2s)
  -- checkpoint saved (50 jse records so far)
[51/3287] 2024-December-31-DCOVE-Senior-Managers-Holdings.pdf... direct (0.1s)
[52/3287] 2024-December-31-DCOVE-Top-10-Shareholdings.pdf... direct (0.1s)
[53/3287] 2024-December-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[54/3287] 2024-JMMB-Annual-Report_Smart-Growth_Fb2.pdf... direct (79.4s)
    ^ SLOW FILE -- 2024-JMMB-Annual-Report_Smart-Growth_Fb2.pdf took 79.4s
[55/3287] 2024-JSE-Group-Financial-Statements-Signed-Final.pdf... direct (25.7s)
[56/3287] 2024-SEPTEMBER-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[57/3287] 2024-September-30-DCOVE-Directors-Holdings.pdf... direct (0.3s)
[58/3287] 2024-September-30-DCOVE-Quarterly-Report-to-Stockholders.pdf... direct (2.4s)
[59/3287] 2024-September-30-DCOVE-Senior-Managers-Holdings.pdf... direct (0.2s)
[60/3287] 2024-September-30-DCOVE-Top-10-Shareholdings-1.pdf... direct (0.1s)
  -- checkpoint saved (60 jse records so far)
[61/3287] 2024-September-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[62/3287] 2024-VMIL-Annual-Report.pdf... direct (87.4s)
    ^ SLOW FILE -- 2024-VMIL-Annual-Report.pdf took 87.4s
[63/3287] 2024_ANNUAL-REPORT_Indies-Pharma-Ja-Ltd-2.pdf... direct (13.9s)
[64/3287] 2025-10-06-Pulse-Investments-Limited-Updated-Announcement-on-Publication-of-Audited-Financial-Statements-Oct-3-2025_.pdf... direct (0.1s)
[65/3287] 2025-3rd-Qrt-Fin-Statement-ending-September-2025-Signed-1.pdf... direct (1.3s)
[66/3287] 2025-4th-Qrt-Fin-Statement-ending-December-2025-Signed.pdf... direct (0.8s)
[67/3287] 2025-AGM-Advisory.pdf... direct (0.1s)
[68/3287] 2025-Audited-Financials_Indies-Pharma-JA-Ltd.pdf... direct (7.6s)
[69/3287] 2025-CCCL-Summary-Group-Audited-Financialspdf.pdf... direct (1.5s)
[70/3287] 2025-CEO-Message-Q1-Signed.docx.pdf... direct (0.2s)
  -- checkpoint saved (70 jse records so far)
[71/3287] 2025-CHL-June-Q3.pdf... needs_ocr_elsewhere (0.0s)
[72/3287] 2025-CHL-March-Q2.pdf... needs_ocr_elsewhere (0.0s)
[73/3287] 2025-CHL-Sept-Q4.pdf... needs_ocr_elsewhere (0.0s)
[74/3287] 2025-Cargo-Handlers-Limited.pdf... direct (6.0s)
[75/3287] 2025-DECEMBER-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[76/3287] 2025-DECEMBER-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[77/3287] 2025-General-Information-Venture-Capital-Pitch-Room_.pdf... direct (0.3s)
[78/3287] 2025-JSE-Group-Audited-Financial-Statements-Final-Signed-Amended.pdf... direct (24.4s)
[79/3287] 2025-JUNE-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[80/3287] 2025-JUNE-Top-Ten-10-Stockholders.pdf... direct (0.1s)
  -- checkpoint saved (80 jse records so far)
[81/3287] 2025-June-30-DCOVE-Directors-Holdings.pdf... direct (0.1s)
[82/3287] 2025-June-30-DCOVE-Quarterly-Report-to-Stockholders-1.pdf... needs_ocr_elsewhere (0.0s)
[83/3287] 2025-June-30-DCOVE-Senior-Managers-Holdings.pdf... direct (0.1s)
[84/3287] 2025-June-30-DCOVE-Top-10-Shareholdings.pdf... direct (0.1s)
[85/3287] 2025-MARCH-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[86/3287] 2025-MARCH-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[87/3287] 2025-Management-Report-Top-10-Share-Holdings-1.pdf... direct (0.7s)
[88/3287] 2025-March-31-DCOVE-Directors-Holdings.pdf... direct (0.2s)
[89/3287] 2025-March-31-DCOVE-Quarterly-Report-to-Stockholders.pdf... needs_ocr_elsewhere (0.0s)
[90/3287] 2025-March-31-DCOVE-Senior-Managers-Holdings.pdf... direct (0.1s)
  -- checkpoint saved (90 jse records so far)
[91/3287] 2025-March-31-DCOVE-Top-10-Shareholdings.pdf... direct (0.1s)
[92/3287] 2025-PJX-Annual-Report.pdf... direct (7.4s)
[93/3287] 2025-Purity-Consolidated-Bakeries-Notice-033126.pdf... direct (0.0s)
[94/3287] 2025-Q2-Report-ECPF-Value-Fund-JSE-Final.pdf... direct (4.0s)
[95/3287] 2025-Q3-Report-ECPF-Value-Fund-JSE-Final.pdf... direct (4.1s)
[96/3287] 2025-Q4-Report-ECPF-Value-Fund-JSE-FINAL.pdf... direct (4.1s)
[97/3287] 2025-SEPTEMBER-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.2s)
[98/3287] 2025-SEPTEMBER-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[99/3287] 2025-Venture-Capital-Pitch-Room-Application-Form.pdf... direct (0.1s)
[100/3287] 2025-signed-4th-Qrt-Fin-Statement-ending-Dec-2024.pdf... direct (0.6s)
  -- checkpoint saved (100 jse records so far)
[101/3287] 202502Q-Fin-Statement-ending-June-2025-Signed.pdf... direct (0.8s)
[102/3287] 20250825.pdf... direct (1.3s)
[103/3287] 20250826.pdf... direct (1.3s)
[104/3287] 20250827.pdf... direct (1.3s)
[105/3287] 2026-AGM-Notice-STSJL-Updated-Resolution-2D-2.pdf... direct (0.2s)
[106/3287] 2026-JUNE-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[107/3287] 2026-JUNE-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[108/3287] 2026-MARCH-DIRECTORS-SNR-OFFICERS-INTERESTS.pdf... direct (0.1s)
[109/3287] 2026-MARCH-Top-Ten-10-Stockholders.pdf... direct (0.1s)
[110/3287] 2026-Q1-Report-ECPF-Value-Fund-JSE-FINAL.pdf... direct (4.4s)
  -- checkpoint saved (110 jse records so far)
[111/3287] 2026-Q2-Report-ECPF-Value-Fund-JSE-FINAL.pdf... direct (4.3s)
[112/3287] 2026-Q3-Report-ECPF-Value-Fund-JSE-FINAL.pdf... direct (3.4s)
[113/3287] 2026SpurTreeSpicesPerformanceReportQ2.pdf... direct (6.9s)
[114/3287] 260703_MPCCEL_MaterialChange_108x70.pdf... direct (0.1s)
[115/3287] 2nd-UPDATED-Spur-Tree-Spices-Q1-Report-March-2024.pdf... direct (2.1s)
[116/3287] 3-Class-C-Notice-of-GM.pdf... direct (0.3s)
[117/3287] 3-Class-C-Proxy-Form.pdf... direct (0.1s)
[118/3287] 3rd-Qtr-Financials-Signed.pdf... direct (1.3s)
[119/3287] 4-Class-D-Notice-of-GM.pdf... direct (0.3s)
[120/3287] 4-Class-D-Proxy-Form.pdf... direct (0.1s)
  -- checkpoint saved (120 jse records so far)
[121/3287] 48th-AGM-1.pdf... direct (0.4s)
[122/3287] 4th-QTR-MRC-Registration-Form-2024.pdf... direct (0.1s)
[123/3287] 5-Class-C-Proxy-Form.pdf... direct (0.2s)
[124/3287] 6-Class-D-Proxy-Form-1.pdf... direct (0.1s)
[125/3287] A.-Tulloch-Stephen-Levy-Resignation.pdf... needs_ocr_elsewhere (0.0s)
[126/3287] A.-Tulloch-Syd-Mogg-Resignation.pdf... needs_ocr_elsewhere (0.0s)
[127/3287] A.S.-Bryden-Sons-Holdings-Limited-2024-Annual-Report.pdf... direct (172.5s)
    ^ SLOW FILE -- A.S.-Bryden-Sons-Holdings-Limited-2024-Annual-Report.pdf took 172.5s
[128/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-%E2%80%93-Addendum-to-Directors-Circular-2.pdf... direct (0.2s)
[129/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-%E2%80%93-Unaudited-Interim-Financial-Report-for-there-Quarter-Ended-December-31-2024.pdf... direct (1.6s)
[130/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Directors-Circular.pdf... direct (2.7s)
  -- checkpoint saved (130 jse records so far)
[131/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-EGM-January-2025.pdf... direct (0.0s)
[132/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Interim-Unaudited-Report-March-31-2025.pdf... direct (1.0s)
[133/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Notice-of-Extension-of-Annual-Report.pdf... direct (0.0s)
[134/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Notice-of-Extension-of-Closing-Date-of-Seprod-Limited-Take-Over-Bid.pdf... direct (0.3s)
[135/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Notice-of-Material-Change.pdf... direct (0.1s)
[136/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Proxy-Form.pdf... direct (0.1s)
[137/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Updated-Form-of-Proxy-1.pdf... direct (0.1s)
[138/3287] A.S.-Bryden-Sons-Holdings-Limited-ASBH-Updated-Form-of-Proxy.pdf... direct (0.1s)
[139/3287] A.S.-Bryden-Sons-Holdings-Limited-Appointment-of-Thomas-Tyler-as-Director.pdf... direct (0.1s)
[140/3287] A.S.-Bryden-Sons-Holdings-Limited-Audited-Consolidated-Financial-Statements-for-the-year-ended-December-31-2024.pdf... direct (15.2s)
  -- checkpoint saved (140 jse records so far)
[141/3287] A.S.-Bryden-and-Sons-Holding-Limited-ASBH-Ordinary-Declaration-of-Dividend-1.pdf... direct (0.1s)
[142/3287] A.S.-Bryden-and-Sons-Holdings-Limited-ASBH-Q3-Interim-Financial-Report-4.pdf... direct (1.2s)
[143/3287] AFS2025-Annual-Report-WEB.pdf... direct (14.5s)
[144/3287] AFS2025-Annual-Report.pdf... direct (14.1s)
[145/3287] AGM-EFRESH-Cover-letter-2025.pdf... direct (0.1s)
[146/3287] AGM-EFRESH-Shareholders-Cover-letter-2024.pdf... direct (0.1s)
[147/3287] AGM-Letter-to-Shareholders-2025-138SL-1.pdf... direct (0.1s)
[148/3287] AGM-NOTICE-FULL.pdf... direct (0.1s)
[149/3287] AGM-Notice-2025.pdf... needs_ocr_elsewhere (5.5s)
[150/3287] AGM-Notice-dated-August-11-2026-Final-1.pdf... direct (0.9s)
  -- checkpoint saved (150 jse records so far)
[151/3287] AGM-Notice-dated-August-12-2025-executed-version.pdf... direct (0.6s)
[152/3287] AGM-Notice.pdf... direct (0.8s)
[153/3287] AGM-PROXY-FORM-2026.pdf... direct (0.1s)
[154/3287] AHPC-Appointment-of-New-Auditors.pdf... direct (0.1s)
[155/3287] AHPC-Audited-Financial-Statements-Dec-31-2025.pdf... needs_ocr_elsewhere (89.7s)
    ^ SLOW FILE -- AHPC-Audited-Financial-Statements-Dec-31-2025.pdf took 89.7s
[156/3287] AHPC-Corporate-Governance-Policy.pdf... direct (0.5s)
[157/3287] AHPC-Notice-to-shareholders-re-delay-in-filing-Audited-FS-2025.pdf... direct (0.1s)
[158/3287] AHPC-Unaudited-2nd-qrt-Financial-Stat-June-30-2026.pdf... needs_ocr_elsewhere (25.1s)
[159/3287] AHPC-Unaudited-Financials-Third-Quarter-Report-Septemer-30-2025.pdf... needs_ocr_elsewhere (9.3s)
[160/3287] AHPC-Unaudited-Fourth-Quarter-Financials-Dec-31-2025.pdf... needs_ocr_elsewhere (9.6s)
  -- checkpoint saved (160 jse records so far)
[161/3287] AMG-Annual-Report-2024.pdf... direct (2.0s)
[162/3287] AMG-PACKAGING-Annual-Report-2025.pdf... direct (1.7s)
[163/3287] AMGS-DIRECTORS-SHAREHOLDINGS-AT-30-NOVEMBER-2024.pdf... needs_ocr_elsewhere (0.0s)
[164/3287] AMGS-DIRECTORS-SHAREHOLDINGS-AT-30-NOVEMBER-2025.pdf... direct (0.1s)
[165/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-28-FEBRUARY-2025.pdf... direct (0.2s)
[166/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-28-FEBRUARY-2026-1.pdf... direct (0.1s)
[167/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-AUGUST-2024.pdf... direct (0.1s)
[168/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-AUGUST-2025.pdf... direct (0.1s)
[169/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-MAY-2025.pdf... needs_ocr_elsewhere (0.0s)
[170/3287] AMGS-DIRECTORS-TO-SHAREHOLDINGS-AT-31-MAY-2026-1.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (170 jse records so far)
[171/3287] AMGS-NOTICE-CHANGE-OF-FINANCIAL-CONTROLLER.pdf... needs_ocr_elsewhere (0.0s)
[172/3287] AMGS-TOP-10-AT-28-FEBRUARY-2025.pdf... direct (0.1s)
[173/3287] AMGS-TOP-10-AT-28-FEBRUARY-2026-1.pdf... direct (0.1s)
[174/3287] AMGS-TOP-10-AT-30-NOVEMBER-2024.pdf... needs_ocr_elsewhere (0.0s)
[175/3287] AMGS-TOP-10-AT-30-NOVEMBER-2025.pdf... direct (0.1s)
[176/3287] AMGS-TOP-10-AT-31-AUGUST-2024.pdf... needs_ocr_elsewhere (0.0s)
[177/3287] AMGS-TOP-10-AT-31-AUGUST-2025.pdf... direct (0.1s)
[178/3287] AMGS-TOP-10-AT-31-MAY-2025.pdf... needs_ocr_elsewhere (0.0s)
[179/3287] AMGS-TOP-10-AT-31-MAY-2026-1.pdf... needs_ocr_elsewhere (0.0s)
[180/3287] ANNOUNCEMENT.CHANGE.AUDITOR.FINAL_-3.pdf... direct (0.1s)
  -- checkpoint saved (180 jse records so far)
[181/3287] ANNUAL-REPORT-2025-final.pdf... direct (8.0s)
[182/3287] ANNUAL-REPORT-Atlantic-Hardware-Plumbing-Company-Limited-December-31-2025.pdf... direct (3.6s)
[183/3287] ANNUAL-REPORT-FOR-THE-YEAR-ENDED-JUNE-30-2024.pdf... direct (10.2s)
[184/3287] ANNUAL-REPORT_2024_FINAL-1.pdf... direct (9.2s)
[185/3287] ANNUALREPORT-2025.FINAL-VERSION-compressed.pdf... direct (20.5s)
[186/3287] ANNUALREPORT2024.DIGITALVERSION-1-1.pdf... direct (20.3s)
[187/3287] ANNUALREPORT2024.DIGITALVERSION.pdf... direct (10.7s)
[188/3287] AR-2024-FINAL.pdf... direct (28.0s)
[189/3287] ASBH-AGM-2026-Agenda.pdf... direct (0.1s)
[190/3287] ASBH-AGM-2026-Proxy-Form-1.pdf... direct (0.1s)
  -- checkpoint saved (190 jse records so far)
[191/3287] ASBH-Acquires-50-Stake-in-Armstrong-Agencies-Ltd.pdf... direct (0.2s)
[192/3287] ASBH-Annual-Report-2025.pdf... direct (268.3s)
    ^ SLOW FILE -- ASBH-Annual-Report-2025.pdf took 268.3s
[193/3287] ASBH-Audited-Consolidated-FS-2025.pdf... direct (20.2s)
[194/3287] ASBH-Corporate-Governance-Policy.pdf... direct (1.0s)
[195/3287] ASBH-Interim-Financial-Report-for-the-period-ended-30-June-2025.pdf... direct (2.1s)
[196/3287] ASBH-Interim-Report-Sep-30-2025.pdf... direct (1.3s)
[197/3287] ASBH-Interim-Unaudited-Financial-Report-for-the-Second-Quarter-Ended-June-30-2026-Updated.pdf... direct (1.5s)
[198/3287] ASBH-JSE-Interim-Report-for-the-period-ended-December-31-2025-2.pdf... direct (1.3s)
[199/3287] ASBH-Letter-Delay-of-Audited-FS-2025-JSE-dd-May-1-2026.pdf... direct (0.1s)
[200/3287] ASBH-Letter-Delay-of-Audited-FS-2025-JSE.pdf... direct (0.1s)

  -- checkpoint saved (200 jse records so far)
[201/3287] ASBH-Letter-JSE-dd-April-16-2026-Declaration-of-Dividend-1.pdf... direct (0.2s)
[202/3287] ASBH-Letter-JSE-dd-April-16-2026-Delay-in-Submission-of-2025-Annual-Report-1.pdf... direct (0.1s)
[203/3287] ASBH-Letter-JSE-dd-April-8-2026-Consideration-of-Dividend.pdf... direct (0.1s)
[204/3287] ASBH-Letter-JSE-dd-January-12-2026-Consideration-of-Dividend.pdf... direct (0.0s)
[205/3287] ASBH-Letter-JSE-dd-January-19-2026-Declaration-of-Dividend-1.pdf... direct (0.1s)
[206/3287] ASBH-Letter-JSE-dd-July-15-2026-Consideration-of-Dividend.pdf... direct (0.1s)
[207/3287] ASBH-Letter-JSE-dd-July-15-2026-Declaration-of-Dividend.pdf... direct (0.2s)
[208/3287] ASBH-Letter-JSE-dd-July-22-2026-Declaration-of-Ord-Dividend.pdf... direct (0.2s)
[209/3287] ASBH-Letter-JSE-dd-July-8-2026-Consideration-of-Dividend.pdf... direct (0.1s)
[210/3287] ASBH-Letter-JSE-dd-October-10-2025-Consideration-of-Dividend.pdf... direct (0.0s)
  -- checkpoint saved (210 jse records so far)
[211/3287] ASBH-Letter-JSE-dd-October-17-2025-Preference-Dividend-Declaration.pdf... direct (0.2s)
[212/3287] ASBH-Letter-dd-Apr-16-2025-Consideration-of-Dividend.pdf... direct (0.0s)
[213/3287] ASBH-Letter-dd-Apr-28-2025-Preference-Dividend-Declaration.pdf... direct (0.0s)
[214/3287] ASBH-Letter-dd-Dec-16-2025-Consideration-of-Ordinary-Dividend.pdf... direct (0.0s)
[215/3287] ASBH-Letter-dd-Dec-23-2025-Declaration-of-Dividend-JSE-Amended.pdf... direct (0.1s)
[216/3287] ASBH-Letter-dd-Jan-29-2025-Preference-Dividend-JSC.pdf... direct (0.0s)
[217/3287] ASBH-Letter-dd-July-22-2025-Consideration-of-Dividend.pdf... direct (0.0s)
[218/3287] ASBH-Letter-dd-July-29-2025-Preference-Dividend-Declaration.pdf... direct (0.1s)
[219/3287] ASBH-Letter-dd-Jun-11-2025-Consideration-of-Ordinary-Dividend.pdf... direct (0.0s)
[220/3287] ASBH-Letter-dd-Jun-18-2025-Declaration-of-Dividend-1.pdf... direct (0.1s)
  -- checkpoint saved (220 jse records so far)
[221/3287] ASBH-Letter-dd-March-24-2026-Appointment-of-Group-CEO-JSE.pdf... direct (0.1s)
[222/3287] ASBH-Letter-dd-Nov-11-2024-Consideration-of-Ordinary-Dividend.pdf... direct (0.0s)
[223/3287] ASBH-Letter-dd-Oct-17-2024-Dividend-Declaration.pdf... direct (0.0s)
[224/3287] ASBH-Letter-dd-Oct-8-2024-Consideration-of-Dividend.pdf... direct (0.1s)
[225/3287] ASBH-Letter-to-JSE-Appointment-of-CFO-29.06.pdf... direct (0.1s)
[226/3287] ASBH-Letter-to-JSE-Appointment-of-Corp-Sec-dd-14.7.2026.pdf... direct (0.1s)
[227/3287] ASBH-Material-Change-Jul-31-2025-Thomas-Tyler.pdf... direct (0.0s)
[228/3287] ASBH-NoAGM-2026.pdf... needs_ocr_elsewhere (1.4s)
[229/3287] ASBH-Notice-of-Material-Disclosure.pdf... direct (0.1s)
[230/3287] ASBH-Q12026-Interim-Report.pdf... direct (1.2s)
  -- checkpoint saved (230 jse records so far)
[231/3287] ASBH-Release-Dec-6-2024.pdf... needs_ocr_elsewhere (0.0s)
[232/3287] ASBH-TAKE-OVER-BID-OFFER-CIRCULAR.pdf... direct (33.6s)
    ^ SLOW FILE -- ASBH-TAKE-OVER-BID-OFFER-CIRCULAR.pdf took 33.6s
[233/3287] ASBH-letter-to-JSE-Resignation-of-CFO-Corporate-Secretary.pdf... direct (0.0s)
[234/3287] ASBH-letter-to-JSE-dd-April-20-2026-final-1.pdf... direct (0.1s)
[235/3287] AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024.pdf... needs_ocr_elsewhere (0.0s)
[236/3287] AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025.pdf... needs_ocr_elsewhere (0.0s)
[237/3287] Access-Financial-Services-Limited-Audited-Financial-Statements-for-Year-Ended-March-31-2025.pdf... direct (8.7s)
[238/3287] Access-Financial-Services-Limited-Audited-Financial-Statements-for-Year-Ended-March-31-2026.pdf... direct (8.6s)
[239/3287] Access-Financial-Services-Limited-Top-Ten-Shareholders-as-at-December-31-2024.pdf... direct (0.1s)
[240/3287] Access-Financial-Services-Limited-Top-Ten-Shareholders-as-at-June-2025.pdf... direct (0.1s)
  -- checkpoint saved (240 jse records so far)
[241/3287] Access-Financial-Services-Limited-Top-Ten-Shareholders-as-at-March-31-2025.pdf... direct (0.1s)
[242/3287] Access-Financial-Services-Limited-Top-Ten-Shareholders-as-at-March-31-2026.pdf... direct (0.2s)
[243/3287] Access-Financial-Services-Limited-Top-Ten-Shareholders-as-at-September-30-2024.pdf... direct (0.1s)
[244/3287] Access-Financial-Services-Limited-Unaudited-Financial-Statements-for-Quarter-Ended-December-31-2024.pdf... direct (2.2s)
[245/3287] Access-Financial-Services-Limited-Unaudited-Financial-Statements-for-Quarter-Ended-December-31-2025.pdf... direct (2.1s)
[246/3287] Access-Financial-Services-Limited-Unaudited-Financial-Statements-for-Quarter-Ended-June-30-2025.pdf... direct (2.1s)
[247/3287] Access-Financial-Services-Limited-Unaudited-Financial-Statements-for-Quarter-Ended-September-30-2024-Revised.pdf... direct (1.5s)
[248/3287] Access-Financial-Services-Limited-Unaudited-Financial-Statements-for-Quarter-Ended-September-30-2025.pdf... direct (2.1s)
[249/3287] Addendum-1-to-Take-Over-Bid-Circular-issued-by-Seprod-Limited-on-May-1-2025-in.pdf... direct (0.3s)
[250/3287] Addendum-to-Barita-Bond-Prospectus.pdf... direct (0.2s)
  -- checkpoint saved (250 jse records so far)
[251/3287] Addendum-to-OFS-TJH-7-Mar-251937057.1.pdf... direct (0.2s)
[252/3287] Addendum-to-Prospectus-Tropical-Battery-Company-June-19-2025.pdf... needs_ocr_elsewhere (0.0s)
[253/3287] Additional-Delay-Notice.Shareholders.2026-1.pdf... direct (0.1s)
[254/3287] AdditionalDelayNotice.Shareholders.2025.pdf... direct (0.0s)
[255/3287] Advisory-Private-Equity-Investment-in-Polaris-at-East-Point.pdf... direct (0.1s)
[256/3287] Advisory-Tom-Tyler-Steps-Down-from-the-CPJ-Board-of-Directors.pdf... needs_ocr_elsewhere (0.0s)
[257/3287] Advisory-to-the-JSE-re-Takeover-Offer.pdf... direct (0.2s)
[258/3287] Advisory_RPL_AGM_May19_2025.pdf... direct (0.0s)
[259/3287] Agenda-JSE-and-Partners-USA-Outreach-2025-Philadelphia-May-6-and-NewYork-May-8.pdf... direct (0.8s)
[260/3287] Agenda-NEW-YORK-May-8-2025.pdf... direct (0.6s)
  -- checkpoint saved (260 jse records so far)
[261/3287] Amended-Directors-Holding-as-at-December-31-2024.pdf... direct (0.3s)
[262/3287] Amended-Form-of-Proxy-November-15-2025.pdf... direct (0.3s)
[263/3287] Amended-Notice-of-AGM-2025.pdf... needs_ocr_elsewhere (2.5s)
[264/3287] Amended-Notice-of-Annual-General-Meeting-2025.pdf... direct (1.1s)
[265/3287] Amended-Senior-Managers-Holding-as-at-December-31-2024.pdf... direct (0.2s)
[266/3287] Amended-Senior-Managers-Holding-as-at-December-31-2025.pdf... direct (0.2s)
[267/3287] Amended-WIG-Unaudited-Financial-Statements-for-the-period-ended-June-30-2026-and-Shareholdings-of-Top-10-Shareholders-Directors-and-Senior-Managers-1.pdf... direct (11.1s)
[268/3287] Amended-and-Restated-Notice-of-the-2024-Annual-General-Meeting-and-Explanatory-Circular.pdf... direct (0.6s)
[269/3287] Annual-Report-2023-Notice-to-Shareholders-September-10-2024.pdf... direct (0.0s)
[270/3287] Annual-Report-2024-DCOVE-1.pdf... direct (154.9s)
    ^ SLOW FILE -- Annual-Report-2024-DCOVE-1.pdf took 154.9s
  -- checkpoint saved (270 jse records so far)
[271/3287] Annual-Report-2024-Final-DCOVE.pdf... direct (155.6s)
    ^ SLOW FILE -- Annual-Report-2024-Final-DCOVE.pdf took 155.6s
[272/3287] Annual-Report_FinalV2.pdf... direct (14.8s)
[273/3287] Appointment-of-Deputy-Chairman-October-31-2024-1.pdf... direct (0.1s)
[274/3287] Appointment-of-Director-Mark-Hart.pdf... direct (0.1s)
[275/3287] Appointment-of-Snr.-Management-Officers-Scotiabank-2026.pdf... direct (0.2s)
[276/3287] Appointment-of-Snr.-Officer-Dayne-Bucknor-2025.pdf... direct (0.1s)
[277/3287] Appointment-of-Snr.-Officer-Morris-Nelson-October-1-2025.pdf... direct (0.1s)
[278/3287] Appointment-of-Snr.-Officer-Yanique-Forbes-Patrick-July-2025.pdf... direct (0.1s)
[279/3287] Appointment-of-Snr.-Officer-Yvett-Anderson-Feb.-2025.pdf... direct (0.1s)
[280/3287] April_2025_analysis.pdf... direct (2.5s)
  -- checkpoint saved (280 jse records so far)
[281/3287] April_2026_analysis.pdf... direct (2.4s)
[282/3287] Atlantic-Hardware-Plumbing-AHPC-Unaudited-Financial-Statements-for-the-Second-Quarter-ended-June-30-2025.pdf... needs_ocr_elsewhere (13.1s)
[283/3287] Atlantic-Hardware-Plumbing-Co.-Ltd.-Basis-of-Allotment.pdf... direct (0.1s)
[284/3287] Atlantic-Hardware-Plumbing-Company-Limited-JSE-Unaudited-Financial-Report-for-Period-Ended-March-31-2026.pdf... direct (1.0s)
[285/3287] Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024.pdf... needs_ocr_elsewhere (0.0s)
[286/3287] Audited-2025-Financial-Statements-Pulse-Investments-Limited.pdf... direct (7.3s)
[287/3287] Audited-Financial-Statements-February-28-2025.pdf... direct (3.9s)
[288/3287] Audited-Financial-Statements-for-the-year-ended-June-30-2024.pdf... direct (3.9s)
[289/3287] August_2024_analysis-1.pdf... direct (2.6s)
[290/3287] August_2025_analysis.pdf... direct (2.2s)
  -- checkpoint saved (290 jse records so far)
[291/3287] BARITA-INVESTMENTS-LIMITED-COMPLETES-ACQUISITION-OF-JN-FUND-MANAGERS-LIMITED-1-1-1.pdf... direct (0.3s)
[292/3287] BIL-Second-Quarter-Investor-Briefing-JSE-Notice.pdf... direct (0.0s)
[293/3287] BLUE-POWER-GROUP-BPOW-ANNUAL-REPORT-2024.pdf... direct (5.8s)
[294/3287] BOND-DISCLOSURE-LETTER.pdf... needs_ocr_elsewhere (0.0s)
[295/3287] BPOW-2025-ANNUAL-REPORT.pdf... direct (1.8s)
[296/3287] BPOW-ANNUAL-REPORT-DELAYED-NOTICE.pdf... direct (0.1s)
[297/3287] BPOW-ANNUAL-REPORT-PROXY-FORM.pdf... direct (0.1s)
[298/3287] BPOW-AUDITED-FINANCIAL-STATEMENTS-APRIL-30-2025.pdf... direct (4.6s)
[299/3287] BPOW-Annual-Report-2025.pdf... direct (6.2s)
[300/3287] BPOW-Earnings-Call-Release-14112024.pdf... direct (0.2s)
  -- checkpoint saved (300 jse records so far)
[301/3287] BPOW-Earnings-Call-Release.pdf... direct (0.2s)
[302/3287] BPOW-Financial-Controller.pdf... direct (0.1s)
[303/3287] BPOW-Notice-of-AGM-Postponement.pdf... direct (0.0s)
[304/3287] BPOW-Notice-of-Annual-General-Meeting.pdf... needs_ocr_elsewhere (5.2s)
[305/3287] BPOW-Notice-of-Delay-in-Filing-Audited-FS-April-2026.pdf... direct (0.1s)
[306/3287] BPOW-RESULTS-AS-AT-JULY-31-2024.pdf... direct (1.4s)
[307/3287] BPOW-RESULTS-AS-AT-OCTOBER-31-2024.pdf... direct (1.2s)
[308/3287] BPOW-RETIREMENT-ANNOUNCEMENT.pdf... direct (0.1s)
[309/3287] BPOW-Results-as-at-January-312025.pdf... direct (1.3s)
[310/3287] BPOW-Unaudited-Financial-Statements-October-31-2025.pdf... direct (1.2s)
  -- checkpoint saved (310 jse records so far)
[311/3287] BRG-Report-September-30-2024.pdf... direct (1.3s)
[312/3287] BRG-Revised-Unaudited-Results-March-31-2025.pdf... direct (1.3s)
[313/3287] BRG-Unaudited-Financial-Statements-September-2025.pdf... direct (1.2s)
[314/3287] BU3-Plant-Press-Release.pdf... direct (0.2s)
[315/3287] Barita-Annual-Report-2024-Notice-of-Annual-General-Meeting.pdf... direct (0.2s)
[316/3287] Barita-Annual-Report-2024-Proxy-Form.pdf... direct (0.1s)
[317/3287] Barita-Annual-Report-2024.pdf... direct (23.0s)
[318/3287] Barita-Annual-Report-2025-Final-1.pdf... direct (11.1s)
[319/3287] Barita-Annual-Report-2025-Notice-of-Annual-General-Meeting-2.pdf... direct (0.2s)
[320/3287] Barita-Annual-Report-2025-Proxy-Form-2.pdf... direct (0.1s)
  -- checkpoint saved (320 jse records so far)
[321/3287] Barita-Bond-Prospectus-2025.pdf... direct (12.5s)
[322/3287] Barita-Investments-Limited-2025-Final-1.pdf... direct (14.8s)
[323/3287] Barita-Investments-Limited-BIL-Investor-Briefing.pdf... direct (0.0s)
[324/3287] Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[325/3287] Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1.pdf... needs_ocr_elsewhere (0.0s)
[326/3287] Barita-Investments-Limited-Financial-Report-9Months-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[327/3287] Barita-Investments-Limited-Investor-Briefing-Notice.pdf... direct (0.1s)
[328/3287] Barita-Investments-Limited-Investor-Briefing-Q1.pdf... direct (0.1s)
[329/3287] Barita-Investments-Limited-Investor-Briefing-Q2-1.pdf... direct (0.2s)
[330/3287] Barita-Investments-Limited-Investor-Briefing-Q2.pdf... direct (0.2s)
  -- checkpoint saved (330 jse records so far)
[331/3287] Barita-Investments-Limited-JSE-Notice.pdf... direct (0.2s)
[332/3287] Barita-Investments-Ltd-Delayed-Annual-Report-Notice.pdf... direct (0.0s)
[333/3287] Barita-Investments-Ltd_A-Credit-Rating.pdf... needs_ocr_elsewhere (2.5s)
[334/3287] Barita-Public-Bond-Offer-Basis-of-Allotment.pdf... direct (0.1s)
[335/3287] Barita-Public-Bond-Offer-Closure-Notice.pdf... direct (0.1s)
[336/3287] BaritaInvestmentsLimited-FinancialReport-12Months-SEPT-30-24-11-14-24.pdf... needs_ocr_elsewhere (0.0s)
[337/3287] BaritaInvestmentsLimited-FinancialReport-3Months-DEC-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[338/3287] BaritaInvestmentsLimited-FinancialReport-3Months-December-31-2024-0214-0705.pdf... needs_ocr_elsewhere (0.0s)
[339/3287] BaritaInvestmentsLimited-FinancialReport-6Months-March-31-2025-v4.pdf... needs_ocr_elsewhere (0.0s)
[340/3287] Berger-Jamaica-Results-2026_June-30.pdf... direct (1.1s)
  -- checkpoint saved (340 jse records so far)
[341/3287] Berger-Paints-Jamaica-BRG-Annual-Report-2025.pdf... direct (3.5s)
[342/3287] Berger-Paints-Jamaica-Limited-Audited-Financial-Statements-2025.pdf... direct (8.8s)
[343/3287] Berger-Paints-Jamaica-Limited-Audited-Finanical-Statement-2024-4.pdf... direct (18.3s)
[344/3287] Berger-Paints-Jamaica-Limited-Notification-Of-Resignation-Chairman-and-Directorx-1.pdf... direct (0.0s)
[345/3287] Berger-Paints-Jamaica-Ltd-2026_March-31.pdf... direct (1.0s)
[346/3287] Berger-Paints_Annual-Report_2024.pdf... direct (24.4s)
[347/3287] Best-Practices-Awards-Winners-2025-for-2024-Assessments.pdf... direct (0.3s)
[348/3287] Blue-Power-Group-Limited-BPOW-Unaudited-FS-January-31-2026.pdf... direct (1.2s)
[349/3287] Blue-Power-Group-Limited-BPOW-Unaudited-FS-July-31-2025.pdf... direct (1.5s)
[350/3287] Blue-Power-Group-LimitedBPOW-2024-Annual-Report-Proxy-Form.pdf... direct (0.1s)
  -- checkpoint saved (350 jse records so far)
[351/3287] Blue-Power-Group-LimitedBPOW-2024-Annual-Report.pdf... direct (1.7s)
[352/3287] Board-Appointment-for-Nick-Rowles-Davies-4.pdf... direct (0.4s)
[353/3287] Board-Appointment-for-Rochelle-Burnett-2.pdf... direct (0.2s)
[354/3287] Board-Members-Announcement-Transition-of-Leadership-Blondell-Walker.pdf... direct (0.3s)
[355/3287] Board-of-Directors-%40-December-31-2024.pdf... direct (0.1s)
[356/3287] Board-of-Directors-%40-December-31-2025-1.pdf... direct (0.1s)
[357/3287] Board-of-Directors-%40-December-31-2025.pdf... direct (0.1s)
[358/3287] Board-of-Directors-%40-June-30-2025-1.pdf... direct (0.1s)
[359/3287] Board-of-Directors-%40-June-30-2025.pdf... direct (0.1s)
[360/3287] Board-of-Directors-%40-June-30-2026.pdf... direct (0.1s)
  -- checkpoint saved (360 jse records so far)
[361/3287] Board-of-Directors-%40-March-31-2026-1.pdf... direct (0.1s)
[362/3287] Board-of-Directors-%40-September-30-2024-1.pdf... direct (0.1s)
[363/3287] Board_of_Directors_%40_December_31_20241.pdf... direct (0.1s)
[364/3287] BoardofDirectors%40September302025-1-2.pdf... direct (0.1s)
[365/3287] Bond-Upsize-Notice.pdf... direct (0.1s)
[366/3287] Brochure-Market-Research-Competition-4th-Quarter.pdf... direct (0.4s)
[367/3287] Business-Plan-Questionnaire-2025-Venture-Capital-Pitch-Room_.pdf... direct (0.2s)
[368/3287] CAB-ANnual-Report-final.pdf... direct (4.5s)
[369/3287] CAB-Q3-2025-Unaudited-Financial-Statements.pdf... direct (2.1s)
[370/3287] CAB-Top-Ten-Shareholders-as-at-December-31-2024.pdf... direct (0.1s)
  -- checkpoint saved (370 jse records so far)
[371/3287] CAB-Top-Ten-Shareholders-as-at-December-31-2025.pdf... direct (0.1s)
[372/3287] CAC-10-Shareholdings-as-at-October-31-2024.pdf... direct (0.1s)
[373/3287] CAC-10-Shareholdings-as-at-October-31-2025.pdf... direct (0.3s)
[374/3287] CAC-2000-Annual-Report-2025-JSE.pdf... direct (8.4s)
[375/3287] CAC-2000-Financial-Statements-Q2-PE-April-30-2026-JSE.pdf... direct (0.1s)
[376/3287] CAC-2000-Limited-2025-FS-Final-Updated-JSE.pdf... direct (6.7s)
[377/3287] CAC-2000-Limited-CEO-Commentary-Unaudited-Financials-Q2-2025-JSE-1.pdf... direct (0.5s)
[378/3287] CAC-2000-Limited-CEO-Report-YE-Oct-31-2025-JSE-signed.pdf... direct (0.3s)
[379/3287] CAC-2000-Limited-Financial-statements-2024-Final.pdf... direct (6.7s)
[380/3287] CAC-2000-Limited-Unaudited-Financials-Q2-for-YE-Oct-31-2025JSE-1.pdf... direct (2.0s)
  -- checkpoint saved (380 jse records so far)

[381/3287] CAC-2000-Ltd-Financial-Stmts-Q3-PE-31-July-2025-Signed-1.pdf... direct (1.6s)
[382/3287] CAC-2000-Q1-Unaudited-Financials-PE-Jan-31-2026-JSE.pdf... direct (0.3s)
[383/3287] CAC-2000-Unaudited-Results-Q1-YE-Oct-31-2025-Signed.pdf... direct (1.9s)
[384/3287] CAC-2024-Annual-Report_Final.pdf... direct (12.6s)
[385/3287] CAC-2024_Form-of-Proxy.pdf... direct (0.1s)
[386/3287] CAC-2024_Notice-of-AGM.pdf... direct (0.1s)
[387/3287] CAC-Annual-Report-2024.pdf... direct (12.9s)
[388/3287] CAC2000-CEO-Report-Q1-PE-January-31-2026-JSE.docx.pdf... direct (0.2s)
[389/3287] CAR-Unaudited_FS_Q3-Ended-30Sept2024.pdf... needs_ocr_elsewhere (0.0s)
[390/3287] CARIBBEAN-CEMENT-COMPANY-LIMITED-CHANGES-TO-BOARD-OF-DIRECTORS.pdf... direct (0.0s)
  -- checkpoint saved (390 jse records so far)
[391/3287] CARIBBEAN-CEMENT-COMPANY-LIMITED-NOTICE-OF-LATE-SUBMISSION-OF-ANNUAL-REPORT.pdf... direct (0.0s)
[392/3287] CAR_REPORT-TO-OUR-STOCKHOLDERS-Q1-2025-.pdf... direct (0.2s)
[393/3287] CAR_REPORT-TO-OUR-STOCKHOLDERS-Q3-2024.pdf... direct (0.2s)
[394/3287] CAR_STOCKHOLDERS_REPORT-Q2-2026-FINAL.docx.pdf... direct (2.2s)
[395/3287] CAR_STOCKHOLDERS_REPORT_Q1-2026_.pdf... direct (0.4s)
[396/3287] CAR_Unaudited_FS_Qtr_ended_31Mar2025.pdf... direct (1.0s)
[397/3287] CBL-2nd-Quarter-Report-Ended-June-30-2026-Signed.pdf... direct (1.1s)
[398/3287] CCC-2024-Summary-Financial-Statements.pdf... direct (1.3s)
[399/3287] CCC-Caribbean-Cement-Company-Limited-Annual-Report-2024.pdf... direct (15.5s)
[400/3287] CCC-Caribbean-Cement-Company-Limited-share-info-at-2025-June-30.pdf... direct (0.2s)
  -- checkpoint saved (400 jse records so far)
[401/3287] CCC-Condensed-Consolidated-Unaudited-Interim-Financial-Report-For-The-Nine-Months-Ended-September-30-2024.pdf... direct (0.9s)
[402/3287] CCC-Condensed-Consolidated-Unaudited-Interim-Financial-Statements-For-The-Six-Months-Ended-June-30-2026.pdf... direct (0.9s)
[403/3287] CCC-Condensed-Consolidated-Unaudited-Interim-Financial-Statements-Q1-2025.pdf... direct (1.5s)
[404/3287] CCC-Consolidated-Financial-Statements-For-The-Year-Ended-December-31-2025.pdf... direct (17.8s)
[405/3287] CCC-DIVIDEND-RECOMMENDATION-NOTICE-May-19-2025.pdf... direct (0.0s)
[406/3287] CCC-NOTICE-OF-DIVIDEND-DECLARATION-JULY-11-2025.pdf... direct (0.0s)
[407/3287] CCC-Notice-of-Annual-General-Meeting-2025.pdf... direct (0.4s)
[408/3287] CCC-Q3-2025-Condensed-Consolidated-Unaudited-Interim-Financial-Statements.pdf... direct (1.6s)
[409/3287] CCC-Top-Ten-as-at-2025-September-30.pdf... direct (0.2s)
[410/3287] CCC-Top-Ten-as-at-March-31-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (410 jse records so far)
[411/3287] CCCL-Top-Ten-1-1.pdf... needs_ocr_elsewhere (0.0s)
[412/3287] CCCL-Top-Ten-1.pdf... needs_ocr_elsewhere (0.0s)
[413/3287] CCL-Top-Ten-and-Directors-Shareholdings-28FEB2025.pdf... direct (0.2s)
[414/3287] CEO-Business-Report-unaudited-Q3-2024.docx.pdf... direct (0.6s)
[415/3287] CEO-FORUM-Speakers.pdf... needs_ocr_elsewhere (0.0s)
[416/3287] CEO-Forum-Overview.pdf... direct (0.2s)
[417/3287] CEO-JSE-Report-for-Quarter-Ending-July-31-2025-signed.docx.pdf... direct (0.2s)
[418/3287] CERTIFIED-BOARD-RESOLUTION-OF-THE-DIRECTORS-DIVIDEND-2026.pdf... direct (0.1s)
[419/3287] CFF-Audited-Financials-2025-for-upload-1.pdf... direct (5.4s)
[420/3287] CFF-Financial-Statements-2024-JSE-UPLOAD.pdf... direct (4.9s)
  -- checkpoint saved (420 jse records so far)
[421/3287] CFF-Q1-2025-JSE-Report-01-final-Reupload.pdf... direct (1.9s)
[422/3287] CFF-Q1-2026-JSE-Financials-for-uplaod.pdf... direct (2.1s)
[423/3287] CFF-Q2-2025-JSE-Report-for-upload-2.pdf... direct (2.4s)
[424/3287] CFF-Q2-2026-JSE-Financials.pdf... direct (2.1s)
[425/3287] CFF-Q3-2024-JSE-Financials.pdf... direct (1.8s)
[426/3287] CFF-Q3-2025-JSE-Financials-Final-for-upload.pdf... direct (2.5s)
[427/3287] CFF_Annual-Report-2024-WEB.pdf... direct (9.2s)
[428/3287] CFF_Annual-Report-2025-upload-version.pdf... direct (8.1s)
[429/3287] CHL-Dec-25-Q-1.pdf... needs_ocr_elsewhere (0.0s)
[430/3287] CHL-June-26-Q3.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (430 jse records so far)
[431/3287] CHL-Mar-26-Q2.pdf... needs_ocr_elsewhere (0.0s)
[432/3287] CL-Financial-Stmts_Sept2025.pdf... direct (0.9s)
[433/3287] CL_Financial_Stmts_Mar2026_.pdf... direct (1.5s)
[434/3287] CPJ-2025.12.31-Interim-Report.pdf... direct (1.3s)
[435/3287] CPJ-Annual-Report-2025.pdf... direct (11.6s)
[436/3287] CPJ-Notice-of-AGM-2.11.2025.pdf... direct (0.4s)
[437/3287] CPJ-Notice-of-AGM-Proxy-Form.pdf... direct (0.3s)
[438/3287] Car-Unaudited-FS-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[439/3287] Car_Top_Ten_Shareholders_Dec_25.pdf... direct (0.4s)
[440/3287] Cargo-Handlers-Ltd-Annual-Report-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (440 jse records so far)
[441/3287] Caribbean-Assurance-Brokers-Limited-2024-Finalized.pdf... direct (4.8s)
[442/3287] Caribbean-Assurance-Brokers-Limited-2025-Final.pdf... direct (4.6s)
[443/3287] Caribbean-Assurance-Brokers-Limited-CABROKERS-Unaudited-Financial-Statements-for-The-Second-Quarter-Ending-June-30th-2026.pdf... direct (1.8s)
[444/3287] Caribbean-Cement-Company-Limited-Annual-Report-2025.pdf... direct (20.1s)
[445/3287] Caribbean-Cement-Company-Limited-Q1-2026-Financials-1.pdf... direct (0.8s)
[446/3287] Caribbean-Cement-Company-Signed-FS-2024-1.pdf... direct (9.8s)
[447/3287] Caribbean-Cream-Limited-Audited-2025-Financial-Statements-FINAL.pdf... direct (5.7s)
[448/3287] Caribbean-Cream-Limited-Audited-FY2026-Financial-Statements-FINAL.pdf... direct (6.3s)
[449/3287] Caribbean-Producers-Jamaica-Limited-2025-Financial-Statements.pdf... direct (9.6s)
[450/3287] Caribbean-Producers-Jamaica-Limited-Audited-Financials-for-Year-Ended-June-30-2024-a.pdf... direct (6.8s)
  -- checkpoint saved (450 jse records so far)
[451/3287] Caribbean-Producers-Jamaica-Limited-CPJ-%E2%80%93-Notice-of-Resignation-from-the-Board-of-Directors.pdf... needs_ocr_elsewhere (0.0s)
[452/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Annual-Report-Period-Ended-December-2024.pdf... direct (11.4s)
[453/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Annual-Report-Period-Ended-December-31st-2024-a.pdf... direct (11.7s)
[454/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Audited-Financial-Statements-For-December-31-2024-1.pdf... direct (9.2s)
[455/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Unaudited-Financial-Results-For-Quarter-Ended-June-30-2025.pdf... direct (0.9s)
[456/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Unaudited-Financial-Results-For-Quarter-Ended-September-30-2025.pdf... direct (1.2s)
[457/3287] Caribbean-Producers-Jamaica-Limited-CPJ-Unaudited-Financial-Statements-For-September-30-2024-1.pdf... direct (1.3s)
[458/3287] Caribbean-Producers-Jamaica-Limited-CPJ-_Annual-Report-2024.pdf... direct (11.4s)
[459/3287] Caribbean-Producers-Jamaica-Limited-Change-in-Fiscal-Year-End.pdf... needs_ocr_elsewhere (0.0s)
[460/3287] Caribbean-Producers-Jamaica-Limited-Changes-in-Executive-Leadership.pdf... direct (0.1s)
  -- checkpoint saved (460 jse records so far)
[461/3287] Caribbean-Producers-Jamaica-Limited_Q12025-Unaudited-Financial-Report-3.31.2025-1.pdf... direct (0.5s)
[462/3287] Carreras-Limited-2024-Annual-Report.pdf... needs_ocr_elsewhere (0.1s)
[463/3287] Carreras-Limited-2025-Final-FS.pdf... direct (5.0s)
[464/3287] Carreras-Limited-Annual-Report-2025.pdf... needs_ocr_elsewhere (0.1s)
[465/3287] Carreras-Limited-FS-Final-2024.pdf... direct (4.6s)
[466/3287] Chairman-Statement.pdf... direct (0.1s)
[467/3287] Chairmans-Statement.pdf... direct (0.2s)
[468/3287] Chairmans-Update-to-Stockholders-of-Supreme-Ventures-Limited.pdf... direct (0.9s)
[469/3287] Circular-Letter-to-Shareholders-2024.pdf... direct (0.5s)
[470/3287] Circular-Letter-to-Shareholders-2025.pdf... direct (0.2s)
  -- checkpoint saved (470 jse records so far)
[471/3287] Condensed-Consolidated-Unaudited-Interim-Financial-Report-For-The-Six-Months-Ended-June-30-2025.pdf... direct (1.1s)
[472/3287] Connected-Party-Trade-in-Shares.pdf... direct (0.0s)
[473/3287] Consolidated-Bakeries-Jamaica-Limited-1st-Quarter-Report-Ended-March-31-2026.pdf... direct (0.8s)
[474/3287] Consolidated-Bakeries-Jamaica-Limited-2024-Financial-statement.pdf... direct (3.4s)
[475/3287] Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed.pdf... needs_ocr_elsewhere (0.1s)
[476/3287] Copy-of-JSE-INTERIM-REPORT-JUNE-25.pdf... direct (1.7s)
[477/3287] Copy-of-JSE-INTERIM-REPORT-JUNE-26-nxt.pdf... direct (1.6s)
[478/3287] Copy-of-JSE-INTERIM-REPORT-MAR-25.pdf... direct (1.7s)
[479/3287] Copy-of-JSE-INTERIM-REPORT-MAR-26.pdf... direct (1.6s)
[480/3287] Copy-of-JSE-INTERIM-REPORT-SEPT-25-Update.pdf... direct (1.4s)
  -- checkpoint saved (480 jse records so far)
[481/3287] Copy-of-PRESS-RELEASE-1.pdf... direct (0.6s)
[482/3287] Copy-of-Trial-Balance-JSE-INTERIM-REPORT-DECEMBER-2024-Final.pdf... direct (1.7s)
[483/3287] Cornerstone-Press-Release-FHC-Notification-26-May-2026.pdf... direct (0.3s)
[484/3287] Cornerstone-Press-Release-January-6-2026.pdf... direct (0.7s)
[485/3287] Cornerstone-Scheme-Booklet.pdf... direct (8.2s)
[486/3287] Corporate-Governance-Code-2025-vf.pdf... direct (2.4s)
[487/3287] Corporate-Governance-Code-2026-vf.pdf... direct (1.8s)
[488/3287] Corporate-Governance-Policy-Revision-4-Updated-November-7-2024.pdf... direct (2.6s)
[489/3287] Corporate-Governance-Principles-Approved-July-29-2026.pdf... direct (0.9s)
[490/3287] Corporate-News-Release-IEG.pdf... direct (0.2s)
  -- checkpoint saved (490 jse records so far)
[491/3287] Correction-Notes-June-30-2024.pdf... direct (0.1s)
[492/3287] Course-Description-The-Secret-to-Master-Salesmanship-Workshop.pdf... direct (0.2s)
[493/3287] DCL-FS-2025-Final-Signed-2.pdf... direct (7.4s)
[494/3287] DCL_Stock-Exchange-Quarterly-report_Q2-2026-Final-Version-JB.pdf... direct (1.0s)
[495/3287] DCL_Stock-Exchange-Quarterly-report_Q3-2025-Signed-3.pdf... direct (1.3s)
[496/3287] DCOVE-Top-10-as-at-December-31-2025-1.pdf... direct (0.1s)
[497/3287] DCOVE-Top-10-as-at-June-30-2026-1-1.pdf... direct (0.1s)
[498/3287] DCOVE-Top-10-as-at-March-31-2026-1-2.pdf... direct (0.2s)
[499/3287] DCOVE-Top-10-as-at-September-30-2025-2-1.pdf... direct (0.1s)
[500/3287] DIRECTORS-Q1-1.pdf... direct (0.1s)
  -- checkpoint saved (500 jse records so far)
[501/3287] DIRECTORS-REPORT-TO-SHAREHOLDERS-JUNE-2024.pdf... direct (0.2s)
[502/3287] DIRECTORS-REPORT-TO-SHAREHOLDES-JUNE-2025-.pdf... direct (0.3s)
[503/3287] DIVIDEND-CONSIDERATION-MARCH-10-2025.pdf... direct (0.1s)
[504/3287] DIVIDEND-CONSIDERATION-NOVEMBER-5-2025.pdf... direct (0.1s)
[505/3287] DIVIDEND-CONSIDERATION-RESPONSE.pdf... direct (0.1s)
[506/3287] DOC-20260331-WA0047._copy.pdf... direct (0.2s)
[507/3287] DOLLA-Unaudited-Interim-Financial-Statements-for-the-Nine-Months-Ended-September-30-2025.pdf... direct (2.6s)
[508/3287] DOLLA-Unaudited-Interim-Financial-Statements-for-the-Six-Months-Ended-June-30-2025.pdf... direct (0.7s)
[509/3287] DOLLA-Unaudited-Interim-Financial-Statements-for-the-year-ended-December-31-2025.pdf... direct (2.1s)
[510/3287] DOLLA_Annual_Report_2025.pdf... direct (15.7s)
  -- checkpoint saved (510 jse records so far)
[511/3287] DTL-Annual-Report-2024-WB.pdf... direct (15.6s)
[512/3287] DTL-Audited-2025-Consolidated-Financial-Statements.pdf... direct (14.9s)
[513/3287] DTL-Communication_Release-Q1-2026-Unaudited-Financial-Statements.pdf... direct (0.2s)
[514/3287] DTL-Form-of-Proxy-2025.pdf... direct (0.2s)
[515/3287] DTL-JSE-Notice-Independent-Review_FIN-1.pdf... direct (0.1s)
[516/3287] DTL-Notice-of-AGM-2025.pdf... direct (0.1s)
[517/3287] DTL-Shareholdings-as-at-December-31-2025.pdf... direct (0.1s)
[518/3287] DTL-Shareholdings_Q4_2024_JSE.pdf... needs_ocr_elsewhere (0.0s)
[519/3287] DTL-Unaudited-Consolidated-Financial-Statements-Q1-2025_Fin.pdf... direct (3.9s)
[520/3287] DTL-Unaudited-Consolidated-Financial-Statements-Q2-2025_Fin.pdf... direct (3.7s)
  -- checkpoint saved (520 jse records so far)
[521/3287] DTL-Unaudited-Financial-Results-for-Q3-Ended-September-30-2024-_Final.pdf... direct (3.7s)
[522/3287] David-McDaniel-JSE-1.pdf... direct (0.1s)
[523/3287] Dec-2024-Q2-Quarterly-Financials.pdf... direct (22.2s)
[524/3287] December_2024_analysis.pdf... direct (2.7s)
[525/3287] December_2025_analysis-1.pdf... direct (2.3s)
[526/3287] Delay-Notice.Shareholders.2026.pdf... direct (0.0s)
[527/3287] Delay-Notification-%E2%80%93-Filing-of-Audited-Financial-Statements-1.pdf-1.pdf... direct (0.3s)
[528/3287] Delay-in-Investor-Briefing-Schedule.pdf... direct (0.1s)
[529/3287] Delay-of-Audited-Financial-Statements.pdf... needs_ocr_elsewhere (0.0s)
[530/3287] DelayNotice.Shareholders.2025.pdf... direct (0.0s)
  -- checkpoint saved (530 jse records so far)
[531/3287] DelayNotice.Shareholders.August.2025.pdf... direct (0.0s)
[532/3287] Derrimon-Board-Commentary-on-Audited-Financial-Statements-for-year-ended-December-31-2025.pdf... direct (0.1s)
[533/3287] Derrimon-Communication-Release-for-Auidited-Financials-FY-2025.pdf... direct (0.4s)
[534/3287] Derrimon-Q3-September-2025_FIN.pdf... direct (3.4s)
[535/3287] Derrimon-Unaudited-Financial-Statements_Q1_March-31-2026.pdf... direct (3.4s)
[536/3287] Digital_Annual-Report-2024-Caribbean-Assurance-Brokers-Limited-1.pdf... direct (22.4s)
[537/3287] Director-Stocks-Sale-Notice-1.pdf... needs_ocr_elsewhere (0.0s)
[538/3287] Director-Stocks-Sale-Notice-revised.pdf... direct (0.0s)
[539/3287] Directors-Circular-CPJ-Shareholders-1.29.2025.pdf... direct (9.0s)
[540/3287] Directors-Holding-as-at-April-27-2024.pdf... direct (0.2s)
  -- checkpoint saved (540 jse records so far)
[541/3287] Directors-Holding-as-at-August-2-2025.pdf... direct (0.3s)
[542/3287] Directors-Holding-as-at-December-31-2024.pdf... direct (0.2s)
[543/3287] Directors-Holding-as-at-December-31-2025-1.pdf... direct (0.1s)
[544/3287] Directors-Holding-as-at-December-31-2025.pdf... direct (0.3s)
[545/3287] Directors-Holding-as-at-December-312024.pdf... direct (0.1s)
[546/3287] Directors-Holding-as-at-January-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[547/3287] Directors-Holding-as-at-June-30-2026-1-1.pdf... direct (0.1s)
[548/3287] Directors-Holding-as-at-June-30-2026-1-2.pdf... direct (0.1s)
[549/3287] Directors-Holding-as-at-June-30-2026.pdf... needs_ocr_elsewhere (4.7s)
[550/3287] Directors-Holding-as-at-March-31-2025.pdf... direct (0.2s)
  -- checkpoint saved (550 jse records so far)
[551/3287] Directors-Holding-as-at-March-31-2026-1-1-1.pdf... direct (0.1s)
[552/3287] Directors-Holding-as-at-March-31-2026.pdf... needs_ocr_elsewhere (4.4s)
[553/3287] Directors-Holding-as-at-November-30-2024.pdf... direct (0.2s)
[554/3287] Directors-Holding-as-at-October-26-2024.pdf... direct (0.3s)
[555/3287] Directors-Holding-as-at-October-31-2024.pdf... direct (0.4s)
[556/3287] Directors-Holding-as-at-October-31-2025.pdf... needs_ocr_elsewhere (4.5s)
[557/3287] Directors-Holding-as-at-September-30-2024-1.pdf... direct (0.3s)
[558/3287] Directors-Holding-as-at-September-30-2024.pdf... direct (0.1s)
[559/3287] Directors-Holding-as-at-September-30-2025-1-1.pdf... direct (0.1s)
[560/3287] Directors-Holding-as-at-September-30-2025.pdf... direct (0.2s)
  -- checkpoint saved (560 jse records so far)
[561/3287] Directors-Holdings-as-at-November-1-2025-1.pdf... needs_ocr_elsewhere (0.0s)
[562/3287] Directors-Senior-Officers-Connected-Parties-December-31-2024-1.pdf... direct (0.1s)
[563/3287] Directors-Senior-Officers-Connected-Parties-December-31-2025.pdf... direct (0.2s)
[564/3287] Directors-Senior-Officers-Connected-Parties-June-30-2025-Revised.pdf... direct (0.1s)
[565/3287] Directors-Senior-Officers-Connected-Parties-June-30-2025.pdf... direct (0.1s)
[566/3287] Directors-Senior-Officers-Connected-Parties-June-30-2026.pdf... direct (0.1s)
[567/3287] Directors-Senior-Officers-Connected-Parties-March-31-2025-Revised.pdf... direct (0.1s)
[568/3287] Directors-Senior-Officers-Connected-Parties-March-31-2025.pdf... direct (0.1s)
[569/3287] Directors-Senior-Officers-Connected-Parties-March-31-2026.pdf... direct (0.2s)
[570/3287] Directors-Senior-Officers-Connected-Parties-September-30-2024.pdf... direct (0.1s)
  -- checkpoint saved (570 jse records so far)
[571/3287] Directors-Senior-Officers-Connected-Parties-September-30-2025.pdf... direct (0.1s)
[572/3287] Directors-Share-Purchase-Notice-2-27-Aug-2024.pdf... needs_ocr_elsewhere (0.0s)
[573/3287] Directors-Share-Purchase-Notice-2A-27.8.2024.pdf... direct (0.0s)
[574/3287] Directors-Share-Purchase-Notice-REVISED-19-22.8.24.pdf... needs_ocr_elsewhere (0.0s)

[575/3287] Directors-and-Connected-Parties-GENAC-Dec-2025.pdf... direct (0.1s)
[576/3287] Directors-and-Connected-Parties-Shareholdings-Report-as-at-May-31-2025.pdf... direct (0.2s)
[577/3287] DirectorsHoldingasatAugust22025.pdf... direct (0.4s)
[578/3287] DirectorsHoldingasatJanuary252025-Executed-Copy.pdf... needs_ocr_elsewhere (0.0s)
[579/3287] DirectorsHoldingasatJuly272024.pdf... direct (0.2s)
[580/3287] DirectorsHoldingasatJune302025.pdf... direct (0.2s)
  -- checkpoint saved (580 jse records so far)
[581/3287] DirectorsHoldingasatMay32025.pdf... direct (0.2s)
[582/3287] DirectorsHoldingasatSeptember302025.pdf... direct (0.3s)
[583/3287] Dividend-letter-2024.pdf... needs_ocr_elsewhere (0.0s)
[584/3287] Dividend_000240-1.pdf... needs_ocr_elsewhere (0.0s)
[585/3287] Dolla-Annual-Report-2024-Final-Single-.pdf... direct (16.0s)
[586/3287] Dolla-Financial-Services-Limited-DOLLA-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (11.1s)
[587/3287] Dolla-Financial-Services-Limited-DOLLA-Audited-Financial-Statements-for-the-Year-Ended-December-31-2025.pdf... direct (10.2s)
[588/3287] Dolla-Financial-Services-Limited-DOLLA-Unaudited-Financial-Results-for-the-Fourth-Quarter-ended-December-31-2024.pdf... direct (2.9s)
[589/3287] Dolla-Financial-Services-Limited-DOLLA-Unaudited-Financial-Results-for-the-Third-Quarter-ended-September-30-2024.pdf... direct (1.0s)
[590/3287] Dolla-Financial-Unaudited-Interim-Financial-Statements-for-the-Quarter-Ended-March-31-2025-.pdf... direct (1.0s)
  -- checkpoint saved (590 jse records so far)
[591/3287] Dolla-Prospectus-2.pdf... direct (150.6s)
    ^ SLOW FILE -- Dolla-Prospectus-2.pdf took 150.6s
[592/3287] Dolla-Unaudited-Interim-Financial-Statements-for-the-Quarter-ended-31-March-2026.pdf... direct (1.9s)
[593/3287] Dolla-Unaudited-Interim-Financial-Statements-for-the-six-months-ended-30-June-2026.pdf... direct (5.8s)
[594/3287] Dolphin-Cove_Annual-Report-2025.pdf... direct (56.4s)
    ^ SLOW FILE -- Dolphin-Cove_Annual-Report-2025.pdf took 56.4s
[595/3287] Dr.-William-Lawrence-%E2%80%93-Chairman-of-the-Academic-Review-Committee-JSE-e-Campus.pdf... direct (0.0s)
[596/3287] ECL-2024-Annual-Report.pdf... direct (7.7s)
[597/3287] ECL-2025-Annual-Report.pdf... direct (6.2s)
[598/3287] ECPF-2024-Annual-Report.pdf... direct (18.3s)
[599/3287] ECPF-2024-Audited-Financial-Statements.pdf... direct (13.1s)
[600/3287] ECPF-2025-FS-FINAL.pdf... direct (12.2s)
  -- checkpoint saved (600 jse records so far)
[601/3287] ECPF-Value-Fund-Quarterly-Release-December-2024.pdf... direct (4.4s)
[602/3287] ECPF-Value-Fund-Quarterly-Release-September-2024-2.pdf... direct (4.0s)
[603/3287] EFRESH-Report-to-Shareholders-ended-March-31-2025_000085.pdf... needs_ocr_elsewhere (0.0s)
[604/3287] EFRESH-Unaudited-Financial-ended-31-March-2025_000084.pdf... needs_ocr_elsewhere (0.0s)
[605/3287] EFresh-Unaudited-Financial-Statements-1.pdf... needs_ocr_elsewhere (0.0s)
[606/3287] ELITE-DIAGNOSTIC-Notice-of-AGM.pdf... direct (0.2s)
[607/3287] ELITE-DIAGNOSTIC-Proxy-Form.pdf... direct (0.3s)
[608/3287] ELITE-DIAGNOSTICS-ANNUAL-REPORT-2025.pdf... direct (10.7s)
[609/3287] EVERYTHING-FRESH-LIMITED-Report-to-Shareholders-June-2026.pdf... needs_ocr_elsewhere (0.0s)
[610/3287] EVERYTHING-FRESH-LIMITED-Unaudited-Reports-June-2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (610 jse records so far)
[611/3287] EduFocal-2024-AGM-Notice-and-Resolutions.pdf... needs_ocr_elsewhere (0.0s)
[612/3287] EduFocal-2024-AGM-Proxy-Form-May-2026.pdf... direct (0.1s)
[613/3287] EduFocal-Annual-Report-2024.pdf... direct (12.1s)
[614/3287] EduFocal-Annual-Report-2025-1.pdf... direct (11.3s)
[615/3287] EduFocal-Articles-of-Incorporation-proposed-draft.pdf... direct (6.8s)
[616/3287] EduFocal-Audit-Committee-Composition-5.5.25.pdf... direct (0.1s)
[617/3287] EduFocal-Audited-Financial-Statement-for-FY2025.pdf... direct (7.3s)
[618/3287] EduFocal-Audited-Financial-Statements-for-FY-2024.pdf... direct (8.5s)
[619/3287] EduFocal-Group-Quarter-4-2024_Final-1.pdf... direct (2.3s)
[620/3287] EduFocal-JSE-Letter-1.12.25-1.pdf... direct (0.1s)
  -- checkpoint saved (620 jse records so far)
[621/3287] EduFocal-JSE-Notification-Letter-for-Change-of-Auditor-21.10.25.pdf... direct (0.1s)
[622/3287] EduFocal-Limited-Shareholdings-of-Directors-and-Connected-Persons-as-at-December-31-2024.pdf... direct (0.1s)
[623/3287] EduFocal-Limited-Top-10-Shareholders-Report-as-at-December-31-2024.pdf... direct (0.1s)
[624/3287] EduFocal-Ltd-MDA-Q3-2025.pdf... direct (1.8s)
[625/3287] EduFocal-Q4-2025.pdf... direct (1.7s)
[626/3287] EduFocal-Top-10-Shareholders-Directors-and-Connected-Persons-Listing-as-at-December-31-2025.pdf... direct (0.1s)
[627/3287] Eduardo-Rodriguez_External-Appointment_GroupCFO.pdf... direct (0.2s)
[628/3287] Edufocal-Group-Quarter-1-2025_Final.pdf... direct (2.3s)
[629/3287] Edufocal-Group-Quarter-2-20251.pdf... direct (1.0s)
[630/3287] Edufocal-Group-Quarter_Final_Q3-1.pdf... direct (2.7s)
  -- checkpoint saved (630 jse records so far)
[631/3287] Edufocal-Q3-2025.pdf... direct (0.8s)
[632/3287] Efresh-Financial-Reports-Sept-2025.pdf... needs_ocr_elsewhere (0.0s)
[633/3287] Efresh-Report-to-Shareholders-Sept-2025.pdf... needs_ocr_elsewhere (0.0s)
[634/3287] Elite-Diagnostic-4th-Quarter-Interim-Report-June-30-2026.pdf... direct (1.4s)
[635/3287] Elite-Diagnostic-Audited-Financials-June-2025.pdf... direct (5.1s)
[636/3287] Elite-Diagnostic-Limit-3rd-Quarter-Interim-Report-March-2025-final.pdf... direct (1.4s)
[637/3287] Elite-Diagnostic-Limit-3rd-Quarter-Interim-Report-March-2026-003.pdf... direct (1.3s)
[638/3287] Elite-Diagnostics-1st-Quarter-Interim-Report-September-2025.pdf... direct (1.3s)
[639/3287] Elite-Diagnostics-2nd-Quarter-Interim-Report-December-31-2024.pdf... direct (1.4s)
[640/3287] Elite-Diagnostics-2nd-Quarter-Interim-Report-December-31-2025.pdf... direct (1.4s)
  -- checkpoint saved (640 jse records so far)
[641/3287] Elite-Diagnostics-4rd-Quarter-Interim-Report-June-30-2025.pdf... direct (1.1s)
[642/3287] Eppley-Annual-Report-2024.pdf... direct (64.4s)
    ^ SLOW FILE -- Eppley-Annual-Report-2024.pdf took 64.4s
[643/3287] Eppley-Caribbean-Property-Fund-2025-Annual-Report.pdf... direct (31.6s)
    ^ SLOW FILE -- Eppley-Caribbean-Property-Fund-2025-Annual-Report.pdf took 31.6s
[644/3287] Eppley-Limited-2025-Annual-Report.pdf... direct (10.6s)
[645/3287] Eppley-Limited-Financial-Statements-2024-3.pdf... direct (12.7s)
[646/3287] Eppley-Limited-Financial-Statements_-2025.pdf... direct (8.9s)
[647/3287] Eppley-Limited-Notice-of-Changes-in-Executive-Management.pdf... direct (0.1s)
[648/3287] Eppley-Limited-Notice-of-Suspension-and-Delisting-of-Preference-Shares-EPLY7.25-JSE-Portal-Upload.pdf... direct (0.0s)
[649/3287] Eppley-Limited-Notice-of-Suspension-and-Delisting-of-Preference-Shares_Upload.pdf... direct (0.0s)
[650/3287] Eppley-Limited-Q1-2025-Report.pdf... direct (1.7s)
  -- checkpoint saved (650 jse records so far)
[651/3287] Eppley-Limited-Q1-2026-Report.pdf... direct (1.9s)
[652/3287] Eppley-Limited-Q2-2025-Report-FINAL.pdf... direct (1.7s)
[653/3287] Eppley-Limited-Q3-2025-Report.pdf... direct (1.9s)
[654/3287] Eppley-Limited-Q4-2024-Report.pdf... direct (1.8s)
[655/3287] Eppley-Limited-Q4-2025-Report.pdf... direct (1.6s)
[656/3287] Eppley-Limited-Quarterly-Release-September-2024-1.pdf... direct (1.7s)
[657/3287] Eppley-Limited-Top-10-Shareholdings-and-Shareholdings-of-Directors-and-Executive-Dec.-2025-1.pdf... direct (0.2s)
[658/3287] Eppley-Limited-Top-10-Shareholdings-and-Shareholdings-of-Directors-and-Executives-Dec-2024-1.pdf... direct (0.1s)
[659/3287] Eppley-buys-Stratus-Alternative-Funds-from-NCB-Capital-Markets-Limited.pdf... direct (0.1s)
[660/3287] Everything-Fresh-Limited-Audited-Financial-Statements-December-31-2024.pdf... direct (7.1s)
  -- checkpoint saved (660 jse records so far)
[661/3287] Everything-Fresh-Limited-Report-to-Shareholders-3rd-Quarter-2024.pdf... needs_ocr_elsewhere (0.0s)
[662/3287] Everything-Fresh-Limited-Top-Ten-Shareholdings-December-31-2024.pdf... direct (0.1s)
[663/3287] Everything-Fresh-Limited-Unaudited-Financial-Statements-3rd-Quarter-2024.pdf... needs_ocr_elsewhere (0.0s)

[664/3287] Everything-Fresh_2025_Annual-Report_web.pdf... direct (70.4s)
    ^ SLOW FILE -- Everything-Fresh_2025_Annual-Report_web.pdf took 70.4s
[665/3287] EverythingFresh_2024_Annual-Report_Final-1.pdf... direct (9.7s)
[666/3287] Evolve-Dolla-Divestment-Press-Release-1.pdf... direct (0.1s)
[667/3287] Explanatory-Statement-1.pdf... direct (4.2s)
[668/3287] Explanatory-Statement.pdf... direct (4.0s)
[669/3287] Express-Catering-Limited-Audited-Financial-Statements-at-May-31-2024-1.pdf... direct (4.6s)
[670/3287] Express-Catering-Limited-Audited-Financial-Statements-at-May-31-2025.pdf... direct (4.6s)
  -- checkpoint saved (670 jse records so far)
[671/3287] Express-Catering-Limited-Q1-2025-Unaudited-Financial-Statements-Dated-August-31_2024-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.8s)
[672/3287] Express-Catering-Limited-Q1-2026-Unaudited-Financial-Statements-Dated-August-31_2025-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.9s)
[673/3287] Express-Catering-Limited-Q2-2025-Unaudited-Financial-Statements-Dated-November-30_2024-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.8s)
[674/3287] Express-Catering-Limited-Q2-2026-Unaudited-Financial-Statements-Dated-November-30_2025-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.9s)
[675/3287] Express-Catering-Limited-Q3-2025-Unaudited-Financial-Statements-Dated-February-28_2025-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.9s)
[676/3287] Express-Catering-Limited-Q3-2026-Unaudited-Financial-Statements-Dated-February-28_2026-and-Top-10-and-Directors-Shareholdings.pdf... direct (0.8s)
[677/3287] Express-Catering-Limited-Top-10-Directors-Shareholdings-at-May-31-2024-1.pdf... direct (0.2s)
[678/3287] Express-Catering-Limited-Top-10-Directors-Shareholdings-at-May-31-2025-1.pdf... direct (0.1s)
[679/3287] Extension-Notice-ASBH-Audited-Financial-Statements-for-the-year-ended-December-31-2024.pdf... direct (0.2s)
[680/3287] FESCO_2024-Form-of-Proxy.pdf... direct (0.1s)
  -- checkpoint saved (680 jse records so far)
[681/3287] FESCO_Future-Energy-Source-Co-Ltd_Annual-Report-2024_Final.pdf... direct (13.0s)
[682/3287] FESCO_Future-Energy-Source-Co-Ltd_Annual-Report-2025.pdf... direct (19.8s)
[683/3287] FESCO_Future-Energy-Source-Co-Ltd_Notice-of-AGM-2025.pdf... direct (0.8s)
[684/3287] FESCO_Future-Energy-Source-Co-Ltd_Proxy-Form-2025-AGM.pdf... direct (0.1s)
[685/3287] FESCO_Future-Energy-Source-Co-Ltd_Unaudited-Q1-Report-as-at-30June2026.pdf... direct (2.3s)
[686/3287] FESCO_Future-Energy-Source-Co-Ltd_Unaudited-Q3-Report-ending-31Dec2024.pdf... direct (2.8s)
[687/3287] FESCO_Future-Energy-Source-Co-Ltd_Unaudited-Q4-Report-ending-31Mar2025.pdf... direct (2.6s)
[688/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q1-Report-ending-30-June-2025.pdf... direct (2.3s)
[689/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q1-Report-ending-30Jun2023-Rev.pdf... direct (1.7s)
[690/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q1-Report-ending-30June2024Rev.pdf... direct (2.2s)
  -- checkpoint saved (690 jse records so far)
[691/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q2-Report-ending-30-Sep-2025.pdf... direct (2.6s)
[692/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q2-Report-ending-30-Sept-2024.pdf... direct (2.5s)
[693/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q2-Report-ending-30Sep2023-Rev.pdf... direct (2.2s)
[694/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q3-Report-ending-31-Dec-2025.pdf... direct (2.6s)
[695/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q3-Report-ending-31Dec2023-Rev.pdf... direct (2.4s)
[696/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q4-Report-ending-31-March-2026.pdf... direct (2.9s)
[697/3287] FESCO_Future-Energy-Source-Company-Ltd_Unaudited-Q4-Report-ending-31Mar2024-Rev.pdf... direct (2.4s)
[698/3287] FESCO_Notice-of-2024-Annual-General-Meeting.pdf... direct (0.2s)
[699/3287] FESCO_Top-10-Directors-and-Officers-Shareholdings-as-at-31-March-2025.pdf... direct (0.3s)
[700/3287] FINAL-AMENDED-ANNUAL-REPORT-2025-1.pdf... direct (22.9s)
  -- checkpoint saved (700 jse records so far)
[701/3287] FINAL-JSE-Quarterly-Report-with-Notes-2nd-Quarter-April-2023-JSE-Revision-v2-signed.pdf... direct (1.3s)
[702/3287] FINAL-JSE-Quarterly-Report-with-Notes-3rd-Quarter-July-2023-JSE-Revision-v2-signed.pdf... direct (1.4s)
[703/3287] FINAL-JSE-Quarterly-Report-with-Notes-3rd-Quarter-July-2024-Signed.pdf... direct (2.2s)
[704/3287] FINAL-Media-Release.Sale-of-North-Street.May-12-2026.pdf... direct (0.1s)
[705/3287] FINAL-V3-_-JSE-press-release_MOU.pdf... direct (0.2s)
[706/3287] FONTANA-AR-2024.pdf... direct (9.3s)
[707/3287] FONTANA-AR2025.pdf... direct (12.4s)
[708/3287] FOR-IMMEDIATE-RELEASE_IEG.pdf... direct (0.1s)
[709/3287] FORM-OF-PROXY-2025.pdf... direct (0.1s)
[710/3287] FORM-OF-PROXY-2026.pdf... direct (0.2s)
  -- checkpoint saved (710 jse records so far)
[711/3287] FORM-OF-PROXY-FOR-BARITA-1.pdf... direct (0.1s)
[712/3287] FORM-OF-PROXY.pdf... direct (0.2s)
[713/3287] FOSRICH-2024-ANNUAL-RPT-JSE-Website.pdf... direct (13.3s)
[714/3287] FOSRICH-2025-ANNUAL-REPORT.pdf... direct (12.8s)
[715/3287] FREI-Q3-Financial-Statements-September-2025.pdf... direct (3.6s)
[716/3287] FREI_Q1_Financial-Statements_March-2026-002.pdf... direct (2.8s)
[717/3287] FREI_Q1_Unaudited-Financial-Statement_March-2025.pdf... direct (3.0s)
[718/3287] FREI_Q2_Financial-Statement_June-2025.pdf... direct (3.0s)
[719/3287] FREI_Q2_Financial-Statement_June-2026.pdf... direct (2.8s)
[720/3287] FREI_Q3_Financial-Statement_September-2024.pdf... direct (2.9s)
  -- checkpoint saved (720 jse records so far)
[721/3287] FRREI-Notice-of-Annual-General-Meeting-2025.pdf... direct (0.1s)
[722/3287] FTNA-1st-Quarter-Unaudited-Financial-Report-Sep-2024.pdf... direct (1.5s)
[723/3287] FTNA-2nd-Quarter-Unaudited-Financials-Dec-2025.pdf... direct (2.5s)
[724/3287] FTNA-3rd-Quarter-Unaudited-Financials-2024-25-updated.pdf... direct (1.6s)
[725/3287] FTNA-3rd-Quarter-Unaudited-Financials-2025-26.pdf... needs_ocr_elsewhere (25.4s)
[726/3287] FTNA-Q1-2025-Unaudited-Financial-Report.pdf... direct (2.5s)
[727/3287] FTNA-Unaudited-Financials-Q2.pdf... direct (1.5s)
[728/3287] FY24_MPC-Caribbean-Clean-Energy-Limited-Audited-FS.pdf... direct (3.2s)
[729/3287] FY25_MPC-Caribbean-Clean-Energy-Audited-Financial-Statements.pdf... direct (4.2s)
[730/3287] FY26-Q2-Report-JSE-Publication.pdf... direct (1.6s)
  -- checkpoint saved (730 jse records so far)
[731/3287] FY26-Quarterly-Q1-.pdf... direct (1.7s)
[732/3287] February_2025_analysis.pdf... direct (2.1s)
[733/3287] February_2026_analysis.pdf... direct (2.2s)
[734/3287] Final-1GS-Press-Release_-Farmhouse-Creative.pdf... direct (0.6s)
[735/3287] Final-Directors-Q4.pdf... direct (0.1s)
[736/3287] Final-OOO-First-Quarter-2024-Report-2.pdf... direct (2.6s)
[737/3287] Final-Officers-Q4.pdf... direct (0.0s)
[738/3287] Final-TOP-10-Q4.pdf... direct (0.2s)
[739/3287] Final-The-LAB-Audited-Financial-Statement-2024-JSE-3-2.pdf... needs_ocr_elsewhere (0.1s)
[740/3287] Finalized-Financial-Statements-Everything-Fresh-Limited-2025-1-2.pdf... direct (7.4s)
  -- checkpoint saved (740 jse records so far)
[741/3287] Financial-Statements-2024-Final.pdf... direct (17.1s)
[742/3287] First-Rock-Annual-Report-2025.pdf... direct (7.5s)
[743/3287] First-Rock-Real-Estate-Investments-Ltd-2025-Consolidated-Audited-Results.pdf... direct (21.9s)
[744/3287] First-Rock-Real-Estate-Investments-Ltd-Shareholder-Listing_-December-31-2024.pdf... direct (0.2s)
[745/3287] FirstQuarter.Delay-Notice.Shareholders.2026.Revised-1.pdf... direct (0.1s)
[746/3287] FirstRock-Real-Estate-Investments-Annual-Report-2024.pdf... direct (26.0s)
[747/3287] FirstRock-Real-Estate-Investments-Ltd-Consolidated-Audited-Financial-Results-2024.pdf... direct (24.4s)
[748/3287] Flyer-CEO-Forum-Presenters.pdf... needs_ocr_elsewhere (0.0s)
[749/3287] Fontana-Limited-2024-Audited-Financial-Statements.pdf... direct (7.1s)
[750/3287] Fontana-Limited-2025-Audited-Financial-Statements.pdf... direct (8.2s)
  -- checkpoint saved (750 jse records so far)
[751/3287] Form-of-Acceptance-Final-2025.pdf... direct (0.4s)
[752/3287] Form-of-Proxy-2024-AGM.pdf... direct (0.2s)

[753/3287] Form-of-Proxy-2024-report-Revised.pdf... direct (0.2s)
[754/3287] Form-of-Proxy-2024.pdf... direct (0.5s)
[755/3287] Form-of-Proxy-2025-138SL.pdf... direct (0.2s)
[756/3287] Form-of-Proxy-2025.pdf... direct (0.5s)
[757/3287] Form-of-Proxy-Everything-Fresh-2024.pdf... direct (0.2s)
[758/3287] Form-of-Proxy-Everything-Fresh-2025.pdf... direct (0.2s)
[759/3287] Form-of-Proxy-Mailpac-Group-2024-.pdf... direct (0.2s)
[760/3287] Form-of-Proxy-Mailpac-Group-2025-1.pdf... direct (0.3s)
  -- checkpoint saved (760 jse records so far)
[761/3287] Form-of-Proxy_2026.pdf... direct (0.1s)
[762/3287] Formal-Order-SGJL-July-15-2026.pdf... needs_ocr_elsewhere (0.0s)
[763/3287] Formal-Order-Schemes-of-Arrangement-1.pdf... needs_ocr_elsewhere (0.0s)
[764/3287] FosRich-Amended-Shareholder-Notice-AGM-2025.pdf... direct (0.1s)
[765/3287] FosRich-Company-Limited-2025-Audited-Financial-Statements.pdf... direct (9.9s)
[766/3287] FosRich-Dec-2024-MDA-1.pdf... direct (1.2s)
[767/3287] FosRich-Dec-2025-Shareholder-Information-1.pdf... direct (0.1s)
[768/3287] FosRich-Form-Of-Proxy-AGM-2025.pdf... direct (0.1s)
[769/3287] FosRich-Q1-2025-MDA.pdf... direct (1.3s)
[770/3287] FosRich-Q1-2026-MDA.pdf... direct (1.0s)
  -- checkpoint saved (770 jse records so far)
[771/3287] FosRich-Q2-2025-MDA.pdf... direct (1.0s)
[772/3287] FosRich-Q2-2026-MDA.pdf... direct (1.1s)
[773/3287] FosRich-Q3-2024-MDA-Revised-1.pdf... direct (1.1s)
[774/3287] FosRich-Q3-2025-MDA.pdf... direct (1.2s)
[775/3287] FosRich-Revised-Shareholder-Notice-AGM-2025-1.pdf... direct (0.1s)
[776/3287] FosRich-Shareholder-Instructions-AGM-2025.pdf... direct (0.1s)
[777/3287] FosRich-Shareholder-Notice-AGM-2025.pdf... direct (0.1s)
[778/3287] FosRich-Shareholder-Notice-Director-appointment-Jan-2026.pdf... direct (0.1s)
[779/3287] FosRich-Shareholder-Notice-Executive-Change-June-2026.pdf... direct (0.0s)
[780/3287] Fosrich-Dec-2024-Audited-Accounts-1.pdf... direct (9.1s)
  -- checkpoint saved (780 jse records so far)
[781/3287] Fosrich-Notice-Dividend-Decision-2024-1.pdf... direct (0.0s)
[782/3287] Full-Speech-Financing-Utility-Resilience-in-an-Era-of-Extreme-Events-Livingstone-Morrison-Group-CEO-JSE.pdf... direct (0.6s)
[783/3287] Future-Energy-Source-Co-Ltd_FESCO_2026-Annual-Report-2026.pdf... direct (16.3s)
[784/3287] Future-Energy-Source-Co-Ltd_FESCO_Notice-of-2026-AGM.pdf... direct (0.2s)
[785/3287] Future-Energy-Source-Co-Ltd_FESCO_Proxy-Form-2026-AGM.pdf... direct (0.1s)
[786/3287] Future-Energy-Source-Co.-Ltd_Top-10-Directors-and-Officers-Shareholdings-as-at-31-March-2026.pdf... direct (0.2s)
[787/3287] Future-Energy-Source-Company-Limited-Audited-2025-Financial-Statements-FINAL.pdf... direct (6.4s)
[788/3287] Future-Energy-Source-Company-Limited-Audited-Financial-Statements_Mar2026.pdf... direct (6.8s)
[789/3287] Future-Energy-Source-Company-Limited-FESCO_4yr-Corp-Bond-Disclosure_24Jun2026.pdf... direct (0.1s)
[790/3287] GENAC-2026-Directors-Appointment-Notice.pdf... direct (0.1s)
  -- checkpoint saved (790 jse records so far)
[791/3287] GENAC-Issues-shares-to-CGH-Limited.pdf... direct (0.1s)
[792/3287] GENAC-JSE-Report-Mar-2025_Q1-1.pdf... direct (1.5s)
[793/3287] GENAC-Material-Disclosure-Change-in-External-Auditors.pdf... direct (0.3s)
[794/3287] GENAC_JSE-Report_Dec_-2024_Q4-1.pdf... direct (2.0s)
[795/3287] GENAC_Notice-of-AGM.pdf... needs_ocr_elsewhere (1.6s)
[796/3287] GENAC_Proxy-Form-for-AGM.pdf... needs_ocr_elsewhere (2.1s)
[797/3287] GHL-DELANEY.pdf... direct (0.1s)
[798/3287] GHL-Dividend-Shareholder-ad-Q3.pdf... needs_ocr_elsewhere (0.9s)
[799/3287] GHL-FINANCIAL-STATEMENTS-Q2-2026.pdf... direct (19.4s)
[800/3287] GHL-Financial-Statements-Q3.pdf... direct (1.9s)
  -- checkpoint saved (800 jse records so far)
[801/3287] GHL-NCB-Merchant.pdf... needs_ocr_elsewhere (1.3s)
[802/3287] GHL-Notice-AGM-AREP.pdf... direct (0.1s)
[803/3287] GHL-Notice-AGM-and-AR-9-April-2026.pdf... direct (0.2s)
[804/3287] GHL-Notice-Delay.pdf... direct (0.3s)
[805/3287] GHL-Notice-Dividend-Payment-Q2.pdf... direct (0.1s)
[806/3287] GHL-Notice-Dividend-Payments.pdf... direct (0.1s)
[807/3287] GHL-Notice-FY-End.pdf... direct (0.1s)
[808/3287] GHL-Notice-Patrick-Solomon.pdf... needs_ocr_elsewhere (0.8s)
[809/3287] GHL-Notice-Q1-2026-Dividend-Payment.pdf... direct (0.1s)
[810/3287] GHL-Q1-2025-Dividend-Ad-1.pdf... direct (0.1s)
  -- checkpoint saved (810 jse records so far)
[811/3287] GHL-Q1-2025-Financials-1.pdf... direct (1.3s)
[812/3287] GHL-Q1-2026.pdf... direct (21.4s)
[813/3287] GHL-Q2-2025.pdf... direct (2.0s)
[814/3287] GHL-Q2-Dividend-2025.pdf... direct (0.1s)
[815/3287] GHL-Q4-2024-2.pdf... direct (1.8s)
[816/3287] GHL-Q4-2025-Financials.pdf... direct (18.8s)
[817/3287] GHL-Record-Date-Ad.pdf... direct (0.1s)
[818/3287] GHL-Record-Date-NOM-Ad-Jam-1.pdf... direct (0.1s)
[819/3287] GHL-Restructuring.pdf... needs_ocr_elsewhere (1.2s)
[820/3287] GHL-Shareholder-Ad-Completion-of-Project.pdf... direct (0.1s)
  -- checkpoint saved (820 jse records so far)
[821/3287] GHL-Shareholder-Notice-Acquisition-Project.pdf... direct (0.1s)
[822/3287] GHL-Shareholder-Notice-Bruce-Bowen-resignation.pdf... direct (0.1s)
[823/3287] GHL-Shareholder-Notice-CRO.pdf... direct (0.1s)
[824/3287] GHL-Shareholdings-of-Directors-as-at-Sept-30-2024.pdf... direct (0.1s)
[825/3287] GHL-Shareholdings-of-Officers-as-at-Sept-30-2024.pdf... direct (0.1s)
[826/3287] GHL-Shareholdings-of-persons-holding-top-10-largest-blocks-as-at-Sept-30.pdf... direct (0.1s)
[827/3287] GHL-Summary-of-Consolidated-Financial-Statements-Q3.pdf... direct (2.0s)
[828/3287] GHL-and-its-Subsidiaries-Audited-FS-YE-31-Dec-2024.pdf... direct (31.8s)
    ^ SLOW FILE -- GHL-and-its-Subsidiaries-Audited-FS-YE-31-Dec-2024.pdf took 31.8s
[829/3287] GHL-and-its-Subsidiaries-Audited-FS-YE-31-Dec-2025.pdf... direct (31.7s)
    ^ SLOW FILE -- GHL-and-its-Subsidiaries-Audited-FS-YE-31-Dec-2025.pdf took 31.7s
[830/3287] GHL_2025_Annual_Report_8_April_2026_Compressed2_26adefcc72.pdf... direct (1085.9s)
    ^ SLOW FILE -- GHL_2025_Annual_Report_8_April_2026_Compressed2_26adefcc72.pdf took 1085.9s
  -- checkpoint saved (830 jse records so far)
[831/3287] GK-1st-Quarter-for-the-Period-Jan-Mar-2025.pdf... direct (1.9s)
[832/3287] GK-1st-Quarter-for-the-Period-Jan-March-2026.pdf... direct (2.9s)
[833/3287] GK-2nd-Quarter-for-the-Period-Jan-Jun-2025.pdf... direct (2.3s)
[834/3287] GK-2nd-Quarter-for-the-Period-Jan-June-2026.pdf... direct (3.1s)
[835/3287] GK-3rd-Quarter-for-the-Period-Jan-Sep-2024.pdf... direct (2.4s)
[836/3287] GK-3rd-Quarter-for-the-Period-Jan-Sep-2025.pdf... direct (2.4s)
[837/3287] GK-AR_2024-April-MM5-Web.pdf... direct (69.2s)
    ^ SLOW FILE -- GK-AR_2024-April-MM5-Web.pdf took 69.2s
[838/3287] GK-Annual-Report-2025.pdf... direct (38.4s)
    ^ SLOW FILE -- GK-Annual-Report-2025.pdf took 38.4s
[839/3287] GK-CFO-Dividend-Release-Q1-2025.pdf... direct (0.0s)
[840/3287] GK-CFO-Dividend-Release-Q1-2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (840 jse records so far)
[841/3287] GK-CFO-Dividend-Release-Q2-2025.pdf... direct (0.0s)
[842/3287] GK-CFO-Dividend-Release-Q2-2026.pdf... direct (0.0s)
[843/3287] GK-CFO-Dividend-Release-Q3-2025.pdf... direct (1.2s)
[844/3287] GK-CFO-Dividend-Release-Q4-2024.pdf... direct (0.0s)
[845/3287] GK-CFO-Dividend-Release-Q4-2025.pdf... needs_ocr_elsewhere (0.0s)
[846/3287] GK-CFO-Release-4th-Interim-Dividend-Payment-December-2024.pdf... direct (0.0s)
[847/3287] GK-Dec-2024-Stockholders-Report.pdf... direct (0.4s)
[848/3287] GK-Dec-2025-Stockholders-Report.pdf... direct (0.8s)
[849/3287] GK-Financial-Offer-Extension.pdf... direct (0.1s)
[850/3287] GK-Leadership-Changes-Feb-10-2025-FINAL-004.pdf... direct (0.2s)
  -- checkpoint saved (850 jse records so far)
[851/3287] GWEST-CORPORATION-LTD-Unaudited-Financial-Statements-2nd-Quarter-Ended-September-2024.pdf... needs_ocr_elsewhere (0.0s)
[852/3287] GWEST-CORPORATION-POSTPONEMENT-OF-ANNUAL-GENERAL-MEETING.pdf... direct (0.0s)
[853/3287] GWEST-CORPORATION-Trading-in-Shares.pdf... direct (0.0s)
[854/3287] GWEST-Corporate-Governance-Guidelines-September-2024.pdf... direct (1.6s)
[855/3287] GWEST-Corporation-Notice-Delay-in-Filing-Audited-Financial-Statement-Year-Ended-March-2026.pdf... direct (0.0s)
[856/3287] GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[857/3287] GWest-Corporation-Limited-Delay-in-Filing-Annual-Report.pdf... direct (0.0s)

[858/3287] GWest-Corporation-Limited-GWEST-Audited-Financial-Statements-Year-Ended-March-31-2025.pdf... direct (8.1s)
[859/3287] GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024.pdf... needs_ocr_elsewhere (0.0s)
[860/3287] GWest-Corporation-Limited-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (860 jse records so far)
[861/3287] GWest-Corporation-Ltd-Annual-Report-2025.pdf... direct (8.6s)
[862/3287] GWest-Corporation-Ltd-GWest-Annual-Report-2026.pdf... direct (12.1s)
[863/3287] GWest-Corporation-Ltd-Unaudited-Financial-Statements-3rd-Quarter-Ended-December-31_-2025.pdf... needs_ocr_elsewhere (0.0s)
[864/3287] GWest-Corporation-Trading-in-Shares.pdf... direct (0.0s)
[865/3287] GenAc-JSE-Report-Dec-2025_Q4.pdf... direct (1.3s)
[866/3287] GenAc-JSE-Report-Jun-2025_Q2.pdf... direct (2.1s)
[867/3287] GenAc-JSE-Report-Jun-2026_Q2.pdf... direct (1.8s)
[868/3287] GenAc-JSE-Report-Mar-2026_Q1.pdf... direct (1.6s)
[869/3287] GenAc-JSE-Report-Sep-2025_Q3.pdf... direct (1.7s)
[870/3287] GenAc-JSE-Report-Third-Quarter-2024.pdf... direct (1.6s)
  -- checkpoint saved (870 jse records so far)
[871/3287] General-Accident-Annual-Report-2025.pdf... direct (7.3s)
[872/3287] General-Accident-Annual-Report-_2024.pdf... direct (20.7s)
[873/3287] General-Accident-Ins-Co-Ja-Limited-FS-2025-Final.pdf... direct (216.4s)
    ^ SLOW FILE -- General-Accident-Ins-Co-Ja-Limited-FS-2025-Final.pdf took 216.4s
[874/3287] General-Accident-Ins-Co-Ja-Ltd-Audited-Financial-Statements-2024.pdf... direct (22.1s)
[875/3287] General-Accident-Proxy-Form-2024.pdf... needs_ocr_elsewhere (4.2s)
[876/3287] General_Accident-Notice_Of_AGM.pdf... needs_ocr_elsewhere (2.0s)
[877/3287] GraceKennedy-AGM-Notice-2025.pdf... direct (0.2s)
[878/3287] GraceKennedy-Limited-Financial-Statements-2024-Final.pdf... direct (29.9s)
[879/3287] GraceKennedy-Limited-Financial-Statements-2025.pdf... direct (28.9s)
[880/3287] GraceKennedy-Notice-of-Annual-General-Meeting-2026.pdf... direct (1.0s)
  -- checkpoint saved (880 jse records so far)
[881/3287] GraceKennedy-Proxy-Form-2025-Fill.pdf... direct (0.9s)
[882/3287] GraceKennedy-Proxy-Form-2025.pdf... direct (1.0s)
[883/3287] GraceKennedy-Proxy-Form-2026-AGM-Digital-Fill.pdf... direct (0.1s)
[884/3287] GraceKennedy-Q1-2025-Results-Release.pdf... direct (0.2s)
[885/3287] GraceKennedy-Q1-2026-Results-Release-final.pdf... direct (0.2s)
[886/3287] GraceKennedy-Q2-2025-Results-Release.pdf... direct (0.3s)
[887/3287] GraceKennedy-Q2-2026-Results-Release-final.pdf... direct (0.1s)
[888/3287] GraceKennedy-Q3-2024-Results-Release.pdf... direct (0.2s)
[889/3287] GraceKennedy-Q3-2025-Results-Release-1.pdf... direct (0.3s)
[890/3287] Guardian_Group_2024_Annual_Report_April_16_2025_Compressed_de29a7572d.pdf... direct (1052.1s)
    ^ SLOW FILE -- Guardian_Group_2024_Annual_Report_April_16_2025_Compressed_de29a7572d.pdf took 1052.1s
  -- checkpoint saved (890 jse records so far)
[891/3287] Gwest-Corp-Unaudited-2nd-quarter-September-2025-Financial-Statement.pdf... needs_ocr_elsewhere (0.0s)
[892/3287] Gwest-Corporation-Ltd-GWEST-Audited-Financial-Statement-Year-Ended-March-2026.pdf... direct (7.0s)
[893/3287] H1-Stockholders-2025-Report.pdf... needs_ocr_elsewhere (0.0s)
[894/3287] HONBUN-1st-Quarter-Report-2025.pdf... needs_ocr_elsewhere (0.0s)
[895/3287] HONBUN-Annual-Report-2024.pdf... direct (11.8s)
[896/3287] HONBUN-Annual-Report-2025-2.pdf... direct (47.8s)
    ^ SLOW FILE -- HONBUN-Annual-Report-2025-2.pdf took 47.8s
[897/3287] HONBUN-Financial-Statements-1st-Quarter-2025.pdf... direct (2.1s)
[898/3287] HONBUN-Financial-Statements-2nd-Quarter-2025.pdf... direct (1.7s)
[899/3287] HONBUN-Financial-Statements-2nd-Quarter-2026.pdf... direct (1.6s)
[900/3287] HONBUN-Financial-Statements-3rd-Quarter-2025.pdf... direct (1.7s)
  -- checkpoint saved (900 jse records so far)
[901/3287] HONBUN-Financial-Statements-3rd-Quarter-2026.pdf... needs_ocr_elsewhere (0.0s)
[902/3287] HONBUN-Financial-Statements-Year-End-2024.pdf... direct (5.7s)
[903/3287] HONBUN-Financial-Statements-Yr-End-September-30-2025.pdf... direct (6.5s)
[904/3287] HONBUN-Shareholders-Listing-as-at-September-30-2022.pdf... direct (0.4s)
[905/3287] HONBUN-Shareholders-Listing-as-at-September-30-2023.pdf... direct (0.1s)
[906/3287] HONBUN-Shareholders-Listing-as-at-September-30-2024.pdf... direct (0.1s)
[907/3287] HONBUN-Shareholders-Profile-2024.pdf... direct (0.1s)
[908/3287] IDB-PBS-.pdf... direct (0.2s)
[909/3287] IEG-Annual-Report-2025.pdf... direct (8.7s)
[910/3287] IEG-Annual-Report-31-May-2024-1.pdf... direct (3.8s)
  -- checkpoint saved (910 jse records so far)
[911/3287] IEG-Audited-Financial-Statements-May-2024.pdf... direct (4.2s)
[912/3287] IEG-Unaudited-Q1-2024-Report.pdf... direct (0.4s)
[913/3287] IEG-Unaudited-Q1-2025.pdf... direct (0.9s)
[914/3287] IEG-Unaudited-Q2-2024-Report.pdf... direct (1.4s)
[915/3287] IEG-Unaudited-Q2-2025-Report.pdf... direct (1.0s)
[916/3287] IEG-Unaudited-Q3-2025-Report-revised.pdf... direct (0.3s)
[917/3287] IEG-Unaudited-Q3-2026-Report.pdf... direct (0.2s)
[918/3287] IEG-Unaudited-Q4-2025-Report-1.pdf... direct (0.4s)
[919/3287] IEG-Unaudited-Q4-2026-Report.pdf... direct (0.6s)
[920/3287] IMAGE-PLUS-CONSULTANTS-LIMITED-%E2%80%93-NOTICE-OF-PROPOSED-ACQUISITION.pdf... direct (0.1s)
  -- checkpoint saved (920 jse records so far)
[921/3287] IPCL-Disclosure-to-the-Jamaica-Stock-Exchange-IR-April-29-2026.pdf... direct (0.1s)
[922/3287] IPCL-Form-of-proxy-2025.pdf... direct (0.4s)
[923/3287] IPCL-Shareholder-Letter-2025.pdf... direct (0.4s)
[924/3287] IPJL-Auditors-1.pdf... needs_ocr_elsewhere (0.0s)
[925/3287] IRONROCKDIRECTORSReport-December-312024.pdf... direct (0.3s)
[926/3287] IRONROCKTop-10-ShareholdersReport-December-312024.pdf... direct (0.1s)
[927/3287] IRoc-Top-10-Shareholders-as-at-Dec-31-2025.pdf... direct (0.1s)
[928/3287] ISP-2024-Annual-Report.pdf... direct (10.4s)
[929/3287] ISP-2024-Re-scheduled-AGM-JSE-Notice-May-26-2026.pdf... direct (0.1s)
[930/3287] ISP-2nd-Quarter-Filing-Report-Revised.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (930 jse records so far)
[931/3287] ISP-3rd-Quarter-J.S.E.-Filing-Report.pdf... needs_ocr_elsewhere (0.0s)
[932/3287] ISP-4th-Qtr-JSE-Filing-Report.pdf... needs_ocr_elsewhere (0.0s)
[933/3287] ISP-Annual-Report_2023-Final-Report.pdf... direct (13.3s)
[934/3287] ISP-Audited-FS-Signed.pdf... direct (8.5s)
[935/3287] ISP-Finance-Services-Limited-Audited-Financial-Statements.pdf... direct (7.8s)
[936/3287] ISP-JSE-4th-Quarter-Filing-Report.pdf... needs_ocr_elsewhere (0.0s)
[937/3287] ISP-JSE-Filing-Report-2nd-Quarter-Ended-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[938/3287] ISP-JSE-Filing-Report-3rd-Quarter-ended-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[939/3287] ISP-JSE-Notice-2024-Annual-Report-December-12-2025.pdf... direct (0.0s)
[940/3287] ISP-JSE-Notice-2024-Annual-Report-June-03-2025.pdf... direct (0.3s)
  -- checkpoint saved (940 jse records so far)
[941/3287] ISP-JSE-Notice-April-25-2025.pdf... direct (0.0s)
[942/3287] ISP-JSE-Notice-February-12-2025.pdf... direct (0.0s)
[943/3287] ISP-JSE-Notice-February-19-2025.pdf... direct (0.1s)
[944/3287] ISP-JSE-Notice-February-25-2025.pdf... direct (0.1s)
[945/3287] ISP-JSE-Notice-June-26-2026.pdf... direct (0.0s)
[946/3287] ISP-JSE-Notice-March-28-2025.pdf... direct (0.0s)
[947/3287] ISP-JSE-Notice-March-30-2026.pdf... direct (0.0s)
[948/3287] ISP-JSE-Notice-November-15-2024.pdf... direct (0.1s)
[949/3287] Image-Plus-3rd-Quarter-Interim-Report-November-30-2024.pdf... direct (1.6s)
[950/3287] Image-Plus-Annual-Report-2024-2025_FSE.pdf... direct (14.1s)
  -- checkpoint saved (950 jse records so far)
[951/3287] Image-Plus-Consultants-Limited-2nd-Quarter-Interim-Report-August-31-2024.pdf... direct (1.3s)
[952/3287] Image-Plus-Consultants-Limited-FS2026.pdf... direct (7.4s)
[953/3287] Image-Plus-Consultants-Limited-Unaudited-1st-Quarter-Report-May-31-2025.pdf... direct (1.8s)
[954/3287] Image-Plus-Consultants-Limited-Unaudited-1st-Quarter-Report-May-31-2026.pdf... direct (1.4s)
[955/3287] Image-Plus-Consultants-Limited-Unaudited-2nd-Quarter-Report-August-31-2025.pdf... direct (1.9s)
[956/3287] Image-Plus-Consultants-Limited-Unaudited-3rd-Quarter-Report-November-30-2025.pdf... direct (2.1s)
[957/3287] Image-Plus-Consultants-Limited_28Feb2025.pdf... direct (6.3s)
[958/3287] Image-Plus_Annual-Report_2026_F.pdf... direct (13.9s)
[959/3287] ImagePlus-AGMNotice2025.pdf... direct (0.5s)
[960/3287] Increased-Shareholding-in-tTech-by-Simply-Secure.pdf... direct (0.1s)
  -- checkpoint saved (960 jse records so far)
[961/3287] Indies-Pharma-AR-25-3-1.pdf... direct (27.0s)
[962/3287] Indies-Pharma-Jamaica-Limited-2024-The-Consolidated-Final-1-1.pdf... direct (8.0s)
[963/3287] Innovative-Energy-Group-Limited-Audited-Consolidated-Financial-Statements-2025.pdf... direct (8.4s)
[964/3287] Interim-Financial-Statements-Sept-2024-1.pdf... needs_ocr_elsewhere (0.0s)
[965/3287] IronRock-Insurance-Annual-2025-Report.pdf... direct (11.6s)
[966/3287] IronRock-Insurance-Company-Annual-Report-2023.pdf... direct (10.1s)
[967/3287] IronRock-Insurance-Company-Annual-Report-2024.pdf... direct (12.7s)
[968/3287] IronRock-Insurance-Company-Limited_Signed-Financial-Statements_2024.pdf... direct (7.0s)
[969/3287] Ironrock-Insurance-Company-Limited-Financial-Statements-2025_Final.pdf... direct (6.3s)
[970/3287] JAMAICA-MONEY-MARKET-BROKERS-LIMITED-Annual-Report-2024-.pdf... direct (17.2s)
  -- checkpoint saved (970 jse records so far)
[971/3287] JAMAICA-MONEY-MARKET-BROKERS-LIMITED-Annual-Report-2026-_Jul29.pdf... direct (17.6s)
[972/3287] JAMAICA-MONEY-MARKET-BROKERS-LIMITED-Annual-Report-ye-March-31-2025-.pdf... direct (15.8s)
[973/3287] JAMAICA-STOCK-EXCHANGE-RELEASE-Leadership-Update.pdf... direct (0.1s)
[974/3287] JAMT-Directors-Holding-as-at-December-31-2025.pdf... direct (0.1s)
[975/3287] JAMT-Directors-Holding-as-at-June-30-2025.pdf... direct (0.2s)
[976/3287] JAMT-Directors-Holding-as-at-June-30-2026-adjusted.pdf... direct (0.1s)
[977/3287] JAMT-Directors-Holding-as-at-March-31-2026.pdf... needs_ocr_elsewhere (3.5s)
[978/3287] JAMT-Directors-Holding-as-at-September-30-2024.pdf... direct (0.1s)
[979/3287] JAMT-Directors-Holding-as-at-September-30-2025.pdf... direct (0.2s)
[980/3287] JAMT-Directors-Report-as-at-December-31-2024.pdf... direct (0.2s)
  -- checkpoint saved (980 jse records so far)
[981/3287] JAMT-Senior-Managers-Holding-as-at-December-31-2024.pdf... direct (0.2s)
[982/3287] JAMT-Senior-Managers-Holding-as-at-December-31-2025.pdf... direct (0.1s)
[983/3287] JAMT-Senior-Managers-Holding-as-at-June-30-2025.pdf... direct (0.2s)
[984/3287] JAMT-Senior-Managers-Holding-as-at-June-30-2026.pdf... direct (0.2s)
[985/3287] JAMT-Senior-Managers-Holding-as-at-March-312026.pdf... needs_ocr_elsewhere (3.2s)
[986/3287] JAMT-Senior-Managers-Holding-as-at-September-30-2024.pdf... direct (0.1s)
[987/3287] JAMT-Senior-Managers-Holding-as-at-September-30-2025.pdf... direct (0.2s)
[988/3287] JAMT-Top-10-Shareholders-as-at-Dec-31-2024.pdf... direct (0.1s)
[989/3287] JAMT-Top-Ten-Shareholders-as-at-December-31-2025.pdf... direct (0.1s)
[990/3287] JAMT-Top-Ten-Shareholders-as-at-June-30-2025.pdf... direct (0.1s)
  -- checkpoint saved (990 jse records so far)
[991/3287] JAMT-Top-Ten-Shareholders-as-at-June-30-2026.pdf... direct (0.1s)
[992/3287] JAMT-Top-Ten-Shareholders-as-at-March-31-2025.pdf... direct (0.1s)
[993/3287] JAMT-Top-Ten-Shareholders-as-at-March-31-2026.pdf... direct (0.1s)
[994/3287] JAMT-Top-Ten-Shareholders-as-at-September-30-2024.pdf... direct (0.1s)
[995/3287] JAMT-Top-Ten-Shareholders-as-at-September-30-2025-1.pdf... direct (0.1s)
[996/3287] JAMTSeniorManagersHoldingasatMarch312025.pdf... direct (0.1s)
[997/3287] JBG-2025-2026-Q2-Interim-Report.pdf... direct (3.5s)
[998/3287] JBG-2025_2026-Q1-Interim-Report.pdf... direct (2.9s)
[999/3287] JBG-2025_2026-Q3-Interim-Report-FINAL.pdf... direct (3.0s)
[1000/3287] JBG-Annual-Report-2025.pdf... direct (21.9s)
  -- checkpoint saved (1000 jse records so far)
[1001/3287] JBG-P1_2025-2026-Provisional-Report-JSE-Notice-final.pdf... direct (0.1s)
[1002/3287] JBG-P2_2025-2026-Provisional-Report-JSE-Notice-final.pdf... direct (0.1s)
[1003/3287] JBG-P4_2025-2026-Provisional-Report-JSE-Notice.pdf... direct (0.1s)
[1004/3287] JBG-Provisional-Report-Period-03-2025-26.pdf... direct (0.2s)
[1005/3287] JBG-Q1_2024-2025-Interim-Report.pdf... direct (1.1s)
[1006/3287] JBG-Q2_2024-2025-Interim-Report.pdf... direct (1.2s)
[1007/3287] JBG-Q3-Interim-Report-to-Shareholders-2025-01-25.pdf... direct (1.2s)
[1008/3287] JBGTop10ShareholdersasatAugust22025.pdf... direct (0.1s)
[1009/3287] JCSD-Noteholder-Advisory-July-2025-Observer-Full-Page-copy.pdf... direct (0.5s)
[1010/3287] JETCON-Top-10-Shareholders-as-at-December-31-2024.pdf... direct (1.0s)
  -- checkpoint saved (1010 jse records so far)
[1011/3287] JETCON-Top-10-Shareholders-as-at-December-31-2025.pdf... direct (0.1s)
[1012/3287] JETCON-Top-10-Shareholders-as-at-June-30-2026.pdf... direct (0.1s)
[1013/3287] JETCON-Top-10-Shareholders-as-at-March-31-2025.pdf... direct (0.1s)
[1014/3287] JETCON-Top-10-Shareholders-as-at-March-31-2026.pdf... direct (0.1s)
[1015/3287] JETCON-Top-10-Shareholders-as-at-September-30-2024.pdf... direct (0.1s)
[1016/3287] JETCONTop10ShareholdersasatJune302025.pdf... direct (0.1s)
[1017/3287] JETCONTop10ShareholdersasatSeptember302025.pdf... direct (0.1s)
[1018/3287] JFP-Annual-Report-2025.pdf... direct (7.1s)
[1019/3287] JFP-Limited-1st-Quarterly-Report-for-Period-Ended-March-312025-1.pdf... direct (1.0s)
[1020/3287] JFP-Limited-2024-PDF-Financial-Statements-Audited.pdf... direct (6.0s)
  -- checkpoint saved (1020 jse records so far)
[1021/3287] JFP-Limited-2025-Audited-Financial-Statements.pdf... direct (6.2s)
[1022/3287] JFP-Limited-2nd-Quarterly-Report-for-Period-Ended-June-30-2025.pdf... direct (1.7s)
[1023/3287] JFP-Limited-4th-Quarterly-Financial-Report-for-period-ended-December-312025.pdf... direct (1.1s)
[1024/3287] JFP-Limited-4th-Quarterly-report-for-period-ended-December-312024-14.2.2024.pdf... direct (1.0s)
[1025/3287] JFP-Limited-Annual-Report-2024_compressed.pdf... direct (7.7s)
[1026/3287] JFP-Limited-Quarterly-Financial-Report-for-period-ended-September-302025.pdf... direct (1.3s)
[1027/3287] JFP-Ltd-3rd-Quarterly-report-for-period-ended-September-302024.pdf... direct (1.0s)
[1028/3287] JFP-Ltd-Quarterly-Financial-Statement-for-period-ending-June-30-2026.pdf... needs_ocr_elsewhere (0.1s)
[1029/3287] JFP-Press-Release-11-June-2026-Amended-.pdf... direct (0.4s)
[1030/3287] JFP-Press-notice-12-Jun-2026-CFO.pdf... direct (0.0s)
  -- checkpoint saved (1030 jse records so far)
[1031/3287] JFP-Press-release-11-Jun-2026-amended-with-dates1.pdf... direct (0.6s)
[1032/3287] JFP_Limited_Q1_2026_-FINAL-15.5.2025.pdf... direct (2.0s)
[1033/3287] JMMB-GL-5.75-Notice-of-General-Meeting-Feb-2025-.pdf... direct (0.4s)
[1034/3287] JMMB-GL-7.25-Notice-of-General-meeting-2025-.pdf... direct (0.3s)
[1035/3287] JMMB-GL-Notice-of-Audited-Financial-Statements-March-1-2025-.pdf... direct (0.2s)
[1036/3287] JMMB-GROUP-LIMITED-2018-PREFERENCE-SHARES-VARIATION-OF-TERMS.pdf... direct (0.0s)
[1037/3287] JMMB-GROUP-LIMITED_SHAREHOLDING-LIST_DIRECTORS-AND-SNR-MGRS_YEAR-ENDED-31-MARCH-2026-1.pdf... direct (0.1s)
[1038/3287] JMMB-GROUP-LIMITED_SHAREHOLDING-LIST_DIRECTORS-AND-SNR-MGRS_YEAR-ENDED-31-MARCH-2026.pdf... direct (0.1s)
[1039/3287] JMMB-GROUP-LIMITED_TOP-10-SHAREHOLDER-LIST_YEAR-ENDED-31-MARCH-2026.pdf... direct (0.1s)
[1040/3287] JMMB-Group-Limited-2025-Annual-Report--1.pdf... direct (71.5s)
    ^ SLOW FILE -- JMMB-Group-Limited-2025-Annual-Report--1.pdf took 71.5s
  -- checkpoint saved (1040 jse records so far)
[1041/3287] JMMB-Group-Limited-Audited-Financial-Results-for-year-ended-31-March-2026.pdf... direct (19.1s)
[1042/3287] JMMB-Group-Limited-JMMB-GL-List-of-Top-10-Shareholders-for-the-year-ended-March-31-2025-.pdf... direct (0.1s)
[1043/3287] JMMB-Group-Limited-JMMB-GL-Shareholdings-of-Directors-and-Senior-Managers-for-the-year-ended-March-31-2025.pdf... direct (0.2s)
[1044/3287] JMMB-Group-Limited-JMMBGL-Audited-Financial-Results-for-the-year-ended-31-March-2025.pdf... direct (17.7s)

[1045/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-2nd-quarter-ended-September-30-2025.pdf... direct (1.4s)
[1046/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-December-31-2024.pdf... direct (1.9s)
[1047/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-December-31-2025.pdf... direct (1.7s)
[1048/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-June-30-2025.pdf... direct (1.5s)
[1049/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-June-30-2026.pdf... direct (1.6s)
[1050/3287] JMMB-Group-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-September-30-2024-1.pdf... direct (1.6s)
  -- checkpoint saved (1050 jse records so far)
[1051/3287] JMMB-Group-Ltd-Annual-Report-2026.pdf... direct (60.1s)
    ^ SLOW FILE -- JMMB-Group-Ltd-Annual-Report-2026.pdf took 60.1s
[1052/3287] JMMB-Notification-to-Extend-2018-Pref-Shares-Amended.pdf... direct (1.3s)
[1053/3287] JPG-2024-Annual-Report.pdf... direct (14.4s)
[1054/3287] JPG-Corporate-Governance-Policy-final.pdf... direct (1.7s)
[1055/3287] JPG-Release-With-Highlights-Q1-2025-Final.pdf... direct (2.3s)
[1056/3287] JPG-Release-With-Highlights-Q1-2026-Final.pdf... direct (1.9s)
[1057/3287] JPG-Release-With-Highlights-Q2-2025-Final.pdf... direct (1.9s)
[1058/3287] JPG-Release-With-Highlights-Q2-2026-Final.pdf... direct (1.7s)
[1059/3287] JPG-Release-With-Highlights-Q3-2024-Final.pdf... direct (2.2s)
[1060/3287] JPG-Release-With-Highlights-Q3-2025-Final.pdf... direct (2.0s)
  -- checkpoint saved (1060 jse records so far)
[1061/3287] JPG-Release-With-Highlights-Q4-2024-Final.pdf... direct (2.4s)
[1062/3287] JPG-Release-With-Highlights-Q4-2025.pdf... direct (2.0s)
[1063/3287] JPS-Interim-Financials-June-2026_0183.pdf... direct (1.6s)
[1064/3287] JPS-Ordinary-Top-Ten-December-31-2024.pdf... direct (0.0s)
[1065/3287] JPS-Ordinary-Top-Ten-December-31-2025-1.pdf... direct (0.0s)
[1066/3287] JPS-Ordinary-Top-Ten-December-31-2025.pdf... direct (0.0s)
[1067/3287] JPS-Ordinary-Top-Ten-June-30-2025.pdf... direct (0.0s)
[1068/3287] JPS-Ordinary-Top-Ten-June-30-2026.pdf... direct (0.0s)
[1069/3287] JPS-Ordinary-Top-Ten-March-31-2026-1.pdf... direct (0.0s)
[1070/3287] JPS-Pref-5D-Top-10-%40-June-30-2026.pdf... direct (0.1s)
  -- checkpoint saved (1070 jse records so far)
[1071/3287] JPS-Pref-5D-Top-10-%40-March-31-2025.pdf... direct (0.1s)
[1072/3287] JPS-Pref-5D-Top-10-%40-September-30-2024-1.pdf... direct (0.1s)
[1073/3287] JPS-Pref-B-Top-Ten-%40-June-30-2026.pdf... direct (0.1s)
[1074/3287] JPS-Pref-B-Top-Ten-%40-March-31-2025.pdf... direct (0.1s)
[1075/3287] JPS-Pref-B-Top-Ten-%40-September-30-2024-1.pdf... direct (0.1s)
[1076/3287] JPS-Pref-C-Top-10-%40-September-30-2024-1.pdf... direct (0.2s)
[1077/3287] JPS-Pref-C-Top-Ten-%40-June-30-2025.pdf... direct (0.1s)
[1078/3287] JPS-Pref-C-Top-Ten-%40-June-30-2026.pdf... direct (0.1s)
[1079/3287] JPS-Pref-C-Top-Ten-%40-March-31-2025.pdf... direct (0.1s)
[1080/3287] JPS-Pref-C-Top-Ten-%40-March-31-2026-1.pdf... direct (0.1s)
  -- checkpoint saved (1080 jse records so far)
[1081/3287] JPS-Pref-E-6-Top-Ten-%40-March-31-2025.pdf... direct (0.1s)
[1082/3287] JPS-Pref-E-6-Top-Ten-%40-September-30-2024-1.pdf... direct (0.2s)
[1083/3287] JPS-Pref-F-9.5-Top-10-June-30-2026.pdf... direct (0.1s)
[1084/3287] JPS-Pref-F-9.5-Top-10-March-31-2025.pdf... direct (0.1s)
[1085/3287] JPS-Pref-F-9.5-Top-10-as-at-Decembber-31-2024.pdf... direct (0.1s)
[1086/3287] JPS-Pref-F-9.5-Top-10-as-at-December-31-2025-1.pdf... direct (0.1s)
[1087/3287] JPS-Pref-F-9.5-Top-10-as-at-December-31-2025.pdf... direct (0.1s)
[1088/3287] JPS-Pref-F-9.5-Top-10-as-at-June-30-2025.pdf... direct (0.1s)
[1089/3287] JPS-Pref-F-9.5-Top-10-as-at-MSeptember-30-2024-1.pdf... direct (0.2s)
[1090/3287] JPS-Pref-F-9.5-Top-10-as-at-March-31-2026-1.pdf... direct (0.1s)
  -- checkpoint saved (1090 jse records so far)
[1091/3287] JPS-Pref-F-9.5-Top-10-as-at-September-30-2025-2.pdf... direct (0.1s)
[1092/3287] JPS-Senior-Manager-%40-December-31-2024.pdf... direct (0.1s)
[1093/3287] JPS-Senior-Manager-%40-December-31-2025-.pdf... direct (0.1s)
[1094/3287] JPS-Senior-Manager-%40-December-31-2025-1.pdf... direct (0.1s)
[1095/3287] JPS-Senior-Manager-%40-June-30-2026-.pdf... direct (0.1s)
[1096/3287] JPS-Senior-Manager-%40-March-31-2026-1.pdf... direct (0.1s)
[1097/3287] JPS-TOP-10-Ordinary-December-31-2025-major.pdf... direct (0.1s)
[1098/3287] JPS-Unaudited-Financials-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[1099/3287] JPS-Unaudited-Quarterly-Financials-March-31-2025-signed.pdf... needs_ocr_elsewhere (0.0s)
[1100/3287] JPS-Unaudited-September-30-2025-2.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1100 jse records so far)
[1101/3287] JPS-ar-2025-WEB-2.pdf... direct (17.5s)
[1102/3287] JPSB7-Top-10-as-at-Dec-31-2024.pdf... direct (0.1s)
[1103/3287] JPSB7_-_Top_10_as_at_Dec_31_20241.pdf... direct (0.1s)
[1104/3287] JPSC5-Top-10-as-at-Dec-31-2024.pdf... direct (0.1s)
[1105/3287] JPSC5_-_Top_10_as_at_Dec_31_20241.pdf... direct (0.1s)
[1106/3287] JPSCo-2024-FS-Final.pdf... direct (7.6s)
[1107/3287] JPSD5-Top-10-as-at-Dec-31-2024.pdf... direct (0.1s)
[1108/3287] JPSD5_-_Top_10_as_at_Dec_31_20241.pdf... direct (0.1s)
[1109/3287] JPSE6-Top-10-as-at-Dec-31-2024.pdf... direct (0.1s)
[1110/3287] JPSE6_-_Top_10_as_at_Dec_31_20241.pdf... direct (0.1s)
  -- checkpoint saved (1110 jse records so far)
[1111/3287] JPSOrdinary-TopTen-September302025-1-2.pdf... direct (0.0s)
[1112/3287] JPSSeniorManager%40September302025-2.pdf... direct (0.5s)
[1113/3287] JPS_Interim_Financial_Statements_Dec_2024final1.pdf... needs_ocr_elsewhere (0.0s)
[1114/3287] JPS_Ordinary_-_Top_Ten_-_December_31_20241.pdf... direct (0.0s)
[1115/3287] JPS_Pref_F_9.5_Top_10_-_as_at_Decembber_31_20241.pdf... direct (0.1s)
[1116/3287] JPS_Senior_Manager_%40_December_31_20241.pdf... direct (0.1s)
[1117/3287] JSE-49th-AGM-Notice-May-1-2026.pdf... direct (0.3s)
[1118/3287] JSE-AGM-PROXY-FORM-2026.pdf... direct (0.1s)
[1119/3287] JSE-AHPC-appointment-of-FC-august-2026.pdf... direct (0.1s)
[1120/3287] JSE-Advisory-re-Close-of-Business.pdf... direct (0.2s)
  -- checkpoint saved (1120 jse records so far)
[1121/3287] JSE-BEST-PRACTICES-LISTED-COMPANY-MEMBER-DEALER-Winners-2024-for-2023-Awards.pdf... direct (0.4s)
[1122/3287] JSE-Bond-Indices-April-1-2025.pdf... direct (0.1s)
[1123/3287] JSE-Bond-Indices-April-1-2026.pdf... direct (0.1s)
[1124/3287] JSE-Bond-Indices-April-10-2026.pdf... direct (0.1s)
[1125/3287] JSE-Bond-Indices-April-102025.pdf... direct (0.1s)
[1126/3287] JSE-Bond-Indices-April-112025.pdf... direct (0.1s)
[1127/3287] JSE-Bond-Indices-April-13-2026.pdf... direct (0.1s)
[1128/3287] JSE-Bond-Indices-April-14-2025.pdf... direct (0.1s)
[1129/3287] JSE-Bond-Indices-April-14-2026.pdf... direct (0.1s)
[1130/3287] JSE-Bond-Indices-April-15-2025.pdf... direct (0.1s)
  -- checkpoint saved (1130 jse records so far)
[1131/3287] JSE-Bond-Indices-April-15-2026.pdf... direct (0.1s)
[1132/3287] JSE-Bond-Indices-April-16-2025.pdf... direct (0.2s)
[1133/3287] JSE-Bond-Indices-April-16-2026.pdf... direct (0.1s)
[1134/3287] JSE-Bond-Indices-April-17-2025.pdf... direct (0.1s)
[1135/3287] JSE-Bond-Indices-April-17-2026.pdf... direct (0.1s)
[1136/3287] JSE-Bond-Indices-April-2-2025.pdf... direct (0.1s)
[1137/3287] JSE-Bond-Indices-April-2-2026-1.pdf... direct (0.1s)
[1138/3287] JSE-Bond-Indices-April-20-2026.pdf... direct (0.1s)
[1139/3287] JSE-Bond-Indices-April-21-2026.pdf... direct (0.1s)
[1140/3287] JSE-Bond-Indices-April-22-2025.pdf... direct (0.1s)
  -- checkpoint saved (1140 jse records so far)
[1141/3287] JSE-Bond-Indices-April-22-2026.pdf... direct (0.1s)
[1142/3287] JSE-Bond-Indices-April-23-2025.pdf... direct (0.2s)
[1143/3287] JSE-Bond-Indices-April-23-2026.pdf... direct (0.1s)
[1144/3287] JSE-Bond-Indices-April-24-2025.pdf... direct (0.1s)
[1145/3287] JSE-Bond-Indices-April-24-2026.pdf... direct (0.1s)
[1146/3287] JSE-Bond-Indices-April-25-2025.pdf... direct (0.1s)
[1147/3287] JSE-Bond-Indices-April-27-2026.pdf... direct (0.1s)
[1148/3287] JSE-Bond-Indices-April-28-2025.pdf... direct (0.1s)
[1149/3287] JSE-Bond-Indices-April-28-2026.pdf... direct (0.1s)
[1150/3287] JSE-Bond-Indices-April-29-2025.pdf... direct (0.1s)

  -- checkpoint saved (1150 jse records so far)
[1151/3287] JSE-Bond-Indices-April-29-2026.pdf... direct (0.1s)
[1152/3287] JSE-Bond-Indices-April-3-2025.pdf... direct (0.1s)
[1153/3287] JSE-Bond-Indices-April-30-2025.pdf... direct (0.2s)
[1154/3287] JSE-Bond-Indices-April-30-2026.pdf... direct (0.1s)
[1155/3287] JSE-Bond-Indices-April-4-2025.pdf... direct (0.1s)
[1156/3287] JSE-Bond-Indices-April-7-2025.pdf... direct (0.1s)
[1157/3287] JSE-Bond-Indices-April-7-2026.pdf... direct (0.1s)
[1158/3287] JSE-Bond-Indices-April-8-2025.pdf... direct (0.1s)
[1159/3287] JSE-Bond-Indices-April-8-2026.pdf... direct (0.1s)
[1160/3287] JSE-Bond-Indices-April-9-2025.pdf... direct (0.1s)
  -- checkpoint saved (1160 jse records so far)
[1161/3287] JSE-Bond-Indices-April-9-2026.pdf... direct (0.1s)
[1162/3287] JSE-Bond-Indices-Aug-16-2024.pdf... direct (0.1s)
[1163/3287] JSE-Bond-Indices-Aug-19-2024.pdf... direct (0.1s)
[1164/3287] JSE-Bond-Indices-Aug-20-2024.pdf... direct (0.2s)
[1165/3287] JSE-Bond-Indices-Aug-21-2024.pdf... direct (0.1s)
[1166/3287] JSE-Bond-Indices-Aug-22-2024.pdf... direct (0.1s)
[1167/3287] JSE-Bond-Indices-Aug-23-2024.pdf... direct (0.1s)
[1168/3287] JSE-Bond-Indices-Aug-26-2024.pdf... direct (0.1s)
[1169/3287] JSE-Bond-Indices-Aug-27-2024.pdf... direct (0.1s)
[1170/3287] JSE-Bond-Indices-Aug-28-2024.pdf... direct (0.1s)
  -- checkpoint saved (1170 jse records so far)
[1171/3287] JSE-Bond-Indices-Aug-29-2024.pdf... direct (0.1s)
[1172/3287] JSE-Bond-Indices-Aug-30-2024.pdf... direct (0.1s)
[1173/3287] JSE-Bond-Indices-August-10-2026.pdf... direct (0.1s)
[1174/3287] JSE-Bond-Indices-August-11-2025.pdf... direct (0.2s)
[1175/3287] JSE-Bond-Indices-August-11-2026.pdf... direct (0.1s)
[1176/3287] JSE-Bond-Indices-August-12-2025.pdf... direct (0.1s)
[1177/3287] JSE-Bond-Indices-August-12-2026.pdf... direct (0.1s)
[1178/3287] JSE-Bond-Indices-August-13-2025.pdf... direct (0.1s)
[1179/3287] JSE-Bond-Indices-August-13-2026.pdf... direct (0.1s)
[1180/3287] JSE-Bond-Indices-August-14-2025.pdf... direct (0.1s)
  -- checkpoint saved (1180 jse records so far)
[1181/3287] JSE-Bond-Indices-August-14-2026.pdf... direct (0.1s)
[1182/3287] JSE-Bond-Indices-August-15-2025.pdf... direct (0.1s)
[1183/3287] JSE-Bond-Indices-August-18-2025.pdf... direct (0.1s)
[1184/3287] JSE-Bond-Indices-August-19-2025.pdf... direct (0.1s)
[1185/3287] JSE-Bond-Indices-August-20-2025.pdf... direct (0.2s)
[1186/3287] JSE-Bond-Indices-August-21-2025-1.pdf... direct (0.1s)
[1187/3287] JSE-Bond-Indices-August-22-2025.pdf... direct (0.1s)
[1188/3287] JSE-Bond-Indices-August-25-2025.pdf... direct (0.1s)
[1189/3287] JSE-Bond-Indices-August-26-2025.pdf... direct (0.1s)
[1190/3287] JSE-Bond-Indices-August-27-2025.pdf... direct (0.1s)
  -- checkpoint saved (1190 jse records so far)
[1191/3287] JSE-Bond-Indices-August-28-2025.pdf... direct (0.1s)
[1192/3287] JSE-Bond-Indices-August-29-2025-1.pdf... direct (0.1s)
[1193/3287] JSE-Bond-Indices-August-3-2026.pdf... direct (0.1s)
[1194/3287] JSE-Bond-Indices-August-4-2025.pdf... direct (0.1s)
[1195/3287] JSE-Bond-Indices-August-4-2026.pdf... direct (0.2s)
[1196/3287] JSE-Bond-Indices-August-5-2025.pdf... direct (0.1s)
[1197/3287] JSE-Bond-Indices-August-5-2026.pdf... direct (0.1s)
[1198/3287] JSE-Bond-Indices-August-7-2025.pdf... direct (0.1s)
[1199/3287] JSE-Bond-Indices-August-7-2026.pdf... direct (0.1s)
[1200/3287] JSE-Bond-Indices-August-8-2025.pdf... direct (0.1s)
  -- checkpoint saved (1200 jse records so far)
[1201/3287] JSE-Bond-Indices-Dec-02-2024.pdf... direct (0.1s)
[1202/3287] JSE-Bond-Indices-Dec-03-2024.pdf... direct (0.1s)
[1203/3287] JSE-Bond-Indices-Dec-04-2024-1.pdf... direct (0.1s)
[1204/3287] JSE-Bond-Indices-Dec-05-2024.pdf... direct (0.1s)
[1205/3287] JSE-Bond-Indices-Dec-06-2024.pdf... direct (0.1s)
[1206/3287] JSE-Bond-Indices-Dec-09-2024.pdf... direct (0.2s)
[1207/3287] JSE-Bond-Indices-Dec-10-2024.pdf... direct (0.1s)
[1208/3287] JSE-Bond-Indices-Dec-11-2024.pdf... direct (0.1s)
[1209/3287] JSE-Bond-Indices-Dec-12-2024.pdf... direct (0.1s)
[1210/3287] JSE-Bond-Indices-Dec-13-2024.pdf... direct (0.1s)
  -- checkpoint saved (1210 jse records so far)
[1211/3287] JSE-Bond-Indices-Dec-16-2024.pdf... direct (0.1s)
[1212/3287] JSE-Bond-Indices-Dec-17-2024.pdf... direct (0.1s)
[1213/3287] JSE-Bond-Indices-Dec-18-2024.pdf... direct (0.1s)
[1214/3287] JSE-Bond-Indices-Dec-19-2024.pdf... direct (0.1s)
[1215/3287] JSE-Bond-Indices-Dec-20-2024.pdf... direct (0.1s)
[1216/3287] JSE-Bond-Indices-Dec-23-2024.pdf... direct (0.2s)
[1217/3287] JSE-Bond-Indices-Dec-24-2024.pdf... direct (0.1s)
[1218/3287] JSE-Bond-Indices-Dec-27-2024.pdf... direct (0.1s)
[1219/3287] JSE-Bond-Indices-Dec-30-2024.pdf... direct (0.1s)
[1220/3287] JSE-Bond-Indices-Dec-31-2024.pdf... direct (0.1s)
  -- checkpoint saved (1220 jse records so far)
[1221/3287] JSE-Bond-Indices-December-1-2025.pdf... direct (0.1s)
[1222/3287] JSE-Bond-Indices-December-10-2025.pdf... direct (0.1s)
[1223/3287] JSE-Bond-Indices-December-11-2025.pdf... direct (0.1s)
[1224/3287] JSE-Bond-Indices-December-12-2025.pdf... direct (0.1s)
[1225/3287] JSE-Bond-Indices-December-15-2025.pdf... direct (0.1s)
[1226/3287] JSE-Bond-Indices-December-16-2025.pdf... direct (0.1s)
[1227/3287] JSE-Bond-Indices-December-17-2025.pdf... direct (0.2s)
[1228/3287] JSE-Bond-Indices-December-18-2025.pdf... direct (0.1s)
[1229/3287] JSE-Bond-Indices-December-19-2025.pdf... direct (0.1s)
[1230/3287] JSE-Bond-Indices-December-2-2025.pdf... direct (0.1s)
  -- checkpoint saved (1230 jse records so far)
[1231/3287] JSE-Bond-Indices-December-22-2025.pdf... direct (0.1s)
[1232/3287] JSE-Bond-Indices-December-23-2025.pdf... direct (0.1s)
[1233/3287] JSE-Bond-Indices-December-24-2025.pdf... direct (0.1s)
[1234/3287] JSE-Bond-Indices-December-29-2025-1.pdf... direct (0.1s)
[1235/3287] JSE-Bond-Indices-December-3-2025.pdf... direct (0.1s)
[1236/3287] JSE-Bond-Indices-December-30-2025.pdf... direct (0.1s)
[1237/3287] JSE-Bond-Indices-December-312025.pdf... direct (0.1s)
[1238/3287] JSE-Bond-Indices-December-4-2025.pdf... direct (0.2s)
[1239/3287] JSE-Bond-Indices-December-5-2025.pdf... direct (0.1s)
[1240/3287] JSE-Bond-Indices-December-8-2025.pdf... direct (0.1s)
  -- checkpoint saved (1240 jse records so far)
[1241/3287] JSE-Bond-Indices-December-9-2025.pdf... direct (0.1s)
[1242/3287] JSE-Bond-Indices-Feb-10-2025.pdf... direct (0.1s)
[1243/3287] JSE-Bond-Indices-Feb-11-2025.pdf... direct (0.1s)
[1244/3287] JSE-Bond-Indices-Feb-12-2025.pdf... direct (0.1s)
[1245/3287] JSE-Bond-Indices-Feb-13-2025.pdf... direct (0.1s)
[1246/3287] JSE-Bond-Indices-Feb-14-2025.pdf... direct (0.1s)
[1247/3287] JSE-Bond-Indices-Feb-17-2025-1.pdf... direct (0.1s)
[1248/3287] JSE-Bond-Indices-Feb-18-2025.pdf... direct (0.1s)
[1249/3287] JSE-Bond-Indices-Feb-19-2025.pdf... direct (0.2s)
[1250/3287] JSE-Bond-Indices-Feb-20-2025.pdf... direct (0.1s)
  -- checkpoint saved (1250 jse records so far)
[1251/3287] JSE-Bond-Indices-Feb-21-2025.pdf... direct (0.1s)
[1252/3287] JSE-Bond-Indices-Feb-24-2025.pdf... direct (0.1s)
[1253/3287] JSE-Bond-Indices-Feb-25-2025.pdf... direct (0.1s)
[1254/3287] JSE-Bond-Indices-Feb-26-2025.pdf... direct (0.1s)
[1255/3287] JSE-Bond-Indices-Feb-27-2025.pdf... direct (0.1s)
[1256/3287] JSE-Bond-Indices-Feb-28-2025.pdf... direct (0.1s)
[1257/3287] JSE-Bond-Indices-Feb-3-2025.pdf... direct (0.1s)
[1258/3287] JSE-Bond-Indices-Feb-4-2025.pdf... direct (0.1s)
[1259/3287] JSE-Bond-Indices-Feb-5-2025.pdf... direct (0.2s)
[1260/3287] JSE-Bond-Indices-Feb-6-2025.pdf... direct (0.1s)
  -- checkpoint saved (1260 jse records so far)
[1261/3287] JSE-Bond-Indices-Feb-7-2025.pdf... direct (0.1s)
[1262/3287] JSE-Bond-Indices-February-102026.pdf... direct (0.1s)
[1263/3287] JSE-Bond-Indices-February-11-2026.pdf... direct (0.1s)
[1264/3287] JSE-Bond-Indices-February-12-2026.pdf... direct (0.1s)
[1265/3287] JSE-Bond-Indices-February-13-2026.pdf... direct (0.1s)
[1266/3287] JSE-Bond-Indices-February-16-2026.pdf... direct (0.1s)
[1267/3287] JSE-Bond-Indices-February-17-2026.pdf... direct (0.1s)
[1268/3287] JSE-Bond-Indices-February-19-2026.pdf... direct (0.1s)
[1269/3287] JSE-Bond-Indices-February-2-2026.pdf... direct (0.1s)
[1270/3287] JSE-Bond-Indices-February-20-2026.pdf... direct (0.2s)

  -- checkpoint saved (1270 jse records so far)
[1271/3287] JSE-Bond-Indices-February-23-2026-2.pdf... direct (0.1s)
[1272/3287] JSE-Bond-Indices-February-24-2026-1.pdf... direct (0.1s)
[1273/3287] JSE-Bond-Indices-February-25-2026.pdf... direct (0.1s)
[1274/3287] JSE-Bond-Indices-February-26-2026.pdf... direct (0.1s)
[1275/3287] JSE-Bond-Indices-February-3-2026.pdf... direct (0.1s)
[1276/3287] JSE-Bond-Indices-February-4-2026-1.pdf... direct (0.1s)
[1277/3287] JSE-Bond-Indices-February-5-2026.pdf... direct (0.1s)
[1278/3287] JSE-Bond-Indices-February-6-2026.pdf... direct (0.1s)
[1279/3287] JSE-Bond-Indices-February-9-2026.pdf... direct (0.1s)
[1280/3287] JSE-Bond-Indices-Jan-02-2025.pdf... direct (0.1s)
  -- checkpoint saved (1280 jse records so far)
[1281/3287] JSE-Bond-Indices-Jan-03-2025.pdf... direct (0.2s)
[1282/3287] JSE-Bond-Indices-Jan-06-2025.pdf... direct (0.1s)
[1283/3287] JSE-Bond-Indices-Jan-07-2025.pdf... direct (0.1s)
[1284/3287] JSE-Bond-Indices-Jan-08-2025.pdf... direct (0.1s)
[1285/3287] JSE-Bond-Indices-Jan-09-2025.pdf... direct (0.1s)
[1286/3287] JSE-Bond-Indices-Jan-10-2025.pdf... direct (0.1s)
[1287/3287] JSE-Bond-Indices-Jan-13-2025.pdf... direct (0.1s)
[1288/3287] JSE-Bond-Indices-Jan-14-2025.pdf... direct (0.1s)
[1289/3287] JSE-Bond-Indices-Jan-15-2025.pdf... direct (0.1s)
[1290/3287] JSE-Bond-Indices-Jan-16-2025.pdf... direct (0.1s)
  -- checkpoint saved (1290 jse records so far)
[1291/3287] JSE-Bond-Indices-Jan-17-2025.pdf... direct (0.2s)
[1292/3287] JSE-Bond-Indices-Jan-20-2025.pdf... direct (0.1s)
[1293/3287] JSE-Bond-Indices-Jan-21-2025.pdf... direct (0.1s)
[1294/3287] JSE-Bond-Indices-Jan-22-2025.pdf... direct (0.1s)
[1295/3287] JSE-Bond-Indices-Jan-23-2025.pdf... direct (0.1s)
[1296/3287] JSE-Bond-Indices-Jan-24-2025.pdf... direct (0.1s)
[1297/3287] JSE-Bond-Indices-Jan-27-2025-2.pdf... direct (0.1s)
[1298/3287] JSE-Bond-Indices-Jan-28-2025-1.pdf... direct (0.1s)
[1299/3287] JSE-Bond-Indices-Jan-29-2025.pdf... direct (0.1s)
[1300/3287] JSE-Bond-Indices-Jan-30-2025.pdf... direct (0.1s)
  -- checkpoint saved (1300 jse records so far)
[1301/3287] JSE-Bond-Indices-Jan-31-2025.pdf... direct (0.1s)
[1302/3287] JSE-Bond-Indices-January-12-2026.pdf... direct (0.2s)
[1303/3287] JSE-Bond-Indices-January-13-2026.pdf... direct (0.1s)
[1304/3287] JSE-Bond-Indices-January-14-2026.pdf... direct (0.1s)
[1305/3287] JSE-Bond-Indices-January-15-2026.pdf... direct (0.1s)
[1306/3287] JSE-Bond-Indices-January-16-2026.pdf... direct (0.1s)
[1307/3287] JSE-Bond-Indices-January-19-2026.pdf... direct (0.1s)
[1308/3287] JSE-Bond-Indices-January-2-2026.pdf... direct (0.1s)
[1309/3287] JSE-Bond-Indices-January-20-2026.pdf... direct (0.1s)
[1310/3287] JSE-Bond-Indices-January-21-2026.pdf... direct (0.1s)
  -- checkpoint saved (1310 jse records so far)
[1311/3287] JSE-Bond-Indices-January-22-2026.pdf... direct (0.1s)
[1312/3287] JSE-Bond-Indices-January-23-2026.pdf... direct (0.1s)
[1313/3287] JSE-Bond-Indices-January-26-2026.pdf... direct (0.2s)
[1314/3287] JSE-Bond-Indices-January-27-2026.pdf... direct (0.1s)
[1315/3287] JSE-Bond-Indices-January-28-2026.pdf... direct (0.1s)
[1316/3287] JSE-Bond-Indices-January-29-2026.pdf... direct (0.1s)
[1317/3287] JSE-Bond-Indices-January-30-2026.pdf... direct (0.1s)
[1318/3287] JSE-Bond-Indices-January-5-2026.pdf... direct (0.1s)
[1319/3287] JSE-Bond-Indices-January-6-2026.pdf... direct (0.1s)
[1320/3287] JSE-Bond-Indices-January-7-2026.pdf... direct (0.1s)
  -- checkpoint saved (1320 jse records so far)
[1321/3287] JSE-Bond-Indices-January-8-2026.pdf... direct (0.1s)
[1322/3287] JSE-Bond-Indices-January-9-2026.pdf... direct (0.1s)
[1323/3287] JSE-Bond-Indices-July-1-2025.pdf... direct (0.1s)
[1324/3287] JSE-Bond-Indices-July-1-2026.pdf... direct (0.2s)
[1325/3287] JSE-Bond-Indices-July-10-2025.pdf... direct (0.1s)
[1326/3287] JSE-Bond-Indices-July-11-2025.pdf... direct (0.1s)
[1327/3287] JSE-Bond-Indices-July-13-2026.pdf... direct (0.1s)
[1328/3287] JSE-Bond-Indices-July-14-2025.pdf... direct (0.1s)
[1329/3287] JSE-Bond-Indices-July-14-2026.pdf... direct (0.1s)
[1330/3287] JSE-Bond-Indices-July-15-2026.pdf... direct (0.1s)
  -- checkpoint saved (1330 jse records so far)
[1331/3287] JSE-Bond-Indices-July-16-2025.pdf... direct (0.1s)
[1332/3287] JSE-Bond-Indices-July-16-2026.pdf... direct (0.1s)
[1333/3287] JSE-Bond-Indices-July-17-2025.pdf... direct (0.1s)
[1334/3287] JSE-Bond-Indices-July-17-2026.pdf... direct (0.1s)
[1335/3287] JSE-Bond-Indices-July-18-2025.pdf... direct (0.2s)
[1336/3287] JSE-Bond-Indices-July-2-2025.pdf... direct (0.1s)
[1337/3287] JSE-Bond-Indices-July-2-2026.pdf... direct (0.1s)
[1338/3287] JSE-Bond-Indices-July-20-2026.pdf... direct (0.1s)
[1339/3287] JSE-Bond-Indices-July-21-2025.pdf... direct (0.1s)
[1340/3287] JSE-Bond-Indices-July-21-2026.pdf... direct (0.1s)
  -- checkpoint saved (1340 jse records so far)
[1341/3287] JSE-Bond-Indices-July-22-2025.pdf... direct (0.1s)
[1342/3287] JSE-Bond-Indices-July-22-2026.pdf... direct (0.1s)
[1343/3287] JSE-Bond-Indices-July-23-2025.pdf... direct (0.1s)
[1344/3287] JSE-Bond-Indices-July-23-2026.pdf... direct (0.1s)
[1345/3287] JSE-Bond-Indices-July-24-2025.pdf... direct (0.2s)
[1346/3287] JSE-Bond-Indices-July-24-2026.pdf... direct (0.1s)
[1347/3287] JSE-Bond-Indices-July-25-2025.pdf... direct (0.1s)
[1348/3287] JSE-Bond-Indices-July-272026.pdf... direct (0.1s)
[1349/3287] JSE-Bond-Indices-July-28-2025.pdf... direct (0.1s)
[1350/3287] JSE-Bond-Indices-July-282026.pdf... direct (0.1s)
  -- checkpoint saved (1350 jse records so far)
[1351/3287] JSE-Bond-Indices-July-29-2025.pdf... direct (0.1s)
[1352/3287] JSE-Bond-Indices-July-292026.pdf... direct (0.1s)
[1353/3287] JSE-Bond-Indices-July-3-2025.pdf... direct (0.1s)
[1354/3287] JSE-Bond-Indices-July-3-2026.pdf... direct (0.1s)
[1355/3287] JSE-Bond-Indices-July-30-2025.pdf... direct (0.1s)
[1356/3287] JSE-Bond-Indices-July-302026.pdf... direct (0.2s)
[1357/3287] JSE-Bond-Indices-July-31-2025.pdf... direct (0.1s)
[1358/3287] JSE-Bond-Indices-July-312026.pdf... direct (0.1s)
[1359/3287] JSE-Bond-Indices-July-4-2025.pdf... direct (0.1s)
[1360/3287] JSE-Bond-Indices-July-6-2026.pdf... direct (0.1s)
  -- checkpoint saved (1360 jse records so far)
[1361/3287] JSE-Bond-Indices-July-7-2025-1.pdf... direct (0.1s)
[1362/3287] JSE-Bond-Indices-July-7-2026.pdf... direct (0.1s)
[1363/3287] JSE-Bond-Indices-July-8-2025.pdf... direct (0.1s)
[1364/3287] JSE-Bond-Indices-July-8-2026.pdf... direct (0.1s)
[1365/3287] JSE-Bond-Indices-July-9-2025.pdf... direct (0.1s)
[1366/3287] JSE-Bond-Indices-July-9-2026.pdf... direct (0.1s)
[1367/3287] JSE-Bond-Indices-July10-2026.pdf... direct (0.2s)
[1368/3287] JSE-Bond-Indices-June-1-2026.pdf... direct (0.1s)
[1369/3287] JSE-Bond-Indices-June-10-2025.pdf... direct (0.1s)
[1370/3287] JSE-Bond-Indices-June-10-2026.pdf... direct (0.1s)
  -- checkpoint saved (1370 jse records so far)
[1371/3287] JSE-Bond-Indices-June-11-2025.pdf... direct (0.1s)
[1372/3287] JSE-Bond-Indices-June-11-2026.pdf... direct (0.1s)
[1373/3287] JSE-Bond-Indices-June-12-2025.pdf... direct (0.1s)
[1374/3287] JSE-Bond-Indices-June-12-2026.pdf... direct (0.1s)
[1375/3287] JSE-Bond-Indices-June-13-2025.pdf... direct (0.1s)
[1376/3287] JSE-Bond-Indices-June-15-2026.pdf... direct (0.1s)
[1377/3287] JSE-Bond-Indices-June-16-2025.pdf... direct (0.1s)
[1378/3287] JSE-Bond-Indices-June-16-2026.pdf... direct (0.2s)
[1379/3287] JSE-Bond-Indices-June-17-2025-1.pdf... direct (0.1s)
[1380/3287] JSE-Bond-Indices-June-17-2026.pdf... direct (0.1s)
  -- checkpoint saved (1380 jse records so far)
[1381/3287] JSE-Bond-Indices-June-18-2025.pdf... direct (0.1s)
[1382/3287] JSE-Bond-Indices-June-18-2026.pdf... direct (0.1s)
[1383/3287] JSE-Bond-Indices-June-19-2025.pdf... direct (0.1s)
[1384/3287] JSE-Bond-Indices-June-19-2026.pdf... direct (0.1s)
[1385/3287] JSE-Bond-Indices-June-2-2025.pdf... direct (0.1s)
[1386/3287] JSE-Bond-Indices-June-2-2026.pdf... direct (0.1s)
[1387/3287] JSE-Bond-Indices-June-20-2025.pdf... direct (0.1s)
[1388/3287] JSE-Bond-Indices-June-22-2026.pdf... direct (0.2s)
[1389/3287] JSE-Bond-Indices-June-23-2025.pdf... direct (0.1s)
[1390/3287] JSE-Bond-Indices-June-23-2026.pdf... direct (0.1s)

  -- checkpoint saved (1390 jse records so far)
[1391/3287] JSE-Bond-Indices-June-24-2025.pdf... direct (0.1s)
[1392/3287] JSE-Bond-Indices-June-24-2026.pdf... direct (0.1s)
[1393/3287] JSE-Bond-Indices-June-25-2025.pdf... direct (0.1s)
[1394/3287] JSE-Bond-Indices-June-25-2026.pdf... direct (0.1s)
[1395/3287] JSE-Bond-Indices-June-26-2025.pdf... direct (0.1s)
[1396/3287] JSE-Bond-Indices-June-26-2026.pdf... direct (0.1s)
[1397/3287] JSE-Bond-Indices-June-27-2025.pdf... direct (0.1s)
[1398/3287] JSE-Bond-Indices-June-29-2026-1.pdf... direct (0.1s)
[1399/3287] JSE-Bond-Indices-June-3-2025.pdf... direct (0.2s)
[1400/3287] JSE-Bond-Indices-June-3-2026.pdf... direct (0.1s)
  -- checkpoint saved (1400 jse records so far)
[1401/3287] JSE-Bond-Indices-June-30-2025.pdf... direct (0.1s)
[1402/3287] JSE-Bond-Indices-June-30-2026.pdf... direct (0.1s)
[1403/3287] JSE-Bond-Indices-June-4-2025.pdf... direct (0.1s)
[1404/3287] JSE-Bond-Indices-June-4-2026-1.pdf... direct (0.1s)
[1405/3287] JSE-Bond-Indices-June-5-2025.pdf... direct (0.1s)
[1406/3287] JSE-Bond-Indices-June-5-2026.pdf... direct (0.1s)
[1407/3287] JSE-Bond-Indices-June-6-2025.pdf... direct (0.1s)
[1408/3287] JSE-Bond-Indices-June-8-2026.pdf... direct (0.1s)
[1409/3287] JSE-Bond-Indices-June-9-2025.pdf... direct (0.1s)
[1410/3287] JSE-Bond-Indices-June-9-2026.pdf... direct (0.2s)
  -- checkpoint saved (1410 jse records so far)
[1411/3287] JSE-Bond-Indices-Mar-10-2025.pdf... direct (0.1s)
[1412/3287] JSE-Bond-Indices-Mar-11-2025.pdf... direct (0.1s)
[1413/3287] JSE-Bond-Indices-Mar-12-2025.pdf... direct (0.1s)
[1414/3287] JSE-Bond-Indices-Mar-13-2025.pdf... direct (0.1s)
[1415/3287] JSE-Bond-Indices-Mar-14-2025.pdf... direct (0.1s)
[1416/3287] JSE-Bond-Indices-Mar-17-2025-1.pdf... direct (0.1s)
[1417/3287] JSE-Bond-Indices-Mar-18-2025.pdf... direct (0.1s)
[1418/3287] JSE-Bond-Indices-Mar-19-2025.pdf... direct (0.1s)
[1419/3287] JSE-Bond-Indices-Mar-20-2025.pdf... direct (0.1s)
[1420/3287] JSE-Bond-Indices-Mar-21-2025.pdf... direct (0.2s)
  -- checkpoint saved (1420 jse records so far)
[1421/3287] JSE-Bond-Indices-Mar-24-2025-1-1.pdf... direct (0.1s)
[1422/3287] JSE-Bond-Indices-Mar-25-2025.pdf... direct (0.1s)
[1423/3287] JSE-Bond-Indices-Mar-26-2025.pdf... direct (0.1s)
[1424/3287] JSE-Bond-Indices-Mar-27-2025-1.pdf... direct (0.1s)
[1425/3287] JSE-Bond-Indices-Mar-28-2025.pdf... direct (0.1s)
[1426/3287] JSE-Bond-Indices-Mar-3-2025.pdf... direct (0.1s)
[1427/3287] JSE-Bond-Indices-Mar-31-2025.pdf... direct (0.1s)
[1428/3287] JSE-Bond-Indices-Mar-4-2025.pdf... direct (0.1s)
[1429/3287] JSE-Bond-Indices-Mar-6-2025.pdf... direct (0.1s)
[1430/3287] JSE-Bond-Indices-Mar-7-2025.pdf... direct (0.1s)
  -- checkpoint saved (1430 jse records so far)
[1431/3287] JSE-Bond-Indices-March-10-2026.pdf... direct (0.2s)
[1432/3287] JSE-Bond-Indices-March-11-2026.pdf... direct (0.1s)
[1433/3287] JSE-Bond-Indices-March-12-2026.pdf... direct (0.1s)
[1434/3287] JSE-Bond-Indices-March-13-2026.pdf... direct (0.1s)
[1435/3287] JSE-Bond-Indices-March-16-2026.pdf... direct (0.1s)
[1436/3287] JSE-Bond-Indices-March-17-2026.pdf... direct (0.1s)
[1437/3287] JSE-Bond-Indices-March-18-2026.pdf... direct (0.1s)
[1438/3287] JSE-Bond-Indices-March-19-2026.pdf... direct (0.1s)
[1439/3287] JSE-Bond-Indices-March-2-2026.pdf... direct (0.1s)
[1440/3287] JSE-Bond-Indices-March-20-2026.pdf... direct (0.1s)
  -- checkpoint saved (1440 jse records so far)
[1441/3287] JSE-Bond-Indices-March-23-2026.pdf... direct (0.1s)
[1442/3287] JSE-Bond-Indices-March-24-2026.pdf... direct (0.2s)
[1443/3287] JSE-Bond-Indices-March-25-2026.pdf... direct (0.1s)
[1444/3287] JSE-Bond-Indices-March-26-2026.pdf... direct (0.1s)
[1445/3287] JSE-Bond-Indices-March-27-2026.pdf... direct (0.1s)
[1446/3287] JSE-Bond-Indices-March-3-2026.pdf... direct (0.1s)
[1447/3287] JSE-Bond-Indices-March-30-2026.pdf... direct (0.1s)
[1448/3287] JSE-Bond-Indices-March-31-2026.pdf... direct (0.1s)
[1449/3287] JSE-Bond-Indices-March-4-2026.pdf... direct (0.1s)
[1450/3287] JSE-Bond-Indices-March-5-2026.pdf... direct (0.1s)
  -- checkpoint saved (1450 jse records so far)
[1451/3287] JSE-Bond-Indices-March-6-2026.pdf... direct (0.1s)
[1452/3287] JSE-Bond-Indices-March-9-2026.pdf... direct (0.2s)
[1453/3287] JSE-Bond-Indices-May-1-2025-1.pdf... direct (0.1s)
[1454/3287] JSE-Bond-Indices-May-1-2026.pdf... direct (0.1s)
[1455/3287] JSE-Bond-Indices-May-11-2026.pdf... direct (0.1s)
[1456/3287] JSE-Bond-Indices-May-12-2025.pdf... direct (0.1s)
[1457/3287] JSE-Bond-Indices-May-12-2026.pdf... direct (0.1s)
[1458/3287] JSE-Bond-Indices-May-13-2025.pdf... direct (0.1s)
[1459/3287] JSE-Bond-Indices-May-13-2026.pdf... direct (0.1s)
[1460/3287] JSE-Bond-Indices-May-14-2025.pdf... direct (0.1s)
  -- checkpoint saved (1460 jse records so far)
[1461/3287] JSE-Bond-Indices-May-14-2026.pdf... direct (0.1s)
[1462/3287] JSE-Bond-Indices-May-15-2025.pdf... direct (0.1s)
[1463/3287] JSE-Bond-Indices-May-15-2026.pdf... direct (0.2s)
[1464/3287] JSE-Bond-Indices-May-16-2025.pdf... direct (0.1s)
[1465/3287] JSE-Bond-Indices-May-18-2026.pdf... direct (0.1s)
[1466/3287] JSE-Bond-Indices-May-19-2025-1.pdf... direct (0.1s)
[1467/3287] JSE-Bond-Indices-May-19-2026.pdf... direct (0.1s)
[1468/3287] JSE-Bond-Indices-May-2-2025.pdf... direct (0.1s)
[1469/3287] JSE-Bond-Indices-May-20-2025.pdf... direct (0.1s)
[1470/3287] JSE-Bond-Indices-May-20-2026.pdf... direct (0.1s)
  -- checkpoint saved (1470 jse records so far)
[1471/3287] JSE-Bond-Indices-May-21-2025.pdf... direct (0.1s)
[1472/3287] JSE-Bond-Indices-May-21-2026.pdf... direct (0.1s)
[1473/3287] JSE-Bond-Indices-May-22-2025.pdf... direct (0.1s)
[1474/3287] JSE-Bond-Indices-May-22-2026-1.pdf... direct (0.2s)
[1475/3287] JSE-Bond-Indices-May-26-2025.pdf... direct (0.1s)
[1476/3287] JSE-Bond-Indices-May-26-2026.pdf... direct (0.1s)
[1477/3287] JSE-Bond-Indices-May-27-2025.pdf... direct (0.1s)
[1478/3287] JSE-Bond-Indices-May-27-2026.pdf... direct (0.1s)
[1479/3287] JSE-Bond-Indices-May-28-2025.pdf... direct (0.1s)
[1480/3287] JSE-Bond-Indices-May-28-2026.pdf... direct (0.1s)
  -- checkpoint saved (1480 jse records so far)
[1481/3287] JSE-Bond-Indices-May-29-2025.pdf... direct (0.1s)
[1482/3287] JSE-Bond-Indices-May-29-2026.pdf... direct (0.1s)
[1483/3287] JSE-Bond-Indices-May-30-2025.pdf... direct (0.1s)
[1484/3287] JSE-Bond-Indices-May-4-2026.pdf... direct (0.1s)
[1485/3287] JSE-Bond-Indices-May-5-2025.pdf... direct (0.2s)
[1486/3287] JSE-Bond-Indices-May-5-2026.pdf... direct (0.1s)
[1487/3287] JSE-Bond-Indices-May-6-2025.pdf... direct (0.1s)
[1488/3287] JSE-Bond-Indices-May-6-2026.pdf... direct (0.1s)
[1489/3287] JSE-Bond-Indices-May-7-2025.pdf... direct (0.1s)
[1490/3287] JSE-Bond-Indices-May-7-2026.pdf... direct (0.1s)
  -- checkpoint saved (1490 jse records so far)
[1491/3287] JSE-Bond-Indices-May-8-2025.pdf... direct (0.1s)
[1492/3287] JSE-Bond-Indices-May-8-2026.pdf... direct (0.1s)
[1493/3287] JSE-Bond-Indices-May-9-2025.pdf... direct (0.1s)
[1494/3287] JSE-Bond-Indices-Nov-1-2024.pdf... direct (0.1s)
[1495/3287] JSE-Bond-Indices-Nov-11-2024-1.pdf... direct (0.2s)
[1496/3287] JSE-Bond-Indices-Nov-12-2024.pdf... direct (0.1s)
[1497/3287] JSE-Bond-Indices-Nov-13-2024.pdf... direct (0.1s)
[1498/3287] JSE-Bond-Indices-Nov-14-2024.pdf... direct (0.1s)
[1499/3287] JSE-Bond-Indices-Nov-15-2024.pdf... direct (0.1s)
[1500/3287] JSE-Bond-Indices-Nov-18-2024.pdf... direct (0.1s)
  -- checkpoint saved (1500 jse records so far)
[1501/3287] JSE-Bond-Indices-Nov-19-2024.pdf... direct (0.1s)
[1502/3287] JSE-Bond-Indices-Nov-20-2024.pdf... direct (0.1s)
[1503/3287] JSE-Bond-Indices-Nov-21-2024.pdf... direct (0.1s)
[1504/3287] JSE-Bond-Indices-Nov-22-2024.pdf... direct (0.1s)
[1505/3287] JSE-Bond-Indices-Nov-25-2024.pdf... direct (0.1s)
[1506/3287] JSE-Bond-Indices-Nov-26-2024.pdf... direct (0.2s)
[1507/3287] JSE-Bond-Indices-Nov-27-2024.pdf... direct (0.1s)
[1508/3287] JSE-Bond-Indices-Nov-28-2024.pdf... direct (0.1s)
[1509/3287] JSE-Bond-Indices-Nov-29-2024.pdf... direct (0.1s)
[1510/3287] JSE-Bond-Indices-Nov-4-2024.pdf... direct (0.1s)
  -- checkpoint saved (1510 jse records so far)
[1511/3287] JSE-Bond-Indices-Nov-5-2024.pdf... direct (0.1s)
[1512/3287] JSE-Bond-Indices-Nov-6-2024.pdf... direct (0.1s)
[1513/3287] JSE-Bond-Indices-Nov-7-2024.pdf... direct (0.1s)
[1514/3287] JSE-Bond-Indices-Nov-8-2024.pdf... direct (0.1s)
[1515/3287] JSE-Bond-Indices-November-10-2025.pdf... direct (0.1s)
[1516/3287] JSE-Bond-Indices-November-11-2025.pdf... direct (0.2s)
[1517/3287] JSE-Bond-Indices-November-12-2025.pdf... direct (0.1s)
[1518/3287] JSE-Bond-Indices-November-13-2025.pdf... direct (0.1s)
[1519/3287] JSE-Bond-Indices-November-14-2025.pdf... direct (0.1s)
[1520/3287] JSE-Bond-Indices-November-17-2025.pdf... direct (0.1s)
  -- checkpoint saved (1520 jse records so far)
[1521/3287] JSE-Bond-Indices-November-18-2025.pdf... direct (0.1s)
[1522/3287] JSE-Bond-Indices-November-19-2025-1.pdf... direct (0.1s)
[1523/3287] JSE-Bond-Indices-November-20-2025.pdf... direct (0.1s)
[1524/3287] JSE-Bond-Indices-November-21-2025.pdf... direct (0.1s)
[1525/3287] JSE-Bond-Indices-November-24-2025.pdf... direct (0.1s)
[1526/3287] JSE-Bond-Indices-November-25-2025.pdf... direct (0.1s)
[1527/3287] JSE-Bond-Indices-November-26-2025.pdf... direct (0.2s)
[1528/3287] JSE-Bond-Indices-November-27-2025.pdf... direct (0.1s)
[1529/3287] JSE-Bond-Indices-November-28-2025.pdf... direct (0.1s)
[1530/3287] JSE-Bond-Indices-November-3-2025.pdf... direct (0.1s)
  -- checkpoint saved (1530 jse records so far)
[1531/3287] JSE-Bond-Indices-November-4-2025.pdf... direct (0.1s)
[1532/3287] JSE-Bond-Indices-November-5-2025.pdf... direct (0.1s)
[1533/3287] JSE-Bond-Indices-November-6-2025-1.pdf... direct (0.1s)
[1534/3287] JSE-Bond-Indices-November-7-2025.pdf... direct (0.1s)
[1535/3287] JSE-Bond-Indices-Oct-1-2024.pdf... direct (0.1s)
[1536/3287] JSE-Bond-Indices-Oct-10-2024.pdf... direct (0.1s)
[1537/3287] JSE-Bond-Indices-Oct-11-2024.pdf... direct (0.1s)
[1538/3287] JSE-Bond-Indices-Oct-14-2024.pdf... direct (0.2s)
[1539/3287] JSE-Bond-Indices-Oct-15-2024.pdf... direct (0.1s)
[1540/3287] JSE-Bond-Indices-Oct-16-2024.pdf... direct (0.1s)
  -- checkpoint saved (1540 jse records so far)
[1541/3287] JSE-Bond-Indices-Oct-17-2024.pdf... direct (0.1s)
[1542/3287] JSE-Bond-Indices-Oct-18-2024.pdf... direct (0.1s)
[1543/3287] JSE-Bond-Indices-Oct-2-2024.pdf... direct (0.1s)
[1544/3287] JSE-Bond-Indices-Oct-23-2024.pdf... direct (0.1s)
[1545/3287] JSE-Bond-Indices-Oct-24-2024.pdf... direct (0.1s)
[1546/3287] JSE-Bond-Indices-Oct-25-2024.pdf... direct (0.1s)
[1547/3287] JSE-Bond-Indices-Oct-28-2024.pdf... direct (0.1s)
[1548/3287] JSE-Bond-Indices-Oct-29-2024.pdf... direct (0.2s)
[1549/3287] JSE-Bond-Indices-Oct-3-2024.pdf... direct (0.1s)
[1550/3287] JSE-Bond-Indices-Oct-31-2024-1.pdf... direct (0.1s)
  -- checkpoint saved (1550 jse records so far)
[1551/3287] JSE-Bond-Indices-Oct-4-2024.pdf... direct (0.1s)
[1552/3287] JSE-Bond-Indices-Oct-7-2024.pdf... direct (0.1s)
[1553/3287] JSE-Bond-Indices-Oct-8-2024.pdf... direct (0.1s)
[1554/3287] JSE-Bond-Indices-Oct-9-2024.pdf... direct (0.1s)
[1555/3287] JSE-Bond-Indices-October-1-2025.pdf... direct (0.1s)
[1556/3287] JSE-Bond-Indices-October-102025.pdf... direct (0.1s)
[1557/3287] JSE-Bond-Indices-October-13-2025.pdf... direct (0.1s)
[1558/3287] JSE-Bond-Indices-October-14-2025.pdf... direct (0.2s)
[1559/3287] JSE-Bond-Indices-October-15-2025.pdf... direct (0.1s)
[1560/3287] JSE-Bond-Indices-October-16-2025.pdf... direct (0.1s)
  -- checkpoint saved (1560 jse records so far)
[1561/3287] JSE-Bond-Indices-October-17-2025.pdf... direct (0.1s)
[1562/3287] JSE-Bond-Indices-October-2-2025.pdf... direct (0.1s)
[1563/3287] JSE-Bond-Indices-October-21-2025.pdf... direct (0.1s)
[1564/3287] JSE-Bond-Indices-October-222025.pdf... direct (0.1s)
[1565/3287] JSE-Bond-Indices-October-232025.pdf... direct (0.1s)
[1566/3287] JSE-Bond-Indices-October-24-2025.pdf... direct (0.1s)
[1567/3287] JSE-Bond-Indices-October-3-2025.pdf... direct (0.1s)
[1568/3287] JSE-Bond-Indices-October-30-2025.pdf... direct (0.1s)
[1569/3287] JSE-Bond-Indices-October-31-2025.pdf... direct (0.2s)
[1570/3287] JSE-Bond-Indices-October-6-2025.pdf... direct (0.1s)
  -- checkpoint saved (1570 jse records so far)
[1571/3287] JSE-Bond-Indices-October-7-2025.pdf... direct (0.1s)
[1572/3287] JSE-Bond-Indices-October-8-2025.pdf... direct (0.1s)
[1573/3287] JSE-Bond-Indices-October-92025.pdf... direct (0.1s)
[1574/3287] JSE-Bond-Indices-Sept-10-2024.pdf... direct (0.1s)
[1575/3287] JSE-Bond-Indices-Sept-11-2024.pdf... direct (0.1s)
[1576/3287] JSE-Bond-Indices-Sept-12-2024.pdf... direct (0.1s)
[1577/3287] JSE-Bond-Indices-Sept-13-2024.pdf... direct (0.1s)
[1578/3287] JSE-Bond-Indices-Sept-16-2024.pdf... direct (0.1s)
[1579/3287] JSE-Bond-Indices-Sept-17-2024.pdf... direct (0.2s)
[1580/3287] JSE-Bond-Indices-Sept-18-2024-1.pdf... direct (0.1s)
  -- checkpoint saved (1580 jse records so far)
[1581/3287] JSE-Bond-Indices-Sept-19-2024.pdf... direct (0.1s)
[1582/3287] JSE-Bond-Indices-Sept-2-2024.pdf... direct (0.1s)
[1583/3287] JSE-Bond-Indices-Sept-20-2024.pdf... direct (0.1s)
[1584/3287] JSE-Bond-Indices-Sept-23-2024.pdf... direct (0.1s)
[1585/3287] JSE-Bond-Indices-Sept-24-2024-1.pdf... direct (0.1s)
[1586/3287] JSE-Bond-Indices-Sept-25-2024.pdf... direct (0.1s)
[1587/3287] JSE-Bond-Indices-Sept-26-2024.pdf... direct (0.1s)
[1588/3287] JSE-Bond-Indices-Sept-3-2024.pdf... direct (0.1s)
[1589/3287] JSE-Bond-Indices-Sept-30-2024.pdf... direct (0.2s)
[1590/3287] JSE-Bond-Indices-Sept-4-2024.pdf... direct (0.1s)
  -- checkpoint saved (1590 jse records so far)
[1591/3287] JSE-Bond-Indices-Sept-5-2024.pdf... direct (0.1s)
[1592/3287] JSE-Bond-Indices-Sept-6-2024.pdf... direct (0.1s)
[1593/3287] JSE-Bond-Indices-Sept-9-2024.pdf... direct (0.1s)
[1594/3287] JSE-Bond-Indices-September-1-2025.pdf... direct (0.1s)
[1595/3287] JSE-Bond-Indices-September-10-2025.pdf... direct (0.1s)
[1596/3287] JSE-Bond-Indices-September-11-2025.pdf... direct (0.1s)
[1597/3287] JSE-Bond-Indices-September-12-2025.pdf... direct (0.1s)
[1598/3287] JSE-Bond-Indices-September-15-2025.pdf... direct (0.1s)
[1599/3287] JSE-Bond-Indices-September-16-2025.pdf... direct (0.2s)
[1600/3287] JSE-Bond-Indices-September-17-2025.pdf... direct (0.1s)
  -- checkpoint saved (1600 jse records so far)
[1601/3287] JSE-Bond-Indices-September-18-2025.pdf... direct (0.1s)
[1602/3287] JSE-Bond-Indices-September-19-2025.pdf... direct (0.1s)
[1603/3287] JSE-Bond-Indices-September-2-2025.pdf... direct (0.1s)
[1604/3287] JSE-Bond-Indices-September-22-2025.pdf... direct (0.1s)
[1605/3287] JSE-Bond-Indices-September-23-2025.pdf... direct (0.1s)
[1606/3287] JSE-Bond-Indices-September-24-2025.pdf... direct (0.1s)
[1607/3287] JSE-Bond-Indices-September-25-2025.pdf... direct (0.1s)
[1608/3287] JSE-Bond-Indices-September-26-2025.pdf... direct (0.1s)
[1609/3287] JSE-Bond-Indices-September-29-2025.pdf... direct (0.2s)
[1610/3287] JSE-Bond-Indices-September-3-2025.pdf... direct (0.1s)
  -- checkpoint saved (1610 jse records so far)
[1611/3287] JSE-Bond-Indices-September-30-2025.pdf... direct (0.1s)
[1612/3287] JSE-Bond-Indices-September-4-2025.pdf... direct (0.1s)
[1613/3287] JSE-Bond-Indices-September-5-2025.pdf... direct (0.1s)
[1614/3287] JSE-Bond-Indices-September-8-2025.pdf... direct (0.1s)
[1615/3287] JSE-Bond-Indices-September-9-2025.pdf... direct (0.1s)
[1616/3287] JSE-Directors-Holding-as-at-December-31-2024.pdf... direct (0.3s)
[1617/3287] JSE-Dividend-Pre-advice-Q4.2024.pdf... direct (0.0s)
[1618/3287] JSE-Filing-Report-1st-Quarter-Ended-March-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[1619/3287] JSE-Filing-Report-1st-Quarter-ended-March-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[1620/3287] JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1620 jse records so far)
[1621/3287] JSE-GOJ-Bond-Trading-Platform-Launch_Remarks-by-Bank-of-Jamaica-Governor-Richard-Byles.pdf... direct (0.4s)
[1622/3287] JSE-INTERIM-REPORT-DEC-25.pdf... direct (1.4s)
[1623/3287] JSE-Intention-to-consider-dividend-Dec-20-2024.pdf... direct (0.2s)
[1624/3287] JSE-Junior-Market-IPO-Prospectus-Atlantic-Hardware-and-Plumbing-Company-Limited.pdf... direct (11.3s)
[1625/3287] JSE-Letter-MJE-Annual-Report-31-December-2024-Final.pdf... needs_ocr_elsewhere (0.0s)
[1626/3287] JSE-Letter-to-sharehoders-re-AGM.pdf... direct (0.1s)
[1627/3287] JSE-Market-Notice-New-Dividend-Date-.pdf... direct (0.0s)

[1628/3287] JSE-Market-Research-Competition-4th-QTR.-FLYER.pdf... direct (0.5s)
[1629/3287] JSE-Message-from-the-CEO.pdf... direct (0.1s)
[1630/3287] JSE-Notice-30-Jun-2026-Lissant-Mitchell.pdf... direct (0.0s)
  -- checkpoint saved (1630 jse records so far)
[1631/3287] JSE-Notice-30-June-2026-Lissant-Mitchell-Amended-.pdf... direct (0.1s)
[1632/3287] JSE-Notice-Late-Submission-of-Audited-Results.pdf... direct (0.6s)
[1633/3287] JSE-Notice-Share-repurchase-232000-units-as-at-28-August-202.pdf... direct (0.1s)
[1634/3287] JSE-Notice-of-Appointment-CAR-Board-of-Directors.pdf... direct (0.1s)
[1635/3287] JSE-Notice_May2026.pdf... direct (0.1s)
[1636/3287] JSE-RELEASE-JBG-Company-Statement-20251114.pdf... direct (0.1s)
[1637/3287] JSE-RELEASE-JBG-Notice-to-Shareholders-20251114.pdf... direct (0.0s)
[1638/3287] JSE-RELEASE.-Board-Changes.RJL_.pdf... direct (0.3s)
[1639/3287] JSE-RELEASE.-Board-Committee-Changes.RJL_.pdf... direct (0.2s)
[1640/3287] JSE-Release-Leadership-Update-May-15-26.pdf... direct (0.2s)
  -- checkpoint saved (1640 jse records so far)
[1641/3287] JSE-Release-PROVEN-Senior-Leadership-Appointments-and-Key-Strategic-Update-Oct-2024.pdf... direct (0.5s)
[1642/3287] JSE-Release_Q1.2025_Salada-Foods.pdf... direct (0.6s)
[1643/3287] JSE-Release_Q1.2026_Salada-Foods.pdf... direct (1.0s)
[1644/3287] JSE-Release_Q2.2025_Salada-Foods.pdf... direct (0.7s)
[1645/3287] JSE-Release_Q3.2025_Salada-Foods.pdf...   pdfplumber failed on JSE-Release_Q3.2025_Salada-Foods.pdf: unsupported operand type(s) for *: 'NoneType' and 'float'
direct (0.1s)
[1646/3287] JSE-Release_SALF_Q2_2026.pdf... direct (0.9s)
[1647/3287] JSE-SMG-CLIENT-USER-MANUAL.pdf... direct (1.5s)
[1648/3287] JSE-Senior-Managers-Holding-as-at-December-31-2024.pdf... direct (0.2s)
[1649/3287] JSE-Sep-2024-Unaudited-report.pdf... needs_ocr_elsewhere (0.0s)
[1650/3287] JSE-Shareholder-Report-2026-Q1.pdf... direct (1.7s)
  -- checkpoint saved (1650 jse records so far)
[1651/3287] JSE-Top-10-Shareholdings-as-at-December-31-2024.pdf... direct (0.1s)
[1652/3287] JSE-further-delay-in-filing-AFS-2025-and-Annual-Report-Final.pdf... direct (0.1s)
[1653/3287] JSE-further-delay-in-filing-AFS-2025-and-Annual-Report-June.pdf... direct (0.1s)
[1654/3287] JSE-report-April-30-2026-for-upload.pdf... direct (5.8s)
[1655/3287] JSEC-March-2026-Publication-Final-Updated-Circulated-May-29-2026.pdf... direct (1.8s)
[1656/3287] JSEG-1st-Quarter-Financials-March-2025-Signed.pdf... direct (1.8s)
[1657/3287] JSEG-2ND-Quarter-Financial-Statements-June-2025.pdf... needs_ocr_elsewhere (38.6s)
    ^ SLOW FILE -- JSEG-2ND-Quarter-Financial-Statements-June-2025.pdf took 38.6s
[1658/3287] JSEG-3rd-Quarter-Report-2024.pdf... direct (2.5s)
[1659/3287] JSEG-3rd-Quarter-Report-Signed.pdf... direct (0.6s)
[1660/3287] JSEs-First-Quarter-2026-Unaudited-Financial-Statements.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1660 jse records so far)
[1661/3287] JSEs-Monthly-Regulatory-Report-April-2025.pdf... direct (1.5s)
[1662/3287] JSEs-Monthly-Regulatory-Report-April-2026.pdf... direct (1.1s)
[1663/3287] JSEs-Monthly-Regulatory-Report-Aug-2024.pdf... direct (1.5s)
[1664/3287] JSEs-Monthly-Regulatory-Report-August-2025.pdf... direct (1.4s)
[1665/3287] JSEs-Monthly-Regulatory-Report-Dec-2024.pdf... direct (1.2s)
[1666/3287] JSEs-Monthly-Regulatory-Report-December-2025.pdf... direct (1.3s)
[1667/3287] JSEs-Monthly-Regulatory-Report-Feb.-2025.pdf... direct (1.1s)
[1668/3287] JSEs-Monthly-Regulatory-Report-February-2026.pdf... direct (1.1s)
[1669/3287] JSEs-Monthly-Regulatory-Report-Jan-2025.pdf... direct (1.0s)
[1670/3287] JSEs-Monthly-Regulatory-Report-January-2026.pdf... direct (0.8s)
  -- checkpoint saved (1670 jse records so far)
[1671/3287] JSEs-Monthly-Regulatory-Report-July-2024-2-1.pdf... direct (1.8s)
[1672/3287] JSEs-Monthly-Regulatory-Report-July-2025.pdf... direct (1.1s)
[1673/3287] JSEs-Monthly-Regulatory-Report-June-2024-3.pdf... direct (1.8s)
[1674/3287] JSEs-Monthly-Regulatory-Report-June-2025.pdf... direct (1.5s)
[1675/3287] JSEs-Monthly-Regulatory-Report-March-2025.pdf... direct (1.0s)
[1676/3287] JSEs-Monthly-Regulatory-Report-March-2026.pdf... direct (1.1s)
[1677/3287] JSEs-Monthly-Regulatory-Report-May-2024.pdf... direct (2.4s)
[1678/3287] JSEs-Monthly-Regulatory-Report-May-2025.pdf... direct (1.6s)
[1679/3287] JSEs-Monthly-Regulatory-Report-May-2026.pdf... direct (1.6s)
[1680/3287] JSEs-Monthly-Regulatory-Report-Nov-2024.pdf... direct (1.3s)
  -- checkpoint saved (1680 jse records so far)
[1681/3287] JSEs-Monthly-Regulatory-Report-November-2025.pdf... direct (1.2s)
[1682/3287] JSEs-Monthly-Regulatory-Report-Oct-2024.pdf... direct (1.3s)
[1683/3287] JSEs-Monthly-Regulatory-Report-October-2025.pdf... direct (1.0s)
[1684/3287] JSEs-Monthly-Regulatory-Report-Sept-2024-002.pdf... direct (1.3s)
[1685/3287] JSEs-Monthly-Regulatory-Report-September-2025.pdf... direct (1.2s)
[1686/3287] JSEs-Weekly-Bulletin-April-03-2026-Final.pdf... direct (0.4s)
[1687/3287] JSEs-Weekly-Bulletin-April-10-2026-Final.pdf... direct (0.4s)
[1688/3287] JSEs-Weekly-Bulletin-April-11-2025.pdf... direct (0.6s)
[1689/3287] JSEs-Weekly-Bulletin-April-17-2025.pdf... direct (0.3s)
[1690/3287] JSEs-Weekly-Bulletin-April-17-2026-Final.pdf... direct (0.5s)
  -- checkpoint saved (1690 jse records so far)
[1691/3287] JSEs-Weekly-Bulletin-April-24-2026-Final.pdf... direct (0.3s)
[1692/3287] JSEs-Weekly-Bulletin-April-25-2025.pdf... direct (0.4s)
[1693/3287] JSEs-Weekly-Bulletin-April-4-2025.pdf... direct (0.4s)
[1694/3287] JSEs-Weekly-Bulletin-August-07-2026-Final.pdf... direct (0.5s)
[1695/3287] JSEs-Weekly-Bulletin-August-15-2025.pdf... direct (0.5s)
[1696/3287] JSEs-Weekly-Bulletin-August-16-2024.pdf... direct (0.6s)
[1697/3287] JSEs-Weekly-Bulletin-August-22-2025.pdf... direct (0.4s)
[1698/3287] JSEs-Weekly-Bulletin-August-23-2024.pdf... direct (0.6s)
[1699/3287] JSEs-Weekly-Bulletin-August-29-2025.pdf... direct (0.6s)
[1700/3287] JSEs-Weekly-Bulletin-August-30-2024.pdf... direct (0.5s)
  -- checkpoint saved (1700 jse records so far)
[1701/3287] JSEs-Weekly-Bulletin-August-8-2025.pdf... direct (0.5s)
[1702/3287] JSEs-Weekly-Bulletin-December-13-2024.pdf... direct (0.5s)
[1703/3287] JSEs-Weekly-Bulletin-December-20-2024-1.pdf... direct (0.5s)
[1704/3287] JSEs-Weekly-Bulletin-December-20-2024.pdf... direct (0.4s)
[1705/3287] JSEs-Weekly-Bulletin-December-24-2025.pdf... direct (0.4s)
[1706/3287] JSEs-Weekly-Bulletin-December-27-2024.pdf... direct (0.4s)
[1707/3287] JSEs-Weekly-Bulletin-December-6-2024.pdf... direct (0.6s)
[1708/3287] JSEs-Weekly-Bulletin-February-13-2026.pdf... direct (0.5s)
[1709/3287] JSEs-Weekly-Bulletin-February-14-2025.pdf... direct (0.4s)
[1710/3287] JSEs-Weekly-Bulletin-February-20-2026.pdf... direct (0.5s)
  -- checkpoint saved (1710 jse records so far)
[1711/3287] JSEs-Weekly-Bulletin-February-21-2025.pdf... direct (0.3s)
[1712/3287] JSEs-Weekly-Bulletin-February-28-2025.pdf... direct (0.6s)
[1713/3287] JSEs-Weekly-Bulletin-February-6-2026.pdf... direct (0.6s)
[1714/3287] JSEs-Weekly-Bulletin-February-7-2025.pdf... direct (0.4s)
[1715/3287] JSEs-Weekly-Bulletin-Final-December-05-2025.pdf... direct (0.5s)
[1716/3287] JSEs-Weekly-Bulletin-Final-December-12-2025.pdf... direct (0.4s)
[1717/3287] JSEs-Weekly-Bulletin-Final-December-19-2025.pdf... direct (0.5s)
[1718/3287] JSEs-Weekly-Bulletin-Final-January-02-2026.pdf... direct (0.4s)
[1719/3287] JSEs-Weekly-Bulletin-Final-January-09-2026.pdf... direct (0.5s)
[1720/3287] JSEs-Weekly-Bulletin-Final-January-16-2026.pdf... direct (0.4s)
  -- checkpoint saved (1720 jse records so far)
[1721/3287] JSEs-Weekly-Bulletin-Final-January-23-2026.pdf... direct (0.4s)
[1722/3287] JSEs-Weekly-Bulletin-Final-January-30-2026.pdf... direct (0.4s)
[1723/3287] JSEs-Weekly-Bulletin-Final-November-07-2025.pdf... direct (0.5s)
[1724/3287] JSEs-Weekly-Bulletin-Final-November-14-2025.pdf... direct (0.5s)
[1725/3287] JSEs-Weekly-Bulletin-Final-November-21-2025.pdf... direct (0.4s)
[1726/3287] JSEs-Weekly-Bulletin-Final-October-10-2025.pdf... direct (0.5s)
[1727/3287] JSEs-Weekly-Bulletin-Final-October-17-2025.pdf... direct (0.4s)
[1728/3287] JSEs-Weekly-Bulletin-Final-October-24-2025.pdf... direct (0.4s)
[1729/3287] JSEs-Weekly-Bulletin-Final-October-31-2025.pdf... direct (0.5s)
[1730/3287] JSEs-Weekly-Bulletin-January-10-2025-.pdf... direct (0.5s)
  -- checkpoint saved (1730 jse records so far)
[1731/3287] JSEs-Weekly-Bulletin-January-17-2025.pdf... direct (0.4s)
[1732/3287] JSEs-Weekly-Bulletin-January-24-2025.pdf... direct (0.5s)
[1733/3287] JSEs-Weekly-Bulletin-January-3-2025.pdf... direct (0.5s)
[1734/3287] JSEs-Weekly-Bulletin-January-31-2025.pdf... direct (0.5s)
[1735/3287] JSEs-Weekly-Bulletin-July-03-2026-Final.pdf... direct (0.4s)
[1736/3287] JSEs-Weekly-Bulletin-July-10-2026-Final.pdf... direct (0.5s)
[1737/3287] JSEs-Weekly-Bulletin-July-11-2025.pdf... direct (0.4s)
[1738/3287] JSEs-Weekly-Bulletin-July-17-2026-Final.pdf... direct (0.6s)
[1739/3287] JSEs-Weekly-Bulletin-July-18-2025-DM.pdf... direct (0.4s)
[1740/3287] JSEs-Weekly-Bulletin-July-24-2026-Final.pdf... direct (0.5s)
  -- checkpoint saved (1740 jse records so far)
[1741/3287] JSEs-Weekly-Bulletin-July-25-2025-1.pdf... direct (0.4s)
[1742/3287] JSEs-Weekly-Bulletin-July-31-2025.pdf... direct (0.6s)
[1743/3287] JSEs-Weekly-Bulletin-July-31-2026-Final.pdf... direct (0.4s)
[1744/3287] JSEs-Weekly-Bulletin-July-4-2025.pdf... direct (0.5s)
[1745/3287] JSEs-Weekly-Bulletin-June-12-2026-Final-1.pdf... direct (0.4s)
[1746/3287] JSEs-Weekly-Bulletin-June-13-2025.pdf... direct (0.6s)
[1747/3287] JSEs-Weekly-Bulletin-June-19-2026-Final.pdf... direct (0.5s)
[1748/3287] JSEs-Weekly-Bulletin-June-20-2025.pdf... direct (0.5s)
[1749/3287] JSEs-Weekly-Bulletin-June-26-2026-FINAL.pdf... direct (0.5s)
[1750/3287] JSEs-Weekly-Bulletin-June-27-2025.pdf... direct (0.5s)
  -- checkpoint saved (1750 jse records so far)
[1751/3287] JSEs-Weekly-Bulletin-June-5-2026-FINAL.pdf... direct (0.6s)
[1752/3287] JSEs-Weekly-Bulletin-June-6-2025.pdf... direct (0.5s)
[1753/3287] JSEs-Weekly-Bulletin-March-06-2026-1.pdf... direct (0.6s)
[1754/3287] JSEs-Weekly-Bulletin-March-13-2026.pdf... direct (0.5s)
[1755/3287] JSEs-Weekly-Bulletin-March-14-2025.pdf... direct (0.5s)
[1756/3287] JSEs-Weekly-Bulletin-March-20-2026.pdf... direct (0.6s)
[1757/3287] JSEs-Weekly-Bulletin-March-21-2025.pdf... direct (0.5s)
[1758/3287] JSEs-Weekly-Bulletin-March-27-2026.pdf... direct (0.6s)
[1759/3287] JSEs-Weekly-Bulletin-March-28-2025.pdf... direct (0.5s)
[1760/3287] JSEs-Weekly-Bulletin-March-7-2025.pdf... direct (0.6s)
  -- checkpoint saved (1760 jse records so far)
[1761/3287] JSEs-Weekly-Bulletin-May-01-2026-Final.pdf... direct (0.5s)
[1762/3287] JSEs-Weekly-Bulletin-May-08-2026-Final.pdf... direct (0.4s)
[1763/3287] JSEs-Weekly-Bulletin-May-15-2026-Final.pdf... direct (0.5s)
[1764/3287] JSEs-Weekly-Bulletin-May-16-2025.pdf... direct (0.5s)
[1765/3287] JSEs-Weekly-Bulletin-May-2-2025.pdf... direct (0.6s)
[1766/3287] JSEs-Weekly-Bulletin-May-22-2025.pdf... direct (0.5s)
[1767/3287] JSEs-Weekly-Bulletin-May-22-2026-Final.pdf... direct (0.4s)
[1768/3287] JSEs-Weekly-Bulletin-May-29-2026-Final.pdf... direct (0.5s)
[1769/3287] JSEs-Weekly-Bulletin-May-30-2025.pdf... direct (0.5s)
[1770/3287] JSEs-Weekly-Bulletin-May-9-2025.pdf... direct (0.6s)
  -- checkpoint saved (1770 jse records so far)
[1771/3287] JSEs-Weekly-Bulletin-November-1-2024.pdf... direct (0.4s)
[1772/3287] JSEs-Weekly-Bulletin-November-11-November-15-2024-DM.pdf... direct (0.6s)
[1773/3287] JSEs-Weekly-Bulletin-November-22-2024.pdf... direct (0.5s)
[1774/3287] JSEs-Weekly-Bulletin-November-29-2024.pdf... direct (0.6s)
[1775/3287] JSEs-Weekly-Bulletin-November-8-2024.pdf... direct (0.5s)
[1776/3287] JSEs-Weekly-Bulletin-October-03-2025.pdf... direct (0.4s)
[1777/3287] JSEs-Weekly-Bulletin-October-11-2024.pdf... direct (0.5s)
[1778/3287] JSEs-Weekly-Bulletin-October-18-2024.pdf... direct (0.5s)
[1779/3287] JSEs-Weekly-Bulletin-October-25-2024.pdf... direct (0.5s)
[1780/3287] JSEs-Weekly-Bulletin-October-4-2024.pdf... direct (0.5s)
  -- checkpoint saved (1780 jse records so far)
[1781/3287] JSEs-Weekly-Bulletin-September-12-2025.pdf... direct (0.7s)
[1782/3287] JSEs-Weekly-Bulletin-September-13-2024.pdf... direct (0.6s)
[1783/3287] JSEs-Weekly-Bulletin-September-19-2025-Final.pdf... direct (0.4s)
[1784/3287] JSEs-Weekly-Bulletin-September-20-2024.pdf... direct (0.6s)
[1785/3287] JSEs-Weekly-Bulletin-September-26-2025.pdf... direct (0.4s)
[1786/3287] JSEs-Weekly-Bulletin-September-27-2024.pdf... direct (0.6s)
[1787/3287] JSEs-Weekly-Bulletin-September-5-2025.pdf... direct (0.5s)
[1788/3287] JSEs-Weekly-Bulletin-September-6-2024.pdf... direct (0.5s)
[1789/3287] JTL-ANNUAL-REPORT-2024.pdf... direct (22.6s)
[1790/3287] JTL-Annual-Report-2025-_rvsd.pdf... direct (15.3s)
  -- checkpoint saved (1790 jse records so far)
[1791/3287] JTL-Q4-2024-Report-.pdf... direct (2.2s)
[1792/3287] JTL-Unaudited-Results-Dec-2025.pdf... direct (1.7s)
[1793/3287] Jamaica-Broilers-Group-Limited-2025-final-accounts.pdf... direct (17.4s)
[1794/3287] Jamaica-Money-Market-Brokers-Limited-Audited-Financial-Reports-for-year-ended-31-March-2026.pdf... direct (11.1s)
[1795/3287] Jamaica-Money-Market-Brokers-Limited-JMMB-Audited-Financial-Results-for-the-year-ended-31-March-2025.pdf... direct (11.4s)
[1796/3287] Jamaica-Money-Market-Brokers-Limited-JMMB_Shareholder-List-for-the-year-ended-31-March-31-2025.pdf... direct (0.0s)
[1797/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-nine-months-ended-December-31-2024.pdf... direct (0.4s)
[1798/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-December-31-2025.pdf... direct (0.4s)
[1799/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-June-30-2025.pdf... direct (0.4s)
[1800/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-June-30-2026.pdf... direct (0.4s)
  -- checkpoint saved (1800 jse records so far)
[1801/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-quarter-ended-September-30-2025.pdf... direct (0.4s)
[1802/3287] Jamaica-Money-Market-Brokers-Limited-Unaudited-Financial-Statements-for-the-six-months-ended-September-30-2024-1.pdf... direct (0.4s)
[1803/3287] Jamaica-Producers-Group-AGM-Notice-2025.pdf... direct (0.7s)
[1804/3287] Jamaica-Producers-Group-Annual-Report-2025.pdf... direct (26.7s)
[1805/3287] Jamaica-Producers-Group-Limited-Financial-Statements-2024.pdf... direct (6.2s)
[1806/3287] Jamaica-Producers-Group-Limited_Financial-Statements_2025.pdf... direct (4.9s)
[1807/3287] Jamaica-Producers-Group-Proxy-Form-2025.pdf... direct (0.1s)
[1808/3287] Jamaican-Teas-Limited-2024-Consolidated-Financial-Statements-FINAL-1.pdf... direct (11.1s)
[1809/3287] Jamaican-Teas-Limited-2025-Consol-FS-Final-Signed.pdf... direct (12.7s)
[1810/3287] January_2025_analysis.pdf... direct (1.9s)
  -- checkpoint saved (1810 jse records so far)
[1811/3287] January_2026_analysis.pdf... direct (2.5s)
[1812/3287] Jetcon-AR2023-Reupload.pdf... direct (10.1s)
[1813/3287] Jetcon-Annual-Report-2024.pdf... direct (9.8s)
[1814/3287] Jetcon-Annual-Report-2025.pdf... direct (10.1s)
[1815/3287] Jetcon-PDF-Financial-Statements-Feb.-26-2026.pdf... direct (6.8s)
[1816/3287] Jetcon-PDF-financial-statements.pdf... direct (7.0s)
[1817/3287] Jetcon-Q1-2025.pdf... direct (1.1s)
[1818/3287] Jetcon-Q1-2026.pdf... direct (0.9s)
[1819/3287] Jetcon-Q2-2025.pdf... direct (1.0s)
[1820/3287] Jetcon-Q2-2026.pdf... direct (0.9s)
  -- checkpoint saved (1820 jse records so far)
[1821/3287] Jetcon-Q3-2024.pdf... direct (1.0s)
[1822/3287] Jetcon-Q3-2025-amended.pdf... direct (1.0s)
[1823/3287] Jtl-Q1-2025.pdf... direct (1.5s)
[1824/3287] Jtl-Q2-2025.pdf... direct (1.8s)
[1825/3287] Jtl-Q2-2026.pdf... direct (1.8s)
[1826/3287] Jtl-Q3-2025.pdf... direct (1.6s)
[1827/3287] Jtl-Q3-2026-FINAL.pdf... direct (1.7s)
[1828/3287] Jtl-Q4-2025-1.pdf... direct (1.7s)
[1829/3287] July_2025_analysis.pdf... direct (2.2s)
[1830/3287] July_2026_analysis.pdf... direct (2.3s)
  -- checkpoint saved (1830 jse records so far)
[1831/3287] June-2025-Financial-Statement_250809_123927.pdf... needs_ocr_elsewhere (0.0s)

[1832/3287] June-2025-Publication.pdf... direct (2.0s)
[1833/3287] June-2026-Q2-Unaudited-Financial-Results-1.pdf... direct (1.1s)
[1834/3287] June_2025_analysis.pdf... direct (2.2s)
[1835/3287] June_2026_analysis.pdf... direct (2.4s)
[1836/3287] K.L.E.-GROUP-LIMITED-UNAUDITED-FINANCIAL-STATEMENTS-ENDED-MARCH-31-2025.pdf... direct (1.6s)
[1837/3287] KE-AR-Digital-Report-2024.pdf... direct (16.0s)
[1838/3287] KES-2025-Financial-Statements-FINALIZED.pdf... direct (10.2s)
[1839/3287] KEX-Digital-AR-2025.pdf... direct (13.3s)
[1840/3287] KEY-ANNUAL-REPORT-2024-FINAL-1.pdf... direct (21.3s)
  -- checkpoint saved (1840 jse records so far)
[1841/3287] KEY-Advisory-re-Delisting.pdf... direct (0.1s)
[1842/3287] KEY-Directors-Circular-Final.pdf... direct (13.6s)
[1843/3287] KEY-Directors-Holding-as-at-June-30-2025.pdf... direct (0.2s)
[1844/3287] KEY-Directors-Holding-as-at-September-30-2024.pdf... direct (0.2s)
[1845/3287] KEY-Offer-Circular-FINAL.pdf... direct (2.7s)
[1846/3287] KEY-Senior-Managers-Holding-as-at-June-30-2025.pdf... direct (0.1s)
[1847/3287] KEY-Senior-Managers-Holding-as-at-September-30-2024.pdf... direct (0.1s)
[1848/3287] KEY-Top-10-Shareholdings-as-at-June-30-2025-003.pdf... direct (0.1s)
[1849/3287] KEY-Top-10-Shareholdings-as-at-September-30-2024.pdf... direct (0.1s)
[1850/3287] KEY-Top10ShareholdingsasatDecember312024.pdf... direct (0.1s)
  -- checkpoint saved (1850 jse records so far)
[1851/3287] KEY-Top10ShareholdingsasatMarch312025.pdf... direct (0.3s)
[1852/3287] KEY-Top10ShareholdingsasatSeptember302025.pdf... direct (0.1s)
[1853/3287] KEYDirectorsHoldingasatDecember312024.pdf... direct (0.2s)
[1854/3287] KEYDirectorsHoldingasatMarch312025.pdf... direct (0.2s)
[1855/3287] KEYDirectorsHoldingasatSeptember302025.pdf... direct (0.2s)
[1856/3287] KEYSeniorManagersHoldingasatDecember312024.pdf... direct (0.1s)
[1857/3287] KEYSeniorManagersHoldingasatMarch312025.pdf... direct (0.2s)
[1858/3287] KEYSeniorManagersHoldingasatSeptember302025.pdf... direct (0.1s)
[1859/3287] KINGSTON-WHARVES-DIVIDEND-DECLARATION-NOTICE-02-JUNE-2026.pdf... direct (0.0s)
[1860/3287] KINTYRE-HOLDINGS-JA-LIMITED-KNTYR-%E2%80%93-Shareholder-Statement-Proposed-NYSE-Listing-Plans-Unaffected-by-VM-Investments-Limited-Court-Proceedings.pdf... direct (0.3s)
  -- checkpoint saved (1860 jse records so far)
[1861/3287] KLE-GROUP-ANNUAL-RPT-2024.pdf... direct (9.2s)
[1862/3287] KLE-GROUP-LIMITED-ANNUAL-REPORT-2025.pdf... direct (13.9s)
[1863/3287] KLE-GROUP-LIMITED-UNAUDITED-FINANCIAL-STATEMENTS-ENDED-SEPTEMBER-30-2025.pdf... direct (2.0s)
[1864/3287] KLE-GROUP-LIMITED-UNAUDITED-FS-QUATER-ENDED-MARCH-31-2026.pdf... direct (1.6s)
[1865/3287] KLE-Group-Limited-2024-FS.pdf... direct (8.0s)
[1866/3287] KLE-Group-Limited-2025-Financial-Statements.pdf... direct (11.0s)
[1867/3287] KLE-Late-Submission-of-Audited-Financial-Statements-Year-ended-December-31-2025.pdf... direct (0.1s)
[1868/3287] KLE-QRTLY-REPT-2025-March-31.pdf... direct (0.1s)
[1869/3287] KLE-QRTLY-REPT-2025-September-30.pdf... direct (0.1s)
[1870/3287] KLE-Quarterly-Report-June-30-2025-1.pdf... direct (0.1s)
  -- checkpoint saved (1870 jse records so far)
[1871/3287] KLE-Top-Ten-Shareholding-2025-December-31.pdf... direct (0.1s)
[1872/3287] KLE-Top-Ten-Shareholdings-December-31-2024.pdf... direct (0.1s)
[1873/3287] KLE-Unaudited-Financial-Statement-September-30-2024.pdf... direct (1.8s)
[1874/3287] KLE-Unaudited-Financials-June-30-2025.pdf... direct (1.7s)
[1875/3287] KNTYR-GetPaid-JSE-Update.pdf.pdf... direct (0.7s)
[1876/3287] KNTYR-Update-on-Rights-Issue.pdf... direct (0.6s)
[1877/3287] KNUTSFORD-EXPRESS-SERVICES-LIMITED-FS-2026-FINALIZED.pdf... direct (9.7s)
[1878/3287] KPL-Shareholdings-Report-December-2024.pdf... direct (0.1s)
[1879/3287] KPL-Shareholdings-Report-December-2025.pdf... direct (0.1s)
[1880/3287] KPREIT-AGM-Notice-2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1880 jse records so far)
[1881/3287] KPREIT-EGM-NOTICE-AND-PROXY-FORM.pdf... direct (1.3s)
[1882/3287] KPREIT-Form-Of-Proxy-2026.pdf... needs_ocr_elsewhere (0.0s)
[1883/3287] KPREIT-UNAUDITEDGROUP-FS-AMENDED.pdf... direct (1.0s)
[1884/3287] KPREIT-Unaudited-Financial-Statements-March-31-2025.pdf... direct (3.8s)
[1885/3287] KPREIT-Unaudited-Financial-Statements-for-Nine-months-ended-September-2024.pdf... direct (1.5s)
[1886/3287] KPREIT-Unaudited-Financial-Statements-for-six-months-ended-June-2025.pdf... direct (1.9s)
[1887/3287] KREMI-Qtr-1-Unaudited-Stock-Exch-report-May-31-2025.pdf... direct (1.8s)
[1888/3287] KREMI-Qtr-2-Unaudited-Stock-Exch-report-August-31-2024-1.pdf... direct (1.8s)
[1889/3287] KREMI-Qtr-2-Unaudited-Stock-Exch-report-August-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[1890/3287] KREMI-Qtr-3-Unaudited-Stock-Exch-report-November-30-2024.pdf... direct (1.9s)
  -- checkpoint saved (1890 jse records so far)
[1891/3287] KREMI-Qtr-3-Unaudited-Stock-Exch-report-November-30-2025.pdf... direct (1.8s)
[1892/3287] KREMI-revised-Qtr-1-Stock-Exch-report-May-31-2024.pdf... direct (1.8s)
[1893/3287] KWL-2025-Final-Financial-Statements.pdf... direct (15.6s)
[1894/3287] KWL-Annual-Report-2024.pdf... direct (27.5s)
[1895/3287] KWL-Annual-Report-2025.pdf... direct (24.6s)
[1896/3287] KWL-Chairmans-Statement-Shareholding-Report-31-December-2024.pdf... direct (0.3s)
[1897/3287] KWL-Chairmans-Statement-Shareholding-Report-31-December-2025_.pdf... direct (0.4s)
[1898/3287] KWL-JSE-DISCLOSURE-UNDER-APPENDIX-1-RULE-12.1.pdf... direct (0.1s)
[1899/3287] Key-Ins-Q1-Shareholder-Report-March-2025-Final_.pdf... direct (0.9s)
[1900/3287] Key-Ins-Q3-Shareholder-Report-September-2025.pdf... direct (1.0s)
  -- checkpoint saved (1900 jse records so far)
[1901/3287] Key-Insurance-Company-Limited-Financial-Statements-2024-1.pdf... direct (12.2s)
[1902/3287] Key-Insurance-Company-Ltd.-Advisory-re-the-Appointment-of-Tammara-Glaves-Hucey.pdf... needs_ocr_elsewhere (0.0s)
[1903/3287] Key-Insurance-Q2-Shareholder-Report-June-2025-Final_Upload-v4.pdf... direct (1.0s)
[1904/3287] Key-Note-Remarks_JSE-Market-Research-Awards_November-2025.pdf... direct (0.9s)
[1905/3287] Key-Shareholders-as-at-December-2025.pdf... direct (0.0s)
[1906/3287] Key-Shareholdings.pdf... direct (0.0s)
[1907/3287] Key-Stockholder-Report-Dec-2024-1.pdf... direct (0.3s)
[1908/3287] Kingston-Properties-Annual-Report-2025.pdf... direct (189.2s)
    ^ SLOW FILE -- Kingston-Properties-Annual-Report-2025.pdf took 189.2s
[1909/3287] Kingston-Properties-Limited-Annual-Report-2024.pdf... direct (29.7s)
[1910/3287] Kingston-Properties-Limited-Audited-Financial-Statements-2024.pdf... direct (6.3s)
  -- checkpoint saved (1910 jse records so far)
[1911/3287] Kingston-Properties-Limited-Audited-Financial-Statements-2025.pdf... direct (6.0s)
[1912/3287] Kingston-Properties-Limited-KPREIT-Unaudited-Financial-Statements-For-The-First-Quarter-Ended-March-31-2026.pdf... direct (2.1s)
[1913/3287] Kingston-Properties-Limited-KPREIT-Unaudited-Financial-Statements-For-The-Second-Quarter-Ended-June-30-2026-1.pdf... direct (3.4s)
[1914/3287] Kingston-Properties-Limited-Share-Capital-Note-Clarification.pdf... direct (0.0s)
[1915/3287] Kingston-Wharves-%E2%80%93-Financial-Statements-2024.pdf... direct (15.7s)
[1916/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q1-2025_.pdf... direct (1.2s)
[1917/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q1-2026_.pdf... direct (2.4s)
[1918/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q2-2025_.pdf... direct (2.1s)
[1919/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q2-2026_.pdf... direct (2.2s)
[1920/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q3-2024.pdf... direct (1.7s)
  -- checkpoint saved (1920 jse records so far)
[1921/3287] Kingston-Wharves-Limited-KWL-Unaudited-Results-Q3-2025_.pdf... direct (2.1s)
[1922/3287] Kingston-Wharves-Limited-Notice-of-Annual-General-Meeting-2025.pdf... direct (0.2s)
[1923/3287] Kintyre-Acquires-Properties-in-Jamaica-and-Trinidad-and-Tobago-1.pdf... direct (0.2s)
[1924/3287] Kintyre-Dividend-Meeting.pdf... direct (0.6s)
[1925/3287] Kintyre-Holdings-Acquire-J110M-Stony-Hill-Property-3.pdf... direct (0.6s)
[1926/3287] Kintyre-Holdings-Appointment-Notice-of-Parallel-CEOs.pdf.pdf... direct (0.4s)
[1927/3287] Kintyre-Holdings-Disclosure-On-Kulcha-Rum-Acquisition-2.pdf... direct (0.1s)

[1928/3287] Kintyre-Holdings-Enters-Strategic-Tech-Venture-with-Digitize-Jamaica-3.pdf... direct (1.0s)
[1929/3287] Kintyre-Holdings-Expansion-Into-The-US-Market.pdf... direct (0.4s)
[1930/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Clarification-Regarding-VM-Investments-Limited-Statement-and-Confirmation-of-Non-Involvement-in-Legal-Proceedings-.pdf... direct (0.3s)
  -- checkpoint saved (1930 jse records so far)
[1931/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Leadership-Changes-2.pdf... direct (0.4s)
[1932/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Leadership-Changes-at-Parallel-Real-Estate-Ventures-Limited.pdf... direct (0.6s)
[1933/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Leadership-Changes-at-Visual-Vibe-Ahead-of-Planned-IPO-2.pdf... direct (0.3s)
[1934/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Notification-of-Proposed-Shareholder-Restructuring-and-Formation-of-International-Holding-Company.pdf... direct (0.5s)
[1935/3287] Kintyre-Holdings-JA-Limited-KNTYR-%E2%80%93-Signing-of-Agreement-to-Acquire-100-of-OOH-Media-Services-Limited--1.pdf... direct (0.4s)
[1936/3287] Kintyre-Holdings-JA-Limited-KNTYR-Enters-EV-Market-JSE.pdf... direct (0.3s)
[1937/3287] Kintyre-Holdings-JA-Limited-KNTYR-Notice-of-Delay-in-Audited-Financial-Statements-.pdf... direct (0.1s)
[1938/3287] Kintyre-Holdings-JA-Limited-KNTYR-Notice-of-Delay-in-Audited-Financial-Statements-June-2026.pdf... direct (0.2s)
[1939/3287] Kintyre-Holdings-JA-Limited-KNTYR-Provides-Update-on-2025-Audited-Financial-Statements-and-Q2-2026-Unadited-Financial-Statements.pdf... direct (0.2s)
[1940/3287] Kintyre-Holdings-JA-Limited-KNTYR-Provides-Update-on-Audited-Financial-Statements-and-JSE-Suspension.pdf... direct (0.2s)
  -- checkpoint saved (1940 jse records so far)
[1941/3287] Kintyre-Holdings-JA-Limited-Q1-2025-v4.pdf... direct (0.7s)
[1942/3287] Kintyre-Holdings-JA-Limited-Q1-Unaudited-FS-Ended-March-31-2026_copy.pdf... direct (3.1s)
[1943/3287] Kintyre-Holdings-JA-Limited-Q2-Unaudited-FS-ended-June-30-2025.pdf... direct (2.3s)
[1944/3287] Kintyre-Holdings-JA-Limited-Q3-Unaudited-FS-ended-Sep-30-2025-2.pdf... direct (2.3s)
[1945/3287] Kintyre-Holdings-JA-Limited-Q3-Unaudited-FS-ended-Sep-30-2025.pdf... direct (2.1s)
[1946/3287] Kintyre-Holdings-JA-Limited-Q3-Unaudited-Financial-Statements.pdf... direct (0.9s)
[1947/3287] Kintyre-Holdings-JA-Limited-Q4-Unaudited-FS-FINAL_copy.pdf... direct (1.0s)
[1948/3287] Kintyre-Holdings-JA-Limited-Seven-Kingston-Limited-Announce-Joint-Venture-for-Ice-Manufacturing-2.pdf... needs_ocr_elsewhere (0.0s)
[1949/3287] Kintyre-Holdings-KNTYR-Subsidiary-Visual-Vibe-Secures-US500000-Investment-from-Michael-Lee-Chin-Led-Portland-Holdings-Private-Equity-Fund.pdf... direct (0.6s)
[1950/3287] Kintyre-Holdings-Leadership-Changes.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1950 jse records so far)
[1951/3287] Kintyre-Holdings-Notice-to-the-JSE-Re-Late-Financial-Statements-2025.pdf.pdf... direct (0.3s)
[1952/3287] Kintyre-Holdings-Rights-Issue-Notice-1.pdf... needs_ocr_elsewhere (1.7s)
[1953/3287] Kintyre-Limited-Group-FS-2024_signed-2.pdf... direct (5.1s)
[1954/3287] Kintyre-Secures-Full-Regulatory-Approvals-for-The-Chalet-at-Bengal-Beach-St.-Ann-and-Contemplates-Immediate-Sale-or-Funding-Partnership.pdf... direct (0.4s)
[1955/3287] Kintyre-seals-J500m-Clarendon-land-deal.pdf... direct (0.4s)
[1956/3287] Knutsford-Express-1st-Quarter-JSE-Report-August-2024-FINAL-Oct-14-2024.pdf... direct (1.6s)
[1957/3287] Knutsford-Express-1st-Quarter-JSE-Report-August-2025-FINAL-Signed-2.pdf... direct (1.8s)
[1958/3287] Knutsford-Express-2nd-Quarter-JSE-Report-12JAN2026.pdf... direct (1.4s)
[1959/3287] Knutsford-Express-Nine-9-months-ending-February-28-2026-B-Signed.pdf... direct (1.5s)
[1960/3287] Knutsford-Express-Services-Ltd-2024-FS-Finalized.pdf... direct (10.2s)
  -- checkpoint saved (1960 jse records so far)
[1961/3287] Kremi-Annual-Report-FY2024-25.pdf... needs_ocr_elsewhere (105.7s)
    ^ SLOW FILE -- Kremi-Annual-Report-FY2024-25.pdf took 105.7s
[1962/3287] Kremi-Annual-Report-FY2025-26.pdf... direct (9.1s)
[1963/3287] Kremi-Annual-Report.pdf... direct (8.8s)
[1964/3287] Kulcha-Rum-100-Acquisition.pdf... direct (0.9s)
[1965/3287] LAB-Financial-Performance-OCT-2024-Updated-1.pdf... direct (0.5s)
[1966/3287] LASCO-Distributors-Limited-JSE-Report-September-2024.pdf... needs_ocr_elsewhere (0.0s)
[1967/3287] LASD-2025-Annual-Report.pdf... direct (5.6s)
[1968/3287] LASD-Annual-Report-2026.pdf... direct (6.1s)
[1969/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-REPORT-AS-AT-DECEMBER-31-2024.pdf... direct (0.1s)
[1970/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-REPORT-AS-AT-JUNE-30-2025.pdf... direct (0.0s)
  -- checkpoint saved (1970 jse records so far)
[1971/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-REPORT-AS-AT-MARCH-31-2025.pdf... direct (0.1s)
[1972/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-REPORT-AS-AT-MARCH-31-2026.pdf... direct (0.1s)
[1973/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-REPORT-AS-AT-SEPTEMBER-30-2024.pdf... direct (0.0s)
[1974/3287] LASD-DIRECTORS-AND-CONNECTED-PARTIES-SHAREHOLDING-JUNE-30-2026.pdf... direct (0.1s)
[1975/3287] LASD-Directors-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[1976/3287] LASD-Directors-and-Connected-Parties-Shareholdngs.pdf... needs_ocr_elsewhere (0.0s)
[1977/3287] LASD-FIRST-QUARTER-UNAUDITED-FINANCIAL-REPORT-THREE-MONTHS-ENDED-JUNE-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[1978/3287] LASD-FIRST-QUARTER-UNAUDITED-FINANCIAL-STATEMENTS-JUNE-30-2026.pdf... needs_ocr_elsewhere (0.0s)
[1979/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-REPORT-FOR-DECEMBER-31-2024.pdf... direct (0.0s)
[1980/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-REPORT-FOR-JUNE-30-2025.pdf... direct (0.0s)
  -- checkpoint saved (1980 jse records so far)
[1981/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-REPORT-FOR-SEPTEMBER-30-2024.pdf... direct (0.0s)
[1982/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-SHAREHOLDING-JUNE-30-2026.pdf... direct (0.0s)
[1983/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-REPORT-FOR-MARCH-31-2025.pdf... direct (0.0s)
[1984/3287] LASD-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-REPORT-FOR-MARCH-31-2026.pdf... direct (0.0s)
[1985/3287] LASD-Second-Quarter-Unaudited-Financial-Report-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[1986/3287] LASD-Senior-Manager-and-Connected-Parties-Shareholdings.pdf... needs_ocr_elsewhere (0.0s)
[1987/3287] LASD-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[1988/3287] LASD-Shareholders-Report-March-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[1989/3287] LASD-TOP-TEN-SHAREHOLDINGS-DECEMBER-31-2024.pdf... direct (0.1s)
[1990/3287] LASD-TOP-TEN-SHAREHOLDINGS-JUNE-30-2025.pdf... direct (0.1s)
  -- checkpoint saved (1990 jse records so far)
[1991/3287] LASD-TOP-TEN-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.1s)
[1992/3287] LASD-TOP-TEN-SHAREHOLDINGS-MARCH-31-2025.pdf... direct (0.1s)
[1993/3287] LASD-TOP-TEN-SHAREHOLDINGS-MARCH-31-2026.pdf... direct (0.1s)
[1994/3287] LASD-TOP-TEN-SHAREHOLDINGS-SEPTEMBER-30-2024.pdf... direct (0.1s)
[1995/3287] LASD-Third-Quarter-Unaudited-Financial-Report-for-the-Nine-months-ended-December-31-2024.pdf... needs_ocr_elsewhere (0.0s)
[1996/3287] LASD-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[1997/3287] LASD-Top-Ten-Shareholdings-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[1998/3287] LASD-Top-Ten-Shareholdings.pdf... needs_ocr_elsewhere (0.0s)
[1999/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-DECEMBER-31-2025.pdf... direct (0.0s)
[2000/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-JUNE-30-2025.pdf... direct (0.0s)
  -- checkpoint saved (2000 jse records so far)
[2001/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-MARCH-31-2025.pdf... direct (0.0s)
[2002/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-MARCH-31-2026.pdf... direct (0.0s)
[2003/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-SEPTEMBER-30-2024.pdf... direct (0.0s)
[2004/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-SEPTEMBER-30-2025.pdf... direct (0.0s)
[2005/3287] LASF-DIRECTORS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.0s)

[2006/3287] LASF-FIRST-QUARTER-UNAUDITED-FINANCIAL-STATEMENTS-JUNE-30-2026.pdf... direct (0.8s)
[2007/3287] LASF-JSE-1st-Quarter-June-2025.pdf... direct (1.2s)
[2008/3287] LASF-JSE-2nd-quarter-September-2024-final.pdf... direct (0.7s)
[2009/3287] LASF-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.0s)
[2010/3287] LASF-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-December-31-2025.pdf... direct (0.0s)
  -- checkpoint saved (2010 jse records so far)
[2011/3287] LASF-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-June-30-2025.pdf... direct (0.0s)
[2012/3287] LASF-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-SEPTEMBER-30-2024.pdf... direct (0.0s)
[2013/3287] LASF-TOP-TEN-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.1s)
[2014/3287] LASF-Top-Ten-Shareholdings-December-31-2025.pdf... direct (0.0s)
[2015/3287] LASF-Top-Ten-Shareholdings-June-30-2025.pdf... direct (0.0s)
[2016/3287] LASF-Top-Ten-Shareholdings-September-30-2024.pdf... direct (0.0s)
[2017/3287] LASM-2025-Annual-Report.pdf... direct (8.3s)
[2018/3287] LASM-DIRECTORS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.1s)
[2019/3287] LASM-Directors-and-Conected-Parties-Shareholdings-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[2020/3287] LASM-Directors-and-Connected-Parties-Shareholdings-as-at-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2020 jse records so far)
[2021/3287] LASM-Directors-and-Connected-Parties-Shareholdings-as-at-June-30-2025.pdf... direct (0.1s)
[2022/3287] LASM-Directors-and-Connected-Parties-Shareholdings.pdf... needs_ocr_elsewhere (0.0s)
[2023/3287] LASM-Directors-and-Connected-Parties-as-at-March-31-2026.pdf... direct (0.1s)
[2024/3287] LASM-Directors-and-Connected-Parties-as-at-September-30-2024.pdf... direct (0.0s)
[2025/3287] LASM-FIRST-QUARTER-UNAUDITED-FINANCIAL-STATEMENTS-JUNE-30-2026.pdf... needs_ocr_elsewhere (0.0s)
[2026/3287] LASM-First-Quarter-Unaudited-Financial-Report-Three-Months-Ended-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[2027/3287] LASM-SENIOR-MANAGERS-AND-CONNECTED-PARTIES-SHAREHOLDINGS-JUNE-30-2026.pdf... direct (0.0s)
[2028/3287] LASM-Second-Quarter-Un-Audited-Financial-Report-for-the-Six-Months-Ended-September-30-2024.pdf... needs_ocr_elsewhere (0.0s)
[2029/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholding-as-at-June-30-2025.pdf... direct (0.0s)
[2030/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholding-as-at-March-31-2026.pdf... direct (0.0s)
  -- checkpoint saved (2030 jse records so far)
[2031/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholding-as-at-September-30-2024.pdf... direct (0.0s)
[2032/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2033/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[2034/3287] LASM-Senior-Managers-and-Connected-Parties-Shareholdings.pdf... needs_ocr_elsewhere (0.0s)
[2035/3287] LASM-TOP-TEN-SHAREHOLDERS-JUNE-30-2026.pdf... direct (0.1s)
[2036/3287] LASM-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2037/3287] LASM-Top-Ten-Shareholders-as-at-June-30-2025.pdf... direct (0.0s)
[2038/3287] LASM-Top-Ten-Shareholders-as-at-March-31-2026.pdf... direct (0.1s)
[2039/3287] LASM-Top-Ten-Shareholders-as-at-September-30-2024.pdf... direct (0.0s)
[2040/3287] LASM-Top-Ten-Shareholders-as-at-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2040 jse records so far)
[2041/3287] LASM-Top-Ten-Shareholders.pdf... needs_ocr_elsewhere (0.0s)
[2042/3287] LASM-Top-Ten-Shareholdings-as-at-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2043/3287] LASM-Unaudited-Financial-Statements-for-the-Second-Quarter-Ended-September-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[2044/3287] LASM-Unaudited-Financial-Statements-for-the-Third-Quarter-Ended-December-31-2024.pdf... needs_ocr_elsewhere (0.0s)
[2045/3287] LETTER-JBG-20260723-JSE-Advisory.pdf... direct (0.1s)
[2046/3287] LETTER-TO-JSE-RE-SHARES-PURCHASED-JULY-2026.pdf... needs_ocr_elsewhere (0.0s)
[2047/3287] LFSL-DIRECTORS-AND-CONNECTED-PARTIES-AS-AT-DECEMBER-31-2024.pdf... direct (0.0s)
[2048/3287] LFSL-JSE-2024_25-Audited-Report.pdf... direct (0.3s)
[2049/3287] LFSL-JSE-2025_26-Audited-report-20260615.pdf... direct (0.1s)
[2050/3287] LFSL-JSE-2nd-Quarter-September-2025.pdf... direct (1.3s)
  -- checkpoint saved (2050 jse records so far)
[2051/3287] LFSL-JSE-3rd-quarter-December-2024-Final.pdf... direct (1.1s)
[2052/3287] LFSL-JSE-3rd-quarter-December-2025-1-20260209-Final.pdf... direct (1.2s)
[2053/3287] LFSL-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-December-31-2024.pdf... direct (0.0s)
[2054/3287] LFSL-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-MARCH-31-2025.pdf... direct (0.0s)
[2055/3287] LFSL-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-March-31-2026.pdf... direct (0.0s)
[2056/3287] LFSL-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-SEPTEMBER-30-2025.pdf... direct (0.0s)
[2057/3287] LFSL-Top-Ten-Shareholdings-December-31-2024.pdf... direct (0.0s)
[2058/3287] LFSL-Top-Ten-Shareholdings-March-31-2025.pdf... direct (0.0s)
[2059/3287] LFSL-Top-Ten-Shareholdings-March-31-2026.pdf... direct (0.1s)
[2060/3287] LFSL-Top-Ten-Shareholdings-September-30-2025.pdf... direct (0.1s)
  -- checkpoint saved (2060 jse records so far)
[2061/3287] LML-Report-2026-Single_compressed.pdf... direct (7.2s)
[2062/3287] LML-Reports-to-the-Shareholders-for-the-Twelve-Months-Ended-March-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2063/3287] LML-Shareholdings-as-at-March-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2064/3287] LTR-TO-JSE-NOTIFICATION-OF-CHANGE-OF-AUDITORupdated.pdf... needs_ocr_elsewhere (0.0s)
[2065/3287] LUMBER-AUDITED-FINANCIAL-STATEMENTS-APRIL-30-2025-1.pdf... direct (94.2s)
    ^ SLOW FILE -- LUMBER-AUDITED-FINANCIAL-STATEMENTS-APRIL-30-2025-1.pdf took 94.2s
[2066/3287] LUMBER-AUDITED-FINANCIAL-STATEMENTS-APRIL-30-2026.pdf... direct (9.4s)
[2067/3287] LUMBER-DEPOT-LIMITED-LUMBER-2024-ANNUAL-REPORT-PROXY-FORM.pdf... direct (0.4s)
[2068/3287] LUMBER-DEPOT-LIMITED-LUMBER-2024-ANNUAL-REPORT.pdf... direct (1.1s)
[2069/3287] LUMBER-DEPOT-LIMITED-LUMBER-2025-ANNUAL-REPORT-PROXY-FORM.pdf... direct (0.1s)
[2070/3287] LUMBER-DEPOT-LIMITED-LUMBER-2025-ANNUAL-REPORT.pdf... direct (5.5s)
  -- checkpoint saved (2070 jse records so far)
[2071/3287] LUMBER-Delayed-Filing-Of-Financial-Statements-2026-1.pdf... direct (0.1s)
[2072/3287] LUMBER-Delayed-Filing-of-Annual-Report-2025.pdf... direct (0.1s)
[2073/3287] LUMBER-Delayed-Filing-of-Audited-Financial-Statements.pdf... direct (0.1s)
[2074/3287] LUMBER-Notice-of-AGM-Postponement.pdf... direct (0.0s)
[2075/3287] LUMBER-RESULTS-AS-AT-JANUARY-31-2025.pdf... direct (17.2s)
[2076/3287] LUMBER-RESULTS-AS-AT-JANUARY-31-2026.pdf... direct (1.1s)
[2077/3287] LUMBER-RESULTS-AS-AT-JULY-31-2025.pdf... direct (1.1s)
[2078/3287] LUMBER-RESULTS-AS-AT-JULY-312024.pdf... direct (0.9s)
[2079/3287] LUMBER-RESULTS-AS-AT-OCTOBER-31-2025.pdf... direct (1.1s)
[2080/3287] LUMBER-RESULTS-AS-AT-OCTOBER-312024.pdf... direct (1.1s)
  -- checkpoint saved (2080 jse records so far)
[2081/3287] LUMBER-Strategic-Property-Acquisition.pdf... direct (0.2s)
[2082/3287] Lasco-Distributors-Limited-2026-FINAL.pdf... direct (6.1s)
[2083/3287] Lasco-Distributors-Limited-March-31-2025-Financial-Statements.pdf... direct (6.5s)
[2084/3287] Lasco-Financial-Services-FS-2025-Consol-3.pdf... direct (7.5s)
[2085/3287] Lasco-Financial-Services-Limited-2026-Final-Consolidated.pdf... direct (7.0s)
[2086/3287] Lasco-Financial_2025_Annual-Report_final-Web.pdf... direct (40.4s)
    ^ SLOW FILE -- Lasco-Financial_2025_Annual-Report_final-Web.pdf took 40.4s
[2087/3287] Lasco-Financial_2026_Annual-Report_Final_website_pages.pdf... direct (12.7s)
[2088/3287] Lasco-Manufacturing-2025-FS-.pdf... direct (5.6s)
[2089/3287] Lasco-Manufacturing-Limited-FS-2026-Final.pdf... direct (5.0s)
[2090/3287] Let-JSE-re-Declaration-of-Interim-Dividend-2026-signed.pdf... direct (0.3s)
  -- checkpoint saved (2090 jse records so far)
[2091/3287] Letter-JSE-ESOP-Announcements-26-June-2026.pdf... direct (0.1s)
[2092/3287] Letter-JSE-Resignation-Perrin-Gayle.pdf... direct (0.1s)

[2093/3287] Letter-JSE-Resignation-Tricia-Davies-April-2026.pdf... direct (0.1s)
[2094/3287] Letter-JSE-SGJ-Announcements-2024-.pdf... direct (0.2s)
[2095/3287] Letter-JSE-SGJ-Announcements-June-2026-FV.pdf... direct (0.1s)
[2096/3287] Letter-re-didivend-correction-of-date-.pdf... needs_ocr_elsewhere (0.0s)
[2097/3287] Letter-to-Bondholders-of-MJE.pdf... direct (0.1s)
[2098/3287] Letter-to-JSE-10NOV2025-3.pdf... direct (0.3s)
[2099/3287] Letter-to-JSE-Corporate-Governance-Policy-Sagicor-Real-Estate-X-Fund-Limited_signed.pdf... direct (3.3s)
[2100/3287] Letter-to-the-RMOD.pdf... direct (0.1s)
  -- checkpoint saved (2100 jse records so far)
[2101/3287] Lumber-Depot-Limited-LUMBER-AGM-Notice.pdf... direct (0.0s)
[2102/3287] Lumber-Depot-Limited-LUMBER-Annual-Report-2024.pdf... direct (4.6s)
[2103/3287] Lumber-Depot-Limited-LUMBER-Annual-Report-2025-1.pdf... direct (97.3s)
    ^ SLOW FILE -- Lumber-Depot-Limited-LUMBER-Annual-Report-2025-1.pdf took 97.3s
[2104/3287] Lumber-Depot-Limited-LUMBER-Annual-Report-2025.pdf... direct (98.3s)
    ^ SLOW FILE -- Lumber-Depot-Limited-LUMBER-Annual-Report-2025.pdf took 98.3s
[2105/3287] MAIN-EVENT-ENTERTAINMENT-GROUP-LIMITED-2025-Audited-Results.pdf... direct (6.9s)
[2106/3287] MAIN-EVENT-ENTERTAINMENT-GROUP-LIMITED-MEEG-ERRATA-STATEMENT-UNAUDITED-RESULTS-Q3-2024.pdf... direct (0.0s)
[2107/3287] MAIN-EVENT-ENTERTAINMENT-GROUP-LTD-ANNUAL-REPORT-2024.pdf... direct (7.3s)
[2108/3287] MANAGEMENT-DISCUSSION-AND-ANALYSIS-1.pdf... direct (0.1s)
[2109/3287] MANAGEMENT-DISCUSSION-AND-ANALYSIS-2.pdf... direct (0.5s)
[2110/3287] MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2110 jse records so far)
[2111/3287] MARKET-RESEARCH-COMPETITION-Overview-Structure-and-Rules.pdf... direct (0.8s)
[2112/3287] MASSY-Audited-Consolidated-Financial-Statements-September-30-2025.pdf... direct (17.1s)
[2113/3287] MASSY-Audited-Financial-Statements.pdf... direct (16.1s)
[2114/3287] MASSY-CEO-Report-2024-Annual-Report.pdf... direct (0.3s)
[2115/3287] MASSY-CEO-Report-2025-Annual-Report.pdf... direct (0.4s)
[2116/3287] MASSY-CFO-Report-2024-Annual-Report.pdf... direct (0.7s)
[2117/3287] MASSY-CFO-Report-2025-Annual-Report.pdf... direct (1.4s)
[2118/3287] MASSY-Change-in-Director-Snr-Officers.-Executive-Director-Group-Chief-Financial-Officer.pdf... needs_ocr_elsewhere (0.0s)
[2119/3287] MASSY-Circular-Letter-to-Shareholders.pdf... direct (0.6s)
[2120/3287] MASSY-Corporate-Governance-Code-2025.pdf... direct (2.0s)
  -- checkpoint saved (2120 jse records so far)
[2121/3287] MASSY-DIVIDEND-DECLARATION-NOTICE.pdf... needs_ocr_elsewhere (0.4s)
[2122/3287] MASSY-Notice-Dividend-Payment-Schedule-Change.pdf... needs_ocr_elsewhere (0.0s)
[2123/3287] MASSY-Notice-Intention-to-Access-Long-Term-Financing.pdf... needs_ocr_elsewhere (0.9s)
[2124/3287] MASSY-Notice-of-Annual-Meeting.pdf... needs_ocr_elsewhere (0.7s)
[2125/3287] MASSY-Notice-of-Annual-Report.pdf... needs_ocr_elsewhere (0.4s)
[2126/3287] MASSY-Notice-of-Audited-Consolidated-Financial-Statements-Sep-30-2025.pdf... needs_ocr_elsewhere (0.3s)
[2127/3287] MASSY-Notice-of-Audited-Financial-Statements.pdf... needs_ocr_elsewhere (0.0s)
[2128/3287] MASSY-Notice-of-Change-in-Board-Composition.pdf... needs_ocr_elsewhere (0.0s)
[2129/3287] MASSY-Notice-of-Change-in-Senior-Officers-Appointment-of-EVP-and-Portfolio-CEO-Motors-Machines.pdf... needs_ocr_elsewhere (0.2s)
[2130/3287] MASSY-Notice-of-Change-in-Senior-Officers-Directors-President-Group-Chief-Executive-Officer.pdf... needs_ocr_elsewhere (0.4s)
  -- checkpoint saved (2130 jse records so far)
[2131/3287] MASSY-Notice-of-Change-in-Senior-Officers-EVP-Portfolio-CEO-Gas-Products-Appointment.pdf... needs_ocr_elsewhere (0.4s)
[2132/3287] MASSY-Notice-of-Change-in-Senior-Officers-EVP-Portfolio-CEO-GasProducts-Resignation.pdf... needs_ocr_elsewhere (0.2s)
[2133/3287] MASSY-Notice-of-Change-in-Senior-Officers-EVP-and-Portfolio-CEO-Motors-Machines.pdf... needs_ocr_elsewhere (0.0s)
[2134/3287] MASSY-Notice-of-Change-in-Senior-Officers-Executive-Vice-President-Deputy-Group-Chief-Executive-Officer.pdf... needs_ocr_elsewhere (0.0s)
[2135/3287] MASSY-Notice-of-Change-in-Senior-Officers-Group-Executive-Vice-President-Executive-Chairperson-Integrated-Retail-Portfolio.pdf... needs_ocr_elsewhere (0.2s)
[2136/3287] MASSY-Notice-of-Change-in-Senior-Officers-SVP-Group-People-Culture.pdf... needs_ocr_elsewhere (0.2s)
[2137/3287] MASSY-Notice-of-Delay-Audited-Consolidated-Financial-Statements-for-the-Financial-Year-Ended-September-30-2025.pdf... direct (0.1s)
[2138/3287] MASSY-Notice-of-Director-Appointment-Chloe-Bermudez.pdf... needs_ocr_elsewhere (0.2s)
[2139/3287] MASSY-Notice-of-Director-Resignation-Soraya-Khan.pdf... needs_ocr_elsewhere (0.2s)
[2140/3287] MASSY-Notice-of-Dividend-Declaration.pdf... needs_ocr_elsewhere (0.4s)
  -- checkpoint saved (2140 jse records so far)
[2141/3287] MASSY-Notice-of-Election-of-Chairman-Designate.pdf... needs_ocr_elsewhere (0.2s)
[2142/3287] MASSY-Notice-of-Final-Dividend-Declaration.pdf... needs_ocr_elsewhere (0.0s)
[2143/3287] MASSY-Notice-of-Final-Dividend-Payment.pdf... needs_ocr_elsewhere (0.5s)
[2144/3287] MASSY-Notice-of-Interim-Dividend-Declaration.pdf... needs_ocr_elsewhere (0.0s)
[2145/3287] MASSY-Notice-of-Partial-Final-Dividend-Payment.pdf... needs_ocr_elsewhere (0.7s)
[2146/3287] MASSY-Notice-of-in-Senior-Officer-Roles-Titles.pdf... needs_ocr_elsewhere (0.0s)
[2147/3287] MASSY-Retirement-of-Directors.pdf... needs_ocr_elsewhere (0.0s)
[2148/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-December-31-2024.pdf... needs_ocr_elsewhere (0.0s)
[2149/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-December-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2150/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2150 jse records so far)
[2151/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-June-30-2026.pdf... direct (0.4s)
[2152/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-March-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[2153/3287] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-period-ended-March-312025.pdf... needs_ocr_elsewhere (0.4s)
[2154/3287] MDA-Audited-Financials-December-31-2024-2.pdf... direct (0.4s)
[2155/3287] MDS-2024-Annual-Report-Symphony-for-Success.pdf... direct (21.4s)
[2156/3287] MDS-2025-Annual-Report-1.pdf... direct (13.7s)
[2157/3287] MDS-Group-2025-Audited-Financial-Statements-FY-Ended-March-31-2025-Amended.pdf... direct (8.9s)
[2158/3287] MDS-Notice-of-AGM.pdf... direct (0.3s)
[2159/3287] MDS-RELEASE-TO-SHAREHOLDERS-For-the-Period-Ended-December-2025.pdf... direct (1.2s)
[2160/3287] MDS-RELEASE-TO-SHAREHOLDERS-For-the-Period-Ended-September-30-2025.pdf... direct (1.0s)
  -- checkpoint saved (2160 jse records so far)
[2161/3287] MDS-RELEASE-TO-SHAREHOLDERS-for-the-Quarter-Ended-June-2025-Final.pdf... direct (0.9s)
[2162/3287] MEEG-Audited-Financial-Statements-Year-Ended-31-October-2024.pdf... direct (5.7s)
[2163/3287] MEEG-Directors-Holding-as-at-April-30-2025.pdf... direct (0.2s)
[2164/3287] MEEG-Directors-Holding-as-at-April-30-2026.pdf... needs_ocr_elsewhere (4.8s)
[2165/3287] MEEG-Directors-Holding-as-at-January-31-2025.pdf... direct (0.2s)
[2166/3287] MEEG-Directors-Holding-as-at-January-31-2026.pdf... needs_ocr_elsewhere (4.5s)
[2167/3287] MEEG-Directors-Holding-as-at-July-31-2025.pdf... direct (0.4s)
[2168/3287] MEEG-Directors-Holding-as-at-October-31-2024.pdf... direct (0.3s)
[2169/3287] MEEG-Directors-Holding-as-at-October-31-2025.pdf... direct (0.2s)
[2170/3287] MEEG-LIMITED-STOCKHOLERS-REPORT-OCTOBER-31-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2170 jse records so far)
[2171/3287] MEEG-Senior-Managers-Holding-as-at-April-30-2026.pdf... needs_ocr_elsewhere (1.4s)
[2172/3287] MEEG-TOP-10-Report-as-at-April-30-2025.pdf... direct (0.1s)
[2173/3287] MEEG-TOP-10-Report-as-at-January-31-2025.pdf... direct (0.3s)
[2174/3287] MEEG-TOP-10-Report-as-at-January-31-2026.pdf... direct (0.1s)
[2175/3287] MEEG-TOP-10-Report-as-at-October-31-2024.pdf... direct (0.1s)
[2176/3287] MEEG-Top-10-Report-as-at-July-31-2025.pdf... direct (0.1s)
[2177/3287] MEEG-Top-10-Shareholders-as-at-October-31-2025.pdf... direct (0.1s)
[2178/3287] MEEG-Unaudited-Results-Q1-%E2%80%93-Three-Months-Ended-January-31-2025-2.pdf... direct (0.9s)
[2179/3287] MEEG-Unaudited-Results-Q2-%E2%80%93-Six-Months-Ended-April-30-2025-1.pdf... direct (1.3s)
[2180/3287] MEEG-Unaudited-Results-Q3-%E2%80%93-Nine-Months-Ended-July-31-2024-Corrected.pdf... direct (0.7s)
  -- checkpoint saved (2180 jse records so far)
[2181/3287] MEEG-Unaudited-Results-Q3-%E2%80%93-Nine-Months-Ended-July-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2182/3287] MEEG-Unaudited-Results-Three-Months-Ended-January-31-2026.pdf... direct (1.2s)
[2183/3287] MEEG-Unaudited-ResultsQ2-Six-Months-Ended-April-30-2026.pdf... needs_ocr_elsewhere (0.0s)
[2184/3287] MFS-CAPITAL-PARTNERS-LTD-CORPORATE-GOVERNANCE-POLICY-APRIL-2025.pdf... direct (3.5s)
[2185/3287] MFS-Capital-Partners-AGM-Notice.pdf... direct (0.1s)
[2186/3287] MFS-Capital-Partners-Audited-Financial-Statements-30-June-2024.pdf... direct (8.4s)
[2187/3287] MFS-Capital-Partners-Audited-Financial-Statements-June-2025.pdf... direct (9.0s)
[2188/3287] MFS-Capital-Partners-Form-of-Proxy.pdf... direct (0.2s)
[2189/3287] MFS-Capital-Partners-Limited-Annual-Report-2024.pdf... direct (10.2s)
[2190/3287] MFS-Capital-Partners-Limited-Annual-Report-2025.pdf... direct (15.4s)
  -- checkpoint saved (2190 jse records so far)
[2191/3287] MFS-Capital-Partners-Limited-Financial-Revision-Note-to-Shareholders.pdf... direct (0.2s)
[2192/3287] MFS-Capital-Partners-Limited-MFS-Q4-Unaudited-Financial-Reports-June-30-2024.pdf... direct (4.2s)
[2193/3287] MFS-Capital-Partners-MFS-Q3-Unaudited-Financial-Reports-March-31-2024.pdf... direct (3.7s)
[2194/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-Quarter-Ending-30-June-2025.pdf... direct (2.8s)
[2195/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-Quarter-Ending-30th-September-2024.pdf... direct (2.6s)
[2196/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-Quarter-Ending-31-December-2024.pdf... direct (2.7s)
[2197/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-Quarter-Ending-31-March-2025-1.pdf... direct (2.7s)
[2198/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-includes-Top-Ten-Shareholders-Quarter-Ending-30-June-2026-Final.pdf... direct (3.1s)
[2199/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-includes-Top-Ten-Shareholders-Quarter-Ending-30-Sep-2025.pdf... direct (3.1s)
[2200/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-includes-Top-Ten-Shareholders-Quarter-Ending-31-Dec-2025.pdf... direct (3.4s)
  -- checkpoint saved (2200 jse records so far)
[2201/3287] MFS-Capital-Partners-MFS-Unaudited-Financial-Statements-includes-Top-Ten-Shareholders-Quarter-Ending-31-Mar-2026.pdf... direct (3.2s)
[2202/3287] MFS-Capital-Partners-MOU-Century-Business-Machines.pdf... direct (0.4s)
[2203/3287] MFS-Capital-Partners-Notice-of-Annual-General-Meeting.pdf... direct (0.1s)
[2204/3287] MFS-Capital-Partners-Press-Release-_-Micro-Financing-Solutions-Limited-undergoes-name-change.pdf... direct (0.2s)
[2205/3287] MFS-Capital-Partners-Press-Release-_Update-to-Shareholders-1.pdf... direct (0.2s)
[2206/3287] MFS-Capital-Partners-Proxy-Form.pdf... direct (0.1s)
[2207/3287] MFS-Capital-Partners-Top-Ten-Shareholders-Listing-30-June-2024.pdf... direct (0.2s)
[2208/3287] MFS-Capital-Partners-Top-Ten-Shareholders-Listing-30-June-2025.pdf... direct (0.1s)
[2209/3287] MFS-Capital-Partners-Top-Ten-Shareholders-Listing-30th-September-2024.pdf... direct (0.1s)
[2210/3287] MFS-Capital-Partners-Top-Ten-Shareholders-Listing-31-December-2024.pdf... direct (0.1s)
  -- checkpoint saved (2210 jse records so far)
[2211/3287] MFS-Capital-Partners-Top-Ten-Shareholders-Listing-31-March-2025.pdf... direct (0.1s)
[2212/3287] MFS-Notice-to-Shareholders.pdf... direct (1.0s)
[2213/3287] MGL-Annual-Report-2025-compressed.pdf... direct (17.2s)
[2214/3287] MGL-JSE-Quarterly-Report-June-2025.pdf... direct (1.7s)
[2215/3287] MGL-Letter-to-JSE-Notice-of-Dividend-Consideration-2025-04-14.pdf... direct (0.0s)
[2216/3287] MGL-Notice-of-Dividend-Payment-May-30-2025-signed.pdf... direct (0.0s)
[2217/3287] MGL-REPORT-FINAL-2024.pdf... direct (15.9s)
[2218/3287] MGL-SUBSIDIARY-BOARD-AND-EXECUTIVE-MANAGEMENT-CHANGES-FINAL.pdf... direct (0.2s)
[2219/3287] MGL-Shareholders-Cover-Letter-2025-1.pdf... direct (0.0s)
[2220/3287] MGL-Shareholders-Cover-Letter.pdf... direct (0.0s)
  -- checkpoint saved (2220 jse records so far)
[2221/3287] MGL-Unaudited-Financial-Statements-March-31-2025.pdf... direct (1.5s)
[2222/3287] MIL-Annual-Report-2025-compressed.pdf... direct (11.8s)
[2223/3287] MIL-Annual-Report-Year-Ended-December-31-2024.pdf... direct (17.3s)
[2224/3287] MIL-Extension-Notice-JSE.pdf... direct (0.0s)
[2225/3287] MJE-ANNUAL-REPORT-2025-compressed.pdf... direct (7.6s)
[2226/3287] MJE-Prospectus.pdf... direct (7.1s)
[2227/3287] MPCCEL-2024-Annual-Report_executed-2.pdf... direct (83.6s)
    ^ SLOW FILE -- MPCCEL-2024-Annual-Report_executed-2.pdf took 83.6s
[2228/3287] MPCCEL-Unaudited-Financial-Statements-June-30-2026.pdf... needs_ocr_elsewhere (0.0s)
[2229/3287] MPCCEL_Annual_Report_2025.pdf... direct (69.7s)
    ^ SLOW FILE -- MPCCEL_Annual_Report_2025.pdf took 69.7s
[2230/3287] MVTurks_Annual-Report-2024.pdf... direct (10.6s)
  -- checkpoint saved (2230 jse records so far)
[2231/3287] MVTurks_Annual-Report-2025.pdf... direct (8.3s)
[2232/3287] MailPac-Annual-Report-2024.pdf... direct (31.6s)
    ^ SLOW FILE -- MailPac-Annual-Report-2024.pdf took 31.6s
[2233/3287] Mailpac-Group-Limited-2024-Audited-Financial-Statements.pdf... direct (7.2s)
[2234/3287] Mailpac-Group-Limited-2025-Financial-Statements_Finalised.pdf... direct (9.4s)
[2235/3287] Mailpac-Group-Limited-Q3-2024-Report-for-JSE.pdf... direct (2.2s)
[2236/3287] Mailpac-Group-Quarterly-Report-December-2025.pdf... direct (1.8s)
[2237/3287] Mailpac-Group-Quarterly-Report-March-31-2026-1.pdf... direct (1.8s)
[2238/3287] Mailpac-Quarterly-JSE-Report-June-30-2026.pdf... direct (2.1s)
[2239/3287] Mailpac-Quarterly-Report-September-30-2025.pdf... direct (2.1s)
[2240/3287] Mailpac-Quarterly-Report-for-the-quarter-ended-December-31-2024.pdf... direct (1.5s)
  -- checkpoint saved (2240 jse records so far)
[2241/3287] Main-Event-Entertainment-Group-Annual-Report-2025.pdf... direct (9.8s)
[2242/3287] Management-Proxy-Circular-2024-1.pdf... direct (0.1s)
[2243/3287] Management-Proxy-Circular-2025.pdf... direct (0.1s)
[2244/3287] March-2025-Publication-final-002.pdf... direct (1.5s)
[2245/3287] March_2025_analysis.pdf... direct (2.5s)
[2246/3287] March_2026_analysis.pdf... direct (2.2s)
[2247/3287] Margaritaville-Turks-Ltd-Audited-Financial-Statements-at-May-31-2024.pdf... direct (3.7s)
[2248/3287] Margaritaville-Turks-Ltd-Audited-Financial-Statements-at-May-31-2025.pdf... direct (3.9s)
[2249/3287] Margaritaville-Turks-Ltd-Top-10-and-Directors-Shareholdings-at-May-31-2024.pdf... direct (0.1s)
[2250/3287] Margaritaville-Turks-Ltd-Top-10-and-Directors-Shareholdings-at-May-31-2025.pdf... direct (0.1s)
  -- checkpoint saved (2250 jse records so far)
[2251/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q1-2025-dated-August-31-2024-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.5s)
[2252/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q1-2026-dated-August-31_-2025-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.5s)
[2253/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q2-2025-dated-November-30-2024-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.8s)
[2254/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q2-2026-dated-November-30_-2025-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.7s)
[2255/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q3-2025-dated-February-28_-2025-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.7s)

[2256/3287] Margaritaville-Turks-MTL-Un-audited-Financial-Statement-for-Q3-2026-dated-February-28_-2026-and-Top-Ten-and-Directors-Shareholdings.pdf... direct (0.6s)
[2257/3287] Mark-Thompson-Resigns-as-CEO-of-Advantage-General-Insurance-Company.pdf... direct (0.2s)
[2258/3287] Massy-Holdings-Ltd.-2024-Annual-Report.pdf... direct (42.4s)
    ^ SLOW FILE -- Massy-Holdings-Ltd.-2024-Annual-Report.pdf took 42.4s
[2259/3287] Massy-Holdings-Ltd.-Annual-Report-2025.pdf... direct (40.6s)
    ^ SLOW FILE -- Massy-Holdings-Ltd.-Annual-Report-2025.pdf took 40.6s
[2260/3287] Material-change-notice-to-JSE-FINAL.pdf... direct (0.4s)
  -- checkpoint saved (2260 jse records so far)
[2261/3287] May_2025_analysis.pdf... direct (3.1s)
[2262/3287] May_2026_analysis.pdf... direct (2.3s)
[2263/3287] Mayberry-Basis-of-Allotment.pdf... direct (0.1s)
[2264/3287] Mayberry-Bond-Prospetus-2024.pdf... direct (8.3s)
[2265/3287] Mayberry-Group-Limited-MGL-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (12.3s)
[2266/3287] Mayberry-Group-Limited-MGL-Unaudited-Financial-Results-for-the-Nine-Months-ended-September-30-2024.pdf... direct (8.2s)
[2267/3287] Mayberry-Group-Limited-MGL-Unaudited-Financial-Results-for-the-Nine-Months-ended-September-30-2025.pdf... direct (9.0s)
[2268/3287] Mayberry-Group-Limited-MGL-Unaudited-Financial-Results-for-the-Six-Months-ended-June-30-2025.pdf... direct (7.8s)
[2269/3287] Mayberry-Group-Limited-MGL-Unaudited-Financial-Results-for-the-Three-Months-Ended_March-31-2025.pdf... direct (25.7s)
[2270/3287] Mayberry-Group-Limited-Results-Highlights-For-the-Year-Ended-December-31-2025_Audited.pdf... direct (3.6s)
  -- checkpoint saved (2270 jse records so far)
[2271/3287] Mayberry-Group-Limited-Unaudited-Financial-Results-for-the-Six-Months-Ended-June-30-2026.pdf... direct (2.8s)
[2272/3287] Mayberry-Group-Limited_Financial-Statements_2025_Final.pdf... direct (11.7s)
[2273/3287] Mayberry-Group-Ltd-Unaudited-Financial-Results-for-the-Three-Months-ended-March-31-2026.pdf... direct (6.7s)
[2274/3287] Mayberry-Investments-Limited-MIL-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (10.1s)
[2275/3287] Mayberry-Investments-Limited-Results-Highlights-for-the-Year-Ended-Dec.-31-2025_Audited.pdf... direct (0.7s)
[2276/3287] Mayberry-Investments-Limited-Unaudited-Financial-Results-for-the-Nine-Months-Ended-Sept.-30-2025Ame.pdf... direct (2.2s)
[2277/3287] Mayberry-Investments-Limited-Unaudited-Financial-Results-for-the-Nine-Months-Ended-September-30-2024.pdf... direct (1.7s)
[2278/3287] Mayberry-Investments-Limited-Unaudited-Financial-Results-for-the-Six-Months-Ended-June-30-2026.pdf... direct (2.3s)
[2279/3287] Mayberry-Investments-Limited-Unaudited-Financial-Results-for-the-Three-Months-Ended-March-31-2026.p.pdf... direct (1.7s)
[2280/3287] Mayberry-Investments-Limited_Financial-Statements_2025_Final.pdf... direct (9.6s)
  -- checkpoint saved (2280 jse records so far)
[2281/3287] Mayberry-Investments-Ltd-Unaudited-Financial-Results-for-the-Three-Months-Ended-March-31-2025.pdf... direct (1.1s)
[2282/3287] Mayberry-Investments-Ltd-_-Notice-of-Amendment-for-2025-Q3-Interim-Results.pdf... direct (0.9s)
[2283/3287] Mayberry-Investments-Ltd-_Unaudited-Results-for-the-Six-Months-Ended-June-30-2025.pdf... direct (1.8s)
[2284/3287] Mayberry-Jamaican-Equities-Limited-Audited-Financial-Statements-for-the-Year-Ended-Dec.-31-2025.pdf... direct (4.7s)
[2285/3287] Mayberry-Jamaican-Equities-Limited-Extension-Notice-2025-Annual-Report.pdf... direct (0.1s)
[2286/3287] Mayberry-Jamaican-Equities-Limited-MJE-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (8.0s)
[2287/3287] Mayberry-Jamaican-Equities-Limited-MJEL-Unaudited-Financial-Results-for-the-Nine-Months-Ended-September-30-2024-_JMD.pdf... direct (7.6s)
[2288/3287] Mayberry-Jamaican-Equities-Limited-MJEL-Unaudited-Financial-Results-for-the-Nine-Months-Ended-September-30-2024-_USD.pdf... direct (7.8s)
[2289/3287] Mayberry-Jamaican-Equities-Ltd-2025-Audited-Results-Highlights-%E2%80%93-USD.pdf... direct (4.2s)
[2290/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Nine-Months-ended-Sept-30-2025-JMD.pdf... direct (7.5s)
  -- checkpoint saved (2290 jse records so far)
[2291/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Nine-Months-ended-Sept-30-2025-USD.pdf... direct (7.4s)
[2292/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Six-Months-Ended-June-30-2026_JMD.pdf... direct (2.4s)
[2293/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Six-Months-Ended-June-30-2026_USD.pdf... direct (2.2s)
[2294/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Six-Months-ended-Jun-30-2025JMD.pdf... direct (7.4s)
[2295/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Six-Months-ended-Jun-30-2025USD.pdf... direct (7.4s)
[2296/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Three-Months-Ended-March-31-2026_JMD.pdf... direct (6.4s)
[2297/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Three-Months-Ended-March-31-2026_USD.pdf... direct (6.3s)
[2298/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Three-Months-ended-March-31-2025JMD.pdf... direct (6.3s)
[2299/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Three-Months-ended-March-31-2025USD.pdf... direct (6.5s)
[2300/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Twelve-Months-Ended-Dec.-31-2025-JMD.pdf... direct (7.5s)
  -- checkpoint saved (2300 jse records so far)
[2301/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Twelve-Months-Ended-Dec.-31-2025-USD.pdf... direct (7.6s)
[2302/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Twelve-Months-ended_December-31-2024-JMD.pdf... direct (7.5s)
[2303/3287] Mayberry-Jamaican-Equities-MJE-Unaudited-Financial-Results-for-the-Twelve-Months-ended_December-31-2024-USD.pdf... direct (7.9s)
[2304/3287] Mayberry-Tranche-III-Prospectus-extra-comp.pdf... direct (7.9s)
[2305/3287] Media-Release-JPS-Welcomes-Lance-Becca-as-New-JPS-Chief-Operating-Officer-FINAL.pdf... direct (0.2s)
[2306/3287] Methods-of-Payment.pdf... direct (0.0s)
[2307/3287] Microsoft-Word-Knutsford-Express-3RD-Quarter-JSE-ReportF-28FEB25.doc.pdf... direct (1.7s)
[2308/3287] NCB-Board-Announces-Leadership-Transition-Press-Release-January-2026.pdf... direct (0.1s)
[2309/3287] NCB-Financial-Group-Limited-Audited-Financial-statements-2025.pdf... direct (27.9s)
[2310/3287] NCB-Financial-Group-Limited-NCBFG-Audited-Financial-Statements-for-Year-Ended-September-30-2024-3.pdf... direct (57.7s)
    ^ SLOW FILE -- NCB-Financial-Group-Limited-NCBFG-Audited-Financial-Statements-for-Year-Ended-September-30-2024-3.pdf took 57.7s
  -- checkpoint saved (2310 jse records so far)
[2311/3287] NCB-Financial-Group-Limited-NCBFG-Financial-Results-Year-Ended-September-30-2024.pdf... direct (4.8s)
[2312/3287] NCB-Financial-Group-Limited-NCBFG-Financial-Results-Year-Ended-September-30-2025.pdf... direct (13.4s)
[2313/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Nine-Months-Ended-June-30-2025.pdf... direct (13.1s)
[2314/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Nine-Months-Ended-June-30-2026-.pdf... direct (7.4s)
[2315/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Quarter-Ended-December-31-2024-1.pdf... direct (11.8s)
[2316/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Quarter-Ended-December-31-2025.pdf... direct (6.6s)
[2317/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Six-Months-Ended-March-31-2025-1.pdf... direct (12.8s)
[2318/3287] NCB-Financial-Group-Limited-NCBFG-Unaudited-Financial-Results-Six-Months-Ended-March-31-2026.pdf... direct (7.3s)
[2319/3287] NCB-Financial-Group-Limited-Release-SP-Ratings-Oct-6_2025-3.pdf... direct (0.5s)
[2320/3287] NCBFG-AR-2025-Proxy-Form.pdf... direct (0.2s)
  -- checkpoint saved (2320 jse records so far)
[2321/3287] NCBFG-AR-2025_Web-7.pdf... direct (221.4s)
    ^ SLOW FILE -- NCBFG-AR-2025_Web-7.pdf took 221.4s

[2322/3287] NCBFG-Annual-Report-2024-2.pdf... direct (84.8s)
    ^ SLOW FILE -- NCBFG-Annual-Report-2024-2.pdf took 84.8s
[2323/3287] NCBFG-Annual-Report-2024-3.pdf... direct (80.3s)
    ^ SLOW FILE -- NCBFG-Annual-Report-2024-3.pdf took 80.3s
[2324/3287] NCBFG-Investor-Release-2025-Electronic-Annual-Report-AGM-Registration-and-Arrangements.pdf... direct (0.3s)
[2325/3287] NCBFG-Investor-Release-2026-Board-Meeting-Dates-1.pdf... direct (0.1s)
[2326/3287] NCBFG-Investor-Release-Annual-Report-AGM-Registration-and-Arrangements.pdf... direct (0.4s)
[2327/3287] NCBFG-Investor-Release-NCBMBTT-GIL-transaction-and-GHL-Restructuring-1May2026.pdf... direct (0.2s)
[2328/3287] NCBFG-PROXY-FORM.pdf... direct (0.1s)
[2329/3287] NCBFG-Press-Release-Internal-Reorganisation-Final.pdf... direct (0.2s)
[2330/3287] NCBFG-Release-Audited-Financial-Statements-FY2024_Final.pdf... direct (0.9s)
  -- checkpoint saved (2330 jse records so far)
[2331/3287] NCBFG-Release-Completes-Reorganisation-of-Pension-Business.pdf... direct (0.1s)
[2332/3287] NCBFG-Release-Director-Appointment-NCBFG-Dec-8_2025-Approved.pdf... direct (0.1s)
[2333/3287] NCBFG-Release_Fitch-Rating-Affirmation-and-Removal-of-RWN.pdf... direct (0.1s)
[2334/3287] NOTICE-2024-ANNUAL-GENERAL-MEETING-1.pdf... needs_ocr_elsewhere (1.6s)
[2335/3287] NOTICE-OF-AGM.pdf... direct (2.8s)
[2336/3287] NOTICE-OF-ANNUAL-GENERAL-MEETING-2026.pdf... direct (0.1s)
[2337/3287] NOTICE-OF-ANNUAL-GENERAL-MEETING-revised.pdf... direct (0.1s)
[2338/3287] NOTICE-OF-ANNUAL-GENERAL-MEETING.pdf... direct (0.1s)
[2339/3287] NOTICE-OF-CHANGE-COMPANY-SECRETARY.pdf... needs_ocr_elsewhere (0.0s)
[2340/3287] NOTICE-OF-DEALINGS.pdf... direct (0.0s)
  -- checkpoint saved (2340 jse records so far)
[2341/3287] NOTICE-OF-DIVIDEND-RECOMMENDATION-CCC-6-10-2026-pdf.pdf... direct (0.0s)
[2342/3287] NOTICE-OF-EGM-2026.pdf... direct (0.4s)
[2343/3287] NOTICE-OF-MEETING-2024-4.pdf... direct (0.2s)
[2344/3287] NOTICE-OF-RESIGNATION-BLONDELL-WALKER-1.pdf... direct (0.0s)
[2345/3287] NOTICE-TO-JSE.-DIVIDEND-CONSIDERATION.pdf... needs_ocr_elsewhere (0.0s)
[2346/3287] NOTICE-TO-JSE.pdf... direct (0.1s)
[2347/3287] NOTICE-TO-STOCK-EXCHANGE.pdf... needs_ocr_elsewhere (0.0s)
[2348/3287] NOTICE.APPT-OF-CO.-SECRETARY.-01-OCT-2024reviseddocx.pdf... direct (0.1s)
[2349/3287] NOTIFICATION-OF-CHANGE-OF-AUDITOR.pdf... needs_ocr_elsewhere (0.0s)
[2350/3287] NROCC-Upsize-Notice-Final.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2350 jse records so far)
[2351/3287] NROCCs-OFS-Prospectus-Transjamaican-Highway.pdf... direct (7.1s)
[2352/3287] News-Release-Jamaica-Stock-Exchange-Suspends-Trading-in-the-Shares-of-Portland-JSX-Limited-_.pdf... direct (0.1s)
[2353/3287] News-Release-Suspension-of-Trading-in-DTL-Ordinary-Shares.pdf... direct (0.1s)
[2354/3287] Nine-Months-Q3-INDIES-PHARMA-Inhouse-Financials_31-July-2024.pdf... direct (2.3s)
[2355/3287] Notice-AGM-Everything-Fresh-2024.pdf... direct (0.2s)
[2356/3287] Notice-AGM-Everything-Fresh-2025.pdf... direct (0.2s)
[2357/3287] Notice-AGM-Mailpac-2024-.pdf... direct (0.7s)
[2358/3287] Notice-AGM-Mailpac-2025-1.pdf... direct (0.2s)
[2359/3287] Notice-CPJ-Announces-an-increase-in-Ownership-Stake-by-ASBH.pdf... direct (0.1s)
[2360/3287] Notice-Delay-in-Filing-Audited-Financial-Statements-Year-Ended-March-31-2025.pdf... direct (0.0s)
  -- checkpoint saved (2360 jse records so far)
[2361/3287] Notice-March-4-2026.pdf... direct (0.1s)
[2362/3287] Notice-advising-of-ASBH-Listing-on-TT-Stock-Exchange-2.pdf... direct (0.1s)
[2363/3287] Notice-and-Proxy-Form.pdf... needs_ocr_elsewhere (0.0s)
[2364/3287] Notice-and-Proxy-Form_CPJ_AGM-2025.pdf... direct (0.2s)
[2365/3287] Notice-of-AGM-2025.pdf... direct (0.3s)
[2366/3287] Notice-of-AGM-2025_web-with-special-instructions.pdf... direct (0.4s)
[2367/3287] Notice-of-AGM-CPJs-2.11.2025.pdf... direct (0.0s)
[2368/3287] Notice-of-AGM-Edufocal-Amended-21.2.25.pdf... direct (0.2s)
[2369/3287] Notice-of-AGM-Proxy-2025.pdf... direct (0.2s)
[2370/3287] Notice-of-AGM-and-Form-of-Proxy.pdf... direct (0.4s)
  -- checkpoint saved (2370 jse records so far)
[2371/3287] Notice-of-AGM.pdf... direct (0.3s)
[2372/3287] Notice-of-Annual-General-Meeting-AUG-13-2026_-FINAL-PDF.pdf... direct (0.4s)
[2373/3287] Notice-of-Annual-General-Meeting-Final.docx-11.pdf... direct (0.8s)
[2374/3287] Notice-of-Annual-General-Meeting.pdf... needs_ocr_elsewhere (1.7s)
[2375/3287] Notice-of-Annual-General-Meeting_2026.pdf... direct (0.2s)
[2376/3287] Notice-of-Annual-Meeting-2025-including-Notes-and-Guidelines-for-Pre-Registration.pdf... direct (0.9s)
[2377/3287] Notice-of-Annual-Meeting-including-Notes-and-Guidelines-for-Pre-registration-2024.pdf... direct (0.5s)
[2378/3287] Notice-of-CFO-Resignation.pdf... direct (0.1s)
[2379/3287] Notice-of-EGM-and-Resolutions-EduFocal.pdf... direct (0.1s)
[2380/3287] Notice-of-Extension-of-Closing-Date.pdf... needs_ocr_elsewhere (5.1s)
  -- checkpoint saved (2380 jse records so far)
[2381/3287] Notice-of-MEETING-to-Consider-Scheme-Class-B.pdf... direct (0.4s)
[2382/3287] Notice-of-MEETING-to-Consider-Scheme-Class-C.pdf... direct (0.6s)
[2383/3287] Notice-of-Meeting-for-BARITA-opt.pdf... direct (0.2s)
[2384/3287] Notice-of-Revised-AGM-Notice-FosRich.pdf... direct (0.0s)
[2385/3287] Notice-of-Takeover-Offer-for-tTech-Shares-13-Dec-2024.pdf... direct (0.2s)
[2386/3287] Notice-of-USFDA-Approval-for-Indies-Pharmas-Drug_JSE-Sept-2024.pdf... direct (0.4s)
[2387/3287] Notice-of-change-of-time-and-venue-Annual-General-Meeting.pdf... needs_ocr_elsewhere (0.0s)
[2388/3287] Notice-of-dealing-to-JSE.pdf... direct (0.0s)
[2389/3287] Notice-of-the-AGM-2025-138SL.pdf... direct (0.2s)
[2390/3287] Notice-of-the-meeting-of-the-Board-of-Directors-in-furtherance-of-Rule-410-.pdf... direct (0.0s)
  -- checkpoint saved (2390 jse records so far)
[2391/3287] Notice-of-the-meeting-of-the-Board-of-Directors-in-furtherance-of-Rule-410-2026.pdf... direct (0.0s)
[2392/3287] Notice-to-JSE-on-Appointment-of-Mentor.pdf... direct (0.0s)
[2393/3287] Notice-to-Shareholders-24-Dec-2024.pdf... direct (0.1s)
[2394/3287] Notice-to-Shareholders-Dividend-Paid-in-USD.pdf... direct (0.1s)
[2395/3287] Notice-to-Shareholders.pdf... needs_ocr_elsewhere (0.0s)
[2396/3287] Notice-to-the-JSE-re-Ministers-Letter-giving-notice-of-Acquisition-of-Licenced-Business.pdf... direct (0.0s)
[2397/3287] Notice-to-the-Jamaica-Stock-Exchange-Kintyre-Holdings-LOI-with-MVL-3-1.pdf... direct (0.3s)
[2398/3287] Notice-to-the-Shareholders-of-RAWILL-Change-of-Management-Financial-Controller.pdf... direct (0.0s)
[2399/3287] Notice-to-the-Shareholders-of-RAWL-Change-of-Management.pdf... direct (0.0s)
[2400/3287] Notice_-JSE_RPL-Senior-Officer-Trading-in-Shares_-Aug-192025.pdf... direct (0.1s)
  -- checkpoint saved (2400 jse records so far)
[2401/3287] Notice_-JSE_RPL-Senior-Officer-Trading-in-Shares_-Feb-11-122025.pdf... direct (0.1s)
[2402/3287] Notice_-JSE_RPL-Senior-Officer-Trading-in-Shares_-Feb-12-202025.pdf... direct (0.1s)
[2403/3287] Notice_-JSE_RPL-Senior-Officer-Trading-in-Shares_Dec-2025-Jan-2026-1.pdf... direct (0.2s)
[2404/3287] Notice_PP.pdf... direct (0.1s)
[2405/3287] Notice_SE_PP_Material_Change.pdf... direct (0.1s)
[2406/3287] Notice_early-maturity.pdf... direct (0.1s)
[2407/3287] Notification-of-Board-Changes.pdf... direct (0.1s)
[2408/3287] November_2024_analysis-1.pdf... direct (2.5s)
[2409/3287] November_2025_analysis.pdf... direct (2.4s)
[2410/3287] OFFICERS-Q1-1.pdf... direct (0.0s)
  -- checkpoint saved (2410 jse records so far)
[2411/3287] OMNI-AGM-NOTICE-2024.pdf... direct (0.2s)
[2412/3287] OMNI-AGM-NOTICE.pdf... direct (0.2s)
[2413/3287] OMNI-IND-PROXY-FORM.pdf... direct (0.1s)
[2414/3287] OMNI-INDUSTRIES-FORM-OF-PROXY.pdf... direct (0.2s)
[2415/3287] OMNI-Industries-Delayed-Annual-Report-Notice.pdf... direct (0.1s)
[2416/3287] OMNI-Industries-Limited-Audited-Financial-Statements-for-the-year-31-December-2025.pdf... direct (5.7s)
[2417/3287] OMNI-Q1-2026-Unaudited-Financials-Statements-Final.pdf... direct (1.1s)
[2418/3287] OMNI-Unaudited-Financial-Statement-for-Q2-Ended-June-30-2024-Corrected.pdf... direct (1.3s)
[2419/3287] ONE-3rd-Quarter-Unaudited-Financial-Statements-31-May-2026-1.pdf... direct (3.6s)

[2420/3287] ONE-Annual-Report-31-August-2025.pdf... direct (16.0s)
  -- checkpoint saved (2420 jse records so far)
[2421/3287] ONE-Audited-Financial-Statement-Year-Ended-31-August-2024-1.pdf... direct (7.0s)
[2422/3287] ONE-Audited-Financial-Statements-Year-Ended-31st-Aug-2025.pdf... direct (5.2s)
[2423/3287] ONE-Second-Quarter-Report-28-February-2025-1.pdf... direct (3.2s)
[2424/3287] ONE-Top-Ten-Shareholders-Year-Ended-Aug-31-2025.pdf... direct (0.1s)
[2425/3287] ONE-Top-Ten-Shareholders-as-at-August-31-2024-1.pdf... direct (0.1s)
[2426/3287] ONE-Unaudited-2nd-Quarter-Report-28-February-2026-1.pdf... direct (3.2s)
[2427/3287] ONE-Unaudited-3rd-Quarter-Report-Ended-31-May-2025.pdf... direct (2.0s)
[2428/3287] ONE-Unaudited-First-Quarter-Report-30-November-2025.pdf... direct (1.8s)
[2429/3287] October_2024_analysis.pdf... direct (2.3s)
[2430/3287] October_2025_analysis.pdf... direct (2.5s)
  -- checkpoint saved (2430 jse records so far)
[2431/3287] Offer-and-Take-Over-Bid-Circular-Seprod-Limited.pdf... direct (6.1s)
[2432/3287] One-Great-Studio-Appoints-Global-Marketing-Strategist-Peter-Lloyd-to-Its-Board.pdf... direct (0.5s)
[2433/3287] PAL-ANNUAL-REPORT-2024.pdf... direct (15.1s)
[2434/3287] PALACE-ANNUAL-REPORT-2025.pdf... direct (11.6s)
[2435/3287] PBS-JSE-Disclosure-Notice-11-6-24.pdf... direct (0.0s)
[2436/3287] PDF-of-JSE-INTERIM-REPORT-SEPT-24.pdf... direct (0.1s)
[2437/3287] PGL-Consolidated-FS-2025-Final.pdf... direct (13.0s)
[2438/3287] PGL-Magazine-DEC2024-final.pdf... direct (1.6s)
[2439/3287] PGL-Magazine-SEPT2024.pdf... direct (2.1s)
[2440/3287] PGL-Top-10-Shareholders-as-at-December-31-2024.pdf... direct (0.1s)
  -- checkpoint saved (2440 jse records so far)
[2441/3287] PGL-Top-10-Shareholders-as-at-September-30-2024.pdf... direct (0.1s)
[2442/3287] PIL-Top-10-Shareholders-as-at-June-30-2026.pdf... direct (0.3s)
[2443/3287] PJAM-Pan-Jamaica-Group-JSE-Release-Q3-2024.pdf... direct (3.0s)
[2444/3287] PJGL-JSE-Release-Q1_2025.pdf... direct (2.5s)
[2445/3287] PJGL-JSE-Release-Q1_2026-Final.pdf... direct (2.3s)
[2446/3287] PJGL-JSE-Release-Q2_2025.pdf... direct (2.5s)
[2447/3287] PJGL-JSE-Release-Q2_2026.pdf... direct (6.3s)
[2448/3287] PJGL-JSE-Release-Q3_2025.pdf... direct (2.8s)
[2449/3287] PJGL-JSE-Release-Q4-Financial-Extracts-amended-v2.pdf... direct (3.7s)
[2450/3287] PJGL-JSE-Release-Q4_2025-signed.pdf... direct (2.7s)
  -- checkpoint saved (2450 jse records so far)
[2451/3287] PJX-2025-Annual-Report.pdf... direct (7.0s)
[2452/3287] PJX-AGM-Advisory.pdf... direct (0.1s)
[2453/3287] PRESS-RELEASE-23JAN2025-FTNA.pdf... direct (0.6s)
[2454/3287] PRESS-RELEASE-SGJ-Announces-Organisational-Changes-to-Support-Business-Growth-003.pdf... direct (0.1s)
[2455/3287] PRESS-RELEASE_BOJ-Approves-Two-New-Directors-for-Access-Financial-Board-Feb-2026-1.pdf... direct (0.2s)
[2456/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-CHANGE-OF-AUDITORS.pdf... direct (0.1s)
[2457/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-COMMON-DIVIDEND-CONSIDERATION-JANUARY-7-2026.pdf... direct (0.1s)
[2458/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-COMMON-DIVIDEND-DECEMBER-11-2025a.pdf... direct (0.1s)
[2459/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-COMMON-DIVIDEND-JANUARY-14-2026.pdf... direct (0.2s)
[2460/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-Q1-2025-1.pdf... direct (0.1s)
  -- checkpoint saved (2460 jse records so far)
[2461/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-Q2-2025.pdf... direct (0.1s)
[2462/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-Q3-2025.pdf... direct (0.1s)
[2463/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-Q4-2025.pdf... direct (0.2s)
[2464/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DECLARATION-PERPETUAL-PREF-DIVIDEND-q3-2024.pdf... direct (0.1s)
[2465/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DIVIDEND-CONSIDERATION-APRIL-30-2025.pdf... direct (0.2s)
[2466/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-DIVIDEND-CONSIDERATION-AUGUST-4-2025.pdf... direct (0.1s)
[2467/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-INTERIM-REPORT-Q1-2026-Unaudited-1.pdf... direct (0.6s)
[2468/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-Interim-Report-Q2-2026.pdf... direct (1.1s)
[2469/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-PERPETUAL-PREFERENCE-SHARE-DIVIDEND-CONSIDERATION-FEBRUARY-20-2026.pdf... direct (0.1s)
[2470/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-PERPETUAL-PREFERENCE-SHARE-DIVIDEND-CONSIDERATION-MAY-6-2026.pdf... direct (0.1s)
  -- checkpoint saved (2470 jse records so far)
[2471/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-PERPETUAL-PREFERENCE-SHARE-DIVIDEND-DECLARATION-FEBRUARY-27-2026.pdf... direct (0.2s)
[2472/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-PERPETUAL-PREFERENCE-SHARE-DIVIDEND-DECLARATION-MAY-13-2026.pdf... direct (0.2s)
[2473/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-Press-release-03072026.pdf... direct (0.1s)
[2474/3287] PRODUCTIVE-BUSINESS-SOLUTIONS-LIMITED-PBS-RESIGNATION-OF-DIRECTOR.pdf... direct (0.1s)
[2475/3287] PROFILE-Stephanie-Ewbank-June-2026.pdf... direct (0.1s)
[2476/3287] PROFILE-Yaniece-Gentles-June-2026.pdf... direct (0.1s)
[2477/3287] PROVEN-Group-Unaudited-Financial-Statements-for-period-ended-December-31-2025.pdf... direct (2.1s)
[2478/3287] PROVEN-Group-Unaudited-Financial-Statements-for-period-ended-June-30-2025.pdf... direct (1.6s)
[2479/3287] PROVEN-Group-Unaudited-Financial-Statements-for-period-ended-June-30-2026_.pdf... direct (2.4s)
[2480/3287] PROVEN-Group-Unaudited-Financial-Statements-for-period-ended-September-30-2025.pdf... direct (1.8s)
  -- checkpoint saved (2480 jse records so far)
[2481/3287] PROVEN-Unaudited-Financial-Statements-for-year-ended-March-2025.pdf... direct (1.6s)
[2482/3287] PROVEN_2024-Annual-Report-.pdf... direct (19.4s)
[2483/3287] PROVEN_2025-Annual-Report.pdf... direct (22.5s)
[2484/3287] PROXY-FORM-2025-1.pdf... direct (0.1s)
[2485/3287] PROXY-FORM.pdf... direct (0.2s)
[2486/3287] PTJL-Second-Quarter-ended-November-30-2024-Unaudited-Results.pdf... needs_ocr_elsewhere (0.0s)
[2487/3287] PTJL-Second-Quarter-ended-November-30-2025-Unaudited-Results.pdf... needs_ocr_elsewhere (0.0s)
[2488/3287] PTL-Ordinary-Top-10-%40-November-30-2024.pdf... direct (0.1s)
[2489/3287] PULS-Unaudited-Financial-Statements-Quarter-Ended-March-31-2025.pdf... direct (0.4s)
[2490/3287] PULSE-Director-Shareholdings-at-30-JUNE-2024.xls-Compatibility-Mode-1.pdf... direct (0.0s)
  -- checkpoint saved (2490 jse records so far)
[2491/3287] PULSE-INVESTMENTS-ANNUAL-REPORT-2024.pdf... direct (3.3s)
[2492/3287] PULSE-INVESTMENTS-LIMITED-Annual-Report-2025.pdf... direct (3.8s)
[2493/3287] PULSE-TOP-10-at-30-JUNE-2024-2.pdf... direct (0.1s)
[2494/3287] Palace-Amusement-Company-PAL-ANNUAL-REPORT-2024-LATE-FILING.pdf... direct (0.0s)
[2495/3287] Pan-Jamaica-Group-AGM-Notice-2025.pdf... direct (0.2s)
[2496/3287] Pan-Jamaica-Group-Annual-Report-2024-amended.pdf... direct (54.0s)
    ^ SLOW FILE -- Pan-Jamaica-Group-Annual-Report-2024-amended.pdf took 54.0s
[2497/3287] Pan-Jamaica-Group-Annual-Report-2025.pdf... direct (40.9s)
    ^ SLOW FILE -- Pan-Jamaica-Group-Annual-Report-2025.pdf took 40.9s
[2498/3287] Pan-Jamaica-Group-Limited_Financial-Statements_2024_Final-pdf-1.pdf... direct (21.7s)
[2499/3287] Pan-Jamaica-Group-Limited_Financial-Statements_2025_Final-.pdf... direct (19.6s)
[2500/3287] Pan-Jamaica-Group-PJAM-JSE-Release-March-4-2025-2.pdf... direct (0.2s)
  -- checkpoint saved (2500 jse records so far)
[2501/3287] Pan-Jamaica-Group-Proxy-Form-2025.pdf... direct (0.1s)
[2502/3287] Paramount-Tading-Jamaica-Limited-Proxy-Form-2025.pdf... direct (0.3s)
[2503/3287] Paramount-Trading-Jamaica-Limited-Annual-Report-2023-2024.pdf... direct (4.6s)
[2504/3287] Paramount-Trading-Jamaica-Limited-Annual-Report-2025.pdf... direct (4.5s)
[2505/3287] Paramount-Trading-Jamaica-Limited-Audited-Financial-Statements-and-Reports-for-the-Financial-Year-ended-May-31-2025-1.pdf... direct (7.3s)
[2506/3287] Paramount-Trading-Jamaica-Limited-Audited-Financial-Statements-and-Reports-for-the-Financial-Year-ended-May-31-2026.pdf... direct (8.9s)
[2507/3287] Paramount-Trading-Jamaica-Limited-Notice-of-Annual-General-Meeting-2025.pdf... direct (1.1s)
[2508/3287] Paramount-Trading-Jamaica-Limited-Top-Ten-10-Stockholders-Directors-and-Senior-Officers-Interests-as-at-May-31-2026.pdf... direct (0.5s)
[2509/3287] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statement-for-the-First-Quarter-Q1-ended-August-31-2025.pdf... needs_ocr_elsewhere (0.0s)
[2510/3287] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-and-Reports-for-the-First-Quarter-Q1-ended-August-31-2024-1.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2510 jse records so far)
[2511/3287] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-and-Reports-for-the-Third-Quarter-Q3-ended-February-28-2026.pdf... needs_ocr_elsewhere (0.0s)
[2512/3287] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-for-the-Third-Quarter-Q3-ended-February-28-2025-and-Shareholdings-of-Top-Ten-10-Shareholders-Directors-and-Senior-Officers.pdf... needs_ocr_elsewhere (0.0s)
[2513/3287] Portland-JSX-Ltd-FS-Quarter-Ended-August-31-2024.pdf... direct (1.8s)
[2514/3287] Portland-JSX-Ltd-FS-Quarter-Ended-November-2024.pdf... direct (1.8s)
[2515/3287] Portland-JSX-Ltd-FS-Quarter-Ended-November-2025.pdf... direct (1.9s)
[2516/3287] Portland-JSX-Ltd-Quarter-Ended-FS-August-2025.pdf... direct (2.3s)
[2517/3287] Portland-JSX-Ltd-Quarter-Ended-FS-May-2025.pdf... direct (1.8s)
[2518/3287] Post-Meeting-Notice-SREXF-Result-of-Board-Meeting-30Mar26-Page-1.pdf... direct (0.1s)
[2519/3287] Post-Meeting-Notice-SREXF-Result-of-Board-Meeting-30Mar26-Page-2.pdf... needs_ocr_elsewhere (1.0s)
[2520/3287] Press-Notice-3-November-2025.pdf... direct (0.0s)
  -- checkpoint saved (2520 jse records so far)
[2521/3287] Press-Release-01-10-2024.pdf... direct (0.2s)
[2522/3287] Press-Release-100MW-GPE-Tender-Wigton-50MW-Solar-Project-Award.pdf... direct (0.2s)
[2523/3287] Press-Release-24-09-2024-1.pdf... direct (0.3s)
[2524/3287] Press-Release-AGIC-appoints-new-CEO34-9.pdf... direct (0.2s)
[2525/3287] Press-Release-Disclosure-for-Expansion-into-Digital-Indoor-Advertising.pdf... direct (0.2s)
[2526/3287] Press-Release-GENAC-Acquisition.pdf... direct (0.1s)
[2527/3287] Press-Release-GK-Announces-Divisional-CFO-Changes.pdf... direct (0.1s)
[2528/3287] Press-Release-GraceKennedy-Announces-Leadership-Changes-Don-Wehby-retires-Jan-14-2025.pdf... direct (0.3s)
[2529/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Announces-Appointment-of-New-Auditors-July-30-2026.pdf... direct (0.1s)
[2530/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Bruno-Loffler-as-Group-Head-of-Finance-Administration-March-11-2025.pdf... direct (0.2s)
  -- checkpoint saved (2530 jse records so far)
[2531/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Delroy-McLean-as-Director.pdf... direct (0.2s)
[2532/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Don-Gittens-as-Director-and-Compensation-Committee-1.pdf... direct (0.2s)
[2533/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Mr.-Dwight-Balli-Independent-Director-to-the-Remuneration-Committee.pdf... direct (0.2s)
[2534/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Mr.-Everton-Younger-as-Chief-Operating-Officer.pdf... direct (0.1s)
[2535/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Appointment-of-Mr.-Loncey-Earle-as-Head-of-Business-Lubricants.pdf... direct (0.2s)
[2536/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Approval-and-Declaration-of-Interim-Dividend-Payment-November-24-2025.pdf... direct (0.1s)
[2537/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Consideration-of-Interim-Dividend-November-3-2025.pdf... direct (0.1s)
[2538/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Net-Profit-Nearly-Quadruples-to-99.1-Million-Board-Expresses-Confidence-in-Continued-Growth.pdf... direct (0.1s)
[2539/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Resignation-of-Dr.-Jacqueline-Leckie-March-11-2025.pdf... direct (0.3s)
[2540/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Resignation-of-Mr.-Daniel-Chin.pdf... direct (0.1s)
  -- checkpoint saved (2540 jse records so far)
[2541/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager-February-17-2026.pdf... direct (0.1s)
[2542/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager-January-12-2026.pdf... direct (0.1s)
[2543/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager-on-June-5-2025.pdf... direct (0.1s)
[2544/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager-on-November-29-2024-2.pdf... direct (0.1s)
[2545/3287] Press-Release-Paramount-Trading-Jamaica-Limited-Trading-in-Shares-by-a-Senior-Manager.pdf... direct (0.1s)
[2546/3287] Press-Release-Quantas-Advantage-Inc-Listed-on-the-JSE.pdf... direct (0.1s)
[2547/3287] Press-Release-Resumption-of-Trading-in-the-Shares-of-Atlantic-Hardware-Plumbing-Company.pdf... direct (0.1s)
[2548/3287] Press-Release-Resumption-of-Trading-in-the-Shares-of-DTL-Jul-10.pdf... direct (0.1s)
[2549/3287] Press-Release-VMIL-Advises-of-COO-Resignation-August-10-2026.pdf... direct (0.0s)
[2550/3287] Press-Release-VMIL-Announces-Appointment-of-New-Director-May-27-2026.pdf... direct (0.2s)
  -- checkpoint saved (2550 jse records so far)
[2551/3287] Press-Release-VMIL-Audited-Financials-delayed.pdf... direct (0.0s)
[2552/3287] Press-Release-VMIL-Dequity-IPO-December-24-2025.pdf... direct (0.1s)
[2553/3287] Press-Release-VMIL-Director-Resignation-Jan-7-2025.pdf... direct (0.0s)
[2554/3287] Press-Release-VMIL-Dividend-Declaration-.pdf... direct (0.0s)
[2555/3287] Press-Release-VMIL-Dividend-Declaration-Amended.pdf... direct (0.0s)
[2556/3287] Press-Release-VMIL-Leadership-Change-January-27-2026.pdf... direct (0.1s)
[2557/3287] Press-Release-VMIL-Management-Changes-January-13-2025.pdf... direct (0.1s)
[2558/3287] Press-Release-VMIL-November-7-2024.pdf... direct (0.0s)
[2559/3287] Press-Release-VMIL-announces-passing-of-Director-Phillip-SIlvera-August-22-2025_-.pdf... direct (0.1s)
[2560/3287] Press-Release-VMIL-declares-dividend-Nov-13-2024.pdf... direct (0.1s)
  -- checkpoint saved (2560 jse records so far)
[2561/3287] Press-Release-Wigton-Phase-I-Repowering-November-25-2024.pdf... direct (0.2s)
[2562/3287] Press-Release-_JSE-Website-March-2025.pdf... direct (0.3s)
[2563/3287] Press-Release-for-Visual-Vibe-Screen-Expansion-Partnership-2.pdf... direct (0.3s)
[2564/3287] Press-Release-on-the-Appointment-of-Director-Albert-Bailey.pdf... direct (0.1s)
[2565/3287] Press-Release-re-CariCRIS-Reaffirms-VM-Investments-Creditworthiness-and-Stable-Outlook.pdf... direct (0.1s)
[2566/3287] Press-Release_-General-Accident-Strengthens-Regional-Leadership-for-Strategic-Growth.pdf... direct (0.2s)
[2567/3287] Productive-Business-Solution-Limited-PBS-2023-FS-and-Audit-Opinion-31-Oct-24-2.pdf... direct (11.7s)
[2568/3287] Productive-Business-Solution-Limited-PBS-COMMON-DIVIDEND-CONSIDERATION-NOVEMBER-17-2025.pdf... direct (0.1s)
[2569/3287] Productive-Business-Solution-PBS-Delayed-Submission-of-the-Q-4-2024-Interim-Financials-February-14-2025.pdf... direct (0.1s)
[2570/3287] Productive-Business-Solutions-Limited-2024-Audited-Financial-Statements.pdf... direct (10.8s)
  -- checkpoint saved (2570 jse records so far)
[2571/3287] Productive-Business-Solutions-Limited-PBS-Annual-Report-2024-1.pdf... direct (28.2s)
[2572/3287] Productive-Business-Solutions-Limited-PBS-Annual-Report-2025-1.pdf... direct (32.9s)
    ^ SLOW FILE -- Productive-Business-Solutions-Limited-PBS-Annual-Report-2025-1.pdf took 32.9s
[2573/3287] Productive-Business-Solutions-Limited-PBS-Delayed-Submission-of-Audited-Financial-Statements-032026.pdf... direct (0.1s)
[2574/3287] Productive-Business-Solutions-Limited-PBS-Delayed-Submission-of-Audited-Financial-Statements.pdf... direct (0.1s)
[2575/3287] Productive-Business-Solutions-Limited-PBS-Extension-Notice-Submission-of-Audited-Financial-Statements-04302026.pdf... direct (0.1s)

[2576/3287] Productive-Business-Solutions-Limited-PBS-Extension-Notice-Submission-of-Audited-Financial-Statements-may-29th.pdf... direct (0.1s)
[2577/3287] Productive-Business-Solutions-Limited-PBS-Extension-Notice-Submission-of-Audited-Financial-Statements.pdf... direct (0.1s)
[2578/3287] Productive-Business-Solutions-Limited-PBS-Group-FS-2025.pdf... direct (13.7s)
[2579/3287] Productive-Business-Solutions-Limited-PBS-Interim-March-2024_Final_Revised.pdf... direct (0.5s)
[2580/3287] Productive-Business-Solutions-Limited-PBS-Interim-Report-Q1-2025-1.pdf... direct (1.7s)
  -- checkpoint saved (2580 jse records so far)
[2581/3287] Productive-Business-Solutions-Limited-PBS-Interim-Report-Q3-2025-3.pdf... direct (1.4s)
[2582/3287] Productive-Business-Solutions-Limited-PBS-Interim-Report-Q4-and-Full-Year-2025-1.pdf... direct (0.7s)
[2583/3287] Productive-Business-Solutions-Limited-PBS-New-Executive-Appointment.pdf... direct (0.1s)
[2584/3287] Productive-Business-Solutions-Limited-PBS-letter-to-JSE-Annual-Report.pdf... direct (0.1s)
[2585/3287] Productive-Business-Solutions-PBS-2023-Annual-Report-Revised.pdf... direct (25.5s)
[2586/3287] Productive-Business-Solutions-PBS-Extension-Notice-Submission-of-Audited-Financial-Statements_6.13.25.pdf... direct (0.1s)
[2587/3287] Productive-Business-Solutions-PBS-Interim-Report-Q2-2025-.pdf... direct (1.1s)
[2588/3287] Productive-Business-Solutions-PBS-Interim-Report-Q3-2024-.pdf... direct (1.2s)
[2589/3287] Productive-Business-Solutions-PBS-Interim-Report-Q4-2024-and-Full-Year.pdf... direct (1.0s)
[2590/3287] Profile-Dr-Marlene-Street-Forrest.pdf... direct (0.2s)
  -- checkpoint saved (2590 jse records so far)
[2591/3287] Profile-Jonathan-Echeverria-March-2026--1.pdf... direct (0.1s)
[2592/3287] Profile-Peter-Moses-June-2026.pdf... direct (0.1s)
[2593/3287] Profile-of-Mac-Kroupensky-.pdf... direct (0.1s)
[2594/3287] Prospectus-FINAL-Dequity-Capital-IPO-2025.pdf... direct (8.4s)
[2595/3287] Proxy-Form-1.pdf... needs_ocr_elsewhere (0.0s)
[2596/3287] Proxy-Form-2025.pdf... direct (0.8s)
[2597/3287] Proxy-Form-2026-Final-Pdf.pdf... direct (0.3s)
[2598/3287] Proxy-Form-EduFocal-EGM-Sept-2025.pdf... direct (0.1s)
[2599/3287] Proxy-Form.pdf... direct (0.1s)
[2600/3287] Pulse-Investments-Limited-%E2%80%93-Update-on-Publication-of-Audited-Financial-Statements-.pdf... direct (0.1s)
  -- checkpoint saved (2600 jse records so far)
[2601/3287] Pulse-Investments-Limited-%E2%80%93-Update-on-Publication-of-Audited-Financial-Statements-Annual-Report-October-31-2025-.pdf... direct (0.1s)
[2602/3287] Pulse-Investments-Limited-2024-Financial-Statements-.pdf... direct (7.5s)
[2603/3287] Pulse-Investments-Limited-Errata-Notice-of-Annual-General-Meeting-April-9-2026.pdf... direct (0.0s)
[2604/3287] Pulse-Investments-Limited-Notice-re-Publication-of-Q2-Unaudited-Financial-Statements-February-24-2026.pdf... direct (0.1s)
[2605/3287] Pulse-Investments-Limited-Unaudited-Financial-Statements-Quarter-Ended-September-30-2025.pdf... direct (0.1s)
[2606/3287] Pulse-Investments-Limited-Unaudited-Financials-2nd-Quarter-Ended-December-312025.pdf... direct (0.2s)
[2607/3287] Pulse-Investments-Limited-Unaudited-Financials-3rd-Quarter-Ended-March-31-2026.pdf... direct (0.7s)
[2608/3287] Pulse-Investments-Ltd-Unaudited-Financial-Statements-Quarter-Ended-December-31-2024.pdf... direct (0.5s)
[2609/3287] Pulse-Investments-Ltd.-Unaudited-Financial-Statements-Quarter-Ended-September-30-2024.pdf... direct (0.4s)
[2610/3287] Pulse-Investments-Report-July-8-2025-Status-of-Villa-Ronai-Development.pdf... direct (0.2s)
  -- checkpoint saved (2610 jse records so far)
[2611/3287] Purchase-of-Shares-by-a-director.pdf... needs_ocr_elsewhere (0.0s)
[2612/3287] Purity_2024_Annual_Report-WEB.pdf... direct (5.5s)
[2613/3287] Purity_2025_Annual_Report-5.pdf... direct (3.6s)
[2614/3287] Q1-2025_Indies-Pharma_Inhouse-Financials-ending_31st-Jan-2025.pdf... direct (2.6s)
[2615/3287] Q1-2026_Indies-Pharma_Inhouse-Financials_31-January-_2026.pdf... direct (2.5s)
[2616/3287] Q1-25_MPC-Caribbean-Clean-Energy-Limited-Unaudited-Interim-Finanacial-Statements.pdf... direct (2.8s)
[2617/3287] Q1-26_MPC-Caribbean-Clean-Energy-Limited-Unaudited-FS.pdf... direct (2.3s)
[2618/3287] Q1-Report-CPJ.pdf... direct (0.6s)
[2619/3287] Q12026_EduFocal_Final.pdf... direct (0.9s)
[2620/3287] Q2-2025_Indies-Pharma_Inhouse-Financials_30_April_2025.pdf... direct (2.6s)
  -- checkpoint saved (2620 jse records so far)
[2621/3287] Q2-2026_Indies-Pharma_Inhouse-Financials_Ending-30-April-2026.pdf... direct (2.7s)
[2622/3287] Q2-25_MPC-Caribbean-Clean-Energy-Limited-Unaudited-Interim-Financial-Statements.pdf... direct (2.8s)
[2623/3287] Q3-2025_Indies-Pharma_Inhouse-Financials-ending-31-July_2025-1.pdf... direct (2.8s)
[2624/3287] Q3-24_MPC-Caribbean-Clean-Energy-Limited-Financial-Statements.pdf... direct (2.8s)
[2625/3287] Q3-25_MPC-Caribbean-Clean-Energy-Limited-1-1.pdf... direct (2.8s)
[2626/3287] Q3-Shareholder-Report-as-at-September-2024.pdf... direct (0.9s)
[2627/3287] Q4-2024_Indies-Pharma_Inhouse-Financials_31st-Oct-2024.pdf... direct (2.7s)
[2628/3287] Q4-2025-JSE-Release-Updated.pdf... direct (1.2s)
[2629/3287] Q4-2025_Indies-Pharma_Inhouse-Financials_31-Oct_2025.pdf... direct (2.8s)
[2630/3287] Q4-24_MPC-Caribbean-Clean-Energy-Limited-Unaudited-Financial-Statements.pdf... direct (3.0s)
  -- checkpoint saved (2630 jse records so far)
[2631/3287] Q4-25_MPC-Caribbean-Clean-Energy-Limited-Unaudited-Interim-Financial-Statements.pdf... direct (2.9s)
[2632/3287] QA-Basis-of-Allotment-06-01-26.pdf... direct (0.1s)
[2633/3287] QA-Prospectus-2026-April-21.pdf... direct (11.7s)
[2634/3287] QWI-ANNUAL-REPORT-2024.pdf... direct (10.8s)
[2635/3287] QWI-Directors-Holding-as-at-December-31-2025.pdf... direct (0.1s)
[2636/3287] QWI-Directors-Holding-as-at-June-30-2026.pdf... direct (0.1s)
[2637/3287] QWI-Directors-Holding-as-at-March-31-2026.pdf... direct (0.1s)
[2638/3287] QWI-Directors-Holding-as-at-September-30-2024-1.pdf... direct (0.1s)
[2639/3287] QWI-First-Quarter-Report-to-December-2025.pdf... direct (1.2s)
[2640/3287] QWI-Investments-Annual-Report-2025.pdf... direct (6.8s)
  -- checkpoint saved (2640 jse records so far)
[2641/3287] QWI-Investments-Limited-Audited-2024-Financial-Statements-FINAL.pdf... direct (5.0s)
[2642/3287] QWI-Investments-Limited-Audited-2025-Financial-Statements-Final.pdf... direct (5.3s)
[2643/3287] QWI-Q1-REPORT-_period-ended-31-Dec-2024.pdf... direct (1.6s)
[2644/3287] QWI-Q2-REPORT-2025_revised.pdf... direct (1.7s)
[2645/3287] QWI-Q3-REPORT-2025.pdf... direct (1.7s)
[2646/3287] QWI-Q3-Report-2026.pdf... direct (1.6s)
[2647/3287] QWI-Q4-REPORT-2024.pdf... direct (1.5s)
[2648/3287] QWI-Q4-REPORT-2025-1.pdf... direct (1.6s)
[2649/3287] QWI-Second-Quarter-Report-to-31-March-2026.pdf... direct (1.6s)
[2650/3287] QWI-Senior-Managers-Holding-as-at-December-31-2025.pdf... direct (0.1s)
  -- checkpoint saved (2650 jse records so far)
[2651/3287] QWI-Senior-Managers-Holding-as-at-June-30-2026.pdf... direct (0.1s)
[2652/3287] QWI-Senior-Managers-Holding-as-at-March-31-2026.pdf... direct (0.1s)
[2653/3287] QWI-Senior-Managers-Holding-as-at-September-30-2024.pdf... direct (0.1s)
[2654/3287] QWIDirectorsHoldingasatDecember312024.pdf... direct (0.3s)
[2655/3287] QWIDirectorsHoldingasatJune302025.pdf... direct (0.1s)
[2656/3287] QWIDirectorsHoldingasatMarch312025-1.pdf... direct (0.1s)
[2657/3287] QWIDirectorsHoldingasatSeptember302025.pdf... direct (0.2s)
[2658/3287] QWISeniorManagersHoldingasatDecember312024.pdf... direct (0.1s)
[2659/3287] QWISeniorManagersHoldingasatJune302025.pdf... direct (0.1s)
[2660/3287] QWISeniorManagersHoldingasatMarch312025.pdf... direct (0.1s)
  -- checkpoint saved (2660 jse records so far)
[2661/3287] QWISeniorManagersHoldingasatSeptember302025-1.pdf... direct (0.1s)
[2662/3287] Quantas-Advantage-Inc.-Unaudited-Interim-Financial-Statements-for-the-nine-months-ended-March-31-2026.pdf... direct (0.5s)
[2663/3287] Quantas-Advantage-Inc.-Unaudited-Interim-Financial-Statements-for-the-year-ended-June-30-2026.pdf... direct (0.4s)
[2664/3287] RA-WILLIAMS-QUARTERLY-REPORT-DECEMBER-2024-UPLOAD.pdf... direct (1.4s)
[2665/3287] RA-Williams-Distributors-Limited-Audited-Financial-Statements-For-Financial-Year-ended-April-30-2025.pdf... direct (6.4s)
[2666/3287] RA-Williams-Distributors-Limited-Audited-Financial-Statements-For-Financial-Year-ended-April-30-2026.pdf... direct (6.9s)
[2667/3287] RA-Williams-Distributors-Ltd-RAWILL-Annual-Report-2025-Late-Submission.pdf... direct (0.1s)
[2668/3287] RA-Williams-Distributors-Ltd-RAWILL-Unaudited-Financial-Statements-for-the-Second-Quarter-Ended-October-31-2025-Revised.pdf... direct (1.4s)
[2669/3287] RA-Williams-Distributors-Ltd-RAWILL-Unaudited-Financial-Statements-for-the-Third-Quarter-Ended-January-31-2026.pdf... direct (1.2s)
[2670/3287] RA-Williams-Distributors-Ltd.-RAWILL-2025-Annual-Report.pdf... direct (11.9s)
  -- checkpoint saved (2670 jse records so far)
[2671/3287] RA-Williams-Distributors-Ltd.-RAWILL-AGM-Thursday-September-25-2025-Form-of-Proxy.pdf... direct (0.1s)
[2672/3287] RA-Williams-Distributors-Ltd.-RAWILL-Notice-of-Annual-General-Meeting-Thursday-September-25-2025.pdf... direct (0.1s)
[2673/3287] RA-Williams-Distributors-Ltd.-RAWILL-Notice-to-Shareholders-Changes-in-Management.pdf... direct (0.0s)
[2674/3287] RA-Williams-Distributors-Ltd.-RAWILL-Unaudited-Financial-Statements-for-the-First-Quarter-Ended-July-31-2025-Revised.pdf... direct (1.0s)
[2675/3287] RA-Williams-Distributors-Ltd.-RAWILL-Unaudited-Financial-Statements-for-the-Third-Quarter-Ended-January-31-2025.pdf... direct (1.7s)
[2676/3287] RADIO-JAMAICA-LIMITED-Form-of-Proxy-3.pdf... direct (0.1s)
[2677/3287] RE-Temporary-Relocation-of-Administrative-Services.pdf... direct (0.1s)
[2678/3287] RELEASE-FROM-CARRERAS-LIMITED.pdf... direct (0.1s)
[2679/3287] RELEASE-TO-SHAREHOLDERS-For-the-Period-Ended-September-2024-Final.pdf... direct (1.1s)
[2680/3287] RELEASE-TO-SHAREHOLDERS-For-the-Quarter-Ended-December-2024.pdf... direct (1.0s)
  -- checkpoint saved (2680 jse records so far)
[2681/3287] REVISED-JPS-Unaudited-Quarterly-Financials-March-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[2682/3287] RJL.NOTICE.AGM_.PROXYFORM.2025.pdf... direct (0.3s)
[2683/3287] RJR-Directors-Holding-as-at-December-31-2025-3.pdf... direct (0.5s)
[2684/3287] RJR-Directors-Holding-as-at-September-30-2025.pdf... direct (0.3s)
[2685/3287] RJR-Limited-Directors-Report-Unaudited-Statements-as-at-December-2025-1.pdf... needs_ocr_elsewhere (0.0s)
[2686/3287] RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2.pdf... needs_ocr_elsewhere (0.0s)
[2687/3287] RJR-Limited-Unaudited-Financial-Statements-as-at-September-2024.pdf... needs_ocr_elsewhere (0.0s)
[2688/3287] RJR-Top-10-as-at-December-31-2025-1.pdf... direct (0.1s)
[2689/3287] RJR-Top-10-as-at-September-30-2025.pdf... direct (0.1s)
[2690/3287] RJRDIRECTORSReportDecember312024-1.pdf... direct (0.5s)
  -- checkpoint saved (2690 jse records so far)
[2691/3287] RJRDirectorsHoldingasatJune302025-1.pdf... direct (0.3s)
[2692/3287] RJRDirectorsHoldingasatMarch312025-1.pdf... direct (0.3s)
[2693/3287] RJRDirectorsHoldingasatSeptember302024.pdf... direct (0.4s)
[2694/3287] RJRGLEANER-Press-Release-March-2-2026-Final-1.pdf... direct (0.2s)
[2695/3287] RJRSENIORMANAGERSReportDecember312024-1.pdf... direct (0.4s)
[2696/3287] RJRTop10ShareholdersReportDecember312024-1.pdf... direct (0.3s)
[2697/3287] RJRTop10asatJune302025-1.pdf... direct (0.1s)
[2698/3287] RJRTop10asatMarch312025-1.pdf... direct (0.1s)
[2699/3287] RJRTop10asatSeptember302024.pdf... direct (0.1s)
[2700/3287] RMOD-Newsletter-May-2024-2-2.pdf... direct (1.2s)
  -- checkpoint saved (2700 jse records so far)
[2701/3287] ROC-2025-Q1-Unaudited-Financial.pdf... direct (1.3s)
[2702/3287] ROC-2026-Q2-Quarterly-Report.pdf... direct (1.9s)
[2703/3287] ROC-JSE-Shareholder-Report-2025-Q4.pdf... direct (1.6s)
[2704/3287] ROC-Q2-Quarterly-Report.pdf... direct (1.8s)
[2705/3287] ROC-Q3-2024-1.pdf... direct (1.5s)
[2706/3287] ROC-Q4-2024-2.pdf... direct (1.2s)
[2707/3287] ROC-Quarterly-Report-2025-Q3.pdf... direct (1.8s)
[2708/3287] RPL-AGM-Notice-Update_final.pdf... direct (0.0s)
[2709/3287] RPL-Annual-Report-FY2025_compressed.pdf... direct (3.9s)
[2710/3287] RPL-Notice-of-AGM-2024-updated.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2710 jse records so far)
[2711/3287] RPL-Notice-of-AGM-FY2024.pdf... needs_ocr_elsewhere (0.1s)
[2712/3287] RPL-Press-Release-FY2024.pdf... direct (0.2s)
[2713/3287] RPL-Press-Release-Q1-2025.pdf... direct (0.2s)
[2714/3287] RPL-Press-Release-Q2-2025.pdf... direct (0.2s)
[2715/3287] RPL-Proxy-2024-updated.pdf... needs_ocr_elsewhere (0.0s)
[2716/3287] RPL-Proxy-FY2024.pdf... direct (0.1s)
[2717/3287] RPL-Proxy-Form-26.pdf... direct (0.1s)
[2718/3287] RPL-Q1-2025-Report_compressed.pdf... direct (1.1s)
[2719/3287] RPL-Q1-2026-Report.pdf... direct (1.2s)
[2720/3287] RPL-Q2-2025-Unaudited-Financials.pdf... direct (1.1s)
  -- checkpoint saved (2720 jse records so far)
[2721/3287] RPL-Q3-2025-Report-Stitch-2.pdf... direct (1.1s)
[2722/3287] RPL-Top-10-Members-December-31-2025.pdf... direct (0.1s)
[2723/3287] Radio-Jamaica-Limited-Audited-2025-Consolidated-Financial-Statements-FINAL-1.pdf... direct (13.2s)
[2724/3287] Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025.pdf... needs_ocr_elsewhere (0.0s)
[2725/3287] Radio-Jamaica-Limited-Unauditted-Financial-Statements-as-at-June-30-2025-1.pdf... needs_ocr_elsewhere (0.0s)
[2726/3287] Redemption-Notice.pdf... needs_ocr_elsewhere (0.0s)
[2727/3287] Regency-Petroleum-Company-Limited-2nd-Quarter-Report-2026.pdf... direct (1.2s)
[2728/3287] Regency-Petroleum-Company-Limited-RPL-Q3-2024-Report.pdf... direct (1.5s)
[2729/3287] Regency-Petroleum-Company-Ltd-Audited-Financials-Dec-31-2024.pdf... direct (5.8s)
[2730/3287] Regency-Petroleum-Company-Ltd-Audited-Financials-Dec-31-2025.pdf... direct (6.5s)
  -- checkpoint saved (2730 jse records so far)
[2731/3287] Regency-Petroleum-Company-RPL-Press-Release-Q3-2024.pdf... direct (0.2s)
[2732/3287] Registration-Form-CEO-BUSINESS-FORUM._.pdf... direct (0.3s)
[2733/3287] Regulatory-Advisory-1.pdf... direct (0.1s)
[2734/3287] Release-GK-2024-YE-Results-GraceKennedy-Delivers-Strong-Financial-Performance-in-2024.pdf... direct (0.2s)
[2735/3287] Release-GK-2025-Year-End-Results.pdf... direct (0.5s)
[2736/3287] Release-GK-acquires-100-of-Catherines-Peak-29012025-final.pdf... direct (0.1s)
[2737/3287] Release-GKFG-moves-to-fully-acquire-Key-final.pdf... direct (0.1s)
[2738/3287] Release-GKMS-Leadership-Changes-27022025-final.pdf... direct (0.2s)
[2739/3287] Release-GraceKennedy-Announces-Strategic-Leadership-Changes-in-Insurance-Segment-090925-final-1.pdf... direct (0.4s)
[2740/3287] Release-GraceKennedy-Announces-Strategic-Leadership-Changes-in-Insurance-Segment-final.pdf... direct (0.2s)
  -- checkpoint saved (2740 jse records so far)
[2741/3287] Release-Jacky-Wright-Appointed-to-GKL-Board-Nov-13-2025-1.pdf... direct (0.1s)
[2742/3287] Release-for-JSE-re-SGJ-BNSJ-Board-Changes-5-February-2026-1.pdf... direct (0.2s)
[2743/3287] Remarks-at-the-Launch-of-the-JSE-Micro-Market-Livingstone-Morrison-OD-Group-Chief-Executive-Officer-Jamaica-Stock-Exchange.pdf... direct (0.5s)
[2744/3287] Report-to-Shareholders-June-2025.pdf... needs_ocr_elsewhere (0.0s)
[2745/3287] Report-to-the-Shareholders-for-the-twelve-months-ended-March-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[2746/3287] Report-to-the-Shareholders.pdf... needs_ocr_elsewhere (0.0s)
[2747/3287] Report_Top-10-Shareholders_Sept.2025.pdf... direct (0.2s)
[2748/3287] Request-for-Minutes-of-AGM-Notice.pdf... direct (0.0s)
[2749/3287] Resignation-C.-Gentles.pdf... needs_ocr_elsewhere (0.0s)
[2750/3287] Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected.pdf... needs_ocr_elsewhere (0.1s)
  -- checkpoint saved (2750 jse records so far)
[2751/3287] Revised-Notice-of-AGM_for-the-period-2025-2026-2.pdf... direct (0.2s)
[2752/3287] Revised_Dt_PROXY-Form-for-period-2025-2026-1.pdf... direct (0.3s)
[2753/3287] SALF-Shareholders-Update-for-60th-AGM-amended.pdf... direct (0.1s)
[2754/3287] SALF-Shareholders-Update-for-61st-AGM-2026.pdf... direct (0.1s)
[2755/3287] SALF_Audited-Financial-Statements_2023-24.pdf... direct (8.7s)

[2756/3287] SALF_Audited-Financial-Statements_2024-25.pdf... direct (7.9s)
[2757/3287] SALF_JSE-Release_Q3.-2026.pdf... direct (0.9s)
[2758/3287] SALF_Salada-Foods-Annual-Report_2023-24-1.pdf... direct (19.5s)
[2759/3287] SALF_Salada-Foods-Annual-Report_2024-25.pdf... direct (19.4s)
[2760/3287] SALF_Top-10-Shareholders_Q2.2026.pdf... direct (0.2s)
  -- checkpoint saved (2760 jse records so far)
[2761/3287] SALF_Top-10-Shareholders_Q3.2026.pdf... direct (0.3s)
[2762/3287] SALFs-Form-of-Proxy-for-AGM-2026.pdf... needs_ocr_elsewhere (2.5s)
[2763/3287] SALFs-Notice-of-AGM-2026.pdf... needs_ocr_elsewhere (2.1s)
[2764/3287] SCI-2024-AGM-2024-Annual-Report.pdf... direct (17.1s)
[2765/3287] SCI-2024-AGM-Form-of-Proxy.pdf... direct (0.2s)
[2766/3287] SCI-2024-AGM-Notice-of-AGM.pdf... direct (0.2s)
[2767/3287] SCI-2024-Shareholders-Advisory2.pdf... direct (0.3s)
[2768/3287] SCI-2025-AGM-2025-Annual-Report.pdf... direct (18.8s)
[2769/3287] SCI-2025-AGM-Form-of-Proxy.pdf... direct (0.2s)
[2770/3287] SCI-2025-AGM-Notice-of-AGM.pdf... direct (0.2s)
  -- checkpoint saved (2770 jse records so far)
[2771/3287] SCI-2025-AGM-Shareholders-Advisory-1.pdf... direct (0.1s)
[2772/3287] SCI-2025-Shareholders-Advisory2-FINAL.pdf... direct (1.1s)
[2773/3287] SCI-Audited-FS-FYE-Jun-30-2024.pdf... direct (9.2s)
[2774/3287] SCI-Audited-Financial-Statements-FYE-Jun-30-2025.pdf... direct (11.3s)
[2775/3287] SCI-Earnings-Call-Announcement-Q3-Mar-2026.pdf... direct (0.0s)
[2776/3287] SCI-FYE-June-2025-Earnings-Call.pdf... direct (0.0s)
[2777/3287] SCI-MDA-FYE-Jun-30-2024.pdf... direct (2.0s)
[2778/3287] SCI-MDA-June-30-2025-Audited.pdf... direct (1.3s)
[2779/3287] SCI-Pref-Share-Short-Form-Prospectus-FINAL-NOV-2024.pdf... direct (11.0s)
[2780/3287] SCI-Q1-Report-Sep-30-2025.pdf... direct (2.9s)
  -- checkpoint saved (2780 jse records so far)
[2781/3287] SCI-Q2-Report-Dec-31-2025.pdf... direct (3.5s)
[2782/3287] SCI-Q3-2025-Earnings-Call-Notice.pdf... direct (0.0s)
[2783/3287] SCI-Q3-Financials-March-31-2025.pdf... direct (3.2s)
[2784/3287] SCI-Q3-Report-Mar-31-2026.pdf... direct (3.0s)
[2785/3287] SCI-unaudited-Financial-Statements-Sep-30-2024-Q1-2025.pdf... direct (2.8s)
[2786/3287] SCI_Basis_of_Allotment.docx.pdf... direct (0.1s)
[2787/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q1-2025-FINAL.pdf... direct (1.7s)
[2788/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q1-2026.pdf... direct (1.7s)
[2789/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q2-2025.pdf... direct (1.8s)
[2790/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q2-2026-.pdf... direct (1.7s)
  -- checkpoint saved (2790 jse records so far)
[2791/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q3-2024-FINAL.pdf... direct (1.9s)
[2792/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q3-2025.pdf... direct (1.8s)
[2793/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q4-2024-Revised.pdf... direct (1.8s)
[2794/3287] SCOTIA-GROUP-MEDIA-RELEASE-Q4-2025-FINAL.pdf... direct (1.7s)
[2795/3287] SGJ-2024-Annual-Report.pdf... direct (29.1s)
[2796/3287] SGJ-2025-AGM-Notice-eDocument.pdf... direct (0.2s)
[2797/3287] SGJ-2025-Annual-Report.pdf... direct (276.8s)
    ^ SLOW FILE -- SGJ-2025-Annual-Report.pdf took 276.8s
[2798/3287] SGJ-2025-Proxy-Insert-eDocument-1.pdf... direct (0.1s)
[2799/3287] SGJ-Announcement-Resignation-Snr.-Management-Officer-1.pdf... direct (0.1s)
[2800/3287] SGJ-Audited-FS-2025-Final.pdf... direct (21.1s)
  -- checkpoint saved (2800 jse records so far)
[2801/3287] SGJ-Changes-to-Board-Composition-March-2025.pdf... direct (0.3s)
[2802/3287] SGJ-Corporate-Governance-Policy-Updated-Q4-2025--1.pdf... direct (3.1s)
[2803/3287] SGJ-JSE-Release-SLI-Merger-5.pdf... direct (0.3s)
[2804/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-April-30-2025.pdf... direct (0.4s)
[2805/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-January-31-2025.pdf... direct (0.4s)
[2806/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-July-31-2024.pdf... direct (0.6s)
[2807/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-July-31-2025.pdf... direct (0.4s)
[2808/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-Oct.-31-2024.pdf... direct (0.5s)
[2809/3287] SGJ-Largest-Shareholdings-Directors-Snr.-Management-as-at-October-31-2025.pdf... direct (0.4s)
[2810/3287] SGJ-Letter-Media-Release-Q1.2025.pdf... direct (0.1s)
  -- checkpoint saved (2810 jse records so far)
[2811/3287] SGJ-Letter-Media-Release-Q2.2025.pdf... direct (0.1s)
[2812/3287] SGJ-Letter-Media-Release-Q2.2026.pdf... direct (0.1s)
[2813/3287] SGJ-Letter-Media-Release-Q3.2024-1.pdf... direct (0.1s)
[2814/3287] SGJ-Letter-Media-Release-Q4.2024-1.pdf... direct (0.2s)
[2815/3287] SGJ-Letter-Media-Release-Q4.2025.pdf... direct (0.1s)
[2816/3287] SGJ-List-of-Shareholdings-Report-Q1-January-31-2026.pdf... direct (0.4s)
[2817/3287] SGJ-List-of-Shareholdings-Report-Q2-April-30-2026-1.pdf... direct (0.3s)
[2818/3287] SHARE-WARRANT-FORM-JMD-Ordinary-Shares.pdf... direct (0.5s)
[2819/3287] SHARE-WARRANT-FORM-USD-Ordinary-Shares.pdf... direct (0.5s)
[2820/3287] SHAREHOLDERS-NOTICE-RE-APPOINTMNE-TOF-DIRECTOR--1.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2820 jse records so far)
[2821/3287] SIL-2024-FS-FINAL.pdf... direct (5.1s)
[2822/3287] SIL-2025-FS-27-Feb-2026.pdf... direct (8.4s)
[2823/3287] SIL-AGM-NOTICE-NOV-2025-AND-PROXY.pdf... needs_ocr_elsewhere (0.0s)
[2824/3287] SIL-FS-2024-Financial-Highlights.pdf... direct (0.2s)
[2825/3287] SIL-Required-shareholder-listing-12-31-2025.pdf... direct (0.1s)
[2826/3287] SIL_Annual-Report-2024.pdf... direct (7.8s)
[2827/3287] SIL_Annual-Report-2025.pdf-final.pdf... direct (9.3s)
[2828/3287] SIL_MDA_Q1-2025-Final.pdf... direct (1.2s)
[2829/3287] SIL_MDA_Q1-2026-1.pdf... direct (2.5s)
[2830/3287] SIL_MDA_Q2-2025.pdf... direct (1.5s)
  -- checkpoint saved (2830 jse records so far)
[2831/3287] SIL_MDA_Q2-2026.pdf... needs_ocr_elsewhere (15.1s)
[2832/3287] SIL_MDA_Q3-2024-final.pdf... direct (1.1s)
[2833/3287] SIL_MDA_Q3-2025.pdf... direct (1.7s)
[2834/3287] SML-2025-Annual-Report.pdf... direct (14.8s)
[2835/3287] SML-JSE-Q1-REPORT-2025.pdf... direct (0.8s)
[2836/3287] SML-JSE-Quarterly-Report-as-at-March-2026-Final-Signed.pdf... direct (1.6s)
[2837/3287] SML-Q4-JSE-Report.pdf... direct (0.6s)
[2838/3287] SML-QUARTERLY-REPORT-AS-AT-JUNE-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[2839/3287] SOS-1st-Qtr-Unaudited-2025-Signed.pdf... direct (1.2s)
[2840/3287] SOS-2024-4th-Qtr-Management-Report-Audited-Financial-Results.pdf... direct (7.8s)
  -- checkpoint saved (2840 jse records so far)
[2841/3287] SOS-2nd-Qtr-2024-Unaudited-Financials-Signed-Full.pdf... direct (1.5s)
[2842/3287] SOS-2nd-Qtr-Eesults-Signed.pdf... direct (1.3s)
[2843/3287] SOS-2nd-Qtr-Unaudited-Financials-2025-Signed-14.8.25.pdf... direct (1.4s)
[2844/3287] SOS-3rd-Quarter-Unaudited-Financials-Signed.pdf... direct (2.0s)
[2845/3287] SOS_2024_Annual-Report_Final_spread.pdf... direct (10.9s)
[2846/3287] SOS_2025_Annual-Report_final_web_spreads.pdf... direct (11.1s)
[2847/3287] SPEAKERS-INVESTMENT-FORUM-BEACH-FRONT.pdf... needs_ocr_elsewhere (0.0s)
[2848/3287] SRF-2024-Annual-Report-WEB.pdf... direct (15.8s)
[2849/3287] SRF-2024-Form-of-Proxy.pdf... direct (0.2s)
[2850/3287] SRF-2024-Notice-of-AGM.pdf... direct (0.2s)
  -- checkpoint saved (2850 jse records so far)
[2851/3287] SRF-2024-Shareholders-Advisory.pdf... direct (0.1s)
[2852/3287] SRF-2025-Annual-Report-Web.pdf... direct (15.2s)
[2853/3287] SRF-2025-Notice-of-AGM.pdf... direct (0.2s)
[2854/3287] SRF-2025-Proxy-Form.pdf... direct (0.2s)
[2855/3287] SRF-2025-Shareholders-Advisory.pdf... direct (0.8s)
[2856/3287] SRF-2025-Shareholders-Advisory2-Updated.pdf... direct (0.4s)
[2857/3287] SRF-2026-AGM-Shareholder-Advisory-No-2-FINAL.pdf... direct (0.5s)
[2858/3287] SRF-Audited-Financial-Statement-FYE-August-31-2025-JSE.pdf... direct (8.7s)
[2859/3287] SRF-Audited-Financial-Statements-FYE-Aug-31-2024-JSE-1.pdf... direct (19.4s)
[2860/3287] SRF-MDA-FYE-Aug-31-2024-JSE-Final-1.pdf... direct (11.9s)
  -- checkpoint saved (2860 jse records so far)
[2861/3287] SRF-MDA-FYE-August-31-2025-JSE-Final.pdf... direct (2.3s)
[2862/3287] SRF-Q1-2025-Report-to-the-JSE-Final.pdf... direct (3.4s)
[2863/3287] SRF-Q1-2026-Report-to-the-JSE-Final.pdf... direct (3.4s)

[2864/3287] SRF-Q2-2025-Report-to-the-JSE-Final.pdf... direct (3.6s)
[2865/3287] SRF-Q2-2026-Report-to-the-JSE-Final.pdf... direct (3.7s)
[2866/3287] SRF-Q3-2025-Earnings-Call-Notice.pdf... direct (0.0s)
[2867/3287] SRF-Q3-2025-Report-to-the-JSE-Final.pdf... direct (4.0s)
[2868/3287] SRF-Q3-2026-Report-to-the-JSE-Final.pdf... direct (4.1s)
[2869/3287] SRF-Shareholders-Advisory-PIK-SHARES.pdf... direct (0.4s)
[2870/3287] STANLEY-MOTTA-LIMITED-2024-ANNUAL-REPORT-AMENDED.pdf... direct (15.6s)
  -- checkpoint saved (2870 jse records so far)
[2871/3287] STANLEY-MOTTA-LIMITED-2025-FS.pdf... direct (9.2s)
[2872/3287] STANLEY-MOTTA-LIMITED-AUDITED-FINANCIAL-STATEMENT-2024-AMENDED.pdf... direct (7.5s)
[2873/3287] STANLEY-MOTTA-LIMITED-SML-UNAUDITED-FINANCIAL-STATEMENTS-FOR-THE-FOURTH-QUARTER-ENDED-DECEMBER-31-2025.pdf... direct (1.0s)
[2874/3287] STANLEY-MOTTA-LIMITED-SML-UNAUDITED-Financial-Statements-For-Third-Quarter-Ended-30-September-2024-1.pdf... direct (1.5s)
[2875/3287] STANLEY-MOTTA-Q3-JSE-REPORT-1-1.pdf... needs_ocr_elsewhere (0.0s)
[2876/3287] STOCKHOLDERS-REPORT-Q3-25.pdf... direct (0.2s)
[2877/3287] STSJL-Q3-PerformanceReport2025-Unaudited.pdf... direct (7.0s)
[2878/3287] SVL-Shareholding-Report-as-a-March-31-2025.pdf... direct (0.6s)
[2879/3287] SVL-Shareholding-Report-as-at-December-31-2024.pdf... direct (1.0s)
[2880/3287] SVL-Shareholding-Report-as-at-June-30-2025.pdf... direct (0.7s)
  -- checkpoint saved (2880 jse records so far)
[2881/3287] SVL-Shareholding-Report-as-at-June-30-2026.pdf... direct (0.9s)
[2882/3287] SVL-Shareholding-Report-as-at-March-31-2026.pdf... direct (0.6s)
[2883/3287] SVL-Shareholding-Report-as-at-September-30-2024.pdf... direct (0.8s)
[2884/3287] SVL-Shareholding-Report-as-at-September-30-2025-1.pdf... direct (0.7s)
[2885/3287] SYGNUS-Shareholder-Advisory-2-FINAL.pdf... direct (0.5s)
[2886/3287] Sagicor-Group-Annual-2025-eDocument-1.pdf... direct (53.3s)
    ^ SLOW FILE -- Sagicor-Group-Annual-2025-eDocument-1.pdf took 53.3s
[2887/3287] Sagicor-Group-Annual-Report-2024_eDocument.pdf... direct (53.3s)
    ^ SLOW FILE -- Sagicor-Group-Annual-Report-2024_eDocument.pdf took 53.3s
[2888/3287] Sagicor-Group-Jamaica-Limited-Audited-Financial-Statements-for-year-ended-December-31-2025.pdf... direct (38.5s)
    ^ SLOW FILE -- Sagicor-Group-Jamaica-Limited-Audited-Financial-Statements-for-year-ended-December-31-2025.pdf took 38.5s
[2889/3287] Sagicor-Group-Jamaica-Limited-SJ-Audited-Financial-Statements-for-the-year-ended-December-31-2024.pdf... direct (34.3s)
    ^ SLOW FILE -- Sagicor-Group-Jamaica-Limited-SJ-Audited-Financial-Statements-for-the-year-ended-December-31-2024.pdf took 34.3s
[2890/3287] Sagicor-Group-Jamaica-Limited-SJ-Audited-Report-to-Stockholders-for-the-Fourth-Quarter-Ended-December-31-2025.pdf... direct (4.1s)
  -- checkpoint saved (2890 jse records so far)
[2891/3287] Sagicor-Group-Jamaica-Limited-SJ-Report-to-Stockholders-for-the-Fourth-Quarter-Ended-December-31-2024.pdf... direct (3.3s)
[2892/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-First-Quarter-Ended-March-31-2025.pdf... direct (0.3s)
[2893/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-First-Quarter-Ended-March-31-2026.pdf... direct (0.3s)
[2894/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Fourth-Quarter-Ended-December-31-2024.pdf... direct (0.6s)
[2895/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Fourth-Quarter-Ended-December-31-2025.pdf... direct (0.3s)
[2896/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Second-Quarter-Ended-June-30-2025.pdf... direct (0.3s)
[2897/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Second-Quarter-Ended-June-30-2026-1.pdf... direct (0.4s)
[2898/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Third-Quarter-Ended-September-30-2024.pdf... direct (0.3s)
[2899/3287] Sagicor-Group-Jamaica-Limited-SJ-Top-Ten-Shareholders-for-the-Third-Quarter-Ended-September-30-2025.pdf... direct (0.3s)
[2900/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-First-Quarter-Ended-March-31-2025.pdf... direct (3.0s)
  -- checkpoint saved (2900 jse records so far)
[2901/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-First-Quarter-Ended-March-31-2026.pdf... direct (3.3s)
[2902/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-Second-Quarter-Ended-June-30-2025.pdf... direct (3.5s)
[2903/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-Second-Quarter-Ended-June-30-2026.pdf... direct (3.4s)
[2904/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-Third-Quarter-Ended-September-30-2024.pdf... direct (3.4s)
[2905/3287] Sagicor-Group-Jamaica-Limited-SJ-Unaudited-Report-to-Stockholders-for-the-Third-Quarter-Ended-September-30-2025.pdf... direct (3.7s)
[2906/3287] Sagicor-Group-Jamaica-Proxy-Form.pdf... direct (0.2s)
[2907/3287] Sagicor-Notice-of-AGM-2025.pdf... direct (0.2s)
[2908/3287] Sagicor-Real-Estate-X-Fund-2024-Annual-Report_eDocument.pdf... direct (13.6s)
[2909/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-%E2%80%93-Unaudited-Report-to-Stockholders-for-the-Second-Quarter-Ended-June-30-2025.pdf... direct (1.6s)
[2910/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-%E2%80%93-Unaudited-Report-to-Stockholders-for-the-Third-Quarter-Ended-September-30-2025.pdf... direct (2.4s)
  -- checkpoint saved (2910 jse records so far)
[2911/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Audited-Report-to-Stockholders-as-at-the-Fourth-Quarter-Ended-December-31-2024.pdf... direct (1.5s)
[2912/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Audited-Report-to-Stockholders-as-at-the-Fourth-Quarter-Ended-December-31-2025.pdf... direct (1.8s)
[2913/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-as-at-the-Fourth-Quarter-Ended-December-31-2025.pdf... direct (0.1s)
[2914/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-as-at-the-Second-Quarter-Ended-June-30-2025-2.pdf... direct (0.1s)
[2915/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-as-at-the-Second-Quarter-Ended-June-30-2026-1.pdf... direct (0.3s)
[2916/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-as-at-the-Third-Quarter-Ended-September-30-2025.pdf... direct (0.1s)
[2917/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-for-the-First-Quarter-Ended-March-31-2026.pdf... direct (0.1s)
[2918/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-for-the-Fourth-Quarter-Ended-March-31-2025.pdf... direct (0.1s)
[2919/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Top-Ten-Shareholders-for-the-Third-Quarter-Ended-September-30-2024.pdf... direct (0.1s)
[2920/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Unaudited-Report-to-Stockholders-as-at-the-First-Quarter-Ended-March-31-2025.pdf... direct (1.9s)
  -- checkpoint saved (2920 jse records so far)
[2921/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Unaudited-Report-to-Stockholders-as-at-the-Third-Quarter-Ended-September-30-2024.pdf... direct (2.0s)
[2922/3287] Sagicor-Real-Estate-X-Fund-Limited-XFUND-Unaudited-Report-to-Stockholders-for-the-First-Quarter-Ended-March-31-2026.pdf... direct (2.3s)
[2923/3287] Sagicor-Real-Estate-X-Fund-Notice-of-AGM.pdf... direct (0.3s)
[2924/3287] Sagicor-Real-Estate-X-Fund-Proxy-Form.pdf... direct (0.2s)
[2925/3287] Sagicor-Real-Estate-X-Fund-X-Fund-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (8.6s)
[2926/3287] Sagicor-Real-Estate-X-Fund-X-Fund-Audited-Financial-Statements-for-the-Year-Ended-December-31-2025.pdf... direct (6.8s)
[2927/3287] Sagicor-Real-Estate-X-Fund-XFUND-Unaudited-Report-to-Stockholders-for-the-Second-Quarter-Ended-June-30-2026.pdf... direct (2.1s)
[2928/3287] Sagicor-Select-Annual-2025-edocument.pdf... direct (13.0s)
[2929/3287] Sagicor-Select-Financial-Q2-2025-Report-1.pdf... direct (2.4s)
[2930/3287] Sagicor-Select-Funds-2024-AGM-Proxy-Form.pdf... direct (0.1s)
  -- checkpoint saved (2930 jse records so far)
[2931/3287] Sagicor-Select-Funds-Financial-Fund-Q3-2024.pdf... direct (2.0s)
[2932/3287] Sagicor-Select-Funds-Financial-Fund-SELECTF-Audited-Financial-Statements-for-2024.pdf... direct (4.8s)
[2933/3287] Sagicor-Select-Funds-Financial-Q1-2026.pdf... direct (1.9s)
[2934/3287] Sagicor-Select-Funds-Financial-Q1_2025.pdf... direct (1.7s)
[2935/3287] Sagicor-Select-Funds-Financial-Q2-2026.pdf... direct (1.8s)
[2936/3287] Sagicor-Select-Funds-Financial-Q3-2025.pdf... direct (2.1s)
[2937/3287] Sagicor-Select-Funds-Limited-AGM-Notice.pdf... direct (0.2s)
[2938/3287] Sagicor-Select-Funds-Limited-Annual-Report-2024.pdf... direct (12.7s)
[2939/3287] Sagicor-Select-Funds-MD-Fund-Q3-2024.pdf... direct (2.1s)
[2940/3287] Sagicor-Select-Funds-MD-Q1_2025.pdf... direct (1.8s)
  -- checkpoint saved (2940 jse records so far)
[2941/3287] Sagicor-Select-Funds-Manufacturing-Distribution-Fund-SELECTMD-Audited-Financial-Statements-for-2024.pdf... direct (4.5s)
[2942/3287] Sagicor-Select-Funds-Manufacturing-and-Distribution-Q1-2026.pdf... direct (1.8s)
[2943/3287] Sagicor-Select-Funds-Manufacturing-and-Distribution-Q2-2026.pdf... direct (1.8s)
[2944/3287] Sagicor-Select-Funds-Manufacturing-and-Distribution-Q3-2025.pdf... direct (1.8s)
[2945/3287] Sagicor-Select-MD-Q2-2025-Report.pdf... direct (1.9s)
[2946/3287] Sagicor-Select_Financial_Audited-Financials-2025.pdf... direct (4.9s)
[2947/3287] Sagicor-Select_MD_Audited-Financials-2025.pdf... direct (4.8s)
[2948/3287] Sagicor-XFund-Annual-2025-edocument6.pdf... direct (11.9s)
[2949/3287] Sagicor_XFund_AGM_Notice_2025-1.pdf... direct (0.3s)
[2950/3287] Sagicor_XFund_Proxy_Form_2025-1.pdf... direct (0.2s)
  -- checkpoint saved (2950 jse records so far)
[2951/3287] Salada-Foods-Top-10-Directors-Snr.-Managers-Report-December-31-2025.pdf... direct (0.2s)
[2952/3287] Salada-Foods-Top-10-Directors-Snr.-Managers-Report-June-30-2025.pdf... direct (0.2s)
[2953/3287] Salada-Foods-Top-10-Directors-Snr.-Managers-Report-September-30-2024.pdf... direct (0.8s)
[2954/3287] Salada-Foods_Top-10-Shareholders-Report-December-31-2024.pdf... direct (0.2s)
[2955/3287] Salada-Form-of-Proxy-16-01-2025.pdf... needs_ocr_elsewhere (2.3s)
[2956/3287] Salada-Notice-of-AGM-16-01-2025.pdf... needs_ocr_elsewhere (2.1s)
[2957/3287] Salesmanship-Workshop.pdf... needs_ocr_elsewhere (0.0s)
[2958/3287] Scotia-Group-Jamaica-Ltd.-Audited-FS-2024-1.pdf... direct (18.3s)
[2959/3287] Scotiabank-Privatising-SGJL.pdf... direct (1.3s)
[2960/3287] Senior-Managers-Holding-as-at-April-27-2024-Executed-copy.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (2960 jse records so far)
[2961/3287] Senior-Managers-Holding-as-at-December-31-2025-1.pdf... direct (0.1s)
[2962/3287] Senior-Managers-Holding-as-at-December-31-2025-2.pdf... direct (0.1s)
[2963/3287] Senior-Managers-Holding-as-at-January-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[2964/3287] Senior-Managers-Holding-as-at-June-30-2026-1-1.pdf... direct (0.1s)
[2965/3287] Senior-Managers-Holding-as-at-March-31-2026-1-3.pdf... direct (0.1s)
[2966/3287] Senior-Managers-Holding-as-at-November-30-2024.pdf... direct (0.1s)
[2967/3287] Senior-Managers-Holding-as-at-October-26-2024.pdf... direct (0.1s)
[2968/3287] Senior-Managers-Holding-as-at-October-31-2024.pdf... direct (0.2s)
[2969/3287] Senior-Managers-Holding-as-at-October-31-2025.pdf... direct (0.1s)
[2970/3287] Senior-Managers-Holding-as-at-September-30-2025-2.pdf... direct (0.3s)
  -- checkpoint saved (2970 jse records so far)
[2971/3287] Senior-Managers-Holding-as-at-September-30-2025.pdf... direct (0.3s)
[2972/3287] Senior-Managers-Shareholdings-GENAC-Dec-2025.pdf... direct (0.0s)
[2973/3287] Senior-Managers-and-Connected-Shareholdings-as-at-May-31-2025.pdf... direct (0.1s)
[2974/3287] Senior-ManagersHolding-as-at-December-31-2024.pdf... direct (0.1s)
[2975/3287] Senior-Mangement-Shareholdings-as-at-November-1-2025.pdf... needs_ocr_elsewhere (0.0s)
[2976/3287] SeniorManagersHoldingasatAugust22025.pdf... direct (0.2s)
[2977/3287] SeniorManagersHoldingasatJanuary252025-Executed-Copy.pdf... needs_ocr_elsewhere (0.0s)
[2978/3287] SeniorManagersHoldingasatJuly272024-Executed-copy-1.pdf... needs_ocr_elsewhere (0.0s)
[2979/3287] SeniorManagersHoldingasatJune302025-1.pdf... direct (0.5s)
[2980/3287] SeniorManagersHoldingasatMarch312025-1.pdf... direct (0.4s)
  -- checkpoint saved (2980 jse records so far)
[2981/3287] SeniorManagersHoldingasatMay32025.pdf... direct (0.2s)
[2982/3287] SeniorManagersHoldingasatSeptember302024-2.pdf... direct (0.4s)
[2983/3287] SeniorManagersHoldingasatSeptember302025.pdf... direct (0.4s)
[2984/3287] Seprod-2024-Annual-Report.pdf... direct (5.2s)
[2985/3287] Seprod-AGM-Notice-Proxy-Form.pdf... direct (0.2s)
[2986/3287] Seprod-Annual-Report-2025.pdf... direct (5.4s)
[2987/3287] Seprod-EGM-Notice.pdf... direct (0.1s)
[2988/3287] Seprod-EGM-Proxy-Form.pdf... direct (0.1s)
[2989/3287] Seprod-Limited-2024-3rd-Quarter-Unaudited-Financial-Statements.pdf... direct (1.7s)
[2990/3287] Seprod-Limited-2024-Audited-Financial-Statements.pdf... direct (12.9s)
  -- checkpoint saved (2990 jse records so far)
[2991/3287] Seprod-Limited-2025-Audited-Financial-Statements.pdf... direct (19.4s)
[2992/3287] Seprod-Limited-2026-2nd-Quarter-Unaudited-Financial-Statements.pdf... direct (1.1s)
[2993/3287] Seprod-Limited-2nd-Quarter-Unaudited-Financial-Statements.pdf... direct (1.7s)
[2994/3287] Seprod-Limited-3rd-Quarter-2025-Results.pdf... direct (1.4s)
[2995/3287] Seprod-Limited-AGM-Notice-and-Proxy.pdf... direct (0.1s)
[2996/3287] Seprod-Limited-Addendum-to-Press-Release-.pdf... direct (0.1s)
[2997/3287] Seprod-Limited-Closing-of-Bid.pdf... direct (0.1s)
[2998/3287] Seprod-Limited-Delay-of-Audited-Financial-Statements.pdf... needs_ocr_elsewhere (0.0s)
[2999/3287] Seprod-Limited-Extension-Notice-for-filing-Annual-Report.pdf... needs_ocr_elsewhere (0.0s)
[3000/3287] Seprod-Limited-Filing-of-2024-Audited-Financial-Statements_0001.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (3000 jse records so far)
[3001/3287] Seprod-Limited-Management-Changes.pdf... needs_ocr_elsewhere (0.0s)
[3002/3287] Seprod-Limited-Press-Release.pdf... direct (0.1s)
[3003/3287] Seprod-Limited-Quarterly-Financial-Statements-as-at-March-31-2025.pdf... direct (1.4s)
[3004/3287] Seprod-Limited-Unaudited-Financial-Statements-for-the-1st-Quarter-ending-31-March-2026.pdf... direct (1.3s)
[3005/3287] Seprod-Limited-Unaudited-Financial-Statements-for-the-4th-Quarter-ending-December-31-2024.pdf... direct (1.3s)
[3006/3287] Seprod-Limited-Unaudited-Financial-Statements-for-the-year-ended-December-31-2025.pdf... direct (1.6s)
[3007/3287] Seprod-Limited-announces-the-divestment-of-International-Biscuits-Limited.pdf... direct (0.1s)
[3008/3287] Seprod-Offer-and-Bid-Circular-1-May-2025.pdf... direct (6.1s)
[3009/3287] Seprod-Shareholders-Profile-31-December-2025.pdf... direct (0.1s)
[3010/3287] September_2024_analysis.pdf... direct (2.5s)
  -- checkpoint saved (3010 jse records so far)
[3011/3287] September_2025_analysis.pdf... direct (2.3s)
[3012/3287] Shareholder-Announcement-Publication-Q4-Unaudited-Financials-2025.pdf... direct (0.0s)
[3013/3287] Shareholder-Announcement-Publication-Q4-Unaudited-Financials.pdf... direct (0.0s)
[3014/3287] Shareholder-Communication-2023-2024.pdf... direct (0.9s)
[3015/3287] Shareholder-List_-Jamaica-Money-Market-Brokers-Limited-as-at-December-31-2024.pdf... direct (0.0s)
[3016/3287] Shareholder-List_-Jamaica-Money-Market-Brokers-Limited-as-at-December-31st-2025.pdf... direct (0.0s)
[3017/3287] Shareholder-List_-Jamaica-Money-Market-Brokers-Limited-as-at-September-30-2024.pdf... direct (0.0s)
[3018/3287] Shareholder-Notice-with-Zoom-Link-August-2025.docx.pdf... direct (0.1s)
[3019/3287] Shareholders-Advisory-July-30-2026.pdf... direct (0.1s)
[3020/3287] Shareholders-Information.pdf... direct (0.2s)
  -- checkpoint saved (3020 jse records so far)
[3021/3287] Shareholders-Report-September-30-2024.pdf... direct (0.2s)
[3022/3287] Shareholders-Reports-as-at-September-30-2024-Top-Ten-Shareholders-Directors-Senior-Managers.pdf... needs_ocr_elsewhere (0.0s)
[3023/3287] Shareholding-Q4-2024-SPUR-TREE-SPICES-JAMAICA-LIMITED.pdf... direct (0.2s)
[3024/3287] Shareholding-Report-as-at-December-31-2024.pdf... direct (0.1s)

[3025/3287] Shareholdings-Report-March-31-2025.pdf... direct (0.2s)
[3026/3287] Shareholdings-of-the-Top-10-Shareholders-Directors-and-Senior-Managers-as-at-March-31-2025.pdf... direct (0.6s)
[3027/3287] Shareholdings-of-the-Top-10-Shareholders-Directors-and-Senior-Managers-as-at-March-31-2026.pdf... direct (9.3s)
[3028/3287] Shares-purcahsed-by-Direcotr-.pdf... needs_ocr_elsewhere (0.0s)
[3029/3287] Signed-2026-March-31-DCOVE-Quarterly-Report-to-Stockholders-2.pdf... direct (1.3s)
[3030/3287] Speech-by-Livingstone-Morrison-OD-Group-CEO-Jamaica-Stock-Exchange.pdf... direct (0.8s)
  -- checkpoint saved (3030 jse records so far)
[3031/3287] Spur-Tree-Spices-Directors-Report-to-Shareholders-FY2025.pdf... direct (0.3s)
[3032/3287] Spur-Tree-Spices-JSE-Q3-Sept-30-2024-Report-to-Shareholders_.pdf... direct (2.2s)
[3033/3287] Spur-Tree-Spices-JSE-Report-to-Shareholders-Q1-2025-_.pdf... direct (2.1s)
[3034/3287] Spur-Tree-Spices-Jamaica-Limited-Annual-Report-FY2025_.pdf... direct (12.4s)
[3035/3287] Spur-Tree-Spices-Jamaica-Limited-Audited-2024-Financial-Statements_.pdf... direct (9.5s)
[3036/3287] Spur-Tree-Spices-Jamaica-Limited-FY-2025-Consolidated-Financial-Statements-Audited.pdf... direct (8.5s)
[3037/3287] Spur-Tree-Spices-Notice-of-AGM-2025.pdf... needs_ocr_elsewhere (0.0s)
[3038/3287] Spur-Tree-Spices-Report-to-Shareholders-Q2-2025.pdf... direct (2.5s)
[3039/3287] Spur-Tree-Spices-Report-to-Shareholders-Q4-2024__.pdf... direct (2.3s)
[3040/3287] Spur-Tree-Spices-Shareholding-Report-as-at-Dec-31-2025-1.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (3040 jse records so far)
[3041/3287] SpurTreeSpicesLTDAnnualReport2024_.pdf... direct (24.3s)
[3042/3287] SpurTreeSpicesPerformanceReportQ12026.pdf... direct (6.9s)
[3043/3287] SpurTreeSpicesQ4PerformanceReport2025-UNAUDITED.pdf... direct (7.1s)
[3044/3287] Stanley-Motta-Limited-%E2%80%93-Unaudited-Financial-Statements-for-the-Quarter-Ended-June-30-2026-Amended.pdf... direct (1.5s)
[3045/3287] Stanley-Motta-Limited-Dividend-Declaration-1.pdf... direct (0.0s)
[3046/3287] Statement-re-New-Chief-Financial-Officer-November-5-2024.pdf... direct (0.1s)
[3047/3287] Stationery-and-Office-Supplies-2025-Audited-Financial-Statements-1.pdf... direct (6.6s)
[3048/3287] Sterling-Investments-Limited-Financial-Highlights2025_.pdf... direct (0.3s)
[3049/3287] Steven-Whittingham-takes-the-helm-at-GKFG.pdf... direct (0.1s)
[3050/3287] Stock-Exchange-Commentary-Unaudited-Financial-Stat-ended-May-31-2026.pdf... direct (1.9s)
  -- checkpoint saved (3050 jse records so far)
[3051/3287] Supreme-Venturers-Limited-SVL-Proxy-Form.pdf... direct (0.1s)
[3052/3287] Supreme-Ventures-Limited-SVL-2025-Annual-Report-REVISED.pdf... direct (19.0s)
[3053/3287] Supreme-Ventures-Limited-SVL-Audited-Consolidated-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (15.5s)
[3054/3287] Supreme-Ventures-Limited-SVL-Audited-Consolidated-Financial-Statements-for-the-year-ended-December-31-2025.pdf... direct (14.8s)
[3055/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-Nine-months-Ended-September-30-2024.pdf... direct (33.8s)
    ^ SLOW FILE -- Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-Nine-months-Ended-September-30-2024.pdf took 33.8s
[3056/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-Six-Months-Ended-June-30-2026.pdf... direct (21.5s)
[3057/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-Three-Months-Ended-March-31-2026.pdf... direct (2.7s)
[3058/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-nine-months-ended-September-30-2025-REVISED.pdf... direct (12.1s)
[3059/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025.pdf... needs_ocr_elsewhere (0.0s)
[3060/3287] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025.pdf... needs_ocr_elsewhere (32.1s)
    ^ SLOW FILE -- Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025.pdf took 32.1s
  -- checkpoint saved (3060 jse records so far)
[3061/3287] Supreme-Ventures-Limited-SVL-Notice-of-AGM.pdf... direct (0.8s)
[3062/3287] Supreme-Ventures-Limited-SVL-Notice-of-Annual-General-Meeting.pdf... direct (0.2s)
[3063/3287] Supreme-Ventures-Limited-SVL-PROXY-FORM.pdf... direct (0.1s)
[3064/3287] Supreme-Ventures-Limited-SVL-Shareholding-Report-as-at-December-31-2025.pdf... direct (0.8s)
[3065/3287] Synergy-Vision-Legacy-Annual-Report-2024-Digital.pdf... direct (19.1s)
[3066/3287] TB-KPMG-Audited-FS-FY2024.pdf... direct (9.4s)
[3067/3287] TBCL_Q3_FY2026_Interim_Report_JSE_Final-1.pdf... direct (2.2s)
[3068/3287] TB_PR1_Director_AI_June2026.pdf... direct (0.2s)
[3069/3287] TB_PR2_SaleLeaseback_June2026-1.pdf... direct (0.8s)
[3070/3287] TB_PR3_Amazon_Ecommerce_June2026.pdf... direct (0.3s)
  -- checkpoint saved (3070 jse records so far)
[3071/3287] TB_Q2_FY2026_JSE_Interim_Report_Final.pdf... direct (6.1s)
[3072/3287] TJH-2024-Annual-Report-Revised.pdf... direct (147.1s)
    ^ SLOW FILE -- TJH-2024-Annual-Report-Revised.pdf took 147.1s
[3073/3287] TJH-Amended-Form-of-Proxy.pdf... direct (1.5s)
[3074/3287] TJH-Amended-Notice-of-AGM.pdf... direct (6.9s)
[3075/3287] TJH-Audited-Financial-Statements-For-The-Year-Ended-December-31-2025.pdf... direct (12.7s)
[3076/3287] TJH-Audited-Financial-Statements-for-the-Year-Ended-December-31-2024.pdf... direct (27.2s)
[3077/3287] TJH-Group-Unaudited-Financial-Statement-Q3-2025.pdf... direct (3.2s)
[3078/3287] TJH-Group-Unaudited-Financial-Statement-Q4-2025.pdf... direct (2.8s)
[3079/3287] TJH-Group-Unaudited-Financial-Statements-Q1-2025.pdf... direct (3.2s)
[3080/3287] TJH-Group-Unaudited-Financial-Statements-Q1-2026.pdf... direct (2.6s)
  -- checkpoint saved (3080 jse records so far)
[3081/3287] TJH-Group-Unaudited-Financial-Statements-Q2-2025.pdf... direct (9.0s)
[3082/3287] TJH-Group-Unaudited-Financial-Statements-Q2-2026-1.pdf... direct (2.7s)
[3083/3287] TJH-OFS-Basis-of-Allotment-Execution-Version_for-JSE-Publication.pdf... direct (0.2s)
[3084/3287] TJH-Press-Release-8.0-JMD-Cumulative-Redeemable-Preference-Shares.pdf... direct (0.3s)
[3085/3287] TJH-Top-Ten-Shareholders-as-at-December-31-2024.pdf... direct (0.2s)
[3086/3287] TJH-Top-Ten-Shareholders-as-at-December-31-2025.pdf... direct (0.1s)
[3087/3287] TJHL-Group-Unaudited-Financial-Statements-Q3-2024.pdf... direct (3.3s)
[3088/3287] TJHL-Group-Unaudited-Financial-Statements-Q4-2024-Revised.pdf... direct (3.1s)
[3089/3287] TM-Ellesco_PR_310125.pdf... direct (0.3s)
[3090/3287] TOBC-CPJ-Final-10-Jan-2025-4-pm.pdf... direct (16.3s)
  -- checkpoint saved (3090 jse records so far)
[3091/3287] TOP-10-AT-31-AUGUST-2025.pdf... direct (0.1s)
[3092/3287] TOP-10-AT-31-August-2024.pdf... direct (0.1s)
[3093/3287] TOP-10-Q1-2.pdf... direct (0.1s)
[3094/3287] TOP-10-Report-as-at-April-30-2026.pdf... direct (0.1s)
[3095/3287] TOP-TEN-AND-DIRECTORS-SHAREHOLDINGS-28FEBRUARY2026.pdf... direct (0.2s)
[3096/3287] TOP-TEN-SHAREHOLDINGS.pdf... direct (0.8s)
[3097/3287] TRADING-IN-SHARES-revised2.pdf... direct (0.0s)
[3098/3287] TROPICAL-Annual-Report-FY2024-Final.pdf... direct (16.1s)
[3099/3287] TROPICAL-Directors-Holding-as-at-September-30-2024.pdf... direct (0.2s)
[3100/3287] TROPICAL-Q1-FS-FY2025-RESTATED.pdf... direct (9.4s)
  -- checkpoint saved (3100 jse records so far)
[3101/3287] TROPICAL-Q2-FS-FY2025.pdf... direct (9.9s)
[3102/3287] TROPICAL-Q3-FS-FY2025.pdf... direct (4.6s)
[3103/3287] TROPICAL-Senior-Managers-Holding-as-at-September-30-2024.pdf... direct (0.4s)
[3104/3287] TROPICAL-Top-10-Shareholders-as-at-September-30-2024.pdf... direct (0.1s)
[3105/3287] TROPICAL-US-trademark-approval-press-release.pdf... direct (0.2s)
[3106/3287] The-Barita-Financial-Group-Name-Changes-Notification-28-May-2026.pdf... direct (0.3s)
[3107/3287] The-LAB-2024-Form-of-Proxy-1.pdf... direct (0.3s)
[3108/3287] The-LAB-2024-Notice-of-AGM.pdf... direct (0.1s)
[3109/3287] The-LAB-Notice-of-Delay-2024-Annual-Report-2.pdf... direct (0.1s)
[3110/3287] The-LAB_Financial-Performance_July-31_.pdf... direct (5.9s)
  -- checkpoint saved (3110 jse records so far)

[3111/3287] The-LAB_Financial-Performance_October-2025.pdf... direct (7.7s)
[3112/3287] The-Limners-Bards-Limited-Annual-Report-2025.pdf... direct (7.7s)
[3113/3287] The-Limners-Bards-Limited-Audited-Financial-Statement-2025-2.pdf... direct (4.9s)
[3114/3287] The-Limners-Bards-Limited-Unaudited-Financial-Statement-for-six-months-ended-April-30-2026.pdf... direct (1.7s)
[3115/3287] The-Limners-Bards-LimitedThe-LAB-Dividend-Declaration-1.pdf... direct (0.1s)
[3116/3287] The-Limners-and-Bards-LimitedThe-LAB-Notification-of-Dividend-Consideration.pdf... direct (0.1s)
[3117/3287] The-Limners-and-Bards-LimitedTheLAB-Unaudited-Financial-Statements-for-Three-Months-Ended-January-31-2026.pdf... direct (1.5s)
[3118/3287] The-Limners-and-Bards-LtdThe-LAB-Annual-Report-2024.pdf... direct (3.3s)
[3119/3287] The-Limners-and-Bards-LtdThe-LAB-Unaudited-Financial-Statement-for-First-Quarter-Ended-January-31-2025.pdf... direct (5.9s)
[3120/3287] The-Limners-and-Bards-LtdThe-LAB-Unaudited-Financial-Statement-for-Third-Quarter-Ended-July-31-2025.pdf... direct (8.1s)
  -- checkpoint saved (3120 jse records so far)
[3121/3287] The-Limners-and-Bards-LtdThe-LAB-Unaudited-Financial-Statement-for-second-Quarter-Ended-April-30-2025Revised.pdf... direct (8.2s)
[3122/3287] The-Palace-Amusement-Company-1921-Limited-Concolidated-Financial-Statements-30-June-2024.pdf... direct (9.9s)
[3123/3287] The-Palace-Amusement-Company-1921-Limited-Consolidated-Financial-Statements-30-June-2025.pdf... direct (9.6s)
[3124/3287] Top-10-Members-as-at-December-31-2024.pdf... direct (0.2s)
[3125/3287] Top-10-Shareholders-GENAC-Dec-2025.pdf... direct (0.0s)
[3126/3287] Top-10-Shareholders-as-At-January-31-2026.pdf... needs_ocr_elsewhere (0.0s)
[3127/3287] Top-10-Shareholders-as-at-April-27-2024.pdf... direct (0.1s)
[3128/3287] Top-10-Shareholders-as-at-October-26-2024.pdf... direct (0.1s)
[3129/3287] Top-10-Shareholders-as-at-September-30-2025.pdf... direct (0.1s)
[3130/3287] Top-Shareholder-as-at-November-1-2025.pdf... direct (0.1s)
  -- checkpoint saved (3130 jse records so far)
[3131/3287] Top-Ten-10-Shareholdings-as-at-May-31-2025.pdf... direct (0.1s)
[3132/3287] Top-Ten-Pref-B-%40-December-31-2025-1.pdf... direct (0.1s)
[3133/3287] Top-Ten-Pref-B-%40-December-31-2025.pdf... direct (0.1s)
[3134/3287] Top-Ten-Pref-B-%40-June-30-2025.pdf... direct (0.1s)
[3135/3287] Top-Ten-Pref-B-%40-March-31-2026-1.pdf... direct (0.1s)
[3136/3287] Top-Ten-Pref-B-%40-September-30-2025-2.pdf... direct (0.1s)
[3137/3287] Top-Ten-QWI-%40-December-31-2025.pdf... direct (0.1s)
[3138/3287] Top-Ten-QWI-%40-June-30-2026.pdf... direct (0.1s)
[3139/3287] Top-Ten-QWI-%40-March-31-2026-1.pdf... direct (0.1s)
[3140/3287] Top-Ten-QWI-%40-September-30-2024.pdf... direct (0.1s)
  -- checkpoint saved (3140 jse records so far)
[3141/3287] Top-Ten-Report-Pref-C-5-%40-December-31-2025-1.pdf... direct (0.1s)
[3142/3287] Top-Ten-Report-Pref-C-5-%40-December-31-2025.pdf... direct (0.6s)
[3143/3287] Top-Ten-Report-Pref-C-5-%40-September-30-2025-2.pdf... direct (0.1s)
[3144/3287] Top-Ten-Report-Pref-D-5-%40-December-31-2025-1.pdf... direct (0.1s)
[3145/3287] Top-Ten-Report-Pref-D-5-%40-December-31-2025.pdf... direct (0.1s)
[3146/3287] Top-Ten-Report-Pref-D-5-%40-June-30-2025.pdf... direct (0.1s)
[3147/3287] Top-Ten-Report-Pref-D-5-%40-March-31-2026-1.pdf... direct (0.1s)
[3148/3287] Top-Ten-Report-Pref-D-5-%40-September-30-2025-2.pdf... direct (0.1s)
[3149/3287] Top-Ten-Report-Pref.-E-6-%40-December-31-2025-1.pdf... direct (0.2s)
[3150/3287] Top-Ten-Report-Pref.-E-6-%40-December-31-2025.pdf... direct (0.2s)
  -- checkpoint saved (3150 jse records so far)
[3151/3287] Top-Ten-Report-Pref.-E-6-%40-June-30-2025.pdf... direct (0.3s)
[3152/3287] Top-Ten-Report-Pref.-E-6-%40-June-30-2026.pdf... direct (0.1s)
[3153/3287] Top-Ten-Report-Pref.-E-6-%40-March-31-2026-1.pdf... direct (0.1s)
[3154/3287] Top-Ten-Report-Pref.-E-6-%40-September-30-2025-2.pdf... direct (0.2s)
[3155/3287] Top-Ten-Shareholders-Listing-as-at-June-30-2024.pdf... direct (0.1s)
[3156/3287] Top-Ten-Shareholders-Listing-as-at-March-31-2024.pdf... direct (0.1s)
[3157/3287] Top-Ten-Shareholdings-as-at-Dec.-31-2025.pdf... direct (0.2s)
[3158/3287] Top10-Shareholders-.pdf... direct (0.2s)
[3159/3287] Top10-Shareholding-Report-31Mar2026.pdf... direct (0.1s)
[3160/3287] Top10ShareholdersasatJuly272024.pdf... direct (0.1s)
  -- checkpoint saved (3160 jse records so far)
[3161/3287] Top10_Share_30Spet25.pdf... direct (0.1s)
[3162/3287] Top10_Shareholders_30Sept2024.pdf... direct (0.1s)
[3163/3287] Top10_Shareholdings_Report_31Mar2025.pdf... direct (0.1s)
[3164/3287] TopShareholderasatJanuary252025-Executed-Copy.pdf... needs_ocr_elsewhere (0.0s)
[3165/3287] TopShareholderasatMay32025.pdf... direct (0.1s)
[3166/3287] TopTenQWI%40December312024.pdf... direct (0.1s)
[3167/3287] TopTenQWI%40June302025-1.pdf... direct (0.3s)
[3168/3287] TopTenQWI%40March312025-1.pdf... direct (0.1s)
[3169/3287] TopTenQWI%40September302025.pdf... direct (0.1s)
[3170/3287] Trading-Notice-dd-10th-March-2026.pdf... direct (0.0s)
  -- checkpoint saved (3170 jse records so far)
[3171/3287] Tropical-APO-Press-Release-.pdf... direct (0.2s)
[3172/3287] Tropical-Battery-2025-AGM-Notice-Resolutions-Revised.pdf... direct (0.2s)
[3173/3287] Tropical-Battery-Annual-Report-2025-1.pdf... needs_ocr_elsewhere (0.2s)
[3174/3287] Tropical-Battery-Audited-FS-FYE-2025.pdf... direct (10.4s)
[3175/3287] Tropical-Battery-Interim-Report-Q1-FY-2026.pdf... needs_ocr_elsewhere (0.1s)
[3176/3287] Tropical-Battery-SPO-Prospectus-FINAL.pdf... direct (19.4s)
[3177/3287] TropicalMobility-Snap-on_PR_050525.pdf... direct (0.1s)
[3178/3287] UNAUDITED-FINANCIAL-STATEMENTS-ENDED-MAY-2026.pdf... direct (1.1s)
[3179/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024.pdf... needs_ocr_elsewhere (0.0s)
[3180/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (3180 jse records so far)
[3181/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-FEBRUARY-2025.pdf... needs_ocr_elsewhere (0.0s)
[3182/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-FEBRUARY-2026-3.pdf... direct (1.3s)
[3183/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024.pdf... needs_ocr_elsewhere (0.0s)
[3184/3287] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025.pdf... needs_ocr_elsewhere (0.0s)
[3185/3287] UNAUDITED-STATMENT-OF-COMPREHENSIVE-INCOME-ENDED-MAY-2025.pdf... needs_ocr_elsewhere (0.0s)
[3186/3287] USA-Agenda-Philadelphia-May-6-2025.pdf... direct (0.4s)
[3187/3287] Unaudited-Financial-Statements-June-2025-1.pdf... direct (2.0s)
[3188/3287] Unaudited-Financial-Statements-June-2025.pdf... needs_ocr_elsewhere (0.0s)
[3189/3287] Unaudited-Financial-Statements-for-1st-Quarter-ended-September-30-2024.pdf... direct (1.2s)
[3190/3287] Unaudited-Financials-Q1-2025.pdf... direct (1.3s)
  -- checkpoint saved (3190 jse records so far)
[3191/3287] Unaudited-Financials-Q2-2025-signed.pdf... direct (0.6s)
[3192/3287] Unaudited-Financials-Q2-2026-signed.pdf... direct (1.4s)
[3193/3287] Unaudited-Financials-Q3-2024.pdf... direct (1.4s)
[3194/3287] Unaudited-Financials-Q3-2025-signed.pdf... direct (1.0s)
[3195/3287] Unaudited-Financials-Q4-2024.pdf... direct (1.1s)
[3196/3287] Unaudited-Financials-Q4-2025-signed.pdf... needs_ocr_elsewhere (0.0s)
[3197/3287] Unaudited-Financials-ended-June-30-2026.pdf... needs_ocr_elsewhere (0.0s)
[3198/3287] Unaudited-Quarterly-Report-For-3rd-Quarter-Ending-February-29-2024-revised.pdf... direct (0.4s)
[3199/3287] Unaudited-financial-statement-for-6-months-ended-November-30-2024.pdf... direct (1.2s)
[3200/3287] Updated-RPL-Annual-Report-2024.pdf... direct (3.2s)
  -- checkpoint saved (3200 jse records so far)
[3201/3287] VM-Investments-Limited-Notice-of-AGM.pdf... direct (0.1s)
[3202/3287] VM-Investments-Limited-VMIL-Bond-IPO-Oversubscribed-Offer-Closes.pdf... direct (0.1s)
[3203/3287] VMIL-4B-Corporate-Bond-Basis-of-Allotment.pdf... direct (0.4s)
[3204/3287] VMIL-Annual-Report-2025.pdf... direct (62.2s)
    ^ SLOW FILE -- VMIL-Annual-Report-2025.pdf took 62.2s
[3205/3287] VMIL-Appointment-of-Two-New-Directors-May-15-2025.pdf... direct (0.1s)

[3206/3287] VMIL-Audited-Financial-Statements-for-the-year-ended-Dec-31-2025.pdf... direct (15.1s)
[3207/3287] VMIL-Audited-Financial-Statements-for-the-year-ended-December-31-2024.pdf... direct (13.7s)
[3208/3287] VMIL-Consideration-of-Dividend-Payment.pdf... needs_ocr_elsewhere (0.0s)
[3209/3287] VMIL-J5.4B-Unsecured-Bonds-Basis-of-Allocation-Final.pdf... direct (0.1s)
[3210/3287] VMIL-JSE-Press-Release-Q3-2024-Final.pdf... direct (2.2s)
  -- checkpoint saved (3210 jse records so far)
[3211/3287] VMIL-JSE-Press-Release-Q4-2024.pdf... direct (2.6s)
[3212/3287] VMIL-Notice-of-the-Annual-General-Meeting-2024.pdf... direct (0.5s)
[3213/3287] VMIL-Press-Release-Delay-in-Submission-of-VMIL-2024-Annual-Report.pdf... needs_ocr_elsewhere (0.0s)
[3214/3287] VMIL-Press-Release-Leadership-Changes-June-6-2025-2.pdf... direct (0.2s)
[3215/3287] VMIL-Public-Bond-Offer-Prospectus.pdf... direct (50.3s)
    ^ SLOW FILE -- VMIL-Public-Bond-Offer-Prospectus.pdf took 50.3s
[3216/3287] VMIL-Q1-2025-Release.pdf... direct (4.1s)
[3217/3287] VMIL-Q1-2026-JSE-Press-Release-Dividend-Declaration-.pdf... direct (1.3s)
[3218/3287] VMIL-Q2-2025-Press-Release.pdf... direct (2.9s)
[3219/3287] VMIL-Q2-2026-JSE-Press-Release-August-13-2026.pdf... direct (1.5s)
[3220/3287] VMIL-Q3-2025-Press-Release.pdf... direct (4.1s)
  -- checkpoint saved (3220 jse records so far)
[3221/3287] VMIL-Trading-Activity-June-2025.pdf... direct (0.0s)
[3222/3287] VMIL-Trading-Activity-May-2025.pdf... needs_ocr_elsewhere (0.0s)
[3223/3287] VMIL-Trading-Activity-September-2025.pdf... direct (0.0s)
[3224/3287] VMIL_2024_IPO_Prospectus_2024.pdf... direct (27.7s)
[3225/3287] Venture-Capital-Pitch-Room-Application-Form-2026.pdf... direct (0.3s)
[3226/3287] Visual-Vibe-x-Knutsford-Express-Partnership-Update.docx.pdf... direct (0.3s)
[3227/3287] WGL-FY26-Q3-Report.pdf... direct (0.8s)
[3228/3287] WIG-%E2%80%93-Unaudited-Financial-Statements-for-the-period-ended-30-June-2025-and-Shareholdings-of-Top-10-Shareholders-Directors-and-Senior-Managers-1.pdf... direct (0.5s)
[3229/3287] WIG-%E2%80%93-Unaudited-Financial-Statements-for-the-period-ended-31-December-2024-and-Shareholdings-of-Top-10-Shareholders-Directors-a.pdf... direct (1.9s)
[3230/3287] WIG-%E2%80%93-Unaudited-Financial-Statements-for-the-period-ended-December-31-2025-and-Shareholdings-of-Top-10-Shareholders-Directors-.pdf... direct (3.5s)
  -- checkpoint saved (3230 jse records so far)
[3231/3287] WIG-Unaudited-Financial-Statements-for-the-period-ended-September-30-2024-and-Shareholdings-of-Top-10-Shareholders-Directors-and-Senior-Managers.pdf... direct (2.3s)
[3232/3287] WIG-Unaudited-Financial-Statements-for-the-period-ended-September-30-2025-and-Shareholdings-of-Top-10-Shareholders-Directors-and-Senior-Managers-1.pdf... direct (2.3s)
[3233/3287] WIGTON-ENERGY-LIMITED-ANNUAL-REPORT-2024-2025-1.pdf... direct (17.1s)
[3234/3287] WIGTON-ENERGY-LIMITED-ANNUAL-REPORT-2025-2026.pdf... direct (14.2s)
[3235/3287] WIP-Terminal-Final-Abridged-Statement-1.pdf... direct (0.1s)
[3236/3287] WIP-Terminal-IM-December-2025.pdf... direct (7.7s)
[3237/3287] WIPT-Notice-of-AGM-2025.pdf... direct (0.2s)
[3238/3287] WIPT-Proxy-Form-AGM-2025.pdf... direct (0.2s)
[3239/3287] West-Indies-Petroleum-Terminal-Limited-2025-Q3-Report.pdf... direct (1.9s)
[3240/3287] West-Indies-Petroleum-Terminal-Limited-2025-Q4-Report.pdf... direct (2.9s)
  -- checkpoint saved (3240 jse records so far)
[3241/3287] West-Indies-Petroleum-Terminal-Limited-2026-Q1-Report.pdf... direct (0.9s)
[3242/3287] West-Indies-Petroleum-Terminal-Limited-2026-Q2-Report.pdf... direct (1.2s)
[3243/3287] West-Indies-Petroleum-Terminal-Limited-Annual-Report-2025.pdf... direct (9.8s)
[3244/3287] West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024.pdf... needs_ocr_elsewhere (76.7s)
    ^ SLOW FILE -- West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024.pdf took 76.7s
[3245/3287] West-Indies-Petroleum-Terminal-Limited_2025-Audited-Financial-Statements.pdf... direct (8.7s)
[3246/3287] Wigton-Amended-2024-Annual-Report.pdf... direct (15.7s)
[3247/3287] Wigton-Energy-Limited-Amended-Articles-of-Incorporation-October-2024.pdf... direct (5.7s)
[3248/3287] Wigton-Energy-Limited-Form-of-Proxy-2025.pdf... direct (0.5s)
[3249/3287] Wigton-Energy-Limited-How-to-Register-2025.pdf... direct (0.1s)
[3250/3287] Wigton-Energy-Limited-Notice-of-Annual-General-Meeting-2025.pdf... direct (0.3s)
  -- checkpoint saved (3250 jse records so far)
[3251/3287] Wigton-Energy-Limited-WIG-Audited-Financial-Statements-for-the-year-ended-March-31-2025.pdf... direct (7.4s)
[3252/3287] Wigton-Energy-Limited-WIG-Audited-Financial-Statements-for-the-year-ended-March-31-2026.pdf... direct (8.5s)
[3253/3287] Wisynco-Annual-Report-2025.pdf... direct (16.7s)
[3254/3287] Wisynco-Group-Limited-Annual-Report-FY2024.pdf... direct (15.3s)
[3255/3287] Wisynco-Group-Limited-Audited-Financial-Statements-FY-2024-1.pdf... direct (11.5s)
[3256/3287] Wisynco-Group-Limited-Audited-Financial-Statements-FY-2025.pdf... direct (8.8s)
[3257/3287] Wisynco-Group-Limited-Report-to-Stockholders-for-year-ended-June-30-2024-revised.pdf... direct (0.5s)
[3258/3287] Wisynco-Group-Limited-Report-to-Stockholders-for-year-ended-June-30-2025-Final.pdf... direct (0.5s)
[3259/3287] Wisynco-Interim-Report-Q1-FY25.pdf... direct (1.5s)
[3260/3287] Wisynco-Q2FY25-Report.pdf... direct (1.3s)
  -- checkpoint saved (3260 jse records so far)
[3261/3287] Wisynco-Q3FY25-Report.pdf... direct (1.4s)
[3262/3287] Woodcats-Basis-of-Allotment.pdf... direct (0.4s)
[3263/3287] Woodcats-International-Limited-Prospectus.pdf... direct (8.1s)
[3264/3287] Woodcats-International-Unaudited-Financial-Statements-2nd-Quarter-Ended-June-30-2026.pdf... direct (2.4s)
[3265/3287] Woodcats-Unaudited-Financial-Statements-Q1-2026.pdf... direct (1.3s)
[3266/3287] cccl-share-info-and-Top-Ten-as-at-2026-June-30.pdf... direct (0.2s)
[3267/3287] cccl-share-info-at-2025-December-31.pdf... direct (0.3s)
[3268/3287] cccl-share-info-at-2026-March-31-1.pdf... direct (0.2s)
[3269/3287] final-Mayberry-Secured-Bond-Prospectus.pdf... direct (10.4s)
[3270/3287] iCreate-Group-Unaudited-Q2-Financial-Statements.pdf... direct (1.2s)
  -- checkpoint saved (3270 jse records so far)
[3271/3287] letter-re-payment-of-Dividend-November-2025.pdf... needs_ocr_elsewhere (0.0s)
[3272/3287] letter-to-JSE-re-Dividend-payment-Document_2025-08-18_160231.pdf... needs_ocr_elsewhere (0.0s)
[3273/3287] ooo-2024-annual-report-11.pdf... direct (17.4s)
[3274/3287] press-release-BAIC-2024.pdf... direct (0.1s)
[3275/3287] re-divided-letter-with-correction-of-date.pdf... needs_ocr_elsewhere (0.0s)
[3276/3287] sale-of-shares-to-a-dreictor-.pdf... needs_ocr_elsewhere (0.0s)
[3277/3287] st-Qtr-Financials-Signed.pdf... direct (0.9s)
[3278/3287] tTech-Amended-Directors-Circular-Final.pdf... direct (3.0s)
[3279/3287] tTech-Directors-Circular-Errata-Page-24-Dec-2024.pdf... direct (0.2s)
[3280/3287] tTech-Offer-Circular-Mandatory-Offer-12-Dec-2024.pdf... direct (3.5s)
  -- checkpoint saved (3280 jse records so far)
[3281/3287] tTech-Shareholders-Report-as-a-September-30-2024.pdf... direct (0.5s)
[3282/3287] tTech-Unaudited-Financial-Statement-as-a-September-30-2024.pdf... direct (0.8s)
[3283/3287] threat_extracted_Board-of-Directors-%40-March-31-2025-Updated.pdf... direct (0.2s)
[3284/3287] threat_extracted_JPS-Senior-Manager-%40-March-31-2025-Updated.pdf... direct (0.1s)
[3285/3287] threat_extracted_JPS-Senior-Manager-%40-September-30-2024-1.pdf... direct (0.1s)
[3286/3287] threat_extracted_JPSCo-2025-Signed-Financial-Statements.pdf... direct (8.0s)
[3287/3287] tinywow_Kintyre-Holdings-JA-Limited-Annual-Report-for-the-Period-Ended-December-31-2024-3_88194693.pdf... direct (2.0s)

=== Processing BSE (148 remaining of 148 total) ===
[1/148] BCO_2024_Annual.pdf... direct (12.8s)
[2/148] BCO_2025_Annual.pdf... direct (4.0s)
[3/148] BCO_2025_Q1.pdf... needs_ocr_elsewhere (0.0s)
[4/148] BCO_2025_Q2.pdf... needs_ocr_elsewhere (0.0s)
[5/148] BCO_2025_Q3.pdf... needs_ocr_elsewhere (0.0s)
[6/148] BCO_2025_Q4.pdf... needs_ocr_elsewhere (0.0s)
[7/148] BCO_2026_Q1.pdf... needs_ocr_elsewhere (0.0s)
[8/148] BCO_2026_Q2.pdf... needs_ocr_elsewhere (0.0s)
[9/148] BCO_2026_Q3.pdf... needs_ocr_elsewhere (0.0s)

[10/148] BDI_2024_Annual.pdf... direct (6.3s)
  -- checkpoint saved (10 bse records so far)
[11/148] BDI_2024_Audited.pdf... direct (5.4s)
[12/148] BDI_2024_Q4.pdf... direct (0.2s)
[13/148] BDI_2025_Audited.pdf... direct (5.2s)
[14/148] BDI_2025_Q1.pdf... direct (0.2s)
[15/148] BDI_2025_Q2.pdf... needs_ocr_elsewhere (0.0s)
[16/148] BDI_2025_Q3.pdf... direct (0.7s)
[17/148] BDI_2025_Q4.pdf... needs_ocr_elsewhere (4.5s)
[18/148] BDI_2026_Q1.pdf... needs_ocr_elsewhere (5.1s)
[19/148] BDI_2026_Q2.pdf... direct (0.4s)
[20/148] BFL_2024_Annual.pdf... direct (5.7s)
  -- checkpoint saved (20 bse records so far)
[21/148] BFL_2025_Annual.pdf... needs_ocr_elsewhere (72.2s)
    ^ SLOW FILE -- BFL_2025_Annual.pdf took 72.2s
[22/148] BFL_2025_Audited.pdf... direct (8.4s)
[23/148] BFL_2025_Q1.pdf... direct (0.2s)
[24/148] BFL_2025_Q2.pdf... direct (0.2s)
[25/148] BFL_2025_Q3.pdf... direct (0.2s)
[26/148] BFL_2025_Q4.pdf... direct (0.2s)
[27/148] BFL_2026_Q1.pdf... direct (0.5s)
[28/148] BFL_2026_Q2.pdf... direct (0.2s)
[29/148] BFL_2026_Q3.pdf... direct (0.2s)
[30/148] BHL_2024_Annual.pdf... direct (8.1s)
  -- checkpoint saved (30 bse records so far)
[31/148] BHL_2024_Audited.pdf... direct (7.5s)
[32/148] BHL_2024_Q4.pdf... direct (0.3s)
[33/148] BHL_2025_Audited.pdf... direct (6.9s)
[34/148] BHL_2025_Q1.pdf... direct (0.3s)
[35/148] BHL_2025_Q2.pdf... needs_ocr_elsewhere (0.0s)
[36/148] BHL_2025_Q3.pdf... direct (0.8s)
[37/148] BHL_2025_Q4.pdf... needs_ocr_elsewhere (5.6s)
[38/148] BHL_2026_Q1.pdf... needs_ocr_elsewhere (5.9s)
[39/148] BHL_2026_Q2.pdf... direct (0.3s)
[40/148] CIBC_2024_Annual.pdf... direct (22.3s)
  -- checkpoint saved (40 bse records so far)
[41/148] CIBC_2024_Audited.pdf... direct (0.6s)
[42/148] CIBC_2024_Q3.pdf... needs_ocr_elsewhere (11.8s)
[43/148] CIBC_2025_Annual.pdf... direct (22.2s)
[44/148] CIBC_2025_Audited.pdf... needs_ocr_elsewhere (10.8s)
[45/148] CIBC_2025_Q1.pdf... needs_ocr_elsewhere (18.3s)
[46/148] CIBC_2025_Q2.pdf... needs_ocr_elsewhere (12.8s)
[47/148] CIBC_2025_Q3.pdf... needs_ocr_elsewhere (13.0s)
[48/148] CIBC_2026_Q1.pdf... needs_ocr_elsewhere (12.3s)
[49/148] CIBC_2026_Q2.pdf... needs_ocr_elsewhere (14.4s)
[50/148] CPFD_2024_Annual.pdf... direct (18.9s)
  -- checkpoint saved (50 bse records so far)
[51/148] CPFD_2024_Q2.pdf... direct (0.6s)
[52/148] CPFD_2024_Q3.pdf... direct (0.6s)
[53/148] CPFD_2025_Annual.pdf... direct (30.8s)
    ^ SLOW FILE -- CPFD_2025_Annual.pdf took 30.8s
[54/148] CPFD_2025_Q1.pdf... direct (1.4s)
[55/148] CPFD_2025_Q2.pdf... direct (0.7s)
[56/148] CPFD_2025_Q3.pdf... direct (0.7s)
[57/148] CPFD_2025_Q4.pdf... direct (0.5s)
[58/148] CPFD_2026_Q1.pdf... direct (0.8s)
[59/148] CPFD_2026_Q2.pdf... direct (0.5s)
[60/148] CPFV_2024_Annual.pdf... direct (18.5s)
  -- checkpoint saved (60 bse records so far)
[61/148] CPFV_2024_Q3.pdf... direct (1.6s)
[62/148] CPFV_2024_Q4.pdf... direct (4.2s)
[63/148] CPFV_2025_Annual.pdf... direct (30.8s)
    ^ SLOW FILE -- CPFV_2025_Annual.pdf took 30.8s
[64/148] CPFV_2025_Q1.pdf... direct (0.9s)
[65/148] CPFV_2025_Q2.pdf... direct (1.0s)
[66/148] CPFV_2025_Q3.pdf... direct (0.7s)
[67/148] CPFV_2025_Q4.pdf... direct (0.9s)
[68/148] CPFV_2026_Q1.pdf... direct (1.8s)
[69/148] CPFV_2026_Q2.pdf... direct (1.0s)
[70/148] CSP_2024_Annual.pdf... direct (25.7s)
  -- checkpoint saved (70 bse records so far)
[71/148] CSP_2024_Q1.pdf... direct (0.4s)
[72/148] CSP_2024_Q2.pdf... direct (0.4s)
[73/148] CSP_2024_Q3.pdf... direct (0.4s)
[74/148] CSP_2025_Annual.pdf... direct (24.8s)
[75/148] CSP_2025_Q1.pdf... direct (0.3s)
[76/148] CSP_2025_Q2.pdf... direct (0.4s)
[77/148] CSP_2025_Q3.pdf... direct (0.4s)
[78/148] CSP_2026_Q1.pdf... direct (0.4s)
[79/148] CSP_2026_Q2.pdf... direct (0.4s)
[80/148] EMABDR_2024_Annual.pdf... direct (22.7s)
  -- checkpoint saved (80 bse records so far)
[81/148] EMABDR_2024_Q3.pdf... direct (11.5s)
[82/148] EMABDR_2024_Q4.pdf... direct (24.8s)
[83/148] EMABDR_2025_Annual.pdf... direct (22.1s)
[84/148] EMABDR_2025_Q1.pdf... direct (8.6s)
[85/148] EMABDR_2025_Q2.pdf... direct (9.0s)
[86/148] EMABDR_2025_Q3.pdf... direct (11.2s)
[87/148] EMABDR_2025_Q4.pdf... direct (23.0s)
[88/148] EMABDR_2026_Q1.pdf... direct (8.8s)
[89/148] EMABDR_2026_Q2.pdf... direct (11.9s)
[90/148] GEL_2024_Annual.pdf... direct (17.3s)
  -- checkpoint saved (90 bse records so far)
[91/148] GEL_2024_Q4.pdf... direct (0.5s)
[92/148] GEL_2025_Annual.pdf... direct (20.5s)
[93/148] GEL_2025_Q1.pdf... direct (0.4s)
[94/148] GEL_2025_Q2.pdf... direct (0.4s)
[95/148] GEL_2025_Q3.pdf... direct (0.4s)
[96/148] GEL_2025_Q4.pdf... direct (0.5s)
[97/148] GEL_2026_Q1.pdf... direct (0.4s)
[98/148] GEL_2026_Q2.pdf... direct (1.4s)
[99/148] GEL_2026_Q3.pdf... direct (0.6s)
[100/148] ICBL_2024_Annual.pdf... direct (24.1s)
  -- checkpoint saved (100 bse records so far)
[101/148] ICBL_2024_Audited.pdf... direct (20.4s)
[102/148] ICBL_2024_Q2.pdf... direct (0.3s)
[103/148] ICBL_2024_Q3.pdf... direct (0.3s)
[104/148] ICBL_2024_Q4.pdf... direct (5.0s)
[105/148] ICBL_2025_Q1.pdf... direct (0.3s)
[106/148] ICBL_2025_Q2.pdf... direct (0.5s)
[107/148] ICBL_2025_Q3.pdf... direct (0.4s)
[108/148] ICBL_2026_Q1.pdf... direct (0.6s)
[109/148] OCM_2024_Annual.pdf... direct (9.7s)
[110/148] OCM_2024_Q3.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (110 bse records so far)
[111/148] OCM_2024_Q4.pdf... direct (0.4s)
[112/148] OCM_2025_Annual.pdf... direct (13.4s)
[113/148] OCM_2025_Q1.pdf... direct (0.3s)
[114/148] OCM_2025_Q2.pdf... direct (0.4s)
[115/148] OCM_2025_Q3.pdf... direct (0.4s)
[116/148] OCM_2025_Q4.pdf... direct (1.0s)
[117/148] OCM_2026_Q1.pdf... direct (0.3s)
[118/148] OCM_2026_Q2.pdf... direct (0.5s)
[119/148] PBSLO_2024_Annual.pdf... direct (27.9s)
[120/148] PBSLO_2024_Q2.pdf... direct (0.4s)
  -- checkpoint saved (120 bse records so far)
[121/148] PBSLO_2024_Q3.pdf... direct (0.4s)
[122/148] PBSLO_2024_Q4.pdf... direct (0.8s)
[123/148] PBSLO_2025_Audited.pdf... direct (14.0s)
[124/148] PBSLO_2025_Q1.pdf... direct (1.6s)
[125/148] PBSLO_2025_Q2.pdf... direct (1.3s)
[126/148] PBSLO_2025_Q3.pdf... direct (1.5s)
[127/148] PBSLO_2025_Q4.pdf... direct (0.7s)
[128/148] PBSLO_2026_Q1.pdf... direct (0.6s)
[129/148] SFC_2022_Annual.pdf... direct (32.3s)
    ^ SLOW FILE -- SFC_2022_Annual.pdf took 32.3s
[130/148] SFC_2022_Q4.pdf... direct (21.2s)
  -- checkpoint saved (130 bse records so far)
[131/148] SFC_2023_Annual.pdf... direct (44.0s)
    ^ SLOW FILE -- SFC_2023_Annual.pdf took 44.0s
[132/148] SFC_2023_Q1.pdf... direct (9.9s)
[133/148] SFC_2023_Q2.pdf... direct (9.6s)
[134/148] SFC_2023_Q3.pdf... direct (10.0s)
[135/148] SFC_2023_Q4.pdf... direct (25.6s)
[136/148] SFC_2024_Q1.pdf... direct (6.7s)
[137/148] SFC_2024_Q2.pdf... direct (12.2s)
[138/148] SFC_2024_Q3.pdf... direct (11.0s)
[139/148] WIB_2024_Annual.pdf... direct (21.6s)
[140/148] WIB_2024_Q2.pdf... direct (0.3s)
  -- checkpoint saved (140 bse records so far)
[141/148] WIB_2024_Q3.pdf... direct (0.3s)
[142/148] WIB_2024_Q4.pdf... needs_ocr_elsewhere (6.5s)
[143/148] WIB_2025_Q1.pdf... direct (0.3s)
[144/148] WIB_2025_Q2.pdf... direct (9.2s)
[145/148] WIB_2025_Q3.pdf... direct (5.6s)
[146/148] WIB_2025_Q4.pdf... needs_ocr_elsewhere (19.5s)
[147/148] WIB_2026_Q1.pdf... direct (0.3s)
[148/148] WIB_2026_Q2.pdf... needs_ocr_elsewhere (11.2s)

=== Processing TTSE (1305 remaining of 1305 total) ===
[1/1305] A.S. Bryden & Sons Holdings Limited - Annual Report 2025.pdf... direct (267.2s)
    ^ SLOW FILE -- A.S. Bryden & Sons Holdings Limited - Annual Report 2025.pdf took 267.2s
[2/1305] AHL - Publication of appointment of EM-HR and EM-Local Sales dd 06.02.23.pdf... needs_ocr_elsewhere (0.0s)
[3/1305] AHL - Resignation of Executive Manager - Marketing (Cover letter) dd 29.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[4/1305] AHL - Resignation of Executive Manager - Marketing (Press release) dd 29.02.2024.pdf... direct (0.0s)
[5/1305] ANSA McAL Limited  - Shares purchased in ANSA McAL Employee Share Ownership Plan dd 11.07.2024.pdf... direct (0.1s)
[6/1305] ANSA McAL Limited  - Shares purchased in ANSA McAL Employee Share Ownership Plan dd 21.10.2024.pdf... direct (0.1s)
[7/1305] ANSA McAL Limited  - Shares purchased in ANSA McAL Employee Share Ownership Plan dd 29.05.2024.pdf... direct (0.1s)
[8/1305] ANSA McAL Limited  - Shares sold in ANSA McAL Employee Share Ownership Plan dd 09.07.2024.pdf... direct (0.1s)

[9/1305] ANSA McAL Limited  - Shares sold in ANSA McAL Employee Share Ownership Plan dd 28.11.2024.pdf... direct (0.1s)
[10/1305] ANSA McAL Limited  - Shares sold in ANSA McAL Employee Share Ownership Plan dd 29.11.2024.pdf... direct (0.1s)
  -- checkpoint saved (10 ttse records so far)
[11/1305] ANSA McAL Limited - Annual Report 2024.pdf... direct (1.5s)
[12/1305] ANSA McAL Limited - Annual Report 2025.pdf... direct (94.3s)
    ^ SLOW FILE -- ANSA McAL Limited - Annual Report 2025.pdf took 94.3s
[13/1305] ANSA McAL Limited - Audited  Statements for the year ended December 31st, 2024 (FULL) dd24.03.2025.pdf... direct (31.8s)
    ^ SLOW FILE -- ANSA McAL Limited - Audited  Statements for the year ended December 31st, 2024 (FULL) dd24.03.2025.pdf took 31.8s
[14/1305] ANSA McAL Limited - ESOP shares purchased dd 28.11.2025.pdf... direct (0.1s)
[15/1305] ANSA McAL Limited - Execution of Loan Agreement (cover letter) dd 11.09.2024.pdf... direct (0.1s)
[16/1305] ANSA McAL Limited - Execution of Loan Agreement (press release) dd 13.09.2024.pdf... direct (0.0s)
[17/1305] ANSA McAL Limited - Final Dividend Payment Schedule dd 26.03.2024.pdf... direct (0.0s)
[18/1305] ANSA McAL Limited - Interim Dividend Schedule dd 13.08.2024.pdf... direct (0.0s)
[19/1305] ANSA McAL Limited - Notice of Annual General Meeting (Cover Letter) dd 17.04.2026.pdf... direct (0.1s)
[20/1305] ANSA McAL Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026.pdf... direct (0.1s)
  -- checkpoint saved (20 ttse records so far)
[21/1305] ANSA McAL Limited - Notice of Annual Meeting (Cover Letter) dd 24.04.2025.pdf... direct (0.1s)
[22/1305] ANSA McAL Limited - Notice of Annual Meeting (Cover Letter) dd 26.04.2024.pdf... direct (0.1s)
[23/1305] ANSA McAL Limited - Notice of Annual Meeting (Press Release) dd 24.04.2025.pdf... direct (0.1s)
[24/1305] ANSA McAL Limited - Notice of Annual Meeting (Press Release) dd 26.04.2024.pdf... direct (0.1s)
[25/1305] ANSA McAL Limited - Notice of Appointment of Chief Operating Officer (Cover Letter) dd 17.06.2025.pdf... direct (0.1s)
[26/1305] ANSA McAL Limited - Notice of Appointment of Chief Operating Officer (Press Release) dd 17.06.2025.pdf... direct (0.0s)
[27/1305] ANSA McAL Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 04.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[28/1305] ANSA McAL Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[29/1305] ANSA McAL Limited - Notice of Appointment of Senior Officer Newspaper Clippings dd 07.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[30/1305] ANSA McAL Limited - Notice of Availability of 2023 Annual Report (Cover letter) dd 29.04.2024.pdf... direct (0.1s)
  -- checkpoint saved (30 ttse records so far)
[31/1305] ANSA McAL Limited - Notice of Availability of 2023 Annual Report (Press Release) dd 29.04.2024.pdf... direct (0.1s)
[32/1305] ANSA McAL Limited - Notice of Availability of Annual Report 2024 (Cover Letter) dd 01.05.2025.pdf... direct (0.1s)
[33/1305] ANSA McAL Limited - Notice of Availability of Annual Report 2024 (Cover Letter) dd 30.04.2025.pdf... direct (0.1s)
[34/1305] ANSA McAL Limited - Notice of Availability of Annual Report 2024 (Press Release) dd 01.05.2025.pdf... direct (0.1s)
[35/1305] ANSA McAL Limited - Notice of Availability of Annual Report 2024 (Press Release) dd 30.04.2025.pdf... direct (0.1s)
[36/1305] ANSA McAL Limited - Notice of Availbility of Annual Report 2025 (CL) dd 30.04.2026.pdf... direct (0.1s)
[37/1305] ANSA McAL Limited - Notice of Availbility of Annual Report 2025 (PR) dd 30.04.2026.pdf... direct (0.1s)
[38/1305] ANSA McAL Limited - Notice of Change in Directors (Cover Letter) dd 21.10.2025.pdf... needs_ocr_elsewhere (0.0s)
[39/1305] ANSA McAL Limited - Notice of Change in Directors (Press Release) dd 22.10.2025.pdf... direct (0.0s)
[40/1305] ANSA McAL Limited - Notice of Change in Directors Newspaper Clippings (Cover Letter) dd 22.10.2025.pdf... direct (0.1s)
  -- checkpoint saved (40 ttse records so far)
[41/1305] ANSA McAL Limited - Notice of Change in Senior Officer (Cover Letter) dd 03.10.2024.pdf... needs_ocr_elsewhere (0.0s)
[42/1305] ANSA McAL Limited - Notice of Change in Senior Officer (Press Release) dd 03.10.2024.pdf... direct (1.1s)
[43/1305] ANSA McAL Limited - Notice of Change in Senior Officers (Cover Letter) dd 08.08.2025.pdf... direct (0.1s)
[44/1305] ANSA McAL Limited - Notice of Change in Senior Officers (Cover Letter) dd 30.12.2025.pdf... direct (0.1s)
[45/1305] ANSA McAL Limited - Notice of Change in Senior Officers (Press Release) dd 08.08.2025.pdf... direct (0.1s)
[46/1305] ANSA McAL Limited - Notice of Change in Senior Officers (Press Release) dd 30.12.2025.pdf... direct (0.0s)
[47/1305] ANSA McAL Limited - Notice of Change in Senior Officers Newspaper Clippings dd 08.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[48/1305] ANSA McAL Limited - Notice of Change of Senior Officers (Cover Letter) dd 01.07.2025.pdf... direct (0.1s)
[49/1305] ANSA McAL Limited - Notice of Change of Senior Officers (Press Release) dd 02.07.2025.pdf... direct (0.0s)
[50/1305] ANSA McAL Limited - Notice of Change of Senior Officers Newspaper Clippings dd 02.07.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (50 ttse records so far)
[51/1305] ANSA McAL Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2024.pdf... direct (0.1s)
[52/1305] ANSA McAL Limited - Notice of Final Dividend Payment (Press Release) dd 02.04.2024.pdf... direct (0.1s)
[53/1305] ANSA McAL Limited - Notice of Interim Dividend Payment dd 20.08.2024.pdf... direct (0.1s)
[54/1305] ANSA McAL Limited - Notice of Resignation of Director (Cover Letter) dd 08.08.2025.pdf... direct (0.1s)
[55/1305] ANSA McAL Limited - Notice of Resignation of Director (Cover Letter) dd 13.08.2025.pdf... direct (0.1s)
[56/1305] ANSA McAL Limited - Notice of Resignation of Director (Cover Letter) dd 26.05.2025.pdf... direct (0.1s)
[57/1305] ANSA McAL Limited - Notice of Resignation of Director (Press Release) dd 13.08.2025.pdf... direct (0.1s)
[58/1305] ANSA McAL Limited - Notice of Resignation of Director (Press Release) dd 27.05.2025.pdf... direct (0.0s)
[59/1305] ANSA McAL Limited - Notice of Resignation of Director Newspaper Clippings dd 14.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[60/1305] ANSA McAL Limited - Notice of Resignation of Director Newspaper Clippings.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (60 ttse records so far)
[61/1305] ANSA McAL Limited - Notice of Suspension of Dividend Payments (Amended Cover Letter) dd 11.04.2025.pdf... direct (0.1s)
[62/1305] ANSA McAL Limited - Notice of Suspension of Dividend Payments (Cover Letter) dd 10.04.2025.pdf... direct (0.3s)
[63/1305] ANSA McAL Limited - Notice of Suspension of Dividend Payments - Amended dd 10.04.2025.pdf... direct (0.1s)
[64/1305] ANSA McAL Limited - Notice of Suspension of Dividend Payments - Subsequent Amendment dd 14.04.2025.pdf... direct (0.1s)
[65/1305] ANSA McAL Limited - Notice of Suspension of Dividend Payments dd 10.04.2025.pdf... direct (0.1s)
[66/1305] ANSA McAL Limited - Notice of Trading in Shares (Cover Letter) dd 26.06.2025.pdf... direct (0.1s)
[67/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 02.04.2025.pdf... direct (0.1s)
[68/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 03.07.2025.pdf... direct (0.1s)
[69/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 04.04.2025.pdf... direct (0.1s)
[70/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 08.04.2025.pdf... direct (0.1s)
  -- checkpoint saved (70 ttse records so far)
[71/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 09.06.2025.pdf... direct (0.1s)
[72/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 10.04.2025.pdf... direct (0.3s)
[73/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 10.06.2025.pdf... direct (0.1s)
[74/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 11.04.2025.pdf... direct (0.1s)
[75/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 14.04.2025 (Director).pdf... direct (0.1s)
[76/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 14.04.2025.pdf... direct (0.1s)
[77/1305] ANSA McAL Limited - Notice of Trading in shares (Cover Letter) dd 28.03.2025.pdf... direct (0.1s)
[78/1305] ANSA McAL Limited - Trading in Shares (Cover Letter) dd 02.04.2026.pdf... direct (0.1s)
[79/1305] ANSA McAL Limited - Trading in Shares (Cover Letter) dd 10.04.2026.pdf... direct (0.1s)
[80/1305] ANSA McAL Limited - Trading in Shares (Cover Letter) dd 23.06.2026.pdf... direct (0.1s)
  -- checkpoint saved (80 ttse records so far)
[81/1305] ANSA McAL Limited - Trading in Shares (Cover Letter) dd 25.06.2026.pdf... direct (0.1s)
[82/1305] ANSA McAL Limited- Notice of Trading in shares (Cover Letter) dd 27.06.2025.pdf... direct (0.1s)
[83/1305] ANSA Merchant Bank Limited - Annual Report 2024.pdf... direct (23.8s)
[84/1305] ANSA Merchant Bank Limited - Annual Report 2025.pdf... direct (32.6s)
    ^ SLOW FILE -- ANSA Merchant Bank Limited - Annual Report 2025.pdf took 32.6s
[85/1305] ANSA Merchant Bank Limited - Notice of 2023 final dividend payment  (Cover letter) dd 22.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[86/1305] ANSA Merchant Bank Limited - Notice of 2023 final dividend payment  (Press Release) dd 22.03.2024.pdf... direct (0.1s)
[87/1305] ANSA Merchant Bank Limited - Notice of 2024 Interim dividend payment  (Cover letter) dd 09.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[88/1305] ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026.pdf... needs_ocr_elsewhere (1.0s)
[89/1305] ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 22.04.2024.pdf... direct (0.2s)
[90/1305] ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 25.04.2025.pdf... needs_ocr_elsewhere (2.2s)
  -- checkpoint saved (90 ttse records so far)
[91/1305] ANSA Merchant Bank Limited - Notice of Appointment of Managing Director (Cover) dd 08.01.2024.pdf... direct (0.1s)
[92/1305] ANSA Merchant Bank Limited - Notice of Appointment of Managing Director (Press Release) dd 08.01.2024.pdf... direct (0.0s)
[93/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter)  dd 04.10.2024.pdf... direct (0.1s)
[94/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 08.09.2025.pdf... direct (0.1s)
[95/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[96/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover letter) dd 04.03.2024.pdf... direct (0.1s)
[97/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover letter) dd 07.02.2024.pdf... direct (0.1s)
[98/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[99/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.10.2024.pdf... needs_ocr_elsewhere (0.0s)
[100/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 07.02.2024.pdf... direct (0.0s)
  -- checkpoint saved (100 ttse records so far)
[101/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 08.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[102/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.09.2025.pdf... needs_ocr_elsewhere (0.4s)
[103/1305] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer dd 07.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[104/1305] ANSA Merchant Bank Limited - Notice of Change of Managing Director (Cover Letter) dd 30.06.2025.pdf... direct (0.1s)
[105/1305] ANSA Merchant Bank Limited - Notice of Change of Managing Director (Press Release) dd 02.07.2025.pdf... needs_ocr_elsewhere (0.8s)
[106/1305] ANSA Merchant Bank Limited - Notice of Changes in Senior Officer  (Press Release) dd 08.06.2026.pdf... needs_ocr_elsewhere (0.5s)
[107/1305] ANSA Merchant Bank Limited - Notice of Changes in Senior Officer (Cover Letter) dd 02.06.2026.pdf... direct (0.1s)
[108/1305] ANSA Merchant Bank Limited - Notice of Changes to the Baord of Directors dd 07.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[109/1305] ANSA Merchant Bank Limited - Notice of Final Dividend Payment (Cover Letter) dd 18.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[110/1305] ANSA Merchant Bank Limited - Notice of Final Dividend Payment (Press Release) dd 19.03.2026.pdf... needs_ocr_elsewhere (0.6s)
  -- checkpoint saved (110 ttse records so far)
[111/1305] ANSA Merchant Bank Limited - Notice of Final Dividend Payment 2024 (Cover Letter) dd 20.03.2025.pdf... needs_ocr_elsewhere (0.0s)
[112/1305] ANSA Merchant Bank Limited - Notice of Final Dividend Payment 2024 (Press Release) dd 20.03.2025.pdf... needs_ocr_elsewhere (0.6s)
[113/1305] ANSA Merchant Bank Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 06.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[114/1305] ANSA Merchant Bank Limited - Notice of Interim Dividend Payment 2025 (Press Release) dd 07.08.2025.pdf... needs_ocr_elsewhere (0.6s)
[115/1305] ANSA Merchant Bank Limited - Notice of Interim dividend payment  (Press release) dd 13.08.2024.pdf... needs_ocr_elsewhere (0.5s)
[116/1305] ANSA Merchant Bank Limited - Notice of Publication of 2024 Annual Report (Cover letter) dd 29.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[117/1305] ANSA Merchant Bank Limited - Notice of Publication of Annual Report (Cover Letter) dd 30.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[118/1305] ANSA Merchant Bank Limited - Notice of Publication of Annual Report 2023 dd 30.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[119/1305] ANSA Merchant Bank Limited - Notice of Resignation of Director (Cover Letter) dd 26.06.2025.pdf... direct (0.1s)
[120/1305] ANSA Merchant Bank Limited - Notice of Resignation of Director (Press Release) dd 30.06.2025.pdf... needs_ocr_elsewhere (0.4s)
  -- checkpoint saved (120 ttse records so far)
[121/1305] ANSA Merchant Bank Limited - Notice of Resignation of Senior Officer (Press Release) dd 08.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[122/1305] ANSA Merchant Bank Limited - Notice to Shareholders dd 02.04.2024.pdf... needs_ocr_elsewhere (0.8s)
[123/1305] ANSA Merchant Bank Limited - Trading in shares by a Connected Party dd 25.08.2025.pdf... direct (0.1s)
[124/1305] ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Cover letter) dd30.09.2024.pdf... direct (0.1s)
[125/1305] ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Press Release) dd30.09.2024.pdf... needs_ocr_elsewhere (0.0s)
[126/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at April 30, 2025 dd 01.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[127/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at August 31, 2025 dd 10.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[128/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at July 31, 2025 dd 04.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[129/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at June 30, 2025 dd 01.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[130/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at March 31, 2025 dd 07.04.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (130 ttse records so far)
[131/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at May 31, 2025 dd 02.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[132/1305] Agostini Limited -  Shares held by Directors and Senior Officers as at October 31 2025 dd 04.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[133/1305] Agostini Limited - Amended Notice of Availability of 2025 Annual Report (Press Release) dd 16.01.2026.pdf... direct (0.1s)
[134/1305] Agostini Limited - Annual Report 2025 (Cover Letter) dd 12.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[135/1305] Agostini Limited - Errata Sheet of Offer and Take Over Bid Circular (Cover Letter) dd 04.07.2025.pdf... needs_ocr_elsewhere (0.0s)

[136/1305] Agostini Limited - Errata Sheet of Offer and Take Over Bid Circular dd 10.07.2025.pdf... direct (1.5s)
[137/1305] Agostini Limited - Notice of Acquisition by Subsidiary (Cover Letter) dd 03.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[138/1305] Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026 (1).pdf... needs_ocr_elsewhere (0.8s)
[139/1305] Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026.pdf... needs_ocr_elsewhere (0.8s)
[140/1305] Agostini Limited - Notice of Annual General Meeting (Press Release) dd 03.02.2026.pdf... needs_ocr_elsewhere (0.4s)
  -- checkpoint saved (140 ttse records so far)
[141/1305] Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 22.05.2026 (1).pdf... direct (0.1s)
[142/1305] Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 22.05.2026.pdf... direct (0.2s)
[143/1305] Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 30.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[144/1305] Agostini Limited - Notice of Appointment of Director (Press Release) dd 01.10.2025.pdf... direct (0.1s)
[145/1305] Agostini Limited - Notice of Appointment of Director (Press Release) dd 22.05.2026.pdf... needs_ocr_elsewhere (1.8s)
[146/1305] Agostini Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[147/1305] Agostini Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 30.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[148/1305] Agostini Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.03.2026.pdf... needs_ocr_elsewhere (1.2s)
[149/1305] Agostini Limited - Notice of Appointment of Senior Officer (Press Release) dd 30.06.2025.pdf... direct (0.1s)
[150/1305] Agostini Limited - Notice of Availability of 2025 Annual Report (Press Release) dd 15.01.2026.pdf... direct (0.0s)
  -- checkpoint saved (150 ttse records so far)
[151/1305] Agostini Limited - Notice of Availability of Bid Circular (Press Release) dd 17.06.2025.pdf... direct (0.2s)
[152/1305] Agostini Limited - Notice of Change in Director (Cover Letter) dd 22.05.2026.pdf... direct (0.1s)
[153/1305] Agostini Limited - Notice of Change in Director (Press Release) dd 22.05.2026 (1).pdf... needs_ocr_elsewhere (0.7s)
[154/1305] Agostini Limited - Notice of Change in Director (Press Release) dd 22.05.2026.pdf... needs_ocr_elsewhere (0.7s)
[155/1305] Agostini Limited - Notice of Issuance of New AGL Shares (Cover Letter) dd 10.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[156/1305] Agostini Limited - Notice of Issuance of New AGL Shares (Press Release) dd 10.07.2025.pdf... direct (0.0s)
[157/1305] Agostini Limited - Notice of Offer and Take Over Bid (Press Release) dd 17.06.2025.pdf... direct (0.1s)
[158/1305] Agostini Limited - Notice of Resignation of Senior Officer (CL) dd 24.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[159/1305] Agostini Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 05.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[160/1305] Agostini Limited - Notice of Resignation of Senior Officer (Cover letter) dd 16.04.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (160 ttse records so far)
[161/1305] Agostini Limited - Notice of Resignation of Senior Officer (PR) dd 24.11.2025.pdf... needs_ocr_elsewhere (0.6s)
[162/1305] Agostini Limited - Notice of Resignation of Senior Officer (Press Release) dd 16.04.2026.pdf... needs_ocr_elsewhere (0.9s)
[163/1305] Agostini Limited - Notice of Resignation of Senior Officer (Press Release) dd 29.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[164/1305] Agostini Limited - Notice of Retirement of Director (Cover Letter) dd 06.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[165/1305] Agostini Limited - Notice of Retirement of Director (Press Release) dd 06.02.2026.pdf... needs_ocr_elsewhere (1.8s)
[166/1305] Agostini Limited - Notice of Special Meeting (Press Release) dd 17.06.2025.pdf... direct (0.1s)
[167/1305] Agostini Limited - Notice of Trading in Shares (CL) dd 01.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[168/1305] Agostini Limited - Notice of Trading in Shares (Cover Letter) dd 24.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[169/1305] Agostini Limited - Offer and Take Over Bid dd 17.06.2025.pdf... direct (25.7s)
[170/1305] Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (170 ttse records so far)
[171/1305] Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[172/1305] Agostini Limited - Shares held by Directors and Senior Officers as at February 28, 2026 dd 02.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[173/1305] Agostini Limited - Shares held by Directors and Senior Officers as at January 31, 2026 dd 02.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[174/1305] Agostini Limited - Shares held by Directors and Senior Officers as at June 30th, 2026  dd 02.07.2026.pdf... needs_ocr_elsewhere (0.0s)
[175/1305] Agostini Limited - Shares held by Directors and Senior Officers as at March 31, 2026 dd 01.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[176/1305] Agostini Limited - Shares held by Directors and Senior Officers as at May 31, 2026 dd 01.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[177/1305] Agostini Limited - Submission of 2025 Annual Report (Cover Letter) dd 23.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[178/1305] Agostini Limited Annual Report 2025.pdf... direct (24.4s)
[179/1305] Agostini's Limited -  Shares held by Directors anf Senior Officers as at April 2024 dd 03-05-2024.pdf... needs_ocr_elsewhere (0.0s)
[180/1305] Agostini's Limited -  Shares held by Directors anf Senior Officers as at June 2024 dd 02.07.2024.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (180 ttse records so far)
[181/1305] Agostini's Limited -  Shares held by Directors anf Senior Officers as at May 2024 dd 03.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[182/1305] Agostini's Limited - Documents requested for Name Change dd 18.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[183/1305] Agostini's Limited - Notice of Acquisition of  a Company (Cover Letter) dd 04.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[184/1305] Agostini's Limited - Notice of Acquisition of  a Company (Press Release) dd 04.02.2025.pdf... needs_ocr_elsewhere (0.7s)
[185/1305] Agostini's Limited - Notice of Annual General Meeting (Cover Letter) dd 05.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[186/1305] Agostini's Limited - Notice of Annual General Meeting dd 05.02.2025.pdf... needs_ocr_elsewhere (0.3s)
[187/1305] Agostini's Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[188/1305] Agostini's Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.03.2024.pdf... direct (0.1s)
[189/1305] Agostini's Limited - Notice of Appointment of a Director (Cover Letter) dd 06.01.2025.pdf... needs_ocr_elsewhere (0.0s)
[190/1305] Agostini's Limited - Notice of Appointment of a Director (Press Release) dd 06.01.2025.pdf... needs_ocr_elsewhere (0.9s)
  -- checkpoint saved (190 ttse records so far)
[191/1305] Agostini's Limited - Notice of Availability of 2024 Annual Report (Press Release) dd 21.01.2025.pdf... needs_ocr_elsewhere (0.0s)
[192/1305] Agostini's Limited - Notice of Change in Company's Name (Cover Letter) dd 17.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[193/1305] Agostini's Limited - Notice of Change in Company's Name dd 17.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[194/1305] Agostini's Limited - Notice of Dividend payment (Cover Letter) dd 09.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[195/1305] Agostini's Limited - Unaudited Financials for the period ended December 31st, 2024 dd 14.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[196/1305] Agostini's Limited Annual Report 2024.pdf... direct (45.9s)
    ^ SLOW FILE -- Agostini's Limited Annual Report 2024.pdf took 45.9s
[197/1305] Angostura Holding Limited - Notcie of Appointment of a Director (Cover Letter) dd 25.09.2024.pdf... needs_ocr_elsewhere (0.0s)
[198/1305] Angostura Holding Limited - Notcie of Appointment of a Director (Press Release) dd 25.09.2024.pdf... direct (0.0s)
[199/1305] Angostura Holding Limited - Notice of Availability of 2024 Annual report (Cover letter) dd 28.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[200/1305] Angostura Holding Limited - Notice of Availability of 2025 Annual Report (Cover Letter) dd 31.03.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (200 ttse records so far)
[201/1305] Angostura Holding Limited - Notice of Final Dividend Payment (Cover Letter) dd 13.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[202/1305] Angostura Holding Limited - Notice of Final Dividend Payment (Cover Letter) dd 27.03.2025.pdf... needs_ocr_elsewhere (0.0s)

[203/1305] Angostura Holding Limited - Notice of Final Dividend Payment dd 13.03.2026.pdf... needs_ocr_elsewhere (0.7s)
[204/1305] Angostura Holding Limited - Notice of Final Dividend Payment dd 27.03.2025.pdf... direct (0.0s)
[205/1305] Angostura Holding Limited - Noticeo of  Dividend Payment (Cover Letter) dd 28.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[206/1305] Angostura Holding Limited - Noticeo of  Dividend Payment dd 28.03.2024.pdf... direct (0.0s)
[207/1305] Angostura Holdings Limited -  Top 10 Shareholders as at  September 30, 2024 dd 30.10.2024.pdf... direct (0.1s)
[208/1305] Angostura Holdings Limited -  Top 10 Shareholders as at March 31st, 2024 dd 30.04.2024.pdf... direct (0.1s)
[209/1305] Angostura Holdings Limited -  Top 10 Shareholders as at March 31st, 2025 dd 11.04.2025.pdf... direct (0.1s)
[210/1305] Angostura Holdings Limited -  Top 10 Shareholders as at March 31st, 2026 dd 01.05.2026.pdf... direct (0.1s)
  -- checkpoint saved (210 ttse records so far)
[211/1305] Angostura Holdings Limited - 2024 Annual Report.pdf... direct (24.5s)
[212/1305] Angostura Holdings Limited - 2025 Annual Report.pdf... direct (19.0s)
[213/1305] Angostura Holdings Limited - Annual Report 2024 Newspaper Clippings (Cover Letter) dd 29.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[214/1305] Angostura Holdings Limited - Management Proxy Circular for Annual Meeting.pdf... direct (0.1s)
[215/1305] Angostura Holdings Limited - Management Proxy Circular for Special Meeting 2025.pdf... direct (0.8s)
[216/1305] Angostura Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd13.06.2024.pdf... needs_ocr_elsewhere (0.0s)
[217/1305] Angostura Holdings Limited - Notice of Annual General Meeting dd13.06.2024.pdf... direct (0.1s)
[218/1305] Angostura Holdings Limited - Notice of Annual Meeting (Press Release) dd 08.08.2025.pdf... direct (0.1s)
[219/1305] Angostura Holdings Limited - Notice of Appointment of Acting CEO (Cover Letter) dd 01.10.2025.pdf... needs_ocr_elsewhere (0.0s)
[220/1305] Angostura Holdings Limited - Notice of Appointment of Acting CEO (Press Release) dd 01.10.2025.pdf... direct (0.0s)
  -- checkpoint saved (220 ttse records so far)
[221/1305] Angostura Holdings Limited - Notice of Appointment of Director (Cover Letter) dd 21.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[222/1305] Angostura Holdings Limited - Notice of Appointment of Director dd 21.05.2024.pdf... direct (0.0s)
[223/1305] Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 07.08.2025.pdf... needs_ocr_elsewhere (0.1s)
[224/1305] Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 26.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[225/1305] Angostura Holdings Limited - Notice of Appointment of Directors (Press Release) dd 07.08.2025.pdf... direct (0.1s)
[226/1305] Angostura Holdings Limited - Notice of Appointment of Directors (Press Release) dd 26.06.2026.pdf... direct (0.0s)
[227/1305] Angostura Holdings Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 01.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[228/1305] Angostura Holdings Limited - Notice of Appointment of Senior Officer (Press Release) dd 01.04.2026.pdf... direct (0.0s)
[229/1305] Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 12.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[230/1305] Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Press Release) dd 12.08.2025.pdf... direct (0.0s)
  -- checkpoint saved (230 ttse records so far)
[231/1305] Angostura Holdings Limited - Notice of Material Change (Cover letter) dd 22.08.2024.pdf... direct (0.1s)
[232/1305] Angostura Holdings Limited - Notice of Material Change (Press release) dd 22.08.2024.pdf.pdf... direct (0.1s)
[233/1305] Angostura Holdings Limited - Notice of Posting of Nominees Biographies (Cover Letter) dd 29.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[234/1305] Angostura Holdings Limited - Notice of Resignation of Directors (Cover Letter) dd 04.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[235/1305] Angostura Holdings Limited - Notice of Resignation of Directors (Press Release) dd 04.06.2025.pdf... direct (0.1s)
[236/1305] Angostura Holdings Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 17.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[237/1305] Angostura Holdings Limited - Notice of Resignation of Senior Officer (Press Release) dd 18.03.2026.pdf... direct (0.0s)
[238/1305] Angostura Holdings Limited - Notice of Resignation of a Senior Officer (Cover Letter) dd 26.06.2024.pdf... needs_ocr_elsewhere (0.0s)
[239/1305] Angostura Holdings Limited - Notice of Resignation of a Senior Officer (Press release) dd 26.06.2024.pdf... direct (0.2s)
[240/1305] Angostura Holdings Limited - Notice of Special Meeting (Cover Letter) dd 24.07.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (240 ttse records so far)
[241/1305] Angostura Holdings Limited - Notice of Special Meeting (Press Release) dd 24.07.2025.pdf... direct (0.1s)
[242/1305] Angostura Holdings Limited - Notice of interim dividend payment (Cover letter) dd 12.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[243/1305] Angostura Holdings Limited - Notice of interim dividend payment (Press release) dd 12.08.2024.pdf... direct (0.0s)
[244/1305] Angostura Holdings Limited - Ntice of Posting of Annual Meeting Douments (Cover Letter) dd 07.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[245/1305] Angostura Holdings Limited - Proxy Form for Annual Meeting.pdf... direct (0.2s)
[246/1305] Angostura Holdings Limited - Proxy Form for Special Meeting 2025.pdf... direct (0.3s)
[247/1305] Angostura Holdings Limited - Shareholdings of Directors and Executive Officers 31-12-2024 dd 27.03.25.pdf... direct (0.1s)
[248/1305] Angostura Holdings Limited - Shareholdings of Directors and Executive Officers 31-12-2025 dd 13.03.26.pdf... direct (0.1s)
[249/1305] Angostura Holdings Limited - Top 10 Shareholders as at December 31, 2024.pdf... direct (0.2s)
[250/1305] Anogstura Holdings Limited - Biographies of Nominated Directors 2025.pdf... direct (0.6s)
  -- checkpoint saved (250 ttse records so far)
[251/1305] Ansa McAL Limited - Notice of Change in Director (Cover Letter) dd 02.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[252/1305] Ansa McAL Limited - Notice of Change in Director (Press Release) dd 02.06.2025.pdf... direct (0.0s)
[253/1305] Ansa McAL Limited - Notice of Change in Director Newspaper Clippings (Cover Letter) dd 04.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[254/1305] CIBC Caribbean Bank Limited - Directors' Report for 2025 Annual Meeting.pdf... direct (0.4s)
[255/1305] CIBC Caribbean Bank Limited - Management Proxy Circular for 2025 Annual Meeting.pdf... direct (0.2s)
[256/1305] CIBC Caribbean Bank Limited - Notice of Annual Meeting (Cover Letter) dd 27.01.2024.pdf... direct (0.1s)
[257/1305] CIBC Caribbean Bank Limited - Notice of Annual Meeting (Press Release) dd 26.01.2026.pdf... direct (0.2s)
[258/1305] CIBC Caribbean Bank Limited - Notice of Annual Meeting (Press Release) dd 27.01.2024.pdf... direct (0.2s)
[259/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Director (Cover Letter) dd 03.06.2026.pdf... direct (0.1s)
[260/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Director (Cover Letter) dd 03.09.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (260 ttse records so far)
[261/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Director (Press Release) dd 03.06.2026.pdf... direct (0.2s)
[262/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Director (Press Release) dd 03.09.2025.pdf... direct (0.1s)
[263/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.02.2026.pdf... direct (0.1s)
[264/1305] CIBC Caribbean Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 23.02.2026.pdf... needs_ocr_elsewhere (0.8s)
[265/1305] CIBC Caribbean Bank Limited - Notice of Appointment of a Senior Officer (Cover Letter) dd 17.12.2024.pdf... needs_ocr_elsewhere (0.0s)
[266/1305] CIBC Caribbean Bank Limited - Notice of Appointment of a Senior Officer (Press Release) dd 18.12.2024.pdf... direct (0.1s)
[267/1305] CIBC Caribbean Bank Limited - Notice of Availiablity of 2025 Annual Report (CL) dd 16.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[268/1305] CIBC Caribbean Bank Limited - Notice of Changes in Senior Officers (Cover Letter) dd 28.01.2025.pdf... needs_ocr_elsewhere (0.0s)

[269/1305] CIBC Caribbean Bank Limited - Notice of Changes in Senior Officers dd 28.01.2025.pdf... direct (0.1s)
[270/1305] CIBC Caribbean Bank Limited - Notice of Changes in Senior Officers(Amended) dd 07.02.2025.pdf... needs_ocr_elsewhere (1.8s)
  -- checkpoint saved (270 ttse records so far)
[271/1305] CIBC Caribbean Bank Limited - Notice of Dividend Payemnt dd 16.12.2024.pdf... needs_ocr_elsewhere (0.0s)
[272/1305] CIBC Caribbean Bank Limited - Notice of Dividend Payment (Directors' Resolution) dd 13.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[273/1305] CIBC Caribbean Bank Limited - Notice of Dividend Payment dd 12.12.25.pdf... needs_ocr_elsewhere (0.0s)
[274/1305] CIBC Caribbean Bank Limited - Notice of Dividend dd 04.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[275/1305] CIBC Caribbean Bank Limited - Notice of Dividend dd 04.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[276/1305] CIBC Caribbean Bank Limited - Notice of Dividend dd 12.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[277/1305] CIBC Caribbean Bank Limited - Notice of Dividend dd 13.03.2025.pdf... needs_ocr_elsewhere (0.0s)
[278/1305] CIBC Caribbean Bank Limited - Notice of Record Date dd 18.12.20254.pdf... direct (0.1s)
[279/1305] CIBC Caribbean Bank Limited - Notice of Record Date for Annual Meeting (CL) dd 16.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[280/1305] CIBC Caribbean Bank Limited - Notice of Record Date for Annual Meeting (PR) dd 15.01.2026.pdf... needs_ocr_elsewhere (0.4s)
  -- checkpoint saved (280 ttse records so far)
[281/1305] CIBC Caribbean Bank Limited - Notice of Retirement of Director (Cover Letter) dd 26.01.2026.pdf... direct (0.2s)
[282/1305] CIBC Caribbean Bank Limited - Notice of Retirement of Director (Press Release) dd 26.01.2026.pdf... needs_ocr_elsewhere (0.8s)
[283/1305] CIBC Caribbean Bank Limited - Proxy Form for 2025 Annual Meeting.pdf... direct (0.3s)
[284/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at April 30, 2025 dd 12.06.2025.pdf... direct (0.2s)
[285/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at April 30, 2026 dd 04.06.2026.pdf... direct (0.2s)
[286/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at January 31, 2025 dd 13.03.2025.pdf... direct (0.2s)
[287/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at January 31, 2026 dd 13.03.2026.pdf... direct (0.2s)
[288/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at July 31, 2025 dd 05.09.2025.pdf... direct (0.3s)
[289/1305] CIBC Caribbean Bank Limited - Shareholdings Report as at Oct 31, 2025 dd 11.12.2025.pdf... direct (0.2s)
[290/1305] CIBC Caribbean Bank Limited - Submission of Annual Report 2025 (Cover Letter) dd 27.01.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (290 ttse records so far)
[291/1305] CIBC Caribbean Bank Limited Annual Report 2024.pdf... direct (21.9s)
[292/1305] CIBC Caribbean Bank Limited Annual Report 2025.pdf... direct (22.2s)
[293/1305] Calypso Macro Index Fund - Annual Report 2024 (Cover Letter) dd 30.04.2025.pdf... direct (0.1s)
[294/1305] Calypso Macro Index Fund - Annual Report 2024.pdf... direct (3.2s)
[295/1305] Calypso Macro Index Fund - Annual Report 2025.pdf... direct (0.9s)
[296/1305] Calypso Macro Index Fund - Notice of  Appointment of  Chief risk Officer (Cover Letter) dd 01.05.2024.pdf... direct (0.1s)
[297/1305] Calypso Macro Index Fund - Notice of Annual Meeting (Press Release) dd 24.04.2024.pdf... needs_ocr_elsewhere (0.6s)
[298/1305] Calypso Macro Index Fund - Notice of Appointment of Chairman of Board of Directors (PR) - 17.09.2025.pdf... direct (0.1s)
[299/1305] Calypso Macro Index Fund - Notice of Availability of 2025 Annual Report (Press Release) dd 24.04.2026.pdf... direct (0.1s)
[300/1305] Calypso Macro Index Fund - Notice of Availability of Annual Report 2024 dd 30.04.2025.pdf... direct (0.1s)
  -- checkpoint saved (300 ttse records so far)
[301/1305] Calypso Macro Index Fund - Notice of Changes of Directors (Cover Letter) dd 17.09.2025.pdf... direct (0.1s)
[302/1305] Calypso Macro Index Fund - Notice of Changes to the Board of Directors (Cover letter) dd 04.09.2024.pdf... direct (0.1s)
[303/1305] Calypso Macro Index Fund - Notice of Changes to the Board of Directors (Press release) dd 04.09.2024.pdf... direct (0.1s)
[304/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Amended Cover Letter) dd 07.06.2024.pdf... direct (0.1s)
[305/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Cover Letter) dd 03.06.2024.pdf... direct (0.1s)
[306/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Cover Letter) dd 22.08.2024.pdf... direct (0.1s)
[307/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Cover Letter) dd 27.02.2024.pdf... direct (0.1s)
[308/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Cover Letter) dd 27.02.2025.pdf... direct (0.1s)
[309/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Cover Letter) dd 28.11.2024.pdf... direct (0.1s)
[310/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Press Release) dd 27.02.2025.pdf... direct (0.1s)
  -- checkpoint saved (310 ttse records so far)
[311/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Press release) dd 03.06.2024.pdf... direct (0.1s)
[312/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Press release) dd 22.08.2024.pdf.pdf... needs_ocr_elsewhere (0.5s)
[313/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Press release) dd 27.02.2024.pdf... direct (0.1s)
[314/1305] Calypso Macro Index Fund - Notice of Dividend Payment (Press release) dd 28.11.2024.pdf... direct (0.1s)
[315/1305] Calypso Macro Index Fund - Notice of Publication of Annual Report (Cover letter) dd 29.04.2024.pdf... direct (0.1s)
[316/1305] Calypso Macro Index Fund - Notice of Publication of Annual Report (Press Release) dd 29.04.2024.pdf... direct (0.1s)
[317/1305] Calypso Macro Index Fund - Notice of Second Dividend Payment (Cover Letter) dd 28.05.2025.pdf... direct (0.1s)
[318/1305] Calypso Macro Index Fund - Notice of Second Dividend Payment (Press Release) dd 28.05.2025.pdf... needs_ocr_elsewhere (0.5s)
[319/1305] Calypso Macro Index Fund - Notice of Special Distribution Payment (Cover Letter) dd 08.05.2026.pdf... direct (0.1s)
[320/1305] Calypso Macro Index Fund - Notice of Special Distribution Payment (Press Release) dd 08.05.2026.pdf... direct (0.1s)
  -- checkpoint saved (320 ttse records so far)
[321/1305] Calypso Macro Index Fund - Notice of Third Dividend Payment (Cover Letter) dd 26.08.2025.pdf... direct (0.1s)
[322/1305] Calypso Macro Index Fund - Notice of Third Dividend Payment (Press Release) dd 26.08.2025.pdf... direct (0.1s)
[323/1305] Calypso Macro Index Fund - Report on Trading by a Director dd 30.08.2024.pdf... direct (0.1s)
[324/1305] Calypso Macro Index Fund - Shareholdings' Report as at June 30, 2024.pdf... direct (1.2s)
[325/1305] Calypso Macro Index Fund - Shareholdings' Report as at June 30th, 2025.pdf... direct (0.1s)
[326/1305] Calypso Macro Index Fund - Shareholdings' Report as at March 31st, 2024.pdf... direct (0.1s)
[327/1305] Calypso Macro Index Fund - Shareholdings' Report as at March 31st, 2025.pdf... direct (0.1s)
[328/1305] Calypso Macro Index Fund - Shareholdings' Report as at September 30, 2024.pdf... direct (0.1s)
[329/1305] Calypso Macro Index Fund - Shareholdings' Report as at September 30th, 2025.pdf... direct (0.1s)
[330/1305] Calypso Macro Index Fund - Submission of 2025 Annual Report (Cover Letter) dd 23.04.2026.pdf... direct (0.1s)
  -- checkpoint saved (330 ttse records so far)
[331/1305] Calypso Macro Index Fund - Trading in Shares (Cover Letter) dd26.05.2025.pdf... direct (0.1s)
[332/1305] CinemaOne Limited - Audited Financial Statements for the year ended September 30th, 2024 (Summary).pdf... direct (0.9s)
[333/1305] CinemaOne Limited - Audited Financial Statements for the year ended September 30th, 2025 (Summary).pdf... direct (0.8s)
[334/1305] CinemaOne Limited - Notice of Annual General Meeting dd 09.12.2025.pdf... direct (0.1s)
[335/1305] CinemaOne Limited - Notice of Shareholders  dd 04.07.2024.pdf... needs_ocr_elsewhere (0.0s)
[336/1305] CinemaOne Limited - Notice of Shareholders (Cover Letter)  dd 03.07.2024.pdf... direct (0.1s)
[337/1305] CinemaOne Limited - Notice of Trading in Shares (Cover Letter) dd 15.01-24.pdf... direct (0.1s)
[338/1305] CinemaOne Limited - Shareholders for the period ended December 31 2024 dd 14.02.2025.pdf... direct (0.2s)
[339/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended December 31st, 2023 dd 14.02.24.pdf... direct (0.3s)
[340/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended December 31st, 2025.pdf... direct (0.4s)
  -- checkpoint saved (340 ttse records so far)
[341/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended June 30, 2024 dd 14.08.2024.pdf... direct (0.2s)
[342/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended June 30, 2025 dd 14.08.2025.pdf... direct (0.3s)
[343/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended March 31st, 2024 dd 15.05.24.pdf... direct (0.2s)
[344/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended March 31st, 2025 dd 16.05.25.pdf... direct (0.3s)
[345/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended March 31st, 2026 dd 15.05.26.pdf... direct (0.4s)
[346/1305] CinemaOne Limited - Shareholdings' Report for the perioded ended September 30th, 2025.pdf... direct (0.2s)
[347/1305] CinemaOne Limited - Shareholdings' Report for the year ended September 30, 2024 dd 08.01.2025.pdf... direct (0.3s)
[348/1305] CinemaOne Limited - Submission of 2023 Annual Report (Cover Letter) dd 27.01.2024.pdf... direct (0.0s)
[349/1305] CinemaOne Limited - Submission of Annual Report (Cover Letter) dd 04.02.2026.pdf... direct (0.0s)
[350/1305] CinemaOne Limited - Submission of Annual Report (Cover Letter) dd 28.01.2025.pdf... direct (0.0s)
  -- checkpoint saved (350 ttse records so far)
[351/1305] CinemaOne Limited Annual Report 2024.pdf... direct (8.5s)
[352/1305] CinemaOne Limited Annual Report 2025.pdf... direct (9.3s)
[353/1305] CinemaOne_Audit_2024_Extension_Notification_Response.pdf... direct (0.1s)
[354/1305] Directors, Senior Officers & Connected Parties- December 31, 2023.pdf... direct (0.1s)
[355/1305] ECPF Top Ten Shareholdings & Connected Parties-Value & Development Fund (Dec-31-2023).pdf... needs_ocr_elsewhere (0.0s)
[356/1305] ECPF Top Ten Shareholdings & Connected Parties-Value & Development Funds (June-30-2024).pdf... direct (0.6s)
[357/1305] ECPF Top Ten Shareholdings & Connected Parties-Value & Development Funds (March-31-2024).pdf... direct (0.1s)
[358/1305] Endeavour Holdings Limited - Annual Report 2023 - 2024.pdf... direct (7.1s)
[359/1305] Endeavour Holdings Limited - Annual Report 2024-2025.pdf... direct (9.4s)
[360/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd 22.08.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (360 ttse records so far)
[361/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd 25.10.2023.pdf... needs_ocr_elsewhere (0.0s)
[362/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd28.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[363/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Press Release) dd 22.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[364/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Press Release) dd 25.10.2023.pdf... direct (0.2s)
[365/1305] Endeavour Holdings Limited - Notice of Annual General Meeting (Press Release) dd 28.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[366/1305] Endeavour Holdings Limited - Notice of Final Dividend Payment (Media Release) dd 24.06.2024.pdf... needs_ocr_elsewhere (0.0s)
[367/1305] Endeavour Holdings Limited - Notice of Interim Dividend Payment (Media Release) dd 28.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[368/1305] Endeavour Holdings Limited - Notice of Interim Dividned Payment (Media Release) dd 24.11.2023.pdf... direct (0.1s)
[369/1305] Endeavour Holdings Limited - Notice of Interim Dividned Payment (Press Release) dd 24.11.2023.pdf... needs_ocr_elsewhere (0.0s)
[370/1305] Endeavour Holdings Limited - Notice of Material Change (Press Release) dd 20.09.2023.pdf... direct (0.0s)
  -- checkpoint saved (370 ttse records so far)
[371/1305] Endeavour Holdings Limited - Shareholdings Report as October 31 2024 dd 28.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[372/1305] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2024  dd 22.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[373/1305] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[374/1305] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[375/1305] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2024  dd 06.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[376/1305] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2025 dd 18.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[377/1305] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2026 dd 24.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[378/1305] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2023  dd 05.09.2023.pdf... needs_ocr_elsewhere (0.0s)
[379/1305] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2024 dd 12.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[380/1305] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2025 dd 07.08.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (380 ttse records so far)
[381/1305] Endeavour Holdings Limited - Shareholdings Report as at October 30, 2023  dd 24.11.2023.pdf... needs_ocr_elsewhere (0.0s)
[382/1305] Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[383/1305] Eppley Caribbean Property Fund Limited - Notice of Dividend (email) dd 14.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[384/1305] Eppley Caribbean Property Fund Limited - Notice of Dividend Payment dd 19.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[385/1305] Eppley Caribbean Property Fund Limited - Top 10 Shareholders as at December 31, 2024 -Value Fund.pdf... direct (0.2s)
[386/1305] Eppley Caribbean Property Fund Limited - Transition to Annual Property Appraisals (Cover letter).pdf... needs_ocr_elsewhere (0.0s)
[387/1305] Eppley Caribbean Property Fund Limited SCC - Annual Report 2024.pdf... direct (18.5s)
[388/1305] Eppley Caribbean Property Fund Limited SCC - Annual Report 2025.pdf... direct (31.1s)
    ^ SLOW FILE -- Eppley Caribbean Property Fund Limited SCC - Annual Report 2025.pdf took 31.1s
[389/1305] Eppley Caribbean Property Fund Limited SCC - Annual Report for the year ended September 30, 2024.pdf... direct (19.0s)
[390/1305] Eppley Caribbean Property Fund Limited SCC - Val Fund - Notice of Dividend Payment dd 08.08.2024.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (390 ttse records so far)
[391/1305] Eppley Caribbean Property Fund Limited SCC - Val Fund - Notice of Dividend Payment dd 15.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[392/1305] Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024.pdf... needs_ocr_elsewhere (0.0s)
[393/1305] Eric Solis Marketing Limited - Notice of Acquisition (Cover Letter) dd 31.01.2025.pdf... needs_ocr_elsewhere (0.0s)
[394/1305] Eric Solis Marketing Limited - Notice of Acquisition dd 31.01.2025.pdf... direct (0.1s)
[395/1305] Eric Solis Marketing Limited - Notice of Change in By-Laws (Cover Letter) dd 14.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[396/1305] Eric Solis Marketing Limited - Notice of Dividend Payment (CL) dd 28.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[397/1305] Eric Solis Marketing Limited - Notice of Dividend Payment (Directors Resolution) dd 02.12.2025.pdf... direct (0.1s)
[398/1305] Eric Solis Marketing Limited - Notice of Dividend Payment (Directors Resolution) dd 05.03.2026.pdf... direct (0.1s)
[399/1305] Eric Solis Marketing Limited - Notice of Dividend Payment (Directors Resolution) dd 10.09.2025.pdf... direct (0.1s)
[400/1305] Eric Solis Marketing Limited - Notice of Material Change (Cover Letter) dd 26.06.2026.pdf... needs_ocr_elsewhere (0.0s)

  -- checkpoint saved (400 ttse records so far)
[401/1305] Eric Solis Marketing Limited - Notice of Material Change (Press Release) dd 24.06.2026.pdf... direct (0.0s)
[402/1305] Eric Solis Marketing Limited - Submission of Annual Report 2025 (Cover Letter) dd 15.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[403/1305] Eric Solis Marketing Limited - Top 10 Shareholders as at 31.01.2025.pdf... direct (0.0s)
[404/1305] Eric Solis Marketing Limited Annual Report 2024.pdf... direct (3.8s)
[405/1305] Eric Solis Marketing Limited Annual Report 2025.pdf... direct (11.8s)
[406/1305] Eris Solis Marketing Limited - Notice of Change of Auditor (Cover Letter) dd 21.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[407/1305] Eris Solis Marketing Limited - Notice of Change of Auditor dd 21.02.2025.pdf... direct (0.0s)
[408/1305] First Citizens Group Financial Holdings Limited - Annual Report 2024.pdf... direct (21.1s)
[409/1305] First Citizens Group Financial Holdings Limited - Annual Report 2025.pdf... direct (20.6s)
[410/1305] First Citizens Group Financial Holdings Limited - Notice of Availability of Annual Report 2024.pdf... needs_ocr_elsewhere (0.9s)
  -- checkpoint saved (410 ttse records so far)
[411/1305] First Citizens Group Financial Holdings Limited - Request for Exemption dd 27.03.2025.pdf... needs_ocr_elsewhere (0.0s)
[412/1305] First Citizens Group Financial Holdings Limited - Shareholding and Top 10 as at Dec 2023.pdf... direct (0.2s)
[413/1305] First Citizens Group Financial Holdings Limited - Shareholding and Top 10 as at June 2024.pdf... direct (0.2s)
[414/1305] First Citizens Group Financial Holdings Limited - Shareholding and Top 10 as at March 31 2026.pdf... direct (0.2s)
[415/1305] FirstCaribbean International Bank Limited - Copies of the 2023 Annual Report dd 24.01.24.pdf... needs_ocr_elsewhere (0.0s)
[416/1305] FirstCaribbean International Bank Limited - Notice of Material Change (Cover letter) dd 15.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[417/1305] FirstCaribbean International Bank Limited - Notice of Material Change (Press release) dd 15.02.2024.pdf... needs_ocr_elsewhere (0.9s)
[418/1305] FirstCaribbean International Bank Limited - Shareholdings report as at April 30, 2024  dd 13.06.2024.pdf... direct (0.2s)
[419/1305] FirstCaribbean International Bank Limited - Shareholdings report as at July 31, 2024  dd 12.09.2024.pdf... direct (0.2s)
[420/1305] GraceKennedy Limited -  Directors  Corporate Data - December 31, 2024 dd 28.02.2025.pdf... direct (0.1s)
  -- checkpoint saved (420 ttse records so far)
[421/1305] GraceKennedy Limited -  Directors  Corporate Data - December 31, 2025 dd 02.03.2026.pdf... direct (0.1s)
[422/1305] GraceKennedy Limited -  Directors  Corporate Data - June 30, 2024 dd 31.07.2024.pdf... direct (0.1s)
[423/1305] GraceKennedy Limited -  Directors  Corporate Data - March 31, 2024 dd 09.05.2024.pdf... direct (0.1s)
[424/1305] GraceKennedy Limited -  Directors  Corporate Data - September 30, 2024 dd 07.11.2024.pdf... direct (0.1s)
[425/1305] GraceKennedy Limited -  Directors  Officers Dealings -Stock Grants - Greg Lindo dd 31.05.24.pdf... direct (0.1s)
[426/1305] GraceKennedy Limited -  Directors  Officers Dealings -Stock Grants - Naomi Holness dd 31.05.2024.pdf... direct (0.1s)
[427/1305] GraceKennedy Limited - 2009 Stock Option Plan - Long Term Incentive (Cover letter) dd 27.03.26.pdf... direct (0.1s)
[428/1305] GraceKennedy Limited - 2009 Stock Option Plan - Long Term Incentive (Cover letter) dd 28.02.2025.pdf... direct (0.1s)
[429/1305] GraceKennedy Limited - 2009 Stock Option Plan - Long Term Incentive (Cover letter) dd 28.02.25.pdf... direct (0.1s)
[430/1305] GraceKennedy Limited - 2009 Stock Option Plan - Long Term Incentive (Cover letter) dd 29.02.2024.pdf... direct (0.1s)
  -- checkpoint saved (430 ttse records so far)
[431/1305] GraceKennedy Limited - 2009 Stock Option Plan - Long Term Incentive (Cover letter) dd 31.07.25.pdf... direct (0.1s)
[432/1305] GraceKennedy Limited - 2nd Quarter Performance (Press Release)  dd31.07.2024.pdf... direct (0.2s)
[433/1305] GraceKennedy Limited - 3rd Quarter Performance (Press Release)  dd 08.11.2024.pdf... direct (0.2s)
[434/1305] GraceKennedy Limited - Annual Report 2024.pdf... direct (34.2s)
    ^ SLOW FILE -- GraceKennedy Limited - Annual Report 2024.pdf took 34.2s
[435/1305] GraceKennedy Limited - Annual Report 2025.pdf... direct (39.4s)
    ^ SLOW FILE -- GraceKennedy Limited - Annual Report 2025.pdf took 39.4s
[436/1305] GraceKennedy Limited - Appointment of Head of Risk (Cover letter) dd 06.02.2024.pdf... direct (0.1s)
[437/1305] GraceKennedy Limited - Appointment of Head of Risk (press release) dd 06.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[438/1305] GraceKennedy Limited - Appointment of New Group Chief Human Resources Officer dd 02.01.23.pdf... direct (0.2s)
[439/1305] GraceKennedy Limited - Audited Financial Statements (Cover Letter) dd 02.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[440/1305] GraceKennedy Limited - Audited Financial Statements (Cover Letter) dd 28.02.2025.pdf... direct (0.0s)
  -- checkpoint saved (440 ttse records so far)
[441/1305] GraceKennedy Limited - Audited Financial Statements for the year 2024 dd 28.02.2025.pdf... direct (1047.5s)
    ^ SLOW FILE -- Guardian Holdings Limited Annual Report 2024.pdf took 1047.5s
[592/1305] Guardian Holdings Limited Annual Report 2025.pdf... direct (1094.4s)
    ^ SLOW FILE -- Guardian Holdings Limited Annual Report 2025.pdf took 1094.4s
[593/1305] Guardian Media Limited - Notice of Annual General Meeting (Cover Letter) dd 019.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[594/1305] Guardian Media Limited - Notice of Annual General Meeting (Press Release ) dd 19.04.2024.pdf... direct (0.1s)
[595/1305] Guardian Media Limited - Notice of Annual Meeting (Cover Letter ) dd 24.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[596/1305] Guardian Media Limited - Notice of Annual Meeting (Press Release ) dd 24.04.2025.pdf... direct (0.1s)
[597/1305] Guardian Media Limited - Notice of Annual Report (Cover Letter) dd 28.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[598/1305] Guardian Media Limited - Notice of Annual Report (Cover Letter) dd 29.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[599/1305] Guardian Media Limited - Notice of Annual Report (Press Release) dd 28.04.2025.pdf... direct (0.0s)
[600/1305] Guardian Media Limited - Notice of Annual Report (Press Release) dd 29.04.2024.pdf... direct (0.0s)
  -- checkpoint saved (600 ttse records so far)
[601/1305] Guardian Media Limited - Notice of Appointment of Managing Director (Cover Letter) dd 06.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[602/1305] Guardian Media Limited - Notice of Appointment of Managing Director (Press Release) dd 06.11.2024.pdf... direct (0.0s)
[603/1305] Guardian Media Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 02.01.2025.pdf... needs_ocr_elsewhere (0.0s)
[604/1305] Guardian Media Limited - Notice of Appointment of Senior Officer (Press Release) dd 02.01.2025.pdf... direct (0.0s)
[605/1305] Guardian Media Limited - Notice of Availability of Annual Report 2025 (CL) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[606/1305] Guardian Media Limited - Notice of Availability of Annual Report 2025 (PR) dd 30.04.2026.pdf... direct (0.0s)
[607/1305] Guardian Media Limited - Notice of Final Dividend Payment 2024 dd 20.03.2025.pdf... needs_ocr_elsewhere (0.0s)
[608/1305] Guardian Media Limited - Notice of Interim Dividend Payment 2025 dd 06.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[609/1305] Guardian Media Limited - Notice of Interim dividend (Cover letter) dd 07.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[610/1305] Guardian Media Limited - Notice of Rescheduled Annual General Meeting (Cover Letter) dd 28.04.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (610 ttse records so far)
[611/1305] Guardian Media Limited - Unaudited Financial Results for the quarter ended March 31st, 2026.pdf... direct (0.5s)
[612/1305] Guardian Media Limited Annual Report 2024.pdf... direct (41.1s)
    ^ SLOW FILE -- Guardian Media Limited Annual Report 2024.pdf took 41.1s
[613/1305] Guardian Media Limited Annual Report 2025.pdf... direct (11.2s)
[614/1305] Investor release Nov 23.pdf... needs_ocr_elsewhere (0.0s)
[615/1305] JMMB Group Limited  - Notice of  Appointment of Deputy Company Secretary (Cover Letter) dd 29.11.2024.pdf... direct (0.1s)
[616/1305] JMMB Group Limited -  Notice of Appointment of a Director (Cover letter) dd 06.03.2024.pdf... direct (0.1s)

[617/1305] JMMB Group Limited -  Notice of Appointment of a Director (Press Release) dd 31.03.2024.pdf... needs_ocr_elsewhere (0.8s)
[618/1305] JMMB Group Limited -  Notice of Interim Dividend Conseridation (Cover Letter) dd 04.06.2024.pdf... direct (0.1s)
[619/1305] JMMB Group Limited -  Notice of Interim Dividend Conseridation (Cover Letter) dd 05.09.2025.pdf... direct (0.1s)
[620/1305] JMMB Group Limited -  Notice of retirement of a Director (Cover letter) dd 20.02.2024.pdf... direct (0.1s)
  -- checkpoint saved (620 ttse records so far)
[621/1305] JMMB Group Limited -  Notice of retirement of a Director (Press Release) dd 31.03.2024.pdf... direct (0.1s)
[622/1305] JMMB Group Limited - Annual Report 2024 (Amended) .pdf... direct (78.3s)
    ^ SLOW FILE -- JMMB Group Limited - Annual Report 2024 (Amended) .pdf took 78.3s
[623/1305] JMMB Group Limited - Annual Report 2024.pdf... direct (79.2s)
    ^ SLOW FILE -- JMMB Group Limited - Annual Report 2024.pdf took 79.2s
[624/1305] JMMB Group Limited - Annual Report 2025.pdf... direct (74.4s)
    ^ SLOW FILE -- JMMB Group Limited - Annual Report 2025.pdf took 74.4s
[625/1305] JMMB Group Limited - Audited Financial Statements  for the year ended 31 March 2024 dd 19.06.2024.pdf... direct (14.7s)
[626/1305] JMMB Group Limited - Audited Financial Statements for the year ended March 31, 2025 dd 02.06.2025.pdf... direct (17.9s)
[627/1305] JMMB Group Limited - Audited Financial Statements for the year ended March 31, 2026 dd 01.06.2026 OLD.pdf... direct (18.5s)
[628/1305] JMMB Group Limited - Audited Financial Statements for the year ended March 31, 2026 dd 01.06.2026.pdf... direct (18.1s)
[629/1305] JMMB Group Limited - Notice of 2024 Annual General Meeting (Press release) dd 24.07.2024.pdf... direct (0.2s)
[630/1305] JMMB Group Limited - Notice of Annual General Meeting (Press Release) dd 15.09.2025.pdf... needs_ocr_elsewhere (6.6s)
  -- checkpoint saved (630 ttse records so far)
[631/1305] JMMB Group Limited - Notice of Appointment of Director (cover letter) dd 02.04.2025.pdf... direct (0.1s)
[632/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 07.01.2026.pdf... direct (0.1s)
[633/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.08.2025.pdf... direct (0.1s)
[634/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 25.11.2025.pdf... direct (0.1s)
[635/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 07.01.2026.pdf... direct (0.1s)
[636/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.08.2025.pdf... needs_ocr_elsewhere (1.6s)
[637/1305] JMMB Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 25.11.2025.pdf... needs_ocr_elsewhere (1.7s)
[638/1305] JMMB Group Limited - Notice of Availability of Annual Report dd 28.07.2025.pdf... direct (0.4s)
[639/1305] JMMB Group Limited - Notice of Consideration of Interim Dividend Payment (CL) dd 03.12.2025.pdf... direct (0.1s)
[640/1305] JMMB Group Limited - Notice of Delay in Publication of Annual Report (Cover Letter) dd 22.07.2024.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (640 ttse records so far)
[641/1305] JMMB Group Limited - Notice of Delay in Publication of Annual Report (Press release) dd 22.07.2024.pdf... direct (0.1s)
[642/1305] JMMB Group Limited - Notice of Dividend Payment (Cover Letter) dd 22.09.2025.pdf... direct (0.1s)
[643/1305] JMMB Group Limited - Notice of ESOP Trading dd 02.09.2025.pdf... direct (0.1s)
[644/1305] JMMB Group Limited - Notice of ESOP Trading dd 05.06.2026.pdf... direct (0.1s)
[645/1305] JMMB Group Limited - Notice of ESOP Trading dd 24.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[646/1305] JMMB Group Limited - Notice of ESOP Trading dd 25.02.2026.pdf... direct (0.1s)
[647/1305] JMMB Group Limited - Notice of ESOP Trading dd 30.09.2025.pdf... direct (0.1s)
[648/1305] JMMB Group Limited - Notice of Interim Dividend Payment (Amended Cover Letter) dd 10.12.2025.pdf... direct (0.1s)
[649/1305] JMMB Group Limited - Notice of Interim Dividend Payment (Cover Letter) dd 10.12.2025.pdf... direct (0.1s)
[650/1305] JMMB Group Limited - Notice of Interim Dividend Payment (Cover Letter) dd 19.06.2024.pdf... direct (0.1s)
  -- checkpoint saved (650 ttse records so far)
[651/1305] JMMB Group Limited - Notice of Interim Dividend Payment (Cover Letter) dd 20.06.2024 - Amended.pdf... needs_ocr_elsewhere (0.0s)
[652/1305] JMMB Group Limited - Notice of Leadership Change Advisory (Cover Letter) dd 31.07.2024.pdf... needs_ocr_elsewhere (0.0s)
[653/1305] JMMB Group Limited - Notice of Leadership Change Advisory (Press Release) dd 20.09.2024.pdf... needs_ocr_elsewhere (0.5s)
[654/1305] JMMB Group Limited - Notice of Reorganization of Board of Directors (Press Release) dd 02.01.2026.pdf... needs_ocr_elsewhere (1.8s)
[655/1305] JMMB Group Limited - Notice of Resignation of Director dd 11.03.2025.pdf... direct (0.1s)
[656/1305] JMMB Group Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 15.08.2025.pdf... direct (0.1s)
[657/1305] JMMB Group Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 27.06.2025.pdf... direct (0.1s)
[658/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 01.04.2025.pdf... direct (0.1s)
[659/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 06.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[660/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 09.06.2026.pdf... direct (0.1s)
  -- checkpoint saved (660 ttse records so far)
[661/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 11.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[662/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 11.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[663/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 17.06.2026.pdf... direct (0.1s)
[664/1305] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 23.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[665/1305] JMMB Group Limited - Notice of Trading in Shares 2 (Cover Letter) dd 01.04.2025.pdf... direct (0.1s)
[666/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter)  not distributed 29.06.2026.pdf... direct (1.0s)
[667/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter)  not distributed 30.06.2026.pdf... direct (0.1s)
[668/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) 2 not distributed 25.06.2026.pdf... direct (0.1s)
[669/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 12.06.2026.pdf... direct (0.1s)
[670/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 19.06.2026.pdf... direct (0.1s)
  -- checkpoint saved (670 ttse records so far)
[671/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 23.06.2026.pdf... direct (0.1s)
[672/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 24.06.2026.pdf... direct (0.1s)
[673/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 25.06.2026.pdf... direct (0.1s)
[674/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed 30.06.2026.pdf... direct (0.1s)
[675/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed dd 11.06.2026.pdf... direct (0.1s)
[676/1305] JMMB Group Limited - Notice of Trading in Shares ESOP (Cover Letter) not distributed dd 12.06.2026.pdf... direct (0.1s)
[677/1305] JMMB Group Limited - Notice of Trading in Shares ESOP 2 (Cover Letter) not distributed 24.06.2026.pdf... direct (0.1s)
[678/1305] JMMB Group Limited - Notice of Trading in Shares dd 26.06.2025.pdf... direct (0.1s)
[679/1305] JMMB Group Limited - Notice of availability of QFS for the period ended 31 December 2023.pdf... needs_ocr_elsewhere (0.0s)
[680/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 15,170 (Cover Letter) dd 12.12.2025.pdf... direct (0.1s)

  -- checkpoint saved (680 ttse records so far)
[681/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 25,000 (Cover Letter) dd 17.03.2026.pdf... direct (0.1s)
[682/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 3,143 (Cover Letter) dd 15.12.2025.pdf... direct (0.2s)
[683/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 32,147 (Cover Letter) dd 16.03.2026.pdf... direct (0.1s)
[684/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 60,346 (Cover Letter) dd 24.12.2025.pdf... direct (0.1s)
[685/1305] JMMB Group Limited - Puchases under Share Buyback Programme - 60,901  (Cover Letter) dd 02.06.2026.pdf... direct (0.1s)
[686/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 10,000 (Cover Letter) dd 02.04.2026.pdf... direct (0.1s)
[687/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 112,627 (Cover Letter) dd 25.11.2025.pdf... direct (0.1s)
[688/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 13,576 (Cover Letter) dd 04.03.2025.pdf... direct (0.1s)
[689/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 133,251 (Cover Letter) dd 10.03.2025.pdf... direct (0.1s)
[690/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 143,516 (Cover Letter) dd 27.02.2025.pdf... direct (0.1s)
  -- checkpoint saved (690 ttse records so far)
[691/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 156,615 (Cover Letter) dd 17.09.2025.pdf... direct (0.1s)
[692/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 16,692 (Cover Letter) dd 26.11.2025.pdf... direct (0.1s)
[693/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 18,636 (Cover Letter) dd 25.02.2025.pdf... direct (0.1s)
[694/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 20,866 (Cover Letter) dd 28.11.2025.pdf... direct (0.2s)
[695/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 21,588 (Cover Letter) dd 21.02.2025.pdf... direct (0.1s)
[696/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 24,424 (Cover Letter) dd 03.03.2025.pdf... direct (0.1s)
[697/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 25,000 (Cover Letter) dd 21.02.2024.pdf... direct (0.1s)
[698/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 28,629 (Cover Letter) dd 18.09.2025.pdf... direct (0.1s)
[699/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 292,768 (Cover Letter) dd 11.03.2025.pdf... direct (0.1s)
[700/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 3,000 (Cover Letter) dd 28.02.2025.pdf... direct (0.1s)
  -- checkpoint saved (700 ttse records so far)
[701/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 32,379 (Cover Letter) dd 06.03.2025.pdf... direct (0.1s)
[702/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 35,000  (Cover Letter) dd 25.02.2025.pdf... direct (0.1s)
[703/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 4,503 (Cover Letter) dd 02.12.2025.pdf... direct (0.1s)
[704/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 40,666 (Cover Letter) dd 04.09.2025.pdf... direct (0.1s)
[705/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 45,000 (Cover Letter) dd 24.02.2025.pdf... direct (0.1s)
[706/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 49,705 (Cover Letter) dd 23.03.2026.pdf... direct (0.1s)
[707/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 57,232 (Cover Letter) dd 26.03.2025.pdf... direct (0.2s)
[708/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 67,836 (Cover Letter) dd 01.12.2025.pdf... direct (0.1s)
[709/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 74,954 (Cover Letter) dd 27.11.2025.pdf... direct (0.1s)
[710/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 790 (Cover Letter) dd 09.12.2025.pdf... direct (0.1s)
  -- checkpoint saved (710 ttse records so far)
[711/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 9,417 (Cover Letter) dd 02.09.2025.pdf... direct (0.1s)
[712/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 92,527 (Cover Letter) dd 08.12.2025.pdf... direct (0.1s)
[713/1305] JMMB Group Limited - Purchases under Share Buyback Programme - 97,861 (Cover Letter) dd 11.12.2025.pdf... direct (0.1s)
[714/1305] JMMB Group Limited - Purchases under Share Buyback Programme -155,676 (Cover Letter) dd 25.08.2025.pdf... direct (0.1s)
[715/1305] JMMB Group Limited - Purchases under Share Buyback Programme -48,412 (Cover Letter) dd 21.02.2025.pdf... direct (0.1s)
[716/1305] JMMB Group Limited - Reorganisation Trinidad and Tobago Entities (Cover Letter) dd 20.02.2024.pdf... direct (0.1s)
[717/1305] JMMB Group Limited - Reorganisation Trinidad and Tobago Entities (Press Release) dd 22.02.2024.pdf... direct (0.1s)
[718/1305] JMMB Group Limited - Reorganizaion of JMMB Board (Cover Letter) dd 09.12.2025.pdf... direct (0.1s)
[719/1305] JMMB Group Limited - Shareholdings Report as at Decemebr 31, 2023 dd 14.02.2024.pdf... direct (0.2s)
[720/1305] JMMB Group Limited - Shareholdings Report as at March 31, 2024 dd 19.06.2024.pdf... direct (0.2s)
  -- checkpoint saved (720 ttse records so far)
[721/1305] JMMB Group Limited - Shareholdings Report for the year ended March 31 2026.pdf... direct (0.2s)
[722/1305] JMMB Group Limited - Top 10 Shareholders for the quarter ended December 31 2024 dd 14.02.2025.pdf... direct (0.0s)
[723/1305] JMMB Group Limited - Top 10 Shareholders for the year ended March 31 2025 dd 02.06.2025.pdf... direct (0.2s)
[724/1305] JMMB Group Limited - Trading in Shares (Cover Letter) dd 5.12.24.pdf... direct (0.1s)
[725/1305] JMMB Group Limited - Unaudited Financial Statements for the period ended 30 June 2024 dd 14.08.24.pdf... direct (1.6s)
[726/1305] JMMB Group Limited - Unaudited Financial Statements for the period ended 31 December 2023 dd 14.02.24.pdf... direct (1.9s)
[727/1305] JMMB Group Limited - Unaudited Financial Statements for the quarter ended June 30, 2025 dd 14.08.2025.pdf... direct (1.7s)
[728/1305] JMMB Group Limited -Top 10 Shareholders as at a March 31, 2024 dd 193.06.2024.pdf... direct (0.1s)
[729/1305] L.J. Williams Limited -  Notice of Appointment of Auditors (Cover Leter) dd 06.11.24.pdf... needs_ocr_elsewhere (0.0s)
[730/1305] L.J. Williams Limited -  Notice of Appointment of Auditors (Press Release) dd 06.11.2024.pdf... direct (0.1s)
  -- checkpoint saved (730 ttse records so far)
[731/1305] L.J. Williams Limited - Amended Shareholdings reports as at December 31, 2024 dd 14.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[732/1305] L.J. Williams Limited - Notice of Annual Meeting dd 03.10. 2024.pdf... direct (0.1s)
[733/1305] L.J. Williams Limited - Notice of Annual Meeting dd 03.10. 2025.pdf... direct (0.1s)
[734/1305] L.J. Williams Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 03.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[735/1305] L.J. Williams Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[736/1305] L.J. Williams Limited - Notice of Availability of Annual Report (Press Release) dd 28.07.2025.pdf... direct (0.0s)
[737/1305] L.J. Williams Limited - Notice of Availability of Annual Report (Press Release) dd 29.07.2024.pdf... direct (0.0s)
[738/1305] L.J. Williams Limited - Notice of Change of Senior Officer (Cover Letter) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[739/1305] L.J. Williams Limited - Notice of Change of Senior Officer (Press Release) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[740/1305] L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 06.03.2024.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (740 ttse records so far)
[741/1305] L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 28.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[742/1305] L.J. Williams Limited - Shareholdings reports as at 31 March, 2026 dd 03.07.2026.pdf... direct (0.3s)
[743/1305] L.J. Williams Limited - Shareholdings reports as at December 31, 2024 dd 11.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[744/1305] L.J. Williams Limited - Shareholdings reports as at December 31st, 2025 dd 13.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[745/1305] L.J. Williams Limited - Shareholdings reports as at June 30, 2024 dd 12.08.2024.pdf... needs_ocr_elsewhere (0.0s)
[746/1305] L.J. Williams Limited - Shareholdings reports as at June 30, 2025 dd 14.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[747/1305] L.J. Williams Limited - Shareholdings reports as at September 30, 2024 dd 12.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[748/1305] L.J. Williams Limited - Updated Shareholdings reports as at December 31st, 2025 dd 08.04.2026.pdf... needs_ocr_elsewhere (0.0s)

[749/1305] LJ Williams Limited Annual Report 2024.pdf... direct (9.2s)
[750/1305] LJ Williams Limited Annual Report 2025.pdf... direct (7.8s)
  -- checkpoint saved (750 ttse records so far)
[751/1305] Letter from MED - Reconstitution of Audit Risk Compiance and Compensation Committee dd 11.06.26.pdf... needs_ocr_elsewhere (0.0s)
[752/1305] Letter from NGL - Reason for Rescheduled Annual Meeting dd 06.02.2026.pdf... direct (0.1s)
[753/1305] Letters from AGL - Response to query on Top Ten Shareholders dd 18.02.2025.pdf... needs_ocr_elsewhere (0.0s)
[754/1305] MPC Caribbean Clean Energy Limited - Annual Report 2024 (Cover Letter) dd 29.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[755/1305] MPC Caribbean Clean Energy Limited - Notice of Annual General Meeting  dd 27.06.2025.pdf... direct (0.6s)
[756/1305] MPC Caribbean Clean Energy Limited - Notice of Annual General Meeting (Press Release) dd 27.06.2025.pdf... direct (0.6s)
[757/1305] MPC Caribbean Clean Energy Limited - Notice of Annual General Meeting dd 21.06.2024.pdf... direct (0.1s)
[758/1305] MPC Caribbean Clean Energy Limited - Notice of Annual General Meeting of Shareholders dd 21.06.2024.pdf... direct (0.6s)
[759/1305] MPC Caribbean Clean Energy Limited - TTSEC Material Change Report - Form 10A dd 13.02.2026.pdf... direct (0.5s)
[760/1305] MPC Caribbean Clean Energy Limited 2024 Annual Report.pdf... direct (83.4s)
    ^ SLOW FILE -- MPC Caribbean Clean Energy Limited 2024 Annual Report.pdf took 83.4s
  -- checkpoint saved (760 ttse records so far)
[761/1305] MPC Caribbean Clean Energy Limited 2025 Annual Report.pdf... direct (70.4s)
    ^ SLOW FILE -- MPC Caribbean Clean Energy Limited 2025 Annual Report.pdf took 70.4s
[762/1305] Massy Holdingd Ltd. - Shareholder Booklet 2024.pdf... direct (0.8s)
[763/1305] Massy Holdingd Ltd. - Shareholder Booklet 2025.pdf... direct (1.7s)
[764/1305] Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Cover Letter)  dd 04.06.2026.pdf... direct (0.1s)
[765/1305] Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Press Release)  dd 01.06.2026.pdf... needs_ocr_elsewhere (0.2s)
[766/1305] Massy Holdings Ltd. -  Notice of Change in Board Composition (Cover Letter) dd 25.11.2024.pdf... direct (1.6s)
[767/1305] Massy Holdings Ltd. -  Notice of Change in Directorship (Cover Letter) dd 20.01.2025.pdf... direct (0.1s)
[768/1305] Massy Holdings Ltd. -  Notice of Change in Directorship (Press Release) dd 20.01.2025.pdf... needs_ocr_elsewhere (0.0s)
[769/1305] Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Cover Letter) dd 21.01.2025.pdf... direct (0.1s)
[770/1305] Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Press Release) dd 21.01.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (770 ttse records so far)
[771/1305] Massy Holdings Ltd. -  Notice of Change in Senior Officer Roles & Titles (Cover Letter) dd 25.11.2024.pdf... direct (0.1s)
[772/1305] Massy Holdings Ltd. -  Submission of Annual Report dd 18.12.2024.pdf... direct (0.1s)
[773/1305] Massy Holdings Ltd. - Annual Report 2025 (Cover Letter)  dd 05.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[774/1305] Massy Holdings Ltd. - Annual Report 2025 - Electronic Submission (Cover Letter)  dd 07.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[775/1305] Massy Holdings Ltd. - Annual Report 2025.pdf... direct (39.9s)
    ^ SLOW FILE -- Massy Holdings Ltd. - Annual Report 2025.pdf took 39.9s
[776/1305] Massy Holdings Ltd. - Change in Registered Address (Cover Letter) dd 22.08.2024.pdf... direct (0.1s)
[777/1305] Massy Holdings Ltd. - Change in Senior Officer (Cover Letter) dd 02.01.24.pdf... direct (0.1s)
[778/1305] Massy Holdings Ltd. - Change in Senior Officer (Press Release) dd 02.01.24.pdf... direct (0.0s)
[779/1305] Massy Holdings Ltd. - Change in Senior Officer and Director (Cover Letter) dd 08.02.2024.pdf... direct (0.1s)
[780/1305] Massy Holdings Ltd. - Change in Senior Officer and Director (Press release) dd 08.02.2024.pdf... direct (0.0s)
  -- checkpoint saved (780 ttse records so far)
[781/1305] Massy Holdings Ltd. - Circular letter to shareholders re USD dividend payment dd 13.09.2024.pdf... direct (1.7s)
[782/1305] Massy Holdings Ltd. - Notice interim dividend payment (Press release) dd 09.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[783/1305] Massy Holdings Ltd. - Notice of 2024 Annual Report dd 26.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[784/1305] Massy Holdings Ltd. - Notice of 2025 Annual Report dd 18.12.2025.pdf... needs_ocr_elsewhere (0.4s)
[785/1305] Massy Holdings Ltd. - Notice of AGM & Availability of Annual Report (Cover letter) dd 18.12.2025.pdf... direct (0.1s)
[786/1305] Massy Holdings Ltd. - Notice of AGM & Submission of Annual Report (Cover letter) dd 26.11.2024.pdf... direct (0.1s)
[787/1305] Massy Holdings Ltd. - Notice of Annual General Meeting dd 18.12.2025.pdf... needs_ocr_elsewhere (0.7s)
[788/1305] Massy Holdings Ltd. - Notice of Annual General Meeting dd 26.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[789/1305] Massy Holdings Ltd. - Notice of Appointment of Acting General Counsel (Cover Letter) dd 10.01.23.pdf... direct (0.1s)
[790/1305] Massy Holdings Ltd. - Notice of Appointment of Acting General Counsel (Press Release) dd 10.01.23.pdf... needs_ocr_elsewhere (0.2s)
  -- checkpoint saved (790 ttse records so far)
[791/1305] Massy Holdings Ltd. - Notice of Appointment of Senior Officer (Cover Letter) dd 15.07.2025.pdf... direct (0.1s)
[792/1305] Massy Holdings Ltd. - Notice of Appointment of Senior Officer (Press Release) dd 06.03.2026.pdf... needs_ocr_elsewhere (0.4s)
[793/1305] Massy Holdings Ltd. - Notice of Appointment of Senior Officer (Press Release) dd 15.07.2025.pdf... needs_ocr_elsewhere (0.2s)
[794/1305] Massy Holdings Ltd. - Notice of Appointment of a Senior Officer  (Press Release) dd 23.09.2024.pdf... needs_ocr_elsewhere (0.2s)
[795/1305] Massy Holdings Ltd. - Notice of Appointment of a Senior Officer (Cover Letter) dd 23.09.2024.pdf... direct (0.1s)
[796/1305] Massy Holdings Ltd. - Notice of Change in Board Composition (Press Release) dd 25.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[797/1305] Massy Holdings Ltd. - Notice of Change in Dividend Payment Schedule (Cover Letter) dd 20.11.2024.pdf... direct (0.1s)
[798/1305] Massy Holdings Ltd. - Notice of Change in Dividend Payment Schedule (Press Release) dd 20.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[799/1305] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Cover Letter) dd 12.08.2025.pdf... direct (0.1s)
[800/1305] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Cover Letter) dd 13.08.2025.pdf... direct (0.1s)
  -- checkpoint saved (800 ttse records so far)
[801/1305] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Press Release) dd 12.08.2025.pdf... needs_ocr_elsewhere (0.4s)
[802/1305] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Press Release) dd 13.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[803/1305] Massy Holdings Ltd. - Notice of Change in Senior Officers- EVP & Deputy Group CEO dd 6.12.24.pdf... needs_ocr_elsewhere (0.0s)
[804/1305] Massy Holdings Ltd. - Notice of Changes in Senior Officer (Cover Letter) dd 06.03.2026.pdf... direct (0.1s)
[805/1305] Massy Holdings Ltd. - Notice of Changes to Audit and Risk Committee (Cover Letter) dd 15.12.2025.pdf... direct (0.1s)
[806/1305] Massy Holdings Ltd. - Notice of Consideration Final Dividend Payment (Cover Letter) dd 27.11.2025.pdf... direct (0.1s)
[807/1305] Massy Holdings Ltd. - Notice of Final Dividend Payment (Cover Letter) dd 12.12.2025.pdf... direct (0.3s)
[808/1305] Massy Holdings Ltd. - Notice of Final Dividend Payment (Cover Letter) dd 20.11.2024.pdf... direct (0.1s)
[809/1305] Massy Holdings Ltd. - Notice of Final Dividend Payment (Press Release) dd 12.12.2025.pdf... needs_ocr_elsewhere (0.5s)
[810/1305] Massy Holdings Ltd. - Notice of Interim Dividend Payment (Press Release) dd 06.02.2026.pdf... needs_ocr_elsewhere (0.5s)
  -- checkpoint saved (810 ttse records so far)
[811/1305] Massy Holdings Ltd. - Notice of Interim Dividend Payment (Press Release) dd 08.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[812/1305] Massy Holdings Ltd. - Notice of Interim Dividend Payment dd 07.02.2025.pdf... needs_ocr_elsewhere (0.0s)

[813/1305] Massy Holdings Ltd. - Notice of Interim Dividend Payment dd 09.05.2025.pdf... needs_ocr_elsewhere (0.5s)
[814/1305] Massy Holdings Ltd. - Notice of Partial Final Dividend Payment (Cover Letter) dd 20.11.2025.pdf... direct (0.1s)
[815/1305] Massy Holdings Ltd. - Notice of Partial Final Dividend Payment (Press Release) dd 20.11.2025.pdf... needs_ocr_elsewhere (0.5s)
[816/1305] Massy Holdings Ltd. - Notice of Resignation and Appointment of Directors (Cover Letter) dd 12.03.2025.pdf... direct (0.1s)
[817/1305] Massy Holdings Ltd. - Notice of Resignation of Director (Press Release) dd 12.03.2025.pdf... needs_ocr_elsewhere (0.5s)
[818/1305] Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Cover Letter) dd 09.07.2025.pdf... direct (0.1s)
[819/1305] Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 06.03.2026.pdf... needs_ocr_elsewhere (0.3s)
[820/1305] Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 09.07.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (820 ttse records so far)
[821/1305] Massy Holdings Ltd. - Notice of Third Interim Dividend Payment (Cover Letter) dd 08.08.2025.pdf... direct (0.1s)
[822/1305] Massy Holdings Ltd. - Notice of Third Interim Dividend Payment dd 08.08.2025.pdf... needs_ocr_elsewhere (0.4s)
[823/1305] Massy Holdings Ltd. - Notice of change in Senior Officer (Cover letter) dd 12.03.2024.pdf... direct (0.1s)
[824/1305] Massy Holdings Ltd. - Notice of change in Senior Officer (Cover letter) dd 25.03.2024.pdf... direct (0.1s)
[825/1305] Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 12.03.2024.pdf... needs_ocr_elsewhere (0.3s)
[826/1305] Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 25.03.2024.pdf... needs_ocr_elsewhere (0.2s)
[827/1305] Massy Holdings Ltd. - Notice of change in Senior Officer(Cover Letter) dd 27.02.2024.pdf... direct (0.1s)
[828/1305] Massy Holdings Ltd. - Notice of consideration of final dividend payment (Cover Letter) dd 08.11.2024.pdf... direct (0.1s)
[829/1305] Massy Holdings Ltd. - Trading in Shares (Cover Letter) dd 06.03.2026.pdf... direct (0.3s)
[830/1305] Massy Holdings Ltd. - Trading in Shares (Cover Letter) dd 07.04.2026.pdf... direct (0.1s)
  -- checkpoint saved (830 ttse records so far)
[831/1305] Massy Holdings Ltd. - Trading in Shares (Cover Letter) dd 11.09.2025.pdf... direct (0.1s)
[832/1305] Massy Holdings Ltd. - Trading in Shares (Cover Letter) dd 27.08.2025.pdf... direct (0.1s)
[833/1305] Massy Holdings Ltd. -Amended Notice of Tradig in Shares by a Director (Cover Letter) dd 20.09.2024.pdf... direct (0.1s)
[834/1305] Massy Holdings Ltd. -Notice of Appointment of a Director (Cover letter) dd 14.08.2024.pdf... direct (0.1s)
[835/1305] Massy Holdings Ltd. -Notice of Appointment of a Director (Press release) dd 14.08.2024.pdf... needs_ocr_elsewhere (0.2s)
[836/1305] Massy Holdings Ltd. -Notice of Tradig in Shares by a Director (Cover Letter) dd 20.09.2024.pdf... direct (0.1s)
[837/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Cover Letter) dd 11.09.2024.pdf... direct (0.1s)
[838/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Cover Letter) dd 13.05.2024.pdf... direct (0.1s)
[839/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Cover Letter) dd 23.05.2024.pdf... direct (0.1s)
[840/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Cover letter) dd 12.08.2024.pdf... direct (0.1s)
  -- checkpoint saved (840 ttse records so far)
[841/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 11.09.2024.pdf... needs_ocr_elsewhere (0.4s)
[842/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 12.08.2024.pdf... direct (0.0s)
[843/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 13.05.2024.pdf... needs_ocr_elsewhere (0.3s)
[844/1305] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 23.05.2024.pdf... needs_ocr_elsewhere (0.3s)
[845/1305] Massy Holdings Ltd. Annual Report 2024.pdf... direct (41.4s)
    ^ SLOW FILE -- Massy Holdings Ltd. Annual Report 2024.pdf took 41.4s
[846/1305] Masys Holdings Ltd. - Notice of Appointment of Director (Press Release) dd 12.03.2025.pdf... needs_ocr_elsewhere (0.3s)
[847/1305] Medcorp Limited - Annual Report 2025.pdf... direct (7.8s)
[848/1305] Medcorp Limited - Audited Annual Financial Statements for the Year Ended December 31, 2025.pdf... direct (5.7s)
[849/1305] Medcorp Limited - Management Discussion and Analysis for year ended Dec 31, 2025.pdf... direct (0.5s)
[850/1305] Medcorp Limited - Notice of Annual Meeting (Press Release) dd 07.08.2025.pdf... direct (0.3s)
  -- checkpoint saved (850 ttse records so far)
[851/1305] Medcorp Limited - Notice of Annual Meeting (Press Release) dd 25.06.2026.pdf... direct (0.3s)
[852/1305] Medcorp Limited - Notice of Appointment of Director (Press Release) dd 27.05.2026.pdf... direct (0.1s)
[853/1305] Medcorp Limited - Notice of Availability of Annual Report 2025 (Press Release) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[854/1305] Medcorp Limited - Notice of Change of Senior Officer (PR) dd 06.04.2026.pdf... direct (0.1s)
[855/1305] Medcorp Limited - Notice of Change to Board of Directors (Press Release) dd 18.12.2025.pdf... direct (0.1s)
[856/1305] Medcorp Limited - Notice of Final Dividend Payment (Cover Letter) dd 29.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[857/1305] Medcorp Limited - Notice of Final Dividend Payment (Press Release) dd 29.01.2026.pdf... direct (0.1s)
[858/1305] Medcorp Limited - Notice of Interim Dividend Payment (Cover Letter) dd 18.07.2025.pdf... direct (0.1s)
[859/1305] Medcorp Limited - Notice of Interim Dividend Payment (Press Release) dd 18.07.2025.pdf... direct (0.1s)
[860/1305] Medcorp Limited - Notice of Resignation of Director (Cover Letter) dd 13.05.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (860 ttse records so far)
[861/1305] Medcorp Limited - Notice of Resignation of Director (Press Release) dd 13.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[862/1305] Medcorp Limited - Notice of Temporary Change in Senior Officer (Press Release) dd 29.09.2025.pdf... direct (0.1s)
[863/1305] Medcorp Limited - Notice of Trading in Shares (Cover Letter) dd  02.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[864/1305] Medcorp Limited - Notice of Trading in Shares (Cover Letter) dd  21.08.2025.pdf... direct (0.0s)
[865/1305] Medcorp Limited - Submission of Annual Report 2025 dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[866/1305] Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026.pdf... needs_ocr_elsewhere (0.0s)
[867/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Bruce Bowen  (Cover Letter) dd 08.01.2024.pdf... direct (0.3s)
[868/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 05.05.2026.pdf... direct (0.3s)
[869/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 11.04.2025.pdf... direct (0.2s)
[870/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 17.01.2025.pdf... direct (0.6s)
  -- checkpoint saved (870 ttse records so far)
[871/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 20.01.2025.pdf... direct (0.3s)
[872/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 23.10.2025.pdf... direct (0.2s)
[873/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 29.07.2025.pdf... direct (0.2s)
[874/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 30.01.2026.pdf... direct (0.3s)
[875/1305] NCB Financial Group Limited -  Allotment of NCBFG Shares Septimus Blake  (Cover Letter) dd 27.02.2024.pdf... direct (0.2s)
[876/1305] NCB Financial Group Limited -  Notice of dividend payment (Email) dd 07.08.2025.pdf... direct (0.1s)
[877/1305] NCB Financial Group Limited -  Notice of dividend payment (Email) dd 09.05.2025.pdf... direct (0.1s)
[878/1305] NCB Financial Group Limited -  Notice of dividend payment (Email) dd 10.05.2024.pdf... direct (0.3s)
[879/1305] NCB Financial Group Limited -  Notice of dividend payment (Email) dd 13.11.2025.pdf... direct (0.1s)
[880/1305] NCB Financial Group Limited -  Notice of dividend payment (Email) dd 14.11.2024.pdf... direct (0.1s)
  -- checkpoint saved (880 ttse records so far)
[881/1305] NCB Financial Group Limited -  Notice of dividend payment (Press release) dd 16.08.2024.pdf... direct (0.2s)
[882/1305] NCB Financial Group Limited -  Notice of interim dividend payment (Email) dd 13.02.2026.pdf... direct (0.1s)
[883/1305] NCB Financial Group Limited - APO Prospectus 2024.pdf... direct (45.2s)
    ^ SLOW FILE -- NCB Financial Group Limited - APO Prospectus 2024.pdf took 45.2s
[884/1305] NCB Financial Group Limited - Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 08.01.2024.pdf... direct (0.3s)
[885/1305] NCB Financial Group Limited - Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 12.09.2024.pdf... direct (0.3s)
[886/1305] NCB Financial Group Limited - Allotment of NCBFG Shares Robert Almeida (Cover Letter) dd 24.09.2024.pdf... direct (0.3s)
[887/1305] NCB Financial Group Limited - Annual Report 2024 (Amended).pdf... direct (80.8s)
    ^ SLOW FILE -- NCB Financial Group Limited - Annual Report 2024 (Amended).pdf took 80.8s
[888/1305] NCB Financial Group Limited - Annual Report 2024.pdf... direct (79.2s)
    ^ SLOW FILE -- NCB Financial Group Limited - Annual Report 2024.pdf took 79.2s
[889/1305] NCB Financial Group Limited - Annual Report 2025.pdf... direct (222.7s)
    ^ SLOW FILE -- NCB Financial Group Limited - Annual Report 2025.pdf took 222.7s
[890/1305] NCB Financial Group Limited - Notcie of Excution of Sale and Purchase Agreement dd 21.11.2024.pdf... direct (0.2s)
  -- checkpoint saved (890 ttse records so far)
[891/1305] NCB Financial Group Limited - Notice of  Appointment of a Director (Cover Letter)dd 18.03.2024.pdf... direct (0.2s)
[892/1305] NCB Financial Group Limited - Notice of  Appointment of a Director dd 18.03.2024.pdf... direct (0.2s)
[893/1305] NCB Financial Group Limited - Notice of Additional Public Offering Launch dd 26.04.2024.pdf... direct (0.2s)
[894/1305] NCB Financial Group Limited - Notice of Annual General Meeting (Press Release) dd 23.01.2025.pdf... direct (9.3s)
[895/1305] NCB Financial Group Limited - Notice of Annual General Meeting dd 16.01.2024.pdf... direct (3.2s)
[896/1305] NCB Financial Group Limited - Notice of Appointment of Director (Cover Letter) dd 08.12.2025.pdf... direct (0.2s)
[897/1305] NCB Financial Group Limited - Notice of Appointment of Director (Press Release) dd 08.12.2025.pdf... direct (0.1s)
[898/1305] NCB Financial Group Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 08.01.2026.pdf... direct (0.4s)
[899/1305] NCB Financial Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 08.01.2026.pdf... direct (0.1s)
[900/1305] NCB Financial Group Limited - Notice of Availability of Revised Annual Report 2024 dd 31.01.2025.pdf... direct (0.2s)
  -- checkpoint saved (900 ttse records so far)
[901/1305] NCB Financial Group Limited - Notice of Block Transaction over the JSE (Cover letter) dd 08.04.2025.pdf... direct (0.3s)
[902/1305] NCB Financial Group Limited - Notice of Block Transaction over the JSE (Cover letter) dd 10.04.2025.pdf... direct (0.3s)
[903/1305] NCB Financial Group Limited - Notice of Board Meeting Dates dd 03.05.2024.pdf... direct (0.1s)
[904/1305] NCB Financial Group Limited - Notice of Change in Senior Officer (cover letter) dd 04.12.2024.pdf... direct (0.2s)
[905/1305] NCB Financial Group Limited - Notice of Change in Senior Officer dd 03.12.2024.pdf... direct (0.2s)
[906/1305] NCB Financial Group Limited - Notice of Changes of Senior Officers (Cover Letter) dd 21.01.2026.pdf... direct (0.4s)
[907/1305] NCB Financial Group Limited - Notice of Changes of Senior Officers (Press Release) dd 19.01.2026.pdf... direct (0.2s)
[908/1305] NCB Financial Group Limited - Notice of Changes to the Board of Directors dd 21.03.2024.pdf... direct (0.2s)
[909/1305] NCB Financial Group Limited - Notice of Closure of Additional Public Offering  04.06.2024.pdf... direct (0.2s)
[910/1305] NCB Financial Group Limited - Notice of Completion of Sale and Purchase Agreement dd 28.01.2025.pdf... direct (0.2s)
  -- checkpoint saved (910 ttse records so far)
[911/1305] NCB Financial Group Limited - Notice of Dividend Consideration dd 09.02.2024.pdf... direct (0.2s)
[912/1305] NCB Financial Group Limited - Notice of Dividend Payment (Press Release) dd 16.02.2024.pdf... direct (0.3s)
[913/1305] NCB Financial Group Limited - Notice of Extension of Additional Public Offering  24.05.2024.pdf... direct (0.2s)
[914/1305] NCB Financial Group Limited - Notice of Fitch Ratings (Press Release) dd 27.02.2026.pdf... direct (0.1s)
[915/1305] NCB Financial Group Limited - Notice of Intent to Raise Funding (Cover Letter) dd 04.06.2025.pdf... direct (0.2s)
[916/1305] NCB Financial Group Limited - Notice of Intent to Raise Funding (Press Release) dd 04.06.2025.pdf... direct (0.2s)
[917/1305] NCB Financial Group Limited - Notice of Resignation of Director (Cover Letter) dd 22.01.2026.pdf... direct (0.2s)
[918/1305] NCB Financial Group Limited - Notice of Resignation of Director (Press Release) dd 22.01.2026.pdf... direct (0.1s)
[919/1305] NCB Financial Group Limited - Notice of Trading in Shares (Cover Letter) dd 03.06.2026.pdf... direct (0.3s)
[920/1305] NCB Financial Group Limited - Notice of Trading in Shares (Cover Letter) dd 19.03.2026.pdf... direct (0.4s)
  -- checkpoint saved (920 ttse records so far)
[921/1305] NCB Financial Group Limited - Notice of Trading in Shares (Cover Letter) dd 19.06.2026.pdf... direct (0.3s)
[922/1305] NCB Financial Group Limited - Notice of Trading in Shares (Cover Letter) dd 24.02.2026.pdf... direct (0.3s)
[923/1305] NCB Financial Group Limited - Notice of Update to Proposed Transaction (Press Release) dd 18.07.2025.pdf... direct (0.1s)
[924/1305] NCB Financial Group Limited - Notice of Virtual Third Quarter Investors' Briefing dd 05.08.2024.pdf... direct (0.2s)
[925/1305] NCB Financial Group Limited - Notice of a Proposed Divestment of a Cayman Subsidiary dd 02.02.2024.pdf... direct (0.1s)
[926/1305] NCB Financial Group Limited - Notice of interim dividend payment (Email) dd 08.05.2026.pdf... direct (0.1s)
[927/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 07.03.2025.pdf... direct (0.4s)
[928/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 07.04.2025.pdf... direct (0.2s)
[929/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 10.09.2024.pdf... direct (0.3s)
[930/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 12.11.2024.pdf... direct (0.3s)
  -- checkpoint saved (930 ttse records so far)
[931/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 13.08.2025.pdf... direct (0.3s)
[932/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 25.09.2024.pdf... direct (0.3s)
[933/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 26.02.2024.pdf... direct (0.3s)
[934/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 28.02.2024.pdf... direct (0.3s)
[935/1305] NCB Financial Group Limited - Notice of trading in shares over the JSE (Cover letter) dd 29.02.2024.pdf... direct (0.4s)
[936/1305] NCB Financial Group Limited - Notificiation of Allotment of NCBFG VIA APO Allocation dd 09.07.2024.pdf... direct (0.3s)
[937/1305] NCB Financial Group Limited - Proxy Form for AGM dd 23.01.2025.pdf... direct (0.1s)
[938/1305] NCB Financial Group Limited - Submission of Annual Report (Cover Letter) dd 26.01.2026.pdf... needs_ocr_elsewhere (0.0s)

[939/1305] NCB Financial Group Limited- Proxy Form Annual General Meeting 2023.pdf... direct (0.7s)
[940/1305] NIF Mgt. Disc & Analysis 2025.pdf... direct (0.9s)
  -- checkpoint saved (940 ttse records so far)
[941/1305] National Enterprises Limited - Annual Report 2024  dd 28.01.2025.pdf... direct (0.1s)
[942/1305] National Enterprises Limited - Notice of 2023 Annual Report (Cover Letter) dd 29.01.2024.pdf... direct (0.1s)
[943/1305] National Enterprises Limited - Notice of Annual General Meeting (Cover Letter) dd 14.08.2025.pdf... direct (0.1s)
[944/1305] National Enterprises Limited - Notice of Annual General Meeting (Press Release) dd 14.08.2025.pdf... direct (0.2s)
[945/1305] National Enterprises Limited - Notice of Annual General Meeting (Press Release) dd 15.05.2024.pdf... direct (0.2s)
[946/1305] National Enterprises Limited - Notice of Annual General Meeting (Press Release) dd 19.02.2026.pdf... direct (0.3s)
[947/1305] National Enterprises Limited - Notice of Annual General Meeting (Press Release) dd 29.02.2024.pdf... direct (0.2s)
[948/1305] National Enterprises Limited - Notice of Annual General Meeting-Express dd 29.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[949/1305] National Enterprises Limited - Notice of Annual General Meeting-Guardian dd 29.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[950/1305] National Enterprises Limited - Notice of Annual Report 2025 (Cover Letter) dd 28.01.2026.pdf... direct (0.1s)
  -- checkpoint saved (950 ttse records so far)
[951/1305] National Enterprises Limited - Notice of Appointment of Chairman (Press Release) dd 09.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[952/1305] National Enterprises Limited - Notice of Availability of Annual Report 2024 dd 28.01.2025.pdf... needs_ocr_elsewhere (0.5s)
[953/1305] National Enterprises Limited - Notice of Change in Directors (Cover letter)  dd 07.06.2024.pdf... direct (0.1s)
[954/1305] National Enterprises Limited - Notice of Change in Directors dd 07.06.2024.pdf... needs_ocr_elsewhere (0.5s)
[955/1305] National Enterprises Limited - Notice of Dividend Payment (Cover Letter) dd 13.12.2023.pdf... direct (0.1s)
[956/1305] National Enterprises Limited - Notice of Dividend Payment (Cover Letter) dd 19.07.2023.pdf... needs_ocr_elsewhere (0.0s)
[957/1305] National Enterprises Limited - Notice of Dividend Payment (Cover Letter) dd 28.02.2023.pdf... direct (0.1s)
[958/1305] National Enterprises Limited - Notice of Dividend Payment (Press Release) dd 18.12.2023.pdf... needs_ocr_elsewhere (0.5s)
[959/1305] National Enterprises Limited - Notice of Dividend Payment (Press Release) dd 19.07.2023.pdf... needs_ocr_elsewhere (0.4s)
[960/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Cover Letter) dd 18.06.2026.pdf... direct (0.1s)
  -- checkpoint saved (960 ttse records so far)
[961/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Cover Letter) dd 22.05.2024.pdf... direct (0.1s)
[962/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Cover Letter) dd 23.06.2025.pdf... direct (0.1s)
[963/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 17.06.2026.pdf... needs_ocr_elsewhere (0.1s)
[964/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 22.05.2024.pdf... needs_ocr_elsewhere (0.4s)
[965/1305] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 23.06.2025.pdf... needs_ocr_elsewhere (0.4s)
[966/1305] National Enterprises Limited - Notice of Resignation of Director (Cover Letter) dd 09.01.2026.pdf... direct (0.1s)
[967/1305] National Enterprises Limited - Notice of Resignation of Director (Cover Letter) dd 13.05.2025.pdf... direct (0.1s)
[968/1305] National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 09.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[969/1305] National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 13.05.2025.pdf... needs_ocr_elsewhere (0.3s)
[970/1305] National Enterprises Limited - Notice of Retirement of Directors (Cover Letter) dd 05.09.2025.pdf... direct (0.1s)
  -- checkpoint saved (970 ttse records so far)
[971/1305] National Enterprises Limited - Notice of Retirement of Directors (Press Release) dd 08.09.2025.pdf... needs_ocr_elsewhere (0.4s)
[972/1305] National Enterprises Limited - Notice of Second Interim Dividend Payment (CL) dd 31.12.2025.pdf... direct (0.2s)
[973/1305] National Enterprises Limited - Notice of Second Interim Dividend Payment (PR) dd 31.12.2025.pdf... needs_ocr_elsewhere (0.4s)
[974/1305] National Enterprises Limited - Notice of Third Dividend Payment (Press release) dd 13.12.2023.pdf... needs_ocr_elsewhere (0.4s)
[975/1305] National Enterprises Limited - Proxy Form for Annual General Meeting dd 27.08.2025.pdf... direct (0.3s)
[976/1305] National Enterprises Limited - Shareholdings Report as at December 31 2024  dd 14.02.2025.pdf... direct (0.2s)
[977/1305] National Enterprises Limited - Shareholdings Report as at December 31, 20233 dd 09.02.2024.pdf... direct (0.2s)
[978/1305] National Enterprises Limited - Shareholdings Report as at December 31st, 2025 dd 13.02.2026.pdf... direct (0.4s)
[979/1305] National Enterprises Limited - Shareholdings Report as at June 30th, 2025 dd 14.08.2025.pdf... direct (0.2s)
[980/1305] National Enterprises Limited - Shareholdings Report as at June, 30 2024 dd 06.08.2024.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (980 ttse records so far)
[981/1305] National Enterprises Limited - Shareholdings Report as at March, 31 2024 dd 14.05.2024.pdf... direct (0.2s)
[982/1305] National Enterprises Limited - Shareholdings Report as at March, 31 2025 dd 15.05.2025.pdf... direct (0.3s)
[983/1305] National Enterprises Limited - Shareholdings Report as at March, 31 2025 dd 15.05.2026.pdf... direct (0.2s)
[984/1305] National Enterprises Limited - Shareholdings Report as at September, 30 2024 dd 20.12.2024.pdf... direct (0.4s)
[985/1305] National Enterprises Limited - Shareholdings Report as at September, 30 2025 dd 29.12.2025.pdf... direct (0.2s)
[986/1305] National Enterprises Limited - Trading in Shares by Director (Cover Letter) dd 25.02.2025.pdf... direct (0.1s)
[987/1305] National Enterprises Limited 2024 Annual Report.pdf... direct (13.2s)
[988/1305] National Enterprises Limited 2025 Annual Report.pdf... direct (14.1s)
[989/1305] National Flour Mills Limited - Amended Notice of Annual General Meeting (Cover Letter) dd 10.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[990/1305] National Flour Mills Limited - Amended Notice of Annual General Meeting (Press Release) dd 10.12.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (990 ttse records so far)
[991/1305] National Flour Mills Limited - Amended Notice of Final Dividend Payment (Cover Letter) 31.12.2025.pdf... direct (0.2s)
[992/1305] National Flour Mills Limited - Audited Annual Financial Statements for the year ended Dec 31, 2025.pdf... direct (2.6s)
[993/1305] National Flour Mills Limited - Biography of Nominees for Directors.pdf... direct (0.2s)
[994/1305] National Flour Mills Limited - Notice of AGM, Proxy Form and Management Proxy Circular.pdf... needs_ocr_elsewhere (7.8s)
[995/1305] National Flour Mills Limited - Notice of Annual General Meeting of Shareholders dd 23.05.2024.pdf... needs_ocr_elsewhere (2.6s)
[996/1305] National Flour Mills Limited - Notice of Annual Meeting (Cover Letter) dd 25.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[997/1305] National Flour Mills Limited - Notice of Annual Meeting (Press Release) dd 29.09.2025.pdf... needs_ocr_elsewhere (2.3s)
[998/1305] National Flour Mills Limited - Notice of Appointment of Director (Cover Letter) 04.11.2024.pdf... needs_ocr_elsewhere (0.0s)
[999/1305] National Flour Mills Limited - Notice of Appointment of Directors (Cover Letter) dd 31.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[1000/1305] National Flour Mills Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 27.05.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1000 ttse records so far)
[1001/1305] National Flour Mills Limited - Notice of Appointment of Senior Officer (Press Release) dd 29.05.2026.pdf... direct (0.1s)
[1002/1305] National Flour Mills Limited - Notice of Availability of Annual Report (Press Release) dd 01.05.2026.pdf... direct (0.1s)
[1003/1305] National Flour Mills Limited - Notice of Changes to Board of Directors (Press Release) dd 02.01.2026.pdf... direct (0.2s)
[1004/1305] National Flour Mills Limited - Notice of Election of Directors (Cover Letter) 27.09.2024.pdf... needs_ocr_elsewhere (0.0s)
[1005/1305] National Flour Mills Limited - Notice of Final Dividend Payment (Cover Letter) 30.12.2025.pdf... needs_ocr_elsewhere (0.0s)
[1006/1305] National Flour Mills Limited - Notice of Postponement of Annual Meeting (Cover Letter) dd 17.10.2025.pdf... needs_ocr_elsewhere (0.0s)
[1007/1305] National Flour Mills Limited - Notice of Postponement of Annual Meeting (Press Release) dd 17.10.2025.pdf... direct (0.1s)
[1008/1305] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 03.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[1009/1305] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 08.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1010/1305] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 12.02.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1010 ttse records so far)
[1011/1305] National Flour Mills Limited - Notice of Resignation of Senior Officer (Press Release) dd 03.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[1012/1305] National Flour Mills Limited - Notice of Resignation of Senior Officer (Press Release) dd 13.08.2025.pdf... direct (0.0s)
[1013/1305] National Flour Mills Limited - Notice of Resignation of a Director (Cover Letter) 06.09.2024.pdf... needs_ocr_elsewhere (0.0s)
[1014/1305] National Flour Mills Limited - Notice of Resignation of a Director (Cover Letter) dd 26.06.2024.pdf... needs_ocr_elsewhere (0.0s)
[1015/1305] National Flour Mills Limited - Notice of Resignation of a Director (Press release) dd 09.09.2024.pdf... direct (0.0s)
[1016/1305] National Flour Mills Limited -Notice of Change of Directors (Press Release) dd 01.10.2024.pdf... direct (0.0s)
[1017/1305] National Flour Mills Limited Annual Report 2024.pdf... direct (10.3s)
[1018/1305] National Flour Mills Limited Annual Report 2025.pdf... direct (109.8s)
    ^ SLOW FILE -- National Flour Mills Limited Annual Report 2025.pdf took 109.8s
[1019/1305] National Investment Fund Holding Company Limited - 13th Semi Annual Coupon Payment dd 10.02.2025.pdf... direct (0.1s)
[1020/1305] National Investment Fund Holding Company Limited - 14th Semi Annual Coupon Payment dd 11.08.2025.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1020 ttse records so far)
[1021/1305] National Investment Fund Holding Company Limited - Annual Report 2024 (Cover Letter) dd 28.04.2025.pdf... direct (0.1s)
[1022/1305] National Investment Fund Holding Company Limited - Annual Report 2024.pdf... direct (7.7s)
[1023/1305] National Investment Fund Holding Company Limited - Annual Report 2025.pdf... direct (7.2s)
[1024/1305] National Investment Fund Holding Company Limited - Notice of NIF Bond 2 Offering dd 17.01.24.pdf... needs_ocr_elsewhere (0.7s)
[1025/1305] National Investment Fund Holding Company Limited - Revision regarding Investment Notice dd 09.01.2024.pdf... needs_ocr_elsewhere (0.4s)
[1026/1305] Notice of Record Date for Annual Report (Cover Letter) dd 27.03.2024.pdf... needs_ocr_elsewhere (0.0s)
[1027/1305] Notice of Record Date for Annual Report (Press release) dd 27.03.2024.pdf... needs_ocr_elsewhere (0.6s)
[1028/1305] One Caribbean Medai Limited - Notice of Annual General Meeting dd 12.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[1029/1305] One Caribbean Media Limited  Annual Report 2024.pdf... direct (11.3s)
[1030/1305] One Caribbean Media Limited  Annual Report 2025.pdf... direct (13.3s)
  -- checkpoint saved (1030 ttse records so far)
[1031/1305] One Caribbean Media Limited - Annual Report (Cover Letter) 2024 dd 29.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[1032/1305] One Caribbean Media Limited - Notice of Annual General Meeting (Cover Letter) dd 16.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[1033/1305] One Caribbean Media Limited - Notice of Annual General Meeting (Press Release) dd 11.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[1034/1305] One Caribbean Media Limited - Notice of Annual General Meeting.pdf... needs_ocr_elsewhere (0.0s)
[1035/1305] One Caribbean Media Limited - Notice of Availability of Annual Report 2025 dd 06.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[1036/1305] One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 07.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[1037/1305] One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 09.06.2025.pdf... needs_ocr_elsewhere (0.0s)
[1038/1305] One Caribbean Media Limited - Notice of Dividend Payment (Press Release) dd 12.11.2025.pdf... needs_ocr_elsewhere (0.0s)
[1039/1305] One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[1040/1305] One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1040 ttse records so far)
[1041/1305] One Caribbean Media Limited - Notice of Final Dividend Payment (Press Release) dd 04.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[1042/1305] One Caribbean Media Limited - Notice of Final Dividend Payment (Press Release) dd 06.06.2025.pdf... direct (0.1s)
[1043/1305] One Caribbean Media Limited - Notice of Final Dividend payment  dd 08.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[1044/1305] One Caribbean Media Limited - Notice of Final Dividend payment (Press Releases) dd 06.06.2024.pdf... needs_ocr_elsewhere (0.0s)
[1045/1305] One Caribbean Media Limited - Notice of Publication of Annual Report 2023 dd15.05.2024.pdf... needs_ocr_elsewhere (0.0s)
[1046/1305] One Caribbean Media Limited - Notice of Publication of Annual Report 2024 dd 29.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[1047/1305] One Caribbean Media Limited - Notice of Resignation of Director (Cover Letter) dd 05.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1048/1305] One Caribbean Media Limited - Notice of Resignation of Director (Press Release) dd 05.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1049/1305] One Caribbean Media Limited - Notice of Trading in Shares (Cover Letter) dd 22.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1050/1305] Point Lisas Industrial Port Development Corporation Limited -  Notice to Shareholders dd 06.05.2024.pdf... direct (0.1s)
  -- checkpoint saved (1050 ttse records so far)
[1051/1305] Point Lisas Industrial Port Development Corporation Limited Annual Report 2024.pdf... direct (11.8s)
[1052/1305] Point Lisas Industrial Port Development Corporation Limited Annual Report 2025.pdf... direct (12.8s)
[1053/1305] Prestige Holdings Limited  - Notice of Annual Meeting dd 26.04.2024.pdf... direct (0.3s)
[1054/1305] Prestige Holdings Limited - Amended Notice of Special Dividend Payment (Cover Letter) dd 08.07.2025.pdf... direct (0.1s)
[1055/1305] Prestige Holdings Limited - Amended Notice of Special Dividend Payment (Press Release) dd 08.07.2025.pdf... direct (0.2s)
[1056/1305] Prestige Holdings Limited - Annual Report 2024 (Cover Letter) dd 25.04.2025.pdf... direct (0.1s)
[1057/1305] Prestige Holdings Limited - Annual Report 2024 - 6 copies (Cover Letter) dd 02.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[1058/1305] Prestige Holdings Limited - Annual Report 2025 (hardcopy) (Cover Letter) dd 31.03.2026.pdf... needs_ocr_elsewhere (0.0s)
[1059/1305] Prestige Holdings Limited - Annual Report 2025 (softcopy) (Cover Letter) dd 31.03.2026.pdf... direct (0.0s)
[1060/1305] Prestige Holdings Limited - Director's Circular of Takeover Bid and Offer (Full) dd 04.07.2025.pdf... direct (2.2s)
  -- checkpoint saved (1060 ttse records so far)
[1061/1305] Prestige Holdings Limited - Noice of Takeover Bid and Offer (Cover Letter) dd 18.06.2025.pdf... direct (0.3s)
[1062/1305] Prestige Holdings Limited - Notice of 2023 Final Dividend Payment dd 20.05.2024.pdf... direct (0.0s)
[1063/1305] Prestige Holdings Limited - Notice of 2024 Final Dividend Payment (Cover Letter) dd 21.03.2025.pdf... direct (0.1s)

[1064/1305] Prestige Holdings Limited - Notice of 2024 Final Dividend Payment (Press Release) dd 28.03.2025.pdf... direct (0.2s)
[1065/1305] Prestige Holdings Limited - Notice of Annual General Meeting dd 14.04.2025.pdf... direct (0.4s)
[1066/1305] Prestige Holdings Limited - Notice of Annual Meeting 2025 (Cover Letter) dd 15.04.2026.pdf... direct (0.1s)
[1067/1305] Prestige Holdings Limited - Notice of Annual Meeting 2025 (Press Release) dd 15.04.2026.pdf... direct (0.4s)
[1068/1305] Prestige Holdings Limited - Notice of Appointment of Company Secretary (Cover Letter) dd 26.06.2024.pdf... direct (0.1s)
[1069/1305] Prestige Holdings Limited - Notice of Appointment of Company Secretary (Press release) dd 26.06.2024.pdf... direct (0.3s)
[1070/1305] Prestige Holdings Limited - Notice of Appointment of a Senior Officer (Cover letter)  dd 09.05.2024.pdf... direct (0.1s)
  -- checkpoint saved (1070 ttse records so far)
[1071/1305] Prestige Holdings Limited - Notice of Appointment of a Senior Officer (Press release)  dd 09.05.2024.pdf... direct (0.2s)
[1072/1305] Prestige Holdings Limited - Notice of Availability of Annual Report 2025 (PR) dd 01.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[1073/1305] Prestige Holdings Limited - Notice of Change in Senior Officer dd 22.04.2024.pdf... direct (0.2s)
[1074/1305] Prestige Holdings Limited - Notice of Delay of Publication of Annual Report dd 15.04.2025.pdf... direct (0.2s)
[1075/1305] Prestige Holdings Limited - Notice of Development Incentive Agreement (Cover Letter) dd 02.09.2025.pdf... direct (0.1s)
[1076/1305] Prestige Holdings Limited - Notice of Development Incentive Agreement (Press Release) dd 02.09.2025.pdf... direct (0.0s)
[1077/1305] Prestige Holdings Limited - Notice of Error in Record Date (Cover Letter) dd 02.04.2026.pdf... direct (0.1s)
[1078/1305] Prestige Holdings Limited - Notice of Error in Record Date (Press Release) dd 02.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[1079/1305] Prestige Holdings Limited - Notice of Final Dividend Payment (Cover Letter) dd 27.02.2026.pdf... direct (0.1s)
[1080/1305] Prestige Holdings Limited - Notice of Final Dividend Payment (Press Release) dd 27.02.2026.pdf... direct (0.2s)
  -- checkpoint saved (1080 ttse records so far)
[1081/1305] Prestige Holdings Limited - Notice of Interim Dividend Payment  (Cover Letter) dd 04.07.2024.pdf... direct (0.1s)
[1082/1305] Prestige Holdings Limited - Notice of Interim Dividend Payment  (Press release) dd 04.07.2024.pdf... direct (0.2s)
[1083/1305] Prestige Holdings Limited - Notice of Interim Dividend Payment (Cover Letter) dd 30.06.2025.pdf... direct (0.1s)
[1084/1305] Prestige Holdings Limited - Notice of Interim Dividend Payment (Press Release) dd 30.06.2025.pdf... direct (0.4s)
[1085/1305] Prestige Holdings Limited - Notice of Second Amendment to 2025 Annual Report (CL) dd 14.04.2026.pdf... direct (0.1s)
[1086/1305] Prestige Holdings Limited - Notice of Second Amendment to 2025 Annual Report (PR) dd 14.04.2026.pdf... direct (0.0s)
[1087/1305] Prestige Holdings Limited - Notice of Special Dividend Payment (Cover Letter) dd 04.07.2025.pdf... direct (0.1s)
[1088/1305] Prestige Holdings Limited - Notice of Takeover Bid and Offer (Press Release) dd 18.06.2025.pdf... direct (0.1s)
[1089/1305] Prestige Holdings Limited - Revised Notice of Special Dividend Payment (Press Release) dd 12.08.2025.pdf... direct (0.0s)
[1090/1305] Prestige Holdings Limited Amended Annual Report 2025.pdf... direct (33.9s)
    ^ SLOW FILE -- Prestige Holdings Limited Amended Annual Report 2025.pdf took 33.9s
  -- checkpoint saved (1090 ttse records so far)
[1091/1305] Prestige Holdings Limited Annual Report 2024.pdf... needs_ocr_elsewhere (191.4s)
    ^ SLOW FILE -- Prestige Holdings Limited Annual Report 2024.pdf took 191.4s
[1092/1305] Prestige Holdings Limited Annual Report 2025.pdf... direct (13.0s)
[1093/1305] RFHLG Summry Audit Report 2024.pdf... direct (0.6s)
[1094/1305] Republic Financial Holdings Limited - Financial Highlights for the 2nd Quarter ended March 31st, 2026.pdf... needs_ocr_elsewhere (0.0s)
[1095/1305] Republic Financial Holdings Limited - Form of Proxy for Annual Meeting 2025.pdf... direct (0.5s)
[1096/1305] Republic Financial Holdings Limited - Management Proxy Circular for Annual Meeting 2025.pdf... direct (0.1s)
[1097/1305] Republic Financial Holdings Limited - Notice of Annual Meeting (for shareholders)  dd 07.11.2025.pdf... direct (0.1s)
[1098/1305] Republic Financial Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 16.10.2025.pdf... direct (0.1s)
[1099/1305] Republic Financial Holdings Limited - Notice of Appointment of President and CEO (CL) dd 30.01.2026.pdf... direct (0.1s)
[1100/1305] Republic Financial Holdings Limited - Notice of Appointment of President and CEO (PR) dd 30.01.2026.pdf... needs_ocr_elsewhere (0.3s)
  -- checkpoint saved (1100 ttse records so far)
[1101/1305] Republic Financial Holdings Limited - Notice of Appointment of Senior Officer (CL) dd 17.12.2025.pdf... direct (0.1s)
[1102/1305] Republic Financial Holdings Limited - Notice of Appointment of Senior Officer (PR) dd 18.12.2025.pdf... direct (0.1s)
[1103/1305] Republic Financial Holdings Limited - Notice of Availability of Annual Report 2025 (PR) dd 21.11.2025.pdf... direct (0.1s)
[1104/1305] Republic Financial Holdings Limited - Notice of Changes of Directors (Cover Letter) dd 16.12.2025.pdf... direct (0.1s)
[1105/1305] Republic Financial Holdings Limited - Notice of Changes of Directors (Press Release) dd 17.12.2025.pdf... direct (0.1s)
[1106/1305] Republic Financial Holdings Limited - Notice of Dividend Payment (Press Release) dd 01.08.2025.pdf... direct (0.1s)
[1107/1305] Republic Financial Holdings Limited - Notice of Dividend Payment (Press Release) dd 05.05.2025.pdf... direct (0.1s)
[1108/1305] Republic Financial Holdings Limited - Notice of Dividend Payment (email) dd 07.02.2025.pdf... direct (0.1s)
[1109/1305] Republic Financial Holdings Limited - Notice of Electronic Version of Annual Report dd 21.11.2024.pdf... direct (0.1s)
[1110/1305] Republic Financial Holdings Limited - Notice of Final Dividend Payment (Press Release) dd 11.11.2025.pdf... direct (0.1s)
  -- checkpoint saved (1110 ttse records so far)
[1111/1305] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (Cover Letter) dd 29.01.2026.pdf... needs_ocr_elsewhere (0.0s)
[1112/1305] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (PR) dd 30.01.2026.pdf... direct (0.1s)
[1113/1305] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (PR) dd 30.04.2026.pdf... direct (0.1s)
[1114/1305] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (email) dd 29.01.2026.pdf... direct (0.1s)
[1115/1305] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (email) dd 30.04.2026.pdf... direct (0.1s)
[1116/1305] Republic Financial Holdings Limited - Notice of Passing of Director (Cover Letter) dd 07.04.2025.pdf... direct (0.1s)
[1117/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Cover Letter) dd 07.10.2025.pdf... direct (0.1s)
[1118/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Cover Letter) dd 08.10.2025.pdf... direct (0.1s)
[1119/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Cover Letter) dd 08.12.2025.pdf... direct (0.1s)
[1120/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Cover Letter) dd 24.11.2025.pdf... direct (0.7s)
  -- checkpoint saved (1120 ttse records so far)
[1121/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Press Release) dd 08.10.2025.pdf... direct (0.1s)
[1122/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Press Release) dd 08.12.2025.pdf... direct (0.1s)
[1123/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Press Release) dd 09.10.2025.pdf... direct (0.1s)
[1124/1305] Republic Financial Holdings Limited - Notice of Resignation of Director (Press Release) dd 25.11.2025.pdf... direct (0.1s)
[1125/1305] Republic Financial Holdings Limited - Notice of annual meeting (Press release) dd 12.11.2024.pdf... direct (0.1s)
[1126/1305] Republic Financial Holdings Limited - Notice of dividend payment (Cover Letter) dd 02.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[1127/1305] Republic Financial Holdings Limited - Notice of dividend payment (Cover Letter) dd 31.07.2025.pdf... needs_ocr_elsewhere (0.0s)
[1128/1305] Republic Financial Holdings Limited - Notice of dividend payment (Cover letter) dd 01.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[1129/1305] Republic Financial Holdings Limited - Notice of dividend payment (Cover letter) dd 11.11.2024.pdf... direct (0.1s)
[1130/1305] Republic Financial Holdings Limited - Notice of dividend payment (Cover letter) dd 29.04.2024.pdf... direct (0.1s)
  -- checkpoint saved (1130 ttse records so far)
[1131/1305] Republic Financial Holdings Limited - Notice of dividend payment (Email) dd 02.05.2025.pdf... direct (0.2s)
[1132/1305] Republic Financial Holdings Limited - Notice of dividend payment (Email) dd 10.11.2025.pdf... direct (0.1s)
[1133/1305] Republic Financial Holdings Limited - Notice of dividend payment (Email) dd 31.07.2025.pdf... direct (0.1s)
[1134/1305] Republic Financial Holdings Limited - Notice of dividend payment (Press release) dd 06.08.2024.pdf... direct (0.2s)
[1135/1305] Republic Financial Holdings Limited - Notice of dividend payment (Press release) dd 29.04.2024.pdf... direct (0.1s)
[1136/1305] Republic Financial Holdings Limited - Notice of final dividend payment (Press release) dd 12.11.2024.pdf... direct (0.1s)
[1137/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd 05.02.2024.pdf... direct (0.0s)
[1138/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd 07.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[1139/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd 17.02.2025.pdf... direct (0.1s)
[1140/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd 26.11.2024.pdf... direct (0.1s)
  -- checkpoint saved (1140 ttse records so far)
[1141/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd13.12.2024.pdf... direct (0.1s)
[1142/1305] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd16.12.2024 Amended.pdf... direct (0.0s)
[1143/1305] Republic Financial Holdings Limited - Proxy Documents for Annual Meeting (Cover Letter) dd 19.11.2025.pdf... direct (0.1s)
[1144/1305] Republic Financial Holdings Limited - Shareholdings Report for the 2nd Quarter ended March 31st 2024.pdf... needs_ocr_elsewhere (0.0s)
[1145/1305] Republic Financial Holdings Limited - Shareholdings Report for the 2nd Quarter ended March 31st 2025.pdf... needs_ocr_elsewhere (0.0s)
[1146/1305] Republic Financial Holdings Limited - Shareholdings Report for the 3rd Quarter ended June 30, 2025.pdf... needs_ocr_elsewhere (0.0s)
[1147/1305] Republic Financial Holdings Limited - Top Ten Shareholders as at December 31st, 2023.pdf... needs_ocr_elsewhere (0.0s)
[1148/1305] Republic Financial Holdings Limited - Trading in Shares (Karen Yip Chuck) (Email) dd 27.06.2025.pdf... direct (0.9s)
[1149/1305] Republic Financial Holdings Limited - Trading in Shares (Nigel Baptiste) (Cover Letter) dd 26.06.2025.pdf... direct (0.1s)
[1150/1305] Republic Financial Holdings Limited Annual Report 2024.pdf... direct (22.4s)
  -- checkpoint saved (1150 ttse records so far)
[1151/1305] Republic Financial Holdings Limited Annual Report 2025.pdf... direct (20.7s)
[1152/1305] Scotiabank Trinidad & Tobago Limited - Notice of Annual General Meeting dd 07.02.2024.pdf... direct (0.1s)
[1153/1305] Scotiabank Trinidad and Tobago Limited - Notice of Annual General Meeting dd11.02.2025.pdf... needs_ocr_elsewhere (1.5s)
[1154/1305] Scotiabank Trinidad and Tobago Limited - Notice of Annual Meeting (Press Release) dd 28.01.2026.pdf... needs_ocr_elsewhere (1.3s)
[1155/1305] Scotiabank Trinidad and Tobago Limited - Notice of Changes in Senior Officers (Release) dd 23.01.2026.pdf... needs_ocr_elsewhere (0.5s)
[1156/1305] Scotiabank Trinidad and Tobago Limited - Notice of Dividend Payment dd 08.06.2026.pdf... direct (0.6s)
[1157/1305] Scotiabank Trinidad and Tobago Limited - Notice of Interim Dividend Payment dd17.09.2024.pdf... needs_ocr_elsewhere (0.3s)
[1158/1305] Scotiabank Trinidad and Tobago Limited - Notice of Retirement of a Director 20.03.2024.pdf... needs_ocr_elsewhere (0.6s)
[1159/1305] Scotiabank Trinidad and Tobago Limited - Schedule 10.pdf... direct (0.1s)
[1160/1305] Scotiabank Trinidad and Tobago Limited - Trading in Shares (Cover Letter) dd 19.09.2025.pdf... direct (0.1s)
  -- checkpoint saved (1160 ttse records so far)
[1161/1305] Scotiabank Trinidad and Tobago Limited Annual Report 2024.pdf... direct (18.6s)
[1162/1305] Scotiabank Trinidad and Tobago Limited Annual Report 2025.pdf... direct (16.2s)
[1163/1305] Scotiabank Trinidad and Tobago Limited- Notice of Appointment of Senior Officers (PR1) dd 02.04.2026.pdf... needs_ocr_elsewhere (1.0s)
[1164/1305] Scotiabank Trinidad and Tobago Limited- Notice of Appointment of Senior Officers (PR2) dd 02.04.2026.pdf... needs_ocr_elsewhere (1.0s)
[1165/1305] TTNGL_Express_Condensed Financial Statements for the Six Months Ended 30 June 2025.pdf... needs_ocr_elsewhere (0.0s)
[1166/1305] TTNGL_Guardian_Condensed Financial Statements for the Six Months Ended 30 June 2025.pdf... needs_ocr_elsewhere (0.0s)
[1167/1305] Tearsheet- Trinidad Express- Div Notice- Feb-13-2024.pdf... direct (1.4s)
[1168/1305] The West Indian Tobacco Company Limited - Annual Report 6 copies (Cover Letter) dd 09.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[1169/1305] The West Indian Tobacco Company Limited - Notice of Availability of Annual Report (PR) dd 31.03.2026.pdf... needs_ocr_elsewhere (0.7s)
[1170/1305] The West Indian Tobacco Company Limited - Notice of Change in Directors (Cover Letter) dd 17.10.2025.pdf... direct (0.1s)
  -- checkpoint saved (1170 ttse records so far)
[1171/1305] The West Indian Tobacco Company Limited - Notice of Change in Directors (Press Release) dd 17.10.2025.pdf... needs_ocr_elsewhere (0.7s)
[1172/1305] The West Indian Tobacco Company Limited - Notice of Change of Directors (Cover Letter) dd 21.04.2026.pdf... direct (0.1s)
[1173/1305] The West Indian Tobacco Company Limited - Notice of Change of Directors (Press Release) dd 22.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[1174/1305] The West Indian Tobacco Company Limited - Notice of Final Dividend 2025 (Cover Letter) dd 21.04.2026.pdf... direct (0.1s)
[1175/1305] The West Indian Tobacco Company Limited - Notice of Final Dividend 2025 (Press Release) dd 22.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[1176/1305] The West Indian Tobacco Company Limited - Notice of Trading in Shares (Cover Letter) dd 15.05.2024.pdf... direct (0.1s)
[1177/1305] The West Indian Tobacco Company Limited - Notice of Trading in Shares (Cover letter) dd 01.06.2026.pdf... direct (0.1s)
[1178/1305] The West Indian Tobacco Company Limited - Notice of Trading in Shares (Cover letter) dd 02.06.2026.pdf... direct (0.1s)
[1179/1305] The West Indian Tobacco Company Limited - Notice of Trading in Shares (Cover letter) dd 12.06.2026.pdf... direct (0.1s)
[1180/1305] The West Indian Tobacco Company Limited - Schedule 8 of Director (Cover Letter) dd 14.08.2025.pdf... direct (0.1s)
  -- checkpoint saved (1180 ttse records so far)
[1181/1305] The West Indian Tobacco Company Limited - Schedule 8 of Director dd 13.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1182/1305] The West Indian Tobacco Company Limited Annual Report 2024.pdf... direct (18.3s)
[1183/1305] The West Indian Tobacco Company Limited Annual Report 2025.pdf... direct (14.6s)
[1184/1305] Trinidad Cement Limited - Audited Annual Financial Statements for the Year Ended Dec 31, 2025 (Full).pdf... direct (12.1s)
[1185/1305] Trinidad Cement Limited - Change in Credit Arrangements (Cover Letter) dd 29.05.2025.pdf... needs_ocr_elsewhere (0.0s)

[1186/1305] Trinidad Cement Limited - Notice of Availability of Annual Report 2025 (Cover Letter) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.7s)
[1187/1305] Trinidad Cement Limited - Notice of Availability of Annual Report 2025 (Press Release) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.7s)
[1188/1305] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 03.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[1189/1305] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 30.06.2026.pdf... needs_ocr_elsewhere (0.0s)
[1190/1305] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 04.02.2026.pdf... needs_ocr_elsewhere (1.0s)
  -- checkpoint saved (1190 ttse records so far)
[1191/1305] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 30.06.2026.pdf... needs_ocr_elsewhere (0.7s)
[1192/1305] Trinidad Cement Limited - Notice of Change in Director (Cover Letter) dd 30.07.2025.pdf... direct (0.1s)
[1193/1305] Trinidad Cement Limited - Notice of Change in Director (Press Release) dd 30.07.2025.pdf... needs_ocr_elsewhere (0.6s)
[1194/1305] Trinidad Cement Limited - Notice of Change in Operating Model (Cover letter) dd 17.04.25.pdf... direct (0.1s)
[1195/1305] Trinidad Cement Limited - Notice of Change in Operating Model dd 17.04.25.pdf... needs_ocr_elsewhere (0.9s)
[1196/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 03.04.2024.pdf... needs_ocr_elsewhere (0.0s)
[1197/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 03.07.2024.pdf... needs_ocr_elsewhere (1.2s)
[1198/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 03.12.2024.pdf... direct (0.1s)
[1199/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 07.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[1200/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 03.04.2024.pdf... needs_ocr_elsewhere (0.5s)
  -- checkpoint saved (1200 ttse records so far)
[1201/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 03.12.2024.pdf... needs_ocr_elsewhere (0.4s)
[1202/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 07.05.2026.pdf... needs_ocr_elsewhere (0.6s)
[1203/1305] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 17.06.2025.pdf... direct (0.0s)
[1204/1305] Trinidad Cement Limited - Notice of Changes to Executive Management (Cover Letter) dd 06.01.2025.pdf... direct (0.1s)
[1205/1305] Trinidad Cement Limited - Notice of Changes to Executive Management (Press Release) dd 03.07.2024.pdf... needs_ocr_elsewhere (1.2s)
[1206/1305] Trinidad Cement Limited - Notice of Changes to Executive Management (Press Release) dd 06.01.2025.pdf... needs_ocr_elsewhere (0.6s)
[1207/1305] Trinidad Cement Limited - Notice of Final Dividend Payment (Cover Letter) dd 08.07.2024.pdf... needs_ocr_elsewhere (0.0s)
[1208/1305] Trinidad Cement Limited - Notice of Final Dividend Payment (Press Release) dd 08.07.2024.pdf... needs_ocr_elsewhere (0.4s)
[1209/1305] Trinidad Cement Limited - Notice of Publication of 2023 Annual Report (Press Release) dd 26-04-2024.pdf... needs_ocr_elsewhere (0.7s)
[1210/1305] Trinidad Cement Limited - Notice of Publication of Annual Report 2024 (Cover letter) dd 29.04.2025.pdf... direct (0.2s)
  -- checkpoint saved (1210 ttse records so far)
[1211/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (CL) dd 27.03.2026.pdf... direct (0.1s)
[1212/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Cover Letter) dd 05.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[1213/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Cover Letter) dd 11.06.2026.pdf... direct (0.1s)
[1214/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Cover Letter) dd 13.05.2024.pdf... needs_ocr_elsewhere (0.6s)
[1215/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (PR) dd 27.03.2026.pdf... needs_ocr_elsewhere (0.8s)
[1216/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 05.05.2025.pdf... needs_ocr_elsewhere (1.5s)
[1217/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 11.06.2026.pdf... needs_ocr_elsewhere (0.7s)
[1218/1305] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 13.05.2024.pdf... needs_ocr_elsewhere (0.6s)
[1219/1305] Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024.pdf... needs_ocr_elsewhere (0.7s)
[1220/1305] Trinidad Cement Limited Annual Report 2024.pdf... direct (14.0s)
  -- checkpoint saved (1220 ttse records so far)
[1221/1305] Trinidad Cement Limited Annual Report 2025.pdf... direct (13.2s)
[1222/1305] Trinidad Express - Tearsheet - ECPF  DF - Dec 2023.pdf... direct (11.4s)
[1223/1305] Trinidad Express - Tearsheet - ECPF  VF - Dec 2023.pdf... direct (19.5s)
[1224/1305] Trinidad and Tobago NGL Limited  - Annual Report 2024.pdf... direct (26.4s)
[1225/1305] Trinidad and Tobago NGL Limited  - Annual Report 2025.pdf... direct (10.7s)
[1226/1305] Trinidad and Tobago NGL Limited - Annual Report 2024 Cover Letter dd 23.05.2025.pdf... needs_ocr_elsewhere (0.0s)
[1227/1305] Trinidad and Tobago NGL Limited - Letter to Shareholders and Notice of Annual Meeting dd 21.01.2026.pdf... direct (2.7s)
[1228/1305] Trinidad and Tobago NGL Limited - Notice of Amended Special Dividend Payment Date (PR) dd 04.05.2026.pdf... needs_ocr_elsewhere (0.0s)
[1229/1305] Trinidad and Tobago NGL Limited - Notice of Annual Meeting (Cover Letter) dd 24.10.2024.pdf... direct (0.1s)
[1230/1305] Trinidad and Tobago NGL Limited - Notice of Annual Meeting (Press Release) dd 15.01.2026.pdf... needs_ocr_elsewhere (1.8s)
  -- checkpoint saved (1230 ttse records so far)
[1231/1305] Trinidad and Tobago NGL Limited - Notice of Annual Meeting (Press Release) dd 24.10.2024.pdf... needs_ocr_elsewhere (1.1s)
[1232/1305] Trinidad and Tobago NGL Limited - Notice of Appointment of Directors (Cover Letter) dd 05.09.2025.pdf... direct (0.1s)
[1233/1305] Trinidad and Tobago NGL Limited - Notice of Appointment of Directors (Press Release) dd 04.09.2025.pdf... needs_ocr_elsewhere (0.0s)
[1234/1305] Trinidad and Tobago NGL Limited - Notice of Appointment of a Director dd 08.02.2024.pdf... needs_ocr_elsewhere (0.0s)
[1235/1305] Trinidad and Tobago NGL Limited - Notice of Change in Auditors (Cover Letter) dd 24.03.2026.pdf... direct (0.1s)
[1236/1305] Trinidad and Tobago NGL Limited - Notice of Change in Auditors (Press Release) dd 24.03.2026.pdf... needs_ocr_elsewhere (0.3s)
[1237/1305] Trinidad and Tobago NGL Limited - Notice of Regisnation of a Director (Cover Letter) dd 18.01.2042.pdf... direct (0.1s)
[1238/1305] Trinidad and Tobago NGL Limited - Notice of Rescheduled Annual Meeting (Cover Letter) dd 04.02.2026.pdf... direct (0.1s)
[1239/1305] Trinidad and Tobago NGL Limited - Notice of Rescheduled Annual Meeting (Press Release) dd 04.02.2026.pdf... needs_ocr_elsewhere (0.0s)
[1240/1305] Trinidad and Tobago NGL Limited - Notice of Rescheduled Annual Meeting (Press Release) dd 12.02.2026.pdf... needs_ocr_elsewhere (0.0s)
  -- checkpoint saved (1240 ttse records so far)
[1241/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Cover Letter) dd 12.05.2025.pdf... direct (0.1s)
[1242/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Cover Letter) dd 25.08.2025.pdf... direct (0.1s)
[1243/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Press Release) dd 12.05.2025.pdf... needs_ocr_elsewhere (0.3s)
[1244/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Press Release) dd 25.08.2025.pdf... needs_ocr_elsewhere (0.0s)
[1245/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director (Cover Letter) dd 22.11.2024.pdf... direct (0.1s)
[1246/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director (Press release) dd 22.11.2024.pdf... needs_ocr_elsewhere (0.7s)
[1247/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director Express Clippings.pdf... needs_ocr_elsewhere (0.0s)
[1248/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director Guardian Clippings.pdf... needs_ocr_elsewhere (0.0s)
[1249/1305] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director dd 18.01.2024.pdf... direct (0.1s)
[1250/1305] Trinidad and Tobago NGL Limited - Notice of Special Dividend (Cover Letter) dd 09.04.2026.pdf... direct (0.1s)
  -- checkpoint saved (1250 ttse records so far)
[1251/1305] Trinidad and Tobago NGL Limited - Notice of Special Dividend (Press Release) dd 10.04.2026.pdf... needs_ocr_elsewhere (0.0s)
[1252/1305] Trinidad and Tobago NGL Limited - Notice to Shareholders - Accesibility of Annual Report 29.06.2026.pdf... needs_ocr_elsewhere (0.3s)
[1253/1305] Trinidad and Tobago NGL Limited - Submission of 2023 Annual Report  (Cover letter) dd 02.07.2024.pdf... needs_ocr_elsewhere (0.0s)
[1254/1305] Unilever Caribbean Limited -  Notice of Annual Report  dd 29.04.2024.pdf... direct (0.1s)
[1255/1305] Unilever Caribbean Limited - Annual Financial Statements for the year ended December 31, 2025.pdf... direct (0.8s)
[1256/1305] Unilever Caribbean Limited - Annual Report 2024 (Cover Letter) dd 30.04.2025.pdf... needs_ocr_elsewhere (0.0s)
[1257/1305] Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Cover Letter) dd 14.08.2025.pdf... direct (0.1s)
[1258/1305] Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Press Release) dd 14.08.2025.pdf... needs_ocr_elsewhere (0.4s)
[1259/1305] Unilever Caribbean Limited - Notice of Annual General Meeting (Press Release) dd 20.05.2024.pdf... direct (0.2s)
[1260/1305] Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 19.05.2025.pdf... direct (0.1s)
  -- checkpoint saved (1260 ttse records so far)
[1261/1305] Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 23.06.2026.pdf... needs_ocr_elsewhere (2.1s)
[1262/1305] Unilever Caribbean Limited - Notice of Appointment of Senior Officer (CL) dd 13.03.2025.pdf... direct (0.1s)
[1263/1305] Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 13.03.2025.pdf... needs_ocr_elsewhere (0.3s)
[1264/1305] Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 20.05.2025.pdf... direct (0.1s)
[1265/1305] Unilever Caribbean Limited - Notice of Appointment of Senior Officer 2 (Press Release) dd 20.05.2025.pdf... direct (0.1s)
[1266/1305] Unilever Caribbean Limited - Notice of Appointment of Senior Officers (Cover Letter) dd 19.05.2025.pdf... direct (0.1s)
[1267/1305] Unilever Caribbean Limited - Notice of Appointment of a Director (Cover letter) dd 13.06.2024.pdf... direct (0.1s)
[1268/1305] Unilever Caribbean Limited - Notice of Appointment of a Director (Press release) dd 13.06.2024.pdf... needs_ocr_elsewhere (0.3s)
[1269/1305] Unilever Caribbean Limited - Notice of Availability of Annual Report 2024 dd 30.04.2025.pdf... needs_ocr_elsewhere (0.5s)
[1270/1305] Unilever Caribbean Limited - Notice of Availabilty of Annual Report 2025 (PR) dd 30.04.2026.pdf... needs_ocr_elsewhere (0.5s)
  -- checkpoint saved (1270 ttse records so far)
[1271/1305] Unilever Caribbean Limited - Notice of Change in Dividend Policy (Cover Letter) dd 27.08.2025.pdf... direct (0.1s)
[1272/1305] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Cover Letter) dd 16.09.2025.pdf... direct (0.1s)
[1273/1305] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Cover Letter) dd 27.03.2026.pdf... direct (0.3s)
[1274/1305] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Press Release) dd 16.09.2025.pdf... needs_ocr_elsewhere (0.9s)
[1275/1305] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Press Release) dd 27.03.2026.pdf... needs_ocr_elsewhere (1.0s)
[1276/1305] Unilever Caribbean Limited - Notice of Final Dividend Payment 2023 (Cover Letter) dd 28.03.2024.pdf... direct (0.1s)
[1277/1305] Unilever Caribbean Limited - Notice of Final Dividend Payment 2023 dd 28.03.2024.pdf... direct (0.1s)
[1278/1305] Unilever Caribbean Limited - Notice of Final Dividend Payment 2024 dd 28.03.2025.pdf... needs_ocr_elsewhere (0.4s)
[1279/1305] Unilever Caribbean Limited - Notice of Final and Special Dividend Payment (CL) dd 27.03.2026.pdf... direct (0.1s)
[1280/1305] Unilever Caribbean Limited - Notice of Final and Special Dividend Payment (PR) dd 27.03.2026.pdf... needs_ocr_elsewhere (0.5s)
  -- checkpoint saved (1280 ttse records so far)
[1281/1305] Unilever Caribbean Limited - Notice of Interim Dividend Payment (Cover Letter) dd 14.05.2025.pdf... direct (0.3s)
[1282/1305] Unilever Caribbean Limited - Notice of Interim Dividend Payment (Press Release) dd 14.05.2025.pdf... direct (0.1s)
[1283/1305] Unilever Caribbean Limited - Notice of Interim Dividend Payment 2024 (Cover Letter) dd 08.09.2024.pdf... direct (0.1s)
[1284/1305] Unilever Caribbean Limited - Notice of Interim Dividend Payment 2024 (Press release) dd 08.09.2024.pdf... direct (0.1s)
[1285/1305] Unilever Caribbean Limited - Notice of Interim and Special Dividend Payment (PR) dd 15.05.2026.pdf... direct (0.1s)
[1286/1305] Unilever Caribbean Limited - Notice of Interim and Special Dividend Payment dd 14.11.2025.pdf... direct (0.1s)
[1287/1305] Unilever Caribbean Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 20.05.2026.pdf... direct (0.1s)
[1288/1305] Unilever Caribbean Limited - Notice of Resignation of Senior Officer (PR) dd 21.05.2026.pdf... direct (0.1s)
[1289/1305] Unilever Caribbean Limited - Notice of Resignation of a Director (Cover letter) dd 16.05.2024.pdf... direct (0.1s)
[1290/1305] Unilever Caribbean Limited - Notice of Resignation of a Director (Press release) dd 16.05.2024.pdf... needs_ocr_elsewhere (0.3s)
  -- checkpoint saved (1290 ttse records so far)
[1291/1305] Unilever Caribbean Limited - Notice of Resignation of a Director dd 28.03.2024.pdf... direct (0.1s)
[1292/1305] Unilever Caribbean Limited - Notice of Resignation of a Senior Officer (Cover letter) dd 06.11.2024.pdf... direct (0.1s)
[1293/1305] Unilever Caribbean Limited - Notice of Resignation of a Senior Officer (Cover letter) dd 24.12.2024.pdf... direct (0.1s)
[1294/1305] Unilever Caribbean Limited - Notice of Resignation of a Senior Officer (Press Release) dd 06.11.2024.pdf... direct (0.1s)
[1295/1305] Unilever Caribbean Limited - Notice of Resignation of a Senior Officer (Press Release) dd 24.12.2024.pdf... needs_ocr_elsewhere (0.4s)
[1296/1305] Unilever Caribbean Limited - Shareholding & Statutory Report as at March 31st, 2026.pdf... direct (1.3s)
[1297/1305] Unilever Caribbean Limited - Statutory Report as at December 31, 2025.pdf... direct (1.3s)
[1298/1305] Unilever Caribbean Limited - Statutory Report as at June 30, 2025.pdf... direct (1.0s)
[1299/1305] Unilever Caribbean Limited - Statutory Report as at June 30th, 2024.pdf... direct (1.7s)
[1300/1305] Unilever Caribbean Limited - Statutory Report as at March 31st, 2024.pdf... direct (1.5s)
  -- checkpoint saved (1300 ttse records so far)
[1301/1305] Unilever Caribbean Limited - Statutory Report as at March 31st, 2025.pdf... direct (1.2s)
[1302/1305] Unilever Caribbean Limited - Statutory Report as at September 30, 2025.pdf... direct (1.2s)
[1303/1305] Unilever Caribbean Limited - Statutory Report as at September 30th, 2024.pdf... direct (1.4s)
[1304/1305] Unilever Caribbean Limited Annual Report 2024.pdf... direct (11.7s)
[1305/1305] Unilever Caribbean Limited Annual Report 2025.pdf... direct (10.9s)

Done. Total records (including resumed): 4740

JSE:
  Direct: 2997
  Needs OCR (cloud, via Part 3): 290

BSE:
  Direct: 123
  Needs OCR (cloud, via Part 3): 25

TTSE:
  Direct: 874
  Needs OCR (cloud, via Part 3): 431

In [39]:
# Save the data for each exchange in a separate file
for source_name in pdf_files_by_source:
    source_records = [r for r in records if r["source"] == source_name]
    if not source_records:
        continue
    out_path = Path(f"{source_name}_local_pdf_corpus.json")
    out_path.write_text(json.dumps(source_records, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Saved {len(source_records)} records to {out_path.resolve()}")

Saved 3287 records to /home/areas001/Final Project/Final Notebooks/jse_local_pdf_corpus.json
Saved 148 records to /home/areas001/Final Project/Final Notebooks/bse_local_pdf_corpus.json
Saved 1305 records to /home/areas001/Final Project/Final Notebooks/ttse_local_pdf_corpus.json

## TTSE Price Data Extraction

In [40]:
# Define each type of TTSE price file
REPORT_TYPE_PREFIXES = {
    "dcbs": "corporate_bond",
    "dgbs": "government_bond",
    "divs": "index_summary",
    "ds": "daily_quotes",}

# Define a function to classify each file by their name
def classify_report(filename: str):
    stem = filename.lower()
    for prefix, report_type in REPORT_TYPE_PREFIXES.items():
        if stem.startswith(prefix):
            return report_type
    return None

# Set the classification groups
classified = {"corporate_bond": [], "government_bond": [], "index_summary": [], "daily_quotes": [], "unknown": []}

# For each TTSE trade file classify them into type
for p in ttse_trade_files:
    report_type = classify_report(p.name)
    classified[report_type or "unknown"].append(p)

# For each type, print the number of files
for report_type, files in classified.items():
    print(f"{report_type}: {len(files)} file(s)")

# If the file does not fall into an above classification, classify them as unknown
if classified["unknown"]:
    print("\nUnknown-prefix files:")
    for p in classified["unknown"][:10]:
        print(" -", p.name)

corporate_bond: 617 file(s)
government_bond: 617 file(s)
index_summary: 619 file(s)
daily_quotes: 619 file(s)
unknown: 0 file(s)

In [41]:
# Map the bond column names to the file names
BOND_HEADER_MAP = {
    "symbol": "symbol", "security": "security", "issue price": "issue_price",
    "opening quotation": "opening_quotation", "high": "day_high", "low": "day_low",
    "bid price": "bid_price", "bid volume": "bid_volume", "offer price": "offer_price",
    "offer volume": "offer_volume", "price": "last_sale_price", "date": "last_sale_date",
    "last trade yield": "last_trade_yield", "face value traded": "face_value_traded",
    "trade value": "trade_value", "closing quotation": "closing_quotation",
    "change from opening quotation": "change_from_opening",}

# Define a function to find the bond header row
def find_bond_header_row(table: list, max_scan_rows: int = 5):
    for i in range(min(max_scan_rows, len(table))):
        row_values = [str(c).strip().lower() if c else "" for c in table[i]]
        matches = sum(1 for v in row_values if v in BOND_HEADER_MAP)
        if matches >= 3:
            return i
    return None

# Define a function to extract the bond table from the PDFs
def extract_bond_table(pdf_path: Path, bond_type: str) -> list:
    rows_out = []
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                for table in page.extract_tables():
                    if not table:
                        continue
                    header_idx = find_bond_header_row(table)
                    if header_idx is None:
                        continue
                    header_row = [str(c).strip().lower() if c else "" for c in table[header_idx]]
                    column_map = [BOND_HEADER_MAP.get(h, f"unrecognized_{h or 'col'}") for h in header_row]
                    for data_row in table[header_idx + 1:]:
                        if not data_row or not data_row[0]:
                            continue
                        row_dict = dict(zip(column_map, [str(c).strip() if c else "" for c in data_row]))
                        row_dict["bond_type"] = bond_type
                        row_dict["source_file"] = pdf_path.name
                        rows_out.append(row_dict)
    except Exception as e:
        print(f"  Failed to extract bond table from {pdf_path.name}: {e}")
    return rows_out

In [42]:
# Create a variable to save all extracted price rows
all_bond_rows = []

# For each bond file, extract the price rows
for report_type, bond_files in [("corporate", classified["corporate_bond"]),
                                  ("government", classified["government_bond"])]:
    for p in bond_files:
        all_bond_rows.extend(extract_bond_table(p, report_type))

# Print the number of rows extracted
print(f"Total bond rows extracted: {len(all_bond_rows)}")

# Save the bond prices in a DataFrame
bond_df = pd.DataFrame(all_bond_rows)

# Save the bond prices to csv
bond_df.to_csv("ttse_bond_data.csv", index=False)
print(f"Saved {len(bond_df)} rows to ttse_bond_data.csv")

# Preview the top 5 rows of the bond prices
bond_df.head(5)

Total bond rows extracted: 8165
Saved 8165 rows to ttse_bond_data.csv

,symbol,security,issue_price,unrecognized_opening\nquotation,unrecognized_trade prices,unrecognized_col,unrecognized_outstanding,unrecognized_last sale,last_trade_yield,face_value_traded,trade_value,unrecognized_closing\nquotation,change_from_opening,bond_type,source_file
0,NIF090830,"$1,600M NIF SERIES B 5.70% 09.08.2030",100.00,103.37,,28 Dec 2023,103.05,103.37,5.09,,,103.37,,corporate,dcbs-2024-01-02.pdf
1,NIF090838,"$1,200M NIF SERIES C 6.60% 09.08.2038",100.00,106.10,,20 Nov 2023,106.10,106.10,5.97,,,106.10,,corporate,dcbs-2024-01-02.pdf
2,NIF090830,"$1,600M NIF SERIES B 5.70% 09.08.2030",100.00,103.37,,28 Dec 2023,103.05,103.37,5.09,,,103.37,,corporate,dcbs-2024-01-03.pdf
3,NIF090838,"$1,200M NIF SERIES C 6.60% 09.08.2038",100.00,106.10,,20 Nov 2023,106.10,106.10,5.97,,,106.10,,corporate,dcbs-2024-01-03.pdf
4,NIF090830,"$1,600M NIF SERIES B 5.70% 09.08.2030",100.00,103.37,,28 Dec 2023,103.05,103.37,5.09,,,103.37,,corporate,dcbs-2024-01-04.pdf

In [43]:
# Maps the daily trades table headers to the extract headers
SECTOR_TABLE_HEADER = {"security", "issued share capital", "capitalisation value", "trades",
                        "traded volume", "traded value", "index", "change", "change %", "change%"}

TOP_LEVEL_HEADER = {"capitalisation value", "trades", "traded volume", "traded value", "index",
                    "change", "change %", "change%"}


# Define a function to classify the daily index reports
def classify_divs_table(table: list):
    for row in table[:2]:
        row_values = {str(c).strip().lower() if c else "" for c in row}
        if "security" in row_values and len(row_values & SECTOR_TABLE_HEADER) >= 4:
            return "sector"
        if len(row_values & TOP_LEVEL_HEADER) >= 4:
            return "top_level"
    return None

# Defines a function to extract the rows from the daily index reports
def extract_divs_tables(pdf_path: Path) -> dict:
    top_level_rows, sector_rows = [], []
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                for table in page.extract_tables():
                    if not table or len(table) < 2:
                        continue
                    table_kind = classify_divs_table(table)
                    if table_kind is None:
                        continue
                    header_row = [str(c).strip().lower() if c else "" for c in table[0]]
                    header_row = [h if h else f"col_{i}" for i, h in enumerate(header_row)]
                    for data_row in table[1:]:
                        if not data_row or not any(data_row):
                            continue
                        row_dict = dict(zip(header_row, [str(c).strip() if c else "" for c in data_row]))
                        row_dict["source_file"] = pdf_path.name
                        (top_level_rows if table_kind == "top_level" else sector_rows).append(row_dict)
    except Exception as e:
        print(f"  Failed to extract DIVS tables from {pdf_path.name}: {e}")
    return {"top_level": top_level_rows, "sector_detail": sector_rows}

In [44]:
all_top_level_rows, all_sector_rows = [], []

# For all index reports, extract the price rows
for p in classified["index_summary"]:
    result = extract_divs_tables(p)
    all_top_level_rows.extend(result["top_level"])
    all_sector_rows.extend(result["sector_detail"])

# Print the number of rows extracted
print(f"Total top-level summary rows: {len(all_top_level_rows)}")
print(f"Total sector detail rows: {len(all_sector_rows)}")

# Save the index price rows to csv
pd.DataFrame(all_top_level_rows).to_csv("ttse_market_summary.csv", index = False)

# Save the index prices in a DataFrame
sector_df = pd.DataFrame(all_sector_rows)
sector_df.to_csv("ttse_sector_detail.csv", index = False)
print("Saved ttse_market_summary.csv and ttse_sector_detail.csv")

# Retrieve the top 5 rows for sanity check
sector_df.head(5)

Total top-level summary rows: 2970
Total sector detail rows: 30829
Saved ttse_market_summary.csv and ttse_sector_detail.csv

,security,issued share\ncapital,capitalisation\nvalue,trades,traded\nvolume,traded\nvalue,index,change,change\n%,source_file,traded value,issued\nshare\ncapital,capitalisation value
0,FCGFH,"251,353,562","12,343,973,430",4,87,"4,272.97",,,,divs-2024-01-02.pdf,NaN,NaN,NaN
1,FCI,"1,577,094,570","11,102,745,773",-,-,-,,,,divs-2024-01-02.pdf,NaN,NaN,NaN
2,NCBFG,"2,466,762,828","8,460,996,500",2,"8,779","30,078.25",,,,divs-2024-01-02.pdf,NaN,NaN,NaN
3,RFHL,"163,673,762","20,087,680,810",4,27,"3,292.56",,,,divs-2024-01-02.pdf,NaN,NaN,NaN
4,SBTT,"176,343,750","12,285,869,063",2,78,"5,416.80",,,,divs-2024-01-02.pdf,NaN,NaN,NaN

In [45]:
# Map the index headers to the extract headers
DS_TOP_LEVEL_HEADER = {"index value", "index change", "change (%)", "volume traded",
                       "value traded ($)", "no. of trades"}

DS_SECURITY_HEADER = {"security", "open price ($)", "high ($)", "low ($)", "o/s bid ($)",
                      "o/s bid vol.", "o/s offer ($)", "o/s offer vol.", "last sale price ($)",
                      "last sale date", "volume traded", "close price ($)", "change ($)"}

# List the TTSE market segments
KNOWN_CATEGORIES = ["Ordinary Shares", "Preference Shares", "Second Tier Shares", "SME Shares",
                    "Mutual Fund Units", "USD Equity Shares"]

# Define a function to remove the embedded newlines/extra whitespace
def normalize_cell(cell) -> str:
    
    if not cell:
        return ""
    return " ".join(str(cell).replace("\n", " ").split())

# Define a function to classify the index reports
def classify_ds_table(table: list):
    for row in table[:2]:
        row_values = {normalize_cell(c).lower() for c in row}
        if len(row_values & DS_SECURITY_HEADER) >= 4:
            return "security_detail"
        if len(row_values & DS_TOP_LEVEL_HEADER) >= 4:
            return "top_level"
    return None

# Define a function to find the headings row
def find_category_headings(page, tolerance: float = 3.0):
 
    words = page.extract_words()
    if not words:
        return []
    words_sorted = sorted(words, key=lambda w: w["top"])
    lines, current_line, current_top = [], [words_sorted[0]], words_sorted[0]["top"]
    for w in words_sorted[1:]:
        if abs(w["top"] - current_top) <= tolerance:
            current_line.append(w)
        else:
            lines.append(current_line)
            current_line, current_top = [w], w["top"]
    lines.append(current_line)

    headings = []
    for line_words in lines:
        line_top = min(w["top"] for w in line_words)
        line_text = " ".join(w["text"] for w in sorted(line_words, key=lambda x: x["x0"]))
        line_text_norm = " ".join(line_text.split()).lower()
        for cat in KNOWN_CATEGORIES:
            if cat.lower() in line_text_norm:
                headings.append((line_top, cat))
                break
    return sorted(headings)

# Define a function to extract the rows from the trade report
def extract_ds_tables(pdf_path: Path) -> dict:
    
    top_level_rows, security_rows = [], []
    current_category = "Ordinary Shares"

    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                headings = find_category_headings(page)
                found_tables = sorted(page.find_tables(), key=lambda t: t.bbox[1])

                for t_obj in found_tables:
                    table = t_obj.extract()
                    if not table or len(table) < 2:
                        continue
                    table_kind = classify_ds_table(table)
                    if table_kind is None:
                        continue

                    header_row = [normalize_cell(c) for c in table[0]]
                    header_row = [h if h else f"col_{i}" for i, h in enumerate(header_row)]

                    table_top = t_obj.bbox[1]
                    for heading_top, cat in headings:
                        if heading_top < table_top:
                            current_category = cat
                        else:
                            break

                    for data_row in table[1:]:
                        if not data_row or not any(data_row):
                            continue
                        row_dict = dict(zip(header_row, [normalize_cell(c) for c in data_row]))
                        row_dict["source_file"] = pdf_path.name
                        if table_kind == "top_level":
                            top_level_rows.append(row_dict)
                        else:
                            row_dict["category"] = current_category
                            security_rows.append(row_dict)
    except Exception as e:
        print(f"  Failed to extract DS tables from {pdf_path.name}: {e}")

    return {"top_level": top_level_rows, "security_detail": security_rows}

In [46]:
all_ds_top_level_rows, all_ds_security_rows = [], []

# For each PDF, extract the daily quote price rows
for p in classified["daily_quotes"]:
    result = extract_ds_tables(p)
    all_ds_top_level_rows.extend(result["top_level"])
    all_ds_security_rows.extend(result["security_detail"])

# Print the number of rows
print(f"Total top-level summary rows: {len(all_ds_top_level_rows)}")
print(f"Total security detail rows: {len(all_ds_security_rows)}")

# Save the daily quote price rows to csv
pd.DataFrame(all_ds_top_level_rows).to_csv("ttse_daily_quotes_market_summary.csv", index = False)

# Save the daily quote prices to a DataFrame
ds_security_df = pd.DataFrame(all_ds_security_rows)

# Save the daily quote rows to csv
ds_security_df.to_csv("ttse_daily_quotes_security_detail.csv", index = False)

print("Saved ttse_daily_quotes_market_summary.csv and ttse_daily_quotes_security_detail.csv")

# Print the number of rows per market segment
if not ds_security_df.empty:
    print("\nRows per category:")
    print(ds_security_df["category"].value_counts(dropna=False))

# Print the first 5 rows as a sanity check
ds_security_df.head(5)

Total top-level summary rows: 4952
Total security detail rows: 16041
Saved ttse_daily_quotes_market_summary.csv and ttse_daily_quotes_security_detail.csv

Rows per category:
category
Ordinary Shares       8944
Mutual Fund Units     2476
SME Shares            1935
Preference Shares     1238
USD Equity Shares      829
Second Tier Shares     619
Name: count, dtype: int64

,col_0,Security,Open Price ($),High ($),Low ($),O/S Bid ($),O/S Bid Vol.,O/S Offer ($),O/S Offer Vol.,Last Sale Price ($),Last Sale Date,Volume Traded,Close Price ($),Change ($),source_file,category
0,,AGL,68.49,,,68.33,93,68.49,502,68.50,29-12-2023,,68.49,,ds-2024-01-02.pdf,Ordinary Shares
1,,AHL,21.95,,,21.95,2,22.24,"1,000",22.00,29-12-2023,,21.95,,ds-2024-01-02.pdf,Ordinary Shares
2,,AMBL,45.10,43.00,43.00,43.00,143,45.00,500,43.00,02-01-2024,88,45.10,,ds-2024-01-02.pdf,Ordinary Shares
3,,AMCL,54.06,55.90,55.90,55.00,"2,687",55.90,172,55.90,02-01-2024,33,54.06,,ds-2024-01-02.pdf,Ordinary Shares
4,,FCGFH,49.11,49.15,49.11,49.11,"1,383",49.20,525,49.11,02-01-2024,87,49.11,,ds-2024-01-02.pdf,Ordinary Shares

## Cloud OCR Extraction

In [5]:
# Import required package
from PIL import Image

# Se OCR key (obtained from OCR API website)
API_KEY = "K81492402488957" 

# Set OCR URL
OCR_SPACE_URL = "https://api.ocr.space/parse/image"

# Set OCR extraction configuration
MAX_REQUEST_BYTES = 1_000_000
REQUEST_DELAY_SECONDS = 20
OCR_TIMEOUT = 120

# Set the exchange corpus file paths
CORPUS_FILES = {
    "jse": Path("jse_local_pdf_corpus.json"),
    "bse": Path("bse_local_pdf_corpus.json"),
    "ttse": Path("ttse_local_pdf_corpus.json"),}

In [19]:
# Set the corpora and flagged records variables
corpora = {}
flagged_records = {}

# Retrieve the PDFs that require OCR extraction
for source_name, path in CORPUS_FILES.items():
    if not path.exists():
        print(f"Could not find {path} -- skipping.")
        corpora[source_name] = []
        flagged_records[source_name] = []
        continue
    with open(path, "r", encoding="utf-8") as f:
        corpora[source_name] = json.load(f)
    flagged_records[source_name] = [r for r in corpora[source_name] if r["retrieved_via"] == "needs_ocr_elsewhere"]
    print(f"{source_name}: {len(corpora[source_name])} total, {len(flagged_records[source_name])} flagged for cloud OCR")

jse: 3287 total, 290 flagged for cloud OCR
bse: 148 total, 25 flagged for cloud OCR
ttse: 1305 total, 431 flagged for cloud OCR

In [21]:
# Import the required packages
import fitz
import time as time_module

# Define a function to render each PDF page for OCR extraction
def render_page_compressed(page, max_bytes: int = None, dpi_override: int = None) -> bytes:
    
    max_bytes = max_bytes or MAX_REQUEST_BYTES
    dpi_sequence = [dpi_override] if dpi_override else [200, 150, 100, 75]

    for dpi in dpi_sequence:
        zoom = dpi / 72
        matrix = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix = matrix)
        img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
        for quality in (85, 70, 55, 40):
            buf = io.BytesIO()
            img.save(buf, format = "JPEG", quality = quality)
            if buf.tell() <= max_bytes:
                return buf.getvalue()
    return buf.getvalue()

In [22]:
# Define a function to extract each rendered PDF page
def ocr_space_extract_page(page, filename_hint: str, max_attempts: int = 3) -> tuple:
   
    dpi_by_attempt = [200, 120, 75]

    for attempt in range(max_attempts):
        dpi = dpi_by_attempt[min(attempt, len(dpi_by_attempt) - 1)]
        image_bytes = render_page_compressed(page, dpi_override = dpi)

        files = {"file": (filename_hint, image_bytes, "image/jpeg")}
        data = {"apikey": API_KEY, "language": "eng", "isOverlayRequired": "false", "OCREngine": "2"}

        try:
            resp = requests.post(OCR_SPACE_URL, files = files, data = data, timeout = OCR_TIMEOUT)
        except requests.exceptions.Timeout:
            print(f"    Timeout on {filename_hint} (attempt {attempt+1}/{max_attempts}, dpi = {dpi})")
            time_module.sleep(5)
            continue
        except requests.RequestException as e:
            return "", f"request exception: {e}"

        if resp.status_code == 429:
            try:
                retry_after = resp.json().get("retryAfter", 60)
            except ValueError:
                retry_after = 60
            print(f"    Rate limited -- sleeping {retry_after}s...")
            time_module.sleep(retry_after + 5)
            continue

        if resp.status_code == 502 or resp.status_code >= 500:
            print(f"    Server error ({resp.status_code}) on {filename_hint}, attempt {attempt+1}")
            time_module.sleep(8)
            continue

        if resp.status_code != 200:
            return "", f"HTTP {resp.status_code}: {resp.text[:200]}"

        try:
            result = resp.json()
        except ValueError:
            return "", f"non-JSON response: {resp.text[:200]}"

        if result.get("IsErroredOnProcessing"):
            return "", f"API error: {result.get('ErrorMessage')}"

        parsed_results = result.get("ParsedResults") or []
        return (parsed_results[0].get("ParsedText", "").strip(), None) if parsed_results else ("", "empty ParsedResults")

    return "", f"failed after {max_attempts} attempts (timeouts/errors)"

In [23]:
# Define a function to process each extracted PDF page via OCR Cloud
def process_pdf_via_cloud_ocr(pdf_path: Path) -> str:
    try:
        doc = fitz.open(pdf_path)
    except Exception as e:
        print(f"  Failed to open {pdf_path.name}: {e}")
        return ""

    page_texts = []
    for page_num, page in enumerate(doc):
        try:
            text, error = ocr_space_extract_page(page, filename_hint=f"{pdf_path.stem}_p{page_num+1}.jpg")
            if error:
                print(f"    page {page_num+1} failed: {error}")
            page_texts.append(text)
        except Exception as e:
            print(f"  Failed on {pdf_path.name} page {page_num+1}: {e}")
        time_module.sleep(REQUEST_DELAY_SECONDS)

    return "\n".join(page_texts).strip()

In [26]:
# Set variable to save OCR results
ocr_results = {}

# Set the max number of files per run
MAX_FILES_THIS_RUN = 2000

# Save a progress file for the OCR extraction
partial_results_path = Path("cloud_ocr_partial_results.json")
if partial_results_path.exists():
    with open(partial_results_path, "r", encoding = "utf-8") as f:
        ocr_results = json.load(f)
    print(f"Resuming -- {len(ocr_results)} files already processed in a previous run.")

# For each PDF page, extract via Cloud OCR 
for source_name, recs in flagged_records.items():
    remaining = [r for r in recs if not ocr_results.get(r["filename"])] 
    remaining = remaining[:MAX_FILES_THIS_RUN]
    if not remaining:
        continue
    print(f"\n=== {source_name.upper()}: {len(remaining)} remaining this run (capped at {MAX_FILES_THIS_RUN}) ===")

    for i, record in enumerate(remaining):
        pdf_path = Path(record["filepath"])
        file_start = time_module.time()
        print(f"[{i+1}/{len(remaining)}] {pdf_path.name}...", end=" ")

        text = process_pdf_via_cloud_ocr(pdf_path)
        elapsed = time_module.time() - file_start
        print(f"{'OK' if text else 'FAILED (no text)'} ({elapsed:.1f}s)")

        ocr_results[record["filename"]] = text

        if (i + 1) % 10 == 0:
            with open(partial_results_path, "w", encoding="utf-8") as f:
                json.dump(ocr_results, f, indent = 2, ensure_ascii = False)
            print(f"  -- checkpoint saved ({len(ocr_results)} total results so far)")

# Save the results 
with open(partial_results_path, "w", encoding = "utf-8") as f:
    json.dump(ocr_results, f, indent = 2, ensure_ascii = False)

# Once completed, print the number of sucesses and failures
print(f"\nDone. {len(ocr_results)} files processed via cloud OCR.")
print(f"  Succeeded: {sum(1 for t in ocr_results.values() if t)}")
print(f"  Failed: {sum(1 for t in ocr_results.values() if not t)}")

Resuming -- 20 files already processed in a previous run.

=== JSE: 270 remaining this run (capped at 2000) ===
[1/270] AMGS-TOP-10-AT-31-AUGUST-2024.pdf... OK (21.3s)
[2/270] AMGS-TOP-10-AT-31-MAY-2025.pdf... OK (21.3s)
[3/270] AMGS-TOP-10-AT-31-MAY-2026-1.pdf... OK (21.3s)
[4/270] ASBH-NoAGM-2026.pdf... OK (21.3s)
[5/270] ASBH-Release-Dec-6-2024.pdf... OK (21.3s)
[6/270] AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024.pdf...     Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p4.jpg, attempt 1
    Timeout on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p4.jpg (attempt 2/3, dpi=120)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p5.jpg, attempt 1
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p5.jpg, attempt 2
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p6.jpg, attempt 1
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p6.jpg, attempt 2
    Timeout on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p31.jpg (attempt 1/3, dpi=200)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p31.jpg, attempt 2
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p31.jpg, attempt 3
    page 31 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p32.jpg, attempt 1
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p32.jpg, attempt 2
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p32.jpg, attempt 3
    page 32 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p33.jpg, attempt 1
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p33.jpg, attempt 2
    Server error (502) on AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p33.jpg, attempt 3
    page 33 failed: failed after 3 attempts (timeouts/errors)
OK (2010.6s)
[7/270] AUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025.pdf...     page 20 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    page 21 failed: API error: ['Download Failed']
OK (932.1s)
[8/270] Addendum-to-Prospectus-Tropical-Battery-Company-June-19-2025.pdf... OK (64.3s)
[9/270] Advisory-Tom-Tyler-Steps-Down-from-the-CPJ-Board-of-Directors.pdf...     Server error (502) on Advisory-Tom-Tyler-Steps-Down-from-the-CPJ-Board-of-Directors_p1.jpg, attempt 1
    Server error (502) on Advisory-Tom-Tyler-Steps-Down-from-the-CPJ-Board-of-Directors_p1.jpg, attempt 2
OK (202.7s)
[10/270] Amended-Notice-of-AGM-2025.pdf... OK (21.7s)
  -- checkpoint saved (30 total results so far)
[11/270] Atlantic-Hardware-Plumbing-AHPC-Unaudited-Financial-Statements-for-the-Second-Quarter-ended-June-30-2025.pdf... OK (171.4s)
[12/270] Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024.pdf...     page 10 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Timeout on Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024_p11.jpg (attempt 1/3, dpi=200)
    Server error (502) on Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024_p11.jpg, attempt 2
    Server error (502) on Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024_p11.jpg, attempt 3
    page 11 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Atlantic-Hardware-Plumbing-Company-Limited-Signed-Audited-Financial-Statements-FY-2024_p12.jpg, attempt 1
OK (1268.9s)
[13/270] BOND-DISCLOSURE-LETTER.pdf... OK (21.2s)
[14/270] BPOW-Notice-of-Annual-General-Meeting.pdf... OK (20.9s)
[15/270] Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025.pdf...     Timeout on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p4.jpg (attempt 1/3, dpi=200)
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p4.jpg, attempt 2
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p5.jpg, attempt 1
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p5.jpg, attempt 2
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p6.jpg, attempt 1
    Server error (502) on Barita-Investments-Limited-Financial-Report-12Months-Sept-30-2025_p13.jpg, attempt 1
OK (1176.3s)
[16/270] Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1.pdf...     Server error (502) on Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1_p3.jpg, attempt 1
    page 3 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1_p4.jpg, attempt 1
    Server error (502) on Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1_p4.jpg, attempt 2
    Server error (502) on Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Barita-Investments-Limited-Financial-Report-6-Months-March-31-2026-1_p5.jpg, attempt 1
OK (947.2s)
[17/270] Barita-Investments-Limited-Financial-Report-9Months-June-30-2025.pdf...     page 14 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on Barita-Investments-Limited-Financial-Report-9Months-June-30-2025_p15.jpg, attempt 1
    Server error (502) on Barita-Investments-Limited-Financial-Report-9Months-June-30-2025_p15.jpg, attempt 2
    Server error (502) on Barita-Investments-Limited-Financial-Report-9Months-June-30-2025_p15.jpg, attempt 3
    page 15 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Barita-Investments-Limited-Financial-Report-9Months-June-30-2025_p16.jpg, attempt 1
    Server error (502) on Barita-Investments-Limited-Financial-Report-9Months-June-30-2025_p16.jpg, attempt 2
OK (967.9s)
[18/270] Barita-Investments-Ltd_A-Credit-Rating.pdf... OK (43.3s)
[19/270] BaritaInvestmentsLimited-FinancialReport-12Months-SEPT-30-24-11-14-24.pdf...     Timeout on BaritaInvestmentsLimited-FinancialReport-12Months-SEPT-30-24-11-14-24_p21.jpg (attempt 1/3, dpi=200)
    Server error (502) on BaritaInvestmentsLimited-FinancialReport-12Months-SEPT-30-24-11-14-24_p21.jpg, attempt 2
    Server error (502) on BaritaInvestmentsLimited-FinancialReport-12Months-SEPT-30-24-11-14-24_p21.jpg, attempt 3
    page 21 failed: failed after 3 attempts (timeouts/errors)
OK (723.7s)
[20/270] BaritaInvestmentsLimited-FinancialReport-3Months-DEC-31-2025.pdf...     Server error (502) on BaritaInvestmentsLimited-FinancialReport-3Months-DEC-31-2025_p1.jpg, attempt 1
    Server error (502) on BaritaInvestmentsLimited-FinancialReport-3Months-DEC-31-2025_p1.jpg, attempt 2
    Server error (502) on BaritaInvestmentsLimited-FinancialReport-3Months-DEC-31-2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
OK (698.4s)
  -- checkpoint saved (40 total results so far)

[21/270] BaritaInvestmentsLimited-FinancialReport-3Months-December-31-2024-0214-0705.pdf...     page 10 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    page 11 failed: API error: ['Download Failed']
OK (621.7s)
[22/270] BaritaInvestmentsLimited-FinancialReport-6Months-March-31-2025-v4.pdf... OK (530.9s)
[23/270] CAR-Unaudited_FS_Q3-Ended-30Sept2024.pdf...     Timeout on CAR-Unaudited_FS_Q3-Ended-30Sept2024_p10.jpg (attempt 1/3, dpi=200)
    Server error (502) on CAR-Unaudited_FS_Q3-Ended-30Sept2024_p10.jpg, attempt 2
    Server error (502) on CAR-Unaudited_FS_Q3-Ended-30Sept2024_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
OK (505.4s)
[24/270] CCC-Top-Ten-as-at-March-31-2025.pdf...     Server error (502) on CCC-Top-Ten-as-at-March-31-2025_p1.jpg, attempt 1
    Server error (502) on CCC-Top-Ten-as-at-March-31-2025_p1.jpg, attempt 2
    Server error (502) on CCC-Top-Ten-as-at-March-31-2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on CCC-Top-Ten-as-at-March-31-2025_p2.jpg, attempt 1
OK (357.2s)
[25/270] CCCL-Top-Ten-1-1.pdf... OK (43.2s)
[26/270] CCCL-Top-Ten-1.pdf... OK (42.2s)
[27/270] CEO-FORUM-Speakers.pdf... OK (21.3s)
[28/270] CHL-Dec-25-Q-1.pdf... OK (169.4s)
[29/270] CHL-June-26-Q3.pdf... OK (170.7s)
[30/270] CHL-Mar-26-Q2.pdf...     page 5 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on CHL-Mar-26-Q2_p6.jpg, attempt 1
    Server error (502) on CHL-Mar-26-Q2_p6.jpg, attempt 2
OK (397.5s)
  -- checkpoint saved (50 total results so far)
[31/270] Car-Unaudited-FS-June-30-2025.pdf...     Server error (502) on Car-Unaudited-FS-June-30-2025_p4.jpg, attempt 1
    Server error (502) on Car-Unaudited-FS-June-30-2025_p4.jpg, attempt 2
    Server error (502) on Car-Unaudited-FS-June-30-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Car-Unaudited-FS-June-30-2025_p5.jpg, attempt 1
    Server error (502) on Car-Unaudited-FS-June-30-2025_p5.jpg, attempt 2
OK (560.7s)
[32/270] Cargo-Handlers-Ltd-Annual-Report-2025.pdf...     page 15 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on Cargo-Handlers-Ltd-Annual-Report-2025_p16.jpg, attempt 1
    Server error (502) on Cargo-Handlers-Ltd-Annual-Report-2025_p16.jpg, attempt 2
    Server error (502) on Cargo-Handlers-Ltd-Annual-Report-2025_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
OK (878.6s)
[33/270] Caribbean-Producers-Jamaica-Limited-CPJ-%E2%80%93-Notice-of-Resignation-from-the-Board-of-Directors.pdf... OK (21.2s)
[34/270] Caribbean-Producers-Jamaica-Limited-Change-in-Fiscal-Year-End.pdf... OK (21.2s)
[35/270] Carreras-Limited-2024-Annual-Report.pdf...     Server error (502) on Carreras-Limited-2024-Annual-Report_p18.jpg, attempt 1
    Server error (502) on Carreras-Limited-2024-Annual-Report_p18.jpg, attempt 2
    Server error (502) on Carreras-Limited-2024-Annual-Report_p18.jpg, attempt 3
    page 18 failed: failed after 3 attempts (timeouts/errors)
    page 19 failed: API error: ['Download Failed']
    Server error (502) on Carreras-Limited-2024-Annual-Report_p45.jpg, attempt 1
    Server error (502) on Carreras-Limited-2024-Annual-Report_p45.jpg, attempt 2
    Server error (502) on Carreras-Limited-2024-Annual-Report_p58.jpg, attempt 1
    Timeout on Carreras-Limited-2024-Annual-Report_p58.jpg (attempt 2/3, dpi=120)
    Server error (502) on Carreras-Limited-2024-Annual-Report_p58.jpg, attempt 3
    page 58 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Carreras-Limited-2024-Annual-Report_p59.jpg, attempt 1
    Server error (502) on Carreras-Limited-2024-Annual-Report_p74.jpg, attempt 1
    Server error (502) on Carreras-Limited-2024-Annual-Report_p82.jpg, attempt 1
    Server error (502) on Carreras-Limited-2024-Annual-Report_p82.jpg, attempt 2
    Timeout on Carreras-Limited-2024-Annual-Report_p86.jpg (attempt 1/3, dpi=200)
    Server error (502) on Carreras-Limited-2024-Annual-Report_p86.jpg, attempt 2
    Server error (502) on Carreras-Limited-2024-Annual-Report_p86.jpg, attempt 3
    page 86 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Carreras-Limited-2024-Annual-Report_p87.jpg, attempt 1
OK (4037.0s)
[36/270] Carreras-Limited-Annual-Report-2025.pdf...     page 3 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on Carreras-Limited-Annual-Report-2025_p4.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p4.jpg, attempt 2
    Server error (502) on Carreras-Limited-Annual-Report-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Carreras-Limited-Annual-Report-2025_p5.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p25.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p25.jpg, attempt 2
    Server error (502) on Carreras-Limited-Annual-Report-2025_p25.jpg, attempt 3
    page 25 failed: failed after 3 attempts (timeouts/errors)
    page 28 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Server error (502) on Carreras-Limited-Annual-Report-2025_p29.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p29.jpg, attempt 2
    Server error (502) on Carreras-Limited-Annual-Report-2025_p29.jpg, attempt 3
    page 29 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Carreras-Limited-Annual-Report-2025_p31.jpg, attempt 1
    Timeout on Carreras-Limited-Annual-Report-2025_p68.jpg (attempt 1/3, dpi=200)
    Server error (502) on Carreras-Limited-Annual-Report-2025_p70.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p81.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p106.jpg, attempt 1
    Timeout on Carreras-Limited-Annual-Report-2025_p106.jpg (attempt 2/3, dpi=120)
    Server error (502) on Carreras-Limited-Annual-Report-2025_p106.jpg, attempt 3
    page 106 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Carreras-Limited-Annual-Report-2025_p107.jpg, attempt 1
    Server error (502) on Carreras-Limited-Annual-Report-2025_p107.jpg, attempt 2
    Server error (502) on Carreras-Limited-Annual-Report-2025_p107.jpg, attempt 3
    page 107 failed: failed after 3 attempts (timeouts/errors)
OK (4540.9s)
[37/270] Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed.pdf...     Timeout on Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed_p10.jpg (attempt 1/3, dpi=200)
    Server error (502) on Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed_p10.jpg, attempt 2
    Server error (502) on Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed_p11.jpg, attempt 1
    Server error (502) on Consolidated-Bakeries-Jamaica-Limited-2025-Final-Financial-Statement-Signed_p13.jpg, attempt 1
OK (1340.2s)
[38/270] DTL-Shareholdings_Q4_2024_JSE.pdf... OK (20.9s)
[39/270] Delay-of-Audited-Financial-Statements.pdf...     Server error (502) on Delay-of-Audited-Financial-Statements_p1.jpg, attempt 1
    Timeout on Delay-of-Audited-Financial-Statements_p1.jpg (attempt 2/3, dpi=120)
    Server error (502) on Delay-of-Audited-Financial-Statements_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (229.7s)
[40/270] Director-Stocks-Sale-Notice-1.pdf...     Server error (502) on Director-Stocks-Sale-Notice-1_p1.jpg, attempt 1
    Server error (502) on Director-Stocks-Sale-Notice-1_p1.jpg, attempt 2
    Server error (502) on Director-Stocks-Sale-Notice-1_p1.jpg, attempt 3

    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (224.5s)
  -- checkpoint saved (60 total results so far)
[41/270] Directors-Holding-as-at-January-31-2026.pdf... OK (85.2s)
[42/270] Directors-Holding-as-at-June-30-2026.pdf... OK (66.4s)
[43/270] Directors-Holding-as-at-March-31-2026.pdf... OK (63.2s)
[44/270] Directors-Holding-as-at-October-31-2025.pdf... OK (63.2s)
[45/270] Directors-Holdings-as-at-November-1-2025-1.pdf... OK (84.6s)
[46/270] Directors-Share-Purchase-Notice-2-27-Aug-2024.pdf... OK (20.9s)
[47/270] Directors-Share-Purchase-Notice-REVISED-19-22.8.24.pdf... OK (20.9s)
[48/270] DirectorsHoldingasatJanuary252025-Executed-Copy.pdf... OK (85.2s)
[49/270] Dividend-letter-2024.pdf... OK (21.7s)
[50/270] Dividend_000240-1.pdf... OK (21.3s)
  -- checkpoint saved (70 total results so far)
[51/270] EFRESH-Report-to-Shareholders-ended-March-31-2025_000085.pdf... OK (42.9s)
[52/270] EFRESH-Unaudited-Financial-ended-31-March-2025_000084.pdf...     Timeout on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p8.jpg (attempt 1/3, dpi=200)
    Server error (502) on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p8.jpg, attempt 2
    Server error (502) on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p8.jpg, attempt 3
    page 8 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p9.jpg, attempt 1
    Server error (502) on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p9.jpg, attempt 2
    Server error (502) on EFRESH-Unaudited-Financial-ended-31-March-2025_000084_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
OK (751.0s)
[53/270] EFresh-Unaudited-Financial-Statements-1.pdf... OK (300.6s)
[54/270] EVERYTHING-FRESH-LIMITED-Report-to-Shareholders-June-2026.pdf... OK (42.9s)
[55/270] EVERYTHING-FRESH-LIMITED-Unaudited-Reports-June-2026.pdf...     Timeout on EVERYTHING-FRESH-LIMITED-Unaudited-Reports-June-2026_p12.jpg (attempt 1/3, dpi=200)
    Server error (502) on EVERYTHING-FRESH-LIMITED-Unaudited-Reports-June-2026_p12.jpg, attempt 2
    Server error (502) on EVERYTHING-FRESH-LIMITED-Unaudited-Reports-June-2026_p12.jpg, attempt 3
    page 12 failed: failed after 3 attempts (timeouts/errors)
OK (520.4s)
[56/270] EduFocal-2024-AGM-Notice-and-Resolutions.pdf... OK (44.8s)
[57/270] Efresh-Financial-Reports-Sept-2025.pdf... OK (256.2s)
[58/270] Efresh-Report-to-Shareholders-Sept-2025.pdf... OK (42.6s)
[59/270] Everything-Fresh-Limited-Report-to-Shareholders-3rd-Quarter-2024.pdf... OK (43.2s)
[60/270] Everything-Fresh-Limited-Unaudited-Financial-Statements-3rd-Quarter-2024.pdf... OK (255.9s)
  -- checkpoint saved (80 total results so far)
[61/270] FTNA-3rd-Quarter-Unaudited-Financials-2025-26.pdf...     Timeout on FTNA-3rd-Quarter-Unaudited-Financials-2025-26_p13.jpg (attempt 1/3, dpi=200)
    Server error (502) on FTNA-3rd-Quarter-Unaudited-Financials-2025-26_p13.jpg, attempt 2
OK (527.4s)
[62/270] Final-The-LAB-Audited-Financial-Statement-2024-JSE-3-2.pdf... OK (789.6s)
[63/270] Flyer-CEO-Forum-Presenters.pdf... OK (21.6s)
[64/270] Formal-Order-SGJL-July-15-2026.pdf... OK (63.9s)
[65/270] Formal-Order-Schemes-of-Arrangement-1.pdf...     Timeout on Formal-Order-Schemes-of-Arrangement-1_p2.jpg (attempt 1/3, dpi=200)
OK (360.4s)
[66/270] GENAC_Notice-of-AGM.pdf... OK (21.7s)
[67/270] GENAC_Proxy-Form-for-AGM.pdf... OK (21.7s)
[68/270] GHL-Dividend-Shareholder-ad-Q3.pdf... OK (20.9s)
[69/270] GHL-NCB-Merchant.pdf... OK (21.8s)
[70/270] GHL-Notice-Patrick-Solomon.pdf... OK (24.3s)
  -- checkpoint saved (90 total results so far)
[71/270] GHL-Restructuring.pdf... OK (25.8s)
[72/270] GK-CFO-Dividend-Release-Q1-2026.pdf...     Server error (502) on GK-CFO-Dividend-Release-Q1-2026_p1.jpg, attempt 1
    Server error (502) on GK-CFO-Dividend-Release-Q1-2026_p1.jpg, attempt 2
    Server error (502) on GK-CFO-Dividend-Release-Q1-2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (224.6s)
[73/270] GK-CFO-Dividend-Release-Q4-2025.pdf... OK (36.8s)
[74/270] GWEST-CORPORATION-LTD-Unaudited-Financial-Statements-2nd-Quarter-Ended-September-2024.pdf... OK (256.0s)
[75/270] GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025.pdf...     Server error (502) on GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025_p2.jpg, attempt 1
    Timeout on GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025_p5.jpg (attempt 1/3, dpi=200)
    Server error (502) on GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025_p5.jpg, attempt 2
    Server error (502) on GWEST-Corporation-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
OK (515.2s)
[76/270] GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024.pdf...     Server error (502) on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p10.jpg, attempt 1
    Server error (502) on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p10.jpg, attempt 2
    Server error (502) on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p11.jpg, attempt 1
    Server error (502) on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p11.jpg, attempt 2
    Timeout on GWest-Corporation-Limited-Unaudited-FS-3rd-Quarter-Ended-Dec.31-2024_p11.jpg (attempt 3/3, dpi=75)
    page 11 failed: failed after 3 attempts (timeouts/errors)
OK (572.4s)
[77/270] GWest-Corporation-Limited-Unaudited-Financial-Statements-1st-Quarter-Ended-June-30-2026.pdf... OK (278.5s)
[78/270] GWest-Corporation-Ltd-Unaudited-Financial-Statements-3rd-Quarter-Ended-December-31_-2025.pdf... OK (276.4s)
[79/270] General-Accident-Proxy-Form-2024.pdf... OK (43.4s)
[80/270] General_Accident-Notice_Of_AGM.pdf... OK (42.7s)
  -- checkpoint saved (100 total results so far)
[81/270] Gwest-Corp-Unaudited-2nd-quarter-September-2025-Financial-Statement.pdf... OK (232.4s)
[82/270] H1-Stockholders-2025-Report.pdf...     Timeout on H1-Stockholders-2025-Report_p2.jpg (attempt 1/3, dpi=200)
OK (168.2s)
[83/270] HONBUN-1st-Quarter-Report-2025.pdf... OK (360.6s)
[84/270] HONBUN-Financial-Statements-3rd-Quarter-2026.pdf... OK (417.6s)
[85/270] IPJL-Auditors-1.pdf... OK (30.6s)
[86/270] ISP-2nd-Quarter-Filing-Report-Revised.pdf...     Server error (502) on ISP-2nd-Quarter-Filing-Report-Revised_p1.jpg, attempt 1
    Server error (502) on ISP-2nd-Quarter-Filing-Report-Revised_p1.jpg, attempt 2
    Timeout on ISP-2nd-Quarter-Filing-Report-Revised_p6.jpg (attempt 1/3, dpi=200)
OK (376.3s)
[87/270] ISP-3rd-Quarter-J.S.E.-Filing-Report.pdf... OK (278.9s)
[88/270] ISP-4th-Qtr-JSE-Filing-Report.pdf... OK (279.9s)
[89/270] ISP-JSE-4th-Quarter-Filing-Report.pdf... OK (278.0s)
[90/270] ISP-JSE-Filing-Report-2nd-Quarter-Ended-June-30-2025.pdf... OK (254.8s)
  -- checkpoint saved (110 total results so far)
[91/270] ISP-JSE-Filing-Report-3rd-Quarter-ended-September-30-2025.pdf... OK (276.6s)
[92/270] Interim-Financial-Statements-Sept-2024-1.pdf... OK (171.4s)
[93/270] JAMT-Directors-Holding-as-at-March-31-2026.pdf... OK (43.5s)
[94/270] JAMT-Senior-Managers-Holding-as-at-March-312026.pdf... OK (41.7s)
[95/270] JFP-Ltd-Quarterly-Financial-Statement-for-period-ending-June-30-2026.pdf... OK (296.5s)
[96/270] JPS-Unaudited-Financials-December-31-2025.pdf... OK (173.7s)
[97/270] JPS-Unaudited-Quarterly-Financials-March-31-2025-signed.pdf... OK (173.0s)
[98/270] JPS-Unaudited-September-30-2025-2.pdf... OK (172.8s)
[99/270] JPS_Interim_Financial_Statements_Dec_2024final1.pdf... OK (258.6s)
[100/270] JSE-Filing-Report-1st-Quarter-Ended-March-31-2025.pdf... OK (276.1s)
  -- checkpoint saved (120 total results so far)
[101/270] JSE-Filing-Report-1st-Quarter-ended-March-31-2026.pdf...     Server error (502) on JSE-Filing-Report-1st-Quarter-ended-March-31-2026_p6.jpg, attempt 1

    Server error (502) on JSE-Filing-Report-1st-Quarter-ended-March-31-2026_p6.jpg, attempt 2
    Server error (502) on JSE-Filing-Report-1st-Quarter-ended-March-31-2026_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
OK (522.0s)
[102/270] JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026.pdf...     Server error (502) on JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026_p10.jpg, attempt 1
    Server error (502) on JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026_p10.jpg, attempt 2
    Server error (502) on JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on JSE-Filing-Report-2nd-Qtr-Ended-June-30-2026_p11.jpg, attempt 1
OK (574.3s)
[103/270] JSE-Letter-MJE-Annual-Report-31-December-2024-Final.pdf... OK (20.9s)
[104/270] JSE-Sep-2024-Unaudited-report.pdf... OK (214.5s)
[105/270] JSEG-2ND-Quarter-Financial-Statements-June-2025.pdf...     Server error (502) on JSEG-2ND-Quarter-Financial-Statements-June-2025_p9.jpg, attempt 1
OK (351.1s)
[106/270] JSEs-First-Quarter-2026-Unaudited-Financial-Statements.pdf...     Server error (502) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p7.jpg, attempt 1
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p7.jpg, attempt 2
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p8.jpg, attempt 1
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p8.jpg, attempt 2
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p8.jpg, attempt 3
    page 8 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p9.jpg, attempt 1
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p9.jpg, attempt 2
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p10.jpg, attempt 1
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p10.jpg, attempt 2
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p11.jpg, attempt 1
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p11.jpg, attempt 2
    Server error (503) on JSEs-First-Quarter-2026-Unaudited-Financial-Statements_p11.jpg, attempt 3
    page 11 failed: failed after 3 attempts (timeouts/errors)
OK (565.8s)
[107/270] June-2025-Financial-Statement_250809_123927.pdf... OK (170.6s)
[108/270] KPREIT-AGM-Notice-2026.pdf... OK (22.3s)
[109/270] KPREIT-Form-Of-Proxy-2026.pdf... OK (22.5s)
[110/270] KREMI-Qtr-2-Unaudited-Stock-Exch-report-August-31-2025.pdf... OK (256.3s)
  -- checkpoint saved (130 total results so far)
[111/270] Key-Insurance-Company-Ltd.-Advisory-re-the-Appointment-of-Tammara-Glaves-Hucey.pdf... OK (21.2s)
[112/270] Kintyre-Holdings-JA-Limited-Seven-Kingston-Limited-Announce-Joint-Venture-for-Ice-Manufacturing-2.pdf... OK (42.8s)
[113/270] Kintyre-Holdings-Leadership-Changes.pdf... OK (21.3s)
[114/270] Kintyre-Holdings-Rights-Issue-Notice-1.pdf... OK (21.2s)
[115/270] Kremi-Annual-Report-FY2024-25.pdf... OK (1787.0s)
[116/270] LASCO-Distributors-Limited-JSE-Report-September-2024.pdf... OK (255.5s)
[117/270] LASD-Directors-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... OK (21.0s)
[118/270] LASD-Directors-and-Connected-Parties-Shareholdngs.pdf... OK (20.9s)
[119/270] LASD-FIRST-QUARTER-UNAUDITED-FINANCIAL-REPORT-THREE-MONTHS-ENDED-JUNE-30-2025.pdf... OK (276.9s)
[120/270] LASD-FIRST-QUARTER-UNAUDITED-FINANCIAL-STATEMENTS-JUNE-30-2026.pdf... OK (298.1s)
  -- checkpoint saved (140 total results so far)
[121/270] LASD-Second-Quarter-Unaudited-Financial-Report-September-30-2025.pdf... OK (385.6s)
[122/270] LASD-Senior-Manager-and-Connected-Parties-Shareholdings.pdf... OK (21.6s)
[123/270] LASD-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... OK (21.6s)
[124/270] LASD-Shareholders-Report-March-31-2026.pdf... OK (108.5s)
[125/270] LASD-Third-Quarter-Unaudited-Financial-Report-for-the-Nine-months-ended-December-31-2024.pdf... OK (376.4s)
[126/270] LASD-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025.pdf... OK (319.0s)
[127/270] LASD-Top-Ten-Shareholdings-as-at-September-30-2025.pdf... OK (27.9s)
[128/270] LASD-Top-Ten-Shareholdings.pdf... OK (33.8s)
[129/270] LASM-Directors-and-Conected-Parties-Shareholdings-as-at-September-30-2025.pdf... OK (57.2s)
[130/270] LASM-Directors-and-Connected-Parties-Shareholdings-as-at-December-31-2025.pdf...     Server error (503) on LASM-Directors-and-Connected-Parties-Shareholdings-as-at-December-31-2025_p1.jpg, attempt 1
OK (66.0s)
  -- checkpoint saved (150 total results so far)
[131/270] LASM-Directors-and-Connected-Parties-Shareholdings.pdf... OK (62.4s)
[132/270] LASM-FIRST-QUARTER-UNAUDITED-FINANCIAL-STATEMENTS-JUNE-30-2026.pdf... OK (255.6s)
[133/270] LASM-First-Quarter-Unaudited-Financial-Report-Three-Months-Ended-June-30-2025.pdf... OK (244.0s)
[134/270] LASM-Second-Quarter-Un-Audited-Financial-Report-for-the-Six-Months-Ended-September-30-2024.pdf... OK (257.6s)
[135/270] LASM-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-December-31-2025.pdf... OK (21.6s)
[136/270] LASM-Senior-Managers-and-Connected-Parties-Shareholdings-as-at-September-30-2025.pdf... OK (21.2s)
[137/270] LASM-Senior-Managers-and-Connected-Parties-Shareholdings.pdf... OK (21.5s)
[138/270] LASM-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025.pdf...     Server error (503) on LASM-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025_p5.jpg, attempt 1
    Server error (503) on LASM-Third-Quarter-Unaudited-Financial-Statements-as-at-December-31-2025_p5.jpg, attempt 2
OK (364.0s)
[139/270] LASM-Top-Ten-Shareholders-as-at-September-30-2025.pdf... OK (21.3s)
[140/270] LASM-Top-Ten-Shareholders.pdf... OK (20.9s)
  -- checkpoint saved (160 total results so far)
[141/270] LASM-Top-Ten-Shareholdings-as-at-December-31-2025.pdf... OK (21.6s)
[142/270] LASM-Unaudited-Financial-Statements-for-the-Second-Quarter-Ended-September-30-2025.pdf... OK (263.5s)
[143/270] LASM-Unaudited-Financial-Statements-for-the-Third-Quarter-Ended-December-31-2024.pdf... OK (316.6s)
[144/270] LETTER-TO-JSE-RE-SHARES-PURCHASED-JULY-2026.pdf... OK (21.3s)
[145/270] LML-Reports-to-the-Shareholders-for-the-Twelve-Months-Ended-March-31-2025.pdf... OK (64.5s)
[146/270] LML-Shareholdings-as-at-March-31-2025.pdf... OK (62.9s)
[147/270] LTR-TO-JSE-NOTIFICATION-OF-CHANGE-OF-AUDITORupdated.pdf... OK (21.2s)
[148/270] Letter-re-didivend-correction-of-date-.pdf... OK (21.8s)
[149/270] MANAGEMENT-DISCUSSION-AND-ANALYSIS.pdf... OK (42.7s)
[150/270] MASSY-Change-in-Director-Snr-Officers.-Executive-Director-Group-Chief-Financial-Officer.pdf... OK (21.2s)
  -- checkpoint saved (170 total results so far)
[151/270] MASSY-DIVIDEND-DECLARATION-NOTICE.pdf... OK (21.1s)
[152/270] MASSY-Notice-Dividend-Payment-Schedule-Change.pdf... OK (21.9s)
[153/270] MASSY-Notice-Intention-to-Access-Long-Term-Financing.pdf... OK (22.2s)
[154/270] MASSY-Notice-of-Annual-Meeting.pdf... OK (21.2s)
[155/270] MASSY-Notice-of-Annual-Report.pdf... OK (21.2s)
[156/270] MASSY-Notice-of-Audited-Consolidated-Financial-Statements-Sep-30-2025.pdf... OK (21.4s)
[157/270] MASSY-Notice-of-Audited-Financial-Statements.pdf... OK (21.2s)
[158/270] MASSY-Notice-of-Change-in-Board-Composition.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1830650}
FAILED (no text) (21.4s)
[159/270] MASSY-Notice-of-Change-in-Senior-Officers-Appointment-of-EVP-and-Portfolio-CEO-Motors-Machines.pdf... OK (36.7s)
[160/270] MASSY-Notice-of-Change-in-Senior-Officers-Directors-President-Group-Chief-Executive-Officer.pdf... OK (21.5s)
  -- checkpoint saved (180 total results so far)
[161/270] MASSY-Notice-of-Change-in-Senior-Officers-EVP-Portfolio-CEO-Gas-Products-Appointment.pdf... OK (21.4s)
[162/270] MASSY-Notice-of-Change-in-Senior-Officers-EVP-Portfolio-CEO-GasProducts-Resignation.pdf... OK (20.8s)
[163/270] MASSY-Notice-of-Change-in-Senior-Officers-EVP-and-Portfolio-CEO-Motors-Machines.pdf... OK (22.2s)
[164/270] MASSY-Notice-of-Change-in-Senior-Officers-Executive-Vice-President-Deputy-Group-Chief-Executive-Officer.pdf... OK (23.4s)
[165/270] MASSY-Notice-of-Change-in-Senior-Officers-Group-Executive-Vice-President-Executive-Chairperson-Integrated-Retail-Portfolio.pdf... OK (29.0s)
[166/270] MASSY-Notice-of-Change-in-Senior-Officers-SVP-Group-People-Culture.pdf... OK (27.7s)
[167/270] MASSY-Notice-of-Director-Appointment-Chloe-Bermudez.pdf... OK (22.4s)
[168/270] MASSY-Notice-of-Director-Resignation-Soraya-Khan.pdf... OK (21.1s)
[169/270] MASSY-Notice-of-Dividend-Declaration.pdf... OK (21.1s)
[170/270] MASSY-Notice-of-Election-of-Chairman-Designate.pdf... OK (20.8s)
  -- checkpoint saved (190 total results so far)
[171/270] MASSY-Notice-of-Final-Dividend-Declaration.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1649819}
FAILED (no text) (21.4s)
[172/270] MASSY-Notice-of-Final-Dividend-Payment.pdf... OK (21.2s)
[173/270] MASSY-Notice-of-Interim-Dividend-Declaration.pdf... OK (21.2s)
[174/270] MASSY-Notice-of-Partial-Final-Dividend-Payment.pdf... OK (21.5s)
[175/270] MASSY-Notice-of-in-Senior-Officer-Roles-Titles.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1799642}
FAILED (no text) (21.4s)
[176/270] MASSY-Retirement-of-Directors.pdf... OK (21.5s)
[177/270] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-December-31-2024.pdf... OK (214.7s)
[178/270] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-December-31-2025.pdf... OK (244.0s)
[179/270] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-June-30-2025.pdf... OK (229.1s)
[180/270] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-Period-Ended-March-31-2026.pdf... OK (215.2s)
  -- checkpoint saved (200 total results so far)
[181/270] MASSY-Unaudited-Consolidated-Financial-Statements-for-the-period-ended-March-312025.pdf... OK (235.8s)
[182/270] MEEG-Directors-Holding-as-at-April-30-2026.pdf... OK (110.4s)
[183/270] MEEG-Directors-Holding-as-at-January-31-2026.pdf... OK (63.5s)
[184/270] MEEG-LIMITED-STOCKHOLERS-REPORT-OCTOBER-31-2025.pdf... OK (85.6s)
[185/270] MEEG-Senior-Managers-Holding-as-at-April-30-2026.pdf... OK (21.8s)
[186/270] MEEG-Unaudited-Results-Q3-%E2%80%93-Nine-Months-Ended-July-31-2025.pdf... OK (433.7s)
[187/270] MEEG-Unaudited-ResultsQ2-Six-Months-Ended-April-30-2026.pdf...     Server error (503) on MEEG-Unaudited-ResultsQ2-Six-Months-Ended-April-30-2026_p1.jpg, attempt 1
    Server error (503) on MEEG-Unaudited-ResultsQ2-Six-Months-Ended-April-30-2026_p1.jpg, attempt 2
    Server error (503) on MEEG-Unaudited-ResultsQ2-Six-Months-Ended-April-30-2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
OK (368.8s)
[188/270] MPCCEL-Unaudited-Financial-Statements-June-30-2026.pdf...     Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p14.jpg, attempt 1
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p14.jpg, attempt 2
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p14.jpg, attempt 3
    page 14 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p15.jpg, attempt 1
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p15.jpg, attempt 2
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p15.jpg, attempt 3
    page 15 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p16.jpg, attempt 1
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p16.jpg, attempt 2
    Server error (503) on MPCCEL-Unaudited-Financial-Statements-June-30-2026_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
OK (502.3s)
[189/270] NOTICE-2024-ANNUAL-GENERAL-MEETING-1.pdf... OK (21.2s)
[190/270] NOTICE-OF-CHANGE-COMPANY-SECRETARY.pdf... OK (21.2s)
  -- checkpoint saved (210 total results so far)
[191/270] NOTICE-TO-JSE.-DIVIDEND-CONSIDERATION.pdf... OK (20.9s)
[192/270] NOTICE-TO-STOCK-EXCHANGE.pdf... OK (21.5s)
[193/270] NOTIFICATION-OF-CHANGE-OF-AUDITOR.pdf... OK (21.2s)
[194/270] NROCC-Upsize-Notice-Final.pdf... OK (21.7s)
[195/270] Notice-and-Proxy-Form.pdf... OK (43.4s)
[196/270] Notice-of-Annual-General-Meeting.pdf... OK (21.6s)
[197/270] Notice-of-Extension-of-Closing-Date.pdf... OK (21.9s)
[198/270] Notice-of-change-of-time-and-venue-Annual-General-Meeting.pdf... OK (22.5s)
[199/270] Notice-to-Shareholders.pdf... OK (21.3s)
[200/270] PTJL-Second-Quarter-ended-November-30-2024-Unaudited-Results.pdf... OK (233.6s)
  -- checkpoint saved (220 total results so far)
[201/270] PTJL-Second-Quarter-ended-November-30-2025-Unaudited-Results.pdf... OK (233.2s)
[202/270] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statement-for-the-First-Quarter-Q1-ended-August-31-2025.pdf... OK (233.4s)
[203/270] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-and-Reports-for-the-First-Quarter-Q1-ended-August-31-2024-1.pdf... OK (232.2s)
[204/270] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-and-Reports-for-the-Third-Quarter-Q3-ended-February-28-2026.pdf... OK (234.0s)
[205/270] Paramount-Trading-Jamaica-Limited-Unaudited-Financial-Statements-for-the-Third-Quarter-Q3-ended-February-28-2025-and-Shareholdings-of-Top-Ten-10-Shareholders-Directors-and-Senior-Officers.pdf... OK (281.0s)
[206/270] Post-Meeting-Notice-SREXF-Result-of-Board-Meeting-30Mar26-Page-2.pdf... OK (28.0s)
[207/270] Proxy-Form-1.pdf... OK (21.5s)
[208/270] Purchase-of-Shares-by-a-director.pdf... OK (21.4s)
[209/270] REVISED-JPS-Unaudited-Quarterly-Financials-March-31-2026.pdf... OK (171.3s)
[210/270] RJR-Limited-Directors-Report-Unaudited-Statements-as-at-December-2025-1.pdf... OK (362.1s)
  -- checkpoint saved (230 total results so far)
[211/270] RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2.pdf...     Server error (503) on RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2_p7.jpg, attempt 1
    Server error (503) on RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2_p7.jpg, attempt 2
    Server error (503) on RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on RJR-Limited-Unaudited-Financial-Statements-as-at-December-2024-2_p8.jpg, attempt 1
OK (394.8s)
[212/270] RJR-Limited-Unaudited-Financial-Statements-as-at-September-2024.pdf... OK (299.9s)
[213/270] RPL-Notice-of-AGM-2024-updated.pdf... OK (21.7s)
[214/270] RPL-Notice-of-AGM-FY2024.pdf... OK (22.0s)
[215/270] RPL-Proxy-2024-updated.pdf... OK (53.5s)
[216/270] Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025.pdf...     Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p1.jpg, attempt 1
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p1.jpg, attempt 2
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p2.jpg, attempt 1

    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p2.jpg, attempt 2
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p3.jpg, attempt 1
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p3.jpg, attempt 2
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p4.jpg, attempt 1
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p4.jpg, attempt 2
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p5.jpg, attempt 1
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p5.jpg, attempt 2
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p6.jpg, attempt 1
    Server error (503) on Radio-Jamaica-Limited-Unadited-Financial-Statements-as-at-September-2025_p6.jpg, attempt 2
OK (432.7s)
[217/270] Radio-Jamaica-Limited-Unauditted-Financial-Statements-as-at-June-30-2025-1.pdf... OK (321.6s)
[218/270] Redemption-Notice.pdf... OK (21.2s)
[219/270] Report-to-Shareholders-June-2025.pdf... OK (42.6s)
[220/270] Report-to-the-Shareholders-for-the-twelve-months-ended-March-31-2026.pdf... OK (84.4s)
  -- checkpoint saved (240 total results so far)
[221/270] Report-to-the-Shareholders.pdf...     Server error (502) on Report-to-the-Shareholders_p3.jpg, attempt 1
    Server error (503) on Report-to-the-Shareholders_p3.jpg, attempt 2
    Server error (503) on Report-to-the-Shareholders_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Report-to-the-Shareholders_p4.jpg, attempt 1
    Server error (503) on Report-to-the-Shareholders_p4.jpg, attempt 2
    Server error (503) on Report-to-the-Shareholders_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
OK (240.1s)
[222/270] Resignation-C.-Gentles.pdf...     Server error (503) on Resignation-C.-Gentles_p1.jpg, attempt 1
    Server error (503) on Resignation-C.-Gentles_p1.jpg, attempt 2
    Server error (503) on Resignation-C.-Gentles_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[223/270] Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected.pdf...     Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p1.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p1.jpg, attempt 2
    Server error (502) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p37.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p37.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p37.jpg, attempt 3
    page 37 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p38.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p38.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p38.jpg, attempt 3
    page 38 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p39.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p39.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p39.jpg, attempt 3
    page 39 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p40.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p40.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p40.jpg, attempt 3
    page 40 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p41.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p41.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p41.jpg, attempt 3
    page 41 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p42.jpg, attempt 1
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p42.jpg, attempt 2
    Server error (503) on Revised-Audited-Financial-Statements-Omni-Industries-Ltd.-EPS-Corrected_p42.jpg, attempt 3
    page 42 failed: failed after 3 attempts (timeouts/errors)
OK (1192.5s)
[224/270] SALFs-Form-of-Proxy-for-AGM-2026.pdf... OK (42.5s)
[225/270] SALFs-Notice-of-AGM-2026.pdf... OK (43.2s)
[226/270] SHAREHOLDERS-NOTICE-RE-APPOINTMNE-TOF-DIRECTOR--1.pdf... OK (21.7s)
[227/270] SIL-AGM-NOTICE-NOV-2025-AND-PROXY.pdf... OK (43.2s)
[228/270] SIL_MDA_Q2-2026.pdf... OK (150.6s)
[229/270] SML-QUARTERLY-REPORT-AS-AT-JUNE-30-2025.pdf... OK (192.8s)
[230/270] SPEAKERS-INVESTMENT-FORUM-BEACH-FRONT.pdf...     Server error (502) on SPEAKERS-INVESTMENT-FORUM-BEACH-FRONT_p1.jpg, attempt 1
    Server error (502) on SPEAKERS-INVESTMENT-FORUM-BEACH-FRONT_p1.jpg, attempt 2
    Server error (503) on SPEAKERS-INVESTMENT-FORUM-BEACH-FRONT_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (164.7s)
  -- checkpoint saved (250 total results so far)
[231/270] STANLEY-MOTTA-Q3-JSE-REPORT-1-1.pdf...     Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p1.jpg, attempt 1
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p1.jpg, attempt 2
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p2.jpg, attempt 1
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p2.jpg, attempt 2
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p3.jpg, attempt 1
    Server error (503) on STANLEY-MOTTA-Q3-JSE-REPORT-1-1_p3.jpg, attempt 2
OK (239.0s)
[232/270] Salada-Form-of-Proxy-16-01-2025.pdf... OK (44.6s)
[233/270] Salada-Notice-of-AGM-16-01-2025.pdf... OK (43.1s)
[234/270] Salesmanship-Workshop.pdf... OK (21.4s)
[235/270] Senior-Managers-Holding-as-at-April-27-2024-Executed-copy.pdf... OK (42.5s)
[236/270] Senior-Managers-Holding-as-at-January-31-2026.pdf... OK (63.5s)
[237/270] Senior-Mangement-Shareholdings-as-at-November-1-2025.pdf...     Server error (503) on Senior-Mangement-Shareholdings-as-at-November-1-2025_p3.jpg, attempt 1
    Server error (503) on Senior-Mangement-Shareholdings-as-at-November-1-2025_p3.jpg, attempt 2
    Server error (502) on Senior-Mangement-Shareholdings-as-at-November-1-2025_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)

OK (195.5s)
[238/270] SeniorManagersHoldingasatJanuary252025-Executed-Copy.pdf...     Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p1.jpg, attempt 1
    Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p1.jpg, attempt 2
    Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p2.jpg, attempt 1
    Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p2.jpg, attempt 2
    Server error (503) on SeniorManagersHoldingasatJanuary252025-Executed-Copy_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (89.4s)
[239/270] SeniorManagersHoldingasatJuly272024-Executed-copy-1.pdf...     Server error (503) on SeniorManagersHoldingasatJuly272024-Executed-copy-1_p1.jpg, attempt 1
    Server error (503) on SeniorManagersHoldingasatJuly272024-Executed-copy-1_p1.jpg, attempt 2
    Server error (503) on SeniorManagersHoldingasatJuly272024-Executed-copy-1_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
OK (65.9s)
[240/270] Seprod-Limited-Delay-of-Audited-Financial-Statements.pdf... OK (21.3s)
  -- checkpoint saved (260 total results so far)
[241/270] Seprod-Limited-Extension-Notice-for-filing-Annual-Report.pdf... OK (21.2s)
[242/270] Seprod-Limited-Filing-of-2024-Audited-Financial-Statements_0001.pdf... OK (21.2s)
[243/270] Seprod-Limited-Management-Changes.pdf... OK (21.3s)
[244/270] Shareholders-Reports-as-at-September-30-2024-Top-Ten-Shareholders-Directors-Senior-Managers.pdf... OK (42.0s)
[245/270] Shares-purcahsed-by-Direcotr-.pdf... OK (21.6s)
[246/270] Spur-Tree-Spices-Notice-of-AGM-2025.pdf... OK (21.5s)
[247/270] Spur-Tree-Spices-Shareholding-Report-as-at-Dec-31-2025-1.pdf... OK (65.8s)
[248/270] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025.pdf...     Server error (502) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p2.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p2.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p3.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p3.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p4.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p4.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p5.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p5.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p6.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p6.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p7.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-six-months-ended-June-30-2025_p7.jpg, attempt 2
OK (537.9s)
[249/270] Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025.pdf...     Server error (502) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p5.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p5.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p6.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p6.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p7.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p7.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p8.jpg, attempt 1
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p8.jpg, attempt 2
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p8.jpg, attempt 3
    page 8 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Supreme-Ventures-Limited-SVL-Interim-Report-to-Stockholders-for-the-three-months-ended-March-31-2025_p9.jpg, attempt 1
OK (507.8s)
[250/270] Top-10-Shareholders-as-At-January-31-2026.pdf... OK (42.9s)
  -- checkpoint saved (270 total results so far)
[251/270] TopShareholderasatJanuary252025-Executed-Copy.pdf... OK (46.3s)
[252/270] Tropical-Battery-Annual-Report-2025-1.pdf...     Server error (502) on Tropical-Battery-Annual-Report-2025-1_p3.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p3.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p4.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p4.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p5.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p5.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)

    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p6.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p6.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p27.jpg, attempt 1
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p27.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p27.jpg, attempt 3
    page 27 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p28.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p28.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p28.jpg, attempt 3
    page 28 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p29.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p29.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p29.jpg, attempt 3
    page 29 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p30.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p30.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p30.jpg, attempt 3
    page 30 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p46.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p46.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p46.jpg, attempt 3
    page 46 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p47.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p47.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p47.jpg, attempt 3
    page 47 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p48.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p48.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p48.jpg, attempt 3
    page 48 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p49.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p49.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p49.jpg, attempt 3
    page 49 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p50.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p50.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p50.jpg, attempt 3
    page 50 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p51.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p51.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p51.jpg, attempt 3
    page 51 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p68.jpg, attempt 1
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p68.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p68.jpg, attempt 3
    page 68 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p69.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p69.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p69.jpg, attempt 3
    page 69 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p70.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p70.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p70.jpg, attempt 3
    page 70 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p71.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p71.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p71.jpg, attempt 3
    page 71 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p72.jpg, attempt 1
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p90.jpg, attempt 1
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p90.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p90.jpg, attempt 3
    page 90 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p91.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p91.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p91.jpg, attempt 3
    page 91 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p92.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p92.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p92.jpg, attempt 3
    page 92 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p93.jpg, attempt 1
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p109.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p109.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p109.jpg, attempt 3
    page 109 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p110.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p110.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p110.jpg, attempt 3
    page 110 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p111.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p111.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p111.jpg, attempt 3
    page 111 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p112.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p112.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p112.jpg, attempt 3
    page 112 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p113.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p113.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p113.jpg, attempt 3
    page 113 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p114.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p114.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p114.jpg, attempt 3
    page 114 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p131.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p131.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p131.jpg, attempt 3
    page 131 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p132.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p132.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p132.jpg, attempt 3

    page 132 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p133.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p133.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p133.jpg, attempt 3
    page 133 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p134.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p134.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p134.jpg, attempt 3
    page 134 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Annual-Report-2025-1_p153.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p153.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p153.jpg, attempt 3
    page 153 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p154.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p154.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p154.jpg, attempt 3
    page 154 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p155.jpg, attempt 1
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p155.jpg, attempt 2
    Server error (503) on Tropical-Battery-Annual-Report-2025-1_p155.jpg, attempt 3
    page 155 failed: failed after 3 attempts (timeouts/errors)
OK (4926.7s)
[253/270] Tropical-Battery-Interim-Report-Q1-FY-2026.pdf...     Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p1.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p1.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p2.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p2.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Tropical-Battery-Interim-Report-Q1-FY-2026_p19.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p19.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p19.jpg, attempt 3
    page 19 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p20.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p20.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p20.jpg, attempt 3
    page 20 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p21.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p21.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p21.jpg, attempt 3
    page 21 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p22.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p23.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p23.jpg, attempt 3
    page 23 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p24.jpg, attempt 1
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p24.jpg, attempt 2
    Server error (503) on Tropical-Battery-Interim-Report-Q1-FY-2026_p24.jpg, attempt 3
    page 24 failed: failed after 3 attempts (timeouts/errors)
OK (928.5s)
[254/270] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024.pdf...     Server error (502) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p9.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p9.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p10.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p10.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p11.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p11.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p11.jpg, attempt 3
    page 11 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p12.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p12.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2024_p12.jpg, attempt 3
    page 12 failed: failed after 3 attempts (timeouts/errors)
OK (475.0s)
[255/270] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025.pdf...     Server error (502) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p13.jpg, attempt 1
    Server error (502) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p13.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p13.jpg, attempt 3
    page 13 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p14.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p14.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p14.jpg, attempt 3
    page 14 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p15.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p15.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p15.jpg, attempt 3
    page 15 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p16.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p16.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-AUGUST-2025_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
OK (554.0s)
[256/270] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-FEBRUARY-2025.pdf... OK (319.4s)
[257/270] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024.pdf...     Server error (502) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p5.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p5.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p6.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p6.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2024_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
OK (468.4s)

[258/270] UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025.pdf...     Server error (502) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p9.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p9.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p10.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p10.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p11.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p11.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p11.jpg, attempt 3
    page 11 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p12.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p12.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p12.jpg, attempt 3
    page 12 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p13.jpg, attempt 1
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p13.jpg, attempt 2
    Server error (503) on UNAUDITED-STATEMENT-OF-COMPREHENSIVE-INCOME-ENDED-NOVEMBER-2025_p13.jpg, attempt 3
    page 13 failed: failed after 3 attempts (timeouts/errors)
OK (517.3s)
[259/270] UNAUDITED-STATMENT-OF-COMPREHENSIVE-INCOME-ENDED-MAY-2025.pdf... OK (323.1s)
[260/270] Unaudited-Financial-Statements-June-2025.pdf...     Server error (502) on Unaudited-Financial-Statements-June-2025_p4.jpg, attempt 1
    Server error (503) on Unaudited-Financial-Statements-June-2025_p4.jpg, attempt 2
    Server error (503) on Unaudited-Financial-Statements-June-2025_p4.jpg, attempt 3
    page 4 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financial-Statements-June-2025_p5.jpg, attempt 1
    Server error (503) on Unaudited-Financial-Statements-June-2025_p5.jpg, attempt 2
    Server error (503) on Unaudited-Financial-Statements-June-2025_p5.jpg, attempt 3
    page 5 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financial-Statements-June-2025_p6.jpg, attempt 1
    Server error (503) on Unaudited-Financial-Statements-June-2025_p6.jpg, attempt 2
    Server error (503) on Unaudited-Financial-Statements-June-2025_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financial-Statements-June-2025_p7.jpg, attempt 1
    Server error (503) on Unaudited-Financial-Statements-June-2025_p7.jpg, attempt 2
    Server error (503) on Unaudited-Financial-Statements-June-2025_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
OK (417.2s)
  -- checkpoint saved (280 total results so far)
[261/270] Unaudited-Financials-Q4-2025-signed.pdf... OK (258.8s)
[262/270] Unaudited-Financials-ended-June-30-2026.pdf...     Server error (502) on Unaudited-Financials-ended-June-30-2026_p12.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p12.jpg, attempt 2
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p12.jpg, attempt 3
    page 12 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p13.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p13.jpg, attempt 2
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p13.jpg, attempt 3
    page 13 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p14.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p14.jpg, attempt 2
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p14.jpg, attempt 3
    page 14 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p15.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p15.jpg, attempt 2
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p15.jpg, attempt 3
    page 15 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p16.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p16.jpg, attempt 2
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p17.jpg, attempt 1
    Server error (503) on Unaudited-Financials-ended-June-30-2026_p17.jpg, attempt 2
OK (556.4s)
[263/270] VMIL-Consideration-of-Dividend-Payment.pdf... OK (20.9s)
[264/270] VMIL-Press-Release-Delay-in-Submission-of-VMIL-2024-Annual-Report.pdf... OK (20.9s)
[265/270] VMIL-Trading-Activity-May-2025.pdf... OK (20.9s)
[266/270] West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024.pdf...     Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p16.jpg, attempt 1
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p16.jpg, attempt 2
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p17.jpg, attempt 1
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p17.jpg, attempt 2
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p17.jpg, attempt 3
    page 17 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p18.jpg, attempt 1
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p18.jpg, attempt 2
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p18.jpg, attempt 3
    page 18 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p19.jpg, attempt 1
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p19.jpg, attempt 2
    Server error (503) on West-Indies-Petroleum-Terminal-Limited-Financial-Statements-31-December-2024_p19.jpg, attempt 3
    page 19 failed: failed after 3 attempts (timeouts/errors)
OK (1070.3s)
[267/270] letter-re-payment-of-Dividend-November-2025.pdf... OK (21.5s)
[268/270] letter-to-JSE-re-Dividend-payment-Document_2025-08-18_160231.pdf... OK (21.0s)
[269/270] re-divided-letter-with-correction-of-date.pdf... OK (22.1s)
[270/270] sale-of-shares-to-a-dreictor-.pdf... OK (21.3s)
  -- checkpoint saved (290 total results so far)

=== BSE: 25 remaining this run (capped at 2000) ===
[1/25] BCO_2025_Q1.pdf... OK (64.5s)
[2/25] BCO_2025_Q2.pdf... OK (114.2s)
[3/25] BCO_2025_Q3.pdf...     Server error (502) on BCO_2025_Q3_p1.jpg, attempt 1
    Server error (503) on BCO_2025_Q3_p1.jpg, attempt 2
    Server error (503) on BCO_2025_Q3_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BCO_2025_Q3_p2.jpg, attempt 1

    Server error (503) on BCO_2025_Q3_p2.jpg, attempt 2
    Server error (503) on BCO_2025_Q3_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BCO_2025_Q3_p3.jpg, attempt 1
    Server error (503) on BCO_2025_Q3_p3.jpg, attempt 2
    Server error (503) on BCO_2025_Q3_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BCO_2025_Q3_p4.jpg, attempt 1
OK (223.3s)
[4/25] BCO_2025_Q4.pdf... OK (85.4s)
[5/25] BCO_2026_Q1.pdf... OK (63.5s)
[6/25] BCO_2026_Q2.pdf... OK (64.4s)
[7/25] BCO_2026_Q3.pdf... OK (64.4s)
[8/25] BDI_2025_Q2.pdf... OK (22.2s)
[9/25] BDI_2025_Q4.pdf... OK (22.3s)
[10/25] BDI_2026_Q1.pdf... OK (21.7s)
  -- checkpoint saved (300 total results so far)
[11/25] BFL_2025_Annual.pdf...     Server error (503) on BFL_2025_Annual_p6.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p6.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p7.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p7.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p8.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p8.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p8.jpg, attempt 3
    page 8 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p9.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p9.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p10.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p10.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p10.jpg, attempt 3
    page 10 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on BFL_2025_Annual_p31.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p31.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p31.jpg, attempt 3
    page 31 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p32.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p32.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p32.jpg, attempt 3
    page 32 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p33.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p33.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p33.jpg, attempt 3
    page 33 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p34.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p34.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p34.jpg, attempt 3
    page 34 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p35.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p35.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p35.jpg, attempt 3
    page 35 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p52.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p52.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p52.jpg, attempt 3
    page 52 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p53.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p53.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p53.jpg, attempt 3
    page 53 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on BFL_2025_Annual_p54.jpg, attempt 1
    Server error (503) on BFL_2025_Annual_p54.jpg, attempt 2
    Server error (503) on BFL_2025_Annual_p54.jpg, attempt 3
    page 54 failed: failed after 3 attempts (timeouts/errors)
    Timeout on BFL_2025_Annual_p55.jpg (attempt 1/3, dpi=200)
OK (1927.7s)
[12/25] BHL_2025_Q2.pdf... OK (23.5s)
[13/25] BHL_2025_Q4.pdf... OK (23.0s)
[14/25] BHL_2026_Q1.pdf... OK (22.7s)
[15/25] CIBC_2024_Q3.pdf... OK (72.5s)
[16/25] CIBC_2025_Audited.pdf...     Server error (502) on CIBC_2025_Audited_p2.jpg, attempt 1
    Server error (503) on CIBC_2025_Audited_p2.jpg, attempt 2
    Server error (503) on CIBC_2025_Audited_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
OK (128.8s)
[17/25] CIBC_2025_Q1.pdf...     Server error (503) on CIBC_2025_Q1_p1.jpg, attempt 1
    Server error (503) on CIBC_2025_Q1_p1.jpg, attempt 2
    Server error (503) on CIBC_2025_Q1_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on CIBC_2025_Q1_p2.jpg, attempt 1
    Server error (503) on CIBC_2025_Q1_p2.jpg, attempt 2
    Server error (503) on CIBC_2025_Q1_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on CIBC_2025_Q1_p3.jpg, attempt 1
    Server error (503) on CIBC_2025_Q1_p3.jpg, attempt 2
    Server error (503) on CIBC_2025_Q1_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (135.0s)
[18/25] CIBC_2025_Q2.pdf...     Server error (503) on CIBC_2025_Q2_p1.jpg, attempt 1
    Server error (503) on CIBC_2025_Q2_p1.jpg, attempt 2
    Server error (503) on CIBC_2025_Q2_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on CIBC_2025_Q2_p2.jpg, attempt 1
OK (98.7s)
[19/25] CIBC_2025_Q3.pdf... OK (70.0s)
[20/25] CIBC_2026_Q1.pdf... OK (69.3s)
  -- checkpoint saved (310 total results so far)
[21/25] CIBC_2026_Q2.pdf... OK (71.8s)
[22/25] OCM_2024_Q3.pdf... OK (22.6s)
[23/25] WIB_2024_Q4.pdf... OK (24.7s)
[24/25] WIB_2025_Q4.pdf...     Server error (502) on WIB_2025_Q4_p2.jpg, attempt 1
    Server error (503) on WIB_2025_Q4_p2.jpg, attempt 2
    Server error (503) on WIB_2025_Q4_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
OK (137.7s)
[25/25] WIB_2026_Q2.pdf...     Server error (503) on WIB_2026_Q2_p1.jpg, attempt 1
    Server error (503) on WIB_2026_Q2_p1.jpg, attempt 2
    Server error (503) on WIB_2026_Q2_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.1s)

=== TTSE: 431 remaining this run (capped at 2000) ===
[1/431] AHL - Publication of appointment of EM-HR and EM-Local Sales dd 06.02.23.pdf...     Server error (503) on AHL - Publication of appointment of EM-HR and EM-Local Sales dd 06.02.23_p1.jpg, attempt 1
    Server error (503) on AHL - Publication of appointment of EM-HR and EM-Local Sales dd 06.02.23_p1.jpg, attempt 2
    Server error (503) on AHL - Publication of appointment of EM-HR and EM-Local Sales dd 06.02.23_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.8s)
[2/431] AHL - Resignation of Executive Manager - Marketing (Cover letter) dd 29.02.2024.pdf...     Server error (503) on AHL - Resignation of Executive Manager - Marketing (Cover letter) dd 29.02.2024_p1.jpg, attempt 1
    Server error (503) on AHL - Resignation of Executive Manager - Marketing (Cover letter) dd 29.02.2024_p1.jpg, attempt 2
    Server error (503) on AHL - Resignation of Executive Manager - Marketing (Cover letter) dd 29.02.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[3/431] ANSA McAL Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 04.11.2025.pdf...     Server error (503) on ANSA McAL Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 04.11.2025_p1.jpg, attempt 1
    Server error (503) on ANSA McAL Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 04.11.2025_p1.jpg, attempt 2
    Server error (503) on ANSA McAL Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 04.11.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[4/431] ANSA McAL Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.11.2025.pdf... OK (21.5s)
[5/431] ANSA McAL Limited - Notice of Appointment of Senior Officer Newspaper Clippings dd 07.11.2025.pdf... OK (47.5s)
[6/431] ANSA McAL Limited - Notice of Change in Directors (Cover Letter) dd 21.10.2025.pdf... OK (21.2s)
[7/431] ANSA McAL Limited - Notice of Change in Senior Officer (Cover Letter) dd 03.10.2024.pdf... OK (21.2s)
[8/431] ANSA McAL Limited - Notice of Change in Senior Officers Newspaper Clippings dd 08.08.2025.pdf... OK (46.6s)
[9/431] ANSA McAL Limited - Notice of Change of Senior Officers Newspaper Clippings dd 02.07.2025.pdf... OK (48.2s)
[10/431] ANSA McAL Limited - Notice of Resignation of Director Newspaper Clippings dd 14.08.2025.pdf... OK (47.5s)
  -- checkpoint saved (325 total results so far)
[11/431] ANSA McAL Limited - Notice of Resignation of Director Newspaper Clippings.pdf... OK (48.0s)
[12/431] ANSA Merchant Bank Limited - Notice of 2023 final dividend payment  (Cover letter) dd 22.03.2024.pdf... OK (23.4s)
[13/431] ANSA Merchant Bank Limited - Notice of 2024 Interim dividend payment  (Cover letter) dd 09.08.2024.pdf... OK (76.2s)
[14/431] ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 17.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[15/431] ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 25.04.2025.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 25.04.2025_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 25.04.2025_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Annual General Meeting (Press Release) dd 25.04.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[16/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.09.2025.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.09.2025_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.09.2025_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.09.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[17/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.03.2024.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.03.2024_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.03.2024_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.03.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[18/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 04.10.2024.pdf... OK (20.8s)
[19/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 08.09.2025.pdf... OK (20.8s)
[20/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.09.2025.pdf... OK (21.1s)
  -- checkpoint saved (335 total results so far)
[21/431] ANSA Merchant Bank Limited - Notice of Appointment of Senior Officer dd 07.05.2024.pdf... OK (21.1s)
[22/431] ANSA Merchant Bank Limited - Notice of Change of Managing Director (Press Release) dd 02.07.2025.pdf... OK (21.1s)
[23/431] ANSA Merchant Bank Limited - Notice of Changes in Senior Officer  (Press Release) dd 08.06.2026.pdf... OK (20.8s)
[24/431] ANSA Merchant Bank Limited - Notice of Changes to the Baord of Directors dd 07.05.2024.pdf... OK (21.1s)
[25/431] ANSA Merchant Bank Limited - Notice of Final Dividend Payment (Cover Letter) dd 18.03.2026.pdf... OK (21.2s)
[26/431] ANSA Merchant Bank Limited - Notice of Final Dividend Payment (Press Release) dd 19.03.2026.pdf... OK (21.2s)
[27/431] ANSA Merchant Bank Limited - Notice of Final Dividend Payment 2024 (Cover Letter) dd 20.03.2025.pdf... OK (21.6s)
[28/431] ANSA Merchant Bank Limited - Notice of Final Dividend Payment 2024 (Press Release) dd 20.03.2025.pdf... OK (20.9s)
[29/431] ANSA Merchant Bank Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 06.08.2025.pdf... OK (21.3s)
[30/431] ANSA Merchant Bank Limited - Notice of Interim Dividend Payment 2025 (Press Release) dd 07.08.2025.pdf... OK (21.2s)
  -- checkpoint saved (345 total results so far)
[31/431] ANSA Merchant Bank Limited - Notice of Interim dividend payment  (Press release) dd 13.08.2024.pdf... OK (21.2s)
[32/431] ANSA Merchant Bank Limited - Notice of Publication of 2024 Annual Report (Cover letter) dd 29.04.2025.pdf... OK (21.2s)
[33/431] ANSA Merchant Bank Limited - Notice of Publication of Annual Report (Cover Letter) dd 30.04.2024.pdf... OK (22.2s)
[34/431] ANSA Merchant Bank Limited - Notice of Publication of Annual Report 2023 dd 30.04.2024.pdf...     Server error (502) on ANSA Merchant Bank Limited - Notice of Publication of Annual Report 2023 dd 30.04.2024_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Publication of Annual Report 2023 dd 30.04.2024_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Publication of Annual Report 2023 dd 30.04.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.8s)
[35/431] ANSA Merchant Bank Limited - Notice of Resignation of Director (Press Release) dd 30.06.2025.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Director (Press Release) dd 30.06.2025_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Director (Press Release) dd 30.06.2025_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Director (Press Release) dd 30.06.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[36/431] ANSA Merchant Bank Limited - Notice of Resignation of Senior Officer (Press Release) dd 08.07.2025.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Senior Officer (Press Release) dd 08.07.2025_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Senior Officer (Press Release) dd 08.07.2025_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice of Resignation of Senior Officer (Press Release) dd 08.07.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[37/431] ANSA Merchant Bank Limited - Notice to Shareholders dd 02.04.2024.pdf...     Server error (503) on ANSA Merchant Bank Limited - Notice to Shareholders dd 02.04.2024_p1.jpg, attempt 1
    Server error (503) on ANSA Merchant Bank Limited - Notice to Shareholders dd 02.04.2024_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited - Notice to Shareholders dd 02.04.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[38/431] ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Press Release) dd30.09.2024.pdf...     Server error (503) on ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Press Release) dd30.09.2024_p1.jpg, attempt 1

    Server error (503) on ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Press Release) dd30.09.2024_p1.jpg, attempt 2
    Server error (503) on ANSA Merchant Bank Limited -Notice of Change in Senior Officer (Press Release) dd30.09.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[39/431] Agostini Limited -  Shares held by Directors and Senior Officers as at April 30, 2025 dd 01.05.2025.pdf... OK (42.8s)
[40/431] Agostini Limited -  Shares held by Directors and Senior Officers as at August 31, 2025 dd 10.09.2025.pdf... OK (43.4s)
  -- checkpoint saved (355 total results so far)
[41/431] Agostini Limited -  Shares held by Directors and Senior Officers as at July 31, 2025 dd 04.08.2025.pdf... OK (43.7s)
[42/431] Agostini Limited -  Shares held by Directors and Senior Officers as at June 30, 2025 dd 01.07.2025.pdf... OK (43.4s)
[43/431] Agostini Limited -  Shares held by Directors and Senior Officers as at March 31, 2025 dd 07.04.2025.pdf... OK (42.5s)
[44/431] Agostini Limited -  Shares held by Directors and Senior Officers as at May 31, 2025 dd 02.06.2025.pdf... OK (43.3s)
[45/431] Agostini Limited -  Shares held by Directors and Senior Officers as at October 31 2025 dd 04.11.2025.pdf... OK (44.1s)
[46/431] Agostini Limited - Annual Report 2025 (Cover Letter) dd 12.01.2026.pdf... OK (21.6s)
[47/431] Agostini Limited - Errata Sheet of Offer and Take Over Bid Circular (Cover Letter) dd 04.07.2025.pdf... OK (22.0s)
[48/431] Agostini Limited - Notice of Acquisition by Subsidiary (Cover Letter) dd 03.03.2026.pdf... OK (76.3s)
[49/431] Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026 (1).pdf...     Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026 (1)_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026 (1)_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026 (1)_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[50/431] Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026.pdf...     Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Acquisition by Subsidiary (Press Release) dd 04.03.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
  -- checkpoint saved (365 total results so far)
[51/431] Agostini Limited - Notice of Annual General Meeting (Press Release) dd 03.02.2026.pdf...     Server error (503) on Agostini Limited - Notice of Annual General Meeting (Press Release) dd 03.02.2026_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Annual General Meeting (Press Release) dd 03.02.2026_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Annual General Meeting (Press Release) dd 03.02.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[52/431] Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 30.09.2025.pdf...     Server error (503) on Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 30.09.2025_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 30.09.2025_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Appointment of Director (Cover Letter) dd 30.09.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[53/431] Agostini Limited - Notice of Appointment of Director (Press Release) dd 22.05.2026.pdf...     Server error (503) on Agostini Limited - Notice of Appointment of Director (Press Release) dd 22.05.2026_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Appointment of Director (Press Release) dd 22.05.2026_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Appointment of Director (Press Release) dd 22.05.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[54/431] Agostini Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.03.2026.pdf... OK (21.6s)
[55/431] Agostini Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 30.06.2025.pdf... OK (21.2s)
[56/431] Agostini Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.03.2026.pdf... OK (22.4s)
[57/431] Agostini Limited - Notice of Change in Director (Press Release) dd 22.05.2026 (1).pdf... OK (21.4s)
[58/431] Agostini Limited - Notice of Change in Director (Press Release) dd 22.05.2026.pdf... OK (20.8s)
[59/431] Agostini Limited - Notice of Issuance of New AGL Shares (Cover Letter) dd 10.07.2025.pdf... OK (21.3s)
[60/431] Agostini Limited - Notice of Resignation of Senior Officer (CL) dd 24.11.2025.pdf... OK (42.5s)
  -- checkpoint saved (375 total results so far)
[61/431] Agostini Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 05.12.2025.pdf... OK (21.2s)
[62/431] Agostini Limited - Notice of Resignation of Senior Officer (Cover letter) dd 16.04.2026.pdf... OK (26.4s)
[63/431] Agostini Limited - Notice of Resignation of Senior Officer (PR) dd 24.11.2025.pdf... OK (21.4s)
[64/431] Agostini Limited - Notice of Resignation of Senior Officer (Press Release) dd 16.04.2026.pdf... OK (20.8s)
[65/431] Agostini Limited - Notice of Resignation of Senior Officer (Press Release) dd 29.12.2025.pdf... OK (21.2s)
[66/431] Agostini Limited - Notice of Retirement of Director (Cover Letter) dd 06.02.2026.pdf... OK (22.2s)
[67/431] Agostini Limited - Notice of Retirement of Director (Press Release) dd 06.02.2026.pdf... OK (26.2s)
[68/431] Agostini Limited - Notice of Trading in Shares (CL) dd 01.06.2026.pdf...     Server error (502) on Agostini Limited - Notice of Trading in Shares (CL) dd 01.06.2026_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Trading in Shares (CL) dd 01.06.2026_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Trading in Shares (CL) dd 01.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.7s)
[69/431] Agostini Limited - Notice of Trading in Shares (Cover Letter) dd 24.06.2025.pdf...     Server error (503) on Agostini Limited - Notice of Trading in Shares (Cover Letter) dd 24.06.2025_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Notice of Trading in Shares (Cover Letter) dd 24.06.2025_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Notice of Trading in Shares (Cover Letter) dd 24.06.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[70/431] Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025.pdf...     Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p2.jpg, attempt 1
    Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p2.jpg, attempt 2
    Server error (503) on Agostini Limited - Offer and Takeover Bid (Cover letter) dd 17.06.2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (89.2s)
  -- checkpoint saved (385 total results so far)
[71/431] Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026.pdf...     Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p1.jpg, attempt 1
    Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p1.jpg, attempt 2
    Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p2.jpg, attempt 1
    Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p2.jpg, attempt 2
    Server error (503) on Agostini Limited - Shares held by Directors and Senior Officers as at April 30, 2026 dd 04.05.2026_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (89.2s)
[72/431] Agostini Limited - Shares held by Directors and Senior Officers as at February 28, 2026 dd 02.03.2026.pdf... OK (43.1s)
[73/431] Agostini Limited - Shares held by Directors and Senior Officers as at January 31, 2026 dd 02.02.2026.pdf... OK (42.8s)
[74/431] Agostini Limited - Shares held by Directors and Senior Officers as at June 30th, 2026  dd 02.07.2026.pdf... OK (42.2s)
[75/431] Agostini Limited - Shares held by Directors and Senior Officers as at March 31, 2026 dd 01.04.2026.pdf... OK (42.8s)
[76/431] Agostini Limited - Shares held by Directors and Senior Officers as at May 31, 2026 dd 01.06.2026.pdf... OK (43.5s)
[77/431] Agostini Limited - Submission of 2025 Annual Report (Cover Letter) dd 23.01.2026.pdf... OK (21.0s)
[78/431] Agostini's Limited -  Shares held by Directors anf Senior Officers as at April 2024 dd 03-05-2024.pdf... OK (43.0s)
[79/431] Agostini's Limited -  Shares held by Directors anf Senior Officers as at June 2024 dd 02.07.2024.pdf... OK (42.1s)
[80/431] Agostini's Limited -  Shares held by Directors anf Senior Officers as at May 2024 dd 03.04.2024.pdf... OK (42.4s)
  -- checkpoint saved (395 total results so far)
[81/431] Agostini's Limited - Documents requested for Name Change dd 18.02.2025.pdf... OK (21.6s)
[82/431] Agostini's Limited - Notice of Acquisition of  a Company (Cover Letter) dd 04.02.2025.pdf... OK (21.3s)
[83/431] Agostini's Limited - Notice of Acquisition of  a Company (Press Release) dd 04.02.2025.pdf... OK (21.2s)
[84/431] Agostini's Limited - Notice of Annual General Meeting (Cover Letter) dd 05.02.2025.pdf... OK (21.3s)
[85/431] Agostini's Limited - Notice of Annual General Meeting dd 05.02.2025.pdf... OK (20.8s)
[86/431] Agostini's Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 12.03.2024.pdf... OK (21.6s)
[87/431] Agostini's Limited - Notice of Appointment of a Director (Cover Letter) dd 06.01.2025.pdf... OK (21.3s)
[88/431] Agostini's Limited - Notice of Appointment of a Director (Press Release) dd 06.01.2025.pdf...     Server error (502) on Agostini's Limited - Notice of Appointment of a Director (Press Release) dd 06.01.2025_p1.jpg, attempt 1
    Server error (503) on Agostini's Limited - Notice of Appointment of a Director (Press Release) dd 06.01.2025_p1.jpg, attempt 2
    Server error (503) on Agostini's Limited - Notice of Appointment of a Director (Press Release) dd 06.01.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.5s)
[89/431] Agostini's Limited - Notice of Availability of 2024 Annual Report (Press Release) dd 21.01.2025.pdf...     Server error (503) on Agostini's Limited - Notice of Availability of 2024 Annual Report (Press Release) dd 21.01.2025_p1.jpg, attempt 1
    Server error (503) on Agostini's Limited - Notice of Availability of 2024 Annual Report (Press Release) dd 21.01.2025_p1.jpg, attempt 2
    Server error (503) on Agostini's Limited - Notice of Availability of 2024 Annual Report (Press Release) dd 21.01.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[90/431] Agostini's Limited - Notice of Change in Company's Name (Cover Letter) dd 17.02.2025.pdf...     Server error (503) on Agostini's Limited - Notice of Change in Company's Name (Cover Letter) dd 17.02.2025_p1.jpg, attempt 1
    Server error (503) on Agostini's Limited - Notice of Change in Company's Name (Cover Letter) dd 17.02.2025_p1.jpg, attempt 2
    Server error (503) on Agostini's Limited - Notice of Change in Company's Name (Cover Letter) dd 17.02.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
  -- checkpoint saved (405 total results so far)
[91/431] Agostini's Limited - Notice of Change in Company's Name dd 17.02.2025.pdf...     Server error (503) on Agostini's Limited - Notice of Change in Company's Name dd 17.02.2025_p1.jpg, attempt 1
    Server error (503) on Agostini's Limited - Notice of Change in Company's Name dd 17.02.2025_p1.jpg, attempt 2
    Server error (503) on Agostini's Limited - Notice of Change in Company's Name dd 17.02.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[92/431] Agostini's Limited - Notice of Dividend payment (Cover Letter) dd 09.05.2024.pdf...     Server error (503) on Agostini's Limited - Notice of Dividend payment (Cover Letter) dd 09.05.2024_p1.jpg, attempt 1
    Server error (503) on Agostini's Limited - Notice of Dividend payment (Cover Letter) dd 09.05.2024_p1.jpg, attempt 2
    Server error (503) on Agostini's Limited - Notice of Dividend payment (Cover Letter) dd 09.05.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[93/431] Agostini's Limited - Unaudited Financials for the period ended December 31st, 2024 dd 14.02.2025.pdf... OK (64.0s)
[94/431] Angostura Holding Limited - Notcie of Appointment of a Director (Cover Letter) dd 25.09.2024.pdf... OK (21.1s)
[95/431] Angostura Holding Limited - Notice of Availability of 2024 Annual report (Cover letter) dd 28.04.2025.pdf... OK (21.4s)
[96/431] Angostura Holding Limited - Notice of Availability of 2025 Annual Report (Cover Letter) dd 31.03.2026.pdf... OK (37.7s)
[97/431] Angostura Holding Limited - Notice of Final Dividend Payment (Cover Letter) dd 13.03.2026.pdf... OK (22.7s)
[98/431] Angostura Holding Limited - Notice of Final Dividend Payment (Cover Letter) dd 27.03.2025.pdf... OK (24.1s)
[99/431] Angostura Holding Limited - Notice of Final Dividend Payment dd 13.03.2026.pdf... OK (20.9s)
[100/431] Angostura Holding Limited - Noticeo of  Dividend Payment (Cover Letter) dd 28.03.2024.pdf... OK (21.4s)
  -- checkpoint saved (415 total results so far)
[101/431] Angostura Holdings Limited - Annual Report 2024 Newspaper Clippings (Cover Letter) dd 29.04.2025.pdf... OK (21.4s)
[102/431] Angostura Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd13.06.2024.pdf... OK (21.7s)
[103/431] Angostura Holdings Limited - Notice of Appointment of Acting CEO (Cover Letter) dd 01.10.2025.pdf... OK (69.6s)
[104/431] Angostura Holdings Limited - Notice of Appointment of Director (Cover Letter) dd 21.05.2024.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Appointment of Director (Cover Letter) dd 21.05.2024_p1.jpg, attempt 1
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Director (Cover Letter) dd 21.05.2024_p1.jpg, attempt 2
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Director (Cover Letter) dd 21.05.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.8s)
[105/431] Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 07.08.2025.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 07.08.2025_p1.jpg, attempt 1
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 07.08.2025_p1.jpg, attempt 2

    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 07.08.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.2s)
[106/431] Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 26.06.2026.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 26.06.2026_p1.jpg, attempt 1
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 26.06.2026_p1.jpg, attempt 2
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Directors (Cover Letter) dd 26.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.0s)
[107/431] Angostura Holdings Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 01.04.2026.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 01.04.2026_p1.jpg, attempt 1
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 01.04.2026_p1.jpg, attempt 2
    Server error (503) on Angostura Holdings Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 01.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.8s)
[108/431] Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 12.08.2025.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 12.08.2025_p1.jpg, attempt 1
    Server error (503) on Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 12.08.2025_p1.jpg, attempt 2
    Server error (503) on Angostura Holdings Limited - Notice of Interim Dividend Payment 2025 (Cover Letter) dd 12.08.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.9s)
[109/431] Angostura Holdings Limited - Notice of Posting of Nominees Biographies (Cover Letter) dd 29.07.2025.pdf...     Server error (503) on Angostura Holdings Limited - Notice of Posting of Nominees Biographies (Cover Letter) dd 29.07.2025_p1.jpg, attempt 1
OK (29.7s)
[110/431] Angostura Holdings Limited - Notice of Resignation of Directors (Cover Letter) dd 04.06.2025.pdf... OK (42.7s)
  -- checkpoint saved (425 total results so far)
[111/431] Angostura Holdings Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 17.03.2026.pdf... OK (22.0s)
[112/431] Angostura Holdings Limited - Notice of Resignation of a Senior Officer (Cover Letter) dd 26.06.2024.pdf... OK (21.4s)
[113/431] Angostura Holdings Limited - Notice of Special Meeting (Cover Letter) dd 24.07.2025.pdf... OK (21.9s)
[114/431] Angostura Holdings Limited - Notice of interim dividend payment (Cover letter) dd 12.08.2024.pdf... OK (21.4s)
[115/431] Angostura Holdings Limited - Ntice of Posting of Annual Meeting Douments (Cover Letter) dd 07.08.2025.pdf... OK (21.9s)
[116/431] Ansa McAL Limited - Notice of Change in Director (Cover Letter) dd 02.06.2025.pdf... OK (21.3s)
[117/431] Ansa McAL Limited - Notice of Change in Director Newspaper Clippings (Cover Letter) dd 04.06.2025.pdf... OK (66.1s)
[118/431] CIBC Caribbean Bank Limited - Notice of Appointment of Director (Cover Letter) dd 03.09.2025.pdf... OK (21.2s)
[119/431] CIBC Caribbean Bank Limited - Notice of Appointment of Senior Officer (Press Release) dd 23.02.2026.pdf... OK (21.2s)
[120/431] CIBC Caribbean Bank Limited - Notice of Appointment of a Senior Officer (Cover Letter) dd 17.12.2024.pdf... OK (21.2s)
  -- checkpoint saved (435 total results so far)
[121/431] CIBC Caribbean Bank Limited - Notice of Availiablity of 2025 Annual Report (CL) dd 16.12.2025.pdf... OK (21.5s)
[122/431] CIBC Caribbean Bank Limited - Notice of Changes in Senior Officers (Cover Letter) dd 28.01.2025.pdf... OK (43.0s)
[123/431] CIBC Caribbean Bank Limited - Notice of Changes in Senior Officers(Amended) dd 07.02.2025.pdf... OK (21.9s)
[124/431] CIBC Caribbean Bank Limited - Notice of Dividend Payemnt dd 16.12.2024.pdf...     Server error (502) on CIBC Caribbean Bank Limited - Notice of Dividend Payemnt dd 16.12.2024_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payemnt dd 16.12.2024_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payemnt dd 16.12.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.5s)
[125/431] CIBC Caribbean Bank Limited - Notice of Dividend Payment (Directors' Resolution) dd 13.03.2026.pdf...     Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment (Directors' Resolution) dd 13.03.2026_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment (Directors' Resolution) dd 13.03.2026_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment (Directors' Resolution) dd 13.03.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[126/431] CIBC Caribbean Bank Limited - Notice of Dividend Payment dd 12.12.25.pdf...     Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment dd 12.12.25_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment dd 12.12.25_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend Payment dd 12.12.25_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[127/431] CIBC Caribbean Bank Limited - Notice of Dividend dd 04.06.2026.pdf...     Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.06.2026_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.06.2026_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[128/431] CIBC Caribbean Bank Limited - Notice of Dividend dd 04.09.2025.pdf...     Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.09.2025_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.09.2025_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 04.09.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[129/431] CIBC Caribbean Bank Limited - Notice of Dividend dd 12.06.2025.pdf...     Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 12.06.2025_p1.jpg, attempt 1
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 12.06.2025_p1.jpg, attempt 2
    Server error (503) on CIBC Caribbean Bank Limited - Notice of Dividend dd 12.06.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[130/431] CIBC Caribbean Bank Limited - Notice of Dividend dd 13.03.2025.pdf... OK (20.9s)
  -- checkpoint saved (445 total results so far)
[131/431] CIBC Caribbean Bank Limited - Notice of Record Date for Annual Meeting (CL) dd 16.12.2025.pdf... OK (21.8s)
[132/431] CIBC Caribbean Bank Limited - Notice of Record Date for Annual Meeting (PR) dd 15.01.2026.pdf... OK (21.4s)
[133/431] CIBC Caribbean Bank Limited - Notice of Retirement of Director (Press Release) dd 26.01.2026.pdf... OK (21.4s)
[134/431] CIBC Caribbean Bank Limited - Submission of Annual Report 2025 (Cover Letter) dd 27.01.2026.pdf... OK (21.3s)
[135/431] Calypso Macro Index Fund - Notice of Annual Meeting (Press Release) dd 24.04.2024.pdf... OK (21.5s)
[136/431] Calypso Macro Index Fund - Notice of Dividend Payment (Press release) dd 22.08.2024.pdf.pdf... OK (20.9s)
[137/431] Calypso Macro Index Fund - Notice of Second Dividend Payment (Press Release) dd 28.05.2025.pdf... OK (21.2s)
[138/431] CinemaOne Limited - Notice of Shareholders  dd 04.07.2024.pdf... OK (21.2s)
[139/431] ECPF Top Ten Shareholdings & Connected Parties-Value & Development Fund (Dec-31-2023).pdf... OK (25.9s)
[140/431] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd 22.08.2025.pdf... OK (21.3s)
  -- checkpoint saved (455 total results so far)
[141/431] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd 25.10.2023.pdf... OK (21.2s)
[142/431] Endeavour Holdings Limited - Notice of Annual General Meeting (Cover Letter) dd28.08.2024.pdf... OK (21.2s)
[143/431] Endeavour Holdings Limited - Notice of Annual General Meeting (Press Release) dd 22.08.2025.pdf... OK (42.8s)
[144/431] Endeavour Holdings Limited - Notice of Annual General Meeting (Press Release) dd 28.08.2024.pdf... OK (42.4s)
[145/431] Endeavour Holdings Limited - Notice of Final Dividend Payment (Media Release) dd 24.06.2024.pdf... OK (20.9s)
[146/431] Endeavour Holdings Limited - Notice of Interim Dividend Payment (Media Release) dd 28.11.2024.pdf... OK (21.2s)
[147/431] Endeavour Holdings Limited - Notice of Interim Dividned Payment (Press Release) dd 24.11.2023.pdf... OK (21.8s)
[148/431] Endeavour Holdings Limited - Shareholdings Report as October 31 2024 dd 28.11.2024.pdf... OK (63.2s)
[149/431] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2024  dd 22.05.2024.pdf...     Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2024  dd 22.05.2024_p3.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2024  dd 22.05.2024_p3.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2024  dd 22.05.2024_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
OK (148.2s)
[150/431] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025.pdf...     Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p1.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p1.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p2.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p2.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p3.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p3.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2025 dd 20.05.2025_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (133.5s)
  -- checkpoint saved (465 total results so far)
[151/431] Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026.pdf...     Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026_p1.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026_p1.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026_p2.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at April 30, 2026 dd 06.05.2026_p2.jpg, attempt 2
OK (102.4s)
[152/431] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2024  dd 06.03.2024.pdf... OK (62.9s)
[153/431] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2025 dd 18.02.2025.pdf... OK (63.2s)
[154/431] Endeavour Holdings Limited - Shareholdings Report as at January 31, 2026 dd 24.02.2026.pdf... OK (63.5s)
[155/431] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2023  dd 05.09.2023.pdf... OK (62.9s)
[156/431] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2024 dd 12.08.2024.pdf... OK (66.0s)
[157/431] Endeavour Holdings Limited - Shareholdings Report as at July 31, 2025 dd 07.08.2025.pdf... OK (63.2s)
[158/431] Endeavour Holdings Limited - Shareholdings Report as at October 30, 2023  dd 24.11.2023.pdf... OK (122.0s)
[159/431] Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025.pdf...     Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p1.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p1.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p2.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p2.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p3.jpg, attempt 1
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p3.jpg, attempt 2
    Server error (503) on Endeavour Holdings Limited - Shareholdings Report as at October 31, 2025 dd 10.11.2025_p3.jpg, attempt 3
    page 3 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (133.5s)
[160/431] Eppley Caribbean Property Fund Limited - Notice of Dividend (email) dd 14.02.2025.pdf...     Server error (503) on Eppley Caribbean Property Fund Limited - Notice of Dividend (email) dd 14.02.2025_p1.jpg, attempt 1
    Server error (503) on Eppley Caribbean Property Fund Limited - Notice of Dividend (email) dd 14.02.2025_p1.jpg, attempt 2
    Server error (503) on Eppley Caribbean Property Fund Limited - Notice of Dividend (email) dd 14.02.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
  -- checkpoint saved (475 total results so far)
[161/431] Eppley Caribbean Property Fund Limited - Notice of Dividend Payment dd 19.02.2025.pdf... OK (21.5s)
[162/431] Eppley Caribbean Property Fund Limited - Transition to Annual Property Appraisals (Cover letter).pdf... OK (21.8s)
[163/431] Eppley Caribbean Property Fund Limited SCC - Val Fund - Notice of Dividend Payment dd 08.08.2024.pdf... OK (21.2s)
[164/431] Eppley Caribbean Property Fund Limited SCC - Val Fund - Notice of Dividend Payment dd 15.05.2024.pdf... OK (21.2s)
[165/431] Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024.pdf...     Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p17.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p17.jpg, attempt 2
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p17.jpg, attempt 3

    page 17 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p18.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p18.jpg, attempt 2
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p18.jpg, attempt 3
    page 18 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p19.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p19.jpg, attempt 2
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p19.jpg, attempt 3
    page 19 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p20.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p20.jpg, attempt 2
    Server error (503) on Eric Solis Marketing Limited - Audited Financial Statements for the year ended April 30th 2024_p20.jpg, attempt 3
    page 20 failed: failed after 3 attempts (timeouts/errors)
OK (573.2s)
[166/431] Eric Solis Marketing Limited - Notice of Acquisition (Cover Letter) dd 31.01.2025.pdf...     Server error (503) on Eric Solis Marketing Limited - Notice of Acquisition (Cover Letter) dd 31.01.2025_p1.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Notice of Acquisition (Cover Letter) dd 31.01.2025_p1.jpg, attempt 2
    Server error (503) on Eric Solis Marketing Limited - Notice of Acquisition (Cover Letter) dd 31.01.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[167/431] Eric Solis Marketing Limited - Notice of Change in By-Laws (Cover Letter) dd 14.08.2025.pdf...     Server error (503) on Eric Solis Marketing Limited - Notice of Change in By-Laws (Cover Letter) dd 14.08.2025_p1.jpg, attempt 1
    Server error (503) on Eric Solis Marketing Limited - Notice of Change in By-Laws (Cover Letter) dd 14.08.2025_p1.jpg, attempt 2
OK (37.5s)
[168/431] Eric Solis Marketing Limited - Notice of Dividend Payment (CL) dd 28.07.2025.pdf... OK (21.2s)
[169/431] Eric Solis Marketing Limited - Notice of Material Change (Cover Letter) dd 26.06.2026.pdf... OK (21.5s)
[170/431] Eric Solis Marketing Limited - Submission of Annual Report 2025 (Cover Letter) dd 15.08.2025.pdf... OK (21.5s)
  -- checkpoint saved (485 total results so far)
[171/431] Eris Solis Marketing Limited - Notice of Change of Auditor (Cover Letter) dd 21.02.2025.pdf... OK (21.2s)
[172/431] First Citizens Group Financial Holdings Limited - Notice of Availability of Annual Report 2024.pdf... OK (21.4s)
[173/431] First Citizens Group Financial Holdings Limited - Request for Exemption dd 27.03.2025.pdf... OK (42.5s)
[174/431] FirstCaribbean International Bank Limited - Copies of the 2023 Annual Report dd 24.01.24.pdf... OK (21.2s)
[175/431] FirstCaribbean International Bank Limited - Notice of Material Change (Cover letter) dd 15.02.2024.pdf... OK (21.2s)
[176/431] FirstCaribbean International Bank Limited - Notice of Material Change (Press release) dd 15.02.2024.pdf... OK (21.1s)
[177/431] GraceKennedy Limited - Appointment of Head of Risk (press release) dd 06.02.2024.pdf... OK (20.9s)
[178/431] GraceKennedy Limited - Audited Financial Statements (Cover Letter) dd 02.03.2026.pdf... OK (21.2s)
[179/431] GraceKennedy Limited - Notice of 2nd Interim Dividend Payment (Cover letter) dd 10.05.2024.pdf... OK (21.3s)
[180/431] GraceKennedy Limited - Notice of Appointmet of Senior Officer (Press Release) dd 06.01.2026.pdf... OK (20.8s)
  -- checkpoint saved (495 total results so far)
[181/431] GraceKennedy Limited - Notice of Availability of Annual Report 2025 (Press Release).pdf... OK (21.1s)
[182/431] GraceKennedy Limited - Notice of Closure of Register of Members dd 07.11.24.pdf... OK (20.8s)
[183/431] GraceKennedy Limited - Notice of Interim Dividend Payment (PR) dd 14.05.2026.pdf... OK (21.2s)
[184/431] GraceKennedy Limited - Notice of Interim Dividend Payment (Press Release) dd 27.02.2026.pdf... OK (21.2s)
[185/431] GraceKennedy Limited - Notice of Share Repurchase  150,000 shares ( Cover Letter) dd 18.06.2024.pdf... OK (21.3s)
[186/431] GraceKennedy Limited - Notice of Share Repurchase - 47,093 Shares ( Cover Letter ) dd 23.09.2024.pdf... OK (21.9s)
[188/431] GraceKennedy Limited - Notice of Share Repurchase - 73,000  Shares (Cover Letter) dd 14.05.2024.pdf... OK (74.8s)
[189/431] GraceKennedy Limited- Notice of Material Change(Press Release)   dd 02-01-24.pdf...     Server error (503) on GraceKennedy Limited- Notice of Material Change(Press Release)   dd 02-01-24_p1.jpg, attempt 1
    Server error (503) on GraceKennedy Limited- Notice of Material Change(Press Release)   dd 02-01-24_p1.jpg, attempt 2
    Server error (503) on GraceKennedy Limited- Notice of Material Change(Press Release)   dd 02-01-24_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[190/431] Guardian Holdings Limited - 2024 Annual Report (Cover Letter) dd 24.04.2025.pdf...     Server error (503) on Guardian Holdings Limited - 2024 Annual Report (Cover Letter) dd 24.04.2025_p1.jpg, attempt 1
    Server error (503) on Guardian Holdings Limited - 2024 Annual Report (Cover Letter) dd 24.04.2025_p1.jpg, attempt 2
    Server error (503) on Guardian Holdings Limited - 2024 Annual Report (Cover Letter) dd 24.04.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
  -- checkpoint saved (505 total results so far)
[191/431] Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025.pdf...     Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p1.jpg, attempt 1
    Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p1.jpg, attempt 2
    Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p2.jpg, attempt 1
    Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p2.jpg, attempt 2
    Server error (503) on Guardian Holdings Limited - Express publication - Q2 Dividend and Financials dd 01.08.2025_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (89.2s)
[192/431] Guardian Holdings Limited - Newsday publication - Dividend and Financials dd 01.08.2025.pdf... OK (65.5s)
[193/431] Guardian Holdings Limited - Notice of Appointment of Director (PR) dd 01.05.2026.pdf... OK (21.8s)
[194/431] Guardian Holdings Limited - Notice of Interim Dividend Payment (Cover Letter) dd 01.08.2024.pdf... OK (22.0s)
[195/431] Guardian Holdings Limited - Notice of Third Interim Dividend Payment (Press release) dd 31.10.2025.pdf... OK (21.5s)
[196/431] Guardian Holdings Limited - Schedule 8 (Patrick Solomon) dd 13.05.2026.pdf... OK (43.4s)
[197/431] Guardian Media Limited - Notice of Annual General Meeting (Cover Letter) dd 019.04.2024.pdf... OK (21.3s)
[198/431] Guardian Media Limited - Notice of Annual Meeting (Cover Letter ) dd 24.04.2025.pdf... OK (21.9s)
[199/431] Guardian Media Limited - Notice of Annual Report (Cover Letter) dd 28.04.2025.pdf... OK (21.2s)
[200/431] Guardian Media Limited - Notice of Annual Report (Cover Letter) dd 29.04.2024.pdf... OK (41.8s)
  -- checkpoint saved (515 total results so far)
[201/431] Guardian Media Limited - Notice of Appointment of Managing Director (Cover Letter) dd 06.11.2024.pdf... OK (21.5s)
[202/431] Guardian Media Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 02.01.2025.pdf... OK (21.3s)
[203/431] Guardian Media Limited - Notice of Availability of Annual Report 2025 (CL) dd 30.04.2026.pdf... OK (21.4s)
[204/431] Guardian Media Limited - Notice of Final Dividend Payment 2024 dd 20.03.2025.pdf... OK (24.7s)
[205/431] Guardian Media Limited - Notice of Interim Dividend Payment 2025 dd 06.08.2025.pdf... OK (43.9s)
[206/431] Guardian Media Limited - Notice of Interim dividend (Cover letter) dd 07.08.2024.pdf... OK (74.1s)
[207/431] Guardian Media Limited - Notice of Rescheduled Annual General Meeting (Cover Letter) dd 28.04.2026.pdf...     Server error (503) on Guardian Media Limited - Notice of Rescheduled Annual General Meeting (Cover Letter) dd 28.04.2026_p1.jpg, attempt 1
    Server error (503) on Guardian Media Limited - Notice of Rescheduled Annual General Meeting (Cover Letter) dd 28.04.2026_p1.jpg, attempt 2
    Server error (503) on Guardian Media Limited - Notice of Rescheduled Annual General Meeting (Cover Letter) dd 28.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.8s)
[208/431] Investor release Nov 23.pdf...     Server error (503) on Investor release Nov 23_p1.jpg, attempt 1
    Server error (503) on Investor release Nov 23_p1.jpg, attempt 2
    Server error (503) on Investor release Nov 23_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[209/431] JMMB Group Limited -  Notice of Appointment of a Director (Press Release) dd 31.03.2024.pdf...     Server error (503) on JMMB Group Limited -  Notice of Appointment of a Director (Press Release) dd 31.03.2024_p1.jpg, attempt 1
    Server error (503) on JMMB Group Limited -  Notice of Appointment of a Director (Press Release) dd 31.03.2024_p1.jpg, attempt 2
    Server error (503) on JMMB Group Limited -  Notice of Appointment of a Director (Press Release) dd 31.03.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[210/431] JMMB Group Limited - Notice of Annual General Meeting (Press Release) dd 15.09.2025.pdf...     Server error (503) on JMMB Group Limited - Notice of Annual General Meeting (Press Release) dd 15.09.2025_p1.jpg, attempt 1
    Server error (503) on JMMB Group Limited - Notice of Annual General Meeting (Press Release) dd 15.09.2025_p1.jpg, attempt 2
    Server error (503) on JMMB Group Limited - Notice of Annual General Meeting (Press Release) dd 15.09.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.1s)
  -- checkpoint saved (525 total results so far)
[211/431] JMMB Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 12.08.2025.pdf... OK (21.2s)
[212/431] JMMB Group Limited - Notice of Appointment of Senior Officer (Press Release) dd 25.11.2025.pdf... OK (21.2s)
[213/431] JMMB Group Limited - Notice of Delay in Publication of Annual Report (Cover Letter) dd 22.07.2024.pdf... OK (21.9s)
[214/431] JMMB Group Limited - Notice of ESOP Trading dd 24.06.2025.pdf... OK (21.3s)
[215/431] JMMB Group Limited - Notice of Interim Dividend Payment (Cover Letter) dd 20.06.2024 - Amended.pdf... OK (21.3s)
[216/431] JMMB Group Limited - Notice of Leadership Change Advisory (Cover Letter) dd 31.07.2024.pdf... OK (21.3s)
[217/431] JMMB Group Limited - Notice of Leadership Change Advisory (Press Release) dd 20.09.2024.pdf... OK (22.1s)
[218/431] JMMB Group Limited - Notice of Reorganization of Board of Directors (Press Release) dd 02.01.2026.pdf... OK (21.2s)
[219/431] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 06.06.2025.pdf... OK (21.3s)
[220/431] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 11.06.2025.pdf... OK (22.6s)
  -- checkpoint saved (535 total results so far)
[221/431] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 11.06.2026.pdf... OK (21.6s)
[222/431] JMMB Group Limited - Notice of Trading in Shares (Cover Letter) dd 23.06.2025.pdf... OK (22.3s)
[223/431] JMMB Group Limited - Notice of availability of QFS for the period ended 31 December 2023.pdf... OK (21.2s)
[224/431] L.J. Williams Limited -  Notice of Appointment of Auditors (Cover Leter) dd 06.11.24.pdf... OK (21.2s)
[225/431] L.J. Williams Limited - Amended Shareholdings reports as at December 31, 2024 dd 14.02.2025.pdf... OK (63.0s)
[226/431] L.J. Williams Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 03.12.2025.pdf... OK (22.3s)
[227/431] L.J. Williams Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.12.2025.pdf...     Server error (502) on L.J. Williams Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.12.2025_p1.jpg, attempt 1
    Server error (503) on L.J. Williams Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.12.2025_p1.jpg, attempt 2
    Server error (503) on L.J. Williams Limited - Notice of Appointment of Senior Officer (Press Release) dd 03.12.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.5s)
[228/431] L.J. Williams Limited - Notice of Change of Senior Officer (Cover Letter) dd 30.04.2026.pdf...     Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Cover Letter) dd 30.04.2026_p1.jpg, attempt 1
    Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Cover Letter) dd 30.04.2026_p1.jpg, attempt 2
    Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Cover Letter) dd 30.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[229/431] L.J. Williams Limited - Notice of Change of Senior Officer (Press Release) dd 30.04.2026.pdf...     Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Press Release) dd 30.04.2026_p1.jpg, attempt 1
    Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Press Release) dd 30.04.2026_p1.jpg, attempt 2
    Server error (503) on L.J. Williams Limited - Notice of Change of Senior Officer (Press Release) dd 30.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[230/431] L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 06.03.2024.pdf...     Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 06.03.2024_p1.jpg, attempt 1
    Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 06.03.2024_p1.jpg, attempt 2
    Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 06.03.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
  -- checkpoint saved (545 total results so far)
[231/431] L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 28.02.2025.pdf...     Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 28.02.2025_p1.jpg, attempt 1
    Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 28.02.2025_p1.jpg, attempt 2
    Server error (503) on L.J. Williams Limited - Notice of Trading in shares (Cover Letter) dd 28.02.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[232/431] L.J. Williams Limited - Shareholdings reports as at December 31, 2024 dd 11.02.2025.pdf... OK (43.4s)
[233/431] L.J. Williams Limited - Shareholdings reports as at December 31st, 2025 dd 13.02.2026.pdf... OK (63.7s)
[234/431] L.J. Williams Limited - Shareholdings reports as at June 30, 2024 dd 12.08.2024.pdf... OK (42.5s)
[235/431] L.J. Williams Limited - Shareholdings reports as at June 30, 2025 dd 14.08.2025.pdf... OK (63.3s)

[236/431] L.J. Williams Limited - Shareholdings reports as at September 30, 2024 dd 12.11.2024.pdf... OK (43.4s)
[237/431] L.J. Williams Limited - Updated Shareholdings reports as at December 31st, 2025 dd 08.04.2026.pdf... OK (65.7s)
[238/431] Letter from MED - Reconstitution of Audit Risk Compiance and Compensation Committee dd 11.06.26.pdf... OK (35.3s)
[239/431] Letters from AGL - Response to query on Top Ten Shareholders dd 18.02.2025.pdf... OK (77.2s)
[240/431] MPC Caribbean Clean Energy Limited - Annual Report 2024 (Cover Letter) dd 29.04.2025.pdf...     Server error (503) on MPC Caribbean Clean Energy Limited - Annual Report 2024 (Cover Letter) dd 29.04.2025_p1.jpg, attempt 1
    Server error (503) on MPC Caribbean Clean Energy Limited - Annual Report 2024 (Cover Letter) dd 29.04.2025_p1.jpg, attempt 2
    Server error (503) on MPC Caribbean Clean Energy Limited - Annual Report 2024 (Cover Letter) dd 29.04.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
  -- checkpoint saved (555 total results so far)
[241/431] Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Press Release)  dd 01.06.2026.pdf...     Server error (503) on Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Press Release)  dd 01.06.2026_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Press Release)  dd 01.06.2026_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd - Election of Chairman Designate - P. Hylton (Press Release)  dd 01.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[242/431] Massy Holdings Ltd. -  Notice of Change in Directorship (Press Release) dd 20.01.2025.pdf...     Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship (Press Release) dd 20.01.2025_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship (Press Release) dd 20.01.2025_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship (Press Release) dd 20.01.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.2s)
[243/431] Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Press Release) dd 21.01.2025.pdf...     Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Press Release) dd 21.01.2025_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Press Release) dd 21.01.2025_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. -  Notice of Change in Directorship Corrected (Press Release) dd 21.01.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (45.2s)
[244/431] Massy Holdings Ltd. - Annual Report 2025 (Cover Letter)  dd 05.01.2026.pdf...     Server error (503) on Massy Holdings Ltd. - Annual Report 2025 (Cover Letter)  dd 05.01.2026_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. - Annual Report 2025 (Cover Letter)  dd 05.01.2026_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. - Annual Report 2025 (Cover Letter)  dd 05.01.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[245/431] Massy Holdings Ltd. - Annual Report 2025 - Electronic Submission (Cover Letter)  dd 07.01.2026.pdf... OK (21.9s)
[246/431] Massy Holdings Ltd. - Notice interim dividend payment (Press release) dd 09.05.2024.pdf... OK (22.9s)
[247/431] Massy Holdings Ltd. - Notice of 2024 Annual Report dd 26.11.2024.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1626380}
FAILED (no text) (21.6s)
[248/431] Massy Holdings Ltd. - Notice of 2025 Annual Report dd 18.12.2025.pdf... OK (21.2s)
[249/431] Massy Holdings Ltd. - Notice of Annual General Meeting dd 18.12.2025.pdf... OK (22.1s)
[250/431] Massy Holdings Ltd. - Notice of Annual General Meeting dd 26.11.2024.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1687617}
FAILED (no text) (21.6s)
  -- checkpoint saved (565 total results so far)
[251/431] Massy Holdings Ltd. - Notice of Appointment of Acting General Counsel (Press Release) dd 10.01.23.pdf... OK (21.4s)
[252/431] Massy Holdings Ltd. - Notice of Appointment of Senior Officer (Press Release) dd 06.03.2026.pdf... OK (21.1s)
[253/431] Massy Holdings Ltd. - Notice of Appointment of Senior Officer (Press Release) dd 15.07.2025.pdf... OK (21.4s)
[254/431] Massy Holdings Ltd. - Notice of Appointment of a Senior Officer  (Press Release) dd 23.09.2024.pdf... OK (20.8s)
[255/431] Massy Holdings Ltd. - Notice of Change in Board Composition (Press Release) dd 25.11.2024.pdf...     page 1 failed: HTTP 413: {"error":"E556: File too large. Max 1.5 MB for Free Plan (Upgrade to PRO/PROPDF for much higher limits).","sizeBytes":1993507}
FAILED (no text) (21.7s)
[256/431] Massy Holdings Ltd. - Notice of Change in Dividend Payment Schedule (Press Release) dd 20.11.2024.pdf... OK (21.7s)
[257/431] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Press Release) dd 12.08.2025.pdf... OK (21.5s)
[258/431] Massy Holdings Ltd. - Notice of Change in Senior Officers and Directors (Press Release) dd 13.08.2025.pdf... OK (21.2s)
[259/431] Massy Holdings Ltd. - Notice of Change in Senior Officers- EVP & Deputy Group CEO dd 6.12.24.pdf... OK (22.1s)
[260/431] Massy Holdings Ltd. - Notice of Final Dividend Payment (Press Release) dd 12.12.2025.pdf... OK (21.2s)
  -- checkpoint saved (575 total results so far)
[261/431] Massy Holdings Ltd. - Notice of Interim Dividend Payment (Press Release) dd 06.02.2026.pdf... OK (21.2s)
[262/431] Massy Holdings Ltd. - Notice of Interim Dividend Payment (Press Release) dd 08.05.2026.pdf... OK (21.3s)
[263/431] Massy Holdings Ltd. - Notice of Interim Dividend Payment dd 07.02.2025.pdf... OK (21.9s)
[264/431] Massy Holdings Ltd. - Notice of Interim Dividend Payment dd 09.05.2025.pdf... OK (21.2s)
[265/431] Massy Holdings Ltd. - Notice of Partial Final Dividend Payment (Press Release) dd 20.11.2025.pdf... OK (32.1s)
[266/431] Massy Holdings Ltd. - Notice of Resignation of Director (Press Release) dd 12.03.2025.pdf... OK (68.3s)
[267/431] Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 06.03.2026.pdf...     Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 06.03.2026_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 06.03.2026_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 06.03.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[268/431] Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 09.07.2025.pdf...     Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 09.07.2025_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 09.07.2025_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. - Notice of Resignation of Senior Officer (Press Release) dd 09.07.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[269/431] Massy Holdings Ltd. - Notice of Third Interim Dividend Payment dd 08.08.2025.pdf...     Server error (503) on Massy Holdings Ltd. - Notice of Third Interim Dividend Payment dd 08.08.2025_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. - Notice of Third Interim Dividend Payment dd 08.08.2025_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. - Notice of Third Interim Dividend Payment dd 08.08.2025_p1.jpg, attempt 3

    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[270/431] Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 12.03.2024.pdf...     Server error (503) on Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 12.03.2024_p1.jpg, attempt 1
    Server error (503) on Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 12.03.2024_p1.jpg, attempt 2
    Server error (503) on Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 12.03.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
  -- checkpoint saved (585 total results so far)
[271/431] Massy Holdings Ltd. - Notice of change in Senior Officer (Press release) dd 25.03.2024.pdf... OK (21.1s)
[272/431] Massy Holdings Ltd. -Notice of Appointment of a Director (Press release) dd 14.08.2024.pdf... OK (21.7s)
[273/431] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 11.09.2024.pdf... OK (21.4s)
[274/431] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 13.05.2024.pdf... OK (21.1s)
[275/431] Massy Holdings Ltd. -Notice of change in Senior Officer (Press Release) dd 23.05.2024.pdf... OK (21.1s)
[276/431] Masys Holdings Ltd. - Notice of Appointment of Director (Press Release) dd 12.03.2025.pdf... OK (21.1s)
[277/431] Medcorp Limited - Notice of Availability of Annual Report 2025 (Press Release) dd 30.04.2026.pdf... OK (22.8s)
[278/431] Medcorp Limited - Notice of Final Dividend Payment (Cover Letter) dd 29.01.2026.pdf... OK (23.1s)
[279/431] Medcorp Limited - Notice of Resignation of Director (Cover Letter) dd 13.05.2026.pdf... OK (21.6s)
[280/431] Medcorp Limited - Notice of Resignation of Director (Press Release) dd 13.05.2026.pdf... OK (31.2s)
  -- checkpoint saved (595 total results so far)
[281/431] Medcorp Limited - Notice of Trading in Shares (Cover Letter) dd  02.09.2025.pdf... OK (21.2s)
[282/431] Medcorp Limited - Submission of Annual Report 2025 dd 30.04.2026.pdf... OK (21.2s)
[283/431] Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026.pdf...     Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p6.jpg, attempt 1
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p6.jpg, attempt 2
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p6.jpg, attempt 3
    page 6 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p7.jpg, attempt 1
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p7.jpg, attempt 2
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p7.jpg, attempt 3
    page 7 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p8.jpg, attempt 1
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p8.jpg, attempt 2
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p8.jpg, attempt 3
    page 8 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p9.jpg, attempt 1
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p9.jpg, attempt 2
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p9.jpg, attempt 3
    page 9 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Medcorp Limited - Unaudited Interim Financial Statements for the Quarter ended March 31, 2026_p10.jpg, attempt 1
OK (370.9s)
[284/431] NCB Financial Group Limited - Submission of Annual Report (Cover Letter) dd 26.01.2026.pdf... OK (24.0s)
[285/431] National Enterprises Limited - Notice of Annual General Meeting-Express dd 29.02.2024.pdf... OK (26.8s)
[286/431] National Enterprises Limited - Notice of Annual General Meeting-Guardian dd 29.02.2024.pdf... OK (21.8s)
[287/431] National Enterprises Limited - Notice of Appointment of Chairman (Press Release) dd 09.09.2025.pdf... OK (21.2s)
[288/431] National Enterprises Limited - Notice of Availability of Annual Report 2024 dd 28.01.2025.pdf... OK (20.9s)
[289/431] National Enterprises Limited - Notice of Change in Directors dd 07.06.2024.pdf... OK (20.8s)
[290/431] National Enterprises Limited - Notice of Dividend Payment (Cover Letter) dd 19.07.2023.pdf... OK (21.2s)
  -- checkpoint saved (605 total results so far)
[291/431] National Enterprises Limited - Notice of Dividend Payment (Press Release) dd 18.12.2023.pdf... OK (20.8s)
[292/431] National Enterprises Limited - Notice of Dividend Payment (Press Release) dd 19.07.2023.pdf... OK (21.1s)
[293/431] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 17.06.2026.pdf... OK (21.6s)
[294/431] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 22.05.2024.pdf... OK (21.1s)
[295/431] National Enterprises Limited - Notice of Interim Dividend Payment (Press Release) dd 23.06.2025.pdf... OK (78.0s)
[296/431] National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 09.01.2026.pdf...     Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 09.01.2026_p1.jpg, attempt 1
    Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 09.01.2026_p1.jpg, attempt 2
    Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 09.01.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[297/431] National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 13.05.2025.pdf...     Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 13.05.2025_p1.jpg, attempt 1
    Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 13.05.2025_p1.jpg, attempt 2
    Server error (503) on National Enterprises Limited - Notice of Resignation of Director (Press Release) dd 13.05.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[298/431] National Enterprises Limited - Notice of Retirement of Directors (Press Release) dd 08.09.2025.pdf...     Server error (503) on National Enterprises Limited - Notice of Retirement of Directors (Press Release) dd 08.09.2025_p1.jpg, attempt 1
    Server error (503) on National Enterprises Limited - Notice of Retirement of Directors (Press Release) dd 08.09.2025_p1.jpg, attempt 2
    Server error (503) on National Enterprises Limited - Notice of Retirement of Directors (Press Release) dd 08.09.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[299/431] National Enterprises Limited - Notice of Second Interim Dividend Payment (PR) dd 31.12.2025.pdf...     Server error (503) on National Enterprises Limited - Notice of Second Interim Dividend Payment (PR) dd 31.12.2025_p1.jpg, attempt 1
    Server error (503) on National Enterprises Limited - Notice of Second Interim Dividend Payment (PR) dd 31.12.2025_p1.jpg, attempt 2
    Server error (503) on National Enterprises Limited - Notice of Second Interim Dividend Payment (PR) dd 31.12.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[300/431] National Enterprises Limited - Notice of Third Dividend Payment (Press release) dd 13.12.2023.pdf...     Server error (503) on National Enterprises Limited - Notice of Third Dividend Payment (Press release) dd 13.12.2023_p1.jpg, attempt 1

    Server error (503) on National Enterprises Limited - Notice of Third Dividend Payment (Press release) dd 13.12.2023_p1.jpg, attempt 2
    Server error (503) on National Enterprises Limited - Notice of Third Dividend Payment (Press release) dd 13.12.2023_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
  -- checkpoint saved (615 total results so far)
[301/431] National Enterprises Limited - Shareholdings Report as at June, 30 2024 dd 06.08.2024.pdf...     Server error (503) on National Enterprises Limited - Shareholdings Report as at June, 30 2024 dd 06.08.2024_p1.jpg, attempt 1
OK (50.8s)
[302/431] National Flour Mills Limited - Amended Notice of Annual General Meeting (Cover Letter) dd 10.12.2025.pdf... OK (22.3s)
[303/431] National Flour Mills Limited - Amended Notice of Annual General Meeting (Press Release) dd 10.12.2025.pdf... OK (22.3s)
[304/431] National Flour Mills Limited - Notice of AGM, Proxy Form and Management Proxy Circular.pdf... OK (46.0s)
[305/431] National Flour Mills Limited - Notice of Annual General Meeting of Shareholders dd 23.05.2024.pdf... OK (21.6s)
[306/431] National Flour Mills Limited - Notice of Annual Meeting (Cover Letter) dd 25.09.2025.pdf... OK (21.3s)
[307/431] National Flour Mills Limited - Notice of Annual Meeting (Press Release) dd 29.09.2025.pdf... OK (21.6s)
[308/431] National Flour Mills Limited - Notice of Appointment of Director (Cover Letter) 04.11.2024.pdf... OK (21.4s)
[309/431] National Flour Mills Limited - Notice of Appointment of Directors (Cover Letter) dd 31.12.2025.pdf... OK (42.6s)
[310/431] National Flour Mills Limited - Notice of Appointment of Senior Officer (Cover Letter) dd 27.05.2026.pdf... OK (21.3s)
  -- checkpoint saved (625 total results so far)
[311/431] National Flour Mills Limited - Notice of Election of Directors (Cover Letter) 27.09.2024.pdf... OK (22.3s)
[312/431] National Flour Mills Limited - Notice of Final Dividend Payment (Cover Letter) 30.12.2025.pdf... OK (21.3s)
[313/431] National Flour Mills Limited - Notice of Postponement of Annual Meeting (Cover Letter) dd 17.10.2025.pdf...     Server error (502) on National Flour Mills Limited - Notice of Postponement of Annual Meeting (Cover Letter) dd 17.10.2025_p1.jpg, attempt 1
    Server error (502) on National Flour Mills Limited - Notice of Postponement of Annual Meeting (Cover Letter) dd 17.10.2025_p1.jpg, attempt 2
    Server error (503) on National Flour Mills Limited - Notice of Postponement of Annual Meeting (Cover Letter) dd 17.10.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (164.8s)
[314/431] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 03.03.2026.pdf...     Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 03.03.2026_p1.jpg, attempt 1
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 03.03.2026_p1.jpg, attempt 2
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 03.03.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[315/431] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 08.08.2025.pdf...     Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 08.08.2025_p1.jpg, attempt 1
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 08.08.2025_p1.jpg, attempt 2
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 08.08.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[316/431] National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 12.02.2026.pdf...     Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 12.02.2026_p1.jpg, attempt 1
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 12.02.2026_p1.jpg, attempt 2
    Server error (503) on National Flour Mills Limited - Notice of Resignation of Senior Officer (Cover Letter) dd 12.02.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.7s)
[317/431] National Flour Mills Limited - Notice of Resignation of Senior Officer (Press Release) dd 03.03.2026.pdf... OK (22.2s)
[318/431] National Flour Mills Limited - Notice of Resignation of a Director (Cover Letter) 06.09.2024.pdf... OK (22.7s)
[319/431] National Flour Mills Limited - Notice of Resignation of a Director (Cover Letter) dd 26.06.2024.pdf... OK (42.1s)
[320/431] National Investment Fund Holding Company Limited - 14th Semi Annual Coupon Payment dd 11.08.2025.pdf... OK (21.3s)
  -- checkpoint saved (635 total results so far)
[321/431] National Investment Fund Holding Company Limited - Notice of NIF Bond 2 Offering dd 17.01.24.pdf... OK (21.2s)
[322/431] National Investment Fund Holding Company Limited - Revision regarding Investment Notice dd 09.01.2024.pdf... OK (21.1s)
[323/431] Notice of Record Date for Annual Report (Cover Letter) dd 27.03.2024.pdf... OK (21.3s)
[324/431] Notice of Record Date for Annual Report (Press release) dd 27.03.2024.pdf... OK (21.8s)
[325/431] One Caribbean Medai Limited - Notice of Annual General Meeting dd 12.06.2025.pdf... OK (21.2s)
[326/431] One Caribbean Media Limited - Annual Report (Cover Letter) 2024 dd 29.04.2025.pdf... OK (21.2s)
[327/431] One Caribbean Media Limited - Notice of Annual General Meeting (Cover Letter) dd 16.06.2025.pdf... OK (23.7s)
[328/431] One Caribbean Media Limited - Notice of Annual General Meeting (Press Release) dd 11.06.2026.pdf... OK (22.1s)
[329/431] One Caribbean Media Limited - Notice of Annual General Meeting.pdf... OK (54.1s)
[330/431] One Caribbean Media Limited - Notice of Availability of Annual Report 2025 dd 06.05.2026.pdf... OK (78.1s)
  -- checkpoint saved (645 total results so far)
[331/431] One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 07.11.2025.pdf...     Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 07.11.2025_p1.jpg, attempt 1
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 07.11.2025_p1.jpg, attempt 2
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 07.11.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[332/431] One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 09.06.2025.pdf...     Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 09.06.2025_p1.jpg, attempt 1
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 09.06.2025_p1.jpg, attempt 2
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Cover Letter) dd 09.06.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[333/431] One Caribbean Media Limited - Notice of Dividend Payment (Press Release) dd 12.11.2025.pdf...     Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Press Release) dd 12.11.2025_p1.jpg, attempt 1
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Press Release) dd 12.11.2025_p1.jpg, attempt 2
    Server error (503) on One Caribbean Media Limited - Notice of Dividend Payment (Press Release) dd 12.11.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
[334/431] One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2025.pdf...     Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2025_p1.jpg, attempt 1

    Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2025_p1.jpg, attempt 2
    Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 02.04.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[335/431] One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 30.04.2026.pdf...     Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 30.04.2026_p1.jpg, attempt 1
    Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 30.04.2026_p1.jpg, attempt 2
    Server error (503) on One Caribbean Media Limited - Notice of Final Dividend Payment (Cover Letter) dd 30.04.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[336/431] One Caribbean Media Limited - Notice of Final Dividend Payment (Press Release) dd 04.05.2026.pdf... OK (23.4s)
[337/431] One Caribbean Media Limited - Notice of Final Dividend payment  dd 08.04.2024.pdf... OK (22.4s)
[338/431] One Caribbean Media Limited - Notice of Final Dividend payment (Press Releases) dd 06.06.2024.pdf... OK (21.5s)
[339/431] One Caribbean Media Limited - Notice of Publication of Annual Report 2023 dd15.05.2024.pdf... OK (22.8s)
[340/431] One Caribbean Media Limited - Notice of Publication of Annual Report 2024 dd 29.04.2025.pdf... OK (21.3s)
  -- checkpoint saved (655 total results so far)
[341/431] One Caribbean Media Limited - Notice of Resignation of Director (Cover Letter) dd 05.08.2025.pdf... OK (23.7s)
[342/431] One Caribbean Media Limited - Notice of Resignation of Director (Press Release) dd 05.08.2025.pdf... OK (20.9s)
[343/431] One Caribbean Media Limited - Notice of Trading in Shares (Cover Letter) dd 22.08.2025.pdf... OK (23.1s)
[344/431] Prestige Holdings Limited - Annual Report 2024 - 6 copies (Cover Letter) dd 02.05.2025.pdf... OK (21.2s)
[345/431] Prestige Holdings Limited - Annual Report 2025 (hardcopy) (Cover Letter) dd 31.03.2026.pdf... OK (21.9s)
[346/431] Prestige Holdings Limited - Notice of Availability of Annual Report 2025 (PR) dd 01.04.2026.pdf... OK (22.1s)
[347/431] Prestige Holdings Limited - Notice of Error in Record Date (Press Release) dd 02.04.2026.pdf... OK (20.8s)
[348/431] Prestige Holdings Limited Annual Report 2024.pdf...     Server error (502) on Prestige Holdings Limited Annual Report 2024_p16.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p16.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p16.jpg, attempt 3
    page 16 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p17.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p17.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p17.jpg, attempt 3
    page 17 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p18.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p18.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p18.jpg, attempt 3
    page 18 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p19.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p19.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p19.jpg, attempt 3
    page 19 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p20.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p20.jpg, attempt 2
    Server error (502) on Prestige Holdings Limited Annual Report 2024_p38.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p38.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p38.jpg, attempt 3
    page 38 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p39.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p39.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p39.jpg, attempt 3
    page 39 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p40.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p40.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p40.jpg, attempt 3
    page 40 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p41.jpg, attempt 1
    page 41 failed: request exception: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
    Timeout on Prestige Holdings Limited Annual Report 2024_p42.jpg (attempt 1/3, dpi=200)
    Server error (502) on Prestige Holdings Limited Annual Report 2024_p63.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p63.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p63.jpg, attempt 3
    page 63 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p64.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p64.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p64.jpg, attempt 3
    page 64 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p65.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p65.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p65.jpg, attempt 3
    page 65 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p66.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p66.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p66.jpg, attempt 3
    page 66 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p67.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p67.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p67.jpg, attempt 3
    page 67 failed: failed after 3 attempts (timeouts/errors)
    Server error (502) on Prestige Holdings Limited Annual Report 2024_p91.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p91.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p91.jpg, attempt 3
    page 91 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p92.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p92.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p92.jpg, attempt 3
    page 92 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p93.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p93.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p93.jpg, attempt 3
    page 93 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p94.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p94.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p94.jpg, attempt 3

    page 94 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p95.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p95.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p95.jpg, attempt 3
    page 95 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p118.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p118.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p118.jpg, attempt 3
    page 118 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p119.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p119.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p119.jpg, attempt 3
    page 119 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p120.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p120.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p120.jpg, attempt 3
    page 120 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p121.jpg, attempt 1
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p121.jpg, attempt 2
    Server error (503) on Prestige Holdings Limited Annual Report 2024_p121.jpg, attempt 3
    page 121 failed: failed after 3 attempts (timeouts/errors)
OK (3647.5s)
[349/431] Republic Financial Holdings Limited - Financial Highlights for the 2nd Quarter ended March 31st, 2026.pdf... OK (43.1s)
[350/431] Republic Financial Holdings Limited - Notice of Appointment of President and CEO (PR) dd 30.01.2026.pdf... OK (21.5s)
  -- checkpoint saved (665 total results so far)
[351/431] Republic Financial Holdings Limited - Notice of Interim Dividend Payment (Cover Letter) dd 29.01.2026.pdf... OK (21.2s)
[352/431] Republic Financial Holdings Limited - Notice of dividend payment (Cover Letter) dd 02.05.2025.pdf... OK (21.8s)
[353/431] Republic Financial Holdings Limited - Notice of dividend payment (Cover Letter) dd 31.07.2025.pdf... OK (21.2s)
[354/431] Republic Financial Holdings Limited - Notice of dividend payment (Cover letter) dd 01.02.2024.pdf... OK (21.2s)
[355/431] Republic Financial Holdings Limited - Notice of trading in shares (Cover letter) dd 07.02.2024.pdf... OK (21.2s)
[356/431] Republic Financial Holdings Limited - Shareholdings Report for the 2nd Quarter ended March 31st 2024.pdf... OK (21.9s)
[357/431] Republic Financial Holdings Limited - Shareholdings Report for the 2nd Quarter ended March 31st 2025.pdf... OK (21.3s)
[358/431] Republic Financial Holdings Limited - Shareholdings Report for the 3rd Quarter ended June 30, 2025.pdf... OK (21.3s)
[359/431] Republic Financial Holdings Limited - Top Ten Shareholders as at December 31st, 2023.pdf... OK (21.6s)
[360/431] Scotiabank Trinidad and Tobago Limited - Notice of Annual General Meeting dd11.02.2025.pdf... OK (21.5s)
  -- checkpoint saved (675 total results so far)
[361/431] Scotiabank Trinidad and Tobago Limited - Notice of Annual Meeting (Press Release) dd 28.01.2026.pdf...     Server error (502) on Scotiabank Trinidad and Tobago Limited - Notice of Annual Meeting (Press Release) dd 28.01.2026_p1.jpg, attempt 1
    Server error (502) on Scotiabank Trinidad and Tobago Limited - Notice of Annual Meeting (Press Release) dd 28.01.2026_p1.jpg, attempt 2
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Annual Meeting (Press Release) dd 28.01.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (164.6s)
[362/431] Scotiabank Trinidad and Tobago Limited - Notice of Changes in Senior Officers (Release) dd 23.01.2026.pdf...     Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Changes in Senior Officers (Release) dd 23.01.2026_p1.jpg, attempt 1
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Changes in Senior Officers (Release) dd 23.01.2026_p1.jpg, attempt 2
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Changes in Senior Officers (Release) dd 23.01.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[363/431] Scotiabank Trinidad and Tobago Limited - Notice of Interim Dividend Payment dd17.09.2024.pdf...     Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Interim Dividend Payment dd17.09.2024_p1.jpg, attempt 1
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Interim Dividend Payment dd17.09.2024_p1.jpg, attempt 2
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Interim Dividend Payment dd17.09.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[364/431] Scotiabank Trinidad and Tobago Limited - Notice of Retirement of a Director 20.03.2024.pdf...     Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Retirement of a Director 20.03.2024_p1.jpg, attempt 1
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Retirement of a Director 20.03.2024_p1.jpg, attempt 2
    Server error (503) on Scotiabank Trinidad and Tobago Limited - Notice of Retirement of a Director 20.03.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[365/431] Scotiabank Trinidad and Tobago Limited- Notice of Appointment of Senior Officers (PR1) dd 02.04.2026.pdf... OK (21.2s)
[366/431] Scotiabank Trinidad and Tobago Limited- Notice of Appointment of Senior Officers (PR2) dd 02.04.2026.pdf... OK (21.2s)
[367/431] TTNGL_Express_Condensed Financial Statements for the Six Months Ended 30 June 2025.pdf... OK (23.6s)
[368/431] TTNGL_Guardian_Condensed Financial Statements for the Six Months Ended 30 June 2025.pdf... OK (22.6s)
[369/431] The West Indian Tobacco Company Limited - Annual Report 6 copies (Cover Letter) dd 09.04.2025.pdf... OK (20.9s)
[370/431] The West Indian Tobacco Company Limited - Notice of Availability of Annual Report (PR) dd 31.03.2026.pdf... OK (21.4s)
  -- checkpoint saved (685 total results so far)
[371/431] The West Indian Tobacco Company Limited - Notice of Change in Directors (Press Release) dd 17.10.2025.pdf... OK (20.8s)
[372/431] The West Indian Tobacco Company Limited - Notice of Change of Directors (Press Release) dd 22.04.2026.pdf... OK (21.2s)
[373/431] The West Indian Tobacco Company Limited - Notice of Final Dividend 2025 (Press Release) dd 22.04.2026.pdf... OK (21.9s)
[374/431] The West Indian Tobacco Company Limited - Schedule 8 of Director dd 13.08.2025.pdf... OK (42.7s)
[375/431] Trinidad Cement Limited - Change in Credit Arrangements (Cover Letter) dd 29.05.2025.pdf... OK (21.3s)
[376/431] Trinidad Cement Limited - Notice of Availability of Annual Report 2025 (Cover Letter) dd 30.04.2026.pdf... OK (42.5s)
[377/431] Trinidad Cement Limited - Notice of Availability of Annual Report 2025 (Press Release) dd 30.04.2026.pdf... OK (21.1s)
[378/431] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 03.02.2026.pdf... OK (42.7s)
[379/431] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 30.06.2026.pdf...     Server error (502) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 30.06.2026_p1.jpg, attempt 1
    Server error (502) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 30.06.2026_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Cover Letter) dd 30.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (164.7s)
[380/431] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 04.02.2026.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 04.02.2026_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 04.02.2026_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 04.02.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.6s)
  -- checkpoint saved (695 total results so far)
[381/431] Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 30.06.2026.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 30.06.2026_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 30.06.2026_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Change in Credit Arrangements (Press Release) dd 30.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[382/431] Trinidad Cement Limited - Notice of Change in Director (Press Release) dd 30.07.2025.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Change in Director (Press Release) dd 30.07.2025_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Change in Director (Press Release) dd 30.07.2025_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Change in Director (Press Release) dd 30.07.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[383/431] Trinidad Cement Limited - Notice of Change in Operating Model dd 17.04.25.pdf... OK (21.4s)
[384/431] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 03.04.2024.pdf... OK (21.6s)
[385/431] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 03.07.2024.pdf... OK (42.8s)
[386/431] Trinidad Cement Limited - Notice of Change to Executive Management (Cover Letter) dd 07.05.2026.pdf... OK (21.9s)
[387/431] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 03.04.2024.pdf... OK (21.1s)
[388/431] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 03.12.2024.pdf... OK (20.8s)
[389/431] Trinidad Cement Limited - Notice of Change to Executive Management (Press Release) dd 07.05.2026.pdf... OK (21.1s)
[390/431] Trinidad Cement Limited - Notice of Changes to Executive Management (Press Release) dd 03.07.2024.pdf... OK (21.2s)
  -- checkpoint saved (705 total results so far)
[391/431] Trinidad Cement Limited - Notice of Changes to Executive Management (Press Release) dd 06.01.2025.pdf... OK (21.7s)
[392/431] Trinidad Cement Limited - Notice of Final Dividend Payment (Cover Letter) dd 08.07.2024.pdf... OK (21.3s)
[393/431] Trinidad Cement Limited - Notice of Final Dividend Payment (Press Release) dd 08.07.2024.pdf... OK (20.8s)
[394/431] Trinidad Cement Limited - Notice of Publication of 2023 Annual Report (Press Release) dd 26-04-2024.pdf... OK (21.1s)
[395/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Cover Letter) dd 05.05.2025.pdf... OK (21.3s)
[396/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Cover Letter) dd 13.05.2024.pdf... OK (43.3s)
[397/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (PR) dd 27.03.2026.pdf... OK (21.8s)
[398/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 05.05.2025.pdf...     Server error (502) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 05.05.2025_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 05.05.2025_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 05.05.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (104.5s)
[399/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 11.06.2026.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 11.06.2026_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 11.06.2026_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 11.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
[400/431] Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 13.05.2024.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 13.05.2024_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 13.05.2024_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Meeting (Press Release) dd 13.05.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.5s)
  -- checkpoint saved (715 total results so far)
[401/431] Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024.pdf...     Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p1.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p1.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p2.jpg, attempt 1
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p2.jpg, attempt 2
    Server error (503) on Trinidad Cement Limited - Notice of Record Date for Annual Report (Cover Letter) dd 26.04.2024_p2.jpg, attempt 3
    page 2 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (89.1s)
[402/431] Trinidad and Tobago NGL Limited - Annual Report 2024 Cover Letter dd 23.05.2025.pdf... OK (22.5s)
[403/431] Trinidad and Tobago NGL Limited - Notice of Amended Special Dividend Payment Date (PR) dd 04.05.2026.pdf... OK (21.5s)
[404/431] Trinidad and Tobago NGL Limited - Notice of Annual Meeting (Press Release) dd 15.01.2026.pdf... OK (23.6s)
[405/431] Trinidad and Tobago NGL Limited - Notice of Annual Meeting (Press Release) dd 24.10.2024.pdf... OK (22.3s)
[406/431] Trinidad and Tobago NGL Limited - Notice of Appointment of Directors (Press Release) dd 04.09.2025.pdf... OK (21.2s)
[407/431] Trinidad and Tobago NGL Limited - Notice of Appointment of a Director dd 08.02.2024.pdf... OK (20.9s)
[408/431] Trinidad and Tobago NGL Limited - Notice of Change in Auditors (Press Release) dd 24.03.2026.pdf... OK (21.1s)
[409/431] Trinidad and Tobago NGL Limited - Notice of Rescheduled Annual Meeting (Press Release) dd 04.02.2026.pdf... OK (20.8s)
[410/431] Trinidad and Tobago NGL Limited - Notice of Rescheduled Annual Meeting (Press Release) dd 12.02.2026.pdf... OK (23.4s)
  -- checkpoint saved (725 total results so far)
[411/431] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Press Release) dd 12.05.2025.pdf... OK (20.8s)
[412/431] Trinidad and Tobago NGL Limited - Notice of Resignation of Director (Press Release) dd 25.08.2025.pdf... OK (20.9s)

[413/431] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director (Press release) dd 22.11.2024.pdf... OK (20.9s)
[414/431] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director Express Clippings.pdf... OK (22.5s)
[415/431] Trinidad and Tobago NGL Limited - Notice of Resignation of a Director Guardian Clippings.pdf... OK (21.6s)
[416/431] Trinidad and Tobago NGL Limited - Notice of Special Dividend (Press Release) dd 10.04.2026.pdf... OK (21.2s)
[417/431] Trinidad and Tobago NGL Limited - Notice to Shareholders - Accesibility of Annual Report 29.06.2026.pdf... OK (25.5s)
[418/431] Trinidad and Tobago NGL Limited - Submission of 2023 Annual Report  (Cover letter) dd 02.07.2024.pdf... OK (30.6s)
[419/431] Unilever Caribbean Limited - Annual Report 2024 (Cover Letter) dd 30.04.2025.pdf... OK (77.8s)
[420/431] Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Press Release) dd 14.08.2025.pdf...     Server error (503) on Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Press Release) dd 14.08.2025_p1.jpg, attempt 1
    Server error (503) on Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Press Release) dd 14.08.2025_p1.jpg, attempt 2
    Server error (503) on Unilever Caribbean Limited - Notice of 2nd Interim Dividend Payment (Press Release) dd 14.08.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
  -- checkpoint saved (735 total results so far)
[421/431] Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 23.06.2026.pdf...     Server error (503) on Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 23.06.2026_p1.jpg, attempt 1
    Server error (503) on Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 23.06.2026_p1.jpg, attempt 2
    Server error (503) on Unilever Caribbean Limited - Notice of Annual Meeting (Press Release) dd 23.06.2026_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.8s)
[422/431] Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 13.03.2025.pdf...     Server error (503) on Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 13.03.2025_p1.jpg, attempt 1
    Server error (503) on Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 13.03.2025_p1.jpg, attempt 2
    Server error (503) on Unilever Caribbean Limited - Notice of Appointment of Senior Officer (Press Release) dd 13.03.2025_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[423/431] Unilever Caribbean Limited - Notice of Appointment of a Director (Press release) dd 13.06.2024.pdf...     Server error (503) on Unilever Caribbean Limited - Notice of Appointment of a Director (Press release) dd 13.06.2024_p1.jpg, attempt 1
    Server error (503) on Unilever Caribbean Limited - Notice of Appointment of a Director (Press release) dd 13.06.2024_p1.jpg, attempt 2
    Server error (503) on Unilever Caribbean Limited - Notice of Appointment of a Director (Press release) dd 13.06.2024_p1.jpg, attempt 3
    page 1 failed: failed after 3 attempts (timeouts/errors)
FAILED (no text) (44.4s)
[424/431] Unilever Caribbean Limited - Notice of Availability of Annual Report 2024 dd 30.04.2025.pdf...     Server error (503) on Unilever Caribbean Limited - Notice of Availability of Annual Report 2024 dd 30.04.2025_p1.jpg, attempt 1
OK (28.9s)
[425/431] Unilever Caribbean Limited - Notice of Availabilty of Annual Report 2025 (PR) dd 30.04.2026.pdf... OK (20.8s)
[426/431] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Press Release) dd 16.09.2025.pdf... OK (22.1s)
[427/431] Unilever Caribbean Limited - Notice of Divestment in its Laundry Brands (Press Release) dd 27.03.2026.pdf... OK (21.5s)
[428/431] Unilever Caribbean Limited - Notice of Final Dividend Payment 2024 dd 28.03.2025.pdf... OK (20.8s)
[429/431] Unilever Caribbean Limited - Notice of Final and Special Dividend Payment (PR) dd 27.03.2026.pdf... OK (20.8s)
[430/431] Unilever Caribbean Limited - Notice of Resignation of a Director (Press release) dd 16.05.2024.pdf... OK (20.8s)
  -- checkpoint saved (745 total results so far)
[431/431] Unilever Caribbean Limited - Notice of Resignation of a Senior Officer (Press Release) dd 24.12.2024.pdf... OK (20.8s)

Done. 746 files processed via cloud OCR.
  Succeeded: 640
  Failed: 106

In [27]:
# Merge the Cloud OCR results into the existing exchange corpus
for source_name, path in CORPUS_FILES.items():
    if not path.exists():
        continue
    updated_count = 0
    for record in corpora[source_name]:
        if record["filename"] in ocr_results and ocr_results[record["filename"]]:
            record["text"] = ocr_results[record["filename"]]
            record["retrieved_via"] = "cloud_ocr"
            updated_count += 1
    path.write_text(json.dumps(corpora[source_name], indent = 2, ensure_ascii = False), encoding = "utf-8")
    print(f"{source_name}: updated {updated_count} records, saved to {path.resolve()}")

jse: updated 281 records, saved to /home/areas001/Final Project/Final Notebooks/jse_local_pdf_corpus.json
bse: updated 23 records, saved to /home/areas001/Final Project/Final Notebooks/bse_local_pdf_corpus.json
ttse: updated 336 records, saved to /home/areas001/Final Project/Final Notebooks/ttse_local_pdf_corpus.json

In [28]:
# Print a summary of the text extraction results
for source_name in CORPUS_FILES:
    if not corpora.get(source_name):
        continue
    df = pd.DataFrame(corpora[source_name])
    print(f"\n{source_name.upper()} -- final retrieved_via breakdown:")
    print(df["retrieved_via"].value_counts())
    print(f"Average text length: {df['text'].str.len().mean():.0f} characters")

JSE -- final retrieved_via breakdown:
retrieved_via
direct                 2997
cloud_ocr               281
needs_ocr_elsewhere       9
Name: count, dtype: int64
Average text length: 30574 characters

BSE -- final retrieved_via breakdown:
retrieved_via
direct                 123
cloud_ocr               23
needs_ocr_elsewhere      2
Name: count, dtype: int64
Average text length: 79190 characters

TTSE -- final retrieved_via breakdown:
retrieved_via
direct                 874
cloud_ocr              336
needs_ocr_elsewhere     95
Name: count, dtype: int64
Average text length: 21051 characters